### ISSUE TITLE
Custom Map Similar to Breath Companion

### ISSUE THREAD

**Issue by Dealman** [Mapsui/Mapsui#1000]
Sorry if a similar question has been asked already, been at this for a few days now. I wanna preface this question with the fact that this kind of stuff is very new to me, and I'm still trying to figure out how it all works.

Basically what I want to try and do is create something very similar to the Breath Companion app, which uses Mapsui.

I'm struggling real hard to try and figure out how I should approach this, most of the samples I can find are related to using real-world data - mostly available online.

~~From what I can gather, I should use MBTiles? So the last 2 days I've been trying to figure out a workflow for converting a .PNG map into a MBTiles file using QGIS.~~

I can't quite get it to work, there are no errors but the map control is just all white. So I'm kind of confused as to what I'm doing wrong and if this is the proper approach?

If you got any pointers in the right direction or some good reference material I can use, that'd be greatly appreciated.

Closest I've been able to find is [JC2MapViewer](https://github.com/x-cubed/JC2MapViewer), but it seems to be vastly outdated. Though, **FileTileProvider** has peeked my interest. So this is currently what I'm trying to get to work.

Thanks in advance!

**Edit:**

Well, I've made some progress. Currently my tile structure looks like this;
![image](https://user-images.githubusercontent.com/7038067/96386322-614cf000-119a-11eb-94c2-e9354d377a72.png)

For testing purposes I only made 4 zoom levels _(0-3)_. However the zooming is not working as intended, tiles are misplaced and some missing.

Currently this is what I've got;
```csharp
string tileDir = (Environment.CurrentDirectory + @"\TestTiles\ZoomLevels");
var fileCache = new FileCache(tileDir, "jpg");
var fileProvider = new FileTileProvider(fileCache);
var tileSchema = new TileSchema();
tileSchema.Extent = new Extent(0, 0, 256, 256);
tileSchema.Resolutions.Add("0", new Resolution("0", 1));
tileSchema.Resolutions.Add("1", new Resolution("1", 4));
tileSchema.Resolutions.Add("2", new Resolution("2", 9));
tileSchema.Resolutions.Add("3", new Resolution("3", 16));
tileSchema.YAxis = YAxis.TMS;
tileSchema.OriginX = 0;
tileSchema.OriginY = 0;

var tileSource = new TileSource(fileProvider, tileSchema);
var tileLayer = new TileLayer(tileSource);

var map = new Map();
map.Layers.Add(tileLayer);

MyMapControl.Map = map;
```
My immediate assumption is that I'm not setting up the schema correctly. For context all tiles are 256x256 pixels each, they were sliced from a 6144x6144 image.

I sliced them in Photoshop from left to right, top to bottom.

**Comment by pauldendulk** [comment]
Yes, you have to get the schema right and that is not that simple. I can't just give you a few pointers. You could read up on the [specification](https://github.com/mapbox/mbtiles-spec), that is not very hard but take some effort. 

My advice would be to start from the samples and change them in small steps into what you want. You could use the world.mbtiles file as a start which can be seen in the sample under 'Data' -> 'MbTiles'. 
There may be tools to help you with this, but I have not used them recently.

**Comment by Dealman** [comment]
Hey thanks for the reply! Yeah I wasn't able to get the _FileTileProvider_ to work yet, not sure if it's supported by Mapsui either since it's part of BruTiles.

I've been experimenting with MBTiles again a bit after I posted this, found a few resources on how to go about making your own MBTiles from an image - though they sadly forgot some of the more important information.

[QGIS3](https://qgis.org/en/site/) has some new tools for exporting to MBTiles, but last I tried I kept getting an empty 16kb file, so I was certainly doing something wrong.

I've gone through the samples and they were very helpful, just been trying to figure out this MBTile stuff lately - doesn't seem very straight forward because it doesn't seem like this is an intended way for it all to be used.

If I manage to make any progress in the future I'll gladly share it all here in case other people may find it useful. 👍

**Comment by pauldendulk** [comment]
BruTile.Desktop could be used in a Desktop project like WPF, but not on Android and iOS. There is not a lot of code there though so you could use it as a start.

**Comment by Dealman** [comment]
Experimented a bit more with this and was able to make a decent MBTiles using MapTiler after some trial and error. It shows up properly in MapTiler.

I am however unable to get it to show at all in Mapsui, pretty sure one of the culprits is that I have no idea how to work with the resolutions - can't seem to find any good info on that subject either. Been playing around with small and large numbers, but wasn't able to get the map to display even at all.

Tried using the world.mbtiles from the samples, but it only works on one zoom level. Trying to zoom corrupts the tiling.

I think for what I'm trying to do, going back to the ~5 year old version of BruTile _(when it used to have UI.Windows)_ would be easier. Putting this on the backburner for now, it's taking way too much time and I am making no progress whatsoever, this is the current code I've got;

```csharp
/*
NW: 0, 0
NE: 30, 0
SW: 0, -23
SE: 30, -23
*/

var map = new Map();

var tileSchema = new TileSchema() { Name = "Base Layer", YAxis = YAxis.TMS, Format = "png", Extent = new Extent(0, -22.998448, 29.998877, 0.000000), OriginX = 0, OriginY = 0};
tileSchema.Resolutions.Add(0, new Resolution(0, 10));
tileSchema.Resolutions.Add(1, new Resolution(1, 20));
tileSchema.Resolutions.Add(2, new Resolution(2, 30));
tileSchema.Resolutions.Add(3, new Resolution(3, 40));
tileSchema.Resolutions.Add(4, new Resolution(4, 50));
tileSchema.Resolutions.Add(5, new Resolution(5, 60));
tileSchema.Resolutions.Add(6, new Resolution(6, 70));
tileSchema.Resolutions.Add(7, new Resolution(7, 80));
var tileSource = new MbTilesTileSource(new SQLiteConnectionString("Teyvat.mbtiles", true), tileSchema, MbTilesType.BaseLayer);
var tileLayer = new TileLayer(tileSource);

map.Layers.Add(tileLayer);

map.Limiter = new ViewportLimiterKeepWithin() { PanLimits = new BoundingBox(SphericalMercator.FromLonLat(0.0, -23.0), SphericalMercator.FromLonLat(30.0, 0.0)) };

MyMapControl.Map = map;

MyMapControl.Navigator.NavigateTo(new BoundingBox(SphericalMercator.FromLonLat(0.0, -23.0), SphericalMercator.FromLonLat(30.0, 0.0)), Mapsui.Utilities.ScaleMethod.Fill);
```
