### ISSUE TITLE
Pin class should have RotateWithMap property

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1001]
It would be very useful to have a way to rotate icons with the map, e.g. for the case of the icon rotation indicating the movement direction of a vehicle (or similar cases).

A `RotateWithMap` property is available in the `Callout` class, but seems to be missing in the `Pin` class.

**Comment by pauldendulk** [comment]
The RotateWithMap boolean is for that purpose. The comments specifically mention vehicle direction. There is a sample unders 'Tests' 'Symbol rotation and offset'

```csharp
        /// <summary>
        /// When true a symbol will rotate along with the rotation of the map.
        /// This is useful if you need to symbolize the direction in which a vehicle
        /// is moving. When the symbol is false it will retain it's position to the
        /// screen. This is useful for pins like symbols. The default is false.
        /// This mode is not supported in the WPF renderer.
        /// </summary>
        public bool RotateWithMap { get; set; }
```

**Comment by janusw** [comment]
> The RotateWithMap boolean is for that purpose.

You don't say which class this Property belongs to. I searched through the Mapsui source code, and found that you are apparently talking about `Mapsui.Styles.ImageStyle.RotateWithMap`.

It might be that I have even found this before, but it was far from obvious to me that this is applicable to a `Pin`.


> There is a sample unders 'Tests' 'Symbol rotation and offset'

The sample only uses `RotateWithMap` with a `Feature`, not a `Pin`. I'm sure for you this must all be trivial, but for someone who does not know the complete Mapsui code structure by heart, some things are not that obvious.

I found that one can apply the property `RotateWithMap` to a `Pin` like this:
`((SymbolStyle)myPin.Feature.Styles.First()).RotateWithMap = true;`

So yes, I can use this. Thanks for the hint (even though it was rather cryptic).

However, I still think it would be a good idea to add a property `Pin.RotateWithMap`, as a shortcut for the above. This would be analogous to other properties like `Pin.Rotation` or `Pin.Scale` or `Pin.Transparency`, which are all just 'shortcuts' to the underlying SymbolStyle properties. It would make the API more consistent and more intuitive.

**Comment by pauldendulk** [comment]
Sorry, I did not mean to say it was obvious. I was just hoping get through my issues with a quick reply 😁. I thought is was just interesting that the comments mentioned vehicles specifically. I will merge your PR. 

Perhaps the use of the property could also be part of some more prominent samples. Perhaps with 'RotateWithMap = true' as label text.

**Comment by pauldendulk** [comment]
> > I thought is was just interesting that the comments mentioned vehicles specifically.
> 
> Yeah, moving vehicles are probably one of the most frequent use cases for directed pins. Though in my case those are not the typical cars/bikes/scooters, but more like drones & planes ;)

cool!

> > Perhaps the use of the property could also be part of some more prominent samples. Perhaps with 'RotateWithMap = true' as label text.
> 
> I can certainly add that, if you tell me which of the samples you regard as "prominent" :)

I was afraid you would ask that :) Perhaps there should be a specific sample for vehicles since it is a common use case.
