### ISSUE TITLE
MapView.Info is called twice for a single tap on Map Feature element

### ISSUE THREAD

**Issue by geosom** [Mapsui/Mapsui#1002]
Hi.
Looking the samples on Xamarin.form, i noticed with a break point that an event on MapView.Info is called twice for a single tap on map Feature element.
Is it a normal behaviour ?

**Comment by geosom** [comment]
Maybe the same issue as #996

**Comment by geosom** [comment]
On the function subscribed, if the property "Handled" of MapInfoEventArgs object is not set  to true, the event occurs twice.
`e.Handled = true;`

**Comment by pauldendulk** [comment]
I do not fully understand you last comment. You mention 'the function subscribed'. Is that a line in the Mapsui code?

**Comment by geosom** [comment]
I was referring to this function in the sample

```
private void MapView_Info(object sender, UI.MapInfoEventArgs e)
        {
            if (e?.MapInfo?.Feature != null)
            {
                foreach (var style in e.MapInfo.Feature.Styles)
                {
                    if (style is CalloutStyle)
                    {
                        style.Enabled = !style.Enabled;
                        e.Handled = true;
                    }
                }
                mapView.Refresh();
            }
        }
```

**Comment by radderz** [comment]
> I do not fully understand you last comment. You mention 'the function subscribed'. Is that a line in the Mapsui code?

I think he means he added a handler to the MapInfo event on the MapControl which is triggered on a click of the canvas.

might be getting double subscribed somehow.

**Comment by sailman342** [comment]
If you indicate that the event has been handled before any chance to give the hand back to the user interface, it will only fire once !

`        private async void MapInfoAsync(object sender, MapInfoEventArgs e)
        {
            e.Handled = true;
            await RouteLayer.MapInfoAsync(sender, e);
        }`

In my case, if the statement e.handled = true is inserted after the await statement, it is fired twice !

Paul, you definitively have a better wording for that :-)

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is fixed now.
