### ISSUE TITLE
how can i add an icon to a pin ? 

### ISSUE THREAD

**Issue by benabdelkrim** [Mapsui/Mapsui#1003]
how can i add an icon to a pin ?

**Comment by pilotshamn** [comment]
this is what i do

 byte[]  funkIcon = assembly.GetManifestResourceStream(Assembly.GetExecutingAssembly().GetName().Name + $".Images.funk100_50.png").ToBytes();

var tempPin=new Pin(mapView)
                                {
                                    Type = PinType.Icon,
                                    Label = theShip1.theAisObject.VesselName,
                                    Position = new Mapsui.UI.Forms.Position(theShip1.theAisObject.Lat, theShip1.theAisObject.Lon),
                                    Rotation = (float)0, // do the rotation 
                                    Anchor = theShipIconAnchor,//  new Point(0.5, 0.5), // between 0 och 1 
                                    Tag = theShip1.theAisObject.MMSId,
                                    Scale = 1.0f, // 0.1f,
                                    Icon = funkIcon ,
                                    //   IsCalloutVisible = true,
                                };

 mapView.Pins.Add(tempPin);

**Comment by benabdelkrim** [comment]
this ligne not working for me (XAMARIN.FORMS)
byte[] funkIcon = assembly.GetManifestResourceStream(Assembly.GetExecutingAssembly().GetName().Name + $".Images.funk100_50.png").ToBytes(); 
did i forget to use some using ?

**Comment by pauldendulk** [comment]
That line is general code to load a resource, it is not related to Mapsui and a solution should be googleble. Perhaps this can help:
https://stackoverflow.com/a/36185255/85325
