### ISSUE TITLE
Updating to Mapsui 3.0.0-alpha.2 fails

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1006]
@pauldendulk: I have a Xamarin.Forms app that references the currently stable Mapsui version:

```
<PackageReference Include="Mapsui.Forms" Version="2.0.3" />
```

Updating to 3.0.0-alpha.1 works without a problem, but when I try to update to 3.0.0-alpha.2, I get the following errors:

```
Restoring packages for .NETStandard,Version=v2.1...
  GET https://api.nuget.org/v3-flatcontainer/mapsui.geometries/index.json
  GET https://api.nuget.org/v3-flatcontainer/notmapsui/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/mapsui.geometries/index.json 654ms
  NotFound https://api.nuget.org/v3-flatcontainer/notmapsui/index.json 456ms
Resolving conflicts for .NETStandard,Version=v2.1...
Unable to find package Mapsui.Geometries. No packages exist with this id in source(s): nuget local packages, nuget.org
Unable to find package NotMapsui. No packages exist with this id in source(s): nuget local packages, nuget.org
```

**Comment by pauldendulk** [comment]
Just after publishing I realized I had not updated the nuspec, but had no time to fix it. Although I expect errors wrt the svg package. Perhaps this is something different.

**Comment by janusw** [comment]
Sorry, false alarm.

I had been trying to build my own Mapsui nupkg, which apparently did not work out perfectly, and this broken pkg (with the same name) was still lingering in my local cache when I tried to update to the 'real' 3.0.0-alpha.2.

Cleaned up the cache, now updating works fine!

**Comment by janusw** [comment]
> Just after publishing I realized I had not updated the nuspec, but had no time to fix it. Although I expect errors wrt the svg package.

Ah, yes, I actually do see minor problems wrt svg.skia:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(5,5): Error XA2002: Can not resolve reference: `Svg.Skia`, referenced by `Mapsui.Rendering.Skia`. Please add a NuGet package or assembly reference for `Svg.Skia`, or remove the reference to `Mapsui.Rendering.Skia`. (XA2002) (WhatsThisDrone.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(5,5): Error XA2002: Can not resolve reference: `Svg.Skia`, referenced by `Mapsui.UI.Forms`. Please add a NuGet package or assembly reference for `Svg.Skia`, or remove the reference to `Mapsui.UI.Forms`. (XA2002) (WhatsThisDrone.Android)
```

Those are easily worked around, however, by adding the Svg.Skia package to my project explicitly.

**Comment by pauldendulk** [comment]
> Those are easily worked around, however, by adding the Svg.Skia package to my project explicitly.

Yes, that should work. Adding it to the nuspec will add it automatically.

**Comment by janusw** [comment]
> Adding it to the nuspec will add it automatically.

Yeah, hope you can fix that for the next release. Thx!

**Comment by inforithmics** [comment]
I fixed the nuspec in the Pull Request updating to SkiaSharp 2.80.2

https://github.com/Mapsui/Mapsui/pull/1015
