### ISSUE TITLE
ASP View Sample - truck dispatch

### ISSUE THREAD

**Issue by papyr** [Mapsui/Mapsui#1007]
Hello, can you please share some insight on how to use this in an ASP web application like an taxify or Truck Dispatch scenario

**Comment by pauldendulk** [comment]
Mapsui can not be used in a web application. It is for desktop and Xamarin mobile. At some point it might support Blazor.

**Comment by radderz** [comment]
@papyr I'd recommend you look up a javascript map framework. If you need it to be an open source website map I'd suggest leaflet which offers similar functionality using javascript.

Once blazor supports SkiaSharp properly this may be usable within a webassembly website but that could be a year or two away at this rate!
