### ISSUE TITLE
ShapeFile in Xamarin.Forms

### ISSUE THREAD

**Issue by benabdelkrim** [Mapsui/Mapsui#1009]
can i use a shapeFile as a layer into Xamarin.Forms ?

**Comment by pauldendulk** [comment]
Unfortunately this is not supported. At some point we hope to migrate to NTS and use their shapefile reading functionality https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile.

In the meantime you could try to use NTSs shapefile functionality, but you will need to convert the geometies from NTS to Mapsui.Geometries. 

Another option is to try to port Mapsui's desktop Shapefile functionality to .NETStandard.

**Comment by benabdelkrim** [comment]
thank you paul for your help

**Comment by benabdelkrim** [comment]
this solution not working in Xamarin.forms ! can you propose an other solution ?

Thanks in advance.

**Comment by pauldendulk** [comment]
Which of the two solutions is not working?

Perhaps your best option is to go with NTS ShapeFile. My advice is to try to use that library in Xamarin.Forms without using Mapsui. The file access might be an issue. Perhaps the library can use a Stream as input. Accessing the file may need platform dependent code. Once you have that working try to integrate it in Mapsui.
