### ISSUE TITLE
Black screen part.

### ISSUE THREAD

**Issue by iamnotstalinlab** [Mapsui/Mapsui#1010]
Guys, I want your help. I am using ViewPager in Xamarin.Android and I facing black screen part, when I change fragment from MapsUI. It is look like this https://t.me/JosephStalinCommunity/717. And I don't know what I should to do, for fix it. I used Google Maps fragment before mapsui and didn't facing something like black screen. I tried to fix it whole week, but I didn't. Google does not give me something good for that.

**Comment by radderz** [comment]
You are going to need to give some more information, could you upload a reproduction zip/repo?

**Comment by iamnotstalinlab** [comment]
What do you mean? Code? How much code do you want to see?) If all code will be good, such it located here: https://gitlab.com/iamnotstalinlab/josephstalinapp. 

Problem code was located in this module https://gitlab.com/iamnotstalinlab/josephstalinapp/-/blob/cb095c669b380f8398a54a10b42acd05cad0c02b/JosephStalinForTheProletarians/MainFragments/mapsFragment.cs#L159 on this line. 

I used ViewPager for showing fragments. One fragment gets black screen, after I swithed from MapsFragment (with MapsUI). If it will be good, I will be little happy)
