### ISSUE TITLE
Tooltip for feature on map WPF

### ISSUE THREAD

**Issue by anushabasavaraj92** [Mapsui/Mapsui#1011]
Is there a way to add tooltip to the features displayed on the map instead of label? 
WPF provides an event for mouse enter which can be used to display tooltip. But, the argument of the event handler doesn't provide the GetMapInfo() function as provided by the mouse click event arguments in WPF.

**Comment by pauldendulk** [comment]
Perhaps you could take a look at Callout, otherwise you have to create something like this yourself by call GetMapInfo on move move.
