### ISSUE TITLE
SkiaSharp went Blazor

### ISSUE THREAD

**Issue by YordanYanakiev** [Mapsui/Mapsui#1012]
https://devblogs.microsoft.com/aspnet/unified-ui-mobile-blazor-bindings-preview-5/

Just found out that SkiaSharp could be used into Blazor, and probably this opens the road for Mapsui to go Web.

**Comment by radderz** [comment]
@YordanYanakiev that isn't what is stated one there.

That preview is only for the Mobile bindings for use within Xamarin mobile apps. Skia isn't supported yet in Blazor for web

**Comment by YordanYanakiev** [comment]
> @YordanYanakiev that isn't what is stated one there.
> 
> That preview is only for the Mobile bindings for use within Xamarin mobile apps. Skia isn't supported yet in Blazor for web

Ahhh.. right. pity, I were overexcited probably and missed the worst part :|

**Comment by pauldendulk** [comment]
Mapsui now has a Blazor MapControl.
