### ISSUE TITLE
App crash because of SkiaSharp version for Mapsui 2.0.3

### ISSUE THREAD

**Issue by johnhs91** [Mapsui/Mapsui#1013]
Hello

Crash issue with SkiaSharp and maybe Mapsui.

Before I used Mapsui source (2.0.0-beta.30), and skiasharp 1.68.1.1. This had a bug as the map sometimes freeze 100%.
After updating to 2.0.3 it fixed the freeze problem. (Updated SkiaSharp aswell because of this)
But after this update, the app started to crash. For what I belive is a bug in SkiaSharp.
But since I can't find source for mapsui 2.0.3, I had to use nuget instead, and it require SkiaSharp 1.68.2.1+, since this update.

I've tried to reproduce the error myself alot of times, but it's hard. Got it once, while I didn't debug sadly.
But it happends like 10+ times a day. (500+ users)

All info I get of the crash is this:

Error:
Application.Main (System.String[] args)
SIGABRT: Cannot access a disposed object. Object name: 'SKGLView'.

Only stacktrace I get is this:
NSObject.get_SuperHandle ()
GLKView.Display ()
SKGLViewRenderer+<>c__DisplayClass4_0.<SetupRenderLoop>b__1 ()
NSAsyncActionDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

My best idea is it's a SkiaSharp bug. But impossible to fix for me, since I can't update the version.
Only thing that use SkiaSharp is Mapsui.

Any idea or help would be awesome!

**Comment by johnhs91** [comment]
If I search specific on SKGLView it's about SkiaSharp. But can this be caused by Xamarin.Forms version maybe?
My knowledge of Xamarin.forms rendere isn't good. So I could be wrong in believing it's about SkiaSharp ?

**Comment by johnhs91** [comment]
Didn't help to update XF to latest. Still got same crash.

**Comment by johnhs91** [comment]
Looks like it's related to this:
https://github.com/xamarin/Xamarin.Forms/issues/11319

So looks like it's a SkiaSharp bug.

**Comment by johnhs91** [comment]
So it happens at hot reload as writting in above issue.
I can reproduce by making my app go to sleep, wait a while. Then startup.
So it get disposed in background, and when opening again, it crash.

It's a SkiaSharp error, but can't see any changes to the renderer, so I'm really lost.

**Comment by pauldendulk** [comment]
The source of Mapsui 2.0.3 is in the release/2.0 branch https://github.com/Mapsui/Mapsui/tree/release/2.0

The alpha release has a newer version of SkiaSharp, could it be fixed there?

**Comment by johnhs91** [comment]
I found 2.0.3 source, in tags. I'm not a github expert, so took some time.

I'm currently trying to build everything with source code of mapsui 2.0.3 and Skiasharp 1.68.3 source code.
To see if I get better information.

I've been looking at SkiaSharp's renderer that crash, and the few changes from 1.68.1.1 till 2.80.x can't create these crashes. So I'm abit confused atm.

Could try just to update to alpha, even though I'm not happy by using alpha versions. Did you change alot from 2.0.3 till 3.0.0 ?

**Comment by pauldendulk** [comment]
The alpha would be just for testing. If the newer skiasharp version fixes your problem then I will upgrade v2 as well.

**Comment by johnhs91** [comment]
So I've searched some more.
And found out the problem is specific in line 60 in here:
https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKGLViewRenderer.cs

Meaning it's on app coming foreground, it run a renderer once. (Oneshot) and because control have been disposed in background, it crash here.
This have always been like this in SkiaSharp, and is so in newest version, so is it posible some lifecycle of mapsui have been changed, so it sometimes don't recreate control before redraw?

Problem here is, it happens rarely, so hard just to check if fixed.
Wish I had a way to check if disposed, then ill just add it in skiasharp.

**Comment by pauldendulk** [comment]
> So I've searched some more.
> And found out the problem is specific in line 60 in here:
> https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKGLViewRenderer.cs
> 
> Meaning it's on app coming foreground, it run a renderer once. (Oneshot) and because control have been disposed in background, it crash here.

Thank you for your detailed analysis.

> This have always been like this in SkiaSharp, and is so in newest version

Did you test this in Mapsui 3.0.0-alpha.3, using SkiaSharp 2.80.2?

**Comment by johnhs91** [comment]
No, took me 10 hours to get more analyse data from build with source code from both.

I can try to set it up with latest alpha mapsui and skia 2.80. And test rest of the day.
But not even secure to get the crash in that time

**Comment by pauldendulk** [comment]
> No, took me 10 hours to get more analyse data from build with source code from both.

Which 'both'?

**Comment by johnhs91** [comment]
I mean I build my app with source code from both SkiaSharp source and Mapsui source. (Instead of nuget)
So I was able to get better debug information.

**Comment by pauldendulk** [comment]
Now that v4 is out the situation is completely different. I will close this.
