### ISSUE TITLE
MyLocationLayer should have a way to indicate viewing direction

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1019]
The class `MyLocationLayer` currently has a property called `Direction`, which apparently means the direction of movement (since the corresponding arrow icon is only shown if the property `IsMoving` is true).

In general, one could distinguish two kinds of directions:
1. Movement direction (related to movement of user location).
2. Viewing direction (related to device orientation).

It would be great if Mapsui's API had the capability of setting both directions independently (and displaying them on the map), e.g. by introducing a new property `ViewingDirection` (or similar).

The current way of displaying a moving user with an arrow is fine, but on top of that one would need something cake-segment like to indicate the viewing direction (similar to what Google Maps does?).

One could use a default value of `ViewingDirection = -1` to indicate that no viewing direction should be shown (while values from 0 to 360 would indicate a valid viewing direction in degrees wrt North direction). Alternatively one could have a separate boolean property 'ShowViewingDirection' to show or hide the view-direction indicator.

For backwards compatibility, one could leave the `Direction` property as it is, or rename it to `MovementDirection` for the sake of clarity.

**Comment by pauldendulk** [comment]
Fair. I have worked with apps with this functionality and found it helpful. I think it was in OsmAnd, an Android app. Perhaps you can check how it functions there. 

This is not something I will find time for but perhaps someone else.

General note, try to implement this in a way that does not depend on Xamarin.Forms. Use the lower level functionality so it could work on MAUI or Blazor some day.

**Comment by janusw** [comment]
> Fair. I have worked with apps with this functionality and found it helpful. I think it was in OsmAnd, an Android app. Perhaps you can check how it functions there.

Yeah, right, OsmAnd has it as well, and it looks very similar to what Google Maps does.

I might try to go ahead and implement this, but I cannot make any promises on that (lots of time constraints on my side right now).

**Comment by charlenni** [comment]
@janusw You don’t have to do so much. 

I assume, that it doesn’t make any sense to add your suggested feature to the the arrow when moving. So you want it only for cases, where you are not moving.

Than the only thing you have to do is to add the possibility to change the bitmap of the still icon. Change the bitmap to a bitmap, that contains the center point and your viewing angle. Now you could move this viewing angle in each direction you want with the Direction property.

Or you could add a third icon for this with a second flag (beside IsMoving).

**Comment by janusw** [comment]
> I assume, that it doesn’t make any sense to add your suggested feature to the the arrow when moving. So you want it only for cases, where you are not moving.

Well, that's not fully true. For some applications it might be enough to have a viewing-direction indicator when the user is not moving. But, generally speaking, it would be inconsistent to leave it out when there is movement.

Just imagine a user on a train, looking out the window. The location is moving rapidly, but still one might be interested in the viewing direction.

> Than the only thing you have to do is to add the possibility to change the bitmap of the still icon. Change the bitmap to a bitmap, that contains the center point and your viewing angle. Now you could move this viewing angle in each direction you want with the Direction property.

This might be the easiest to implement, but I don't think it's sufficient (see above). The combination of the movement indicator with a view-direction indicator should be possible.

So, yes, we'd need an additional icon that can be overlayed with the movement indicator (arrow or dot), an additional direction property (e.g. `ViewingDirection` as suggested above) and possibly a new flag to specify whether the viewing direction should be displayed.
