### ISSUE TITLE
how to get longtap event?

### ISSUE THREAD

**Issue by sebseyres** [Mapsui/Mapsui#1020]
Hi, 
Is it a way to have longTap event in mapsui android?
I get the tap event like this  : 
mapControl.NativeMapControl.Info += Map_InteractAsync;
but I don't know how to catch the MapLongClickedEventArgs (https://mapsui.com/api/Mapsui.UI.Forms.MapLongClickedEventArgs.html)

Regards
Seb

**Comment by benabdelkrim** [comment]
mapView.MapLongClicked += (sender, e) => {
                infoo.Text = "Long click";
};
