### ISSUE TITLE
show label pin in mapView ?

### ISSUE THREAD

**Issue by benabdelkrim** [Mapsui/Mapsui#1021]
as we know we can show a label of a feature (point,polygon...) but i want to show a label text to a pin object ?

**Comment by memsom** [comment]
Can you use the Callout? This exists at least on the Xamarin.Forms version of the codebase. You have a lot of ability to customise the Callout, so you can make it look more like a label if you want to.

**Comment by pauldendulk** [comment]
Labels are also supported. See the samples

![image](https://user-images.githubusercontent.com/963462/107757679-257bfe80-6d26-11eb-952a-122f5a06b83f.png)
