### ISSUE TITLE
SQLite exception in MbTilesTileSource

### ISSUE THREAD

**Issue by erp931117** [Mapsui/Mapsui#1022]
Hi, I'm really new and I'm trying to reproduce the example using the world.mbtiles file, the problem is that when starting debugging it throws an exception "Could not open database file /MbTiles/world.mbtiles", I have the following property configured public static string MbTilesLocation {get; set; } = @ "." + Path.DirectorySeparatorChar + "MbTiles"; What should I do to indicate the path of the world.mbtiles file ???

**Comment by pauldendulk** [comment]
So, if I understand you correctly, you have a working code sample, and you have your own code that is not working, and now you are asking what the difference is between your code and the sample code?

Is your mbtiles file properly deploying to the device? In the samples the mbtiles is an embedded resource (set the 'Build Action' of the file to 'Embedded Resource') which is then copied to a location on the device.

**Comment by erp931117** [comment]
Thanks, after analyzing the code of the examples in detail I managed to make everything work well, thanks for such a good project, you are an example to follow.
