### ISSUE TITLE
Question : Can i render map in codebehinde withhout mapconrol

### ISSUE THREAD

**Issue by pilotshamn** [Mapsui/Mapsui#1024]
Hello
I want (in WPF) to create a map and render it in codebehind without any visual control i xaml and then render it to a bitmap or SKSurface. Is that possible.?

**Comment by pauldendulk** [comment]
> render it in codebehind without any visual control i xaml

Mapsui's main map renderer uses SkiaSharp and does not depend on xaml or ui controls. The main renderer renders to a SKSurface it is also possible to render to a bitmap.

**Comment by pilotshamn** [comment]
Thanks for the answer sounds good maspsui is really great. is there any samples of this method?

**Comment by pilotshamn** [comment]
Hi i tried the below code  but the map is not rendered only the widgets?  

I have an wpf xaml file like this
<Window
    x:Class="WpfMapsuiCore.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:WpfMapsuiCore"
      xmlns:wpf="clr-namespace:SkiaSharp.Views.WPF;assembly=SkiaSharp.Views.WPF"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="MainWindow"
    Width="800"
    Height="450"
    mc:Ignorable="d">
    <Grid>
        <wpf:SKElement x:Name="BitmapHost" PaintSurface="OnPaintCanvas" />
    </Grid>
</Window>


and codebehind
public partial class MainWindow : Window
    {
        static Mapsui.Map map; // = new Mapsui.Map { CRS = "EPSG:3857", Transformation = new MinimalTransformation() };
       static  public Mapsui.Geometries.Point centerOfSandhamn = new Mapsui.Geometries.Point(18.9108, 59.2879);
        public Mapsui.Geometries.Point centerOfRadarLatLon = new Mapsui.Geometries.Point(59.28795, 18.91875); //lat long
        static public Mapsui.Geometries.Point centerOfRadarLonLat = new Mapsui.Geometries.Point(18.91875, 59.28795); //long lat
        public MainWindow()
        {
           InitializeComponent();
            map = CreateMap();
        }
     public static Map CreateMap()
        {
            var map = new Map
            {
                CRS = "EPSG:3857",
                Transformation = new MinimalTransformation()
            };
            var attribution = new BruTile.Attribution("© OpenStreetMap contributors", "http://www.openstreetmap.org/copyright");
            var tileSourceStreet = new HttpTileSource(new GlobalSphericalMercator(), "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", new[] { "a", "b", "c" }, name: "OpenStreetMap", attribution: attribution);
            var tileLayerStreet = new TileLayer(tileSourceStreet);
            map.Layers.Add(tileLayerStreet);
            map.Widgets.Add(new ScaleBarWidget(map) { TextAlignment = Mapsui.Widgets.Alignment.Center, HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Center, VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Top });
            map.Widgets.Add(new Mapsui.Widgets.Zoom.ZoomInOutWidget { MarginX = 20, MarginY = 40 });
            var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfRadarLonLat.X, centerOfRadarLonLat.Y);
            map.Home = n => n.NavigateTo(sphericalMercatorCoordinate, map.Resolutions[15);
}

 private void OnPaintCanvas(object sender, SKPaintSurfaceEventArgs e)
        {
            SKCanvas canvas = e.Surface.Canvas;
            int width = e.Info.Width;
            int height = e.Info.Height;
   var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfSandhamn.X, centerOfSandhamn.Y);
            var viewport = new Viewport { Center = sphericalMercatorCoordinate, Width = width, Height = Height, Resolution = 20 };
          //  var viewport = new Viewport { Center = new Mapsui.Geometries.Point(100, 100), Width = width, Height = Height, Resolution = 20 };
            new MapRenderer().Render(canvas, viewport, map.Layers, map.Widgets);
        }

**Comment by pauldendulk** [comment]
The WPF MapControl writes to an SKSurface. So, when you run Mapsui.Samples.Wpf you are looking at a map rendered to SKSurface. Here is the source code:

https://github.com/Mapsui/Mapsui/blob/938570cc3245cfd09d9068174ea07f123e2cef7a/Mapsui.UI.Wpf/MapControl.cs#L493

What is your use case?

**Comment by pilotshamn** [comment]
Thanks a lot i will have a look at the source.
I have written a c# inrterface to a marine radarantenna using skiasharp to do the grafics (works really good) now i would like to have  an map underlay  with the radar, and Iwas thinking of mapsui. Actually the ideal would bee if one can use S-57 verctormaps but as i have read is not possible with mapsui, so i will go for OSM. I can send you som screendumps if you want.
Regards Peder

**Comment by pilotshamn** [comment]
Hi Again 
I think i understod the code and did like this
I create a map and try the call the  renderer from a button: MapRenderer().Render(canvas, viewport, map.Layers, map.Widgets);
if i do not have a MapControl in xaml and assignes the map created in code to  MapControl.Map = map; 
the only thing that gets rendered are the widgets. When I get te map rendered it is blurred?
Any idea of I am doing wrong?

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
