### ISSUE TITLE
How to horizontally repeat map of open street map?

### ISSUE THREAD

**Issue by aliveho** [Mapsui/Mapsui#1025]
Hi,

I am making the shipping route program by Mapsui WPF.
I'd like to horizontally repeat all tiled maps from Open Street Map.

![Repeated_Map](https://user-images.githubusercontent.com/5700640/100455672-6f2f5280-3102-11eb-8304-6198892aaf6a.png)

Please let me know how to do that.

Thanks

**Comment by pauldendulk** [comment]
This is not supported.

It is on the which list.
https://github.com/Mapsui/Mapsui/issues/906

You can vote by adding a thumbs up here
https://github.com/Mapsui/Mapsui/issues/518
