### ISSUE TITLE
Can add net framework 4.7 support for mapsui 3?

### ISSUE THREAD

**Issue by IOL0ol1** [Mapsui/Mapsui#1026]
win10 default net framework is 4.7.

**Comment by IOL0ol1** [comment]
Hi, I'm using mapsui 2. I want update to mapsui 3, but it‘s not supported net472.
I try to compile it by myself.
I'd like to ask why not distinguish between platform publishing nugets?
like this:
**Mapsui** (for all)
├Mapsui.dll
├Mapsui.Geometries.dll
└Mapsui.Rendering.Skia.dll

**Mapsui.Wpf**  (depend on Mapsui)
├Mapsui.Render,Xaml.dll
└Mapsui.UI.Wpf.dll

**Mapsui.Uwp**  (depend on Mapsui)
└Mapsui.UI.Uwp.dll

**Mapsui.iOS**  (depend on Mapsui)
└Mapsui.UI.iOS.dll

**Mapsui.Mono**  (depend on Mapsui)
└Mapsui.UI.Android.dll

**Comment by IOL0ol1** [comment]
i have pull #1029 for update a old csproj file.
Perhaps can later support multiple .Net versions by modify     
**&lt;TargetFramework&gt;net48&lt;/TargetFramework&gt;**     
to     
**&lt;TargetFrameworks&gt;net472;net48&lt;/TargetFrameworks&gt;**  in .csproj file

**Comment by memsom** [comment]
From what I could tell, some of the libs in the dependency tree are using incompatible frameworks. I migrated my fork to use the latest of everything about a week before I noticed it was also done in origin/master, and I can tell you - it was not possible to use any framework prior to 4.8 and make it all compile and be happy without a lot of juggling. It wasn't worth it for me as I just wanted to use the Xamarin Forms parts.

**Comment by IOL0ol1** [comment]
> From what I could tell, some of the libs in the dependency tree are using incompatible frameworks. I migrated my fork to use the latest of everything about a week before I noticed it was also done in origin/master, and I can tell you - it was not possible to use any framework prior to 4.8 and make it all compile and be happy without a lot of juggling. It wasn't worth it for me as I just wanted to use the Xamarin Forms parts.

So there is no way to continue using mapsui 3 with net472.:pleading_face:

**Comment by IOL0ol1** [comment]
@memsom 

I used in WPF.
I am tried to publish mapsui 3 supported by net462, and the effect was fine at my fork.

**So i think the library file should keep the runtime version as low as possible.**
Some projects (like Mapsui.Rendering.Skia) refer to third-party (net462) libraries, so the lowest version of the  Mapsui.Rendering.Skia was locked to net462.

In addition, I found that it might not be necessary to consolidate files from multiple platforms into a single nuget package,
so I tried to recompile the release as I thought. Of course, splitting nuget package should not be discussed in this issue.
nuget search "Net45.Mapsui"  (some mistake on publish, It's should be call Net462.Mapsui)

**Comment by memsom** [comment]
@IOL0ol1  well, my fork I wanted it to use the latest version of every dependency, so maybe that is more extreme. But it getting pulled to 4.8 was the simplest way to achieve that. The main version, I can't speak for the developers. I don't know why it was pushed to 4.8.

**Comment by IOL0ol1** [comment]
[Update] I have publish nuget package "Mapsui3".
If anyone needs it. **Enable pre release included**  when search nuget.
There is basically no modification of the code, just changes to the project file and how the package is built

**Comment by pauldendulk** [comment]
This is not something I would like to invest in. Also, there is now a workaround with mapsui3.
