### ISSUE TITLE
Do I need to create a map and location application?

### ISSUE THREAD

**Issue by erp931117** [Mapsui/Mapsui#1028]
Hi, a friend has asked me to help develop a mapping application. I have managed to install and display a map of my region with Mapsui 2.0. My question is this:
Do I need to show the location with the GPS and update the route as the user moves? Is Mapsui sufficient for this or do I need something else? Thank you.

**Comment by memsom** [comment]
Which platform is the application targeting? For me, I'm using Xamarin.Forms on  mobile and the MyLocation layer sort of does all I need. But if you use a desktop platform, you will need to feed the GPS info in to the engine to make it work I think.

**Comment by erp931117** [comment]
Thank you. I'm using Xamarin.Forms on mobile too.

**Comment by pauldendulk** [comment]
Xamarin.Forms supports this. It this functionality is not sufficient you could create some functionality like this yourself. Perhaps using Mapsui's code as a basis.
