### ISSUE TITLE
The new version of Callout cannot be used alone,old version can do it.

### ISSUE THREAD

**Issue by tangxiaodao** [Mapsui/Mapsui#1033]
The previous version of Callout can be used alone, for example, when drawing a line or polygon, add Callout to the end node of line or polygon, and the Callout will display the end of the line.And the current version can only be used by Pin.

**Comment by pauldendulk** [comment]
I don't think I can look into this soon.

**Comment by charlenni** [comment]
The new callout is only a style (see [here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Styles/CalloutStyle.cs)), which could be used by any Feature of Mapsui. So you have to add this style to your object.
