### ISSUE TITLE
Loading GeoTiff file to Mapsui mapcontrol in WPF

### ISSUE THREAD

**Issue by anushabasavaraj92** [Mapsui/Mapsui#1036]
Can the Geotiff file be used as the tile provider for mapsui map? If yes, kindly share an example.

**Comment by pauldendulk** [comment]
Take a look at GeoTiffProvider.cs.

**Comment by anushabasavaraj92** [comment]
Kindly give an example of how to use it as a layer.

**Comment by pauldendulk** [comment]
There is the GeoTiffProviderTests.cs. Once the GeoTiffProvider is move from Mapsui.Desktop to Mapsui and GeoTiffProviderTests from Mapsui.Desktop.Test to Mapsui.Tests it will be visuble in the samples under 'Tests' dropdown.

**Comment by anushabasavaraj92** [comment]
I was able to successfully load the file. But, it's taking longer time to read the tiff file due to its size everytime the application is loaded. Is there a way to cache the file stream which might help in reducing the load time?

**Comment by pauldendulk** [comment]
In that case you might want to look for a tool that can turn the tiff into an .mbtiles format. I used these years ago, I do not know what the best tool for this would be today.
