### ISSUE TITLE
Rendering map from postgis osm data

### ISSUE THREAD

**Issue by DavisMillier** [Mapsui/Mapsui#1038]
Hi , I want to know, is it possible for this library to connect to the PostGis database and load and render maps based on the user screen? Exactly like what happens on sites.
For a long time I have been looking for a way to render and display data within client software(C# wpf application or Qt desktop application) using a local geographic database, similar to what the Openstreetmap site displays but offline using data from the local database(postgis with osm data).
Thanks

**Comment by pauldendulk** [comment]
This is not supported. I may be possible to create a Mapsui IProvider using the SharpMap postgis provider.
