### ISSUE TITLE
How to make Callout object react on TouchStart/TouchEnd/TouchMove events

### ISSUE THREAD

**Issue by eltomek** [Mapsui/Mapsui#1039]
Can I somehow make Callout object react on TouchStart/TouchEnd/TouchMove events? I'd like to make a feature that the user creates a route on the map by tapping onto a map and each map touch creates a new node represented by a dot/circle (a Callout maybe?) that connects with a line with a previous one. That's pretty simple to do but I want the user to be able to move the existing node by simply touching and dragging it. While he drags the node, I need the line connection to be re-drawn. I don't really know where to start with because I can see none of the objects that I could use as a visual representation for a node support OnTouch/OnPress/OnRelease events. Only MapView and MapControl seem to support them but is there any way to identify a Callout that has been clicked?

**Comment by sailman342** [comment]
I didn't use the callout, I created a feature from a picture

```
            Feature feature = new Feature
            {
                Geometry = wgs84Point,
                ["Type"] = "Pin",
                ["Label"] = labelArg,
                ["Address"] = addrArg,
                ["Id"] = IdArg,
                ["Coord"] = wgs84Point,
                ["TrakIndex"] = trakIndex,
                ["Waypoint"] = null
            };

            feature.Styles.Add(CreatePinStyle(imagePath, scale));
```
I put these features on a separate layer ....

And you connect to the mapTouchEvents ...

```
        internal void MapTouchStarted(object sender, TouchedEventArgs e)
        {
            if (EditionManager != null)
            {
                if (WaypointsFeatures.Count > 0)
                {
                    System.Diagnostics.Debug.WriteLine($" touch start{ e.ScreenPoints.Count} {e.ScreenPoints[0].X} {e.ScreenPoints[0].Y} ");

                    MapInfo info = MainPage.AppMainPage.RBMap.MapView.GetMapInfo(e.ScreenPoints[0]);
                    if (info.Feature != null)
                    {
                        // only waypoints pins are draggable !
                        if (info.Feature["Type"] != null && (string)info.Feature["Type"] == "Pin" && info.Feature["Waypoint"] != null)
                        {
                            e.Handled = true;

                            waypointFeatureDraggingStarted = true;
                            draggedWaypoint = (Waypoint)info.Feature["Waypoint"];
                            // we get a copy of the feature (in the datasource ?) 
                            // so get the original one !
                            draggedFeature = WaypointsFeatures[draggedWaypoint.Index];
                            //draggedFeature = (Feature)info.Feature;
                        }
                    }
                }
            }
    
```    
and so on with the move and end events ... :-)

**Comment by eltomek** [comment]
> I didn't use the callout, I created a feature from a picture
>                     MapInfo info = MainPage.AppMainPage.RBMap.MapView.GetMapInfo(e.ScreenPoints[0]);
>                     if (info.Feature != null)
>                     {
>                         // only waypoints pins are draggable !
>                         if (info.Feature["Type"] != null && (string)info.Feature["Type"] == "Pin" && info.Feature["Waypoint"] != null)
>                         {
>                             e.Handled = true;

Thank you, that did the job. Only one needs to remember to set 
`IsMapInfoLayer = true`
for the layer with Features one wants to detect.
