### ISSUE TITLE
Calculating distance between Points returns values higher by approx 60%

### ISSUE THREAD

**Issue by eltomek** [Mapsui/Mapsui#1041]
I'm trying to calculate the distance between 2 Points (with SphericalMercator coords and being correctly displayed on the map).
With both available methods to calculate it:

1. `distance = myPoint.Distance(otherPoint);`
2. `distance = Algorithms.Distance(myPoint, otherPoint);`
I get values of approx 60% higher than their real geographical positions (confirmed with Google Maps measuring tool). 
I tried converting them:
```
Distance dist = new Distance(distance);
Debug.WriteLine($"Distance km: {dist.Kilometers}");
```
but seems just like `distance` is in meters as `dist.Kilometers` simply prints `distance`/1000.

**Comment by sailman342** [comment]
While you are on that, why don't you try mine and tell me if it is ok ?

```
        public static double DistanceInMeters(Point pt1, Point pt2)
        {
            double retVal = 40000000.0;
            if (pt1 != null && pt2 != null)
            {
                double deltaLat2m = (pt1.Y - pt2.Y) * 10000000.0 / 90.0;
                deltaLat2m *= deltaLat2m;
                double deltaLon2m = (pt1.X - pt2.X) * Math.Cos((pt1.Y + pt2.Y) * Math.PI / 360.0) * 10000000.0 / 90.0; // divide by 2 and multiply by 2Pi is Pi
                deltaLon2m *= deltaLon2m;
                retVal = Math.Sqrt(deltaLat2m + deltaLon2m);
            }
            return retVal;
        }
```

**Comment by eltomek** [comment]
> 
> 
> While you are on that, why don't you try mine and tell me if it is ok ?

Sure, no problem. The value displayed near Toronto is divided by 1000.

![image](https://user-images.githubusercontent.com/3283040/103541527-da0b4080-4e9b-11eb-858a-1a43d9f95819.png)

![image](https://user-images.githubusercontent.com/3283040/103541618-01620d80-4e9c-11eb-8085-9addc3865fe4.png)

**Comment by sailman342** [comment]
Are you writing a navigation application, this is what I am doing right now ! For pleasure :-)

**Comment by eltomek** [comment]
> Are you writing a navigation application, this is what I am doing right now ! For pleasure :-)
Yes, kind of - it's going to be an navigation tool for aviation. If you'd like you might catch me on my email so that we could support each other along the way.

**Comment by sailman342** [comment]
This is a good idea, is there a way to get in touch outside of Github not to bother others with our stuff ?

**Comment by eltomek** [comment]
> This is a good idea, is there a way to get in touch outside of Github not to bother others with our stuff ?

You can see the email address on someone else's profile if one provided it.

**Comment by eltomek** [comment]
@pauldendulk I don't think the defect is closed, the distance calculated by `Point.Distance` seems to be wrong by 60%.

**Comment by pauldendulk** [comment]
Point.Distance simply calculates the euclidean distance, like in school math. It is not about geography. So it cannot be used to calculate distance on the globe. 

To calculate distance on the globe you need to convert to LatLon and use a method like this:
https://stackoverflow.com/a/7595937/85325

This should be included in Mapsui with a sample (PRs welcome).

Does sailman's method solve your problem? What is the input to this method LatLon or SphericalMercator?

**Comment by sailman342** [comment]
My calculations proved to be correct and I agree with you Paul :-)

**Comment by pauldendulk** [comment]
Mapsui now has a method for this: `Mapsui.Utilities.Haversine.Distance(lon1, lat1, lon2, lat2)`.
