### ISSUE TITLE
How to make some Layers lay on top of others to have some kind of graphical elements always on top?

### ISSUE THREAD

**Issue by eltomek** [Mapsui/Mapsui#1042]
Say I put some Features on a WritableLayer and some Drawables on the MapView. Drawables always cover up my Features on the WritableLayer . Is there any way I could "Z-Index" layers, make them overlap Drawables and make some Features overlap other Features?

**Comment by sailman342** [comment]
are you using xamarin forms ?

**Comment by eltomek** [comment]
Yes, I'm using Mapsui in Xamarin.Forms context.

**Comment by eltomek** [comment]
Any hints? The Geometries (in this case Polygon) are on top of Drawables both visually but also logically (i.e clicking the center of the Drawable makes the Polygon to be clicked and not the Drawable). There must be a way to handle this :)

![image](https://user-images.githubusercontent.com/3283040/106664929-fcc96b80-65a5-11eb-9865-749d95d259b5.png)

**Comment by radderz** [comment]
Also when you say drawables, are you meaning those pins with the icons with a number in them? Are they setup as a Point feature within a layer with a style that renders that icon?

**Comment by sailman342** [comment]
I gave you an exemple, the simplest way is one layer for each kind of element.

You have to remove the style of the layer to get rid of the white circles, polyline on layer n-1 and lables on layer n :-)

**Comment by eltomek** [comment]
@sailman342 problem is the Polyline is added to MapView.Drawables and Features (the ones that are obscured by Polyline) are added to Map.Layers - those are 2 separate objects and MapView.Drawables seem to obscure Map.Layers (at least in my case).
@radderz - the items with circles and numeric values are of Feature type.

**Comment by radderz** [comment]
@eltomek, why are you adding the line to drawables ? you should just create a layer for the polyline and add it to the layers.. A feature can also be a polygon or polyline..

**Comment by sailman342** [comment]
![image](https://user-images.githubusercontent.com/58634016/106710787-d253ce80-65f6-11eb-92b1-f4ea15637949.png)

I gave you access to my private project waiting to be finished before being placed on the public side.

Have a look on the way I didi it on RoadBookMobile in class GpxNavFileLoader
```

        public static Feature GetGpxLineStringFeature(IEnumerable<Point> wgs84PointsList, string labelArg, int indexArg, Color colorArg, int widthArg)
        {
            Feature lineStr = new Feature()
            {
                Geometry = new LineString(wgs84PointsList),
                ["Type"] = "GpxNavLineString",
                ["Label"] = labelArg,
                ["Index"] = indexArg
            };

            lineStr.Styles.Add(new VectorStyle() { Line = new Pen(colorArg) { Width = widthArg } });

            return lineStr;
        }

```

Then as said you add the feature to a dedicated layer ....

**Comment by eltomek** [comment]
I think you miss my point @sailman342 - yes, I've looked at the code you've shared with me, thank you for that. What you do is adding an object of a `Feature()` type to the `Layer`, this is what the the `Layer.Add()` method expects (actually an `IFeature`), while I'm talking about a `Polyline` type which is of a `Drawable()` type, that's why the only way I thought it could be done was adding the `Drawable` to `Map.Drawables` collection.
With what @radderz wrote I digged deeper into the API and found out that the `Drawable` has a `Feature` property so with `layer.Add(polyline.Feature)` it worked good, thank you!

**Comment by charlenni** [comment]
For Xamarin.Forms version you have two different map controls: MapControl and MapView.

MapControl implements all as the MapControls for other platforms like iOS or Android. Nothing special.

MapView tries to mimic the original MapView from Xamarin.Forms, which uses Google Maps. There you have a special list of "Drawables", which have an easy interface to use, but not all special advantages from Mapsui. Internally these are normal Features, which are placed on a normal Layer. This Layer tries to stay on top of all other Layers of Mapsui.

So what you did was, that you used the special Drawables layer from MapView with an own Layer, which is always "deeper" than the Drawables layer.

To solve this, you have to use two normal Mapsui Layers and create your own Features, or you use the Drawables layer and add Pins, which are above the Drawables layer.

I hope, this makes sense.
