### ISSUE TITLE
Get TileSource from TileLayer

### ISSUE THREAD

**Issue by AlexCenteno** [Mapsui/Mapsui#1047]
Hello and thanks for your work !!

I have seen in prerelease 3 that the TileSource property has been removed from the TileLayer class. Is it possible to get it back? even if it is read-only, it is an important point for my development.

Thanks again and regards

**Comment by pauldendulk** [comment]
It was removed because I did not to support changes to the TileSource. It complicates caching. I guess having a readonly property is possible.

**Comment by charlenni** [comment]
See #1066
