### ISSUE TITLE
Transparent Fill Not Working

### ISSUE THREAD

**Issue by m1dst** [Mapsui/Mapsui#1049]
If I style a feature as follows..

feature.Styles.Add(new VectorStyle
            {
                Fill = new Brush(Color.Transparent),
                Outline = new Pen(Color.Red, 5)
            });

Then I get a red outline with a solid white fill, not what I expect.

If I apply the same style to the layer instead then I get a red outline with a transparent fill as expected.

I am misunderstanding how things work or have I found a bug?

**Comment by charlenni** [comment]
It would be helpful, if you could say, which renderer do you use: Skia or XAML? And of what type is your feature?

**Comment by m1dst** [comment]
Sorry.  I am using Skia as I've been testing on iPhone.  I was using a LinearRing polygon to represent a circle in this example.

**Comment by m1dst** [comment]
To make it easier for you to understand I've extracted one of your test files (Mapsui\Tests\Mapsui.Tests.Common\Maps\PolygonSample.cs" and modified it to show the issue.  I should have done this originally.  You will see I have set the map background to red and the border to green and the fill to transparent.  I see a fill of white.

You can flip between WPF and SKIA and the result is the same.

If it is not a bug then I am unsure how I would format the style for each feature on a single layer if the style was derived from data.

Hope this explains the issue clearer.

[PolygonSample.cs.txt](https://github.com/Mapsui/Mapsui/files/5866223/PolygonSample.cs.txt)

**Comment by charlenni** [comment]
Ok, found your problem.

In Mapsui there are two ways to set a style for a feature. The first one is to set it for the whole layer, the second one is to set it for a single feature. While rendering, Mapsui first draws all features for the given layer styles and then draws all features with their own styles.

In your case, you draw first the feature with the default layer style, which uses color white to fill your feature. Ten you draw the feature with its own style (transparent) above the first drawing. And the result is a transparent polygon above a white polygon.

If you want to draw each feature with its own style, you have to remove the style from the layer and only add it to the feature.

So I would assume, that it isn't a bug, but a feature ;-)

**Comment by m1dst** [comment]
So to confirm, you're saying the feature is drawn twice?  I assumed the feature style would override the layer style.  So if I have 999 features all with the same style and 1 with a different style, I have to apply the style at the feature level for all 1000 features?

**Comment by charlenni** [comment]
Yes, that's the way, Mapsui is working. Up to now, it wasn't a problem, because, in your example, 1000 features are drawn with the layer style and one more feature was drawn with its own style. So you have 1001 drawings. The problem here is, that the layer style draws something, that the feature style couldn't revert, because the feature style should show, what is underneath.

So you have two possible solutions:
1. Remove the layer style and use a style for each feature (could be the same for all features)
2. Set the fill color of the layer style to transparent

**Comment by charlenni** [comment]
Did this solve your problem? If yes, could you please close this issue?

BTW. this means not, that this is an ideal behavior for this, but it is the way, Mapsui does it. For your problem, you could divide your features by style they use and create for each style a different layer.

**Comment by m1dst** [comment]
Thanks - Now I know how it works then I can use it in the appropriate way.  I'll close now and report back if I hit problems with this approach as I have some pretty complex maps to reproduce.
