### ISSUE TITLE
Enabling double tap produces two event handler calls with numTaps = 1 and numTap = 2

### ISSUE THREAD

**Issue by sailman342** [Mapsui/Mapsui#1052]
if you enable double tap detection

`
            mapView.UseDoubleTap = true;
`

the event handler will be called twice, once with e.NumOfTaps == 1 and once with e.NumOfTaps == 2

Is it the normal behavior ? Sometime difficult to handle ...

This is Mapsui 2.0.3 with Xamarin Forms 4.8

Please note, it is also present on Mapsui 3.x and Xamarin Forms 5.0 ! (Not official I know :-) )

Here is a small demo of the feature ;-)

Thanks for this nice job :-)

https://github.com/sailman342/MapsuiTest

**Comment by charlenni** [comment]
How do you think, this should be handled correct?
1. If you enable double tap, then you have to wait at each tap to be sure, that the tap isn't a double tap. So the single tap is very slow. 
2. If you don't wait the double tap time, then you raise a single tap and later, if you get another tap in the double tap distance, you raise another event. 

Now which is the correct one? Which one should be used by all users? And if you find it difficult to distinguish between single and double tap, where you know what your app does, how difficult must this for Mapsui?

**Comment by sailman342** [comment]
I think a double tap is a single event, so normal behavior should be to have a single event call ...

If user wants double click detection either "you or he" will have to wait and I undestand your problem ;-)

But if you ran the test program you saw that the tap == 2 comes BEFORE the taps == 1 how do you know before it happens then ?

**Comment by charlenni** [comment]
Ah, a little detail, that you missed. Which test program did you use?

**Comment by sailman342** [comment]
I gave you a link in the first post

(https://github.com/sailman342/MapsuiTest)

kindest :-)

**Comment by charlenni** [comment]
Sorry for not seeing the link.

You are right. The code fires two events. It seems, that there is a bug.

If I understand it correct, then you use the source Mapsui code in your project. Could you try the below code:

        // If touch start and end is in the same area and the touch time is shorter
        // than longTap, than we have a tap.
        if (isAround && (ticks - releasedTouch.Tick) < (e.DeviceType == SKTouchDeviceType.Mouse ? shortClick : longTap) * 10000)
        {
            _waitingForDoubleTap = true;
            if (UseDoubleTap) { await Task.Delay(delayTap); }

            if (_numOfTaps > 1 && Algorithms.Distance(releasedTouch.Location, _firstTouch) < touchSlop)
            {
                if (!e.Handled)
                    e.Handled = OnDoubleTapped(location, _numOfTaps);
            }
            else if (_numOfTaps > 1 && Algorithms.Distance(releasedTouch.Location, _firstTouch) >= touchSlop)
            {
                // Both taps are to different from each other, so use the last as single tap
                if (!e.Handled)
                    e.Handled = OnSingleTapped(_firstTouch);
            }
            else if (_numOfTaps == 1)
            {
                if (!e.Handled)
                    e.Handled = OnSingleTapped(location);
            }
            _numOfTaps = 0;
            if (_waitingForDoubleTap)
                _waitingForDoubleTap = false; ;
        }

Should replace the code in MapControl.cs of Mapsui.UI.Forms around line 163. And then test it. It should remove any second event and if first and second tap of a double tap are to fare from each other, then the last tap position is used for a single tap.

**Comment by charlenni** [comment]
And, if you are already testing, around line 190 there should be 

        else if (isAround && (ticks - releasedTouch.Tick) >= (e.DeviceType == SKTouchDeviceType.Mouse ? shortClick : longTap) * 10000)
        {
            if (!e.Handled)
                e.Handled = OnLongTapped(location);
        }

for the long tap.

**Comment by sailman342** [comment]
Well, this is the kind of things that need some time to think about :-)

I did the first mod and here are the results (the 3 digits are millisecond)

```
---------------- 439 MapTouchStarted 
---------------- 551 test for Charlenni MapClickedAsync 1 
---------------- 554 MapTouchEnd 
---------------- 651 MapTouchStarted 
---------------- 755  It is a double click during first timer
---------------- 774 MapTouchMove 
---------------- 786 MapTouchMove 
---------------- 801 test for Charlenni MapClickedAsync 1 
---------------- 805 MapTouchEnd 
```

As you can see it fires twice a single tap now...

I know it is a complex case and I admit I didn't took time to study your code in details.

I am trying to make an interface where :  you click twice on the map to create a waypoint.

If you click on the waypoint you get infos messages , and if you click twice on the waypoint, you delete it ...

Furtheremore waypoints can be dragged :-(

The problem is difficult to solve because of the différencies between the platforms.

So I am trying to build a logic as resistant as possible only based on touch/touchend but ... 

On UWP, move events seems to be generated by a timer, on other platforms is seems event driven (the hardware detects the move ?) If you keep your mouse at the same place on UWP you get move events, on Android if you keep your finger at the same place (stop breathing) you have no move events ... 

Very difficult to reproduce but on Android sometime the mapTouchEnd  event doesn't occur :-( so if you rely on it, the code hangs ... so another timer is needed ?

For the second mod, the OnLongTapped is called nowhere right now, I have a difficulty to see where it should be placed, and given the above,  lets think about all that :-)

:-)

**Comment by charlenni** [comment]
For a double tap, the time difference between two clicks should below 200 ms. So I assume, that between your clicks are to much time.

I tried to mimic the Android code, but you are correct, on each platform it is handled different.

**Comment by sailman342** [comment]
200 ms is short, here is what says Microsoft

`The number of milliseconds that may occur between the first and second clicks of a double-click. If this parameter is set to 0, the system uses the default double-click time of 500 milliseconds. If this parameter value is greater than 5000 milliseconds, the system sets the value to 5000 milliseconds.`

At other places I found `values should range between 200 ms and 900 ms,` 200 is therefore the bare minimum for young healthy people :-)

As you can see in the sample the elapsed time was 212 ms.

I will polish the instrumentation and keep you posted on my findings.

**Comment by charlenni** [comment]
The problem is, that all platforms have different double click times (see [Wikipedia](https://en.wikipedia.org/wiki/Double-click)). With 5000 ms you have to wait 5000 ms after a click to decide, if this is a click or a double click. That would be horrible.

Reading [this](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/input-mouse/how-to-distinguish-between-clicks-and-double-clicks?view=netdesktop-5.0) arrival, there are two ways of doing this:
1. Send a single click event and later a double click event and the user has to revert the action of the single click event before the double click event
2. Wait

So what do you think is the right way to handle this? Should there be an adjustable time for waiting? What is with triple and more clicks?

**Comment by sailman342** [comment]
Hello @charlenni , 

Sorry for the delay but you know Swiss are slow (I was busy by the way :-), one use to say that Swiss stand up early but wake up late :-) .... it's not a legend :-)

I thing that experienced people will find in Touch all what they need to build their own interface and own rules. And this would be the case for triple and more clicks.

Therefore I would have a tendency to say that one user action would result in one event call , and a double click is a single user action not two ! To make it more clearer to the user I would have a separate event handler for double click as it very likely result in different code execution !

Therefore Mapsui should wait, the user would have to do anyway and given that you can disable double click events, that should be no harm !

Anyway, you must solve the longTap problem as well, the fact that from time to time the touchEnd event is missing on Android is of no help.

Relying on the position is also a complex issue. It works with a mouse on a PC screen, but with fingers on a phone screen not easy. 

Most of the time missing one click is of minor importance, just retry ! I don't like the rollback philosophy of Microsoft, it works for databases but for user interface ? ? If on single click you present one type of info and another type of info on double click, it is not always possible to rollback, mainly if you use a displayalert or equivalent window with a OK button (no way to kill other than user action)

I will work on that topic next week, and id you don’t mind I will keep you posted 😊

**Comment by charlenni** [comment]
I don't think, that Swiss are slow. And if I want to tell this to my colleagues, they will through with stones ;-)

I search a little bit and found MR.gesture (see [here](https://www.mrgestures.com/)). There is a Tapping and a Tapped event. The first is a single tap, where not is validated, that it is a single tap, the latter is a real single tap. Perhaps this could be a solution.

**Comment by sailman342** [comment]
:-) 

I prepared for you a small test program, btw it is not complete yet .

I built it with the latest Mapsui sources so that you can investigate your changes, only two lines are changed in Mapsui sources to compile with XF 5.0 (To take into account the fact that XF has now a Brush class. Pretty easy mod :-))

The interface is awfull, I will take some time later to tune it. There are a lot of redundancies due to the fact that it is extracted from my App.

Already visible is the difference of behaviour with double tap enabled or not, but I still need to investigate.

https://github.com/sailman342/MapsuiTouchTimings

We could have a nice solution if we could implement a dependency service to check if the mouse button is still down for drag and long tap but for mouse (PC) it is easy but I could not find a way to detect that the finger is still touching the surface (and as Touchend seems not to be reliable )

I need also to implement for IOS and OS X, but I have to fix my iMac first (I put a metal GPU to be able to run Big Sur to have the latest xCode compatible with Visual Studio :-( .... )

Kindest, Alain

**Comment by sailman342** [comment]
@charlenni  Hello the test program is ok now, ready for investigations :-)

https://github.com/sailman342/MapsuiTouchTimings

At the time of writing the Mapsui sources are still orginal one as per master branch.

Would you like to investigate before you or I modify Mapsui sources !

Available for MacOs, iOS, Android, UWP (I know WPF handles like UWP plus the "on top" bug)

Tell me what I do next

**Comment by charlenni** [comment]
@sailman342 I made a small app for iOS, Android and UWP to test the touch handling. It is without any Mapsui parts, so that it is easy to concentrate on the real things. You could try it. See [here](https://github.com/charlenni/VTMap).

You could pan, pinch, swipe/fling, single click, double click, long click.

**Comment by sailman342** [comment]
@charlenni  thanks a lot ! I hope you didn't loose time for me because I don't want to disturb you.

In between, I was thinking you would try my App and use it for debugging Mapsui.

My problem is too specific I believe. My intention was to help, not to slow you down.

You know that I have to build with Mapsui sources because I need WPF ... so what I have done is to create a new Mapcontrol event

```
        private async void OnTouch(object sender, SKTouchEventArgs e)
        {
            // Save time, when the event occures
            long ticks = DateTime.Now.Ticks;

            var location = GetScreenPosition(e.Location);

            if(e.ActionType == SKTouchAction.Pressed || e.ActionType == SKTouchAction.Released || e.ActionType == SKTouchAction.Moved)
            {
                TouchHandler?.Invoke(this, e);
                if (e.Handled) return;
            }

```

with that I can reconstruct all what I need.

Please note that using maInfo is also problematic because it is a Skiasharp event and it is difficult to tap on a small icon or pin. So I use distance scaled to the map.resolution ...

Do you want me to move your App on Macos ?

**Comment by sailman342** [comment]
By the way, there  is way you can distinguish between a long Tap and a drag .... too many moved events on small device ...

Tell me how I can help :-)

**Comment by sailman342** [comment]
Solved by TouchAction Event handler implementation
