### ISSUE TITLE
Xamarin Forms with offline maps from maptiler

### ISSUE THREAD

**Issue by dinonovak** [Mapsui/Mapsui#1054]
I would like to use offline map. 
I have downloaded country map from https://data.maptiler.com/downloads/tileset/osm/europe/, format is specified as MBtiles (PBF), how can I add this as map layer to Xamarin Forms app - but should be te same for all ?

Thanx D.

**Comment by charlenni** [comment]
I downloaded vector tile map data. That wouldn't work with Mapsui.
