### ISSUE TITLE
Attributions missing (e.g. for OSM) in Mapsui 3.x

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1055]
In current versions of Mapsui the attribution links are not visible any more on the map, for example for OpenStreetMap-based maps.

To reproduce this, you can use one of the Forms samples:

* Mapsui.Samples.Forms.Android
* Mapsui.Samples.Forms.iOS
* Mapsui.Samples.Forms.Mac

Just run one of these apps, select "Demo" and then "1 OpenStreetMap". There should be an attribution link in the lower right corner, saying `© OpenStreetMap contributors`. On current master this is not the case any more.

This is certainly a regression:
* I verified that it still worked with release 2.0.3.
* I verified that it fails at least since 3.0.0-alpha2.

I'm not sure when exactly the regression was introduced, but it might have been the switch from BruTile 2.1.2 to 3.0.0 that happened shortly before 3.0.0-alpha1 (see bc9d9a6c94a5db6478ee46e8af53cccb8bd47ed9). I have trouble building that version with VS for Mac, therefore I cannot check this hypothesis. Maybe someone else can?

This might well be a bug in BruTile, or a problem with the interplay of Mapsui and BruTile. Any hints welcome ...

**Comment by janusw** [comment]
After having trouble to build some older versions with VS for Mac, I performed a proper bisection with VS on Windows using Mapsui.Samples.Forms.UWP. This worked out much better and actually disproved my hypothesis above. Instead it spit out the following result:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
```
13c81e6f8813109cfb59687cf34f50a9d65deebd
51facc331dd25853668485f23f10a5b09525edbd
5860e075d83f5c7f791a064d811ffb42b8fb3117

Put another way, the last 'good' commit I found is f271d17d395ea7c94522e3afdc116b5b3243fb5f, while the first 'bad' commit is 5860e075d83f5c7f791a064d811ffb42b8fb3117. The two commits in between those (13c81e6f8813109cfb59687cf34f50a9d65deebd and 51facc331dd25853668485f23f10a5b09525edbd) were 'skipped', because the sample app did not show any map at all.

@pauldendulk, all mentioned commits are yours. Do you see where this was broken and how to fix it?

**Comment by charlenni** [comment]
I would say it is [13c81e6](https://github.com/Mapsui/Mapsui/commit/13c81e6f8813109cfb59687cf34f50a9d65deebd) in file TileLayer.cs, line 164. There the attribution is set. This part is deleted in the mentioned PR.

**Comment by janusw** [comment]
> I would say it is [13c81e6](https://github.com/Mapsui/Mapsui/commit/13c81e6f8813109cfb59687cf34f50a9d65deebd) in file TileLayer.cs, line 164. There the attribution is set. This part is deleted in the mentioned PR.

Good point, thanks for the comment. I somehow missed that (although I did search these commits for 'attribution', but apparently only in lowercase) :/

**Comment by pauldendulk** [comment]
The fix is merged.
