### ISSUE TITLE
Does Mapsui provide clustering?

### ISSUE THREAD

**Issue by markaw375** [Mapsui/Mapsui#1058]
Hi. Does Mapsui provide marker clustering to help to manage multiple markers at different zoom levels?

**Comment by pauldendulk** [comment]
No. The thing that comes closest is Stacked Labels. There is a sample for that.

**Comment by AbdulBarakeh** [comment]
Does clustering/stacking of markers exist yet, or are there any plans to implement it?

**Comment by pauldendulk** [comment]
No plans for the near future. It is possible to create something like that by implementing your own provider. The IProvider.GetFeaturesAsync gets a FetchInfo which has a Resolution field. Depending on that resolution you could determine how to return the clustered features.
