### ISSUE TITLE
MapView: buttons can overlap with status bar on some iPhone models

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1059]
When using Mapsui.UI.Forms.MapView to display a map on iOS, it can happen that the zoom buttons overlap with the status bar on certain iPhone models.

This happens in particular when the MapView is basically 'full-screen' and without any other UI elements above. Since in iOS the status bar (with the clock and icons for battery, WiFi, etc) is transparent by default, the map is shown beneath it. The map buttons (for zooming etc) are rather close to the top of the map and they can even overlap with the status bar icons for certain screen sizes (e.g. with the iPhone 12 or iPhone XR).

I can imagine two different ways to fix this:

1. Adjust the default placement of the buttons (moving them slightly downward). Possibly only apply this adjustment on iOS, since the problem does not occur on Android.
2. Provide some way to adjust the button placement via the Mapsui API, so that an app can adjust it to its needs.

The first one is certainly simpler to implement, and perfectly sufficient for my purpose.

**Comment by charlenni** [comment]
Remove the existing buttons and use your own.

        /// <summary>
        /// Enable zoom buttons
        /// </summary>
        public bool IsZoomButtonVisible

        /// <summary>
        /// Enable My Location button
        /// </summary>
        public bool IsMyLocationButtonVisible

        /// <summary>
        /// Enable Northing button
        /// </summary>
        public bool IsNorthingButtonVisible

Perhaps you could go to the Children of MapView and detect the AbsolutLayout for Buttons and move it by your own (see [here](https://github.com/Mapsui/Mapsui/blob/3142da09bdbc571fd5029e1fe81206c7193ce0d8/Mapsui.UI.Forms/MapView.cs#L151)).

**Comment by janusw** [comment]
> Remove the existing buttons and use your own.

That's a bit too big of a hammer for my tiny misplacement problem. The buttons are nice and useful as they, just not always placed perfectly :)

> Perhaps you could go to the Children of MapView and detect the AbsolutLayout for Buttons and move it by your own (see [here](https://github.com/Mapsui/Mapsui/blob/3142da09bdbc571fd5029e1fe81206c7193ce0d8/Mapsui.UI.Forms/MapView.cs#L151)).

Yes, indeed the following works well in a child class of MapView:

```
AbsoluteLayout.SetLayoutBounds(((AbsoluteLayout)Content).Children[1], new Rectangle(0.95, 0.05, 40, 176));
```

Since access to `_mapButtons` is possible in principle (via the completely cryptic detour `((AbsoluteLayout)Content).Children[1]`, wouldn't it be more consistent to also provide more direct access to it?

**Comment by charlenni** [comment]
In the way of? Create a property of type AbsolutLayout like "ButtonLayout" or two properties of type float like "ButtonLayoutX"/"ButtonLayoutY"?

**Comment by janusw** [comment]
> In the way of? Create a property of type AbsolutLayout like "ButtonLayout" or two properties of type float like "ButtonLayoutX"/"ButtonLayoutY"?

I'm not sure what would be the best approach here. It might already be enough to make `MapView._mapButtons` protected instead of private.

Maybe it is even sufficient to just have a better default placement, which works on all devices. I have a workaround, anyway.

**Comment by janusw** [comment]
Turns out the adjustment above was not quite enough on some iPhone models (in particular iPhone 12), but this should be sufficient:

```
AbsoluteLayout.SetLayoutBounds(((AbsoluteLayout)Content).Children[1], new Rectangle(0.95, 0.07, 40, 176));
```

If changing the default is acceptable, this fix is perfectly fine with me. One could leave the default as is for Android (and other platforms) and use this new value only for iOS.

**Comment by pauldendulk** [comment]
So what should be done?

**Comment by janusw** [comment]
> So what should be done?

My proposal is #1067. Feedback welcome.

**Comment by sailman342** [comment]
While we are talking about buttons, I am wondering why on Forms.WPF they are square at the bottom right of the window ?

I could not not find any evidence in the code, must be somewhere but where ?

**Comment by pauldendulk** [comment]
@sailman342 Could you post a screenshot?

**Comment by sailman342** [comment]
![image](https://user-images.githubusercontent.com/58634016/107921791-4daa6e00-6f6f-11eb-8f2d-128aae6b9c84.png)


Here it is :-)

**Comment by sailman342** [comment]
I know there are problems on Forms WPF with skiasharp. Whatever you do controls are always below the Map. But the scale widget is showing correctly why not the buttons ?

**Comment by janusw** [comment]
Note that those are not the buttons that I was talking about (they are round and in the upper right corner). Actually in most of the Forms samples I only see the round ones, but e.g. in the OSM sample ("Demo -> 1 OpenStreetMap") I see both of them. @sailman342, from which sample is your screenshot?

**Comment by sailman342** [comment]
This is the code of my App and I don't create the buttons :D

**Comment by janusw** [comment]
Huh, it's hard for us to judge what you are doing in your app ;)

Is the app actually based on Mapsui.UI.Forms, or rather Mapsui.UI.Wpf? With the former, the round buttons should usually show up, unless you manually hide them, AFAIK. I've never tried Wpf, though.

Regarding the square buttons, I just looked into OsmSample.cs, and this has the following line:

```
map.Widgets.Add(new Widgets.Zoom.ZoomInOutWidget { MarginX = 20, MarginY = 40 });
```

I assume this ZoomInOutWidget is what you're seeing ...?

**Comment by sailman342** [comment]
I downloaded the current master and rebuild it here it is , Demo, OPenstreetmap

![image](https://user-images.githubusercontent.com/58634016/107930948-f3fc7080-6f7b-11eb-8375-c8e7a1f2c287.png)

**Comment by sailman342** [comment]
The round buttons are created in Mapsui.UI.Forms Mapview.cs

```
            _mapZoomInButton = new SvgButton(Utilities.EmbeddedResourceLoader.Load("Images.ZoomIn.svg", typeof(MapView)))
            {
                BackgroundColor = Color.Transparent,
                WidthRequest = 40,
                HeightRequest = 40,
                Command = new Command(obj => { _mapControl.Navigator.ZoomIn(); })
            };

            _mapZoomOutButton = new SvgButton(Utilities.EmbeddedResourceLoader.Load("Images.ZoomOut.svg", typeof(MapView)))
            {
                BackgroundColor = Color.Transparent,
                WidthRequest = 40,
                HeightRequest = 40,
                Command = new Command(obj => { _mapControl.Navigator.ZoomOut(); }),
            };
```

Same code for UWP, MAcOs where it works fine, I don't understand !

**Comment by janusw** [comment]
So you're saying the round buttons are always missing on WPF? That sounds like a bug, but I cannot verify it (working on Mac). You should probably open a new issue for that. This one is closed already ...

**Comment by sailman342** [comment]
I wanted to follow the advise you gave me some time ago :-) It is even better if you can help for the solution.

Ok I will investigate further I was just thinking you had some more insight than I given the soliution you propose for the ios :-)

**Comment by charlenni** [comment]
To bring some light in this: The above is correct ;-)

The square buttons are an example for possible widgets. That are things, that are drawn over the map without relation to the content. Another example is the ScaleBar.

The round zoom buttons are part of the MapView implementation. If they are missing in WPF, then this is a Forms for WPF problem. I assume, that this is part of the problem, that in WPF the Skia SKGLView is always on top of all other views.

**Comment by sailman342** [comment]
I see the custom widget I was looking for 👍

**Comment by sailman342** [comment]
OK got it, the zoom in and out buttons are not showing on forms.wpf because they are controls hidden behind the map :-(


MapView.cs

```
            _mapButtons = new StackLayout { BackgroundColor = Color.Transparent, Spacing = 0, IsVisible = true, InputTransparent = true, CascadeInputTransparent = false };

            _mapButtons.Children.Add(_mapZoomInButton);
            _mapButtons.Children.Add(_mapZoomOutButton);
            _mapButtons.Children.Add(_mapSpacingButton1);
            _mapButtons.Children.Add(_mapMyLocationButton);
            _mapButtons.Children.Add(_mapSpacingButton2);
            _mapButtons.Children.Add(_mapNorthingButton);
```

**Comment by janusw** [comment]
Actually I think it *is* worth to open a new issue in Mapsui (even if it is a bug in SkiaSharp), that way the issue is more visible to anyone experiencing the same odd behavior as you did. A new issue would be a **much** better place to put all this information than hiding it inside a closed issue with a completely different topic.

Also (and I think I asked you this before): You say it is a "known" bug, but has it actually been reported to SkiaSharp? If not, you better do that. If yes, place a link to the SkiaSharp issue in your new Mapsui issue that you are about to create.

This issue is dead. Please let it rest. If you expect a bug to be fixed, please report it properly!

**Comment by sailman342** [comment]
https://github.com/Mapsui/Mapsui/issues/775

OK RIP (Sorry, still on the learning curve :-) )

**Comment by pauldendulk** [comment]
Perhaps #775 should have been still open? Although it is not really a bug but unsupported in SkiaSharp, still for our users it may help to keep it open.

**Comment by charlenni** [comment]
Sorry @janusw, one last thing.

@sailman342 If you have a version of Mapsui on your computer. Try to replace the parent object of MapControl (SKGLView) with a SKCanvasView. I assume, that this is the problem. Background could be found [here](https://github.com/mono/SkiaSharp/issues/1108).

**Comment by janusw** [comment]
> Perhaps #775 should have been still open? Although it is not really a bug but unsupported in SkiaSharp, still for our users it may help to keep it open.

Yes, IMHO #775 should be reopened and have a proper title. This is an open problem in Mapsui, as long as the upstream bug in SkiaShapr is not fixed.

**Comment by sailman342** [comment]
Sorry @janusw  but :-)

@charlemmi I did it already a long time ago https://github.com/Mapsui/Mapsui/issues/892 but I deleted the test program thinking nobody would be interested in.

 It is only a couple of lines of code to change, do you want me to make a test version again and publish it ?

**To answer to your question, it works fine !**

**Comment by janusw** [comment]
Dudes,

all of this discussion deserves a new issue. Trust me! ;)

**Comment by charlenni** [comment]
The only possible solution would be to derive MapControl from a layout and add a SKGLView or a SKCanvasView to this layout. Ok, except to change SkiaSharp ;-)
