### ISSUE TITLE
Appveyor build artifacts have bad version number

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1060]
The nupkg files that are built for every commit as artifacts of the Appveyor CI build have odd version numbers. For example, for the current master the nupkg is labeled `Mapsui.2.0.0-build.1377.nupkg`, see https://ci.appveyor.com/project/pauldendulk/mapsui/builds/37632553/artifacts. This is at least misleading, since the most recent tag is called `3.0.0-alpha.3`.

AFAICS the version `2.0.0` comes from here: https://github.com/Mapsui/Mapsui/blob/055c6f1b5a1a74a4b56b8d29d118acb9ecdf4fee/appveyor.yml#L17

I don't fully understand the build number 1377, though. This might just be a running number based on the first build with this version (or something like that)?

To improve the situation, one could either just update the version in appveyor.yml to `3.0.0`, or alternatively use the output of `git describe --tags` (which for the current master is `3.0.0-alpha.3-27-g055c6f1b`) as a unique reference to the specific commit.

**Comment by pauldendulk** [comment]
Ah, yes, that needs to be manually updated. Thanks. An alternative would be to have a version.txt in the solution folder. I use this in other projects an like that. Different branches can keep track of their own version that way. 

How do you deal with the current version in your projects?

**Comment by janusw** [comment]
> Ah, yes, that needs to be manually updated. Thanks.

Thanks for merging, Paul. Unfortunately it seems that it did not help. The artifacts at https://ci.appveyor.com/project/pauldendulk/mapsui/builds/37658318/artifacts still have "2.0.0" in their name, but I don't see where it comes from. @pauldendulk, do you have an idea?

> An alternative would be to have a version.txt in the solution folder. I use this in other projects an like that. Different branches can keep track of their own version that way.
> 
> How do you deal with the current version in your projects?

I do like `git describe` :smiley:

I use it in combination with annotated and unannotated tags. Some of my projects include a custom build step that writes the output of `git describe` to a file, which is then used for all kinds of version labeling business.

Regarding branches: `git describe` does not actually include the branch name, but it still guarantees to give you a unique label (since it includes the shortened git hash).

I think an automated solution is preferable over updating the version manually, since one tends to forget that (in particular if you want a version specifier that is valid and unique for every commit).

Since all tags in Mapsui seem to be unannotated, `git describe --tags` would be helpful here.

**Comment by pauldendulk** [comment]
![image](https://user-images.githubusercontent.com/963462/107194254-17f60a00-69f0-11eb-9671-ad942228958b.png)

Somehow the envvar is not updated in appveyor. Perhaps it is overriden somehow because I have edited it on the service once.

**Comment by janusw** [comment]
> Somehow the envvar is not updated in appveyor. Perhaps it is overriden somehow because I have edited it on the service once.

Ah, I suspected something like that. If these things are hard-wired in the AppVeyor config anyway, does it use the appveyor.yml file at all, or is it more just like an export of that data? I don't have much experience with AppVeyor unfortunately.

As mentioned above, the most elegant solution IMHO would be to have an automated versioning scheme (like `git describe`, which basically gives a version label based on the last tag you've set and possibly the number of commits since then). But I'm not sure how easy it would be to integrate this with the CI build etc.

In any case, adjusting the version string in the AppVeyor settings is a reasonable fix for now.

**Comment by charlenni** [comment]
I don't know anything about AppVeyor, but found [this](https://www.appveyor.com/docs/build-configuration/#appveyoryml-and-ui-coexistence) part in documentation.

**Comment by pauldendulk** [comment]
Thanks @charlenni, that describes the problem exactly. 
"Environment variables. Variables defined on UI are getting merged with those ones defined in appveyor.yml. Variable values with the same names are getting overridden with values from UI."

**Comment by janusw** [comment]
> Thanks @charlenni, that describes the problem exactly.
> "Environment variables. Variables defined on UI are getting merged with those ones defined in appveyor.yml. Variable values with the same names are getting overridden with values from UI."

So, can you just update the value in the AppVeyor UI to 3.0.0 as well (if you haven't done so yet)?

Is it possible to only rely on the yaml file and get rid of the UI part completely?

**Comment by pauldendulk** [comment]
I deleted the envvar in the appveyor ui and did a rebuild and now there is a 3.0.0-build.1387 'latest build' nuget.

**Comment by janusw** [comment]
Nice, thank you!
