### ISSUE TITLE
Clicking MyLocationButton always pans to (0,0)

### ISSUE THREAD

**Issue by balluonline** [Mapsui/Mapsui#1063]
Clicking MyLocationButton always sets coordinates to (0,0). Is there a way to point to user's last location?

**Comment by pauldendulk** [comment]
Basically the GPS location is unknown at this point. If would be better to show no position at this point. There are samples showing an accurate position when the GPS has a fix.

**Comment by balluonline** [comment]
This is happening even after there is a GPS fix.  Clicking the my location button takes to (0,0). Do we need to do something extra to make it work?
