### ISSUE TITLE
Sample? - Moving Points (Xamarin Forms - IOS)

### ISSUE THREAD

**Issue by m1dst** [Mapsui/Mapsui#1071]
Is there an example of editing features on Xamarin Forms IOS?  I can see the WPF editing project but that seems to rely on mouse events (rather than touch).  Before I start looking deeply into that are there any pointers or samples somewhere I can review?

**Comment by pauldendulk** [comment]
No there only is a WPF sample.  Most of the code in there is platform independent so perhaps it is possible for you to make a port to Xamarin.Forms.

**Comment by m1dst** [comment]
I’m gonna try and see what I can do.  I’m no expert so hoping I can work
something out. I’ll share my results.

**Comment by pauldendulk** [comment]
Most of the editing code is now platform independent. There is a 'Editing' sample category that you could take a look at.
