### ISSUE TITLE
Map not showing immediately with Limiter applied

### ISSUE THREAD

**Issue by JBou** [Mapsui/Mapsui#1075]
When applying a Limiter on a Map, you have to click/drag once, to make the map load and show the tiles. Also, before clicking, the wrong coordinates are shown. This can be reproduced in the Sample `Special -> Keep within Extend`.

**Comment by pauldendulk** [comment]
Thanks. A reoccurring issue 🙁

**Comment by pauldendulk** [comment]
@JBou uh, was this fixed with the associated merge?

**Comment by JBou** [comment]
As I just tested #1467 and added a ViewportLimiterKeepWithin, it seems to work, I don't have to click/drag anymore. I think this is fixed.

**Comment by pauldendulk** [comment]
Thanks for testing.
