### ISSUE TITLE
Possibility to hide and show layers based on zoom level/resolution

### ISSUE THREAD

**Issue by JBou** [Mapsui/Mapsui#1076]
Is there a possibility to hide layers when not zoomed in enough when using wms, or also for labels and geometries?
There are a lot of request that return transparent wms tiles when zoomed out. they only slow down the map. If we could set a min and max resolution on a layer, it would increase the performance a lot.
This can be tested with the `Parzellen` and `Parzellennumern` layer here: [JBou/suedtirol_map](https://github.com/JBou/Mapsui/tree/suedtirol_map)

**Comment by pauldendulk** [comment]
Yes, this is possible with ILayer.MaxVisible and ILayer.MinVisible.
