### ISSUE TITLE
MapView crashes with "Failed to create EGL" upon the Page Navigation in Xamarin.Forms for UWP

### ISSUE THREAD

**Issue by eltomek** [Mapsui/Mapsui#1083]
An Unhandled `System.ExecutionEngineException` is thrown when calling the Navigation.PushAsync in UWP for the ContentPage that contains MapView component.

Full code for this issue reproduction is available at: https://github.com/eltomek/MapsuiTest2
The `e.Message` is:

> "System.Exception: Failed to create EGL surface\r\n   at SkiaSharp.Views.GlesInterop.GlesContext.CreateSurface(SwapChainPanel panel, Nullable`1 renderSurfaceSize, Nullable`1 resolutionScale)\r\n   at SkiaSharp.Views.UWP.AngleSwapChainPanel.EnsureRenderSurface()\r\n   at SkiaSharp.Views.UWP.AngleSwapChainPanel.OnSizeChanged(Object sender, SizeChangedEventArgs e)" 

The problem may be similar to https://github.com/Mapsui/Mapsui/issues/935

Assume the following code structure:

`App.xaml.cs` that initiatites the navigation stack with a `MapPage`:

    public App()
    {
        InitializeComponent();

        MainPage = new NavigationPage(new MapPage());
    }

The `MapPage` class has got a `MapView` and `Button` that calls:

    async private void OnButtonClicked(object s, EventArgs e)
    {
        await Navigation.PushAsync(new TestPage());
    }

where `TestPage()` is of a type `ContentPage` containing just the `MapView`:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MapsuiTest.Views.TestPage"
             xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms">
    <ContentPage.Content>
        <StackLayout>
            <mapsui:MapView x:Name="mapView" 
                            VerticalOptions="FillAndExpand"
                            HorizontalOptions="FillAndExpand"
                            BackgroundColor="Gray" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
This program fails on UWP everytime I press the button (`OnButtonClicked`) while on Android it always works properly.

By "fails" I mean the `PushAsync` gets called and tries load TestPage() but once loaded it always triggers the Unhandled `System.ExecutionEngineException` in `App.g.i.cs` in the following code section:
```
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
    UnhandledException += (sender, e) =>
    {
        if (global::System.Diagnostics.Debugger.IsAttached) 
              global::System.Diagnostics.Debugger.Break();   <- this is where the debugger breaks
    };
#endif
```
**If you remove/comment-out the `MapView` from XAML of the target page the code works good.** Also, i**f you remove the `MapView` **from the calling page** (`MapPage` in the sample above) then it works good too. Seems like **navigating from one Page containing `MapView` to other one containing `MapView` is an issue.**

Version info:
Mapsui.Forms: 2.0.3 and 3.0-Alpha4
Xamarin.Forms: 4.8.0.1821 and 5.0.0.2012

**Comment by pauldendulk** [comment]
@eltomek false alarm?

**Comment by eltomek** [comment]
> 
> 
> @eltomek false alarm?

No, but I think it's a duplicate of #935
