### ISSUE TITLE
Can MyLocation symbol be changed with user graphics?

### ISSUE THREAD

**Issue by eltomek** [Mapsui/Mapsui#1089]
Is that possible to use an external resource as as a MyLocation symbol? Tried adding a SymbolStyle as a Style property of MapView.MyLocationLayer but it doesn't take any effect on the original blueish icons.

**Comment by charlenni** [comment]
No, that isn't possible in the moment. There are internally used two integers (bitmapStillId and bitmapMovingId) for the bitmaps. But both are private. If you want to change this bitmapIds, than you have to change the code.

**Comment by pauldendulk** [comment]
@eltomek You could for instance make a copy of the MyLocationLayer and create your own version to your liking.
