### ISSUE TITLE
Mapsui does not rotate Viewport with MapView.MyLocationLayer.UpdateMyDirection method

### ISSUE THREAD

**Issue by eltomek** [Mapsui/Mapsui#1090]
Do I understand correctly that the `newViewportRotation` parameter of `MapView.MyLocationLayer.UpdateMyDirection` method is intended to rotate the mapView by a given degrees from the true north?

Say I have this code that updates the heading and newPosition on MapClick:

```
     public void OnMapClick(object sender, MapClickedEventArgs e)
        {
            Position newPosition = e.Point;

            double heading = GmsSphericalUtil.ComputeHeading(mapView.MyLocationLayer.MyLocation, newPosition);

            mapView.MyLocationLayer.UpdateMyLocation(newPosition);
            mapView.MyLocationLayer.UpdateMyDirection(0, heading);
            mapView.Refresh();

        }
```
The code works good however, the `mapView.MyLocationLayer.UpdateMyDirection(0, heading);` doesn't produce the right behavior. Whatever `newDirection` and `newViewportRotation` values I provide, the map does not rotate, instead I get the MyLocation symbol rotated. What I need is for the MyLocation symbol to be headed up the map and the map to get rotated so that the symbol headed up the screen points to `e.Point`

**Comment by charlenni** [comment]
No, you are not right. The map rotation is only used to set the MyLocation arrow to the correct rotation. For example, if the map is rotated about 90° (north shows to the left) and your heading is 270°, then the arrow directs up.

So, if you want to turn the map into direction of heading, then you have to use the viewport rotation.
