### ISSUE TITLE
Bing map does not work on iOS

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1094]
The Bing map does not show up on iOS. This can be seen in the BingSample or the PinSample. Both just show a black background. I see the following error in the console output:

```
Mapsui.Samples.Forms.iOS[2938:1486955]
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.
Temporary exceptions can be configured via your app's Info.plist file.
```

So apparently the Bing map is accessed via a http URL, and there could be two ways to fix the problem:
* Use a https URL if possible.
* Add an exception via Info.plist.

**Comment by janusw** [comment]
Changing http to https in the Bing URLs seems to work well. Those URLs are actually defined in BruTile:
https://github.com/BruTile/BruTile/blob/master/BruTile/Predefined/KnownTileSources.cs

In fact there are also other KnownTileSources with http URLs (like the OpenCycleMap and Stamen maps).

**Comment by charlenni** [comment]
You should open an issue in BruTile. I thought, we had this problem before and thought, it had been changed.

BTW. my map tiles are back again. A reboot did the trick.

**Comment by janusw** [comment]
> ... and there could be two ways to fix the problem:
> 
>    * Use a https URL if possible.

I opened BruTile/BruTile#142 for this. It works for Bing, but not for OpenCycleMap and Stamen. Therefore we still need the second option:

>    * Add an exception via Info.plist.

This is done in #1097.

**Comment by pauldendulk** [comment]
BruTile 3.1.3 with the fix was just released.
