### ISSUE TITLE
How to Animate Pin to specified location?

### ISSUE THREAD

**Issue by Adeel984** [Mapsui/Mapsui#1096]
I'm developing app where i need to animate the pin to specific Position, how can i do that? i've searched a lot but didn't find any code related to Xamarin . I want same [Like This](https://openlayers.org/en/latest/examples/feature-move-animation.html)

**Comment by charlenni** [comment]
Do you want this for Mapsui for Xamarin.iOS, Mapsui for Xamarin.Android or Mapsui for Xamarin.Forms.

If you talk about the last one: Pin has a property called [Position](https://github.com/Mapsui/Mapsui/blob/fca6076ddb0dbdfee740bab883db97307fa2f276/Mapsui.UI.Forms/Objects/Pin.cs#L97), which could be changed. With this, you could move the Pin.

**Comment by Adeel984** [comment]
I want in Xamarin.Forms, I knew about Position Property, But i thought there may be some API or function for it i just wanted to expose. BTW Thanks for your kind suggestion.
