### ISSUE TITLE
request to provide a NuGet Package for Branch 2.0 linked to lastest SkiaSharp version due to 32bit constraints.

### ISSUE THREAD

**Issue by BartStodola** [Mapsui/Mapsui#1103]
I have one request. 
I would need to get an additional NuGet-package based on your **branch 2.0**. This should be linked against the latest Version from **SkiaSharp v2.80.2.0**
Because in the version the skiasharp-team eliminated an external dependency to _32bit_ assemblies.

This constraint now is blocking me currently from using your product in my _x64-builds_.

**Comment by janusw** [comment]
The update to SkiaSharp 2.80.2 has been done on Mapsui's master branch and is included in the nuget packages 3.0.0-alpha.3 and 3.0.0-alpha.4. Could you use one of those?

**Comment by BartStodola** [comment]
Unfortunatelly we are restricted to use stable-release only. When will the v3.0.0 be released as a stable version?

**Comment by janusw** [comment]
> Unfortunatelly we are restricted to use stable-release only.

Well, in my experience the 3.0 alpha releases are pretty 'stable', despite their naming. By now quite a number of bugs have been fixed there wrt 2.0, and the development pace is currently not extremely high, I would say. The API is not really guaranteed to be stable, though. But the probability of getting your bugs fixed is much higher than on 2.x.

So, maybe you should consider moving from 2.0 to 3.0 alpha (depending on your exact requirements regarding stability). I did the same some time ago and did not regret it up to now.

Alternatively, you could update the SkiaSharp packages on the release/2.0 branch yourself (or backport the update from master), and open a PR to get it merged.

> When will the v3.0.0 be released as a stable version?

I assume it will take some time. Maybe @pauldendulk can tell you more.

**Comment by pauldendulk** [comment]
Maybe we should release a v3 soon, basically in it's current form. I have no time to patch v2 either.

**Comment by pauldendulk** [comment]
Outdated.
