### ISSUE TITLE
"BruTile Tile Library" user agent blocked by openstreetmap

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1104]
A 403 is returned by openstreetmap if the user agent is set to "BruTile Tile Library". This is default user agent string if none is specified. Various other user agent strings I tried seem to work, so it seems like this string was specifically blocked. Perhaps because someone was using BruTile to download a large tile set. This is not permitted. 

I now changed the user agent into "If you use BruTile please specify a user-agent specific to your app". but this one may also be blocked at some point. There is no great way to solve this for the demo. The best way for users is to to specify their own user agent.

**Comment by janusw** [comment]
> I now changed the user agent into "If you use BruTile please specify a user-agent specific to your app". but this one may also be blocked at some point. There is no great way to solve this for the demo. The best way for users is to to specify their own user agent.

Maybe the Mapsui samples apps should each use their own user agent, at least. If they don't all use the BruTile default, that should decrease the chance of getting it blocked again.

**Comment by janusw** [comment]
> The best way for users is to to specify their own user agent.

A way to enforce this would be to make the parameter `userAgent` of `KnownTileSources.Create` optional (i.e. remove the default value `null`).

**Comment by pauldendulk** [comment]
> > I now changed the user agent into "If you use BruTile please specify a user-agent specific to your app". but this one may also be blocked at some point. There is no great way to solve this for the demo. The best way for users is to to specify their own user agent.
> 
> Maybe the Mapsui samples apps should each use their own user agent, at least. If they don't all use the BruTile default, that should decrease the chance of getting it blocked again.

> > The best way for users is to to specify their own user agent.
> 
> A way to enforce this would be to make the parameter `userAgent` of `KnownTileSources.Create` optional (i.e. remove the default value `null`).

That may be a good idea. Btw, there is a Mapsui OpenStreetMap.Create method which uses another user agent, so Mapsui is mostly unaffected.

**Comment by pauldendulk** [comment]
Related issues in BruTile https://github.com/BruTile/BruTile/issues/144

**Comment by janusw** [comment]
The recent PR #1186 relates to this issue, I guess.

Can this be closed or should anything further be done?

**Comment by pauldendulk** [comment]
I will update the FAQ with a code sample on how to change the user-agent: https://mapsui.com/documentation/faq.html

**Comment by pauldendulk** [comment]
The FAQ was updated.
