### ISSUE TITLE
Crash when rendering with Skia and calling GetMapInfo on offscreen coordinates

### ISSUE THREAD

**Issue by dedmen** [Mapsui/Mapsui#1106]
https://github.com/Mapsui/Mapsui/blob/f4e253adbe4a464cb561eaa6d7be34e623ccae6e/Mapsui.Rendering.Skia/MapRenderer.cs#L224

If pixmap height is only 352 and you try to access 353 this crashes with AccessViolationException.

Adding below here: https://github.com/Mapsui/Mapsui/blob/f4e253adbe4a464cb561eaa6d7be34e623ccae6e/Mapsui.Rendering.Skia/MapRenderer.cs#L214
```
if (intX >= width || intY >= height)
                    return result;
```
fixes it, but I'm not sure if thats the right way to go.
Should it be rather left to the user to make sure he's not calling GetMapInfo outside of the viewport?
Should we extend the rendering viewport in case GetMapInfo is called on a point that's currently not visible? 

I think the latter probably makes more sense, GetMapInfo shouldn't be dependent on whether one can currently see the coordinates.

**Comment by pauldendulk** [comment]
Well at least it should not crash. I think this is fixed in V3. Which version are you using?

**Comment by dedmen** [comment]
I was on latest prerelease from NuGet
https://github.com/WolfCorps/TacControl/blob/master/src/DesktopClient/TacControl.csproj#L340

> 3.0.0-alpha.4

**Comment by pauldendulk** [comment]
This was the fix I was referring to https://github.com/Mapsui/Mapsui/pull/1065/files, but that was part of alpha.4, so apparently this is a different issue that should be fixed.

**Comment by pauldendulk** [comment]
@dedmen This should be fixed in the next release.
