### ISSUE TITLE
How to use MapView in .Net 5.0 WPF?

### ISSUE THREAD

**Issue by YongqingKyleHuang** [Mapsui/Mapsui#1107]
I tried to use MapView in .Net 5.0 WPF:
<Window  
    xmlns:wpf="http://schemas.microsoft.com/netfx/2009/xaml/presentation"
    xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms"
    Title="MainWindow" Height="450" Width="800">
    <mapsui:MapView/>
</Window>

but this is compiling error:  : XamlC error XFC0000 : Cannot resolve type "Application".

The following sample project is not .Net 5.0 enabled yet:

Mapsui/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.WPF/Mapsui.Samples.Forms.WPF.csproj

<TargetFramework>net48</TargetFramework>

 Could you help me ? Please give a small sample using MapView in .Net 5.0 WCF

Thanks in advance!

**Comment by YongqingKyleHuang** [comment]
<Window  
    xmlns:wpf="http://schemas.microsoft.com/netfx/2009/xaml/presentation"
    xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms"
    Title="MainWindow" Height="450" Width="800">
    <mapsui:MapView/>
</Window>

**Comment by YongqingKyleHuang** [comment]
xmlns:wpf="http://schemas.microsoft.com/netfx/2009/xaml/presentation"
    xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms"
    Title="MainWindow" Height="450" Width="800">
    <mapsui:MapView/>

**Comment by pauldendulk** [comment]
This is not supported in v2. In v3 we just added a TargetFrameworks for netcoreapp3.1 in Mapsui.UI.Wpf so I assume that one should work. 

Note, Mapsui.UI.Wpf is does not have the MapView (which is Xamarin.Forms) but only the WPF MapControl, which has less functionality.
