### ISSUE TITLE
Geotiff file loading 

### ISSUE THREAD

**Issue by anushabasavaraj92** [Mapsui/Mapsui#1108]
Loading a geotiff file of 500MB makes the UI response slow. Is there a way to increase the responsiveness in WPF?

**Comment by pauldendulk** [comment]
Which ILayer are you using? Perhaps the ImageLayer is the best option.

**Comment by pauldendulk** [comment]
If that does not work perhaps you need to find a way to cut the file into an MBTiles format.

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
