### ISSUE TITLE
How to use world file information to show a floorplan image 

### ISSUE THREAD

**Issue by weismantelf** [Mapsui/Mapsui#1114]
I want to show a floorplan image as an overlay in a map.
For this image I have an existing world calibration file.

How I can use now the information from the world file (pgx file):

0.03479964522741726  
0.012925279615629953  
0.012525868198190633  
-0.028942567736269766  
676817.5510796336  
6372505.020911227

 to show the image in an image layer? 

How do I calculate the image position, scale and rotation factor?

thx

**Comment by pauldendulk** [comment]
Not sure, but the GeoTiffProviderTests uses a .tfw files with similar information. Please try to modify the test to run with your data. Perhaps you need to copy the GeoTiffProvider class and modify it to your own needs.
