### ISSUE TITLE
Design to support NTS

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1118]
This issue is to discuss the way in which we should start integrating NTS.

**Comment by pauldendulk** [comment]
# Changes to prepare for NTS

The PR [here](https://github.com/Mapsui/Mapsui/pull/1119) is a proposal on how to proceed with NTS. Some ideas behind this PR:
- It should, at least for a while, be possible to support both Mapsui.Geometries and NTS. Also there will be other types of things which will need specific renderers which are not geometrie, like Rasters, VectorTiles. So we need some abstraction that allows for those different types.
- To allow flexibility I have chosen for a solution where the Geometry was removed from the IFeature and an IGeometryFeature was introduced with a Geometry field. The core classes use the IFeature while specific layers use IGeometry. Later an INtsFeature could be introduced with it's own layers and renderers. 
- Where to make the cut? In classes where IGeometryFeature is used we can have type save Geometries, that's nice. But since the core classes use IFeature we need to do some casting somewhere. In some situations this can be prevented using generics, but not everywhere. The currently version compiles and seems to function correctly (after quickly clicking to through all the samples) but there may be better ways to make the cut. More thought will help.

## Some things that have changed
- Removed Geometry from IFeature
- Add IGeometryFeature with a Geometry
- The IProvider now has a generic argument ```public interface IProvider <out T> where T : IFeature```
- The ILayer has no generic argument. Not sure if it should. 

## More changes to come
- **MPoint and MRect for all core classes**: Currently the Mapsui.Geometries Point and BoundingBox are used in many many places. Often this does not relate to geometries at all, like in the Widgets. In other cases it is an extent of a geometry but not a geometry itself. Instead of replacing them with NTS Point and BoundingBox I propose to replace them with two new Mapsui specific classes. I was thinking of calling them **MPoint** and **MRect**. A first step would be to copy the current Point and BoundingBox and replace them. We will need to add extension method converters both ways (ToMPoint, ToMRect and ToGeometry).
- We will need to split the Mapsui project into two parts:
  - The Mapsui core which has no dependency on Mapsui.Geometry or NTS, and instead uses MPoint and MRect
  - The other (have no name for it yet) that depends on Mapsui.Geometries which will hold most of the current layers. 
  - And perhaps the TileLayer could go into it's own project.
- A new Mapsui.Nts project will have a dependency on Mapsui core only.
- Some classes that need to stay in Mapsui core (and will need to make use of MPoint and MRect).
  - Map
  - Viewport
  - Navigator
  - ViewportLimiters
  - MapInfo
  - Widgets
  - Everything related to UI
- Quad should stay and perhaps should be called MQuad, or perhaps be merged with MRect.
- Raster should not be derived from IGeometry and should be a field in a IRasterFeature

## Some other changes 

Some other changes were made that were not directly related but complicated the necessary changes:

- The IFeatures interface was removed, and I would like to remove the Features class as well. It was based on the old [DataTable](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable?view=net-5.0) class that was once used in SharpMap. The List<IFeature> and other collections suffice.
- **All XAML rendering was removed!**

**Comment by charlenni** [comment]
If you move to the new concept of renderers for special classes, you could keep the complete rendering in the core of Mapsui. You could make a special renderer for raster maps and Mapsui even doesn't know what a raster map is. And each type of layer could be optimized for rendering if you like this.

You want to use NTS for your geometries in your special layer? No problem. You want to use the old geometries for your layer? Also, no problem. Mapsui didn't have to know anything about geometries. You want to pre render parts of your layer by converting geometries into Skia paths? No problem.

With this concept Mapsui is very flexible.

So move all special cases in the renderer out to their own special renderers and add them at startup to the known renderers.

**Comment by pauldendulk** [comment]
@charlenni I think this is roughly what I had in mind, to move more in the direction of the custom style renderers. But you also say 'you could keep the complete rendering in the core of Mapsui'. What do you mean with this? I would think everything becomes like a special case, so it goes more in the opposite direction.

### Flexibility comes at a price
I would also like to add we should be careful adding flexibility because it could make the code hard to understand and could impact performance. Nevertheless I think we should move in that direction.

**Comment by charlenni** [comment]
The core rendering is to go through the list of layers and check, which renderer is needed. Then call this renderer. The renderer itself should go into a project with Skia support, the rest could stay in the Mapsui core project.

**Comment by charlenni** [comment]
And if you think about changes in this area: I found two days ago a nice [article](https://stackoverflow.com/questions/64737621/c-sharp-skiasharp-opentk-winform-how-to-draw-from-a-background-thread/65056572#65056572) about drawing in the background with Skia. The author suggested dividing the drawing process in two processes: rendering and painting. He first renders all layers to SKPictures, which store all painting commands. This could be done on any thread you want and has to be done only, if something on this layer has changed. It could even be done on a thread per layer. In another step, the stored painting commands are painted to the canvas, which has to be done on UI thread. Perhaps this speed up Mapsui a little. 

We started a discussion about this at #1084.

**Comment by pauldendulk** [comment]
### Status update

In steps the dependency of Mapsui.Geometries is reduced. Where possible MRect and MPoint are used. A lot of code in Mapsui is moved to Mapui.Core. All tiling is now independent of Mapsui.Geometries and moved to Mapui.Layers.Tiling and a part to Mapui.Layers.ArcGIS. Next WMS and the GeoTiffProvider should be moved out of the Mapsui project. It looks like this is not a lot of work. What remains all has a strong dependency on Mapsui.Geometries and will need a straight port to NTS. That will be a lot of work. It involves many renderers and samples. Perhaps some samples could be made geometryless first.  At some point all that will be moved to a Mapsui.Layers.Nts folder and Mapsui.Core will be renamed to Mapsui again. That would complete the port to NTS. I may create a Mapsui.Layers.Wms and Mapsui.Layers.Wfs project.

**Comment by pauldendulk** [comment]
## Status update after cleaning samples and tests

IGeometryFeature has been removed and I have gone through all use of GeometryFeature. In the samples and tests I could replace it in many cases with PointFeature. This left to do:

- Improve projections. In the current solution different IProjection implementations are used. There should be only one. The current ProjectingProvider only projects IGeometry. It should project all types of features. This will allow us to remove move GeometryFeatures (and replace it with PointFeatures). A complication at the moment that projection from a MemoryProvider needs a copy of the feature. So for that a generic copy method would be needed. I don't see a good generic solution for that. I now am thinking of a ProjectingProvider that does not copy and solve the problem for projecting of MemoryProviders in some other way. A way to iterate over all coordinates could be by using a:  ```IFeature.Visitor(Action<IFeature, ref double x, ref double y);```
- Move things into Layers and move Mapsui.Core back to Mapsui.
- Migratie to NTS.

**Comment by pauldendulk** [comment]
### Status update

Wrapped up Projections. Next up is to reorganize the project structure.

**Comment by pauldendulk** [comment]
### Status update

Done:
- Improve projections: Done months ago actually. I am fairly happy with the result.
- Moved all files depending on Mapsui.Geometries to Mapsui.GeometryLayer, removed Mapsui.Geometry dependency from Mapsui and moved all Mapsui.Core code back to Mapsui.

Todo:
- Port everything in Mapsui.GeometryLayers into a new Mapsui.Nts project.

**Comment by pauldendulk** [comment]
### Status update

Straight port of Mapsui.Geometries to NTS is in progress on a branch and in large part still only local on my machine. More than half way there. 

Done:
- Rendering
- Shapefile 
- All tests

Half done:
- WPF editing 
- Xamarin.Forms editing

The problem with editing is that the NTS Geometries have no default constructor and there seems to be no way to alter the Coordinates. So, when a vertex is added a new geometry needs to be created from what was already there. There are also some other quirky things, like a polygon needs at least three points, but you have to start with one with editing, so you have to keep track of those first few points yourself in a separate array. It is possible to set the X, Y values of the Coordinates, so the Geometries are mutable.

Todo:
- WFS provider

**Comment by pauldendulk** [comment]
### Status update

The current branch is ready to be merged https://github.com/Mapsui/Mapsui/pull/1454. Mapsui.Geometries has been removed so everything is ported. As far as I am aware everything works. The tests are green and I have gone through all samples. I could not test WFS because the current sample does not work. I have probably introduced bugs but we find out in the coming period. After the merge this phase is completed.

**Comment by pauldendulk** [comment]
### Status update

#1454 was merged. For problems following from this merge please create new issues.
