### ISSUE TITLE
Mapsui.Forms  not work

### ISSUE THREAD

**Issue by NeluQi** [Mapsui/Mapsui#1120]
On current versions of xamarin Forms, the map does not work. Displays displays white blank. When I post via Mapsui everything works, but using Mapsui.Forms it doesn't.

Can you drop an actual example for Mapsui.Forms and xamarin Forms 4.8?

**Comment by pauldendulk** [comment]
Look at the BingSample.cs. Note, you need an api key to be allowed to use it.

**Comment by pauldendulk** [comment]
I just started Mapsui.Samples.Droid from the latest master on my Android device and it seems to function properly. 

What did you do? Which version? Which project? Which platform? Device or emulator? Which sample? (You are supposed to mention things like that in an issue).

**Comment by NeluQi** [comment]
The problem was in the version of the libraries (It seems in AndroidX) and HardwareAccelerated = false
