### ISSUE TITLE
How to add Satelite Tile Layer

### ISSUE THREAD

**Issue by Adeel984** [Mapsui/Mapsui#1122]
I want to use Satelite tile layer along with default tile layer i.e "OpenStreetMap.CreateTileLayer();" Haven't find any solution. Please guide me in this regards.

**Comment by pauldendulk** [comment]
Look at the BingSample.cs. Note, you need an api key to be allowed to use it.

**Comment by Adeel984** [comment]
@pauldendulk BingSample.cs  is not available [here](https://github.com/Mapsui/Mapsui/tree/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared) where does it located?
