### ISSUE TITLE
How to remove Dots from the Start and End points of a line

### ISSUE THREAD

**Issue by stubprogrammer** [Mapsui/Mapsui#1129]
![line](https://user-images.githubusercontent.com/84324144/118486393-fa44e900-b732-11eb-82e2-8da3dbe93f0f.jpg)
There's a line in mentioned picture which has a dot at both endpoints.
Referring to the issue https://github.com/Mapsui/Mapsui/issues/956 , it only works for point feature. However if we draw shapes like line, polygons, these dots appear on end points of vertices/lines and are not removed by using Layer.style= null. Source code is used from the following branch
https://github.com/Mapsui/Mapsui/tree/master/Samples/Mapsui.Samples.Wpf.Editing/Editing
The code for this line is  "if else" in the method Addvertex present in Editmanager.cs

**Comment by pauldendulk** [comment]
The editing sample uses a VertexLayer to show those vertices because they need to be dragged and deleted. I you start the editing sample from the Mapsui sln the is a layer list on the top right with a VertexLayer that can be disabled.
