### ISSUE TITLE
No map refresh after pan in UWP

### ISSUE THREAD

**Issue by sgerst** [Mapsui/Mapsui#1130]
I just recognize an issue after updateing to the newest version.

If I just pan my map, features (vector or also mbtiles sources) are not shown/refreshed if they are outside the actual viewport. If I pan the map and then zoom in or out, they occur. It seems like the map is only renderd if you use the zoom function.

I'm using version 2.0.3 in an UWP app.

Has anyone an idea?

**Comment by pauldendulk** [comment]
I miss something. If they are outside the actual viewport they can not be seen. Or are they partially outside of the viewport? Or do I not understand the problem?

**Comment by sgerst** [comment]
To reproduce it: 
Bind a mbtiles Source. 
Then zoom in. -> Tiles will be loaded an renderd.
Then pan. -> "New" tiles from outside the viewport will be loaded, but blurred.

![image](https://user-images.githubusercontent.com/84453104/126107148-d429e32e-2679-4cdd-a16f-867474522435.png)

**Comment by charlenni** [comment]
But there are tiles for this zoom level in the MBTiles file? If not, a tile of a lower zoom level is used and zoomed as replacement of the missing tile.

**Comment by sgerst** [comment]
Yes. If I zoom out and then in again, the tiles will be viewed correctly.

**Comment by sgerst** [comment]
In a previous version, all worked well.

**Comment by pauldendulk** [comment]
ah thanks, I needed that clarification. Seems like a bug. We should test if it exists in current master.

**Comment by pauldendulk** [comment]
This is what I see in current master in WPF. Looks correct. 

![image](https://user-images.githubusercontent.com/963462/126129851-e68c77ab-7896-4b85-94db-76cb89b8f01e.png)

**Comment by pauldendulk** [comment]
And this in UWP. No refresh at all while dragging. This is in current master.

![animated-features3](https://user-images.githubusercontent.com/963462/126130524-526118e0-ad94-4485-8597-fc9574efa2d2.gif)

**Comment by pauldendulk** [comment]
@sgerst Should be fixed in the next release.
