### ISSUE TITLE
Proxy block mapsui.com

### ISSUE THREAD

**Issue by PTEC3D50** [Mapsui/Mapsui#1131]
Your website mapsui.com is blocked by my enterprise proxies. Please, can you ask for a review through bluecoat website : https://sitereview.bluecoat.com/#/ , select filter Blue Coat ProxySG.

Regards,

**Comment by pauldendulk** [comment]
Interesting. I did what you asked. Not sure how this works.

**Comment by pauldendulk** [comment]
I entered mapsui.com in bluecoat (months ago). Did this fix your problem?

**Comment by PTEC3D50** [comment]
Yes, this problem is fix ! Thanks !
