### ISSUE TITLE
Circle: StrokeColor and StrokeWidth have no effect

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1136]
Example code:

```csharp
using Xamarin.Forms;
using Mapsui.UI.Forms;
using BruTile.Predefined;

namespace MyApp
{
    public class TargetMap : MapView
    {
        public TargetMap() : base()
        {
            Map.Layers.Add(new Mapsui.Layers.TileLayer(KnownTileSources.Create(KnownTileSource.OpenStreetMap, userAgent: "Mapsui")) { Name = "OSM" });

            Position p = new Position(50, 9);

            Navigator.NavigateTo(Mapsui.Projection.SphericalMercator.FromLonLat(p.Longitude, p.Latitude), Map.Resolutions[8]);

            var c = new Circle
            {
                Center = p,
                Radius = Distance.FromKilometers(50),
                FillColor = Color.White,
                StrokeColor = Color.Red,
                StrokeWidth = 10,
                Quality = 60
            };
            Drawables.Add(c);
        }
    }
}
```

This should obviously show a white circle with a thick red border, but what I see is a white circle with a thin grey border! No matter what color and width I set, it has no effect (only the FillColor does). Same behavior on Android, iOS and Mac.

In the Mapsui samples (CircleSample) I see that stroke color and width do have an effect. I have no idea why it doesn't work here. Any clues welcome.

**Comment by janusw** [comment]
> This should obviously show a white circle with a thick red border, but what I see is a white circle with a thin grey border!

I still don't fully understand what's going on, but I found some hints:
* thin grey is the default for VectorStyle.Outline
* the Circle class translates the StrokeColor and StrokeWidth properties into VectorStyle.Outline

There is one inconsistency that I don't understand:
* both the Circle and Polygon class rely on Geometries.Polygon
* the Circle class sets VectorStyle.Outline in its CreateFeature and OnPropertyChanged methods
* however, the Polygon class sets VectorStyle.Outline in OnPropertyChanged, but VectorStyle.Line in CreateFeature

**Comment by janusw** [comment]
Regarding the differences in Circle and Polygon: The stroke color and width seem to work well for the Polygon case, using e.g. something like this ...

```
            var pg = new Polygon
            {
                FillColor = Color.White.MultiplyAlpha(0.5),
                StrokeColor = Color.Red,
                StrokeWidth = 10,
            };
```

... so I'll conclude phenomenologically that the handling of properties for the Polygon is correct, while it is wrong for the Circle (even if I don't understand why).

I'm still completely puzzled as to why things work correctly in the samples.

**Comment by charlenni** [comment]
See #1100 and #1101. Didn't this do the trick?

**Comment by janusw** [comment]
> See #1100 and #1101. Didn't this do the trick?

Completely missed this, partly because I'm still stuck on an older version (due to bugs like #1115).

So, thanks for the pointer. And yes, this actually seems to do the trick. And I guess it also explains my confusion as to why things work in the sample app (-> current master), but not in a standalone app (with an older nupkg).
