### ISSUE TITLE
3d Maps Or Custom Tile Server

### ISSUE THREAD

**Issue by fahad462** [Mapsui/Mapsui#1139]
Is it possible to view 3d Map Or Load map from custom tile server?

**Comment by johnjore** [comment]
Can't help with the 3D questions, but custom tile server is in the documentation (or a google search)

Replace the URL below with your own. From memory, I spent way too much time on this before I realized that HTTP does not work, nor does HTTPS if not trusted.

Snippet from my app:
```
            var tileSource = new HttpTileSource(new GlobalSphericalMercator(), "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", new[] { "a", "b", "c" }, name: "OpenStreetMap", userAgent: "OpenStreetMap in Mapsui");
            var tileLayer = new TileLayer(tileSource)
            {
                Name = "OSM",
            };
            map.Layers.Add(tileLayer);

```

**Comment by fahad462** [comment]
> Can't help with the 3D questions, but custom tile server is in the documentation (or a google search)
> 
> Replace the URL below with your own. From memory, I spent way too much time on this before I realized that HTTP does not work, nor does HTTPS if not trusted.
> 
> Snippet from my app:
> 
> ```
>             var tileSource = new HttpTileSource(new GlobalSphericalMercator(), "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", new[] { "a", "b", "c" }, name: "OpenStreetMap", userAgent: "OpenStreetMap in Mapsui");
>             var tileLayer = new TileLayer(tileSource)
>             {
>                 Name = "OSM",
>             };
>             map.Layers.Add(tileLayer);
> ```

Thank you
