### ISSUE TITLE
Hidden linestring and/or offline map not visible. Bug or User Error?

### ISSUE THREAD

**Issue by johnjore** [Mapsui/Mapsui#1140]
Hi!

I'm trying to write a hiking app with support for offline maps.

I have my own tile server, and I have downloaded zoom levels 0 to 10 and saved in an mbtiles file.
I also have about 10x mbtiles files, one for each GPX file with zoom levels 13 to 17.

I turn off data on my phone and load the offline files (assuming this is happening in a random order) and import the GPX. Depending on parameters I get

a) blurry map. The dedicated mbtiles files are not overlaying ontop of the country map, or "shining" through to become visible at zoom levels not present in the country mbtiles file
b) gpx linestring not visible

Here are a few attempts:
```
//Map not clear. GPX visible
//var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(file, true), null, MbTilesType.BaseLayer, false, true);

//Map not clear. GPX not visible
//var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(file, true), null, MbTilesType.Overlay, true, true);

//Remove australia map file with zoom 0 to 10. Map is clear and GPX visible
//var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(file, true), null, MbTilesType.BaseLayer, false, true);

//Remove australia map file with zoom 0 to 10. Map is clear and GPX not visible
//var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(file, true), null, MbTilesType.BaseLayer, true, true);
```

* Why does determineZoomLevelsFromTilesTable=true make the linestring invisible or hidden?
* Does mapsui not make missing tiles at different zoom levels "transparent" so more detailed mbtiles become visible?
* Do I need to load australia map first, and then the rest of the map files?

I'm using Mapsui 3.0.0-alpha.4

**Comment by pauldendulk** [comment]
Try one thing at a time. Did you succeed to show your gpx trail on tip of the OSM map that is used in most samples?

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
