### ISSUE TITLE
Get feature through GetMapInfo()

### ISSUE THREAD

**Issue by buu-huu** [Mapsui/Mapsui#1149]
I would like to get the corresponding feature on my map, when I click on it. So far, I created a MouseDown event, that asks my MapControl for the information via `GetMapInfo()`, but I always get null for features and layers, when I debug.

I might do something wrong with the Point, that I pass as an argument. Currently, I get the click position of the MouseButtonEventArgs ang convert the X and Y value to a Mapsui.Geometries.Point.

Thank you in advance for your great help here!

```csharp
public partial class MapWindow : Window
{
      public MapWindow(Mesocyclone meso)
      {
            InitializeComponent();
            
            mapControl.Map = MapBuilder.CreateMap(new List<Mesocyclone> { meso }); // Just creating my map here through a static method that I created...
      }
      
      private void mapControl_MouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
      {
            System.Windows.Point p = e.GetPosition(this);
            Mapsui.Geometries.Point mapPoint = new Mapsui.Geometries.Point(p.X, p.Y); // I guess, this might be the problem but I don't know, how I can get a Mapsui.Geometries.Point inside that event
            var info = mapControl.GetMapInfo(mapPoint);
      }
 }
```

**Comment by charlenni** [comment]
Why don't you use then `Info` event (see [here](https://github.com/Mapsui/Mapsui/blob/6589ae5cf45b005078a6c6c0d10a2c3f8460282a/Mapsui.UI.Shared/MapControl.cs#L125)) of `MapControl`?

**Comment by buu-huu** [comment]
> 
> 
> Why don't you use then `Info` event (see [here](https://github.com/Mapsui/Mapsui/blob/6589ae5cf45b005078a6c6c0d10a2c3f8460282a/Mapsui.UI.Shared/MapControl.cs#L125)) of `MapControl`?

That solved the issue. Thank you very much!
