### ISSUE TITLE
Remove widget from Map

### ISSUE THREAD

**Issue by buu-huu** [Mapsui/Mapsui#1153]
Is there any possibility to remove a widget from a map?

I added a `ScaleBarWidget(mapControl)` but I can't remove it with `mapControl.Map.Widgets.Remove()`.
My workaround would be, to create a new map, but maybe there is a better solution.

**Comment by charlenni** [comment]
`mapControl.Map.Widgets` is of type `ConcurrentQueue<IWidget>`. Normally, you could not remove an entry. If you want to do this, you have to use a workaround. For this, see the [answer](https://stackoverflow.com/questions/683956/pfx-concurrentqueue-is-there-a-way-to-remove-a-specific-item-from-the-queue) on StackOverflow. It is in VisualBasic, but should work.
