### ISSUE TITLE
Creating/rendering a custom map from OSM

### ISSUE THREAD

**Issue by buu-huu** [Mapsui/Mapsui#1154]
I would like to use a custom map "style" for my map. Mainly to have the map without an internet connection and to fit my preferences. Currently I do it with `OpenStreetMap.CreateTileLayer()`.

I never rendered an OpenStreetMap before, but I think that would be the way to go. Since there are many renderers for OSM out there, I ask, what is the best approach to to this.

I didn't find a solution, how to implement this and if there is an easy way to do this with Mapsui. To put it in a nutshell:
- What output format of the OSM renderer is best for Mapsui? Any recommendations for a renderer?
- How do I get that custom rendered map in Mapsui? I didn't find a sample for that.

**Comment by pauldendulk** [comment]
Mapsui is no close integration with OSM. The OSM layer that is used in most samples is a tile layer served by OSM. If you want to created a alternative to that you need to render your own tiles, but that is not an easy thing to do and you will need a tile server that can serve a huge number of tiles.

**Comment by buu-huu** [comment]
Thanks Paul, I will give it a try when I have a bit freetime. I will share my observations/code when I get it to work.
