### ISSUE TITLE
[iOS] Incorrect number of touches counting in ScrollView

### ISSUE THREAD

**Issue by Pastajello** [Mapsui/Mapsui#1155]
Hello.

The MapsUI for Forsm are working very well. Im using it for a lot of scenarios, but there is one that i bugged.
The iOS page with ScrollView and MapView inside, with enough content that the page will scroll.

        <ScrollView>
            <StackLayout>
                <mapsui:MapView VerticalOptions="FillAndExpand" HorizontalOptions="Fill"/>
                <Grid HeightRequest="400" BackgroundColor="Red"/>
                <Grid HeightRequest="400" BackgroundColor="Green"/>
                <Grid HeightRequest="400" BackgroundColor="Blue"/>
                <Grid HeightRequest="400" BackgroundColor="Red"/>
            </StackLayout>
        </ScrollView>

Lets go with something like this in our normal ContentPage.
Now what I'd expect is that there is some problems when panning the map inside the ScrollView, Both Map and ScrollView are intercepting touch events so the operating is problematic.

That is the case on Android. - GOOD
But on iOS, the problem is much more traumatic - when the user is panning the Map the touches that are being counted below are behaving weirdly - they are not being reset when user stops touching the map. So with that map interaction is basically frozen when we end up with more then 4(?) or so touch points. At one point I ended up with 35 touches at the same time.

How to check that:
Mapsui.UI.Forms.MapControl.cs:211.
Put a 
`Debug.WriteLine(_touches.Count);`
Now with the above code and prepared MapPage You can see on the output how many touch points are at the moment of moving the fingr on the map. It accumulates, even if it shouldnt.

Expected:
The '_touches" field should reset when the finger/focus of the map is being taken from the control so the number of _touches is correct

For now I have no clear idea how to do that as I had to set up project on my Windows PC because VS4Mac & Rider had massive problems to run the sample solutions.(Why btw. ?_? )

**Comment by jmielczarkowski** [comment]
That's same issue we have in our app from last year. We raise that topic but we couldn't understand the root cause, topic is open and stays for longer time, but I saw no one is taking care of that. Is there any chance that you will consider to improve it?


ref https://github.com/Mapsui/Mapsui/issues/1044

**Comment by charlenni** [comment]
I assume, that the end of the touch is catchend by the ScrollView and not propagated down to Mapsui. If I remember it correct, then iOS provides each time you touch the view a new value for the finger. So it isn't possible to see, which finger touches the view.

Is this a problem if Mapsui? Is this a problem of ScrollView? I assume the second one, but it isn't clear.

So: Don't use Mapsui in a ScrollView.

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
