### ISSUE TITLE
Drawables not visible on device

### ISSUE THREAD

**Issue by Bachensteffi** [Mapsui/Mapsui#1162]
I want to show a couple of polylines on my map. On the emulator, there is no problem but if I want to test it on my device (Samsung Galaxy A52; Red Velvet Cake 11.0) the polylines won't appear although the method is not throwing an exception.
Here is the method to create my polylines:
```csharp
        public void CreateRoute()
        {
            try
            {
                ReadCsvFile("RoutenBeispiel.CSV");
                AddRoutePositions();

                Position oldRoutePosition = new Position(RoutePositions[0].latitude, RoutePositions[0].longitude);
                Color oldProfileColor = Color.Black;

                foreach (RoutePosition routePosition in RoutePositions)
                {
                    Position position = new Position(routePosition.latitude, routePosition.longitude);
                    Color profileColor;

                    switch (routePosition.supportProfile)
                    {
                        case 1:
                            profileColor = Color.Black;
                            break;

                        case 2:
                            profileColor = Color.Green;
                            break;

                        case 3:
                            profileColor = Color.Blue;
                            break;

                        case 4:
                            profileColor = Color.Magenta;
                            break;

                        case 5:
                            profileColor = Color.Red;
                            break;

                        default:
                            profileColor = Color.Yellow;
                            break;
                    }

                    if (oldRoutePosition == position)
                    {
                        oldProfileColor = profileColor;
                        oldRoutePosition = position;
                    }

                    else
                    {
                        var polyline = new Polyline();
                        polyline.StrokeColor = oldProfileColor;
                        polyline.StrokeWidth = 5;
                        polyline.Positions.Add(oldRoutePosition);
                        polyline.Positions.Add(position);

                        _mapView.Drawables.Add(polyline);

                        oldRoutePosition = position;
                        oldProfileColor = profileColor;
                    }
                }
                Console.WriteLine("Route erstellt");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
```
Does anyone know how I can fix this?

**Comment by pauldendulk** [comment]
Perhaps you can get some information by attaching a logger:
https://mapsui.com/documentation/how-to-work-with-mapsui.html#logging

**Comment by Bachensteffi** [comment]
Unfortunally I don't get more information. Maybe I didn't use the logger in the correct way (never used one before).
I debugged the hole method on the device and it seems like the polylines are created an has been added to _mapView.Drawables.

I also wrote a method which should create dots instead of lines for the route. Same as before the dots show up on the emulator but in this case the screen is turning black on the device...

Here are the pictures of how it looks like on the emulator:
![grafik](https://user-images.githubusercontent.com/87804081/126636633-f56fa58f-e3e4-4d74-9221-596256137579.png)

For the case I wasn't using the logger correctly, can you please give me a hint how to use it in the "try" part of my code?
My logger configuration:
`Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .CreateLogger();`

**Comment by pauldendulk** [comment]
Use the Mapsui logger to listen to like in the sample I pointed at in the url

```csharp
            Logger.LogDelegate += (level, message, exception) =>
            {
                // Here write the log message to your own logger
                Console.WriteLine(message);
            };
```

**Comment by charlenni** [comment]
Did you test your app on any other device too? Are there the same problems? I wouldn't assume this. Perhaps it is a problem with the drivers for the graphics of your special device and Android 11. If yes, then it would be a SkiaSharp or Skia problem.

**Comment by Bachensteffi** [comment]
I'm sorry for not answering. Haven't had time to code the last month. But now I'm back for the problem.

Yes, I did test it on an other device. Same problem. I the OS of the other smartphone is Andoid 10, but I have to check it

**Comment by janusw** [comment]
Some questions:
* Which version of Mapsui are you using?
* Are you using Mapsui.UI.Android or Mapsui.UI.Forms?
* Can you run the Mapsui Samples app? There is an "Add Polyline" sample in there. Does it work on the same device?

**Comment by janusw** [comment]
>     * Are you using Mapsui.UI.Android or Mapsui.UI.Forms?

Just noticed that I can probably answer this one myself: Since you're using the MapView, it must be Mapsui.UI.Forms.

**Comment by janusw** [comment]
>     * Can you run the Mapsui Samples app? There is an "Add Polyline" sample in there. Does it work on the same device?

To try this, check out the Mapsui repo, then build and run the "Mapsui.Samples.Forms.Android" project on your device.

**Comment by Bachensteffi** [comment]
I'm using Mapsui.Forms 3.0.0-rc.1

I also can't run the sample app yet. Need to install the .NET framework 4.8 which I can't find on the website from microsoft. But I didn't spend much time to search for it yet. When I can run the sample app I will inform you.

**Comment by janusw** [comment]
> I also can't run the sample app yet. Need to install the .NET framework 4.8 which I can't find on the website from microsoft.

Which sample app are you trying to run exactly? Mapsui.Samples.Forms.Android should not need .NET framework 4.8, I think ...

**Comment by Bachensteffi** [comment]
Never mind. There was a problem with the download. I redownloaded the project. Now it is running. Here the polylines are visible.

**Comment by janusw** [comment]
That's good. Then there must be something about your custom project. Could you provide a reproducible code sample, please? Meaning: Not just a snippet, but a full (runable) project.

**Comment by Bachensteffi** [comment]
I think I find the problem by reproducing the code. I don't know when or why, but I must have uninstalled the package Mapsui and run the app just with Mapsui.Forms. There were missing dependencies, but I didn't get a warning.
**Thank you all for your help.**
