### ISSUE TITLE
LabelStyle struggle 

### ISSUE THREAD

**Issue by johanferguson** [Mapsui/Mapsui#1173]
I am developing a mobile app for offline mapping on Xamarin Forms.

I want to change the Font properties of my LabelStyle, however, the labels does not seem to respond to the Font properties I give it e.g. Bold that is set to true, does not show labels in Bold.

Pretty much tried every scenario, but can't get it to work as I wanted.

Johan

**Comment by janusw** [comment]
> I want to change the Font properties of my LabelStyle, however, the labels does not seem to respond to the Font properties I give it e.g. Bold that is set to true, does not show labels in Bold.

Could you give us an example of what exactly you are trying? There are many samples in the Mapsui repository, which are useful for reproducing issues like this (and in particular there is a LabelsSample in Mapsui.Samples.Common.Maps).

**Comment by johanferguson** [comment]
Below is my code sample.
When I for e.g. changing the FonFamily from "Arial" to "Arial Black" the font in the Label does not change to "Arial Black".
I have been through the sample you referred to, however, in no instance in the sample Font was specified in the LabelStyle.
Thus, my problem is with changing the Font.


public static LabelStyle SatelliteLabelStyling()
        {
            return (new LabelStyle
            {
                LabelColumn = "VDNumber",
                CollisionDetection = true,
                WordWrap = Mapsui.Styles.LabelStyle.LineBreakMode.TailTruncation,
                BackColor = new Brush(Color.Transparent),
                Opacity = 1,                
                ForeColor = Mapsui.Styles.Color.Opacity(Mapsui.Styles.Color.FromArgb(255, 0, 61, 98), 1),
                Font = new Font { FontFamily = "Arial", Size = 17 },
                Halo = new Pen(Color.White)
            });
        }

**Comment by johanferguson** [comment]
I am developing on Xamarin Forms (not by choice)
The font families I am testing with are very common fonts e.g. Arial, Arial Black, Times New Roman and Courier New.
Apart from that, the bold property = true also seems not to have an effect.

**Comment by janusw** [comment]
> I am developing on Xamarin Forms (not by choice)

Yeah, you mentioned that. But what hardware/OS platform(s) do you want to you run this on in the end? Android and iOS, I assume?

> The font families I am testing with are very common fonts e.g. Arial, Arial Black, Times New Roman and Courier New.
> Apart from that, the bold property = true also seems not to have an effect.

Well, only because these are "common" fonts it doesn't mean that they will are available automatically, in particular if you have a cross-platform app that targets multiple OS (in multiple versions).

From https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#set-the-font-family:

> Therefore, the most reliable approach for specifying a font family is to use a custom font.
