### ISSUE TITLE
"Mouseover" event not detecting feature

### ISSUE THREAD

**Issue by nabeelio** [Mapsui/Mapsui#1181]
Hi,

I'm not sure if I'm doing this wrong, but it looks like the `GetMapInfo()` isn't detecting features on the mouse-over callback. So as a test, using the WPF example, specifically the MapInfo sample. I modified the MouseMove method to this:

```csharp
private void MapControlOnMouseMove(object sender, MouseEventArgs e)
{
    var screenPosition = e.GetPosition(MapControl);
    var worldPosition = MapControl.Viewport.ScreenToWorld(screenPosition.X, screenPosition.Y);
    var mapInfo = MapControl.GetMapInfo(worldPosition);
    var isFeature = mapInfo.Feature != null;
    MouseCoordinates.Text = $"{worldPosition.X:F0}, {worldPosition.Y:F0}, isFeature={isFeature}";
}
```

I'm trying to have it so if you mouse over a certain feature, it will add a feature to another layer showing a popup with some text. `IsMapInfoLayer` is set to `true`.

**Comment by pauldendulk** [comment]
That is because the WPF Point needs to be converted to a Mapsui Point.
```
var mapInfo = this.MapControl.GetMapInfo(screenPosition.ToMapsui());
```

Be careful, this may impact performance.

**Comment by nabeelio** [comment]
Great, thanks, that worked excellently. Don't seem to be seeing any CPU spikes but I'll keep an eye on that. Thanks!

**Comment by pauldendulk** [comment]
Summary: 
- There is no built in support for MouseOver. 
- You could implement is yourself by requesting the GetMapInfo on the MouseOver of the platform. 
   - Don't forget to set `ILayer.IsMapInfoLayer = true;`.
   - You need to realize this impacts performance.
