### ISSUE TITLE
IProvider - GetFeaturesInView not called when navigating map

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#1183]
I'm drawing a grid using a layer with a custom IProvider as datasource. Sometimes when navigating around (like panning the map) the function ' GetFeaturesInView' of the IProvider is not called (or very late), resulting in the grid not being visualized.

Demo:

![GetFeaturesInView](https://user-images.githubusercontent.com/538812/131153289-6c049c64-a90d-4b58-adc8-267e309c10c6.gif)

I've made a Xamarin.Forms project to reproduce, see project 'MemoryProvider' (branch bug/getfeaturesinview_not_called/) in the [samples/Mapsui.Samples.MemoryProvider folder](https://github.com/Mapsui/Mapsui/tree/bug/getfeaturesinview_not_called/Samples/Mapsui.Samples.MemoryProvider/MemoryProvider/). For the custom IProvider see [GridMemoryProvider.cs](https://github.com/Mapsui/Mapsui/blob/bug/getfeaturesinview_not_called/Samples/Mapsui.Samples.MemoryProvider/MemoryProvider/MemoryProvider/GridMemoryProvider.cs)

So far I've tested on UWP.

**Comment by pauldendulk** [comment]
I can reproduce the problem. It seems it never occurs when you drag, wait and do mouse up, and it does occur sometimes if you do the mouse up while dragging. In that case the map has some inertia and is sliding. So probably there is some problem with sliding logic. 

Is this what you see also?

**Comment by bertt** [comment]
yes it happens with a quick sequence of mouse down. mouse move, mouse up

**Comment by pauldendulk** [comment]
I think that the critical part is that you do the mouse up while moving the mouse.

**Comment by pauldendulk** [comment]
I pushed a MapView.UseFling property (set to false) to your branch. I could not reproduce your problem with it. Perhaps you can also check if this solves your other problem.

**Comment by pauldendulk** [comment]
see: https://github.com/Mapsui/Mapsui/blob/bug/getfeaturesinview_not_called/Mapsui.UI.Forms/MapControl.cs#L143

**Comment by bertt** [comment]
tested, works much better :-) But it seems the MapView.Info event is now broken?

**Comment by pauldendulk** [comment]
Apparently the scope was too broad, was confused by the comment, how the new push:

**Comment by bertt** [comment]
yep, Info event does work again 👍

**Comment by pauldendulk** [comment]
I will create a PR with an HasFling property. The property will default be true, so you have to set it to false yourself. So for other users there will still be two bugs that need to be resolved at some point.

**Comment by charlenni** [comment]
You don't need a HasFling flag. It is enough to describe to the Fling event and set the Handled flag to false. This means, that the user has handled the Fling event and the default behavior isn't triggered.

**Comment by charlenni** [comment]
The problem is Layer.cs, line 156.

While a fling takes place, the data of the map is updated always with Continously.  So, I assume for performance reasons, the data is never loaded. 

To load the data at the end of the fling, you have to create a FlingEnd method for the fling animation, that loads the missing data and displays it correct. That should solve the problem.

**Comment by pauldendulk** [comment]
> The problem is Layer.cs, line 156.
> 
> While a fling takes place, the data of the map is updated always with Continously. So, I assume for performance reasons, the data is never loaded.
> 
> To load the data at the end of the fling, you have to create a FlingEnd method for the fling animation, that loads the missing data and displays it correct. That should solve the problem.

Yes, something like this. For responsiveness/performance it is important to not fetch data in continuous mode. What surprises me is that there is an a data update most of the time, what triggers this? It looks like there is already a mechanism for an update at FlingEnd but it does not work perfectly.

**Comment by charlenni** [comment]
Are we sure, that there isn‘t a move in between the fling events. Because a move event would trigger an update.

**Comment by bertt** [comment]
fixed in https://github.com/Mapsui/Mapsui/pull/1198
