### ISSUE TITLE
Map navigates to wrong area

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#1188]
Sometimes when doing a very quick sequence of mouse down/mouse move/mouse up the map navigates to a complete other area (could be countries away). I've seen this behaviour on IPhone but it's not very easy to reproduce.

Sample:

https://user-images.githubusercontent.com/538812/132014787-9a411da8-f8bc-446b-8a4a-d6a7035b35c9.MP4

Suggestion: Make it possible to disable map animation (fly to?)

**Comment by charlenni** [comment]
@bertt Thank you bringing this up. But which part of Mapsui do you use? UI.iOS or UI.Forms?

Do you think, that the view thinks it is a double click?

**Comment by bertt** [comment]
Hi yes Xamarin.Forms

**Comment by janusw** [comment]
I have also seen behavior like this with UI.Forms occasionally.

> Do you think, that the view thinks it is a double click?

Don't think so (why would a double-click take you to a totally different area?). Maybe rather an out-of-control swiping / panning operation?

@bertt Are you using the MapView class, or just the MapControl?

**Comment by bertt** [comment]
This issue is fixed in other map navigation issue by @pauldendulk , see https://github.com/Mapsui/Mapsui/issues/1183#issuecomment-912627184

I'll close this issue.
