### ISSUE TITLE
TileFetcher Race Condition

### ISSUE THREAD

**Issue by scottdewald** [Mapsui/Mapsui#12]
The _retries dictionary needs to be locked before it is accessed since it is accessed by multiple threads. An exception can be thrown at line 179 when it checks if a value is in the dictionary and then adds it. In between this check/add, if another thread adds the value this thread will fail when it tries to add it as well.

**Comment by pauldendulk** [comment]
I got this exception on iOS:

> at System.Collections.Generic.Dictionary`2<!0, !1>.get_Item (!0) [0x00021] in /Users/builder/data/lanes/1503/6481535e/source/mono/external/referencesource/mscorlib/system/collections/generic/dictionary.cs:176

> at (wrapper unknown) object.gsharedvt_in () 

> at Mapsui.Fetcher.TileFetcher.GetTilesMissing (
    System.Collections.Generic.IEnumerable`1<BruTile.TileInfo>,
    BruTile.Cache.MemoryCache`1<Mapsui.Providers.Feature>,
    System.Collections.Generic.IDictionary`2<BruTile.TileIndex, int>,int) 

> at Mapsui.Fetcher.TileFetcher.TileFetchLoop (object) 

> at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) 

The only get_Item directly in GetTilesMissing is on _retries but _retries is only accessed on the looper thread. I rewrote the retries class to make the code cleaner and to make absolutely sure it is accessed on a single thread only (by checking the managed thread id). This behaves as expected on Windows. Idon't see how this could have been a problem.
