### ISSUE TITLE
Split up the Mapsui.Native package

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1207]
Proposed by @pauldendulk in #1206:

> Also, I think that WPF should be in a separate package. The 'Native' phrase stems mostly from 'native mobile' in the context of Xamarin development. Also, I think it is a totally different user group.

There were some comments about this before (see #1034), which were not really picked up in the discussion of #1175. I see two options for the split-up:

1. Split Mapsui.Native into Mapsui.Win (UWP & WPF) and Mapsui.Mobile (iOS & Android). Or ...
2. Split it into four different packages: Mapsui.UWP, Mapsui.WPF, Mapsui.iOS and Mapsui.Android.

The latter provides clearer separation of the platforms, but there were some concerns about inflation of the number of packages.

**Comment by pauldendulk** [comment]
My proposal was to split off a Mapsui.Wpf nuspec. 

Motivation:
- WPF is used independently of the other platforms. I certainly don't see WPF and UWP used together, they are both Windows, but if you build one you do not build the other. I don't like the idea of combining them in one package.
- I expect that WPF will be in use for longer period, so it will have it's own timeline. While the other platforms will be replaced more and more by Xamarin.Forms and MAUI.
- I could make sense to split the packages up even further to also add separate UWP, iOS ad Android packages. That also means adding 3 other nuspecs that need to be maintained. I think that is a big investment especially when it is not clear how long will will be maintaining them. If the nuget download number are low we may stop supporting them for the next release.

**Comment by pauldendulk** [comment]
We also split off other platforms in a later PR. For instance, it would perhaps make sense to move UWP to a separate package because I don't think this is often used in combination with iOS and Android. But then again, I wonder if that is worth the investment.

**Comment by pauldendulk** [comment]
A general remark. I understand that you want to move towards a more formal process. That's okay. We can move there step by step, but at the moment there is a release out that is not functioning. So there is some urgency here.

**Comment by pauldendulk** [comment]
I added a PR: https://github.com/Mapsui/Mapsui/pull/1208

**Comment by charlenni** [comment]
I would say a Mapsui.WPF, a Mapsui.Mobile (UWP, iOS, Android) and a Mapsui.Forms is ok. Later there could be a Mapsui.Maui.

**Comment by janusw** [comment]
> I would say a Mapsui.WPF, a Mapsui.Mobile (UWP, iOS, Android) and a Mapsui.Forms is ok. Later there could be a Mapsui.Maui.

Don't know. Windows/UWP is practically dead on mobile devices AFAIK, so I see UWP more on the desktop.

The typical duopoly on mobile has been Android & iOS for quite some time now. But I expect most mobile app to target Mapsui.Forms anyway.

In any case, if we start splitting off a single platform now, it would be more consistent to have them all separate IMHO. The advantages are:
* packages become even smaller
* bugs like #https://github.com/Mapsui/Mapsui/issues/1115 really only bite a single platform (Android in this case)
* nuget.org download statistics give us a better idea of how much each platform is used

Is it so much more overhead to have 6 packages instead of 4, @pauldendulk? The packages are built automatically, and you even have a script to batch-upload them to nuget.org in one go, right?

**Comment by pauldendulk** [comment]
> Is it so much more overhead to have 6 packages instead of 4, @pauldendulk? The packages are built automatically, and you even have a script to batch-upload them to nuget.org in one go, right?

The overhead is in the maintenance. More files to track, more files to change if we need updates. Still, it may be worth it.

**Comment by janusw** [comment]
> > Is it so much more overhead to have 6 packages instead of 4, @pauldendulk? The packages are built automatically, and you even have a script to batch-upload them to nuget.org in one go, right?
> 
> The overhead is in the maintenance. More files to track, more files to change if we need updates. Still, it may be worth it.

Maintenance might even become simpler, since things are more cleanly separated. If dependencies change in one particular package, you do not need to change the others.

Plus, if we generate a package from one particular VS project, we may not even need a nuspec for that one at all (which means less maintenance overhead).

**Comment by pauldendulk** [comment]
> Plus, if we generate a package from one particular VS project, we may not even need a nuspec for that one at all (which means less maintenance overhead).

I think that this would be a big simplification and I was also thinking about this. But if you do that for one project in our current solution you do not get the dependency on the Mapsui nuget. Alternatively we could do this for all our projects. This would mean we get separate nugets for Mapsui.Rendering.Skia and Mapsui.Rendering.Xaml as well. Also if we split projects further this will immediately result in more nugets. For the NTS support feature I intended to split Mapsui into Mapsui and Mapsui.Layers, en perhaps more projects. I don't think I want those as packages. In another project I use NuGet.Build.Packages to bundle projects into one, but it is not supported anymore. Perhaps there is an alternative now (it was years ago that i worked on this).

**Comment by pauldendulk** [comment]
@janusw @charlenni @bertt @inforithmics I have looked into alternatives for the nuspec, but so far found nothing that I am enthusiastic about (not convinced by nugetizer yet). I think we will find a good option for generating nugets form the csproj at some point, but just not today. Still, the thought of having separate nuget packages for each UI project has become more attractive to me. So, what I am thinking now is to create those separate nuspecs anyway. Best to have the packages organized this way from the start. I could work on this tomorrow. So what would have then:

- Mapsui
- Mapsui.Forms
- Mapsui.Wpf
- Mapsui.iOS
- Mapsui.Android
- Mapsui.Uwp

- Mapsui.Native will have to be deprecated.

Another options would be to add the UI in the name following the project name. There is something to say for that but that would change Mapsui.Forms to Mapsui.UI.Forms which would not be nice. Also the package could have additional dlls. For instance Mapsui.Wpf has the xaml dll. So I think it is better to leave the UI part out.

So, let's go for it?

**Comment by janusw** [comment]
> So, let's go for it?

Fine with me. I already explained the advantages I see in this scheme (see above), and I don't see any major problems with it. 

Deprecating Mapsui.Native is not a big deal, since it does not even exist for a week (and doesn't work fully yet, at least not on WPF).

**Comment by inforithmics** [comment]
Fine with me too.

**Comment by charlenni** [comment]
It is ok for me. That's the way I would expect it.

**Comment by pauldendulk** [comment]
Just released the split up nugets.

I tested the wpf getting started sample and it works.

**Comment by janusw** [comment]
> Just released the split up nugets.

👍 🥳 

> I tested the wpf getting started sample and it works.

Speaking of which: The getting-started guides still refer to Mapsui.Native, right?
