### ISSUE TITLE
BoundingBox and NavigateTo not work

### ISSUE THREAD

**Issue by aprilesalvatore** [Mapsui/Mapsui#1231]
Hi guys,
I've a series of pins in the map and I want to zoom only on area covered from pins. I use this function to calculate a bundle box 👍 

public static BoundingBox ToBoundingBox(this IList<Pin> pins)
        {
            var geometries = pins.Select(x => SphericalMercator.FromLonLat(x.Position.Longitude, x.Position.Latitude)).ToList();
           
            if (geometries.Count == 0) return null;

            var minX = geometries.Min(g => g.BoundingBox.MinX);
            var minY = geometries.Min(g => g.BoundingBox.MinY);
            var maxX = geometries.Max(g => g.BoundingBox.MaxX);
            var maxY = geometries.Max(g => g.BoundingBox.MaxY);

            return new BoundingBox(minX, minY, maxX, maxY);
        }

and  I call in this way:

var boundingBox = mapView.Pins.ToBoundingBox();
mapView.Navigator.NavigateTo(boundingBox, ScaleMethod.Fit);

and I've this result:

![WhatsApp Image 2021-09-21 at 21 22 13](https://user-images.githubusercontent.com/13586739/134234718-0737473d-f287-4459-90c5-2e85ff5c583d.jpeg)

but my expected result should  be :
![WhatsApp Image 2021-09-21 at 21 22 23](https://user-images.githubusercontent.com/13586739/134234761-bd032a67-3077-4928-8dd8-e3052561cd95.jpeg)

where is my mistake ?

**Comment by charlenni** [comment]
Did you checked the BoundigBox in between? If yes, what values do you get? What are the converted values for the pins?

**Comment by charlenni** [comment]
And the converted values, which are used to calculate the BoundingBox?

**Comment by aprilesalvatore** [comment]
var geometries = pins.Select(x => SphericalMercator.FromLonLat(x.Position.Longitude, x.Position.Latitude)).ToList();

**Comment by aprilesalvatore** [comment]
Is there some configuration that I've set ?

**Comment by aprilesalvatore** [comment]
Do i neeed to set some info in viewport? how do I do ?

**Comment by charlenni** [comment]
I checked it here and found, that it worked like a charm. So it must be something on your side.

For an image as you showed, the width of the BoundingBox had to be around 70 millions. For your pins you should get the following values for the BoundingBox:

    Min = {POINT (1033324.65383779 5012688.29449056)}
    Max = {POINT (1872547.26679702 5780452.83896506)}
    Width = 839222.6129592323
    Height = 767764.54447449371

If you don't get such values, your part before creating the BoundingBox is buggy. If you get this values, then something with the navigation is wrong.

**Comment by aprilesalvatore** [comment]
Thank !

**Comment by charlenni** [comment]
@aprilesalvatore It would be nice if you could explain, what solved your problem.

And if it is solved, could you close the issue?

**Comment by aprilesalvatore** [comment]
I've created this functions:

  public static void ZoomToBox(this INavigator navigator, Mapsui.Geometries.Point beginPoint, Mapsui.Geometries.Point endPoint)
        {
            var width = Math.Abs(endPoint.X - beginPoint.X);
            var height = Math.Abs(endPoint.Y - beginPoint.Y);
            if (width <= 0) return;
            if (height <= 0) return;

            var info = DeviceDisplay.MainDisplayInfo;

            var xamarinWidth = (info.Width / info.Density) - 50;
            var xamarinHeight = (info.Height / info.Density) - 50;

            Mapsui.Utilities.ZoomHelper.ZoomToBoudingbox(beginPoint.X, beginPoint.Y, endPoint.X, endPoint.Y,
                xamarinWidth, xamarinHeight, out var x, out var y, out var resolution);

            navigator.NavigateTo(new Mapsui.Geometries.Point(x, y).BoundingBox.Centroid, resolution);
        }

**Comment by pauldendulk** [comment]
I don't understand why such a helper function should be needed. Either there is a bug in our code or you do something wrong in your initial sample (but I don't see how).

Since it is important to me that the Navigation code work correctly I tested it by modifying the AsyncLayer sample and used a version of your initial extension method. It works as expected. This is the whole sample:

```csharp
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Mapsui.Geometries;
using Mapsui.Layers;
using Mapsui.Projection;
using Mapsui.Providers;
using Mapsui.Styles;
using Mapsui.UI;
using Mapsui.Utilities;
using Newtonsoft.Json;

// ReSharper disable UnusedAutoPropertyAccessor.Local

namespace Mapsui.Samples.Common.Maps
{
    public class AsyncFetchSample : ISample
    {
        public string Name => "Async fetch";
        public string Category => "Special";

        public void Setup(IMapControl mapControl)
        {
            mapControl.Map = CreateMap();
        }

        public static Map CreateMap()
        {
            var map = new Map();

            map.CRS = "EPSG:3857";
            map.Transformation = new MinimalTransformation();

            map.Layers.Add(OpenStreetMap.CreateTileLayer());
            var cities = GetCitiesFromEmbeddedResource();
            map.Layers.Add(CreateAsyncLayer(cities));
            map.Home = n => n.NavigateTo(ToBoundingBox(cities));

            return map;
        }

        public static BoundingBox ToBoundingBox(IEnumerable<IFeature> pins)
        {
            var geometries = pins.Select(x => SphericalMercator.FromLonLat(x.Geometry.BoundingBox.Centroid.X, x.Geometry.BoundingBox.Centroid.Y)).ToList();

            if (geometries.Count == 0) return null;

            var minX = geometries.Min(g => g.BoundingBox.MinX);
            var minY = geometries.Min(g => g.BoundingBox.MinY);
            var maxX = geometries.Max(g => g.BoundingBox.MaxX);
            var maxY = geometries.Max(g => g.BoundingBox.MaxY);

            return new BoundingBox(minX, minY, maxX, maxY);
        }

        private static Layer CreateAsyncLayer(IEnumerable<IFeature> cities)
        {
            // The Layer type fetches data asynchronous (it should be renamed). 
            // This impacts the speed with which data is shown after panning. 
            // This Delayer class is used to filter a continuous stream of 
            // RefreshData requests.
            return new Layer
            {
                Name = "Async Layer",
                IsMapInfoLayer = true,
                DataSource = new MemoryProvider(cities) { CRS = "EPSG:4326" },

                Style = CreateBitmapStyle()
            };
        }

        private static IEnumerable<IFeature> GetCitiesFromEmbeddedResource()
        {
            var path = "Mapsui.Samples.Common.EmbeddedResources.congo.json";
            var assembly = typeof(PointsSample).GetTypeInfo().Assembly;
            var stream = assembly.GetManifestResourceStream(path);
            var cities = DeserializeFromStream<City>(stream);

            return cities.Select(c =>
            {
                var feature = new Feature();
                var point = SphericalMercator.FromLonLat(c.Lng, c.Lat);
                feature.Geometry = new Point(c.Lng, c.Lat);
                feature["name"] = c.Name;
                feature["country"] = c.Country;
                return feature;
            }).ToList();
        }

        private class City
        {
            public string Country { get; set; }
            public string Name { get; set; }
            public double Lat { get; set; }
            public double Lng { get; set; }
        }

        public static IEnumerable<T> DeserializeFromStream<T>(Stream stream)
        {
            var serializer = new JsonSerializer();

            using (var sr = new StreamReader(stream))
            using (var jsonTextReader = new JsonTextReader(sr))
            {
                return serializer.Deserialize<List<T>>(jsonTextReader);
            }
        }

        private static SymbolStyle CreateBitmapStyle()
        {
            // For this sample we get the bitmap from an embedded resource
            // but you could get the data stream from the web or anywhere
            // else.
            var path = "Mapsui.Samples.Common.Images.home.png"; // Designed by Freepik http://www.freepik.com
            var bitmapId = GetBitmapIdForEmbeddedResource(path);
            var bitmapHeight = 176; // To set the offset correct we need to know the bitmap height
            return new SymbolStyle { BitmapId = bitmapId, SymbolScale = 0.20, SymbolOffset = new Offset(0, bitmapHeight * 0.5) };
        }

        private static int GetBitmapIdForEmbeddedResource(string imagePath)
        {
            var assembly = typeof(PointsSample).GetTypeInfo().Assembly;
            var image = assembly.GetManifestResourceStream(imagePath);
            return BitmapRegistry.Instance.Register(image);
        }
    }
}
```
