### ISSUE TITLE
Adding image in callout

### ISSUE THREAD

**Issue by SivaG017** [Mapsui/Mapsui#1235]
I want adding images in callout panel.

**Comment by janusw** [comment]
Have a look at https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/PinSample.cs. If you run this through one of the Samples apps, you'll see that some of the callouts that appear when clicking the map contain a blue dot image.

I think this is done through the `Callout.Content` property. Unfortunately it isn't documented very well, but at least the documentation of `CalloutStyle.Content` tells us that it's supposed to be a bitmap id.
