### ISSUE TITLE
How to set layer order pins & track

### ISSUE THREAD

**Issue by dinonovak** [Mapsui/Mapsui#1251]
I am adding pins and map track on the map
pins are added using
```
((ObservableRangeCollection<Pin>)((MapView)mapView).Pins).AddRange(list);
```
and track is added  using
```
List <MemoryLayer> trackLayers = addRoute();
            foreach (var trackLayer in trackLayers)
            {
                trackLayer.Name = "ImotaRoute";
                map.Layers.Add(trackLayer);
                Thread.Sleep(1);
            }
```

The issue is that pins are added behind the track layer so even callouts are behind the track
https://ibb.co/KrCn4Wj

When map is created I am first adding track and then pins.
I there any way to control z-order of the layers. I suppose that issue is that track layers are added (so added on top of existing. map) while adding pins to existing observable collection is adding them to map below.

**Comment by charlenni** [comment]
That‘s strange. You use the MapView control? There are the 4 main layers (drawables, pins, callouts and my location), which stay always on top. If you add another layer, then this layer should lay below this 4 layers.

Could you provide the complete code?

**Comment by FrozDark** [comment]
I confirm that layers added latest are on top of other existing layers so I do insert at index 0
I think it happens after setting the map to the mapcontrol

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
