### ISSUE TITLE
Little change to MinimalTransformation if fromCRS toCRS are equal return point unchanged

### ISSUE THREAD

**Issue by FrozDark** [Mapsui/Mapsui#1316]

**Comment by pauldendulk** [comment]
There is a change when there should be none? 

The MinimalTransformation does indeed transform to and from EPSG:4326. It could just check if the fromCRS and toCRS are the same and return the input.

**Comment by FrozDark** [comment]
I did set map.CRS to "EPSG:4326" and made transformation like this `mapView.Map.Transformation.Transform(mapView.Map.CRS, "EPSG:4326", (Point)mapView.Viewport.Center);`

Looking though it I realized that Viewport.Center is type of "EPSG:3857"

So I would like to ask what is the puprose of map.CRS property? Just for holding the type of map is using?

**Comment by pauldendulk** [comment]
Perhaps we can help you better if you explain what you are trying to do and how it fails.

Some background info that might be relevant:
- The Map.CRS indicates the projection of the visible map. It can be used to transform data that is in another CRS to that Map.CRS. This can be data in a IProvider. See the projection sample for that scenario.
- The TileLayers can not be projected. The OpenStreetMap layer is in EPSG:3857. If you set the Map.CRS to EPSG:4326 and use the OpenStreetMap layer this is a configuration error. We should log a warning if this occurs.
- The Mapview has some functionality to make it easy to work with a EPSG:3857 map and coordinates in EPSG:4326. If that is your scenario I don't think you need anything special. It is however something I have little knowledge of. CC @charlenni.
