### ISSUE TITLE
Draw a viewfinder (red cross) on the map center

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#1320]
Hi there,
I need to draw a viewfinder (red cross) on the map center.
I've tried to draw line with skiaforms:SKCanvasView thats overlap the map view control.
The result is that the the map no longer moves with dragging.
I don't know if this is a bug or is a normal behavior.
Any ideas on how to do it?
Thank you.

**Comment by gpsaliola** [comment]
I've solved with InputTransparent="True" property on skiaforms:SKCanvasView.

**Comment by pauldendulk** [comment]
Are you using a custom renderer?

**Comment by charlenni** [comment]
No, the solution uses a second canvas view (in addition to the canvas view Mapsui uses). But than all imputes are grabbed by the top most canvas view.

Another possible solution would be to use a custom widget.

**Comment by gpsaliola** [comment]
InputTransparent = "True" also works with a XAML "Line" object that overlaps the map.
It seems to me a simple and functional solution.
