### ISSUE TITLE
SphericalMercator.ToLonLat Accuracy loss

### ISSUE THREAD

**Issue by patricklee90** [Mapsui/Mapsui#1382]
Hi,

I refer to this post [Link](https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/projections.md), Mapsui is running under CRS EPSG:3857 and I required to do the conversion in order to use outside for my project that working under CRS EPSG: 4326.

double longt = 101.71046179910427;
double lat = 3.1567427968766819;

var fromLatLng = SphericalMercator.FromLonLat(longt, lat);
var toLatLng = SphericalMercator.ToLonLat(fromLatLng.X, fromLatLng.Y);

Then the toLatLng outcome is 101.71046447753906, 3.1567425727844238

both point accuracy error is 30 cm which is the decimal point changed 0.00000xxx onward

before: 101.71046179910427, 3.1567427968766819
after:    101.71046[<strong >447753906</strong>], 3.156742[<strong>5727844238</strong>]

What should I do to make sure the conversion loss is less than 10 cm?

![image](https://user-images.githubusercontent.com/40401455/141647860-92c9219d-1a95-454f-a346-8f138875e3f4.png)

**Comment by pauldendulk** [comment]
Do you have version 3.0.0 or later?

**Comment by patricklee90** [comment]
> Do you have version 3.0.0 or later?

Hi @pauldendulk thanks for the answer!

It has been resolved after i upgraded to 3.0.0 onward

Thanks!
