### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#1385]
In some cases the map gets into a state where the zoom, user position and north buttons no longer respond. Furthermore, the map can be rotated with a single finger and it is no longer possible to move it.
Is there any way to restore this situation?
At the moment the only way I have found is to restart the application but if the user is recording its own track this is not possible.
Some idea?

**Comment by Sebastian1989101** [comment]
This sounds like the end of a previous touch event is not correctly registered. Do you have any reproduction project for this issue?

**Comment by gpsaliola** [comment]
Unfortunately, the behavior is not systematic and does not always occur.
Also when this happens the zoom, user position and north orientation buttons are frozen.

**Comment by pauldendulk** [comment]
This is now outdated. If something like this occurs please create a new bug report.
