### ISSUE TITLE
Animation without Timers

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1395]
### Background

This is an idea which has been in the back of my mind for a long time. I could not make time for it so far and expect this won't change soon. By creating this issue and having some discussion around it perhaps we could make some progress. Perhaps someone else could pick this up.

### Why No Timers?
- **Performance:** Timers consume a thread and thread starvation can cause serious performance problems. A discrete performance decrease can arise when virtual threads are used instead of CPU threads.
- **Memory Leaks:** Timers need to be disposed and if they don't get disposed cause memory leaks https://github.com/Mapsui/Mapsui/pull/1390
- **Growing number of timers:** We have various things that need to be animated, like the animated viewport or animated features. Animated features get triggered by a data source with it's own timer. Multiple animated layers will mean multiple timers.
- **Syncing:** We can avoid the problem of syncing the animation state with the render update loop frequency. This frequency can vary, so it is hard to know in advance what the state of an animation should be on the next draw operation.

### How?
- Only the render loop should have a frequent update. Perhaps we need a single timer here, but I think it is possible to remove that one too (Let the renderer call Invalidate and do a Thread.Sleep before the next update is due). 
- In the render loop before rendering call een UpdateAnimations method on the objects supporting animation. The implementations should keep track of the origin-time/position and the target-time/position, and the easy function. The UpdateAnimation method will calculate the current position based on that. 
- A variation on the above is that this calculation is done in the Layer.GetFeatures or Provider.GetFeatures methods. Perhaps this is better.
- We should not render when nothing has changed. Now we render based on the invalidate state. This is state that is triggered by an event. Perhaps we should be able to call invalidate with an end time.

### Alternative solutions
- Perhaps more efficient timers with thread reuse (Task.Run and other things in the async/await realm).
- A single global timer (or a more fancy schedular) where all classes can make use of.

**Comment by charlenni** [comment]
I had made this before, but dropped it, because you changed the Navigator in your way.

With #1397 there is only one timer in Mapsui: the render loop timer.  With these changes, there is only on static `Animations` object, which collects all `AnimationEntry`s. The `UpdateAnimations` function is called from the render loop. If there are any entries in the animations list, then an invalidation of the screen is made.
