### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by nasrul29** [Mapsui/Mapsui#1405]
Hi guys,

I have developed GIS/mapviewer (WPF) using mapsui 2.0.3 before and currently I need to add some features and I went to open the API documentation at https://mapsui.com/api/Mapsui.UI.Wpf.html and was surpised that the documentation has lost lots of information...what happened to it?

**Comment by pauldendulk** [comment]
This seems to be an error in building the docs. Not sure what is going on. First thing I can do it to use the same docker image when building the docs as when building the code.

**Comment by pauldendulk** [comment]
The vs 2022 image fixes the build errors but not the problem. Next is to inspect the warnings.

**Comment by pauldendulk** [comment]
@nasrul29 I updated the docfx version to the latest one. This seems to fix the problem. Perhaps you can check if you mis something.

There is another problem though. This documentation is generated from master and the most important documentation at this moment is for v3. We should generate several documentation sites, corresponding to a release. Probably in a folder that corresponds to it's version number.

**Comment by pauldendulk** [comment]
I created a US to support docs for several versions https://github.com/Mapsui/Mapsui/issues/1561

This issues itself has been fixed.
