### ISSUE TITLE
WPF memory leaks in navigation context

### ISSUE THREAD

**Issue by senchden** [Mapsui/Mapsui#1412]
Hello.
If WPF MapControl is located in a navigation context (i.e. `Page` within a `Frame` or `UserControl` in `ContentControl`) and user navigates back and forth between UserControls, the Controls that contain `MapControl` are not getting disposed of which leads to a memory leak. This happens even if I use the `master` branch. Quick memory debugging showed that it is related to `TimerCallback` - possibly relates to https://github.com/Mapsui/Mapsui/issues/1395 . What do you think of making the WPF `MapControl` `IDisposable`?

**Comment by senchden** [comment]
Great. I will be watching how it progresses

**Comment by ondrasvoboda** [comment]
Hi, I'm facing the same issue. 
@senchden does #1406 fix it for you?
@pauldendulk I see that #1406 was merged, when do you expect to be released?

**Comment by senchden** [comment]
@ondrasvoboda The automatic counting did not work for me, but since the `Dispose` method was made `public`, I decided to call `Dispose` manually. After that the leak was gone.

**Comment by ondrasvoboda** [comment]
That's good news, thanks. I need to wait till it's released then,

**Comment by pauldendulk** [comment]
This has been fixed.
