### ISSUE TITLE
Could not build using the WinUI 3.0.0-build.2484

### ISSUE THREAD

**Issue by pedroivobraga** [Mapsui/Mapsui#1413]
I'm trying to use MapsUI on the WinUI 3.
I'm adding reference to Nuget package 3.0.0-build.2484, but when I try to build it I'm receiving the following error:

Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Mapsui.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null.'

**Comment by inforithmics** [comment]
There missing assemblies in the Niger files. I will Make a pull request for Thema tomorrow.

**Comment by pauldendulk** [comment]
The nightly nuget is horribly outdated. There will be more changes soon when I move more code into Mapsui.Layers and Mapsui.Core back into Mapsui.

Also dependencies need to be added, like Xamarin.Essentials.

Perhaps this could be a reason to do all this new development in a branch. But then again, let's just keep this period short. I need to focus on NTS, after this things should fall into place again.

**Comment by inforithmics** [comment]
Pull request where I added Mapsui.Core to the Mapsui NuGet Package
https://github.com/Mapsui/Mapsui/pull/1417

**Comment by pauldendulk** [comment]
There is no WinUI nuspec yet. Should this not be added too?

**Comment by pauldendulk** [comment]
#1417 was merged.

**Comment by pauldendulk** [comment]
This was resolved.
