### ISSUE TITLE
Add Marker with title in WPF Mapsui 

### ISSUE THREAD

**Issue by idanmaman2** [Mapsui/Mapsui#1422]
hi , I can't understand how to add point to Mapsui map ( with and without a title) , adn i can find onlt data about xmarin and uwp and not for wpf ,, there is any clear code sample ? 
thanks Idan .

**Comment by charlenni** [comment]
Hello,

there isn't any difference in creating a point between Xamarin.Forms and WPF. The difference is only the control, which displays the map.

Look into the samples. For samples with text look into [this](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Symbols/LabelsSample.cs) sample.

**Comment by pauldendulk** [comment]
Also, checkout the develop/3.x branch to have samples that apply to v3. WPF has it's own sample project Samples/Mapsui.Samples.Wpf.
