### ISSUE TITLE
MbTiles + Sqlite-net-pcl issue

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#1424]
I added the Sqlite-net-pcl package to my app to manage a Sqlite database.
Since I added this package, the mbTiles display no longer works on iOS, while it continues to work on Android. 
An example can be downloaded at this link https://www.okmap.org/a/MbTilesExample.zip.
It can be easily verified that, if you uninstall the Sqlite-net-pcl package, the app will work again.
On iOS you need to put an MBTile map in the app's sandbox folder.
In Android, the map must be placed in the /Download/OkMap folder.
I'm sorry to raise all these issues but I hope to help improve this wonderful package.

**Comment by inforithmics** [comment]
This is not a Mapsui issue it is a issue of Sqlite.net-pcl that it doesn't work AOT Compiled on iOS

https://github.com/praeclarum/sqlite-net/issues/1067

So solution would be to downgarde sqlite to 1.7.335 
or don't AOT Compile the Application and use only Interpreter

**Comment by gpsaliola** [comment]
Thank you for the answer!
I downgraded Sqlite-net-pcl to version 1.7.335 but it didn't fix the problem.

**Comment by gpsaliola** [comment]
Eureka! It seem works properly with 1.6.292 version.
Thank you!
