### ISSUE TITLE
How to get data from the map 

### ISSUE THREAD

**Issue by idanmaman2** [Mapsui/Mapsui#1432]
![image](https://user-images.githubusercontent.com/90776557/146737418-371f3ead-9ab9-467f-a260-355ba6aa6fe1.png)

hi , I would like to get all  the points of the bus staions in certian area from the map ( lat long or x y ) is that possible ( only with mapsui) ? 
or even to get Ienumrable of all the busstaions that exsists and filter them by my self 
thanks Idan .

**Comment by pauldendulk** [comment]
The google map offers a map component including all the map data google offers. Mapsui is only a map component without the data. It is possible to add all kinds of data to it, but you need to first get access to such a data source. The default map shown in the picture is the openstreetmap tile layers. OpenStreetMap allows free use (if you include attribution) but it is now ours. So I guess the answer is no, unless you find such data yourself and find out how to add it as a layer in Mapsui.
