### ISSUE TITLE
Strange warping of raster features

### ISSUE THREAD

**Issue by faldor20** [Mapsui/Mapsui#1433]
I am trying to render some weather data onto a map of Australia. 
I get the data from a local weather service by downloading a jpeg of the current rain radar.
I then use a raster feature to render this forecast over Australia using the bounds of the original forecast query. When I do this however I get strange warping.
It seems as if the forecast is aligned at the top to bottom but the middle is warped somewhat

I was able to fix this by dividing the rendering up into many strips, as I said the tops and bottom of the square always render at the correct position/scale so I just made it so we never stray far from a top or bottom by cutting the image up into 10 strips and rendering those.

I am unsure why this is happening but I suspect it has something to do with strange map projection wizardry that I don't really understand.

Am I doing something wrong here?

Without sliced rendering
![image](https://user-images.githubusercontent.com/26968035/146882603-11fd7858-d4dc-4346-a3f1-3115b4e4a651.png)
With sliced rendering:
![image](https://user-images.githubusercontent.com/26968035/146882726-5d0f85d7-3d85-4410-a1eb-ad78246f96fd.png)

Code sample, in f#, but should still be pretty obvious
``` fsharp
let raster = new MRaster(bitmapStream, bounds|>LongLatToSherical)
let rasterFeature =new RasterFeature(raster)
let features:MemoryProvider<IFeature> =Providers.MemoryProvider([rasterFeature])
let weatherLayer =new MemoryLayer
    ("RasterLayer",
    DataSource=(features),
    CRS="EPSG:4326",
    Opacity=0.65)
let tiles=[|weatherLayer,osmLayer|]
let map =  new Mapsui.Map(
                    CRS = "EPSG:3857"
                                
                            ) 
map.Layers.Add tiles
```

**Comment by pauldendulk** [comment]
The openstreetmap tile layer is in the SphericalMercator projection "EPSG:3857". Is your raster source also in "EPSG:3857".?

**Comment by faldor20** [comment]
The raster source is a very large section of an epsg:4326 map. As far as i could tell from your documentation this shouldn't effect the rendering only the coordinate system. 
Is that not correct?

**Comment by pauldendulk** [comment]
In Mapsui is it not possible to convert rasters to another projection. Only geometries.

**Comment by pauldendulk** [comment]
What part of the documentation are you referring too? Perhaps it could be improved.
