### ISSUE TITLE
Set Pan/Zoom limit in WPF 3.0.2

### ISSUE THREAD

**Issue by blwhttngtn** [Mapsui/Mapsui#1443]
Hi! As always, very delighted to follow, consume, and promote Mapsui. I just upgraded our WPF Mapsui/MBTiles project from 1.4.8 to 3.0.2. There were a lot of good changes. Here's a screenshot of me taking a temporary stab at adjusting pan-and-zoom limits using the new architecture. Aside from this being tough to read, I can't quite pan over to our users in Australia. Please advise! 

P.S. I really liked the usage of Map.PanMode and Map.ZoomMode, but eager to see what is the equivalent in WPF 3+. Thanks!

![image](https://user-images.githubusercontent.com/12670350/148706766-d6099136-62f1-424d-ac11-c3c65d5dfbbb.png)

I should add that I've referenced the v2.0 upgrade guide at this URL: http://mapsui.com/documentation/v2.0-upgrade-guide.html.

**Comment by pauldendulk** [comment]
Not sure if this answers your question, but perhaps you should take a look at the KeepWithinExtentSample where ViewportLimiterKeepWithin is used. 

Current master is v4 there is a 'Navigation' category. Not sure if that is the case in develop/3.0.

**Comment by blwhttngtn** [comment]
Thank you @pauldendulk. This is helpful.
