### ISSUE TITLE
Question: Is it possible to Navigate to particular bounding rectangle after layers are created?

### ISSUE THREAD

**Issue by rajeshtamda** [Mapsui/Mapsui#1444]
Say I have 2 different layers of data representing 2 different things on the map and a tile layer.
If say I have applied a filter / search which applies only to 1 set of data, so my expectation here is to remove that 1 particular layer and re-add it with new set of data and then center the map to the bounding envelope of this layer.

As of now what I understood is to create a new instance  of map again and then re-create all layers and then add it to view to achieve this functionality.

Is there a way to optimize this if so how? (just to re-render that 1 particular layer and setting the viewport rectangle)

**Comment by pauldendulk** [comment]
If this is not about limiting the pan/zoom but just zooming into a certain area there should are easier solutions than to remove a layer. 

The MapControl.Navigator has several options to zoom to a certain area. You could use Navigator.NavigateTo(extent) with the Extent of the layer of interest as argument. But perhaps I do not understand your question.

Also it might be relevant to you to set ILayer.Enabled = false;

**Comment by rajeshtamda** [comment]
Setting Map.Home works fine only for the first time. Once I have my map visible with tile layer, some feature layers and tap of a button say I want to update one of the layer and then reset the visible map rect to the updater layer's extent that's when Map.Home is not working.
For now I am being force to create to map instance add all layers and then set Map.Home and then assign this new map instance to  MapControl's .Map property.

**Comment by pauldendulk** [comment]
You do not need the Home method. This is only intended as the default map extent. You call the MapControl.Navigator from your own code.

**Comment by rajeshtamda** [comment]
Thank you, this seems to work.
