### ISSUE TITLE
Creating custom (derived) Geometry is impossible to clone.

### ISSUE THREAD

**Issue by Hylke-Atmos** [Mapsui/Mapsui#1445]
The way Geometry is setup in MapSui makes it impossible to create custom (derived) Geometry, because it fails in to be able to be cloned or copied in some cases.

This issue is twofold:
1. Even though the IGeometry interface (and therefor IGeometryCollection) specify a clone function it is impossible to use (in particular in the collection classes such as GeometryCollection). These classes keep an Collection of Geometry objects instead of IGeometry objects also the IGeometry.Clone() function returns a Geometry which I think doesn't help either (but more about that later). When calling the Clone function on a GeometryCollection it will always throw an Exception: "Clone() has not been implemented on derived datatype", which is partially true but mainly because all derived classes redefine Clone() (using new keyword) returning their own type (probably for easier use in some other parts of the library), but therefor will not be called from within the Geometry collection, because that is calling Geometry.Clone()!
2. There is an alternative workaround created by the use of the "Copy" extension method, however this method checks the class name against any known class type. This works fine for known types within the library, but if you decide to create your own derived class, this doesn't work at all, since it is not part of the library.

In case you are wondering why would someone want to create their own derived class. I attempted to add an "ArrowLineString" which is a derived class from MultiLineString, and is intended to be a line between 2 points but with 2 additional linestringgeometries for visualizing an Arrow to indicate the direction of the line.

From what I saw a large refactor of the whole Geometry setup would be needed to solve this problem and make the whole geometry data model more abstract.

I was wondering;
- If it was intended this way?
- What was the intention of the public Clone() function if it is not intended to be used outside the library?
- Why is Clone() being redefined in all derived classes with the result of not being able to call clone on the abstract base class Geometry?
- If I'm missing something?
- If there are others who are running into the same issue?
- If there are plans on refactoring this part?
- If it would be appreciated when I help refactoring this?

**Comment by charlenni** [comment]
Sorry, that I couldn't say something to your problem, but I could say something about I would solve this.

Instead of using a new Geometry type use a custom style with a custom renderer and use the style for holding information about the arrow(s) and draw them by yourself.

**Comment by Hylke-Atmos** [comment]
Thanks for the response and although it is indeed a workaround for the problem, I personally think there is a bigger issue here.

If you would try to clone a GeometryCollection for example (which for example contains either a couple of different or even the same type of gemetries, such as LineStrings or even Points). You can't execute GeometryCollection.Clone(). It will simply crash! This is because it will iterate over the Collection<Geometry> and call Geometry.Clone(), but that will never work!
As mentioned above since all derived classes redefine the "Clone" function it will not call the derived Clone function it keeps trying to call Geometry.Clone(), which is not implemented.

I personally think redefining Clone was a bad idea (unless I'm missing something), because it breaks the inheritance capabilities while at some places there are references to the abstract base class Geometry.

**Comment by pauldendulk** [comment]
We are currently preparing to migrate from Mapsui.Geometries to NTS so I think this is something we will not fix.

**Comment by pauldendulk** [comment]
And thanks for reporting 🙂

**Comment by Hylke-Atmos** [comment]
Thanks for the quick response, is there a timeline when you are expecting the migration to NTS?

In the mean time I did find a good way to refactor this with only a little bit of effort. I can share it if you'd like?

**Comment by pauldendulk** [comment]
I can give no guarantees regarding timelines, sometimes nothing happens because there are other priorities. A release of v4 (using NTS) will take at least months.

As Mapsui.Geometries will be completely removed I really would like to avoid investing it any more. My time is very limited and I need to focus on the NTS conversion.

Regarding your questions about the Clone implementation. This is very old code. It was originally ported from some Java library. Then it was part of SharpMap, years before I got involved in that project. It needs to be removed because of the license.

**Comment by Hylke-Atmos** [comment]
Thanks for the update.

For now I'll deal with the solution I have.
I'll also share this solution in a pull request. This solution is mainly a different view of how the "Clone" interface has been defined and implemented.

I'll leave it up to you whether you think it is worth accepting for the time until NTS is migrated..

**Comment by pauldendulk** [comment]
This has now been replaced with NTS Geometry.Copy().
