### ISSUE TITLE
WPF Map Control Unresponsive (Mapsui.Wpf-Net472)

### ISSUE THREAD

**Issue by blwhttngtn** [Mapsui/Mapsui#1458]
I just updated a few users to Mapsui.Wpf-Net472. Users who are running 11th Gen Intel i7 chips are experiencing reproducible non-responsive WPF MapControl. 

After navigating to the 'map page', where the users expect to see a map, these users see a white/blank page. After resizing the application by stretching the edges of the application, the screen goes from white/blank to rendering appropriately. Sadly, the map is rendered, but the map is unresponsive/frozen.

Users who aren't running 11th Gen Intel i7 chips aren't experiencing this issue. I can provide more context, but I wanted to start the thread here first, and answer specific questions that anyone may have.

**Comment by inforithmics** [comment]
Are you eure that it ist mapsui.wpf- net472. Because as far as I Knie mapsui.wpf only Supports net48.

**Comment by charlenni** [comment]
If it is a special CPU problem, it could be a Skia problem.

**Comment by blwhttngtn** [comment]
> Are you sure that it is mapsui.wpf- net472. Because as far as I know mapsui.wpf only Supports net48.

![image](https://user-images.githubusercontent.com/12670350/151874192-349dcca0-5133-4a73-859f-7c6c1edfb476.png)

**Comment by blwhttngtn** [comment]
> 

Thank you will swap Skia packages to see if there's any change.

**Comment by blwhttngtn** [comment]
> If it is a special CPU problem, it could be a Skia problem.

Thank you. Good idea. I'll swap Skia packages to see if there's a change in behavior.

**Comment by pauldendulk** [comment]
The Mapsui.Wpf-Net472 package is not created by us. I had not seen it before. It is created by jwikberg 

- His nuget: https://www.nuget.org/packages/Mapsui.Wpf-Net472/ 
- His fork: https://github.com/jwikberg/Mapsui

**Comment by jwikberg** [comment]
I'd be surprised if this is related to targeting .Net 4.7.2 instead of 4.8.
@blwhttngtn Can you check if the official Mapsui package has the same issue on 4.8 with this CPU/GPU?

**Comment by pauldendulk** [comment]
Is UseGPU=false for MapControl? This has caused caused problems in the past. https://github.com/Mapsui/Mapsui/issues/1191

**Comment by inforithmics** [comment]
Wegen this helps it ist probably an Intel Graphocs Driver issue. Because Mapsui uses the Gpu to Render the Maps.

**Comment by blwhttngtn** [comment]
@inforithmics Yes, you're right it's an Intel Graphics Driver Issue! I've been able to move past the issue temporarily by asking our affected users to download an Intel Graphics Driver update. @pauldendulk, I hadn't modified the default value of MapControl's UseGPU.

**Comment by blwhttngtn** [comment]
> I'd be surprised if this is related to targeting .Net 4.7.2 instead of 4.8. @blwhttngtn Can you check if the official Mapsui package has the same issue on 4.8 with this CPU/GPU?

You're correct -- targeting was not the issue.

**Comment by pauldendulk** [comment]
Perhaps we should change the default. I will create an issue.

**Comment by pauldendulk** [comment]
Assuming this another UseGPU issue.
