### ISSUE TITLE
Is there a way to find out if a polygon shape is intersecting with the visible map rectangle? 

### ISSUE THREAD

**Issue by rajeshtamda** [Mapsui/Mapsui#1461]
I have couple of shapes on my map and based the shapes that are currently visible I need to update my legend. 
So I was wondering if we do have a way to find out if a polygon intersects with the visible map rectangle which will make my job lot easier.

**Comment by pauldendulk** [comment]
In the MemoryProvider.GetFeatures we select all features for which the extent is within the map extent. So this is not exactly what you are asking because it could be that the extent of a feature intersects while the geometry does not, but it may be sufficient. 

```csharp
        public virtual IEnumerable<T> GetFeatures(FetchInfo fetchInfo)
        {
            if (fetchInfo == null) throw new ArgumentNullException(nameof(fetchInfo));
            if (fetchInfo.Extent == null) throw new ArgumentNullException(nameof(fetchInfo.Extent));

            var features = Features.ToList();

            fetchInfo = new FetchInfo(fetchInfo);
            // Use a larger extent so that symbols partially outside of the extent are included
            var biggerBox = fetchInfo.Extent?.Grow(fetchInfo.Resolution * SymbolSize * 0.5);
            var grownFeatures = features.Where(f => f != null && (f.Extent?.Intersects(biggerBox) ?? false));

            return grownFeatures.ToList();
        }
```

**Comment by rajeshtamda** [comment]
I shall try this out shortly and let you know if the solution has addressed my specific use case.

**Comment by pauldendulk** [comment]
This is an old question also things have changed now that we are using NTS.
