### ISSUE TITLE
Is .Net Maui already supported?

### ISSUE THREAD

**Issue by Phil4121** [Mapsui/Mapsui#1465]
Hi!
I'm playing around with .Net Maui and would like to add a map to my sample app. I've already tried a few other APIs but nothing really works. So I found "Mapsui" and was very happy that this projekt already provides samples for .Net Maui. I've added 3.0.2 to my projects an tried to implement the `MapView` as provided in the samples.
Unfortunatly with no success. The namespace which is included in the sample `clr-namespace:Mapsui.UI.Maui;assembly=Mapsui.UI.Maui` isn't found at all.

So, are the samples wrong or has the implementation for .Net Maui been removed?

Thx

**Comment by Phil4121** [comment]
Found the solution, did not install Mapsui.Forms!!!!

**Comment by pauldendulk** [comment]
The samples apply to the code that is in the current master, so they may have to altered in order to work with v3.

**Comment by Phil4121** [comment]
Okay thanks for your answer! The problem is after adding Mapsui.Forms to my Maui Projekt I have to add a bunch of other package from Xamarin.AndroidX which causes lots of compliation errors.

**Comment by inforithmics** [comment]
When you use Maui you Should use mapsui.maui which isn't currently available in nugets.org. you have to Download it from the pull requests.

**Comment by inforithmics** [comment]
Herr you can download the ein package, which Container the maui.nupkg. But Maui port ist still in Development the maui Sample in Mapsui works for in winui and Android iOS has some skia sharp issues that Should resolved with maui Preview 13. Which comes out this Montag.

https://github.com/Mapsui/Mapsui/actions/runs/1736095563#artifacts

**Comment by pauldendulk** [comment]
I think the status is that at the moment is it not usable for v3. The coming weeks we hope to release a first beta of v4. That first version may not the maui control yet. So if you want to play with maui perhaps you should reference the code in your project.

**Comment by Phil4121** [comment]
Thanks to everybody who helped me! I'll try to pull the current Maui version!
