### ISSUE TITLE
Add NuGet for Avalonia

### ISSUE THREAD

**Issue by mattkanwisher** [Mapsui/Mapsui#1492]
It doesn't appear you generate packages for MapsUI.Avalonia, nor are there any nightly builds. Can you add it to nuget?

Thanks!

**Comment by pauldendulk** [comment]
We are currently changing a lot. There are nightly builds: https://mapsui.com/documentation/nuget-of-latest-build.html but Avalonia is not yet part of this. There will be a v4 beta in a few weeks (or less), but the first version will not have Avalonia yet.

**Comment by pauldendulk** [comment]
oh, cool, I thought wrong. So you could try the nightly @mattkanwisher.

**Comment by mattkanwisher** [comment]
This url is empty data? https://ci.appveyor.com/nuget/mapsui 

```xml
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app" xml:base="https://ci.appveyor.com/nuget/mapsui">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>
```

**Comment by pauldendulk** [comment]
@mattkanwisher It is the root of the nuget repository. Nuget itself know how to handle it. If you follow the instructions [here](https://mapsui.com/documentation/nuget-of-latest-build.html) you should be able to pull the nuget package from there.

**Comment by inforithmics** [comment]
You view the packages for example in Nuget Package Explorer

<img width="479" alt="image" src="https://user-images.githubusercontent.com/2290863/154563648-febe59c5-5826-44f2-be64-31804febefee.png">

**Comment by pauldendulk** [comment]
Avalonia was released as beta nuget a while ago.
