### ISSUE TITLE
Xiaomi MIUI Phones with Xamarin Forms

### ISSUE THREAD

**Issue by dinonovak** [Mapsui/Mapsui#1495]
HI,

I am having issues with Xamarin Forms app using mapsui on Xiaomi devices.
this is reflected that map track is not displayed, while in emulator and on Pixel amd Samsung phones works ok.

Anyone has similar experience?

Thanx,
D

**Comment by pauldendulk** [comment]
It is a static field on MapControl, so anywhere.

```Mapsui.UI.Forms.MapControl.UseGPU = false;```

**Comment by dinonovak** [comment]
this is same issue as #1514
track is not shown due to number format convesion
closing it
