### ISSUE TITLE
SingleCallout sample does not work

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1496]
Carry-over from https://github.com/Mapsui/Mapsui/issues/1143#issuecomment-1040187353 ...

The SingleCallout sample ("Info -> 1 Single Callout"  does not work for me. Tried with Mapsui.Samples.Forms.Mac and Mapsui.Samples.Forms.Android.

According to @pauldendulk, a callout should appear when clicking one of the points. It does not. Has this ever worked? If yes, when?

Note that the CustomCallout sample works perfectly. AFAICS the difference between both is primarily that the latter uses `CalloutType.Custom`, while the former uses the default `CalloutType.Single`.

**Comment by charlenni** [comment]
Yes, it has worked. I will look into this, but could take some time.

**Comment by pauldendulk** [comment]
The screenshot in that comment was made yesterday. I had a problem with the sample in Avalonia and there it turned out that the click event was called twice. So, the toggle logic in the sample turned it on and turned it off again and it was not visible in between. I fixed it there by fixing the click event. Perhaps this issue is similar.

**Comment by pauldendulk** [comment]
Investigating this was not possible with a breakpoint because it interfered with the click event. Some kind of logging is probably the best option.

**Comment by janusw** [comment]
> The screenshot in that comment was made yesterday. I had a problem with the sample in Avalonia and there it turned out that the click event was called twice. So, the toggle logic in the sample turned it on and turned it off again and it was not visible in between. I fixed it there by fixing the click event. Perhaps this issue is similar.

Yes, my problem indeed seems to be similar: There are two places which handle the click/info event!

The `SingleCalloutSample` itself handles it via the `MapOnInfo` method, and when run through the Forms samples, it is handled once more via the `MapView_Info` method in `MainPageLarge` or `MapPage`. Both invert the `Enabled` property of the CalloutStyle.

The problem is fixed when removing the `MapOnInfo` method in the `SingleCalloutSample` (analogous to the `CustomCalloutSample`, which doesn't have it either):

```diff
------ Samples/Mapsui.Samples.Common/Maps/Callouts/SingleCalloutSample.cs ------
index 3431f3be3..1dd860f48 100644
@@ -33,21 +33,10 @@ namespace Mapsui.Samples.Common.Maps.Callouts
             map.Layers.Add(OpenStreetMap.CreateTileLayer());
             map.Layers.Add(CreatePointLayer());
             map.Home = n => n.NavigateTo(map.Layers[1].Extent!.Centroid, map.Resolutions[5]);
-            map.Info += MapOnInfo;
 
             return map;
         }
 
-        private static void MapOnInfo(object sender, MapInfoEventArgs e)
-        {
-            var calloutStyle = e.MapInfo?.Feature?.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
-            if (calloutStyle != null)
-            {
-                calloutStyle.Enabled = !calloutStyle.Enabled;
-                e.MapInfo?.Layer?.DataHasChanged(); // To trigger a refresh of graphics.
-            }
-        }
-
         private static MemoryLayer CreatePointLayer()
         {
             return new MemoryLayer
```

However, this will probably break the sample when it is run through a non-Forms sample app, right? So probably one should rather remove the `MapOnInfo` treatment from Mapsui.Samples.Forms.Shared ...?

**Comment by janusw** [comment]
> However, this will probably break the sample when it is run through a non-Forms sample app, right?

I checked: It does break the SingleCallout in Mapsui.Samples.Droid, but since @pauldendulk wants to deprecate this one anyway, maybe we can live with this (and prioritize the Forms samples).

> So probably one should rather remove the `MapOnInfo` treatment from Mapsui.Samples.Forms.Shared ...?

Huh, looks like it's been in there for a while, and I'm not sure what else it's used for, so I'd rather keep it there, after all.

**Comment by pauldendulk** [comment]
I have not look into the code yet but I want to. I think it is important that this works. The MapInfo event is a simple solution that could be used in many scenarios. But somehow it conflicts with parts of the Mapview implementation.
