### ISSUE TITLE
Callout: anchor wrong when rotating with map (again!)

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1503]
This is sort of a reincarnation of #1151, with exactly the same phenomenology ...

When using a `Pin` with `Callout`, both of which have `RotateWithMap=true`, the callout anchor is placed incorrectly when the map is rotated off the default orientation, observable e.g. in the "Add Pin Sample" (PinSample.cs).

This has been working with 3.0.2 (was fixed in #1179), but seems to be broken again now in 4.0.0-beta.1.

**Comment by inforithmics** [comment]
Can you test my Pull Request. This seems to fix the Problem

**Comment by pauldendulk** [comment]
I do not see this problem in the Info | Custom Callout sample.

![image](https://user-images.githubusercontent.com/963462/154631730-27bb61a2-f1ce-48d9-9af0-0bb3819895b4.png)

How could I reproduce this?

**Comment by inforithmics** [comment]
You can reproduce this with add pin sample. Adding a pin an then rotating the map and deploying it to an Android Phone for example.

**Comment by pauldendulk** [comment]
So it seems to be more like a mono compiler bug. Perhaps it is solved with MAUI en .NET 6. Do you know if in .NET 6 mono is replaced with Microsofts own runtime?

**Comment by pauldendulk** [comment]
I was about to mention that we should have regression tests for this, but if this is only on Android it will not be easy to test that way. @janusw Do you also see the problem on Mac? If so, it would help to create regression tests.

**Comment by charlenni** [comment]
@pauldendulk You don‘t see it in your Test, because there the Offset is 0/0. You could only see the effect, if you set Offset to another value.

**Comment by janusw** [comment]
> @janusw Do you also see the problem on Mac? 

Yes, I also see it on Mac.

**Comment by pauldendulk** [comment]
> @pauldendulk You don‘t see it in your Test, because there the Offset is 0/0. You could only see the effect, if you set Offset to another value.

Ah!, so we should add that to our samples as well.

**Comment by pauldendulk** [comment]
> > @janusw Do you also see the problem on Mac?
> 
> Yes, I also see it on Mac.

With any of the existing samples or only in your app?

**Comment by janusw** [comment]
> > @pauldendulk You don‘t see it in your Test, because there the Offset is 0/0. You could only see the effect, if you set Offset to another value.
> 
> Ah!, so we should add that to our samples as well.

We have that already (in "Forms -> Add Pin Sample").

**Comment by janusw** [comment]
> > > @janusw Do you also see the problem on Mac?
> > 
> > 
> > Yes, I also see it on Mac.
> 
> With any of the existing samples or only in your app?

I only tried it with the sample for now, but I'm pretty sure the behavior will be the same in my app.

**Comment by pauldendulk** [comment]
> We have that already (in "Forms -> Add Pin Sample").

But I do not see it there, so there is different behavior between the platforms.

**Comment by janusw** [comment]
> > We have that already (in "Forms -> Add Pin Sample").
> 
> But I do not see it there, so there is different behavior between the platforms.

Interesting. On which platform are you testing it?
