### ISSUE TITLE
Add regresssion tests for all our samples

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1506]
### Mapsui samples
Mapsui has a setup for samples where all samples implement the ISample interface, through reflection all samples are loaded and are added to the samples apps on all platforms. This is low maintenance and works well.

### Mapsui is showing the regression tests as samples
We also have a set of regression tests. They are similar in setup in the sense that a Map object is created. The Map is used to generate a bitmap which is compared to a stored reference bitmap (using NUnit and some of our utilities). At some point in the past I thought it would be a good idea to show those tests as samples, so I implemented the ISample interface for all the tests, and now they are visible in all platform samples.

### Mapsui could use all samples in our regression tests
A logical next step is to go the other way around. Use the samples in our regression tests. For showing samples we use reflection. For running the regression tests we do not, but perhaps we could. There would be just one [Test] method that would fetch all ISample implementations and would run them. Naming of the reference bitmap should be based on the name of the ISample implementation (this can be done with reflection). Doing this will be a huge improvement of our coverage, and would detect many regressions that slip through right now. The regression tests frequently help me to avoid introducing a bug.

### The problem
There is however a problem. Most samples work asynchronous. So, initially the Map will be empty. Somehow you would have to wait for the data to be loaded. Currently there is a Busy boolean which might be used, but such a solution is still hacked. We use something like that in the FetchWorker tests but it is ugly. To make this work properly we may need to change the architecture. Perhaps async/await may be a solution, but I doubt it is, because for most scenarios we do not want to wait on the data fetcher at all. Perhaps we could use async/await and simply not await is in the IProvider.GetFeatures method. There maybe many other option. The purpose of this post right now is just to start thinking about a good solution.

Another problem is that many samples use external data. We could still have tests for those. They will be some kind of api tests. But we should treat them differently. They should be in another category and perhaps implement a different interface.

**Comment by charlenni** [comment]
Good idea, but I think, it would lead to trouble, because nearly all samples use a map in the background (mostly OpenStreetMap), which change from time to time, so that the generated images change.

The next is, that many of this samples need interaction, e.g. by clicking on a feature to show a callout.

**Comment by inforithmics** [comment]
I think this could be achieved without to many changes in the samples. So the changes I have in mind are.

1. The online Source Stay as they are, but the results are returned by a IPersistCache (for example the sqlite IPersistCache i implemented in the V3 of  the Tiling Layer.
2.  The I Sample interface is extended With a Test or Action Method. In which the User Interaction is done in code deterministic to have testability. I think with this two changes Every Sample can be automatically tested.

1. Get All Samples
2. Create Map
3. Call Test Method
4. Create Image and compare with stored Image.

I'm thinking about making a pull request to concretisize this. But I cannot promise anything yet.

**Comment by pauldendulk** [comment]
This has been done quite a while ago.
