### ISSUE TITLE
Map track not shown on Android devices - depends on device language selected

### ISSUE THREAD

**Issue by dinonovak** [Mapsui/Mapsui#1514]
I am having a strange issue that I am unable to troubleshoot.

Xamarin Forms app (forms 5.0.0.2337) with mapsui 3.0.2
On iOS and most android devices map is drawn without any problems (option Mapsui.UI.Forms.MapControl.UseGPU = false;  resolved most of the issues) and map, track and pins are shown without any problems

But on Samsung Galaxy s8 (Android 9, OneUI 1.0) track is simply not shown.

I have a log from when page is opened attached but no errors that can indicate any issues.
Is there any additional troubleshooting that I can apply to see. what could be the issue in this case.
I somehow suspect that could be problem related to skia.

[s8log.txt](https://github.com/Mapsui/Mapsui/files/8102695/s8log.txt)

**Comment by charlenni** [comment]
Did you installed the Logger to look, if there are any exceptions while drawing?

**Comment by dinonovak** [comment]
I am ttracking potential issues with, there are just few lines in the attached log but nothing indicative

Mapsui.Logging.Logger.LogDelegate += (level, message, ex) => {
                Console.WriteLine("MAPSUI Error: " + message + " - " + ex);

**Comment by dinonovak** [comment]
Here is new confirmartion. If I switch languange no Croatian (HR) for device, track disappears.
if I leave it on English track is shown ?!

**Comment by inforithmics** [comment]
Number Format USA
Double:
1.3 (Point decimal seperator)

Number Format Germany, Crotia:
Double:
1,3 (Comma decimal seperator)

version that does not work:
segmentPoints.Add(SphericalMercator.FromLonLat(Convert.ToDouble(xelement.GetAttribute("lon")), Convert.ToDouble(xelement.GetAttribute("lat"))));

You need to specify CultureInfo.InvariantCulture or else it reads with the number settings of the language settings.

works:
segmentPoints.Add(SphericalMercator.FromLonLat(Convert.ToDouble(xelement.GetAttribute("lon"), CultureInfo.InvariantCulture), Convert.ToDouble(xelement.GetAttribute("lat"), CultureInfo.InvariantCulture)));
