### ISSUE TITLE
v4.0 migration - LinesString - how to add track to map ?

### ISSUE THREAD

**Issue by dinonovak** [Mapsui/Mapsui#1515]
HI,

looking if v4.0 may solve issue with track I am trying to migrate my code to it. But I am having issue how to do it with line string.
currently I am creating line string this way:

```csharp
List<MPoint> segmentPoints = new List<MPoint>();
foreach (XmlElement xelement in xmlPoints) //fetching points from XML file
{
   segmentPoints.Add(SphericalMercator.FromLonLat(Convert.ToDouble(xelement.GetAttribute("lon")), Convert.ToDouble(xelement.GetAttribute("lat"))).ToMPoint());
 }

var feature = new GeometryFeature() // creating feature layer
{
  Geometry = new LineString(segmentPoints.ToArray())  // this is where I need help, how do I construct linestring from MPoints list ?
};
```

**Comment by dinonovak** [comment]
tried following but track is not showing, I am not sure what format lat/lon needs to be in

List<Coordinate> segmentCoords = new List<Coordinate>();
foreach (XmlElement xelement in xmlPoints)
{
        segmentCoords.Add(new Coordinate(Convert.ToDouble(xelement.GetAttribute("lon")), Convert.ToDouble(xelement.GetAttribute("lat"))));
}
//add layer
var feature = new GeometryFeature()
{
        Geometry = new LineString(segmentCoords.ToArray())
};

**Comment by dinonovak** [comment]
I also tried adding route as points using

List<MPoint> segmentPointsX = new List<MPoint>(); 
foreach (XmlElement xelement in xmlPoints)
                {
                    MPoint xPoint = SphericalMercator.FromLonLat(Convert.ToDouble(xelement.GetAttribute("lon")), Convert.ToDouble(xelement.GetAttribute("lat"))).ToMPoint();
                    segmentPointsX.Add(xPoint);
                    segmentCoords.Add(new Coordinate(xPoint.X, xPoint.Y));
                }

private static ILayer CreateLayerPoints()
        {

            return new Layer("TrackAsPoints")
            {
                DataSource = new MemoryProvider<PointFeature>(segmentPointsX.Select(p => new PointFeature(p)).ToList())
               
            };
        }

Again this layer is not shown.
Also tried adding polygon based on polygon sample
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Geometries/PolygonSample.cs

Again on Samsung s8 this layer is not shown.
Attaching s9 vs s8 images for same build.

Any ideas?

![s8image](https://user-images.githubusercontent.com/18152490/154841937-edd45291-59cf-4ba1-a291-9bdc6ebb5d6a.jpeg)
![s9image](https://user-images.githubusercontent.com/18152490/154841940-0099fef3-c534-4e31-870d-bb526c63f906.jpeg)

**Comment by inforithmics** [comment]
Have you tried upgrading upgrading the project to SkiaSharp 2.88.0-preview.209 (Because the Rendering is done with SkiaSharp there could be an issue that might be resolved by a later version)

**Comment by dinonovak** [comment]
I am not adding skiasharp manually.
How can i manually update skiasharp (just add it as nuget package skiasharp & skiasharp.views.forms) ?

what I can see that mapsui is resolving skiasharp to, and automatically downloading it.
      "Mapsui/4.0.0-build.2929": {
        "type": "package",
        "dependencies": {
          "BruTile": "[4.0.0, 5.0.0)",
          "NetTopologySuite": "[2.4.0, 3.0.0)",
          "SkiaSharp": "[2.80.3, 3.0.0)",
          "Svg.Skia": "[0.5.7.1, 0.6.0)",
          "Topten.RichTextKit": "[0.4.145, 0.5.0)"
        },
        "compile": {
          "lib/netstandard2.0/Mapsui.Nts.dll": {},
          "lib/netstandard2.0/Mapsui.Rendering.Skia.dll": {},
          "lib/netstandard2.0/Mapsui.Tiling.dll": {},
          "lib/netstandard2.0/Mapsui.dll": {}
        },
        "runtime": {
          "lib/netstandard2.0/Mapsui.Nts.dll": {},
          "lib/netstandard2.0/Mapsui.Rendering.Skia.dll": {},
          "lib/netstandard2.0/Mapsui.Tiling.dll": {},
          "lib/netstandard2.0/Mapsui.dll": {}
        }
      },
      "Mapsui.Forms/4.0.0-build.2929": {
        "type": "package",
        "dependencies": {
          "Mapsui": "4.0.0-build.2929",
          "SkiaSharp.Views.Forms": "[2.80.3, 3.0.0)",
          "Xamarin.Essentials": "[1.7.0, 2.0.0)",
          "Xamarin.Forms": "[5.0.0.2083, 6.0.0)"
        },
        "compile": {
          "lib/xamarinios1.0/Mapsui.UI.Forms.dll": {}
        },
        "runtime": {
          "lib/xamarinios1.0/Mapsui.UI.Forms.dll": {}
        },
        "build": {
          "build/xamarinios1.0/Mapsui.Forms.targets": {}
        }
      },

**Comment by inforithmics** [comment]
Yes, that would upgrade skia sharp. Somtimes the Graphic Driver had Problems than a Setting MapControl.UseGpu= false could help. Or embedding the Layer that does not work into an RasterizingLayer. See samples for that.

**Comment by dinonovak** [comment]
I am already using MapControl.UseGPU = false; and that fixed some artifacts on Android devices.
but stragely looks like if I am trying to add any additional layer (besides adding pins to existing pin layer) it is not drawn on the control.

**Comment by dinonovak** [comment]
Can someone check if adding LineSegment is working for them on iOS 15.2 simulator?

**Comment by inforithmics** [comment]
If you make a reproduction sample I can have a look at it in the ios 15.2 simulator. I guess you are using Visual studio 2022 17.1
Or are you using Visual Studio for Mac.

**Comment by dinonovak** [comment]
HI,
this is created in Visual Studio for Mac Version 8.10.19 (build 2) it has been updated to latest stable release
using mapsui 3.0.2 (latest stable)

Here is full sample that is loading garmin gpx track
https://gitlab.com/dnovak/mapsuitrack

Simulator iOS 15.0 - track is shown
Simulaor iOS 15.2 - track is not shown 

I suspect it is SkiaSharp issue but I am unable to troubleshoot why layers are not showing.

**Comment by dinonovak** [comment]
@inforithmics here is result of my debugging so far - this is tested on few android devices (Android 9 & 10 & 11). 

Looks like device language is the reason for track disappearing.
If device is with English (US) language as default, all works OK, if I add secondary language (in my case Croatian) and set is as default track disappears. Switching back to English (uS) track is shown.

Could it really be the case that there is some language dependancy ?!

**Comment by pauldendulk** [comment]
> Can someone check if adding LineSegment is working for them on iOS 15.2 simulator?

What do you mean with this? Just adding a line? Perhaps you should clone the Mapsui repository and run the samples, and look at the sample code.

**Comment by dinonovak** [comment]
This issue is caused by same error as #1514 (number format conversion from non US to US)
You can close this

**Comment by pauldendulk** [comment]
One more thing. MPoint is part of Mapsui itself (along with MRect and MQuad), while LineString is part of NTS. If you work with NTS it makes more sense to work with NTSs Point or Coordinate. There are extension methods for converting between them.

And I see we even have an MPoint ToCoordinate extension method. Perhaps we should also add an ToCoordinates that takes an ```IEnumerable<MPoint>```
