### ISSUE TITLE
caching OSM Layer in Xamarin Forms

### ISSUE THREAD

**Issue by marcellangmaier** [Mapsui/Mapsui#1544]
Does anyone has an example of caching an OSM layer in a xamarin forms app?
I want to intercept the tile loading and want to use a cached tile (if available in the cache and if not expired) or else I want to download the tile from OSM and save it into my cache.
Or can anyone guide me into the right direction howto do this?

**Comment by pauldendulk** [comment]
There has been a recent PR that uses caching of the tile layers. The purpose of this MR has been for testing but it can probably help you as well. https://github.com/Mapsui/Mapsui/pull/1530. These changes are in master and you probably work with 3.x so it will not work one on one.

**Comment by janusw** [comment]
You could do something like this:

```
BruTile.Cache.FileCache fc = new FileCache(...);
BruTile.Predefined.KnownTileSources.Create(KnownTileSource.OpenStreetMap, persistentCache: fc);
```
