### ISSUE TITLE
How to add Marker (Point) to MapControl in WPF

### ISSUE THREAD

**Issue by CMD6789** [Mapsui/Mapsui#1570]
Hi everybody,

can someone tell me how can i add markers (points) to MapControl in WPF?

Thanks in advance.

**Comment by pauldendulk** [comment]
There are many samples that use a marker. I just updated the documentation page about samples:

https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/samples.md

**Comment by DerRofocale** [comment]
No one example from samples working. I broke my head already. Doing same like in sample but half of code not working

**Comment by DerRofocale** [comment]
Code from sample. i wanna mark some my points by lnt&log
