### ISSUE TITLE
Move more functionality from MapControl to platform independent parts of Mapsui

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1580]
**Is your feature request related to a problem? Please describe.**
The MapControl.Map object is independent of the UI platform. Therefore it is easy to handle in platform independent parts of the app. For various other cases the MapControl is needed. To use it in platform independent code the IMapControl interface can be injected, but this is not as easy as having it all in a platform independent component. Also the MapControl needs to be created before it can be initialized.

**Options**
- Add a new field to the MapControl which will have the Map field and other functionality that is now on the MapControl, such as the Viewport, Navigator, Refresh methods.
- Like the above but rename the existing Map (to 'Data'?) and name the new field Map.
- Move parts that are now on MapControl to Map, and keep the rest identical. Disadvantage, the Map will have too much responsibility.

**Comment by charlenni** [comment]
For me, it isn't clear, which parts of MapControl you talk about. Could you give an example, which part of MapControl should go to a platform independent part?

**Comment by pauldendulk** [comment]
In v4 we choose the 3rth option. The Map should be the main thing that users need to deal with, not the MapControl. There may still be cases where the users needs the MapControl but should not, we should create new issues for those cases when we run into them.
