### ISSUE TITLE
How to stop current view refresh?

### ISSUE THREAD

**Issue by daxiangxi** [Mapsui/Mapsui#1589]
hello, i used WritableLayer to show my own data, when the data is large, the refresh process may take a long time and user can feel the pause,  I consider when user move the mapview Continuously, if mapsui can stop current refresh process and repsone the next move action, then the user experience will be better, Can we do this?

**Comment by pauldendulk** [comment]
I don't know why it is slow. Is see two reasons

1. It takes time for the data to load. In this case do not use a WriteableLayer but a Provider to load the data and assign that to the Layer.DataSource.
2. It takes time to render the data (there is actually a lot of data or large polygons). In this case you could nest the layer in a RasterizingLayer. Never tested how this works in combination with a WriteableLayer though. If you are using the latest beta you could also use the RasterizingTileLayer.

Here some info on how to work with the samples:
https://mapsui.com/documentation/samples.html

**Comment by daxiangxi** [comment]
ok, thank you pauldendulk, I'll try your suggestion.
