### ISSUE TITLE
MAUI Map Control: slow map update on pan map

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#1623]
Hi, I'm trying the MAUI sample described at https://mapsui.com/documentation/getting-started-maui.html with Mapsui.Maui 4.0.0-beta.4

It works, but on Windows I notice slow map update on panning the map:
![maui1](https://user-images.githubusercontent.com/538812/171052774-b20653dc-02da-4125-973e-cdb76b7997a0.gif)

When moving the mouse out of the map control, the map is updated.

**Comment by pauldendulk** [comment]
Slow or no update?
And how is it for zooming.

**Comment by pauldendulk** [comment]
The PR has been merged this will be fixed in 4.0.0-beta.5.
