### ISSUE TITLE
The encoding of ShapeFile field and content reading is the same

### ISSUE THREAD

**Issue by wxdlt** [Mapsui/Mapsui#1631]
The field name is of string type. At present, utf-7 reading is used. The reading code of string type in the field value is user-defined. I wonder whether this can be unified

in DbaseReader：
（123ow）
```csharp
   _dbaseColumns[i] = new DbaseField
                {
                    ColumnName = Encoding.UTF7.GetString((_br.ReadBytes(11))).Replace("\0", "").Trim()
                    //proposal: ColumnName = _fileEncoding.GetString((_br.ReadBytes(11))).Replace("\0", "").Trim()
                };
```
At present, this will cause me to read the field garbled，Do you want to unify the coding！

**Comment by wxdlt** [comment]
Yes, this line of code can solve my problem. The code I use here is UTF-8. I have tested it in the unit test. Modifying this line of code can solve such problems

**Comment by pauldendulk** [comment]
Yes, I understand that it solves your problem but I was trying to go a bit further than that and get some better understanding of the problem, and test some other cases. But never mind, the new code still works for the existing test cases so I will just push the change. 

Thanks for reporting the problem!

**Comment by inforithmics** [comment]
I read a bit about it and found out that the encoding is saved in the optional .cpg File.  So utf-8 is certainly a good default.
When a cpg File is there the encoding should be read from there. 

https://gis.stackexchange.com/questions/246535/how-do-i-create-find-cpg-files-after-creating-a-shapefile-in-qgis

**Comment by pauldendulk** [comment]
I am closing this one. Reading the encoding from the .cpg is a possible enhancement. But if we ever do that it could be a new issue.
