### ISSUE TITLE
Missing nuget package for WinUI

### ISSUE THREAD

**Issue by hoffe86** [Mapsui/Mapsui#1634]
Hey
Is it possible that there is no nuget package available for WinUI?
There is one mentioned in the [WinUI example](https://mapsui.com/documentation/getting-started-winui.html), but I can not found anything on nuget.org.

Thanks
Christoph

**Comment by pauldendulk** [comment]
It is not released yet. It will be in one of the upcoming betas. At some point we did have package of the build but that was broken at some point since we are moving from appveyor to github actions. We also need to release Mapsui.Uno package coming weeks.

**Comment by inforithmics** [comment]
Is released.
https://www.nuget.org/packages/Mapsui.WinUI/4.0.0-beta.5
