### ISSUE TITLE
method Intersects of Class  MRect  storage problem

### ISSUE THREAD

**Issue by wxdlt** [Mapsui/Mapsui#1643]
public bool Intersects(MRect? rect)
    {
        if (rect is null) return false;

        if (rect.Max.X < Min.X) return false;
        if (rect.Max.Y < Min.Y) return false;
        if (rect.Min.X > Max.X) return false;
        if (rect.Min.Y > Max.Y) return false;

        return true;
    }

It is not an intersecting relationship judgment.
I hope my findings can help improve

**Comment by wxdlt** [comment]
This is my intersection implementation   
public bool Intersects(MRect? rect)
    {
        if (rect is null) return false;

        return (rect.Contains(TopLeft) || rect.Contains(TopRight) || rect.Contains(BottomLeft) || rect.Contains(BottomRight));
    }

**Comment by pauldendulk** [comment]
Are you saying the method is not correct? Do you have an example of a flawed calculation?
