### ISSUE TITLE
Add ISample.CreateMapAsync for better support of MVVM

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1650]
**The problem**
For Maui I would like to use MVVM in the samples (because it seems that is what everybody is using in Maui). One thing I would like to change is to make the Map property a BindableProperty and make it an observable property in the ViewModel, but that is another issue. The next step would be to assign the various Maps of the samples to that property. However, the current samples work with an IMapControl, which does not fit into that pattern.

**Proposed solution**
Distinguish between two kinds of samples, the ISample in which only a Map is created and the IMapControlSample, in which a MapControl is configured. The selection between those two can done in the SampleExtensions which is currently already selecting between the ISample and IAsyncSample (btw, those can be merged, both can be Async).

**Alternative solutions**
- Use ISample and think of an entirely different mechanism (different page in the sample app) for IMapControlSample. This would require extra work in all the sample apps.
- Move everything in the MapControl that is needed in the IMapControlSample to the Map so that only a Map is needed. This is too much. What is needed for some samples:
  - The Navigator (could be moved)
  - Several properties related to interaction (like double click). They belong on the MapControl.
  - The Performance field of the MapControl. Seems to belong to MapControl
  - The renderer (for the custom renderer and symbol animation). The Renderer should stay in the MapControl.
- Preconfigure what is needed for those samples in another way in the application. Looks like this will be extra work.
- Use one ISample interface but have two methods on it. One to create the Map and one to configure the IMapControl.

**Comment by inforithmics** [comment]
Proposed solution sounds good. 
For MVVM Mapsui nuget needs to be split up. Every dll should get it's own nuget package. The Main reason is that Mapsui Rendering has SkiaSharp dependencies and in MVVM the ViewModels shouldn't have dependencies on the UI (SkiaSharp). So ViewModels should only reference Mapsui and the rendering should only be referenced by the Mapsui.UI. nuget packages.

**Comment by pauldendulk** [comment]
@inforithmics Good point! I had not thought about that. 

The smallest change would be to more Mapsui.Rendering.Skia to its own package. I think we need to do that before the release of 4.0. It also makes you think about putting every dll in its own package.

**Comment by pauldendulk** [comment]
Here is the related PR https://github.com/Mapsui/Mapsui/pull/1651

**Comment by inforithmics** [comment]
Mapsui.Tiling (Brutile Dependency)
Mapsui.Nts (NetTopology Dependency)
Mapsui.Rendering.Skia (Skia.Sharp Dependency)
Mapsui.ArcGis (Brutile Dependency)
Maybe Mapsui could become Mapsui.Core or something simular
and Mapsui nuget package references Mapsui.Tiling nts rendering. arcgis ... So that the User of the Mapsui nuget sees no change.

But this is only an idea I didn't fully analyse it.

**Comment by pauldendulk** [comment]
This was implemented a while ago.

This remark is still relevant. This may be needed for MVVM support.

> - Move everything in the MapControl that is needed in the IMapControlSample to the Map so that only a Map is needed. This is too much. What is needed for some samples:
>   - The Navigator (could be moved)
>   - Several properties related to interaction (like double click). They belong on the MapControl.
>   - The Performance field of the MapControl. Seems to belong to MapControl
>   - The renderer (for the custom renderer and symbol animation). The Renderer should stay in the MapControl.

**Comment by charlenni** [comment]
@pauldendulk As I said before: it would be helpful to define, what Map should contain. I suggested, that Map only contains things, that belong to the pure map data like layers. Nothing else.
