### ISSUE TITLE
Mapsui.Avalonia : Tile map layer opacity is applied to some tiles

### ISSUE THREAD

**Issue by mirtaqi** [Mapsui/Mapsui#1658]
I have an application that using the avalonia as ui and Mapsui for display map
My map format is mbtiles
I am using this mbtiles map as background and user can change the opacity of base map.
when the map's opacity is set to less than 1  and user zoom the map the opacity applied to the some tiles and other tiles rendered with opacity=1

Mapsui 4.0.0-beta.5
Mapsui.Avalonia 4.0.0-beta.5
Avalonia 0.10.15
Windows 10 / Ubuntu

![screenflicker2](https://user-images.githubusercontent.com/48408847/177544945-700330b2-3bf6-49bd-a704-7326052ba630.gif)

**Comment by mirtaqi** [comment]
If I stop zooming everything is fine as expected and the area of the map that is in the viewport is displayed correctly.
This happens only when zooming in and zooming out for the first time, and it does not happen after all tiles are cached once.
For testing, I developed a separate application that only contains a form and displays the map, and the issue still exists.

**Comment by pauldendulk** [comment]
So, I think this is indeed the problem I described above. 

Workarounds with the current implementation
- Don't use transparency
- In the constructor of the TileLayer there is a IRenderFetchStrategy Parameter. It determines which tiles are fetched for rendering. You can use the MinimalRenderFetchStrategy as a parameter.  It does not try to be smart by fetching a higher level tile if the current level tile is not there yet. So there will be no semi-transparant tiles drawn over each other. There will be a moment when only the background is visible. Still not very nice, but perhaps better than the current solution.

Possible future improvements (which will not have high priority).
- When drawing the higher level tile the renderer should clip it to the extent of the current level tile.
- Make it possible to draw a semi-transparent surface over the tile layer. This will be useful for what I see in your animation, but it won't help if you actually want to see what is underneath.

**Comment by pauldendulk** [comment]
I see this as a known limitation. Not a bug. A possible future improvement should be discussed in a new issue.
