### ISSUE TITLE
I haven't got a clue how to progress beyond the world example!!! :(

### ISSUE THREAD

**Issue by gfmoore** [Mapsui/Mapsui#1661]
I've got the basic world map appearing in my .net Maui app.

You say:
The best way to get started with mapsui is to download the source and run a samples app. 

Not for me it isn't!.

I'd like to try and understand what is going on and rather than spend my life decoding someone else's code (and I've tried) I'd just like some simple examples on how to do the basics (in writing, or a video).

So for example, I have my location, how do I programmatically set the location for the map and then programmatically fix a scale? (I don't even know the correct terms.)

Then I'd like to pin some locations on the map.

That would be a really good start. 

Ta
G.

**Comment by pauldendulk** [comment]
@gfmoore Mapsui is an open source project with limited resources and at the moment it is simply not possible provide extensive documentation or videos. More and better documentation is one of our goals but at the moment getting a stable v4 released has a higher priority.

Perhaps the setup of the samples (the way they are loaded and activated) is complicated but that is not something you need to understand. The sample files themselves (those derived from ISample) are often fairly simple. For instance look at the [Zoom Lock sample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Navigation/ZoomLockSample.cs) to fix the scale or the [Write To Layer sample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Special/WriteToLayerSample.cs) to add a pin.

**Comment by gfmoore** [comment]
Uhmmm, well okay I've managed to get my map to scale by hacking away and looking all over to get some code that works: (and for the benefit of others using .net Maui - and I bet you wish you weren't!!)

```
      //you'll need to get a location using IGeolocation - let me know if you need some code
      location = await geolocation.GetLocationAsync(new GeolocationRequest
      {
        DesiredAccuracy = GeolocationAccuracy.Best,
        Timeout = TimeSpan.FromSeconds(30)
      });

      var smc = SphericalMercator.FromLonLat(location.Longitude, location.Latitude);
      
      var mapControl = new Mapsui.UI.Maui.MapControl();
      var map = mapControl.Map;
      //map.BackColor = Mapsui.Styles.Color.FromString("#000000");
      map.BackColor = Mapsui.Styles.Color.Black;

      map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
      
      map.Widgets.Add(new ScaleBarWidget(map));
      map.Widgets.Add(new ZoomInOutWidget { MarginX = 10, MarginY = 20 });  //adds the +/- zoom widget

      map.Home = n => n.NavigateTo(new MPoint(smc.x, smc.y), map.Resolutions[16]);  //0 zoomed out-19 zoomed in
      IsBusy = false;

      //add to my xaml (I have a grid which contains a <ContentView x:Name="MapDisplay"></ContentView>
      MapDisplay.Content = mapControl;

```
Oh and you'll need to import a load of stuff Mapsui.xxxx etc

So my problem is adding a pin to my location. Following the example doesn't work.

```
 //add a pin
      var layer = new GenericCollectionLayer<List<IFeature>>
      {
        Style = SymbolStyles.CreatePinStyle()
      };
      map.Layers.Add(layer);

      layer?.Features.Add(new GeometryFeature
      {
          Geometry = new Point(smc.x, smc.y)
      });

      layer?.DataHasChanged();
```

There seems to be a mismatch between Point - the type is Microsoft.Graphics.Maui.Point to NetTopologySuite.Geometries.Geometry

I tried putting

Mapsui. xxx.xxx.Geometery = new Mapsui.MPoint to get types aligned.

I could not find a reference for Geometry in the api (Not using filter anyway)

I'm assuming!!! that what this code does is create a layer over the map that will display pins and that any point you add to it's internal list will render as a pin, but I'm simply guessing!!!


And though I take your point that you are working hard on v4 what is it all worth if peeps don't know how to use it!!!

I mean, please spend a day on just writing some simple explanations of the concepts and how to get this basic stuff working. I've spent yet another 3 hours this morning getting nowhere. It's all very well saying look at the samples, but a) the sln won't build and b) even then I don't know where to look. It's simply gobbledegook to me. c) Your coding approach looks very clever, but is way beyond my understanding at this time.

In terms of my problem I was hoping to do something like

layer.Features.Add(new Pin.Point(x, y));

Thanks for any help.

**Comment by charlenni** [comment]
Hi,

I saw many comment on the need of a better documentation, but I don't see a description of what is the problem. Do you see anything on the screen? Do you get an error?

The object Point could be found in each of the libraries that are out. Because there isn't one in the native .Net, all the libraries have to make their own. GeometryFeature could be found very fast, if you search "GeometryFeature.cs". Mapsui should use an own file for each object type. In this case, you use GeometryFeature from the package Mapsui.NTS, which then uses a Point for Geometry from the NetTopologySuite.Geometries (see [NetTopologySuite.Geometries.Point](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/src/NetTopologySuite/Geometries/Point.cs)) package. I assume, you use the wrong type for Point, but I could only assume, because you don't tell us anything about what happens.

Loading some more dependencies should be the normal case, because no one will invent the wheel again. And not all users of Mapsui need all parts of it.

I would say, it isn't trivial to write a documentation for each user, regardless of his level of knowledge, and for all the platforms Mapsui supports. Perhaps it is better to choose one of the commercial platforms, which are certainly far better documented than Mapsui.

**Comment by gfmoore** [comment]
It's very simple mate, show me how to put a pin on my map! Using the getting started example for Maui. How hard is it to do that. Your response I found to be shall we say, unhelpful.

And the documentation IS poor. So much for asking users to get involved. And I'm not a commercial programmer, just trying to write an app for my own purposes.

I have high hopes for this package.

**Comment by charlenni** [comment]
Again, you deliver nothing than criticism. You answered none of my questions. You don‘t provide your demo project. You don‘t provide any information about what you see and what you don‘t see.

I never worked with Maui before. So do you expect, that I should learn it to provide you with help for your project with Mapsui?

**Comment by gfmoore** [comment]
If you've not worked with Maui before, then why are you here!!!

Criticism is valid if it is correct and I think my criticism that there is no proper documentation is valid and now there is work on V4. BUT there is no documentation for v1, 2 and 3. I don't think documentation is any objective at all.

I put the code I tried. i put down that there is a type mismatch, I put down that I searched the api but couldn't find "geometry". I've looked through the source code, of which there is so much and much of it is also undocumented and I've no idea what it is trying to accomplish. 

All I want to do mate is add a pin to my current location and I don't know how to do it.

If you want to help then please can you explain the concept and what I need to do and if you please a code fragment that will work with .Net Maui.

Otherwise, please, and as kindly as I can say it, butt out and go and flame someone else.

I'm now sure I won't get any help from this repo, but there it is. Sad.

**Comment by gfmoore** [comment]
Oh I've noticed this by the way: http://mapsui.com/documentation/documentation.html 

We should iteratively improve the documentation. If questions are asked in the issues we should search for the answer in the documentation. Update the documentation when it is missing and answer the issue with a url to the documentation.
Writing documentation is not only useful to inform the user but also as a sanity check for the developer. If what you have to tell becomes complicated and hard to grasp this could mean the software is not well designed. Writing documentation early should be used as a part of the software development process.

And also this:
http://mapsui.com/documentation/v4.0-upgrade-guide.html

Mapsui.Geometries Removed!!!!

**Comment by inforithmics** [comment]
@gfmoore If you like to improve the documentation of mapsui, you can make a pull request to improve the documentation. 
The documentation lives here in mapsui https://github.com/Mapsui/Mapsui/tree/master/docfx/documentation and is from there generated for the website.

**Comment by gfmoore** [comment]
For anyone else, I finally figured out one way at least of adding a pin
```
   ...

     var smc = SphericalMercator.FromLonLat(location.Longitude, location.Latitude);
      
      var mapControl = new Mapsui.UI.Maui.MapControl();
      var map = mapControl.Map;
      var viewPort = mapControl.Viewport;
      //map.BackColor = Mapsui.Styles.Color.Black;

      map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
      
      map.Widgets.Add(new ScaleBarWidget(map));
      map.Widgets.Add(new ZoomInOutWidget { MarginX = 10, MarginY = 20 });  //adds the +/- zoom widget

      map.Home = n => n.NavigateTo(new MPoint(smc.x, smc.y), map.Resolutions[16]);  //0 zoomed out-19 zoomed in

      IsBusy = false;

      //add a pin
      var myPin = new Pin(mapView)
      {
        Position = new Position(location.Latitude, location.Longitude),
        Type = PinType.Pin,
        Label = "Zero point",
        Address = "Zero point",
        Scale = 0.7F,
        Color = Colors.Blue,
      };
      mapView.Pins.Add(myPin);

      mapView.Map = map;

'''
```

re contributing to documentation. If I even understood any of it I would! :)

**Comment by hellcoderGIT** [comment]
I just started to look into this lib yesterday and the difference between MapView and MapControl is not really clear to me but here is a way to do it with MapControl:

```

    public Map CreateMap()
    {
        var map = new Map();
        map.Layers.Add(OpenStreetMap.CreateTileLayer());    
        map.Layers.Add( CreatePointLayer());
        map.Home = n => n.NavigateTo(map.Layers[1].Extent!.Centroid, map.Resolutions[5]);
        return map;
    }

    protected override  void OnAppearing()
    {
        base.OnAppearing();
        mapControl.Map = CreateMap();
        mapControl.Info += MapControl_Info;

    }

    private void MapControl_Info(object sender, Mapsui.UI.MapInfoEventArgs e)
    {
        var mapInfo = e.MapInfo; //called on map click allowing access to features
    }
    private MemoryLayer CreatePointLayer()
    {
        return new MemoryLayer
        {
            Name = "Points",
            IsMapInfoLayer = true,
            Features = GetPointFeatures(),
            Style = CreateBitmapStyle()
        };
    }

    private static IEnumerable<IFeature> GetPointFeatures()
    {    
        List<IFeature> features = new List<IFeature>();
        var home = new PointFeature(SphericalMercator.FromLonLat(100.564660, 13.691786).ToMPoint());
        home["name"] = "Home";        
        features.Add(home);

        return features;
    }

   
    private SymbolStyle CreateBitmapStyle()
    {       
        var bitmapId = typeof(a.class.of.the.assembly).LoadBitmapId(@"Resources.Images.home.png"); //this resource cannot be a MauiImage, it needs to be an embeddedResource
        var bitmapHeight = 176; // To set the offset correct we need to know the bitmap height
        return new SymbolStyle { BitmapId = bitmapId, SymbolScale = 0.20, SymbolOffset = new Offset(0, bitmapHeight * 0.5) };
    }

```

Another thing I came across is that the current Maui Alpha does not seem to support the OpenStreetMap layer on Android, had to use another base layer (bing) to get it working.

**Comment by charlenni** [comment]
@hellcoderGIT MapControl for Forms or Maui has the same behavior than the MapControl for all other platforms Mapsui support. MapView is a convenience Layer around MapControl. It tries to mimic the behavior of the official MapView from Forms. It uses WGS84 for coordinates and provide a special layer for Pins or Drawables. It has a layer for your own position to show, where you are and follow you.

So for small projects MapView would be the easier entrance to maps. If you understand a little bit better what you are doing, MapControl would be the better.

**Comment by hellcoderGIT** [comment]
@charlenni thanks for clarifying this.

**Comment by gfmoore** [comment]
Sorry, my bad. The mapView.Map = map; in my code is a link to the xaml view, in this case
```
<mapsui:MapView x:Name="mapView" />
```

I should have chosen a better name.

Thanks for your code, which is very helpful and shows me how I should better structure my code. :)

G.

**Comment by gfmoore** [comment]
Hi, I decided, belatedly, to create a test app. I can confirm that that using the basic Quickstart Maui that the open street map does display on the pixel 5 emulator.

My repo is at https://github.com/gfmoore/MapsuiTest.App

**Comment by kablammyman** [comment]
> Hi, I decided, belatedly, to create a test app. I can confirm that using the basic Quickstart Maui that the open street map does display on the pixel 5 emulator.
> 
> My repo is at https://github.com/gfmoore/MapsuiTest.App
> 
> EDIT: I'm sure you haven't but just in case for anyone else, don't forget to add the permissions if you are getting your location from IGeolocation. For android you need: Android.Manifest.xml
> 
> ```
>   <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
>   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
>   <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
>   <uses-feature android:name="android.hardware.location" android:required="false"/>
>   <uses-feature android:name="android.hardware.location.gps" android:required="false"/>
>   <uses-feature android:name="android.hardware.location.network" android:required="false"/>
> ```
> 
> For wondows In the Solution Explorer pane, right-click on the Platforms/Windows/Package.appxmanifest file, and select View Code. Under the node, add the element.
> 
> See https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?tabs=windows

this was extremely helpful...Granted, the current stable version as of today  is 4.1.1 and this line:

`mapViewElement.Navigator.NavigateTo(new MPoint(smc.x, smc.y), mapControl.Map.Resolutions[16]);  //0 zoomed out-19 zoomed in`

now gives this error:

`CS1061	'Navigator' does not contain a definition for 'NavigateTo' and no accessible extension method 'NavigateTo' accepting a first argument of type 'Navigator' could be found (are you missing a using directive or an assembly reference?)`

but thanks to having your whole text project, I jut downgraded to 4.0.0 beta.5 and now I can finally start playing with mapsui code.

**Comment by pauldendulk** [comment]
The Navigator has been rewritten. CenterOnAndZoomTo might the best alternative method for what you are doing. Here is the documentation:
https://mapsui.com/api/Mapsui.Navigator.html#Mapsui_Navigator_CenterOnAndZoomTo_Mapsui_MPoint_System_Double_System_Int64_Mapsui_Animations_Easing_

**Comment by kablammyman** [comment]
> The Navigator has been rewritten. CenterOnAndZoomTo might the best alternative method for what you are doing. Here is the documentation: https://mapsui.com/api/Mapsui.Navigator.html#Mapsui_Navigator_CenterOnAndZoomTo_Mapsui_MPoint_System_Double_System_Int64_Mapsui_Animations_Easing_

Thanks for this. I was able to make everything work with a lil bit of trial and error thanks to your help.

I was looking for how to fix that line before, but I had no idea where to find the info you shared.

And for anyone wondering, this is how that line of code should look with v 4.1.1

`var smc = SphericalMercator.FromLonLat(long, lat);
mapControl.Map.Home = n => n.CenterOnAndZoomTo(new MPoint(smc.x, smc.y), n.Resolutions[12]);`
