### ISSUE TITLE
.Net Maui How to add line (polyline) to basic map  [Not a bug]

### ISSUE THREAD

**Issue by gfmoore** [Mapsui/Mapsui#1666]
I know you must think I am very stupid, but everytime I think I start getting a handle on this I fail again.

Thanks to the help received I can now use a map
```
   //setup Mapsui map
    mapControl = new Mapsui.UI.Maui.MapControl();
    mapControl.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
    
    //link to xaml
    mapViewElement.Map = mapControl.Map;
```

I can add pins and I can reposition and scale.

I am now trying to add a line between two points or what I suspect is to use a polyline.

Here's what I thought I'd try based on the syntax for adding a pin
i.e     mapViewElement.Pins.Add(myPin);

```
    Polyline pl = new Polyline { StrokeWidth = 4, StrokeColor = c};

    var pos1 = new Position(lng1, lat1);
    var pos2 = new Position(lng2, lat2);

    pl.Positions.Add(pos1);
    pl.Positions.Add(pos2);

    mapViewElement.   hopedtohavepolyline    .Add(pl);
```

I feel I am so close?

I suspect I may also have to change lat, lng to spherical coordinates (no problem)

Could someone again have mercy on me please and point me in the right direction.

By the way what is the best practice for coordinates? I've always thought in terms of latitude and longitude. But should every "location" be in these SphericalMercator units. In which case I assume I should convert all my latitudes and longitudes to SphericalMercator units in the source of my coordinates list?

**Comment by gfmoore** [comment]
Sorry, I have only just realised that there is an actual Discussion tab. Do you want me to move this? Or can you do it?

**Comment by charlenni** [comment]
Type mapViewElement. and look, what VS suggest you. You will find Drawables. Select this and read the help. It says, that this is for drawables like Polygon and Polyline.

**Comment by gfmoore** [comment]
Thanks @charlenni, appreciate your help :)

I  sort of figured it out and I've left in my trials to show you how I struggled to get the right magic incantation
```
  public void DrawPolyLine(List<PostcodePosition> pp, Color c)
  {
   //PostcodePosition is a clas that contains a Postcode (UK) and a latitude and longitude)

    Polyline pl = new Polyline { StrokeWidth = 10, StrokeColor = Colors.Green };

    var p1 = SphericalMercator.FromLonLat(pp[0].Longitude, pp[0].Latitude);
    var p2 = SphericalMercator.FromLonLat(pp[1].Longitude, pp[1].Latitude);

    //MPoint mp1 = new MPoint
    //{
    //  X = p1.x,
    //  Y = p1.y
    //};

    //MPoint mp2 = new MPoint 
    //{ 
    //  X = p1.x,
    //  Y = p1.y
    //};

    //Position pos1 = new Position(mp1);
    //Position pos2 = new Position(mp2);

    //Position pos1 = new(p1.x, p1.y);
    //Position pos2 = new(p2.x, p2.y);
    
    Position pos1 = new(pp[0].Latitude, pp[0].Longitude);
    Position pos2 = new(pp[1].Latitude, pp[1].Longitude);

    //var pos1 = new Position(pp[0].Longitude, pp[0].Latitude);
    //var pos2 = new Position(pp[1].Longitude, pp[1].Latitude);

    pl.Positions.Add(pos1);
    pl.Positions.Add(pos2);

    mapViewElement.Drawables.Add(pl);

```

This gives rise to a lot of interesting questions:

What is the relationship or definition of 
MPoint
SphericalMercator
Position
etc

and it seems Position uses latitude, longitude whereas point uses X(longitude) and Y(latitude).

Shouldn't Position do the same. I assume this is a long lasting thing and is unlikely to be changed if it is wrong.

How do I know when I can use a straight latitude/longitude or should use the SpericalMercator values.

However, I will close this as I've now achieved my goal. (Reminds me of the old Dos adventure games: You are standing in a dark room, you can hear heavy breathing...

**Comment by EORG-Dev** [comment]
I wanna add that one can add the Polyline `pl` by the use of 

`var pointLayer = new Layer
 {
     DataSource = new MemoryProvider(pl.Feature),
     Style = null,
 };
  mapViewElement.Map.Layers.Add(pointLayer);`

It too took me a long time to fiddle around with this. I would wish for there to be extensive Mapsui.UI.Forms-Documentation but I fully understand that is alot of unpaid effort. 

Thank you, gfmoore, for putting in that little bit of effort
