### ISSUE TITLE
Dependency failure with HarfBuzzSharp 2.8.2-preview.178

### ISSUE THREAD

**Issue by hinnerkweiler** [Mapsui/Mapsui#1676]
**Describe the bug**
Build fails on Mac following the quick start procedure for MAUI from Website. Following errors came up:

******/code/maptest/maptest/EXEC: Error: must specify directory to which to extract with -d option (maptest)
******/.nuget/packages/harfbuzzsharp.nativeassets.maccatalyst/2.8.2-preview.178/buildTransitive/net6.0-maccatalyst13.5/HarfBuzzSharp.NativeAssets.MacCatalyst.targets(9,9): Error MSB3073: The command "unzip -d  " exited with code 10. (MSB3073) (maptest)

**To Reproduce**
Following the steps outlined at: http://mapsui.com/documentation/getting-started-maui.html (installing MapsUI via VS Nuget Manager or dotnet CLI.

**Expected behavior**
Successful compiling  

**Desktop (please complete the following information):**
 - macOS 12.3
 - Visual Studio 17.3-Pre (b.1038)

**Solution:
*HarfBuzzSharp 2.8.2-preview.178 seems to have a stable 2.8.2 release now. I manually installed it and that solved the errors for me.*

**Comment by softlion** [comment]
Same issue on iOS. Not with compilation, but it crashes at runtime.

Adding HarfBuzzSharp 2.8.2.1-preview91 fixed it.

I saw it's already updated in the source code of MapsUI.

So a new nuget release would be nice :)

**Comment by taublast** [comment]
Can confirm this bug is still present in mapsui.maui 4.0.0-beta.5 and manually installing HarfBuzzSharp 2.8.2.3 into maui project works around it.

**Comment by pauldendulk** [comment]
@hinnerkweiler @taublast @softlion Is this problem still present in Mapsui 4.0.0-beta.8?

**Comment by hinnerkweiler** [comment]
Not that one... but still broken. In fact not even the "Mapsui MAUI getting started" from documentation works (tried it today again, still not working) an I abandoned Mapsui.

<img width="864" alt="Screenshot 2023-02-21 at 09 30 37" src="https://user-images.githubusercontent.com/18248862/220296254-b74af75e-fece-4c7a-97e0-678244771291.png">

**Comment by softlion** [comment]
> 

No it's fixed.

**Comment by softlion** [comment]
> Not that one... but still broken. In fact not even the "Mapsui MAUI getting started" from documentation works (tried it today again, still not working) an I abandoned Mapsui.
> 
> <img alt="Screenshot 2023-02-21 at 09 30 37" width="864" src="https://user-images.githubusercontent.com/18248862/220296254-b74af75e-fece-4c7a-97e0-678244771291.png">

You forgot to register the handlers. RTFM :)

```
	builder
			.UseMauiApp<App>()
			//For Mapsui
			.UseSkiaSharp(true)
```

**Comment by pauldendulk** [comment]
@softlion Thanks! I was already googling for a replacement for my broken mac (seriously), but there is no immediate need now.

I'll investigate if there is a better way to deal with error. Also, I improved the getting started a bit 
https://mapsui.com/documentation/getting-started-maui.html.

**Comment by pauldendulk** [comment]
Conclusion: fixed in Mapsui 4.0.0-beta.8.

**Comment by hinnerkweiler** [comment]
@softlion 
> You forgot to register the handlers. RTFM :)
> 
> ```
> 	builder
> 			.UseMauiApp<App>()
> 			//For Mapsui
> 			.UseSkiaSharp(true)
> ```

What ever caused you to think I did not do it, led you to a just wrong conclusion. 

However, after reading your comment, I compared the errors and they come out the same (see below). If it has no effect to register the handlers it seems obvious that the broken part of mapsui is somewhere else. The exception is at least not caused by just a missing `.UseSkiaSharp(true)` 

@pauldendulk Sorry, but to me it it looks like that old mac could need that replacement ;)
Looking at the edits on the Manual it now reads
`and with Microsoft.Mapsui.Platform.HandlerNotFoundException has been thrown on Mac.`– This is worse than before as this apparently has nothing to do with the cause identified by @softlion and potentially drives people mad by pointing them in a wrong direction for the cause. 

But I have one more thing: The "Getting started" compiles and runs on the iPhone! 🥇 Maybe that would be a better hint for the documentation for people like me who never went so far to even try because it is not even starting on the Mac: 
Also since it runs on the phone but not on the Mac it can't be that mapsui is all broken and than I found this in the App Logs when starting it on the mac - and maybe you can spare that new Mac as you can't solve it anyways:

```
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
```


<img width="952" alt="Screenshot 2023-02-23 at 23 43 30" src="https://user-images.githubusercontent.com/18248862/221047919-6ac5e829-6835-4be2-913e-1d49cbf0c0e2.png">

<img width="901" alt="Screenshot 2023-02-24 at 00 35 20" src="https://user-images.githubusercontent.com/18248862/221055531-3efe0403-4b82-41c0-8eee-416edccdf888.png">

**Comment by charlenni** [comment]
Could it be that this is a SkiaSharp problem and has nothing to do with Mapsui?

**Comment by pauldendulk** [comment]
@hinnerkweiler Could you try to set the static `MapControl.UseGPU = false;` before the builder code? Perhaps there is a problem with the Skia SKGLView on Mac.

**Comment by hinnerkweiler** [comment]
That's it! @pauldendulk 
<img width="1021" alt="Screenshot 2023-02-24 at 11 45 35" src="https://user-images.githubusercontent.com/18248862/221159691-8230a4d5-1dfe-4784-a27f-e8b558573b75.png">


I just created a new issue as fallow up since this seemed to be of another topic so you may close both issues and save the money for a mac. Perfect! Thank you.
