### ISSUE TITLE
SqlitePersistentCache can not use for MAUI project

### ISSUE THREAD

**Issue by wanglehui** [Mapsui/Mapsui#1689]
Hi, we create new MAUI project guide by quick start : https://mapsui.com/documentation/getting-started-maui.html

when SqlitePersistentCache is required，add configuration in project file like this:

	<ItemGroup>
		<PackageReference Include="Mapsui.Maui" Version="4.0.0-beta.5" />
		<PackageReference Include="Mapsui.Extensions" Version="4.0.0-beta.5" />
		<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.0" />
	</ItemGroup>

but this seem not work and throw System.TypeLoadException：

this project run in Android platform

**Comment by inforithmics** [comment]
use
`<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />`
instead of
`<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.0" />`

This commit should fix it. Not yet released or merged

https://github.com/Mapsui/Mapsui/pull/1683/commits/9a01930d9c84b40582382c184ff9eeef5acee225

**Comment by wanglehui** [comment]
Thank for your response,  

we use <PackageReference Include="sqlite-net-pcl" Version="1.8.116" /> in project,
but get the new exception：
=======================
System.IO.FileNotFoundException: 'Could not load file or assembly 'SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.4.976, Culture=neutral, PublicKeyToken=b68184102cba0b3b' or one of its dependencies.'
=======================
Do i need  wait for project Mapsui.Extensions update ?

We create new Android project guide by quick start :
https://mapsui.com/documentation/getting-started-android.html

And it work well for SqlitePersistentCache used.

**Comment by inforithmics** [comment]
I would add SQlite Pcl bundle green.

<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0" />

Do you use sqlite beside Mapsui, if yes then you should change your usage to sqlite-net-pcl because there would be two sqlite implementations and dll.

**Comment by wanglehui** [comment]
Aha！ Your solution worked well. Thanks a lot for your help.
