### ISSUE TITLE
Avalonia: frequent calling of Logger

### ISSUE THREAD

**Issue by IldarKhayrutdinov** [Mapsui/Mapsui#1691]
**Describe the bug**

Frequent calling of `Logger` on `Avalonia` when idle. On `Wpf` called only when the map updating.  
Test project: [AvaloniaApplication1.zip](https://github.com/Mapsui/Mapsui/files/9362948/AvaloniaApplication1.zip)

**To Reproduce**
1. Create empty avalonia project from template and add mapsui (see test project).
2. Run in debug or release mode.
3. Do nothing.
4. There are a lot of logs writing on continuously.

**Expected behavior**
Logging only when the map updating as on wpf.

**Screenshots**
![image](https://user-images.githubusercontent.com/29858598/185145313-8353e78a-13fc-4a7b-a03b-e4c8bb547ab1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - SDK: .Net 6
 - Avalonia 0.10.18 (latest)
 - Mapsui 4.0.0-beta.5 (latest)

**Comment by pauldendulk** [comment]
Agreed. This needs to be fixed.

**Comment by pauldendulk** [comment]
Fixed in next release.
