### ISSUE TITLE
PinClicked handler is not called in Maui

### ISSUE THREAD

**Issue by rperazzolli** [Mapsui/Mapsui#1692]
I'm testing Mapsui for Maui.
I can display a Pin on the map, but it doesn't respond to the click event.
The code I use is as follows:

    var MapaBase = new Mapsui.UI.Maui.MapControl();
    MapaBase.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
    Content = MapaBase;
		MapView Ventana=new MapView();
		Ventana.Map = MapaBase.Map;
		Ventana.MyLocationEnabled = false;
		Mapsui.UI.Maui.Pin PinLocal = new Mapsui.UI.Maui.Pin()
		{
			Position = new Mapsui.UI.Maui.Position(-38, -60),
			Color = new Microsoft.Maui.Graphics.Color(255, 0, 0),
			Label = "AAAA",
			Type = PinType.Pin,
			Scale = 0.5f
		};
		Ventana.PinClicked += Ventana_PinClicked;
		Ventana.Pins.Add(PinLocal);
    var smc = SphericalMercator.FromLonLat(-60, -38);
    MapaBase.Map.Home = n => n.NavigateTo(new MPoint(smc.x, smc.y), MapaBase.Map.Resolutions[12]);

**Comment by pauldendulk** [comment]
Closing. Sorry, we never looked into this. Please retry this in version 4.0.0.
