### ISSUE TITLE
Avalonia.XPlat support?

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#1697]
Hi, I'm trying to get Mapsui working in Avalonia.xplat, but get an error (not compatible with netstandard2.0) when installing the Mapsui.Avalonia package,

To reproduce:

```
$ dotnet new avalonia.xplat
$ Install-Package Mapsui.Avalonia -pre
Install-Package : NU1202: Package Mapsui.Avalonia 4.0.0-beta.5 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Mapsui.Avalonia 
4.0.0-beta.5 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)
```

Is there a way to get Mapsui working in Avalonia.xplat project?

**Comment by bertt** [comment]
Some more testing: I can install Mapsui NuGet package to the shared project, but when install Mapsui.Avalonia to one of the head projects I get error:

 Mapsui.Avalonia 4.0.0-beta.5 requires Avalonia.Desktop (>= 0.10.12 && < 0.11.0) but version Avalonia.Desktop 11.0.0-preview1 was resolved.	

Potential fix: Increase Avalonia.Desktop dependency to higher version

**Comment by inforithmics** [comment]
Shouldn't be a problem, I'll try to make a pull request.

**Comment by inforithmics** [comment]
Here the pull request:
https://github.com/Mapsui/Mapsui/pull/1698

**Comment by bertt** [comment]
merged!
