### ISSUE TITLE
Mapsui.Samples.Maui.MapView has a Project Reference to Mapsui.UI.Maui

### ISSUE THREAD

**Issue by pkzOR** [Mapsui/Mapsui#1699]
Following the guidelines in the Maui Quickstart (http://mapsui.com/documentation/getting-started-maui.html), I've create a Maui App and a dll project (called Common) where my MapView and ViewModel is located.

The line in my MapView.xaml   `xmlns:mapsui="clr-namespace:Mapsui.UI.Maui;assembly=Mapsui.UI.Maui" ` gives the error _Mapsui.UI.Maui not found_.  

I have verified that the Dependencies in my Common.dll match the Dependencies in the Mapsui.Samples.Maui.MapView, but I see that your  **Mapsui.Samples.Maui and**  **Mapsui.Samples.Maui.MapView** both have a Project Reference to **_Mapsui.UI.Maui_**.   

Is that expected?  I was expecting that,  for my project the Mapsui package reference would be enough. Shouldn't all the samples just reference the required nugets? Or am I totally confused?

**Comment by pkzOR** [comment]
I now see that I needed to add nuget package for mapsui.maui, but it still seems the samples should have the nuget references.

**Comment by inforithmics** [comment]
[Mapsui.nuget](https://www.nuget.org/packages/Mapsui/) package is only the Basis.
for Maui you have to Reference [Mapsui.Ui.Maui](https://www.nuget.org/packages/Mapsui.Maui/4.0.0-beta.5) for that you have to check the include Previews checkbox in Visual Studio. (Because the Mapsui.Maui is still in Beta).

The samples use for debugging purposes the projects. Project Mapsui.UI.Maui is Mapsui.Maui nuget package.

**Comment by pauldendulk** [comment]
> I now see that I needed to add nuget package for mapsui.maui, but it still seems the samples should have the nuget references.

If the samples used that nugets that would be more representative of the situation the users are in, but with such a setup we can not do refactoring throughout the code and the samples. So Renaming a field in Mapsui would need manual renaming of that field in the samples. So, this way we make it easier for ourselves, which I think is a necessity given the capacity we have.

**Comment by pkzOR** [comment]
OK. Thanks for the explanation.
