### ISSUE TITLE
How can I make Custom Tile Map like Deepzoom

### ISSUE THREAD

**Issue by honeyhead** [Mapsui/Mapsui#1700]
I have experience using Deepzoom(Tile Images) in Silverlight and WPF.

And I wanted to implement it with SkiaSharp, but there was no way.

Since it is similar to the method of implementing the map, I thought that Mapsui would be possible. Is it possible to implement these things with Mapsui?

The Tile structure corresponding to Deepzoom is similar to that of Openseedraon or lipvips

Downsampling can be a way when you need to load a large amount of images from a mobile app, but I want to process them on the server rather than that.

![image](https://user-images.githubusercontent.com/3714819/185937123-a252e074-0609-4596-92ca-7977f953391a.png)

I think [Breath Companion ](https://software-notion.de/apps/breath-companion) is implemented like this, right?

**Comment by pauldendulk** [comment]
Mapsui supports tile layers which have this kind of tile piramide. So, this is possible. You have to create such a tile set yourself, there is no tooling for it. You could use the mbtiles format to store those tiles.
