### ISSUE TITLE
Cyclic dependency in MAUI nuget package

### ISSUE THREAD

**Issue by gplumb** [Mapsui/Mapsui#1702]
**Describe the bug**
When attempting to install the latest nuget pre-release for Mapsui.Maui, Visual Studio complains (`NU1108: Cycle detected`).  Full output from console:

```
Install-Package : NU1108: Cycle detected. 
  MapsUI -> Mapsui.Maui 4.0.0-beta.5 -> Mapsui (>= 4.0.0-beta.5).
At line:1 char:1
+ Install-Package Mapsui.Maui -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'MapsUI'.
At line:1 char:1
+ Install-Package Mapsui.Maui -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**To Reproduce**
1. Create a new MAUI project in Visual Studio 2022 (17.3.2), using .net 6
2. Install `Latest prerelease 4.0.0-beta.5` via nuget or via the Package Manager console (`Install-Package Mapsui.Maui -pre`)

**Expected behavior**
Install the latest MAUI nuget pre-release :-)

**Desktop (not sure this is helpful, but nonetheless...):**
 - Windows 11 21H2
 - VS 2022 (17.3.2)

**Comment by inforithmics** [comment]
is MapsUI your project i guess this is a nuget error resolution error. Try renaming mapsui to something different than MapsUI.

**Comment by gplumb** [comment]
Oh ffs... that's exactly it!  Sorry for wasting your time 🤦

**Comment by gplumb** [comment]
Oh ffs... that's exactly it! Sorry for wasting your time 🤦
