### ISSUE TITLE
Navigated event not triggered when map is moved

### ISSUE THREAD

**Issue by Tardigrade42** [Mapsui/Mapsui#1710]
**Describe the bug**
I tried to track if the user moved the map (to show a refocus button). For this, I tried to use the `Navigated` event from the `INavigator` interface. But for some reason it only triggers, if I scroll in or out of the map. But I expected it to trigger also if the map is moved.

I used the following setup:
`Mapsui.Maui` version `Latest prerelease 4.0.0-beta.5`  
`Visual Studio Community 2022 Preview` version `17.4.0 Preview 1.0`
On a `Windows 10 Pro` laptop version `19044.1949`  
I built and run the Maui App locally on the laptop.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build a new Maui App from the template
2. Add a map `MapControl map = new();`
3. Add a layer `map.Map.Layers.Add(OpenStreetMap.CreateTileLayer());`
4. Add the map to the xaml to be shown.
5. Subscribe to the `Navigated event`: `map.Navigator.Navigated += NavigationHandler;`
6. Add a useful method-implementation:
```C#
private void NavigationHandler(object sender, ChangeType e) {
      Debug.WriteLine("Something changed");
}
```
7. If you now run the app on Windows and scroll in or out, you will see the output.
8. If you only move the map, nothing happens => the issue

**Expected behavior**
I would have expected, that I get the output in step 7 and 8.
Is this a bug or am I doing something wrong here?

**Comment by pauldendulk** [comment]
The Navigator is intended as a class that the user of Mapsui (a developer) can use to change the viewport state, but not all viewport state within Mapsui is changed through. Perhaps the MapControl.Viewport.ViewportChanged can be used in your scenario.

**Comment by Tardigrade42** [comment]
Awesome, that worked. I only have one challenge now: If the event is triggered, I pass a bool to another class where I would like to set the visibility of a button according to the bool. However, if I do so, I get the following error:
`Eine Schnittstelle, die für einen anderen Thread marshalled war, wurde von der Anwendung aufgerufen. (0x8001010E (RPC_E_WRONG_THREAD))`
(I don't know why this is in German)
Is the `MapControl.Viewport.ViewportChanged` event triggered from another thread? / Do you have any Idea, why this exception is thrown?

**Comment by charlenni** [comment]
You have to call things, that make changes to the GUI on the main thread. You can not relay, that all events are created in main thread.

**Comment by Tardigrade42** [comment]
Thanks for the answer! Now I found my mistake. In case anyone else is reading this and is struggling with the same issue, read this doc:
https://learn.microsoft.com/de-de/dotnet/maui/platform-integration/appmodel/main-thread

Since my issue is solved, I will close the issue. Thanks to you both for the support!
