### ISSUE TITLE
Freezing with many LineStrings im MemoryLayer

### ISSUE THREAD

**Issue by TomQv** [Mapsui/Mapsui#1711]
Hi, I'm new to MapsUI, trying to find out, if it could replace the old mapengine in my apps.

To display gps-tracks I created a MemoryLayer. In the ctor the gps-tracks are loaded from my source source, the LineStrings are created and then geometries and features. I even create a simplified copy for each resolution for each linestring.

In GetFeatures, just the features according to box and resolution are returned.

It works fine, but only if its not too many tracks. For example if its maybe more then 50 tracks with 1000 points each, the mapcontrol freezes. Funny enough I see in the debugger windows, that GetFeatures is still called and also the process is running with maybe 20% cpu-load.

Am I doing something wrong? Is there a better way to render many linestrings?
I also found this issue #1705, which might be similar?

I'm working with 4.0.0-beta5 on UWP, didn't test other platforms yet.

```

public class TrackLayer : Mapsui.Layers.MemoryLayer 
    {
        Dictionary<double, GeometryFeature[]> _features;

        public TrackLayer(IMarkEx markex, Mapsui.Map map)
        {
            try
            {
                this.Tag = markex;
                this.Name = markex.Mark.Name;
                this.Style = markex.LineStyle();

                // TODO: projection??

                // TODO: one linestring for each tracksegment
                var coordinates = markex.Track.GetList().Select(t => SphericalMercator.FromLonLat(t.Lon, t.Lat).ToCoordinate()).ToArray();
                var linestrings = new GeometryFactory().CreateLineString(coordinates);

                var lastcount = 0;
                _features = new Dictionary<double, GeometryFeature[]>();
                foreach (var resolution in map.Resolutions)
                {
                    var simplifiedlinestrings = TopologyPreservingSimplifier.Simplify(linestrings, resolution);
                    var count = ((LineString)simplifiedlinestrings).Count;
                    if (count != lastcount)
                    {
                        var features = new[] { new GeometryFeature { Geometry = simplifiedlinestrings } };
                        _features.Add(resolution, features);
                        lastcount = count;
                        //Debug.WriteLine(linestrings.Count + " " + count + "  " + res);
                    }
                }
            }
            catch (Exception ex)
            {
                var message = HelperX.CreateExeptionMessage(ex);
                Debug.WriteLine(message);
            }
        }

        public override IEnumerable<IFeature> GetFeatures(MRect box, double resolution)
        {
            // Safeguard in case BoundingBox is null, most likely due to no features in layer
            if (box == null) { return new List<IFeature>(); }
            if (_features == null) { return new List<IFeature>(); }

            var biggerRect = box.Grow(
                    SymbolStyle.DefaultWidth * 2 * resolution,
                    SymbolStyle.DefaultHeight * 2 * resolution);

            // find feature closest to resolution
            var minresolution = _features.Keys.Min(i => (Math.Abs(resolution - i), i)).i;
            var features = _features[minresolution];
            var feature = features.Where(f => f.Extent?.Intersects(biggerRect) == true);
            return feature;
        }
}

```

**Comment by pauldendulk** [comment]
So, the MapControl does not show any updates while it seems the rest of the app behaves correctly? 

Do you see exceptions anywhere? Could you try to attach to the Mapsui logging https://mapsui.com/documentation/logging.html?

**Comment by TomQv** [comment]
I added a simple handler to logging:

```
Mapsui.Logging.Logger.LogDelegate += (level, message, ex) =>
      Debug.WriteLine("Mapsui.Logging: " + level + " " + message + " " + QvX.HelperX.CreateExeptionMessage(ex));
```

And the output is loads of:

```
Mapsui.Logging: Information Time for drawing control [ms]: 916.469 
Mapsui.Logging: Information Time for drawing control [ms]: 911.9809 
Mapsui.Logging: Information Time for drawing control [ms]: 916.6611 
Mapsui.Logging: Information Time for drawing control [ms]: 958.6009 
Mapsui.Logging: Information Time for drawing control [ms]: 941.7189 
Mapsui.Logging: Information Time for drawing control [ms]: 936.5741 
Mapsui.Logging: Information Time for drawing control [ms]: 953.7888 
```
GetFeatures()  just seems to be too busy with many linestrings. This was actually my question, how to make it easier. I read somewhere, that you guys are working on a GetFeaturesAsync? Or should I simplify the geometry  more? What is the most efficent way to render some amount of linestrings? Didn't try RasterLayer yet.

**Comment by charlenni** [comment]
The problem is, that you try to redraw all the lines as much as often possible. Each time you have to get the Features, convert them to SKPath and draw them. This needs much time.

You could use your own renderer, that saves the SKPath if they are created.

**Comment by TomQv** [comment]
Ok, thanks. I'm still trying to understand, how the workflow is in Mapsui.
Is there a sample of an own renderer? And for how long are the SKPaths valid? Until the resolution changes?

**Comment by charlenni** [comment]
All the renderers are implemented as "own" renderers. So you could look into the source code itself.

Another possibility, that come into mind could be to cut the big LineStrings into shorter ones. If you have one big LineString, all the Points inside of it have to be converted each time. Think about a LineString of 1000 Points, from which only two are visible. So try co create a new Feature with only the visible points of the LineString. Perhaps this speeds the things up.

**Comment by charlenni** [comment]
Look in LineStringExtension.ca in the function ToSkiaPath what each time happens, when a LineString is draw on the screen. The whole LineString is converted in screen coordinates (not sure, if it is reduced to the viewport) and then clipped to the screen. If you do this each time for 50*1000 Points, then you need some time.

**Comment by inforithmics** [comment]
Possible Workarounds would be to use the RasterizingTileLayer or the RasterizingLayer, so the Features are rendered into a Bitmap 
which could be fast rendered. See the Samples how to use it.

**Comment by TomQv** [comment]
@charlenni  Ok, thanks.
I see actually two bottle necks. 
First the skpaths should be cached, in case the viewport was not changed (too  much).
And second, there seem to be no cancelling of rendering all geometries currently, when the viewport continues to change while rendering is still busy.
Like with BruTiles, which is ultra fast and very responsive.

@inforithmics rasterizing is actually no option for us, because we really want fast and nice vector rendering.

I'll play a bit with own renderer..

**Comment by charlenni** [comment]
You could look on my [vector tile renderer](https://github.com/charlenni/VectorTileLayers) to see, how I did it. Is for Mapsui V3, but should work with some changes.

**Comment by pauldendulk** [comment]
I assume this is not a bug but a performance issue. The question mentions 50 tracks with 1000, so I assume 50000 vertices. This could indeed be slow. 

Solution:
Use RasterizingTileLayer.

Future improvements:
Convert to Skia outside of render loop. There will always be some limit however.
