### ISSUE TITLE
The api page is empty

### ISSUE THREAD

**Issue by MateuszLas421** [Mapsui/Mapsui#1730]
**Describe the bug**
The api page is empty

**To Reproduce**
http://mapsui.com/api/index.html

**Comment by pauldendulk** [comment]
Thanks for reporting this. 

This is a failing doc build:
https://ci.appveyor.com/project/pauldendulk/mapsui-373p2
We probably need to install something before we build it.

**Comment by inforithmics** [comment]
I’ll make a pull request to fix this. Missing .net 6.0.401 sdk

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/1740
