### ISSUE TITLE
VS 2022 17.4 Preview 6 problem

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#1750]
Hello,

I updated Mapsui and VS 2022 today and now get an error, when compiling Mapsui:

![grafik](https://user-images.githubusercontent.com/4381223/200378551-968ef0e3-c9f4-410f-9af9-c2f7de39b12b.png)

The first part I get when I call "Restore NuGet packages". So I go to the NuGet manager of solution and look into, which packages are installed, but get the second part error message.

Something I do wrong? Or should I downgrade to 17.3?

**Comment by inforithmics** [comment]
This is a new validation NU1608 
Two possibilities.

1) Ignore the Warning
 <NoWarn>$(NoWarn);NU1008;NU1701;NU1608</NoWarn>
In Directory.Build.props

2) Fix the Versions
The more work task would be to specify in Directory.Packages.props versions that work but i guess maui and Xamarin.Forms have different Versions. So I would keep the newer versions in Directory.Packages.props. And use VersionOverride in Xamarin.Forms to select the right versions.

**Comment by charlenni** [comment]
Thank you, @inforithmics, for your help. I found this morning the problem: In global.json is the .Net version hard-coded to 6.0.402, which I don't have on my system, but 7.0.100-rc2, which comes with VS 2022 17.4.0 Preview 6.0. Changed it in global.json to this version and the Maui and WinUI versions are compiling.

The NuGet problem for the solution still exists. I always get an error, "Value can not be null. Parameter name: versionRange" as visible in the screenshot. Is this "versionRange" from Mapsui?

**Comment by inforithmics** [comment]
Looks for me like a nuget error message, that it tried to find a compatible VersionRange but couldn't. I thinkt today Visual Studio 2002 (Non Preview and .NET 7  Frameworks comes out so I'll have a look at it).

**Comment by inforithmics** [comment]
Following change in global.json should work

```
{
  "sdk": {
    "allowPrerelease": true,
    "version": "6.0.402",
    "rollForward": "latestMajor"
  },

latestMajor means 7.0.0 is allowed
prerelease means that 7.0.0-rc is allowed.

Have you tried Mapsui.Legacy.sln (Disables .NET 6 Target because on Mac .NET 6 has made some problems earlier) 
```

**Comment by inforithmics** [comment]
In this pull request I fixed the nuget warnings.
https://github.com/Mapsui/Mapsui/pull/1754

**Comment by pauldendulk** [comment]
I assume this is fixed.
