### ISSUE TITLE
Clearing callouts when another is clicked

### ISSUE THREAD

**Issue by RParkerE** [Mapsui/Mapsui#1756]
I am fairly new to C#/.NET and have been working through building an app. I know .NET7 recently released and brought map functionality to Maui, but have already implemented code using MAPSUI. There doesn't seem to be great documentation surrounding the usage of this, however.

Looking through their getting started page and their examples on Github (specifically: [SingleCalloutSample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Callouts/SingleCalloutSample.cs)) I was able to get my list of places to show up on the map and when clicked display certain features.This has led to me only being able to toggle whether the callout is displayed or not. What I am hoping to figure out is how to disable all other callouts once another location is selected, so that only a single callout is displayed at a time.

I am aware the following code is the logic dictating the callout displays, but not sure how to adjust it to "wipe" existing callouts on click. Any help would be greatly appreciated:

```
private static void MapOnInfo(object? sender, MapInfoEventArgs e)
{
var calloutStyle = e.MapInfo?.Feature?.Styles.Where(s => s is CalloutStyle).Cast().FirstOrDefault();
if (calloutStyle != null)
{
calloutStyle.Enabled = !calloutStyle.Enabled;
e.MapInfo?.Layer?.DataHasChanged(); // To trigger a refresh of graphics.
}
}
```

**Comment by charlenni** [comment]
What you search for is the property [UniqueCallout](https://github.com/Mapsui/Mapsui/blob/1fb8bea6907b91a7ecf246d298f215e407032030/Mapsui.UI.Forms/MapView.cs#L238) of MapView

**Comment by RParkerE** [comment]
So in my map initialization I just need to add `MyMapView.UniqueCallout = true;`?

**Comment by charlenni** [comment]
And if you call NyMapView.HideCallouts()? What happens then?

**Comment by charlenni** [comment]
Argh, now I see, that you don't use the Pin from MapView, but make an own feature with a callout style. That is different. You have to remove the callouts by yourself with setting the enabled flag to false for all visible features.

**Comment by RParkerE** [comment]
Okay. I believe I am understanding now. To use `UniqueCallout` I would need to be using the pins such as the example [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/PinSample.cs#L149). Otherwise I need to call a method to clear/remove the currently visible custom callouts before displaying the next?

**Comment by RParkerE** [comment]
Okay. I believe I am understanding now. To use `UniqueCallout` I would need to be using the pins such as the example [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/PinSample.cs#L149). 

Otherwise to clear the callouts I would need to implement and call clear function alongside/within the clickevent `private static void MapOnInfo(object? sender, MapInfoEventArgs e)`. Where I am struggling is the `MapInfoEventArgs e` I am assuming will only return the point/callout which was clicked, and I do not know how to access an array of all enabled callouts to turn the others off.

I attempted to implement something along the lines of the two solutions below and neither did what I wanted. The first prevented all callouts from showing and the second had the same effect as code originally did.

```
private static void MapOnInfo(object? sender, MapInfoEventArgs e)
 {
    e.MapInfo?.Feature?.Styles.Clear();
    var calloutStyle = e.MapInfo?.Feature?.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
    if (calloutStyle != null) 
    {
        calloutStyle.Enabled = !calloutStyle.Enabled;
        e.MapInfo?.Layer?.DataHasChanged(); // To trigger a refresh of graphics
    }
}
```

```
private static void MapOnInfo(object? sender, MapInfoEventArgs e)
 {
    var calloutStyles = e.MapInfo?.Feature?.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().AsParallel();
    if (calloutStyle != null) 
    {
        foreach(calloutStyle in calloutStyles)
            calloutStyle.Enabled = !calloutStyle.Enabled;
        e.MapInfo?.Layer?.DataHasChanged(); // To trigger a refresh of graphics
    }
}
```

**Comment by charlenni** [comment]
Ok, if you don't want to use Pins, then you have to do it by hand.

The function `CreatePointLayer()` creates a `MemoryLayer`that holds one or more `Features`. That are your pins. Each of this `Feature` has none (`Feature` isn't drawn), one or more `Styles`. This `Style` tells Mapsui, how the `Feature` should be drawn. One of this `Styles` is the `CalloutStyle`. It says Mapsui, that at this place a callout should be drawn, but only, if `CalloutStyle.Enabled=true`.

To hide all callouts on your layer, you have to set `Enabled=false` for all `Feature` that have a `CalloutStyle`.

```
foreach(var feature in e.MapInfo?.Layer?.Features)
  foreach(var style in feature.Styles)
    if (style is CalloutStyle)
      ((CalloutStyle)style).Enabled = false;
```

That's it.

Or you save the last `Feature` with a callout ;-)

**Comment by RParkerE** [comment]
Thank you, this solves it. Appreciate all the help!

**Comment by charlenni** [comment]
So we could close this.

**Comment by RParkerE** [comment]
I found that `e.MapInfo?.Layer` extends from `ILayer` which has no definition for `Features`:
`CS1061	'ILayer' does not contain a definition for 'Features' and no accessible extension method 'Features' accepting a first argument of type 'ILayer' could be found (are you missing a using directive or an assembly reference?)`

I did get this working by creating a `List<CalloutStyle> calloutlist` to keep track of clicked callouts and updated the code section as shown below:
```
private static void MapOnInfo(object? sender, MapInfoEventArgs e)
        {
            var calloutStyle = e.MapInfo?.Feature?.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
            if (calloutStyle != null)
            {
                calloutlist.Add(calloutStyle);
                foreach (var callout in calloutlist)
                {
                    callout.Enabled = false;
                }
                calloutStyle.Enabled = !calloutStyle.Enabled;
                e.MapInfo?.Layer?.DataHasChanged(); // To trigger a refresh of graphics.
            }
            if (calloutlist.Count > 1)
                calloutlist.RemoveRange(0, calloutlist.Count - 1);
        }
```
