### ISSUE TITLE
App on phone? Spyware?LGMapui app NEED HELP DELETING

### ISSUE THREAD

**Issue by Sanasaa** [Mapsui/Mapsui#1758]
I don't understand this site. But it's the only thing I came across that might help me. I was hacked by a really evil ex of mine. And I hate my life he knows everything I do. Everywhere I go the app is called mapsui on my android lg  . I found it it's a horrible spyware it has control of your camera knows your location basically everything but other than that I can't find it better move it do anything is there any way to get rid of this horrible thing I will do anything please I need someone's help I beg you guys if there's any way someone can help me I would appreciate more than you know

**Comment by FrozDark** [comment]
Delete what? Mapsui? Or spyware? Latest one is not related to this repo
If the spyware on the phone -> Factory reset

**Comment by Sanasaa** [comment]
![Screenshot_20221116-142911](https://user-images.githubusercontent.com/118299509/202277020-7c27fafa-4756-48d6-8cde-f37f117b668f.png)

**Comment by Sanasaa** [comment]
Ok sorry this is the app . I googled it and it says it's spyware. And I've done the obvious...factory reset.thanks tho
