### ISSUE TITLE
Rotating map in Sample app on master - branch

### ISSUE THREAD

**Issue by verthal** [Mapsui/Mapsui#1770]
**Describe the bug**
Currently is not possible to rotate the map in the sample app on Android.
If you try to rotate left around 90 degrees, its just jumping around 180 degrees.

**To Reproduce**
1. use master branch
2. Build Android Sample app
3. Try any sample to reproduce the behavior.

**Expected behavior**
rotating map just like in previous versions

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 / Huawei Mate 20 Lite
 - OS: Android 10 / 13

**Additional context**
tested on master branch.

**Comment by pauldendulk** [comment]
Thanks for reporting this. I guess you are rotating with your fingers (could be in code)?

**Comment by pauldendulk** [comment]
I reproduced it and fixed it with this PR https://github.com/Mapsui/Mapsui/pull/1776. Also did some rewriting of the rotation logic, moved parts to pure functions, added some tests for those. This will be fixed in 4.0.0-beta.6.

**Comment by verthal** [comment]
Sorry for that late reply. I was on holiday.
Yes. I tested it with fingers on Android devices
Thank you for that fast bugfix. Its working now :-)
