### ISSUE TITLE
Crash in maui with 4.0.0 beta6

### ISSUE THREAD

**Issue by softlion** [Mapsui/Mapsui#1784]
**Describe the bug**

Crashes when the map is displayed

**To Reproduce**

Run any android maui app having the control in its xaml.  
On android simultor.

**Cause:**
Maui handler not found for SKGLView.
``Microsoft.Maui.Platform.HandlerNotFoundException: Handler not found for view SkiaSharp.Views.Maui.Controls.SKGLView.``

**Comment by softlion** [comment]
Solution:

`UseSkiaSharp(true);`

instead of

`UseSkiaSharp();`

**Comment by pauldendulk** [comment]
Thanks for solving your own issue. 

I updated the getting started to use UseSkiaSharp(true): 
https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/getting-started-maui.md
