### ISSUE TITLE
Navigator.NavigateTo(MRect) doesn't work

### ISSUE THREAD

**Issue by nebeskm** [Mapsui/Mapsui#1789]
**Describe the bug**
I created two Pins and want to show Map with both Pins.
```
public void ZoomToAllPins()
    {
        //pins is List<Pin>
        if ((pins?.Count ?? 0) > 0)
        {
            MRect box = null;
            foreach (var item in pins)
            {
                if (item.Feature != null)
                {
                    if (box == null)
                    {
                        box = item.Feature.Extent;
                    }
                    else
                    {
                        box = box.Join(item.Feature.Extent);
                    }
                }
            }

            if (box != null)
            {
                box = box.Grow(Math.Max(box.Width, box.Height) * 0.1);
                mapView.Navigator.NavigateTo(box);
            }
        }
    }
```

Method `mapView.Navigator.NavigateTo(box);` sets the viewport resolution to "∞" and all properties of viewport extent to "NaN" and empty screen is shown.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/69464636/212074852-0577b057-b34e-4c03-a365-54dc825a489c.png)

**Additional context**
MAUI, .NET 7.0, VS 17.4.2, Mapsui 4.0.0-beta.6

**Comment by pauldendulk** [comment]
I like to reproduce this in a unit test. What is the value of the `box` argument in `mapView.Navigator.NavigateTo(box);`?

**Comment by nebeskm** [comment]
> I like to reproduce this in a unit test. What is the value of the `box` argument in `mapView.Navigator.NavigateTo(box);`?

The value of the `box` is `BL: (X=1592349,1527748636,Y=6252466,346115143)  TR: (X=1634395,1776871067,Y=6472853,802936471)`

But I think the `box` is OK. This method uses `var resolution = ZoomHelper.DetermineResolution(extent.Width, extent.Height, _viewport.Width, _viewport.Height, scaleMethod);` and the problem is that `_viewport.Width, _viewport.Height` is both 0.

**Comment by pauldendulk** [comment]
Could it be that this method is called during startup when the components are not fully initialized? If so, you might want to look at the Map.Home method which has been added with this problem in mind (it is still not a great solution though). Also, we should write a warning to the log if the Width and Height is not initialized.

**Comment by nebeskm** [comment]
You're right, thanks! I added a button on the map that calls the method `ZoomToAllPins()` and it is OK.

**Comment by pauldendulk** [comment]
Note, that the Map.Home method was intended for this purpose. If you assign that method with your own method it should be called when the map component is initialized

https://github.com/Mapsui/Mapsui/blob/63e8c216f9856201feb6f16803d2a211ac5cc9b6/Mapsui/Map.cs#L280
