### ISSUE TITLE
Mapsui.Samples.Blazor AddPinDemo Pins appear on wrong position

### ISSUE THREAD

**Issue by HolgerFreudenreich** [Mapsui/Mapsui#1795]
**Describe the bug**
When you click on the map, the pin does not appear at the click position but with offset.

**To Reproduce**
1. Set solution Mapsui.Samples.Blazor as startup project
2. Choose Category Demo und sample 4 Add Pins
3. Click in the map
4. The pin appears but on wrong position.

**Expected behavior**
The pins appears on click position. In the Mapsui.Samples.Wpf sample this works fine.

**Comment by inforithmics** [comment]
This is fixed with this pull request:
https://github.com/Mapsui/Mapsui/pull/1792

**Comment by HolgerFreudenreich** [comment]
Now it works as expected, thank you very much!
