### ISSUE TITLE
Map showing only background after navigate to different shell tab and then back again (android)

### ISSUE THREAD

**Issue by clough360** [Mapsui/Mapsui#1816]
**Describe the bug**
I have an application with the mapsui control on a shell navigation tab. The first time visiting the tab, the map is displayed correctly, and I can pan / zoom and interact with the map.
When I select a different shell tab, and then go back to the map tab, only the map control background colour is shown, no map layer is shown.
The issue is only on android, not IOS.

The map was working correctly in 4.0.0 beta 5

**To Reproduce**
Create a maui application using Shell, with a screen with shell tabs on.
Add a mapsui map with open layers on it to the first tab.
Add other tabs with other controls on
Run the app, and the above behaviour is observed.

Note, my app has other functionality than this, I'll try and determine the smallest reproducible version.

**Expected behavior**
The map is displayed correctly when navigating back to the tab with the map on it.

**Screenshots**
On initially visiting the tab:
![image](https://user-images.githubusercontent.com/12503052/216630133-325eb9d4-533e-4dab-ba02-45c18a30eb1e.png)

After navigation to another tab
![image](https://user-images.githubusercontent.com/12503052/216629494-3fc8f65e-8a19-4a92-81a2-84fb0917f0f5.png)
(background of mapsui component set to pink)

**Smartphone (please complete the following information):**
 - Device: Android emulator and Android device (eg Samsung galaxy) in both debug and release builds
 - OS: all android versions I have tried, definitely 11
 - Browser: NA
 - Version: 4.0.0 beta 6 and beta 7 (works on beta 5)

**Additional context**
This used to work fine with the previous betas. I am not sure when it broke, I will install an earlier version and see if I can find it went wrong.

I've tried doing a map.Refresh() in OnAppearing, with no success.

**Comment by inforithmics** [comment]
Have you a sample project that displays this behavior?

**Comment by janusw** [comment]
I have seen similar weirdness with MAUI on Android recently. I suspect it's a bug in the Maui framework itself rather than Mapsui. Have you checked with the same MAUI / .NET SDK Version that beta 5 works, but 6 and 7 fail? Or was your beta 5 build done with an earlier SDK version?

**Comment by inforithmics** [comment]
Can you provide the Android Debug Output, when It fails?

**Comment by pauldendulk** [comment]
And attach to logger to see exceptions https://mapsui.com/documentation/logging.html.

Also you could use different colours (lets add a u because you are in the UK) for:
- The background of the tab
- mapControl.BackgroundColor
- mapControl.Map.BackColor

It could be something related to initialization resulting in wrong width/height/boundingbox. Or some unexpected things happening during reinitialization. 

btw, the MAUI MapControl is derived from the ContentView which might have it's own issues. I was considering deriving is from an AbsoluteLayout which would allow users to place MAUI popups at the place where they click the map.

**Comment by janseris** [comment]
This happens for me as well.

**Comment by pauldendulk** [comment]
I assume this is fixed by either `UseGPU = false;` or with the over fetch issue that was fixed in beta 9, If not please open a new issue.

**Comment by pauldendulk** [comment]
@anmelegov If MapControl.UseGPU = false produces an NullReferenceException this is a bug that we should fix please open an issue for that, describing the exact situation.

You mention 'fully reinstantiate the map component'. I don't know your exact situation but in general the idea is that the MapControl itself belongs to the view and should be cleaned up if the view is cleaned up. The state should be maintained in the Map object as part of the ViewModel. The IMapControl should not need to be injected in the ViewModel. If this is what you do but this still causes problem then please describe that in a bug report so we can fix it.
