### ISSUE TITLE
[Uno] Type universe cannot resolve assembly: Uno.UI

### ISSUE THREAD

**Issue by FrozDark** [Mapsui/Mapsui#1821]
Using latest uno platform it can not start with the error "A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: Uno.UI"

I think it's related to new Uno template that uses PCL (cross-platform library)

I just installed MapsUI 4.0.0-beta7 to PCL and placed the map control

**Comment by inforithmics** [comment]
I’ll have to test it against new pcl builds probably. The the dependent uno.ui reference needs to be increased to 4.7….

**Comment by nickrandolph** [comment]
Make sure you're referencing the correct package for your uno application - if you're using Uno.UI (UWP), make sure you're referencing https://www.nuget.org/packages/Mapsui.Uno, if you're using Uno.WinUI (ie WinUI/WinAppSdk) use https://www.nuget.org/packages/Mapsui.Uno.WinUI

**Comment by pauldendulk** [comment]
@FrozDark How is this with beta.8?

**Comment by pauldendulk** [comment]
Closing this. I actually do not know what the status is but a lot has happened in this area so I assume this is fixed. If not please reopen.
