### ISSUE TITLE
Question: How do I adjust Geometries.Raster to new structures?

### ISSUE THREAD

**Issue by feclaudia** [Mapsui/Mapsui#1822]
Hello!

I have problems to transform my routines to the new geometry structures. My old routine to load a png file as background was:

```csharp
private void LoadBackground(string Path)
{
    FileStream fs = new FileStream(Path, FileMode.Open, FileAccess.Read, FileShare.Read);
    var bytes = BruTile.Utilities.ReadFully(fs);
    var image = new MemoryStream(bytes);
    var raster = new Raster(image, MyMapControl.Viewport.Extent);
    var layer = new MemoryLayer() { DataSource = new MemoryProvider(raster), Name = "Background"};
    MyMapControl.Map.Layers.Insert(0, layer);
}
```

I tried to change it to:

```csharp
private void LoadBackground(string Path)
{
    FileStream fs = new FileStream(Path, FileMode.Open, FileAccess.Read, FileShare.Read);
    var bytes = BruTile.Utilities.ReadFully(fs);
    var raster = new MRaster(bytes, MyMapControl.Viewport.Extent);
    var features = new List<RasterFeature>();
    features.Add(new RasterFeature(raster));
    var layer = new MemoryLayer() { Features = features, Name = "Background"};
    MyMapControl.Map.Layers.Insert(0, layer);            
}
```
but it is not working. The image export produces an empty white image.
What is missing? What is the solution?

I'm thankful for any advice!
Thanks, Claudia

**Comment by pauldendulk** [comment]
A RasterFeature now needs a RasterStyle in order to show up. I think we need to make this easier to use.

This is mentioned in our very limited upgrade docs. Perhaps we should make them more visible https://mapsui.com/documentation/v4.0-upgrade-guide.html.

**Comment by feclaudia** [comment]
Ok, I didn't see that. Thank you!
I added a rasterstyle, but my image export is still empty.
```
private void LoadBackground(string Path)
{
    FileStream fs = new FileStream(Path, FileMode.Open, FileAccess.Read, FileShare.Read);
    var bytes = BruTile.Utilities.ReadFully(fs);
    var raster = new MRaster(bytes, MyMapControl.Viewport.Extent);
    var rs = new RasterFeature(raster);
    var stylie = new RasterStyle();
    rs.Styles.Add(stylie);
    var features = new List<RasterFeature>();
    features.Add(rs);
    var layer = new MemoryLayer() { Features = features, Name = "Background"};
    MyMapControl.Map.Layers.Insert(0, layer);         
}
```
My second layer is a list of polygons, which are visible on the exported image.
Maybe there is something else missing?
Thank you, Claudia

**Comment by pauldendulk** [comment]
I added a PR with a sample here https://github.com/Mapsui/Mapsui/pull/1828. 

Your code looks correct though. You say it is missing in the export. What if you view this MapControl in the UI, does it show there? There could be a problem with loading the data, this can take some time that you need to wait for. You could use this extension method for this https://github.com/Mapsui/Mapsui/blob/e897168d2900bf9819b7a2acd4d81e9203f58eea/Mapsui/Extensions/MapControlExtensions.cs#L14.

Also you could attach the logger to see if there are any exceptions https://mapsui.com/documentation/logging.html.

**Comment by feclaudia** [comment]
Thank you so much for your example! I tried it step by step.
The problem in my case is the extent. I have to adjust it. 
It worked with the old Geometries.Raster, but not anymore with the MRaster.
Thanks a lot, Claudia

**Comment by pauldendulk** [comment]
That great!
