### ISSUE TITLE
[4.0.0-beta.7 Regression] viewport changes not always detected

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1830]
**Describe the bug**

I recently tried updating my Xamarin.Forms application from Mapsui.Forms 4.0.0-beta.6 to 4.0.0-beta.7, and found a new problem that did not exist previously ...

I'm using a `MapView` and subscribe to `Viewport.ViewportChanged`, in order to trigger specific actions. But with beta.7 those actions do not seem to be triggered on every viewport change (only sometimes). With beta.6 (and earlier) this worked flawlessly.

I also checked the Mapsui logger, which sometimes shows messages like:

```
Viewport Extent Changed: BL: (X=...,Y=...)  TR: (X=...,Y=...)
```

But, again, these message do not appear on every viewport change, only sometimes.

I see the same behavior both on iOS and Android.

**Expected behavior**

`MapView.Viewport.ViewportChanged` should be triggered on every viewport change.

**Smartphone (please complete the following information):**
 - Device: iPhone 8, Samsung Galaxy S21
 - OS: iOS 16.3, Android 13

**Comment by janusw** [comment]
A quick look through the git history leads me to suspect that PR #1791 (by @inforithmics) might be the culprit. In particular the following commits seem related:
* 5225885c79bb7047f3abeddd8cc197af1ff3a90f
* 4bcf4b6965d326406de2da42c88e549deebdc378
* fbc87f4e0660fadb7db362e00c9d4a94e04a3a5b

**Comment by janusw** [comment]
I verified that Mapsui.Forms version 4.0.0-build.4666 (built via AppVeyor from 956875e15e0e5d2c8453f1ae199f31f8c8af39da) works well. This is the version just before the merge of #1791.

**Comment by janusw** [comment]
Unfortunately the AppVeyor build failed on the merge commit of #1791, so I tried the last commit inside the PR (1011f4cde5ab299feb21420028055c9c9a7e8065), where AppVeyor succeeded and built package version 4.0.0-build.4672. This version indeed shows the same problem as 4.0.0-beta.7, which I take as evidence that #1791 actually caused this problem (as suspected).

**Comment by pauldendulk** [comment]
Thanks for you excellent analysis. I am eager to work on this but I think won't have time the coming days. I would like to rewrite this part of the code to make problems like these likely.

**Comment by inforithmics** [comment]
In the mentioned pull request the viewport, was optimized to only trigger a change if the values of the viewport update were different. So for example when the center is set to the same values, no change is triggered. This means that less viewport events are triggered. I suspect that there is somewhere a Bug that is now uncovered by the less viewport events. So my question is what are you specifically doing on a Viewport change? For narrowing down the area to look for.

**Comment by inforithmics** [comment]
I looked at the Viewport Code and found that the Transform call on the ViewPort does not update the Extent and doesn't call OnViewPort Changes

**Comment by inforithmics** [comment]
I fixed the Transform issue in this pull request.
 
https://github.com/Mapsui/Mapsui/pull/1832

**Comment by pauldendulk** [comment]
Thanks a lot for the fix. 

My plan is to replace all the individual fields (CenterX, CenterY, Resolution ...) with a single ViewportState. This class is already in master but not used yet. This class will will not send events itself. A change of the ViewportState should always result in an Viewport.Changed event. An advantage should be that several fields of the ViewportState could change in one step but should result in one Viewport.Changed event.

**Comment by pauldendulk** [comment]
See https://github.com/Mapsui/Mapsui/issues/1400

**Comment by janusw** [comment]
> In the mentioned pull request the viewport, was optimized to only trigger a change if the values of the viewport update were different. So for example when the center is set to the same values, no change is triggered.

I think this in itself is already a problem. It means that you could zoom out from, say, zoom level 20 to a very small zoom level (whole-world scale in the extreme case) without the application being notified about this extreme viewport change (if the center stays constant).

> This means that less viewport events are triggered.

How was this change motivated in the first place?


> So my question is what are you specifically doing on a Viewport change?

I don't think it makes a lot of difference. I simply want to know whenever the viewport changes (in _any_ way).

In my specific case, I'm loading dynamic content on the map, and I need to know to know the (viewport) area for which to load that content.

**Comment by pauldendulk** [comment]
@janusw I may be wrong, but my interpretation of @inforithmics fix is that the ViewportChanged is now triggered as before. This remark 'This means that less viewport events are triggered' refers to unnecessary events that are triggered by calculations that should be internal to the Viewport. At the end of a calculation a ViewportChanged is sent. 

My plans wrt the ViewportState have a similar purpose. Now, if you zoom in to a location changes can get triggered for CenterX, CenterY and Resolution separately while it is basically one operation.

**Comment by janusw** [comment]
> I'm using a `MapView` and subscribe to `Viewport.ViewportChanged`, in order to trigger specific actions. But with beta.7 those actions do not seem to be triggered on every viewport change (only sometimes). With beta.6 (and earlier) this worked flawlessly.

To be a bit more precise here: Zooming in and out via the buttons seems to work alright and triggers all expected viewport changes. The problem only occurs with finger-pinch zooming, and sometimes also with single-finger panning.

Btw, it also seems to cause problems with the loading of background tiles, so it might also be visible with the samples (haven't tried that)

**Comment by pauldendulk** [comment]
Do you still see the problem in the packages that were built in https://github.com/Mapsui/Mapsui/pull/1832?

**Comment by janusw** [comment]
> Do you still see the problem in the packages that were built in #1832?

I don't. It seems this issue is fixed. 🥳

**Comment by inforithmics** [comment]
@pauldendulk yes your interpretation is right. Before every Setting of a Viewport Property triggered a change. Even if the values stayed the same. So too much events were fired. And maybe because of that the not triggering of changed Event in Transform was hidden by that.
