### ISSUE TITLE
Viewport - Center animation does not respect extent of limits

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1842]
**Describe the bug**
Viewport - Center animation does not respect the limiter

**To Reproduce**
1. Start Mapsui.Samples.Wpf
2. Select "Animations" from the dropdown
3. Select "Animated Viewport - Center"
4. Pan the map to the bottom right until you can not go further
5. Click top lef in the white area, but map will zoom even futher
6. Start panning and the map will snap back to the limited extents.

**Expected behavior**
Limit to extents when animating

**Animated gif**
![mapsui](https://user-images.githubusercontent.com/963462/219051716-d8eccb03-f271-4df6-8b43-3e737e2ab6ee.gif)

**Platform**
Testing on Windows with Mapsui.Samples.Wpf but I expect this to occur everywhere.

**Comment by FrozDark** [comment]
I confirm it occurs on WinUI, Uno as well

**Comment by pauldendulk** [comment]
I am working on the fix. It needs some refactoring though.

**Comment by pauldendulk** [comment]
Just tested and this is fixed. The fix will be in 4.0.0-beta.9
