### ISSUE TITLE
WinUI and Uno Platform types should be in the same namespace

### ISSUE THREAD

**Issue by jeromelaban** [Mapsui/Mapsui#1874]
**Describe the bug**
Many of the types provided for Uno Platform are located in `LiveChartsCore.SkiaSharpView.Uno.WinUI`, whereas their corresponding types for WinAppSDK are located in `LiveChartsCore.SkiaSharpView.WinUI`.

This makes cross-targeting for XAML files difficult to create, as WinUI's XAML does not support conditional XAML for this kind of differences.

**To Reproduce**
```xaml
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"    
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    xmlns:lvc="using:LiveChartsCore.SkiaSharpView.WinUI">

    <Grid>
        <lvc:CartesianChart Height="400" Grid.Column="0" Grid.Row="0" 
                          Series="{Binding BackTofLeftSeries}"
                          TooltipPosition="Hidden"
                          AnimationsSpeed="00:00:00.000"/>
  </Grid>
</Page>
```

**Expected behavior**
The XAML above should build for both WinAppSDK and Uno Platform targets.

**Workaround**
As most of the types cannot be inherited from, the only possible solution is to use conditional exclusions for Uno (starting from Uno 4.8):

```xaml
<Page x:Class="App1.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:App1"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"

      xmlns:unolvc="http://uno.ui#using:LiveChartsCore.SkiaSharpView.Uno.WinUI"
      xmlns:winlvc="using:LiveChartsCore.SkiaSharpView.WinUI"
      mc:Ignorable="d unolvc"

      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <unolvc:CartesianChart Height="400"
                               Grid.Column="0"
                               Grid.Row="0"
                               Series="{Binding BackTofLeftSeries}"
                               TooltipPosition="Hidden"
                               AnimationsSpeed="00:00:00.000" />
        <winlvc:CartesianChart Height="400"
                               Grid.Column="0"
                               Grid.Row="0"
                               Series="{Binding BackTofLeftSeries}"
                               TooltipPosition="Hidden"
                               AnimationsSpeed="00:00:00.000" />
    </Grid>
</Page>
```
and the following exclusion in the corresponding csproj file:
```xml
<ItemGroup>
   <ExcludeXamlNamespaces Include="winlvc" />
</ItemGroup>
```

**Version**
2.0.0-beta.701 for `LiveChartsCore.SkiaSharpView.WinUI` and `LiveChartsCore.SkiaSharpView.Uno.WinUI`.

**Comment by pauldendulk** [comment]
It looks like your bug report was intended for [LiveCharts2](https://github.com/beto-rodriguez/LiveCharts2). Although I guess it also applies to the Mapsui Uno and Uno.WinUI MapControl. 

Since both projects are in the same sln this would result in a compile error. A possible solution is to create a separate sln for Uno. Do you know of another workaround?

**Comment by jeromelaban** [comment]
@pauldendulk Oh wow... my apologies!! I'll re-create the issue.... You can delete it as you please...

**Comment by jeromelaban** [comment]
As for your comment, if mapsui has a similar issue, I can re-create an issue here. I haven't looked at it yet.

**Comment by jeromelaban** [comment]
By the looks of it, the types in the WinUI and Uno.WinUI are in the same namespace:
![image](https://user-images.githubusercontent.com/5839577/224054928-e24a1bd9-d0a0-4308-b11c-1d426bdf6a74.png)

It's all good :)
