### ISSUE TITLE
[WinUI] Support for .NET 7.0

### ISSUE THREAD

**Issue by FrozDark** [Mapsui/Mapsui#1875]
**Describe the bug**
Currently mapsui 4.0.0 beta8 is not including dependencies associated with any of net 7.0 versions
https://www.nuget.org/packages/Mapsui.WinUI#dependencies-body-tab

**Expected behavior**
Support for net7.0-windows10.0.18362

**Comment by FrozDark** [comment]
> What is the consequence of this? Can you not use it at all in a WinUI 7.0 project? Or not all functionality?

I misunderstood something. 
I've managed to install it to net7.0-windows10.0.19041.0 but can not on WinUI with TargetFramework net7.0-windows10.0.18362.0

**Comment by inforithmics** [comment]
the net7.0 target was missing added in this pullrequest.

https://github.com/Mapsui/Mapsui/pull/1879

the target is
net7.0-windows10.0.19041.0

because 10.0.18362 is end of life.

**Comment by inforithmics** [comment]
I saw that at leas Windows App Sdk 1.2.0 (1.2.221109.1) needs to be referenced for .NET 7 Support.

https://github.com/microsoft/WindowsAppSDK/releases/tag/v1.2.0

So I added it to the mentioned pull request

**Comment by pauldendulk** [comment]
Thanks @inforithmics.
