### ISSUE TITLE
Mapsui.UI.Uno.WinUI using Microsoft.iOS 16.2 higher than mine referencing 16.1

### ISSUE THREAD

**Issue by FrozDark** [Mapsui/Mapsui#1876]
Error description
`error CS1705: Package "Mapsui.UI.Uno.WinUI" with a certificate "Mapsui.UI.Uno.WinUI, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" is using "Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" much higher version than "Microsoft.iOS" with a certificate "Microsoft.iOS, Version=16.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065", which referenced to`

I've tried to use conditional syntax in PCL csproj to include separate packages of Mapsui Uno|WinUI but faield with iOS version

Repro
[UnoIssues.zip](https://github.com/Mapsui/Mapsui/files/10943334/UnoIssues.zip)

**Comment by inforithmics** [comment]
I think the iOS Folder is missing in the UnoIssues.zip because the build fails for me with the following message. Could not find a part of the path .....UnoIssues/UnoIssues.Mobile/iOS/Info.plist. .....

**Comment by inforithmics** [comment]
Have you tried the "nightly Mapsui.Uno.Winui"

https://github.com/Mapsui/Mapsui/suites/11509803664/artifacts/595017634

**Comment by FrozDark** [comment]
The issue appeared due to the fact that latest uno-check is installing iOS manifest of version 16.1 instead of 16.2. Previously uno-check had been installing 16.2
Manually installing 16.2 fixes the issue

**Comment by pauldendulk** [comment]
Apparently this was some problem with uno-check. Will probably not apply to the current version.
