### ISSUE TITLE
MyLocation button zeros out the location after panning map

### ISSUE THREAD

**Issue by skipru** [Mapsui/Mapsui#1884]
I am porting my application from Mapsui.Xamarin version 2 to Mapsui.Maui 4.0.0-beta.8 (Windows and Android)
All is going well except for a few issues, the current one being an issue with the MyLocation button.

When I pan the map away from center, then attempt to re-center via the MyLocation button, the location goes to 0,0 and the resolution gets lost. (It might be two different issues.)

I tried a workaround in my location event handler code as follows:
```
void OnLocationChanged(object sender, LocationChangedEventArgs eventArgs)
{
	...
	_myLocationLayer.UpdateMyLocation(new Mapsui.UI.Maui.Position(latitude, longitude), false);
	_myLocationLayer.UpdateMyDirection(bearing, 0, true);
	_myLocationLayer.UpdateMySpeed(speed);

	// Workaround to fix resolution and location when using MyLocation button after panning
	var zeroPosition = SphericalMercator.FromLonLat(0, 0);
	if (MapView.Viewport.CenterX == zeroPosition.x) {
		MapView.Navigator.NavigateTo(_myLocationLayer.MyLocation.ToMapsui(), resolution);
		MapView.Refresh();
	}
	...
}
```

That works, but I have my GPS service loop set to update infrequently (only a few times per minute) so there is a long delay where the map sits at 0,0 in the the Atlantic Ocean before being re-centered to the proper location.

Maybe I am not using the MyLocationLayer properly? I also don't see Map.Home doing anything, so it may be an indication I am not setting things up correctly when I set up the map. Any hints or suggestions are welcome. Apologies if this is the wrong place to report.

By the way, I wish to congratulate you on a great product. It is apparent you have put a lot of work into Mapsui. It is very much appreciated!

--
Skip
Portland, Oregon.

**Comment by pauldendulk** [comment]
Is the MyLocation symbol (blue dot with white rim around it) also at the 0, 0 position, or at the correct position?

**Comment by skipru** [comment]
It is actually the "in motion" icon that shows, but yet, it is in the right location. I do not see any icon at 0, 0. 

I can try to recreate the error with the latest master and a simple test case if that would help.

**Comment by pauldendulk** [comment]
> I can try to recreate the error with the latest master and a simple test case if that would help.

Yes, that would help, thank you.

**Comment by skipru** [comment]
Ok done and I will attach here. It seems to to be better on master, but still needs a location update before the map centers away from 0,0.
[SkipruSample.zip](https://github.com/Mapsui/Mapsui/files/10993419/SkipruSample.zip)

**Comment by skipru** [comment]
Update: I found a workaround. There were two location layers (I didn't realize one was already created in MapView), but I still need the location layer to be last for the center images to appear. I changed this one line, and now everything works as expected:

```
            //_myLocationLayer = new Mapsui.UI.Objects.MyLocationLayer(mapView) {Enabled = true};
            _myLocationLayer = mapView.MyLocationLayer;
```

**Comment by pauldendulk** [comment]
Thanks for the sample, that helps.

I now understand there is confusion about how the MyLocation layer should be used. I am thinking about a way to make this more clear for users. Currently the MapView supports some common scenarios. It does this by adding this to the MapView itself. I am thinking about a solution where it would be possible to create MapView with the same functionality in a single line (I was thinking about a builder pattern) but the functionality would be more explicit. So the MyLocation layer would be like any other layer, so you could see it in the list. But it will take some time before I will have time for this. I see this as an enhancement.

It is not yet clear to me if there is an actual bug in the current implementation. You now write some of your own code around the MyLocation layer. What happens if you just use the MyLocation layer the way it was intended in the MapView. It should just work off the shelf. Does it? Or did I introduce a bug?

**Comment by skipru** [comment]
I think there is still a problem with Z-order of the MyLocation symbol at the center. Centering itself is working perfectly, but I seem to need to move the MyLocation layer to the end of the layer list. I changed my sample code as below. Note the "Layers.Add" of the MyLocationLayer. If I understand correctly it is moving the layer to the end of the list. If I comment out that line, the MyLocation symbol does not appear. I like your enhancement idea of using something like a builder syntax for the MapView to make things more explicit. I hope to have time to do some more testing in a few days, but with this small workaround, things are looking quite good.

``
	public partial class MainPage : ContentPage
	{
		MapView mapView;
		double startingResolution = 10;
		CancellationTokenSource _cancel = new CancellationTokenSource();

		public MainPage()
		{
			InitializeComponent();

			mapView = MyMap;
			mapView.Map = new Mapsui.Map();
			mapView.Map.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());

            // MyLocation layer needs to be moved to the end (top) of the list of layers
            mapView.Map.Layers.Add(mapView.MyLocationLayer);

            mapView.MyLocationEnabled = true;
			mapView.MyLocationFollow = true;

			var coords = SphericalMercator.FromLonLat(SkipsLocationTest._mockLocationLon, SkipsLocationTest._mockLocationLat);
			MPoint startingPoint = new MPoint(coords.x, coords.y);

			// Map.Home seems to be ignored...
			mapView.Map.Home = (INavigator n) => { n.NavigateTo(startingPoint, startingResolution); };

			// starting resolution never gets set unless I do this...
			mapView.Map.Navigator.NavigateTo(startingPoint, startingResolution);

			SkipsLocationTest.LocationChanged += OnLocationChanged;
			SkipsLocationTest.StartLocationService(_cancel);
		}

		private void OnLocationChanged(object sender, LocationChangedEventArgs e)
		{
			var l = e.Location;
			Mapsui.UI.Maui.Position currentLoc = new Mapsui.UI.Maui.Position(l.Latitude, l.Longitude);
			double currentBearing = l.Course.Value;
			double currentSpeed = l.Speed.Value;

            mapView.MyLocationLayer.UpdateMyLocation(currentLoc, false);
            mapView.MyLocationLayer.UpdateMyDirection(currentBearing, 0, true);
            mapView.MyLocationLayer.UpdateMySpeed(currentSpeed);
        }
    }
}
```

**Comment by pauldendulk** [comment]
@skipru Thanks for reporting back. So, this is no bug. A MapBuilder might be handy but it adding this will go hand in hand with some refactoring so this is for 5.0.0-beta.1.
