### ISSUE TITLE
Map tiles are not automatically displayed when tile server access is restored

### ISSUE THREAD

**Issue by baldricks-turnip** [Mapsui/Mapsui#1891]
**Describe the bug**
Map tiles are not automatically displayed when tile server access is restored. Panning or zooming is required to refresh the display.

**To Reproduce**
Display a map on an Android device with access to map tile server (OSM).
Disable network (I disabled WiFi as the device I was using has no cellular data comms).
Pan the map to where there are no maps in the cache and so none are displayed, or blurry maps are displayed.
Enable the WiFi link.
The maps remain as they were - blurry or missing.

**Expected behavior**
I'd expect the tiles to be downloaded and displayed once the network has been restored.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11

**Additional context**
Mapsui.Maui 4.0.0-beta.8 package

**Comment by baldricks-turnip** [comment]
The implementation doesn't need to know about the link. Tiles may also fail to download because of a temporary server outage. For any failed tiles that are still visible on the display, there could simply be a periodic download retry.
This is how my existing WPF map tile renderer implementation works. In fact we go one stage further and will even redraw tiles that are a certain age (configurable) in the case that a tile service updates data on a regular basis.

**Comment by pauldendulk** [comment]
I can imagine that we might build something like that at some point but if we do we have to make sure it it a simple solution, I would like to avoid adding a timer. Given the number of things that have a higher priority we won't have time for this soon, so I close this issue for now, Also, it is possible to user to add a mechanism for this in their own code.
