### ISSUE TITLE
.NET MAUI polygons and center to location sample do nothing

### ISSUE THREAD

**Issue by janseris** [Mapsui/Mapsui#1892]
Reproduce:
1. in hamburger menu ("Shell"), open "MapsUI page" menu item.
2. try click buttons "Add polygons" and "Center to location".

They do nothing although code is pasted from the samples in this repository.

The code is in:
`MapsUIPage`
`MapsUIPageViewModel`

[AndroidBluetoothBeaconTest.zip](https://github.com/Mapsui/Mapsui/files/10997006/AndroidBluetoothBeaconTest.zip)

The widgets sample triggered by the "Add widgets" button works well.

Wrapping the code in the following did not help:
```
MainThread.BeginInvokeOnMainThread(() =>
{
    // Code to run on the main thread
}); 
```

Project:
[AndroidBluetoothBeaconTest.zip](https://github.com/Mapsui/Mapsui/files/10997018/AndroidBluetoothBeaconTest.zip)

Samples source:
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Navigation/CenterOnLocationSample.cs
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Geometries/PolygonSample.cs
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/Widgets/WidgetSample.cs

**Comment by pauldendulk** [comment]
If you add a fat red outline it is also possible to see the polygon if you are zoomed out.
```csharp
public static ILayer CreateLayer()
{
    return new Layer("Polygons")
    {
        DataSource = new MemoryProvider(CreatePolygon().ToFeatures()),
        Style = new VectorStyle
        {
            Fill = new Brush(Color.Red),
            Outline = { Color = Color.Red, Width = 10 }
        }
    };
}
```

The AddPolygon method uses the Home method which is intended for navigating on app startup. In this case you need to use the navigator like this:

```csharp
private void AddPolygons(MapControl mapControl)
{
    var map = mapControl.Map;
    var polygonLayer = CreateLayer();
    map.Layers.Add(polygonLayer);
    mapControl.Navigator.NavigateTo(polygonLayer.Extent!.Centroid, map.Resolutions[15]);

    mapControl.Refresh();
    mapControl.RefreshGraphics();
}
```

The same problem with CenterOnLocation. This is the fix:
```csharp
private void CenterToLocation(MapControl mapControl)
{
    var map = mapControl.Map;
    // Get the lon lat coordinates from somewhere (Mapsui can not help you there)
    var centerOfLondonOntario = new MPoint(-81.2497, 42.9837);
    // OSM uses spherical mercator coordinates. So transform the lon lat coordinates to spherical mercator
    var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfLondonOntario.X, centerOfLondonOntario.Y).ToMPoint();
    // Set the center of the viewport to the coordinate. The UI will refresh automatically
    // Additionally you might want to set the resolution, this could depend on your specific purpose
    mapControl.Navigator.NavigateTo(sphericalMercatorCoordinate, map.Resolutions[9]);

    mapControl.Refresh();
    mapControl.RefreshGraphics();
}
```

btw, with beta.9 you do not need the MapControl for this scenario. Also, you do not need to call Refresh. It is done by the Navigator.
