### ISSUE TITLE
MAUI with multiple pages only work first time

### ISSUE THREAD

**Issue by TFreudi1** [Mapsui/Mapsui#1896]
I have created a shell based MAUI project with to pages. The Map pages shows the map only the first time. If you go back to the other page and than choose the map-page again MapSui dont show a map. 

**To Reproduce**
Take my sample project
Choose Map Page from Hamburger menu
Chosse Home Page from Hamburger menu
Choose Map Page from Hamburger menu

**Expected behavior**
Map should be visible

This happens on all platforms
[MauiAppMapSui.zip](https://github.com/Mapsui/Mapsui/files/11019916/MauiAppMapSui.zip)

**Comment by pauldendulk** [comment]
Thanks for the sample! I understand this is an important issue but I am now focused on beta 9 which will contain changes that may affect this issue.

**Comment by charlenni** [comment]
Did you try to call ````MapControl.StopUpdates()```` before leaving the pages with the MapControl and call ````MapControl.StartUpdates()```` when coming back? Does this solve the problem?

**Comment by TFreudi1** [comment]
Yes, the sample project is very simple, see link below. On the map-page the code is now:
`public partial class MapPage : ContentPage
{
    MapControl mapControl = new MapControl();
    public MapPage()
    {
		InitializeComponent();
        mapControl.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
        Content = mapControl;
    }

    protected override void OnAppearing()
    {
        base.OnAppearing();
        mapControl.StartUpdates();
    }

    protected override void OnDisappearing()
    {
        mapControl.StopUpdates();
        base.OnDisappearing();
    }
}`

First time page open map correct, if you go back to home-page and than to map-page, map-page is white and shows nothing.
![error](https://user-images.githubusercontent.com/4739177/226624654-d16866d9-cb99-4ecb-9f66-f29e7b2ec756.png)

**Comment by janseris** [comment]
I reported this as well and my issue somehow disappeared.
Basically navigating out of the page and visiting again only loads map background and nothing else.

**Comment by inforithmics** [comment]
Seems to be some Bug with SKGlView

Workaround:
```
public static MauiApp CreateMauiApp()
{		
       Mapsui.UI.Maui.MapControl.UseGPU = false;
```

**Comment by inforithmics** [comment]
An alternative approach would be to always create the Mapsui Control on Appearing.

```
  protected override void OnAppearing()
    {
        base.OnAppearing();

        MapControl mapControl = new MapControl();
        mapControl.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
        Content = mapControl;
    }
```

**Comment by pauldendulk** [comment]
- I can't think of a downside except performance with `UseGPU = false`;
- In the upcoming beta.9 it will be possible to reuse the Map object, which will contain the Layers and Viewport. So, you could destroy and recreated the MapControl, and then reassign the Map to the new MapControl.

**Comment by TFreudi1** [comment]
Good job pauldendulk, I will use the GPU option meanwhile.

**Comment by janseris** [comment]
> * I can't think of a downside except performance with `UseGPU = false`;
> 
>     * In the upcoming beta.9 it will be possible to reuse the Map object, which will contain the Layers and Viewport. So, you could destroy and recreated the MapControl, and then reassign the Map to the new MapControl.

Will the bug be fixed in beta 9 or will just the Map object be possible to reuse (adds additional complexity)?
Thanks

**Comment by pauldendulk** [comment]
The bug itself will not be fixed. The problem may be in the skia SkGLView that we are using.

**Comment by TFreudi1** [comment]
Well OK, not easy :-)  but because my problem is solved through useGPU=false, and because in my use case the performance degradation is not a problem, i closed it. Also there a 2 more open issues with the same problem.

**Comment by charlenni** [comment]
We had this in the beginning of Xamarin.Forms too.

**Comment by janseris** [comment]
> We had this in the beginning of Xamarin.Forms too.

Sounds like you don't have it anymore, how did you get rid of the issue?

**Comment by TFreudi1** [comment]
No, no it is still there but when I disable GPU , for me it works like expected. See my Screenshots above, in the last one I see know the map in it's last state.

**Comment by pauldendulk** [comment]
With this PR MAUI Android now does not use GPU anymore by default. 
https://github.com/Mapsui/Mapsui/pull/1934

**Comment by janseris** [comment]
@pauldendulk  Thanks and is there any future for using GPU - what needs to be done maybe by other control providers or MAUI itself etc?

**Comment by pauldendulk** [comment]
We need to investigate the problem by trying to reproduce it in the most simple way. It may be a problem in SkiaSharp. If it is we should submit an issue there with a minimum reproducible sample. So, what I would do:

1. Take the sample provided by @TFreudi1 and run it to check if it can be reproduced.
1. Replace Mapsui in the sample with a local component based and the MapControl which uses SkiaSharp like the MapControl does.
1. Try to reproduce the problem in that sample, if it does not add more of the Mapsui code and test again.
1. Keep adding things until it reproduces. Those maybe sometimes bigger chunks of Mapsui code.
1. If you need to add all of the Mapsui code. The easiest way is to clone Mapsui and built the sample as a project in the Mapsui.sln (perhaps this should be step 2, so you are sure it can be reproduced in code).
1. If it is reproduced. Try to remove as much of the added code to still reproduce it.

Doing this you may be able to prove a bug in SkiaSharp or find a flaw in the way we use SkiaSharp. If it is a bug in SkiaSharp we may also find a workaround.

**Comment by janseris** [comment]
> We need to investigate the problem by trying to reproduce it in the most simple way. It may be a problem in SkiaSharp. If it is we should submit an issue there with a minimum reproducible sample. So, what I would do:
> 
>     1. Take the sample provided by @TFreudi1 and run it to check if it can be reproduced.
> 
>     2. Replace Mapsui in the sample with a local component based and the MapControl which uses SkiaSharp like the MapControl does.
> 
>     3. Try to reproduce the problem in that sample, if it does not add more of the Mapsui code and test again.
> 
>     4. Keep adding things until it reproduces. Those maybe sometimes bigger chunks of Mapsui code.
> 
>     5. If you need to add all of the Mapsui code. The easiest way is to clone Mapsui and built the sample as a project in the Mapsui.sln (perhaps this should be step 2, so you are sure it can be reproduced in code).
> 
>     6. If it is reproduced. Try to remove as much of the added code to still reproduce it.
> 
> 
> Doing this you may be able to prove a bug in SkiaSharp or find a flaw in the way we use SkiaSharp. If it is a bug in SkiaSharp we may also find a workaround.

It can be repdpruced. I have created a minimal example as well in an other issue.

**Comment by anmelegov** [comment]
It could be a bug in a MAUI.. Just found similar issues with bundled image control in .NET 7

- https://github.com/dotnet/maui/issues/14471
- https://github.com/dotnet/maui/issues/14205

**Comment by janusw** [comment]
I think it is caused by this SkiaSharp issue: https://github.com/mono/SkiaSharp/issues/2550

**Comment by charlenni** [comment]
@janusw Do you think it is possible to try this with @inforithmics branch using SkiaSharp 3.0? It seems, that this version made much progress in using GPU backends with different platforms. Perhaps that solve the problem?

**Comment by janusw** [comment]
> @janusw Do you think it is possible to try this with @inforithmics branch using SkiaSharp 3.0?

Well, in my setup it is not so easy to test anything based on Mapsui master or 5.0.0-beta.1 right now, since I'm currently bound to Mapsui 4.x, and there are several breaking changes on master.

But there is a reproducer above that someone could try with the branch you mention. Or maybe it's easier to try the reproducer from the SkiaSharp issue directly with SkiaSharp 3.0?

**Comment by charlenni** [comment]
Ok, then lets make a short summary:
- the problem still exists even with 2.88.8 (?) and the last MAUI we use
- it isn't a Mapsui, but a SkiaSharp problem
- it is only with Android and with the TabBar
- there are two workarounds
  1. use the CPU backend, which Mapsui does by default in the moment
  2. set IsVisible of MapControl first to false and then to true when the view reappears on the screen

It would be nice, if some one could create a test app (could be a plain SkiaSharp SKGLView but with SkiaSharp 3.0 and a TabBar) to check, if this problem still exists.
