### ISSUE TITLE
Dragging a polygon's vertex

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1902]
### Discussed in https://github.com/Mapsui/Mapsui/discussions/1901

<div type='discussions-op-text'>

<sup>Originally posted by **DmitryEvstakhov** March 24, 2023</sup>
Hi guys!
I use example Mapsui.Examples.Mpf.Editing. When I dragging point from a polygon I have some problems:
1. Dragging vertex is not smooth. I mean that the vertex from the VertexOnlyLayer drags smoothly, but the rendered geometry of polygon is not smooth (jerky).
2.  Sometimes the geometry doesn't redraw at all. You have moved one vertex of polygon, but the polygon rendered geometry remains the same. But when I move the map the geometry will be rendered correctly.

Initial geometry:
![01](https://user-images.githubusercontent.com/59865880/227527846-9e796f0c-30d2-4e6a-b112-93ef6761f61d.png)

When I dragged vertex:
![02](https://user-images.githubusercontent.com/59865880/227528006-1d097422-de3c-4872-a56e-c493a19ab00e.png)

When I move the map:
![03](https://user-images.githubusercontent.com/59865880/227528324-9f4a9265-4411-46d2-b238-ef1c21b97e12.png)

Why is this happening and how to solve this problem?
</div>

**Comment by pauldendulk** [comment]
Video by @DmitryEvstakhov. Thanks.
https://user-images.githubusercontent.com/59865880/227552763-b25cfccf-2b4a-477d-b6be-eb210a2b56f4.mp4

**Comment by pauldendulk** [comment]
I can reproduce it with todays master. It seems the vertex in the geometry that is being dragged around jumps back to a previous state while panning. Sometimes to a quite recent position but later it can go back to an older position. Somehow this older state is preserved. It is not just slow. 

When you stop dragging the vertex stays at an older position.

When you drag the map it immediately goes to the correct position.

**Comment by pauldendulk** [comment]
When I remove the renderCache parameter of the PolygonRenderer.Draw in the VectorStyleRenderer.Draw method at line 42 the problem is solved. So, something with caching.

```csharp
case Polygon polygon:
    PolygonRenderer.Draw(canvas, viewport, vectorStyle, feature, polygon, opacity, renderCache);
    break;
```

**Comment by inforithmics** [comment]
From the described behavior, I think the HashCode does not Change when a Point is changed, causing the Hash to return the old rendered Polygon.

**Comment by inforithmics** [comment]
pull request that fixes this.

https://github.com/Mapsui/Mapsui/pull/1908
