### ISSUE TITLE
Map movement under elements on top

### ISSUE THREAD

**Issue by TiDaGo** [Mapsui/Mapsui#1914]
Map movement under elements on top
```xml
    <AbsoluteLayout AbsoluteLayout.LayoutBounds="0,0,1,1">
    <StackLayout AbsoluteLayout.LayoutBounds="0,0,1,1"
             AbsoluteLayout.LayoutFlags="All">
      <mapsui:MapView x:Name="mapView"
                 VerticalOptions="FillAndExpand"
                 HorizontalOptions="Fill"
                 IsZoomButtonVisible="False"
                 BackgroundColor="{StaticResource PassiveBackground}" />
    </StackLayout>
    <yummy:PancakeView BackgroundColor="{StaticResource Primary}"
                       CornerRadius="10,10,0,0"
                       IsClippedToBounds="true"
                       HorizontalOptions="FillAndExpand"
                       HeightRequest="60"
                       x:Name="bottomToolTip"
                       AbsoluteLayout.LayoutBounds="0,1,1,0.1"
                       AbsoluteLayout.LayoutFlags="All">
      <FlexLayout Direction="Row" AlignItems="Center" JustifyContent="SpaceEvenly">
        <cv:SvgImage x:Name="fltTypes" AssemblyName="Blog4Van" Source="Resources.icons.flt_place_type.svg" EnableTouchEvents="True" WidthRequest="52" Touch="FltTypes_Clicked"/>
        <cv:SvgImage x:Name="fltServices" AssemblyName="Blog4Van" Source="Resources.icons.flt_place_service.svg" HeightRequest="60" EnableTouchEvents="True" Touch="FltServices_Touch"/>
      </FlexLayout>
    </yummy:PancakeView>
  </AbsoluteLayout>
```

it's working on red zone, but all right in green zones (cv:SvgImage becouse have EnableTouchEvents="True")

![image](https://user-images.githubusercontent.com/27810072/228436658-870e6c3a-9281-4420-a7d6-955218ffd80f.png)

and when i touch in red zone - application invoked mapView.TouchAction action

**Smartphone (please complete the following information):**
 - Im not have IOS, but working on all androids

**Comment by charlenni** [comment]
I would say, that this is normal behavior. The red area doesn't consume the events, so Android give them to the next view in the list at this place and that is the MapView.

**Comment by TiDaGo** [comment]
> I would say, that this is normal behavior. The red area doesn't consume the events, so Android give them to the next view in the list at this place and that is the MapView.

Yup, i know, but it's not ok )

**Comment by charlenni** [comment]
Then you should mention this to the developer team of Android.

**Comment by TiDaGo** [comment]
> Then you should mention this to the developer team of Android.

You understad - the map is moving. i can fix it n my project, not on GIT )
detect upper layount and if not map - blocked map events

**Comment by pauldendulk** [comment]
If the map is moving that is because the touch events has reached the MapControl/MapView. This is how the UI framework works. In some scenarios this is what the app developer wants. If you do not want this you have to configure the element on top so that it does not pass the touch event to what is below. In code you could do that by adding e.Handled = true in the touch event. In XAML you probably need to configure some property, not sure which.
