### ISSUE TITLE
KeepWithinExtentSample seems not to work.

### ISSUE THREAD

**Issue by inforithmics** [Mapsui/Mapsui#1938]
**Mapsui Version**
Current Master

**Mapsui Platform**
Xamarin.Forms

**Device**
Windows (WPF)

**Describe the bug**
The Keep within Extent Sample should keep the zoom and panning inside the extent. But with zoom and panning I can move outside the extent.

**To Reproduce**
1.  Get Master
2. Open Mapsui.Forms.slnf
3. Navigation => Keep Within Extent
4. I can zoom and pan outside of Madagaskar.

**Expected behavior**
Zoom and Pan should be within Madagaskar.

**Screenshots**
Initial zoom is within madagaskar.
![image](https://user-images.githubusercontent.com/2290863/229554726-1cad3c44-32dc-4749-a1d7-ba3899bba7ee.png)

Afterwards I can move outside of madagascar
![image](https://user-images.githubusercontent.com/2290863/229554993-fc7d4837-7132-40cc-8b54-7d90cbd3fe00.png)

**Additional context**

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/1942
