### ISSUE TITLE
on maui how to attach offline map to ui?

### ISSUE THREAD

**Issue by halukmy** [Mapsui/Mapsui#1943]
I download some map title like map.osm and on offline navigation how to show on layer?

Thanks

**Comment by pauldendulk** [comment]
You need to have an IProvider implementation for the specific format you are interested in. In the Mapsui repository there are provider from MBTiles and tiles on the file system, this is probably not what you need. If there is a C# library to read your format it may not be hard to implement an IProvider. Mapsui also support NTS. If there is a component to convert your format to NTS geometries that may be a good option.

**Comment by pauldendulk** [comment]
All I have used so far for offline support is to use an mbtiles file. So, no direct pbf support or anything streaming. You would need to write something yourself for that. You could look at [osmsharp](https://github.com/OsmSharp/core/tree/develop/src/OsmSharp) to read a pdf and then convert it to NTS.

**Comment by halukmy** [comment]
oh, is there any sample for mbtiles ?

**Comment by pauldendulk** [comment]
Yes, in the file MbTilesSample.cs. If you start one of the sample apps you can see it as '1 MbTiles' in the category 'Data Formats'.

**Comment by halukmy** [comment]
dear @pauldendulk still searching, but some rookie on that, can you share a very simple MbTilesSample project?

**Comment by pauldendulk** [comment]
The Mapsui repository contains sample projects for the various platforms. All those sample platforms contain several categories with each several specific samples. One of these is a simple MBTiles sample, it is called '1 MbTiles' and is in the 'Data Formats' category. This is it: https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/DataFormats/MbTilesSample.cs

So, you need to clone the Mapsui repository and build the Mapsui.sln, or one of the slnf's, and then run one of the samples, selected the 'Data Formats' category, and click on '1 MbTiles'.

**Comment by halukmy** [comment]
Thanks so much mr Paul, i find it from samples 1mbtiles, and i download Turkey mbtiles from maptiler data, uploaded with visual studio, and changed buli daction embedded resource and copy always , i just see blank map, where should be problem at
