### ISSUE TITLE
Beta 10 Navigator.FlyTo zoom reverts back right after pan animation finished

### ISSUE THREAD

**Issue by FrozDark** [Mapsui/Mapsui#1952]
**Mapsui Version**
Started from beta9

**Mapsui Platform**
Tested on Uno only

**Device**
Android, Windows

**Describe the bug**
Using Navigator.FlyTo with zoom the zoom reverts back right after pan animation finished

Video:
https://user-images.githubusercontent.com/6670150/231395086-1d06c4b6-9df9-4a1f-b8a1-c7b61557cffd.mp4

**To Reproduce**
1. Run repro on any platform
2. Click on "Center on point"
[FlyToMapsuiIssues.zip](https://github.com/Mapsui/Mapsui/files/11209135/FlyToMapsuiIssues.zip)

**Expected behavior**
Normal zoom

**Comment by inforithmics** [comment]
I had a look at it and found following:

FlyTo Animation has following code:

```
public static List<AnimationEntry<Viewport>> Create(Viewport viewport, MPoint center, double maxResolution, long duration)
    {
        var animations = new List<AnimationEntry<Viewport>>();
        AnimationEntry<Viewport> entry;

        var viewportCenter = new MPoint(viewport.CenterX, viewport.CenterY);

        if (!center.Equals(viewportCenter))
        {
            entry = new AnimationEntry<Viewport>(
                start: viewportCenter,
                end: center,
                animationStart: 0,
                animationEnd: 1,
                easing: Easing.SinInOut,
                tick: CenterTick,
                final: CenterFinal
            );
            animations.Add(entry);
        }

        entry = new AnimationEntry<Viewport>(
            start: viewport.Resolution,
            end: Math.Min(maxResolution, viewport.Resolution * 2),
            animationStart: 0,
            animationEnd: 0.5,
            easing: Easing.SinIn,
            tick: ResolutionTick,
            final: ResolutionFinal
        );
        animations.Add(entry);

        entry = new AnimationEntry<Viewport>(
            start: Math.Min(maxResolution, viewport.Resolution * 2),
            end: viewport.Resolution,
            animationStart: 0.5,
            animationEnd: 1,
            easing: Easing.SinIn,
            tick: ResolutionTick,
            final: ResolutionFinal
        );
        animations.Add(entry);

        Animation.Start(animations, duration);
        return animations;
    }
```

It seems for me that the second and third animation entry are the same, removing the third item fixes the problem.

public static List<AnimationEntry<Viewport>> Create(Viewport viewport, MPoint center, double maxResolution, long duration)
    {
        var animations = new List<AnimationEntry<Viewport>>();
        AnimationEntry<Viewport> entry;

        var viewportCenter = new MPoint(viewport.CenterX, viewport.CenterY);

        if (!center.Equals(viewportCenter))
        {
            entry = new AnimationEntry<Viewport>(
                start: viewportCenter,
                end: center,
                animationStart: 0,
                animationEnd: 1,
                easing: Easing.SinInOut,
                tick: CenterTick,
                final: CenterFinal
            );
            animations.Add(entry);
        }

        entry = new AnimationEntry<Viewport>(
            start: viewport.Resolution,
            end: Math.Min(maxResolution, viewport.Resolution * 2),
            animationStart: 0,
            animationEnd: 0.5,
            easing: Easing.SinIn,
            tick: ResolutionTick,
            final: ResolutionFinal
        );
        animations.Add(entry);

        Animation.Start(animations, duration);
        return animations;
    }

**Comment by inforithmics** [comment]
I had a look at it

```
public static List<AnimationEntry<Viewport>> Create(Viewport viewport, MPoint center, double maxResolution, long duration)
    {
        var animations = new List<AnimationEntry<Viewport>>();
        AnimationEntry<Viewport> entry;

        var viewportCenter = new MPoint(viewport.CenterX, viewport.CenterY);

        if (!center.Equals(viewportCenter))
        {
            entry = new AnimationEntry<Viewport>(
                start: viewportCenter,
                end: center,
                animationStart: 0,
                animationEnd: 1,
                easing: Easing.SinInOut,
                tick: CenterTick,
                final: CenterFinal
            );
            animations.Add(entry);
        }

        entry = new AnimationEntry<Viewport>(
            start: viewport.Resolution,
            end: Math.Min(maxResolution, viewport.Resolution * 2),
            animationStart: 0,
            animationEnd: 0.5,
            easing: Easing.SinIn,
            tick: ResolutionTick,
            final: ResolutionFinal
        );
        animations.Add(entry);

        entry = new AnimationEntry<Viewport>(
            start: Math.Min(maxResolution, viewport.Resolution * 2),
            end: viewport.Resolution,
            animationStart: 0.5,
            animationEnd: 1,
            easing: Easing.SinIn,
            tick: ResolutionTick,
            final: ResolutionFinal
        );
        animations.Add(entry);

        Animation.Start(animations, duration);
        return animations;
    }
```

As far as i understand the code it says in the fly to.
zoom out and then zoom into the current resolution (Seems for me the definition of flyto). 

So the code says zoom out move to the position and then zoom in. Because the maxresultion is smaller it makes a zoom into and then a zoom out.

**Comment by inforithmics** [comment]
So for the desired behavior to work a end resolution parameter needs to be added. because the maxresolution parameter is for the flyout only.

**Comment by inforithmics** [comment]
I think you should use CenterOnAndZoomTo instead to flyto

**Comment by FrozDark** [comment]
@pauldendulk @inforithmics thanks for clarification. Didn't know what is that for
