### ISSUE TITLE
Cannot build Avalonia samples due to incorrect geo data file names

### ISSUE THREAD

**Issue by iq2luc** [Mapsui/Mapsui#1957]
**Mapsui Version**
Branch: master

**Mapsui Platform**
Platform: Avalonia

**Device**
Linux 6.2.10 x86_64

**Describe the bug**
Cannot build Avalonia samples (Mapsui.Samples.Common project) because of errors caused by incorrect file names: `cities.DBF` instead of `cities.dbf`, `cities.SHP` instead of `cities.shp` and `cities.SHX` instead of `cities.shx`.

```
CSC : error CS1566: Error reading resource 'Mapsui.Samples.Common.GeoData.World.cities.dbf' -- 'Could not find file './Samples/Mapsui.Samples.Common/GeoData/World/cities.dbf'.'
CSC : error CS1566: Error reading resource 'Mapsui.Samples.Common.GeoData.World.cities.shp' -- 'Could not find file './Samples/Mapsui.Samples.Common/GeoData/World/cities.shp'.'
CSC : error CS1566: Error reading resource 'Mapsui.Samples.Common.GeoData.World.cities.shx' -- 'Could not find file './Samples/Mapsui.Samples.Common/GeoData/World/cities.shx'.'
```

**To Reproduce**
1. Open filtered mapsui solution (Mapsui.Avalonia.slnf)
2. Remove remaining non-Avalonia related projects
3. Build Mapsui.Samples.Avalonia project
4. See the above mentioned errors

**Expected behavior**
Ideally the project would build and run without any issues.

**Proposed solution**
Renaming the three mentioned files accordingly (lowercase extensions instead of uppercase extensions) allows the project to be build and ran without any other issues.

**Comment by pauldendulk** [comment]
ah, our first Linux path case sensitivity issue. I guess we need to add a Linux build action on some point. I will fix this by making the file extensions lower case. Thanks for the report.

**Comment by iq2luc** [comment]
Thanks @pauldendulk for your swift reply and proposed resolution.

Indeed it was just a very small issue, other than that everything works great on Linux (at least all Avalonia based samples I tested).

Being my first contact with Mapsui and seeing there was no Linux support officially mentioned, I have to confess my initial expectations were set at "probably I'll have to hack here and there to make it work". The actual state of affairs put a nice smile on my face, so I'll take this opportunity to express a big "thank you!" to all the people involved into this great project.

**Comment by pauldendulk** [comment]
> Being my first contact with Mapsui and seeing there was no Linux support officially mentioned, I have to confess my initial expectations were set at "probably I'll have to hack here and there to make it work". The actual state of affairs put a nice smile on my face, so I'll take this opportunity to express a big "thank you!" to all the people involved into this great project.

Thanks, good to hear that 😊. We will not always react this quickly, and there is always some part that is work in progress but we are improving step by step.

**Comment by inforithmics** [comment]
pull request for linux github action with basic unit tests.

https://github.com/Mapsui/Mapsui/pull/1964

@iq2luc The avalonia Samples projct targets net6.0-windows10.0.19041.0 so I think you have changed it to run it on linux. Could you provide me the changes so we could improve the Mapsui.Samples.Avalonia so that it runs out of the box on linux. Or does it work without changes?

**Comment by iq2luc** [comment]
Hello @inforithmics,

not much really, besides renaming the the geo data files as @pauldendulk already did, only a very small patch was needed (see [mapsui-linux-build.zip](https://github.com/Mapsui/Mapsui/files/11260319/mapsui-linux-build.zip), for the patch, the warnings and a screenshot).

Thank you all so much for caring about Linux builds.

**Comment by inforithmics** [comment]
Thanks as I see it it only needs to target net6.0 instead of net6.0-windows10.0.19041.0 and it works crossplatform. I didn't know that it is that easy.

**Comment by inforithmics** [comment]
Updated:
https://github.com/Mapsui/Mapsui/pull/1964

So that it runs out of the box on windows and linux

**Comment by iq2luc** [comment]
> [...] I didn't know that it is that easy.

Well, that was the source of my happiness when I mentioned it a few posts above.

By the way, I also tried to target net7.0 instead of net6.0 and it worked without any issues.
