### ISSUE TITLE
Expensive bitmap rendering

### ISSUE THREAD

**Issue by ImpulseDeer** [Mapsui/Mapsui#1967]
**Mapsui Version**
4.0.0-beta.10

**Mapsui Platform**
WPF

**Device**
Windows 10

**Describe the bug**
It is reported over at the SkiaSharp issue tracker that changes in 2.88 saw major degradation in bitmap rendering performance: https://github.com/mono/SkiaSharp/issues/2188

I have seen quite a high load on the SkiaSharp draw calls for the rendering the bitmap tiles when trying out Mapsui. Maybe worth trying out the proposed fix to mark the bitmaps immutable?

**Comment by pauldendulk** [comment]
Thanks for the suggestion but we do not use canvas.DrawBitmap in our code but canvas.DrawImage which draws a SKImage which is mentioned in that thread as a solution, so I think this does not apply.
