### ISSUE TITLE
[Regression] Artifical clipping on rotated map

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1975]
**Mapsui Version**
4.0.0-beta.11

**Mapsui Platform**
Xamarin.Forms

**Device**
Android 13

**Describe the bug**
I'm seeing a problem with rotated maps with v4.0.0-beta.11 on Android. If I draw a circle on a rotated map, it is somehow clipped artifically (smaller than the actual viewport). See screenshot below (map rotated by 90°).

This was working with beta.10 (the problem appeared with beta.11). It works on iOS, but fails on Android. Non-rotated maps work fine. I suspect it was broken by #1959.

**Expected behavior**
The circle should be drawn over the full viewport and not be clipped artificially.

**Screenshots**
![Screenshot_20230424_115218](https://user-images.githubusercontent.com/484108/233966953-12e738f5-add1-4098-ade9-c593a0478d20.jpg)

**Comment by pauldendulk** [comment]
Oh no, did I push my code to test clipping? I am on phone right now so not easy to check.

**Comment by pauldendulk** [comment]
I broke it here. https://github.com/Mapsui/Mapsui/pull/1959#discussion_r1176029629. Removing the Grow(-50) will fix it.

**Comment by janusw** [comment]
> Why does it only occur on Android, though?

Probably it also occurs on iOS. I think I simply did not use a rotated map on iOS when I tried it.
