### ISSUE TITLE
[Regression] Pins are not rendered with rc.1

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1995]
**Mapsui Version**
4.0.0-rc.1

**Mapsui Platform**
Xamarin.Forms

**Device**
Android, iOS, Mac

**Describe the bug**
With rc.1, the Pins on a MapView are not being rendered any more. With beta.11 they are still visible. I'm using `PinType.Icon`, but changing this to `PinType.Pin` does not seem to make a difference. Happens on all platforms that I tried.

I would expect that the problem should be visible in the samples, but I haven't checked that yet. Looking at the recent git history, #1973 seems like it might be a possible culprit (it's the only PR since beta.11 that touches the Pin class).

**Comment by pauldendulk** [comment]
I can reproduce this in the MapView 'Add Pin Sample'. The callout is visible but not the pin.

**Comment by janusw** [comment]
> I can reproduce this in the MapView 'Add Pin Sample'. The callout is visible but not the pin.

Thanks for the confirmation. I have verified that 4.0.0-beta.11-37-g4788199a1 still works.

**Comment by janusw** [comment]
> I have verified that 4.0.0-beta.11-37-g4788199a1 still works.

OTOH, 4.0.0-beta.11-47-gce2544005 fails (which is the merge commit of #1973), so I'd conclude that #1973 indeed caused this issue.

@inforithmics, do you understand how the problem comes about?

**Comment by inforithmics** [comment]
I‘ll investigate it

**Comment by janusw** [comment]
Fixed via #1997.
