### ISSUE TITLE
Add SymbolStyle.IconPath as alternative for SymbolStyle.BitmapId

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1998]
**The problem**
Currently the registration and assignment of BitmapId is not very handy. Users need to do a couple of things, load a bitmap, register it and assign it to the SymbolStyle.BitmapId. There are various helpers to make this easier but it is not very clear what should be used.

**The solution**
Add a SymbolStyle.IconPath which specifies the location of the icon, like:
- `SymbolStyle.IconPath = "file://myfolder/myimage.png"`
- `SymbolStyle.IconPath = "http://mywebsite.com/myimage.png"`
- `SymbolStyle.IconPath = "embeddedResource://myassembly.resourses.images.myimage.png"`

The images are loaded by Mapsui and added to BitmapRegistry. The IconPath string should be used as key to make sure they are loaded only once.

The BitmapId could still be used, but not in combination with IconPath.

A longer term goal is to serialize the entire layer definition to file. This would also need bigger changes to how layers are defined, and the fetching logic should be moved from the layers to the MapControl, Map, or a new Fetcher class.

**Alternatives**
I did not spend much time thinking about alternatives yet, but I am sure there are a lot.

**Comment by pauldendulk** [comment]
Having a look of some of our code to see how this could work. The CustomCalloutSample has this string: `const string path = "Mapsui.Samples.Common.GeoData.Json.congo.json";` which is used to retrieve an embedded resource. This could be turned into: `embeddedResource://Mapsui.Samples.Common.GeoData.Json.congo.json`. And the renderer should use that string as the cache. If it is not in the cache the renderer should retrieve it from the assembly.

CustomCalloutSample  also has the CreateCallbackImage which creates an in-memory bitmap stream. For this case I don't have a good solution yet. In some cases we want to work with SKPicture references in memory. We do want to support this use case.

**Comment by inforithmics** [comment]
I'll implement this but the IconPath is an Uri

```
  var file = new Uri("file://myfolder/myimage.png");
  var http = new Uri("http://mywebsite.com/myimage.png");
  var resource = new Uri("embeddedResource://myassembly.resourses.images.myimage.png");
```

tested it (in unit test and all 3 work).

**Comment by pauldendulk** [comment]
This was implemented in a series of merge requests (and involved quite some refactoring).

**Comment by mfranc28** [comment]
Hey where is this ? I don't see it in the last update.

**Comment by pauldendulk** [comment]
@mfranc28 It is 5.0.0-beta.2 but ended up as 'SymbolStyle.ImageSource'. Here is some documentation https://mapsui.com/v5/imagesource/
