### ISSUE TITLE
Xamarin.Forms MapView crashes on iOS when using Hot Restart - release 3.0.2 and 4.0.0-rc.2

### ISSUE THREAD

**Issue by sylverbee** [Mapsui/Mapsui#2011]
**Mapsui Version**
3.02

**Mapsui Platform**
Xamarin.Forms

**Device**
iPhone 6Splus iOS 15.7.6
iPhone XR iOS 16.4.1
iPad Pro 16.4.1

**Describe the bug**
When try to display a page with a MapView, the app crashes.
Displaying a MapControl is ok.

**To Reproduce**
Create a ContentPage
Add XAML code
```
<ContentPage x:Class="SnowballsBattle.Pages.Map2Page" xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms" NavigationPage.HasBackButton="False">
    <ContentPage.Content>

        <StackLayout>
            <mapsui:MapView x:Name="myMap" BackgroundColor="Gray" HorizontalOptions="Fill" IsMyLocationButtonVisible="True" VerticalOptions="FillAndExpand" />
        </StackLayout>

    </ContentPage.Content>
</ContentPage>
```

**Additional context**
App works correctly on PC (W11) and Android (simulator)
Dev on VS 2022 Windows

**Comment by pauldendulk** [comment]
I will personally do not want to make time for 3.0.2 bugs while we are close to releasing 4.0.0. Did you try 4.0.0-rc.2 as well?

**Comment by sylverbee** [comment]
Yes I did : same concern.

**Comment by pauldendulk** [comment]
> Yes I did : same concern. I haven't tried to use a Mac to deploy app on device. Some report it could be a solution.

ah, you are referring to the remark of @Inrego https://github.com/Mapsui/Mapsui/issues/1872#issuecomment-1573342107. My interpretation of this is just does not work when using Hot Start, and the problem is in the way things are deployed in Hot Start. So, I think this is something we can not fix, and perhaps we should submit a bug in some Microsoft project.

**Comment by pauldendulk** [comment]
### Conclusion

This is a limitation of Hot Restart

https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart#limitations
