### ISSUE TITLE
WFS Multipoint: Empty Geometry

### ISSUE THREAD

**Issue by wilhelmberg** [Mapsui/Mapsui#2013]
## Mapsui Version
Custom fork of `4.0.0-beta.8`

## Mapsui Platform
NET 6 Web App

## Device
Windows

## Describe the bug

All NTS geometries returned from [this WFS](https://www.data.gv.at/katalog/en/dataset/740b8eeb-79d6-4dfd-b237-0f8fec5ed39b#resources) are empty.

WFS geometries look like this:

```xml
<vogis:the_geom>
    <gml:MultiPoint srsName="http://www.opengis.net/gml/srs/epsg.xml#31254">
        <gml:pointMember>
            <gml:Point>
                <gml:pos>-55439.03125 233237.953125</gml:pos>
            </gml:Point>
        </gml:pointMember>
    </gml:MultiPoint>
</vogis:the_geom>
```

## Fix the bug

Added
```c#
IPathNode posNode = new PathNode(
    "http://www.opengis.net/gml"
    , "pos"
    , (NameTable)XmlReader.NameTable
);
```

here:
https://github.com/Mapsui/Mapsui/blob/0efa00ff144f4196e6ad5fbe11782bd426443754/Mapsui.Nts/Providers/Wfs/Utilities/GeometryFactories.cs#L271

and changed

```c#
CoordinatesNode = new AlternativePathNodesCollection(coordinatesNode, posListNode);
```

to

```c#
CoordinatesNode = new AlternativePathNodesCollection(coordinatesNode, posListNode, posNode);
```

**Comment by pauldendulk** [comment]
Thanks for the bug report. Mapsui beta.8 is four months old, there have been some changes. Did you test with the rc.2 as well?

**Comment by wilhelmberg** [comment]
NET 6 Console app with `Mapsui.Nts@4.0.0-rc.2 nupkg`

```c#
WFSProvider provider = await WFSProvider.CreateAsync(
	"https://vogis.cnv.at/geoserver/vogis/laser_2002_04_punkte/ows"
	, "vogis"
	, "laser_2002_04_punkte"
	, WFSProvider.WFSVersionEnum.WFS_1_1_0
);

provider.CRS = "EPSG:31254";

MRect bbox = new(
	-34900
	, 255900
	, -34800
	, 256000
);

IEnumerable<IFeature> features = await provider.ExecuteIntersectionQueryAsync(bbox);
foreach (IFeature feature in features) {
	if (feature is not GeometryFeature ntsGeometryFeature) {
		continue;
	}
	Console.WriteLine(ntsGeometryFeature.Geometry);
}
```

Output:
```
MULTIPOINT EMPTY
MULTIPOINT EMPTY
```

**Comment by pauldendulk** [comment]
So what do you think? Simply add the "pos" namespace and it will be solved? Is this just one namespace we missed? Why was this not a problem before? Is this WFS different? Different WFS version? Or should or client somehow detect the namespaces used in the WFS response?

**Comment by wilhelmberg** [comment]
Adding `pos` to the list of possible candidate tags for coordinates solved the problem for me.

But I'm not familiar with the WFS specification and cannot say if `<pos>xx.xxx yy.yyy</pos>`  (see OP) is valid for a MultiPoint feature instead of `<coordinates>` or `<posList>` .
Or if the WFS is misconfigured.

FYI: The layer displays in QGIS without problems.

`<coordinates>` and `<posList>` are defined here (that's where I added `pos`):
https://github.com/Mapsui/Mapsui/blob/0efa00ff144f4196e6ad5fbe11782bd426443754/Mapsui.Nts/Providers/Wfs/Utilities/GeometryFactories.cs#L273-L276

**Comment by pauldendulk** [comment]
I do not want to dig into WFS at this point because I am busy with other thing. We could just add your fix for now and wait for the next complained. @inforithmics What do you think?

**Comment by inforithmics** [comment]
I'll have a look.

**Comment by inforithmics** [comment]
Pull request (sample does not work yet)

https://github.com/Mapsui/Mapsui/pull/2030

**Comment by pauldendulk** [comment]
#2030 was merged
