### ISSUE TITLE
Callouts do not work in Blazor

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2014]
**Mapsui Version**
4.0.0-rc.2

**Mapsui Platform**
Blazor, not on WPF or Avalonia.

**Device**
Windows, in the Chrome browser

**Describe the bug**
The Info | Single Callout sample should show a callout when clicking on a symbol but it does not. The logger mentions a DllNotFoundException with as message libHarfBuzzSharp.

![image](https://github.com/Mapsui/Mapsui/assets/963462/a5996711-eb6f-474f-ab63-b95b0ae62038)

**To Reproduce**
1. Run Samples.Mapsui.Blazor which is part of the Mapsui repository, or go to https://mapsui.com/samples/
2. Select category 'Info'
3. Select sample 'Single Callout'
4. Click on a symbol.
5. Don't see a callout

**Expected behavior**
Show a callout.

**Comment by pauldendulk** [comment]
Current status: Fixed for our sample, but not for our users.

**Comment by mattleibow** [comment]
I think this will fix it: https://github.com/mono/SkiaSharp/pull/2497

CI is still working, but a `2.88.4-preview.77` version should appear in the feed https://aka.ms/skiasharp-eap/index.json

**Comment by pauldendulk** [comment]
@mattleibow  I upgraded to SkiaSharp 2.88.4-preview.77 but did not fix the problem. Upgrading to 2.88.4-preview.82 that not fix it either. Here is the PR with the upgrade https://github.com/Mapsui/Mapsui/pull/2086/files

This line needs to be enabled:
```<NativeFileReference Include="libHarfBuzzSharp.a" />```

This is the message of the exception:
```Unexpected error in skia rendererException in BuildFontRuns() with original length of 53 now 53, style run count 1, font run count 0, direction overrides: False```

**Comment by inforithmics** [comment]
Made a pull request for this

https://github.com/Mapsui/Mapsui/pull/2103

**Comment by pauldendulk** [comment]
Assume this is fixed with the MR. Please test on the next release.
