### ISSUE TITLE
MapControl.TouchEnded is not always triggered

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#2017]
**Mapsui Version**
4.0.0-rc.2

**Mapsui Platform**
Xamarin.Forms

**Device**
Android & iOS

**Background**
I want to implement a custom behavior for single-finger dragging in a `MapView`. To achieve this, I enable `MapView.PanLock` (and possibly `MapView.ZoomLock`) and implement handlers for the events `MapControl.TouchStarted`, `MapControl.TouchMove` and `MapControl.TouchEnded`.

**Describe the bug**
`TouchStarted` and `TouchMoved` are basically triggered as expected, but I noticed that sometimes the `TouchEnded` event seems to be missing at the end of a single-finger dragging gesture.
At first I was completely puzzled about when the problem occurs, but after playing around for a while I noticed:
* When keeping the finger steady for a moment, before lifting it off the screen, `TouchEnded` is triggered quite reliably.
* When performing a fast dragging gesture and lifting the finger right during the movement (without stopping), `TouchEnded` is omitted.

**Comment by janusw** [comment]
After inspecting the MapControl code, I think I found the part that causes the observed behavior:

https://github.com/Mapsui/Mapsui/blob/3f138795ff407046e34411c7a86a34579c2508d5/Mapsui.UI.Forms/MapControl.cs#L326-L332

Note that all of this happens in an if-branch that checks for `e.ActionType == SKTouchAction.Released`. What I don't understand at all is why one would trigger a `TouchStarted` event on `SKTouchAction.Released`. (*)

I think what happens is this:
* If the finger movement stops before lifting, the last point is released from `_touches`, so that it is empty. Everything is fine and works as expected in this case.
* If the finger movement does not stop before lifting, the release-point seems to be different from the last move-point, and is therefore not removed, so that `_touches` is not empty, and `TouchStarted` is triggered instead of `TouchEnded`.

To me this clearly looks like a bug, but maybe there is a particular reason why the behavior is like this? One should check why the `OnTouchStart` was inserted in the code above (and whether it can be removed without breaking anything). I think that removing it would solve my problem.

(*) The only thing I could think of: If two fingers were touching, and one is released, so that one switches from a two-finger gesture (usually zoom) to a single-finger gesture (usually pan), one might possibly want to signal the start of the sinlge-finger gesture. But even then, one would still need to signal the end of the two-finger gesture, right?!?

**Comment by janusw** [comment]
> After inspecting the MapControl code, I think I found the part that causes the observed behavior:
> 
> https://github.com/Mapsui/Mapsui/blob/3f138795ff407046e34411c7a86a34579c2508d5/Mapsui.UI.Forms/MapControl.cs#L326-L332
> 
> Note that all of this happens in an if-branch that checks for `e.ActionType == SKTouchAction.Released`. What I don't understand at all is why one would trigger a `TouchStarted` event on `SKTouchAction.Released`. (*)
> 
> [..]
> 
> To me this clearly looks like a bug, but maybe there is a particular reason why the behavior is like this? One should check why the `OnTouchStart` was inserted in the code above (and whether it can be removed without breaking anything).

If I'm not mistaken, then the `OnTouchStart` was inserted in 3e7cbddf0758407c5711651a833b368df329954b (as part of PR #600).

**Comment by janusw** [comment]
> If I'm not mistaken, then the `OnTouchStart` was inserted in [3e7cbdd](https://github.com/Mapsui/Mapsui/commit/3e7cbddf0758407c5711651a833b368df329954b) (as part of PR #600).

Unfortunately this PR does not include a lot of comments about which problem exactly is fixed or under which circumstances the bug occurs. Also no issue is linked to the PR :/

**Comment by pauldendulk** [comment]
Thanks for your analysis!

It seems this is exactly the same problem:
https://github.com/Mapsui/Mapsui/issues/2000

> I suspect what is happening is that the TouchStarted event is being fired but the TouchEnded event is not.

**Comment by pauldendulk** [comment]
Perhaps relevant. In many UI frameworks a mouseDown event is not necessary followed by a mouseUp event, there can be mouseLeave or mouseCanceled instead. 

Also, the TouchStarted events is part of the MapView, so is not supported on all platforms and there will probably be changes in how this works.

**Comment by janusw** [comment]
> Perhaps relevant. In many UI frameworks a mouseDown event is not necessary followed by a mouseUp event, there can be mouseLeave or mouseCanceled instead. So instead of getting TouchEnded to fire we may need to look into TouchExisted instead.

Thanks for the comment. I just checked. What I see is a `TouchStarted` at the beginning of the dragging gesture, then a serious of `TouchMove` (all as expected so far), but then nothing when the gesture is stopped (when the finger is lifted while moving): Not`TouchEnded`, no `TouchExited`, and also nothing else (neither `TouchStarted` nor `TouchEntered`). Somehow the end signal is simply missing.

> Also, the TouchStarted events is part of the MAUI specific MapView, so is not supported on all platforms and there will probably be changes in how this works.

Not fully true. It's actually part of the MapControl, not the MapView. It seems it's available in Xamarin.Forms and MAUI, but apparently not in the other platform-specific MapControls(?).

**Comment by pauldendulk** [comment]
> Not fully true. It's actually part of the MapControl, not the MapView. It seems it's available in Xamarin.Forms and MAUI, but apparently not in the other platform-specific MapControls(?).

Yes sorry, you are right, not in MapView but But it is something we would like to get the same for all platforms at some point. And in general I would like to support less specific solutions (so we do not have to support it) but at the same time allow users to implement things themselves.

**Comment by janusw** [comment]
> > Perhaps relevant. In many UI frameworks a mouseDown event is not necessary followed by a mouseUp event, there can be mouseLeave or mouseCanceled instead. So instead of getting TouchEnded to fire we may need to look into TouchExisted instead.
> 
> Thanks for the comment. I just checked. What I see is a `TouchStarted` at the beginning of the dragging gesture, then a serious of `TouchMove` (all as expected so far), but then nothing when the gesture is stopped (when the finger is lifted while moving): Not`TouchEnded`, no `TouchExited`, and also nothing else (neither `TouchStarted` nor `TouchEntered`). Somehow the end signal is simply missing.

After looking through the `MapControl` code once more, I found the simple solution to this puzzle: If the finger lifting happens while moving, one does not receive a `TouchEnded`, but a `Swipe` event, which is documented to exactly match this situation:

https://github.com/Mapsui/Mapsui/blob/45ccb7638456a53796a5f1423b5d911dedd36ad3/Mapsui.UI.Forms/MapControl.cs#L454-L457

Too bad I didn't see this before. So it seems the 'bug' I'm describing is not really a bug, but merely a feature(?): One simply gets different types of events, depending on whether finger lifting occurs at rest, or during movement. Although one could argue that the difference between the two can be pretty subtle in practice ...

**Comment by janusw** [comment]
> After looking through the `MapControl` code once more, I found the simple solution to this puzzle: If the finger lifting happens while moving, one does not receive a `TouchEnded`, but a `Swipe` event, which is documented to exactly match this situation:

Sorry, that is actually not quite true: What I see is only the `Fling` event, not `Swipe`.

Testing on Android (v13), as long as a move fast enough, I get `Fling`. If I move slower, I get `TouchEnded`. I was not able to trigger the  `Swipe` in between. It seems the velocity is _always_ fast enough to trigger the `Fling` condition. If I disable `UseFling`, I get `TouchEnded` or nothing. I would count this as a 'bug', after all 😉

**Comment by charlenni** [comment]
I think, the most of this code is coming from me. If I remember it correct, it wasn't easy to do this all by myself, because it is handled slightly different on each platform and SkiaSharp provides only the basic things. Perhaps it is nowadays a little different, I don't know this.

For a detailed description of touch, swipe and fling see [this](https://m1.material.io/patterns/gestures.html#gestures-drag-swipe-or-fling-details) article.

**Comment by pauldendulk** [comment]
In this case it is a bit unclear what should happen so hard to determine what is correct. So I am going to look at #2000 first, because we can be sure the map should not lock.

**Comment by janusw** [comment]
> > After looking through the `MapControl` code once more, I found the simple solution to this puzzle: If the finger lifting happens while moving, one does not receive a `TouchEnded`, but a `Swipe` event, which is documented to exactly match this situation:
> 
> Sorry, that is actually not quite true: What I see is only the `Fling` event, not `Swipe`.
> 
> Testing on Android (v13), as long as I move fast enough, I get `Fling`. If I move slower, I get `TouchEnded`. I was not able to trigger the `Swipe` in between. It seems the velocity is _always_ fast enough to trigger the `Fling` condition. If I disable `UseFling`, I get `TouchEnded` or nothing. I would count this as a 'bug', after all 😉

The relevant code is this:
https://github.com/Mapsui/Mapsui/blob/45ccb7638456a53796a5f1423b5d911dedd36ad3/Mapsui.UI.Forms/MapControl.cs#L269-L278

The main problem here is that `OnSwiped` is not called at all. Moreover, the velocity condition does not look proper to me. IMHO it should only depend on the absolute value, not the separate velocity components.

**Comment by janusw** [comment]
> > In this case it is a bit unclear what should happen so hard to determine what is correct. So I am going to look at #2000 first, because we can be sure the map should not lock.
> 
> Ok, sure. I will take a stab at fixing the problem here myself, and would be grateful for some comments on that.

see #2026

**Comment by janusw** [comment]
> The relevant code is this:
> 
> https://github.com/Mapsui/Mapsui/blob/45ccb7638456a53796a5f1423b5d911dedd36ad3/Mapsui.UI.Forms/MapControl.cs#L269-L278
> 
> The main problem here is that `OnSwiped` is not called at all. 

My git archeology research indicates that the `OnSwiped` event has never actually been called. In the initial commit (8e649d0e2634d1692bb706bb6af0c2a550f776e0), `OnSwiped` is implemented but never called (only `OnFlinged` is), and apparently such a call has never been added since then, so it's about time ;)

**Comment by pauldendulk** [comment]
Could we remove Swipe altogether? Below is the implementation of OnSwiped. It does not do any navigation, so it just calls the event that the user might listen to, but not clear for what purpose. And there is apparently something todo as well. Also, we do not have Swipe on other platforms. 

```
    private bool OnSwiped(double velocityX, double velocityY)
    {
        var args = new SwipedEventArgs(velocityX, velocityY);

        Swipe?.Invoke(this, args);

        // TODO
        // Perform standard behavior

        return args.Handled;
    }
```

This is from the documentation in the MapControl. Apparently the difference is speed. I assume we could just decide that there is no gesture detected when the speed is to low. In that case we should have a normal TouchStart and TouchEnd.

```
    /// <summary>
    /// Swipe is called, when user release mouse button or lift finger while moving with a certain speed 
    /// </summary>
    public event EventHandler<SwipedEventArgs>? Swipe;

    /// <summary>
    /// Fling is called, when user release mouse button or lift finger while moving with a certain speed, higher than speed of swipe 
    /// </summary>
    public event EventHandler<SwipedEventArgs>? Fling;
```

**Comment by charlenni** [comment]
One more thing: While reading about this, I found an old webpage about problems of different speeds values for fling, because they depend on the resolution of the display (number of pixels per second on 4" or 5" displays). Not sure, if this is the case here, too.

**Comment by pauldendulk** [comment]
> One more thing: While reading about this, I found an old webpage about problems of different speeds values for fling, because they depend on the resolution of the display (number of pixels per second on 4" or 5" displays). Not sure, if this is the case here, too.

This is probably something we need to take care of at some point. Perhaps we should add a todo about in the fling code.

**Comment by charlenni** [comment]
@pauldendulk You are right. I missed, that the touch handling is only for the Forms and MAUI part. But if @janusw corrects it, I would still include it. At the moment there isn't anything, we could think about. But later, it is helpful to someone. And at this time, add a property for the velocity, so that users could change it by setting their own value. No need to check this for all platforms and all devices.

What I remember correct is, that you said, that the Forms part of Mapsui should be kept away from Mapsui, because there are too many platforms. Seems, that you changed your mind meanwhile 😉

**Comment by pauldendulk** [comment]
That might be, I change my mind all the time 😁. Perhaps what I was thinking about then was that you had then an already well developed version specific to forms (developed in your own repository) which was not easy to integrate with the other platforms that we had at that point. So, we had to keep that separate at that point, and add parts to the shared project later on. I don't think the OnSwipe is needed, but we will need other parts that are now mostly in MapView. For instance, a standard location position layer should be available for all platforms.

**Comment by charlenni** [comment]
The most important part of MapView is, that the coordinates look like the users expect them. So the right way is to implement correct handling of projections to convert coordinates on the fly between Features in the layer and Mapsui. If they have a layer which converts all the coordinates of their various Features from lat/lon to Mapsui format (which they don't know), then they don't need MapView anymore, and you could get ride off.

Regarding the MyLocationLayer: This shouldn't be very complicated to transfer it from MapView to MapControl. The most complicated part is the coordinate transformation.

**Comment by pauldendulk** [comment]
@janusw A question about your use case. You tried to implement custom dragging. Could you have used the Xamarin/MAUI touch events instead of the Mapsui events? Deferring such a use case to the platform could make things easier for Mapsui.

**Comment by charlenni** [comment]
Perhaps I could answer this.

If you want to have a MAUI or Forms version, that runs on all platforms, you should use the touch handling that SkiaSharp offers with their MAUI or Forms implementation. This is only a subset of the capabilities of the used platform (see for example the Android [implementation](https://github.com/mono/SkiaSharp/blob/6b626b3bca0240a9a285e975d3e17adfcbac193f/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs)). If you want improve this, you should change it in SkiaSharp and not in Mapsui for Forms or MAUI.

What could be moved to shared code is the handling of this events, e.g. what happens if you touch or fling and how it is handled.

**Comment by janusw** [comment]
> @janusw A question about your use case. You tried to implement custom dragging. Could you have used the Xamarin/MAUI touch events instead of the Mapsui events?

Actually I don't think this would be a good idea for my use case, since I also have other objects on the map control (like widgets, pins, callouts, etc) that need to intercept tap events (which requires Mapsui's hit detection). The custom handling of touch events on the map should only kick in, if no other object has been tapped. (In fact this doesn't always seem to work, in particular on Android. I will possibly open another issue for that.)

With the standard Xamarin/Maui touch events I won't be able to do proper hit detection with objects on the map, I guess, because they occur before all the Mapsui event handling, right?

**Comment by janusw** [comment]
I think all problems mentioned in this issue have been fixed by now, partly on the user side by disabling `UseFling`, partly on the Mapsui side by merging #2032.

**Comment by pauldendulk** [comment]
@janusw ok, clear.

What I am looking for a solution where the user can do everything they want without Mapsui having to know about their scenarios. The response of @charlenni pointed to the SkiaSharp OnTouch event. If the user could hook into that they would have all freedom. Yet you also want to be able to use the Mapsui hit detection. I have rough ideas of how we could have the best of both worlds, but it would involve bigger changes, so not something for the current phase of the project. I'll shut up.

**Comment by janusw** [comment]
> What I am looking for a solution where the user can do everything they want without Mapsui having to know about their scenarios. The response of @charlenni pointed to the SkiaSharp OnTouch event. If the user could hook into that they would have all freedom. Yet you also want to be able to use the Mapsui hit detection. I have rough ideas of how we could have the best of both worlds, but it would involve bigger changes, so not something for the current phase of the project. 

That is actually not an issue for me. I can basically do all I want with MapControl's `TouchStarted` / `TouchMove` / `TouchEnded` events. The only remaining issue might be the correct ordering of events and the relation to hit detection of map objects etc. I'm looking into that now ...

**Comment by pauldendulk** [comment]
This OnTouchStart is probably intentional. It occurs when one finger is released but another is still touching. 

https://github.com/Mapsui/Mapsui/blob/3f138795ff407046e34411c7a86a34579c2508d5/Mapsui.UI.Forms/MapControl.cs#L326-L332
