### ISSUE TITLE
Mouse wheel event is propagate to parent in Blazor

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2042]
**Mapsui Version**
4.0.0-rc.3

**Mapsui Platform**
Blazor

**Device**
Windows Chrome browser

**Describe the bug**
When mouse wheel zooming the map itself behaves as expected (it zooms in and out) but it also triggers a scroll zoom on the page as a whole, moving the map itself up and down.

**To Reproduce**
1. Open any sample in https://mapsui.com/samples/
2. Make the page small enough so that a scroll bar is shown.
3. Use mouse wheel to zoom in/out
4. You see the map zooming in but also the map as whole scrolling up and down.

**Expected behavior**
I expect that the scroll event is not propagated to the parent. On other dotnet platform an EventArgs.Handled = true could be used for that.

**Comment by pauldendulk** [comment]
So far, did not succeed to prevent this.

tried:
```html
    @onmousewheel:stopPropagation="true"
    @onmousewheel:preventDefault="true"
```

Some things I googled:
- https://stackoverflow.com/questions/61579284/how-to-stop-event-propagation-in-blazor-server-app
- https://github.com/dotnet/aspnetcore/issues/24932
- https://github.com/dotnet/aspnetcore/issues/17358

**Comment by inforithmics** [comment]
'''<div @onwheel="OnWheel">
    
</div>

@code {
    private void OnWheel(WheelEventArgs e)
    {
        e.preventDefault();
        // Handle the wheel event as needed
    }
}
'''

**Comment by pauldendulk** [comment]
No luck so far.

**Comment by inforithmics** [comment]
ChatGpt and some code fixes

https://github.com/Mapsui/Mapsui/pull/2046

**Comment by inforithmics** [comment]
Chat gpt suggested using an Javascript interop. But the javascript code had an error I needed to fix to make it work. So 95 % success with chatgpt

**Comment by pauldendulk** [comment]
I find it most helpful for things that are used a lot like javascript and python. Did not expect it to be great for this kind of Blazor niche thing, but this looks good.

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/2046
