### ISSUE TITLE
Mapsui.Avalonia 4.0.0-rc.3 references Avalonia.Desktop which breaks WASM

### ISSUE THREAD

**Issue by slater1** [Mapsui/Mapsui#2061]
**Mapsui Version**
Mapsui.Avalonia 4.0.0-rc.3

**Mapsui Platform**
Avalonia WASM

**Device**
Windows 10 

**Describe the bug**
Mapsui.Avalonia depends on Avalonia.Desktop. If Mapsui.Avalonia is referenced from an Avalonia 11 browser csproj, the following error results

`Parameter types of pinvoke callback met
hod 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable`

Which is the same problem caused last fall by [FluentAvalonia](https://github.com/AvaloniaUI/Avalonia/discussions/9264)

**To Reproduce**
```
dotnet new install Avalonia.Templates --avalonia-version 11.0.0-rc1.1
dotnet new avalonia.xplat -o test
cd test/test.Browser
dotnet add package Mapsui.Avalonia -v 4.0.0-rc.3
dotnet build
```

Result:
```
PS > dotnet build
MSBuild version 17.6.1+8ffc3fe3d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Could not extract the MVID from "obj\Debug\net7.0\refint\test.dll". Are you sure it is a reference assembly?
  test -> F:\repos\dauer\test\test\test\bin\Debug\net7.0\test.dll
  test.Browser -> F:\repos\dauer\test\test\test.Browser\bin\Debug\net7.0\browser-wasm\test.Browser.dll
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.5\Sdk\WasmApp.Native.targets(290,5): error : Parameter types of pinvoke callback met
hod 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable. [F:\repos\dauer\test
\test\test.Browser\test.Browser.csproj]

Build FAILED.
```

**Expected behavior**
I can build the Avalonia WASM target referencing Mapsui.

**Screenshots**
![image](https://github.com/Mapsui/Mapsui/assets/2089725/0a12d0ea-37db-43ce-90b1-fa86d1042801)

**Additional context**
It seemed to work before Avalonia 11 rc1.1 / 4.0.0-rc3. Is the Avalonia.Desktop reference new?

**Comment by inforithmics** [comment]
I made a pull request that reference Avalonia.skia instead of Avalonia.Desktop this should fix the problem.

**Comment by slater1** [comment]
Can confirm [version 4.0.0](https://www.nuget.org/packages/Mapsui.Avalonia/4.0.0) fixes this issue
