### ISSUE TITLE
Mapsui.Samples.Maui has problem connecting to WMS server on Android 13 platform.

### ISSUE THREAD

**Issue by FrankCAD** [Mapsui/Mapsui#2107]
**Mapsui Version**
4.0.0

**Mapsui Platform**
MAUI

**Device**
Android 13
Emulator 'Tablet M-DPI 10.1in - API 33'

**Describe the bug**
Problem connecting to WMS server.

1. Run Mapsui.Samples.Maui
2. Go to 'Data Formats'
3. Click on example '6 WMS'
4. Map does not display (should show map 'Windkaart' of The Netherlands)

Traced the problem back to line 350 in the file Mapsui/Providers/Wms/WmsProvider.cs (Task FetchOnThreadAsync) generating WebException.
See [System.Net.WebException.txt](https://github.com/Mapsui/Mapsui/files/11990734/System.Net.WebException.txt)

Similar problems with the examples: 
3 WMTS 
5 WMTS Michelin 
6 WMS Projection 
6 WMS Projection DotSpatial 
8 TMS openbasiskaart

_Running the same examples on 'Windows Machine' do not show these problems._

**Comment by inforithmics** [comment]
Thanks for the Bug Report will be fixed in this pull request
https://github.com/Mapsui/Mapsui/issues/2107

**Comment by pauldendulk** [comment]
Should be fixed in 4.1.0-preview.1.
