### ISSUE TITLE
WMSProvider return null CRS array 

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#2118]
**Mapsui Version**
4.0.0

**Mapsui Platform**
Xamarin - Android

**Device**
Samsung A53

**Describe the bug**
WMSProvider return null CRS array with this url: http://geocatalogo.regione.abruzzo.it/erdas-iws/ogc/wms

**To Reproduce**
`            
WmsProvider provider = await WmsProvider.CreateAsync("http://geocatalogo.regione.abruzzo.it/erdas-iws/ogc/wms", persistentCache: MyDefaultCache);
`

**Expected behavior**
provider.CRS should not be null. This server supports these CRS: 
<CRS>EPSG:32633</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:3857</CRS>

**Comment by pauldendulk** [comment]
The capabilities list the the CRSes available, but you need to select the one you want to use yourself. Below is code I used to get a layer from that service.

```csharp

    public static async Task<ILayer> CreateLayerAsync()
    {
        var dataSource = await WmsProvider.CreateAsync("http://geocatalogo.regione.abruzzo.it/erdas-iws/ogc/wms");
        dataSource.CRS = "EPSG:3857";
        dataSource.AddLayer("Mosaici_UTM-WGS84_2018_2019_Regione_Abruzzo.ecw");
        
        return new ImageLayer("wms")
        {
            DataSource = dataSource,
            Style = new RasterStyle()
        };
    }
```

WMS over map:

![image](https://github.com/Mapsui/Mapsui/assets/963462/8fcca517-1d3d-4e83-ac05-d79d4cef0d04)

**Comment by gpsaliola** [comment]
`WmsProvider provider = await WmsProvider.CreateAsync("http://geocatalogo.regione.abruzzo.it/erdas-iws/ogc/wms", persistentCache: MyDefaultCache);`

After this statement, shouldn't provider.CRS list supported CRSs?
It works with other URLs, why not with this one?

**Comment by pauldendulk** [comment]
Glancing at the code I don't immediately see how to would work and if I remove the CRS in the OpenSea map sample I get the same error. Do you have an example of another url where it does work?

**Comment by gpsaliola** [comment]
In my app, the user chooses which map to display from a database.
To set the CRS to use use this code (example):

```
    public static async Task<ILayer> CreateLayerAsync()
    {
        var dataSource = await WmsProvider.CreateAsync("http://geocatalogo.regione.abruzzo.it/erdas-iws/ogc/wms");
        
		// Your statement ----
		// dataSource.CRS = "EPSG:3857";
                // ----
		
		// My Statement ----
		string lCrs;
		if (dataSource.IsCrsSupported("EPSG:3857") == true) lCrs = "EPSG:3857";
		else if (dataSource.IsCrsSupported("EPSG:4326") == true) lCrs = "EPSG:4326";
		else throw new Exception("EPSG Not Supported");
		dataSource.CRS = lCrs; 
		// ----
		
		dataSource.AddLayer("Mosaici_UTM-WGS84_2018_2019_Regione_Abruzzo.ecw");
        
        return new ImageLayer("wms")
        {
            DataSource = dataSource,
            Style = new RasterStyle()
        };
    }

```

**Comment by pauldendulk** [comment]
I am now stepping through a sample with the sample layer above but don't see anything irregular so far. Perhaps you could create a little sample to show me exactly which value is different from what you expect. Follow a getting started and then add the WMS layer on top of it, and throw an exception on the unexpected value.

**Comment by gpsaliola** [comment]
I'm very sorry I misinterpreted.
I thought that provider.CRS contained the collection of supported CRS and I didn't realize that I have to set it myself.
I'm sorry if I wasted your time, you were very kind.
Thank you.

**Comment by pauldendulk** [comment]
The IProvider.CRS is just a single string value. Perhaps you got confused with the list of CRSes in the wms layers. 

What is confusing is that the layers in wms have a tree structure (layers contain child layers, which contain child layers, etc). Perhaps you were looking at the wrong wms layer. In the case this WMS there are three levels, The rootlayers, and then a child layer under that, and then real layers, with their the CRS list.

![image](https://github.com/Mapsui/Mapsui/assets/963462/822e5530-a019-41af-a4e6-89fc30942905)

**Comment by gpsaliola** [comment]
Optimal. Truly many thanks.
Perfect explanation.
Sorry for misinterpreting.
Thank you again.
