### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Smurfj3** [Mapsui/Mapsui#2120]
I have a rather large number of pins on the map (around 5000), I am aware that this will cause stuttering, but I thought setting the MaxVisible resolution would fix this issue. However it has 0 effect, whether I am zoomed in to where I can see 2 pins, zoomed out to where I can see 50 pins or all the way zoomed out to where no pins are visible, the lag continues to be the exact same.

Am I missing something?

**Comment by Smurfj3** [comment]
Well I fixed it myself by creating a grid system that the pins go in, pins are added and removed from the MapView.Pins automatically as you pan around the map, which now lets me have over 10.000 pins with no lag. I figured this would be a feature already in Mapsui but I can't find it in the documentation. I am still curious though if there is an existing feature that removes and adds the pins maybe based on the tiles that are rendered.

**Comment by pauldendulk** [comment]
Thanks for answering the question yourself. 

Not sure why the pins are slow in this case. Usually the rendering is the bottleneck, so I do not expect removing it pin is necessary. We will need to investigate this when updating the logic for v5.
