### ISSUE TITLE
Xamarin forms. User left rotation does'nt work initialy

### ISSUE THREAD

**Issue by GaLogix** [Mapsui/Mapsui#2121]
**Mapsui Version**
4.0.0-rc.2

**Mapsui Platform**
Xamarin Forms

**Device**
Android

**Describe the bug**
User cannot rotate map to the left initaly. He must spin to the right otherwise, the map does not rotate even if ViewPort.Rotation indicates a number

**Expected behavior**
I would like the user to be able to turn in both directions initially

**Comment by gpsaliola** [comment]
Duplicate #2090

**Comment by pauldendulk** [comment]
I assume this is fixed with https://github.com/Mapsui/Mapsui/pull/2128. Please reopen if this is not fixed after the next release.
