### ISSUE TITLE
WMS Provider catch with "The SSL connection could not be established"

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#2130]
Mapsui Version
4.0.0

Mapsui Platform
Xamarin - Android

Device
Samsung A53

Describe the bug
WMSProvider catch with "The SSL connection could not be established" error with this url: 
https://depth.openseamap.org/geoserver/gebco2021/wms

To Reproduce

`            WmsProvider provider = await WmsProvider.CreateAsync("https://depth.openseamap.org/geoserver/gebco2021/wms", persistentCache: MyDefaultCache);
`

Expected behavior
WmsProvider.CreateAsync should not catch in error.
This server works fine with OpenLayers.

**Comment by inforithmics** [comment]
It is fixed in this pull request it was a missing useragent
https://github.com/Mapsui/Mapsui/pull/2134

**Comment by pauldendulk** [comment]
I assume this is fixed with the PR. If the problem persists after the next release please reopen.
