### ISSUE TITLE
The animation of the Navigator is interrupted if MyLocationFollow disabled just before it starts

### ISSUE THREAD

**Issue by anmelegov** [Mapsui/Mapsui#2132]
**Mapsui Version**
4.0.0

**Mapsui Platform**
MAUI

**Device**
Android

**Describe the bug**
The animation of the map is interrupted if MyLocationFollow disabled just before it starts

**To Reproduce**
1. enable following user location by pressing UI button
2. execute next lines:
```
MapView.MyLocationFollow = false;
MapView.Map.Navigator.CenterOnAndZoomTo(placePosition, 2D, 650U, Mapsui.Animations.Easing.SinIn);
```

**Expected behavior**
Map should scroll until it reaches the `placePosition`. Alternatively the start of the animation сould automatically disable following as it happens when you move the viewport manually

**Comment by anmelegov** [comment]
cannot reproduce

**Comment by inforithmics** [comment]
I tried it to reproduce, but I failed to do so too.

**Comment by anmelegov** [comment]
> I tried it to reproduce, but I failed to do so too.

It's reproducible on mine environment but I can't affirm that is related to MyLocationFollow. Seems that is related to initialization of the component or his parents. When I run the app, the first few animations don't play or interrupting until the component warms up. I'm using the .NET8-preview-6
