### ISSUE TITLE
The attributions of two or more maps overlap

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#2141]
Mapsui Version
4.0.0

Mapsui Platform
Xamarin - Android

Device
Samsung A53

Describe the bug
The attributions of two or more maps overlap

Expected behavior
Attributions should be concatenated like OpenLayers does for example

Screenshots
This example uses two layers:
https://mapserver.mapy.cz/turist-m/{z}-{x}-{y}
http://ows.emodnet-bathymetry.eu/wfs

![Screenshot_20230801_122849](https://github.com/Mapsui/Mapsui/assets/6804212/19a769a4-58cc-4977-b190-7b6d789c2c2c)

**Comment by inforithmics** [comment]
Could you give an example how the Attributions are concatenated. Are all Attributions concatenated or duplicates removed?

**Comment by gpsaliola** [comment]
This is an example of how OpenLayers handles attributions of two or more maps. They are concatenated. I don't know if it removes duplicates but that would be a good thing (I think for example all OSM based maps).

![image](https://github.com/Mapsui/Mapsui/assets/6804212/af4b867b-552c-48b2-bf43-3a7de434a67f)

**Comment by gpsaliola** [comment]
Thanks for the tips.
It's not an alignment issue anyway, but I think I can fix it in code.
Thank you.

**Comment by pauldendulk** [comment]
The alignment was just an example of how you can change the attribution.

**Comment by gpsaliola** [comment]
I was thinking of solving it this way.
When I define maps I store the attributions for each in an array and set the value of Attribution to empty.
When I define the last map, I concatenate all the attributions of the array and set the Attribution value of this last map to this value.

**Comment by pauldendulk** [comment]
@gpsaliola Seems like a good solution which accounts for changes in text length. Note, that it is a hyperlink and osm requires the link back to their website. So, you may want to add that too.

**Comment by gpsaliola** [comment]
Is there a way to have the Attribution field on the map with the text wrapped?

**Comment by pauldendulk** [comment]
No. For your purpose it might be better to create your own attribution widget and change it to your own needs. You could richtextkit for wrap around labels.

**Comment by gpsaliola** [comment]
Ok. Thank you!
