### ISSUE TITLE
GradientTheme Field Name  

### ISSUE THREAD

**Issue by Spe1993** [Mapsui/Mapsui#2152]
GradientTheme Class
GetStyle Method
![image](https://github.com/Mapsui/Mapsui/assets/30460939/c4f3981e-8a01-459d-b5b9-84acfbadb566)
I can not get attribute when my field name is "id" because if this ToUpper() . It make i only user "ID" as Filed name

**Comment by inforithmics** [comment]
This is certainly a Bug.
