### ISSUE TITLE
Tile map not showing (it was showing before suddenly stopped without code changes)

### ISSUE THREAD

**Issue by ClaudioM20** [Mapsui/Mapsui#2162]
I have an app that uses mapsui for .net, it was working for a while but all of the sudden without any code changes when we checked the app the tile map was not showing. Everything like map bar and stuff like that work but the tile map is blank (see attached file).

Code of the map:
```csharp
//Add a simple map
var map = new Map
{
    CRS = "EPSG:3857",
    Transformation = new MinimalTransformation()
};
var tileLayer = OpenStreetMap.CreateTileLayer();
map.Layers.Add(tileLayer);
map.Limiter= new ViewportLimiterKeepWithin();
map.Widgets.Add(new Mapsui.Widgets.ScaleBar.ScaleBarWidget(map) { TextAlignment = Mapsui.Widgets.Alignment.Center, HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Left, VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Bottom });
mapView.Map = map;



//Note in the translator the longitude comes after the latitude, its no long and lat is LAT and LONG
var cordsTranslator = SphericalMercator.FromLonLat(-0.12015019954599473,51.50716224170015);

mapView.MyLocationLayer.UpdateMyLocation(new Position(51.50716224170015, -0.12015019954599473), true);

//Navigate to a certain cord (this case to where the user is)
mapView.Map.Home = n => n.NavigateTo(new Mapsui.Geometries.Point(cordsTranslator.X, cordsTranslator.Y), map.Resolutions[11]);  //0 zoomed out-19 zoomed in


    //Add a pin to the map NOTE: the label has to come before position otherwise Exception
    var myPin = new Mapsui.UI.Forms.Pin(mapView)
    {
        Label = "Teste",
        Position = new Position(51.50716224170015, -0.12015019954599473),
        Color=Color.Goldenrod,
    };
    mapView.Pins.Add(myPin);

mapView.PinClicked += (sender, args) =>
{
    //Center on pin pin.position.longitude is latitude
    cordsTranslator = SphericalMercator.FromLonLat(args.Pin.Position.Longitude, args.Pin.Position.Latitude);
    mapView.Navigator.CenterOn(new Mapsui.Geometries.Point(cordsTranslator.X,cordsTranslator.Y));  //0 zoomed out-19 zoomed in

    //DisplayPopUp
    DisplayAlert("", $"Label:{args.Pin.Label}\n{args.Pin.Position.Latitude}\n{args.Pin.Position.Longitude}", "OK");
    args.Handled= true;
};
```

![1693821951675](https://github.com/Mapsui/Mapsui/assets/71674427/39f5a804-1eda-44b0-a7dc-8111ba9c172a)

**Comment by charlenni** [comment]
You use the OpenStreetMap. If I remember it correct, they allow a number of tile downloads for free. Then they cut the connection. Could that be the case?

**Comment by ClaudioM20** [comment]
I fixed it by getting the tile from an http request, instead of using var tileLayer = OpenStreetMap.CreateTileLayer(); i use:

`
     var attribution = new BruTile.Attribution("© OpenStreetMap contributors",
 "http://www.openstreetmap.org/copyright");
     var tileSource = new HttpTileSource(new GlobalSphericalMercator(),
"https://tile.openstreetmap.org/{z}/{x}/{y}.png",
new[] { "a", "b", "c" }, name: "OpenStreetMap",
attribution: attribution);

     var tileLayer = new TileLayer(tileSource) { Name = "Carto Light" };
`
   
You can close this request.

**Comment by pauldendulk** [comment]
I think they block the agent if you do too many requests.  There might be something in your app which could cause this. There was a bug in an older version which could cause too many requests in rare cases. You might want to consider upgrading if you are on an older version.

**Comment by luisrr1590** [comment]
I'm having the same issue using Mapsui.Forms 3.0.2....and I only request to OSM like two times a day. Suddenly, since last week the tile stopped working.

Thanks for the fix

**Comment by pauldendulk** [comment]
Then, you probably have the same problem. Openstreetmap has started to block the user agent that you are using. Check the requests with a tool like fiddler and alter the user agent in that request to see if this fixes the problem.
