### ISSUE TITLE
How to add feature to existing layer ?

### ISSUE THREAD

**Issue by TheR7angelo** [Mapsui/Mapsui#2171]
In my project creates an empty layer, without elements, and I would like to dynamically add elements to my layer without changing it.

By change I mean replace it with a new one.

How to do this knowing that the layer's element list is immutable

**Comment by pauldendulk** [comment]
In the samples the GenericCollectionLayer is used for this. You could look at the 'Add Pins' sample under 'Demo' or at any of the samples under 'Editing'.

**Comment by TheR7angelo** [comment]
Hello and thank you, this is exactly what I needed.

Is it possible to add a ProjectingProvider to manage srid projection types?

Currently I make the conventions with a separate function.

`    
using DotSpatial.Projections;
using NetTopologySuite.Geometries;

private static Geometry? ReProject(Geometry geometry, int toSrid)
    {
        if (geometry.IsEmpty || geometry.SRID.Equals(0)) return null;
        if (geometry.SRID.Equals(toSrid)) return geometry;

        var fromProj = ProjectionInfo.FromEpsgCode(geometry.SRID);
        var toProj = ProjectionInfo.FromEpsgCode(toSrid);

        var coordinates = geometry.Coordinates;
        var xy = new double[coordinates.Length * 2];
        var z = new double[coordinates.Length];

        for (int i = 0, j = 0; i < coordinates.Length; i++, j+=2)
        {
            xy[j] = coordinates[i].X;
            xy[j + 1] = coordinates[i].Y;
        }

        Reproject.ReprojectPoints(xy, z, fromProj, toProj, 0, coordinates.Length);

        for (int i = 0, j = 0; i < coordinates.Length; i++, j += 2)
        {
            coordinates[i].X = xy[j];
            coordinates[i].Y = xy[j + 1];
        }

        geometry.SRID = toSrid;

        return geometry;
    }`
