### ISSUE TITLE
OpenStreetMap tile layer gives a blank map

### ISSUE THREAD

**Issue by RobSchoenaker** [Mapsui/Mapsui#2172]
All of the sudden, my app drawn blank tiles for OSM tiles on said tile layer. This behaviour started about 3 weeks ago. When I attach a debugger and start the map view, I see errors like these:

`Could not load the file 'I18N, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'.`

`{System.IO.FileNotFoundException: Could not load the file 'I18N, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'.File name: 'I18N, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly, System.Threading.StackCrawlMark& stackMark) [0x00035] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System/AppDomain.cs:817   at System.AppDomain.Load (System.String assemblyString) [0x00002] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System/AppDomain.cs:796   at (wrapper remoting-invoke-with-check) System.AppDomain.Load(string)  at System.Reflection.Assembly.Load (System.String assemblyString) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Reflection/Assembly.cs:429   at System.Text.EncodingHelper.InvokeI18N (System.String name, System.Object[] args) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Text/EncodingHelper.cs:131 }`

And after this, a whole lot of codepage issues:

`Encoding 54936 data could not be found. Make sure you have correct international codeset assembly installed and enabled.`

`Encoding 950 data could not be found. Make sure you have correct international codeset assembly installed and enabled.`

These encodings are just 2 examples. It seems there are over 20 of these messages.

it should be noted that Bing maps work. It looks to me there may be an issue decoding the OSM tiles. Or maybe a tile server that has gone awry?

**Mapsui Version**
4.0.0 (latest) with Xamarin Forms 5.0.0.2578

**Mapsui Platform**
MapsUI with Xamarin.Forms on Android

**Device**
Android 13, but lower Android versions show the same issue.

**Describe the bug**
OpenStreamMap Tile layer shows a blank map. Any pins are drawn. The tiles just stay blank

**To Reproduce**
I do not have clear steps to reproduce. I think I am missing someting and could use any help.

**Expected behavior**
Tile should be drawn as usual - Bing maps works for example

**Screenshots**
Screenshot would not be necessary. The map just stays blank.

**Additional context**
The problem started appearing some weeks ago. Before this, the map was working fine. Users of the started complaining about white maps and more and more users have a white map now, which makes OSM not usable.
ANy help or pointers are much appreciated.

**Comment by denizz-ryzhkov** [comment]
I faced with the same issue. It works for me if create tile layer in this way TileLayer(KnownTileSources.Create()) instead OpenStreetMap.CreateTileLayer()

**Comment by pauldendulk** [comment]
The underlying problem is probably that osm blocked the user agent. I think they do this when they have seen app that abuse the service that use that agent. You should use a user agent that is unique to your app. 

Also see this issue:
https://github.com/Mapsui/Mapsui/issues/2162

Also make sure you have Mapsui logging configured:
https://mapsui.com/documentation/logging.html

You could also use a tool like fiddler to check what your request looks like.

**Comment by pauldendulk** [comment]
> I faced with the same issue. It works for me if create tile layer in this way TileLayer(KnownTileSources.Create()) instead OpenStreetMap.CreateTileLayer()

CreateTileLayer also has an optional `userAgent` parameter you could try.

**Comment by denizz-ryzhkov** [comment]
> > I faced with the same issue. It works for me if create tile layer in this way TileLayer(KnownTileSources.Create()) instead OpenStreetMap.CreateTileLayer()
> 
> CreateTileLayer also has an optional `userAgent` parameter you could try.

Yeah, it works with another agent. Thanks

**Comment by RobSchoenaker** [comment]
I will.check this. Thanks for the swift response!
