### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by danieldegroot2** [Mapsui/Mapsui#2173]
https://github.com/Mapsui/Mapsui/blob/a34cc7d73c90c855810b3035dbba1da858974381/Mapsui.Tiling/OpenStreetMap.cs#L30
https://github.com/Mapsui/Mapsui/blob/a34cc7d73c90c855810b3035dbba1da858974381/Mapsui.Tiling/OpenStreetMap.cs#L31

I would like to suggest using the now preferred https://tile.openstreetmap.org URL, see

https://github.com/openstreetmap/operations/issues/737

**Comment by pauldendulk** [comment]
Thanks, did not know about this. This is easy to fix.

**Comment by pauldendulk** [comment]
Fixed with this PR https://github.com/Mapsui/Mapsui/pull/2175
