### ISSUE TITLE
GenericCollectionLayer with ProjectingProvider

### ISSUE THREAD

**Issue by TheR7angelo** [Mapsui/Mapsui#2180]
Is it possible to add a ProjectingProvider to manage srid projection types?

Currently I make the conventions with a separate function.

```csharp
using DotSpatial.Projections;
using NetTopologySuite.Geometries;

private static Geometry? ReProject(Geometry geometry, int toSrid)
{
    if (geometry.IsEmpty || geometry.SRID.Equals(0)) return null;
    if (geometry.SRID.Equals(toSrid)) return geometry;

    var fromProj = ProjectionInfo.FromEpsgCode(geometry.SRID);
    var toProj = ProjectionInfo.FromEpsgCode(toSrid);

    var coordinates = geometry.Coordinates;
    var xy = new double[coordinates.Length * 2];
    var z = new double[coordinates.Length];

    for (int i = 0, j = 0; i < coordinates.Length; i++, j+=2)
    {
        xy[j] = coordinates[i].X;
        xy[j + 1] = coordinates[i].Y;
    }

    Reproject.ReprojectPoints(xy, z, fromProj, toProj, 0, coordinates.Length);

    for (int i = 0, j = 0; i < coordinates.Length; i++, j += 2)
    {
        coordinates[i].X = xy[j];
        coordinates[i].Y = xy[j + 1];
    }

    geometry.SRID = toSrid;

    return geometry;
}
```

**Comment by pauldendulk** [comment]
The `ProjectingProvider` internally uses an IProjection. There are two IProjection implementations in Mapsui. 

`Projection` which can only transform between epsg:3857 and epsg:4326. 

`DotSpatialProject' which is in the Mapsui.Extension package because of it's dependency on DotSpatial. This one supports a lot of different EPSGs. You can see how it is used in the ShapefileProjectionSample.

**Comment by TheR7angelo** [comment]
Good morning,

sorry I'm using a GenericCollectionLayer and I don't see the ProjectingProvider mention in it.

So I do my conversions by hand.
Did I see it wrong or does this not exist yet?

**Comment by pauldendulk** [comment]
oh, you are right. In most scenarios we use a layer with a DataSource, and you would be able to set the ProjectingProvider on that DataSource. The GenericCollectionLayer has no DataSource and holds the data in its own Feature field, so it is not possible to combine them.

**Comment by TheR7angelo** [comment]
Good morning

Okay I'm still doing the conversions by hand so thank you for your information.
