### ISSUE TITLE
When clicking the zoom button the map pans while mouse is up

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2189]
**Mapsui Version**
4.0.0-preview.1

**Mapsui Platform**
Blazor

**Device**
Chrome on Windows

**Describe the bug**
When clicking the zoom button (mouse down and then up) and then moving away from the zoom button, the map pans with the moving mouse even though the mouse is up. 

Also while the mouse is down on the zoom button and you move within the button, the map also moves. So, the problem is probably on the mouse down.

**To Reproduce**
1. Go to the Mapsui online Blazor samples
2. Select 'OpenStreetMap' under demo
3. Click on the + button.
4. Move the mouse away
5. The map pans while it should not on mouse up

**Expected behavior**
The map should not pan on mouse up

**Comment by pauldendulk** [comment]
I tested this on Avalonia as well (no other platforms apart from Blazor and Avalonia) and there is works correctly, but when stepping through the code in Avalonia I saw that in MapControlMouseMove _MouseDown was true. It did not pan because _previousMousePosition was null, but that is not how it is supposed to work in general. This is the code in Avalonia:

```csharp
        if (_mouseDown)
        {
            if (_previousMousePosition == null)
            {
                // Usually MapControlMouseLeftButton down initializes _previousMousePosition but in some
                // situations it can be null. So far I could only reproduce this in debug mode when putting
                // a breakpoint and continuing.
                return;
            }
```

Could it be there is an error in the shared HandleTouching? See the `return false` in the `else` in the code below.

@inforithmics You added the `else` in the [simplify editing widget PR](https://github.com/Mapsui/Mapsui/pull/2133/files) but it does not change the behavior (it return false already in that case), so, it looks to me like an attempt to fix exactly this problem, but you only wrote false instead of true. Could that be?

```csharp
private bool HandleTouching(MPoint position, bool leftButton, int clickCount, bool shift)
{
    var touchableWidgets = GetTouchableWidgets();
    var touchedWidgets = WidgetTouch.GetTouchedWidget(position, position, touchableWidgets);

    foreach (var widget in touchedWidgets)
    {
        if (widget is IWidgetExtended extendedWidget)
        {
            var widgetArgs = new WidgetArgs(clickCount, leftButton, shift);
            if (extendedWidget.HandleWidgetTouching(Map.Navigator, position, widgetArgs))
                return true;
        }
        else
        {
            // Handle the touched avoid duplicated touched events
            return false; // PDD says: Should this be true instead?
        }
    }

    return false;
}
```

**Comment by inforithmics** [comment]
The idea behind this is the following: There are two TouchHandling Interfaces IWidgetExtended that handles the down event Touching and the Up Event Touched. So When a Widget with IWiget is at the same position I don't handle it so that it is handled in the Touched Event (Up) Event.

But I have to see maybe this causes issues with the pan up, so returning true should still work with the IWidget Touch logic.

**Comment by inforithmics** [comment]
So I investigeted it, it is correct to return true here. But following needs to be fixed.

   ```
 private bool HandleTouchingTouched(MPoint position, bool leftButton, int clickCount, bool shift)
    {
        if (HandleTouching(position, leftButton, clickCount, shift))
        {
            return true; 
        }

        if (HandleTouched(position, leftButton, clickCount, shift))
        {
            return true; 
        }

        return false;
    }
```

to

 ```
  private bool HandleTouchingTouched(MPoint position, bool leftButton, int clickCount, bool shift)
 {
     bool result = HandleTouching(position, leftButton, clickCount, shift);

     if (HandleTouched(position, leftButton, clickCount, shift))
     {
         result = true; 
     }

     return result;
 }
```

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/2190/files
