### ISSUE TITLE
Support for MAUI Blazor Hybrid

### ISSUE THREAD

**Issue by MrZander** [Mapsui/Mapsui#2192]
I am developing a MAUI Blazor Hybrid application and would like to use Mapsui in it.  Following the quickstart guide for Mapsui.Blazor doesn't seem to work in this form.  I'm presented with `SkiaSharp currently only works on Web Assembly` in the console.

I have also attempted to include Mapsui.Maui in order to call `UseSkiaSharp(true)`, but that didn't help.

If my understanding is correct, Blazor hybrid is running in a WebView, I would assume this should work like a normal web-based Blazor project?

Not quite sure if this is a feature request or a bug report, but any feedback would be appreciated.

**Comment by MrZander** [comment]
I see.  Okay, I'll have to just make native MAUI views for these pages then.
Thanks!

**Comment by JTrotta** [comment]
So I do not understood: is it possible to use Mapsui.Blazor  ? I still have the error `SkiaSharp currently only works on Web Assembly`

**Comment by pauldendulk** [comment]
Blazor and Blazor-Hybrid are two separate things. Blazor works, as in our samples, https://mapsui.com/samples/. Blazor-Hybrid does not because of SkiaSharp limitations.

**Comment by JTrotta** [comment]
> Blazor and Blazor-Hybrid are two separate things. Blazor works, as in our samples, https://mapsui.com/samples/. Blazor-Hybrid does not because of SkiaSharp limitations.

Will it work ?

**Comment by pauldendulk** [comment]
Blazor-Hybrid does not work
