### ISSUE TITLE
Xamarin Forms - gaps between tiles when rotating map

### ISSUE THREAD

**Issue by memsom** [Mapsui/Mapsui#2195]
**Mapsui Version** 4.0

**Mapsui Platform** Android (monodroid10)

**Device** Various phones and tablets. (Google Pixel 3a/6a, Samsung S10/S2x, Samsung Galaxy Tab A6, A8 and others)

**Describe the bug**

When the map is zoomed to circa zoom level 18, the map tiles have a noticeable grid effect when rotated. This seems to happen with OSM, but also other map tile providers.

**To Reproduce**
1. Create a mobile app with a map
2. Set the map provider to be OSM (or any other online tile provider of XYZ tiles)
3. Zoom the map to the maximum zoom level
4. rotate the map (this currently only works in one direction due to other bugs in 4.0)

Your map will now have gaps between the tiles. These seem to lessen and often vanish when the map is rotated back to north.

**Expected behavior**

The map should cleanly rotate and the map tiles should not have spaces between them. The spaces are actually offsetting the geographical points and skewing the map rendering.

**Screenshots**

![image](https://github.com/Mapsui/Mapsui/assets/429330/40735126-af9d-42e1-b76e-cb6e480b5d31)

**Additional context**

**Comment by jack-day** [comment]
I'm experiencing this too. Would be great to see if this can get fixed.

**Comment by pauldendulk** [comment]
Thanks for you clear bug report. It was easy to reproduce it on WPF, rotate and zoom maximally. I've seen this before in other situations and often choose to ignore it but this is more noticeable.

**Comment by pauldendulk** [comment]
A PR was created an merged. This should be fixed in 4.1.0
