### ISSUE TITLE
Switching between the widget samples causes hyperlink and buttons samples to become unresponsive

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2208]
**Mapsui Version**
4.1.0-preview.1

**Mapsui Platform**
Tested on WPF but could be on all

**Device**
Tested on WPF but could be on all

**Describe the bug**
Switching from the Button sample to Custom Widget sample and back makes the 'click me' button become unresponsive. If you back to the Custom Widget sample and drag the map a bit and then back. It is fixed again.

**To Reproduce**
See above

**Additional context**
- Stepping through the code this it seemed the cause was a malfunction of the code in the shared MapControl pasted below. Changes in the number of widgets are not updated. This code looks like a performance optimization. Perhaps we should just iterate through all the widgets on every touch event for now. We could use `yield return` to avoid having to create a List every time. GetExtendedWidgets() seems to have the same problem.

```csharp
  private List<IWidget> GetTouchableWidgets()
  {
      if (_updateTouchableWidget != Map.Widgets.Count || _touchableWidgets == null)
      {
          _updateTouchableWidget = Map.Widgets.Count;
          _touchableWidgets = new List<IWidget>();
          var touchableWidgets = Map.GetWidgetsOfMapAndLayers().ToList();
          foreach (var widget in touchableWidgets)
          {
              if (widget is IWidgetTouchable { Touchable: false }) continue;

              _touchableWidgets.Add(widget);
          }
      }

      return _touchableWidgets;
  }
```

**Comment by pauldendulk** [comment]
@inforithmics I think this is related to the changes to touch logic that you worked. I propose to remove the optimization to fix this. Is that possible or are there other complications?

**Comment by inforithmics** [comment]
I think the culprit is here

` if (_updateTouchableWidget != Map.Widgets.Count || _touchableWidgets == null)`

if there is the same number of updateTouchableWidget and map widgets it won't update the touchable widgets.

But as you discovered this can be removed.
https://github.com/Mapsui/Mapsui/issues/2209#issuecomment-1753298739

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/2210
Tested on MAUI, Avalonia and Uno.WinUI.
