### ISSUE TITLE
MouseCoordinatesWidget does not display the mouse coordinates.

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2209]
**Mapsui Version**
4.1.0-preview.1

**Mapsui Platform**
Tested on WPF but could be on all

**Device**
Tested on WPF but could be on all

**Describe the bug**
The MouseCoordinatesWidget shows the text 'Mouse Position' and not the mouse position.

**To Reproduce**
1. Open the MouseCoordinatesWidget sample under Widgets in WPF
2. Move the mouse over the map
3. The widget still displays 'Mouse Position'.

**Additional context**
In the code of the `MouseCoordinatesWidget.HandleWidgetMoving` the coordinates are updated but this method is never called. This seems to be caused by MapControl.HandleMoving the method is GetExtendedWidgets used which only return widgets with Touchable is true.

**Comment by pauldendulk** [comment]
This other bug seems to be additional problem for the one reported here
https://github.com/Mapsui/Mapsui/issues/2208

@inforithmics Could we do with the Touchable boolean? The simplest solution would be to leave it up to the implementations. Just call them with the information if we are moving or dragging? On the other hand the boolean check will be better for performance, but if it causes enough confusion to introduce bugs it should perhaps be removed for now.

**Comment by inforithmics** [comment]
Good point, I looked at the code when I introduced it and it was for fixing a Bug when the BoxWidget would capture the mouse, But because Widget and ExtendedWidgets are handled by the same code this can be removed now. 
Should I make a Pull request for that?

**Comment by inforithmics** [comment]
I did a pull request, But I removed the touchable only for the IExtendedWidget because there it wasn't needed and caused a bug
But for IWidgets it is still needed. Because when a IWidget reacts to a Touchable Event I have to stop the evaluation in the Down event so that it can cancel the up Event.

**Comment by pauldendulk** [comment]
At the moment there is `IWidget.HandleWidgetTouched(Navigator navigator, MPoint position);` and `IExtendedWidget.HandleWidgetTouched(Navigator navigator, MPoint position, WidgetArgs args);` which looks very similar. Is there a reason for them to exist both apart from history and not wanted to break existing code?

**Comment by inforithmics** [comment]
The only reason for that is that I didn't want to break code so late into the Release. I plan to break it on the next major release.
Removing IWidget.HandleWidgetTouched(Navigator navigator, MPoint position);

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/2210
Tested on MAUI, Avalonia and Uno.WinUI.
