### ISSUE TITLE
Map does not rotate more than 360 degrees

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2220]
**Mapsui Version**
4.1.0

**Mapsui Platform**
Tested on MAUI but probably all 

**Device**
Tested on Windows but probably all 

**Describe the bug**
When clicking on the map in the rotate animation sample the map rotates 360 but stops after that.

**To Reproduce**
- Run the samples
- Select 'Animations' category
- Select 'Animated Viewport - Rotate'

**Expected behavior**
Keep rotating indefinitely.

**Comment by robloo** [comment]
Could you normalize by modulo 360? That probably wouldn't require changing hardly any code:

```csharp
double rotation = rotation % 360;
if (rotation < 0)
{
    rotation += 360;
}
```

**Comment by pauldendulk** [comment]
@robloo That would result in problems with calculating the size of rotation changes. We do this when determining if the map should 'snap' out of non-rotated mode. What is the distance between 355 degrees and 5 degrees (5 = 365 % 360)?  It also is problematic for animations. What is the shortest route if you are passing the 360? The current solution is to never intervene, and only do a % 360 if we really have to at the last moment in the renderer, but I think we do not even need it there.

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/2221
