### ISSUE TITLE
[Uno.WinUI][Wasm] Callout does not display on pin clicked

### ISSUE THREAD

**Issue by silviuo** [Mapsui/Mapsui#2234]
**Mapsui Version**
The version of the NuGet package. Or the branch in case you work with the Mapsui code base.

Mapsui.Uno.WinUI 4.1.0

**Mapsui Platform**
On which platform did you see the bug? MAUI, Blazer, Wpf, Avalonia, Uno or other?
Also tells us if you tested platforms that did not have the bug.

Only tested on Uno.WinUI

**Device**
Windows, Mac, Android, iPhone, iPad? Also tell us which OS and which version of that OS
if you think this is relevant. For some platforms the browser version might matter.

Windows 11 - Chrome, Edge, Firefox latest versions

**Describe the bug**

In a Uno app targeting .Net 7.0, on Wasm only, the Callout does not display when the associated pin is clicked.

**To Reproduce**
1. Open sample app (attached below)
2. Click on any pin
3. Notice callout does not display
![image](https://github.com/Mapsui/Mapsui/assets/10283398/5527f95e-9a10-4b00-8711-c97b212da356)

[UnoMapsuiSample.zip](https://github.com/Mapsui/Mapsui/files/13121157/UnoMapsuiSample.zip)

**Expected behavior**

Callout should display on pin clicked (as it does correctly on all platforms, except for Wasm).
![image](https://github.com/Mapsui/Mapsui/assets/10283398/954343dd-01e7-48bd-b5e0-e6c6b4507eba)

**Screenshots**

![image](https://github.com/Mapsui/Mapsui/assets/10283398/8f901efa-8eae-4ece-b768-254af7952fa5)

**Additional context**

In case it helps, in the sample app attached, you will also find commented out code that showcases what happens with an additional MyLocationLayer present: on pin clicked, the MyLocation object toggles its Enabled state once per click (the circle disappears and reappears on any pin clicked). 

You'll notice in the screenshot above that inside the MapOnInfo() method, when the Info layer clicked event is triggered, the values of the CalloutStyle object are correct, which seems to indicate that something might be broken at the graphics refresh stage. Instead of DataHasChanged(), I also tried Map.Refresh(), the result being the same.

Thank you for looking into this!

**Comment by inforithmics** [comment]
Add following to your wasm project and then it works, the reason is that harfbuzz webassembly is not loaded (is used for text).

```
<PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" VersionOverride="7.3.0" GeneratePathProperty="true" />
<NativeFileReference Include="$(PKGHarfBuzzSharp_NativeAssets_WebAssembly)\build\netstandard1.0\libHarfBuzzSharp.a\3.1.12\libHarfBuzzSharp.a" />
```

In Blazor I have added a workaround that adds this automatically in the nuget have to investigate if I can It in uno.wasm too.

**Comment by silviuo** [comment]
It worked, thank you!
Do you want to keep the issue open while you investigate adding the workaround to the nuget or should I close it?

**Comment by inforithmics** [comment]
Yes, I plan to fix this in the nuget package directly.
