### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by 345813473** [Mapsui/Mapsui#2235]
https://github.com/Mapsui/Mapsui/blame/654daac40359b4f31fe5aaf2e8898f36ae0f2ee6/Mapsui/Features/BaseFeature.cs#L25

 public virtual object? this[string key]
 {
        get => _dictionary.TryGetValue(key，out var value) ? value : null;
        set => _dictionary[key] = value;
  }

**Comment by pauldendulk** [comment]
Thanks, this is a small thing and there are many other things to look at wrt performance, but I don't see a reason not to improve this.
