### ISSUE TITLE
IntArrayExtension.IsNaturalOrder returns wrong result in .NET-Standard 2.0

### ISSUE THREAD

**Issue by der1Mac** [Mapsui/Mapsui#2253]
**Mapsui Version**
4.1.1

**Mapsui Platform**
WPF, .Net 4.8

**Device**
Windows

**Describe the bug**
I think the code in Mapsui.Extensions.IntArrayExtension:

        if (axisOrder.Length == 2 && axisOrder[0] == 1 && axisOrder[1] == 1)

should be replaced by

        if (axisOrder.Length == 2 && axisOrder[0] == 0 && axisOrder[1] == 1)

Actual version always returns false for IsNaturalOrder no matter if axisOrder is [0, 1] or [1, 0] for netstandard.

**Expected behavior**
for axisOrder [0, 1] true should be returned

Nevertheless, the project evolved very nice. Like it very much (despite not having much time for using it at the moment).

**Comment by pauldendulk** [comment]
It looks like you are right. What do you think @inforithmics?

@der1Mac I would be great if you could create a MR for this. If you do please point it to the develop/4.1 branch.

**Comment by der1Mac** [comment]
> It looks like you are right. What do you think @inforithmics?
> 
> @der1Mac I would be great if you could create a MR for this. If you do please point it to the develop/4.1 branch.

Sorry, I will not have time to do this before mid December (maybe later). I hope I can contribute even more starting from January.

**Comment by pauldendulk** [comment]
@der1Mac Thanks for the reply. In the meantime @charlenni has fixed this, so this can be closed. Everything ok! ✅
