### ISSUE TITLE
Use System.Drawing.Color instead of Mapsui.Styles.Color

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2260]
**The Problem**
Mapsui has its own Color class. The class was introduced back in the days of PocketPC and Silverlight. Back then not all platforms had System.Drawing.Color. Drawbacks:
- We need a conversion to libraries that use System.Drawing.Color, Skia.Svg. There will still be some color converters necessary, for instance when using SKColor.
- We need to maintain more code in Mapsui

**The Solution**
- Delete Mapsui.Styles.Color and use System.Drawing.Color instead. 
- Add extension methods to System.Drawing.Color so that we can keep the code mostly as it was before.

**Complications**
At this point I don't see any specific problems but there could be. Perhaps caused by the fact that System.Drawing.Color is a struct and Mapsui.Styles.Color is a class.

**Comment by charlenni** [comment]
Is System.Drawing.Color available on all platforms Mapsui runs on? If yes, it is a good idea.

**Comment by pauldendulk** [comment]
In this PR we go to NET6. By removing netstandard2.0 it now becomes possible to use System.Drawing.Color in all projects.

https://github.com/Mapsui/Mapsui/pull/2252/files

This is one of the advantages of removing old stuff.

**Comment by charlenni** [comment]
System.Drawing.Color belongs to NuGet package System.Drawing.Primitives, which contains beside Color also Point/PointF, Rectangle/RectangleF and Size/SizeF. Should they also replace MPoint and MRect?

**Comment by pauldendulk** [comment]
> System.Drawing.Color belongs to NuGet package System.Drawing.Primitives, 

With the upgrade to .NET6 we do not depend on the nuget package. System.Drawing.Color is part of .NET6 itself. So, if you want to start on this item already you need to checkout the branch which upgraded to .NET6, which is this one: https://github.com/Mapsui/Mapsui/tree/feature/cleanup. And it could only be turned into a reviewable PR after that branch is merged to master. This is a bit of a complication but possible. There are a lot of changes in this PR so it is probably not a good idea to start on todays master.

> which contains beside Color also Point/PointF, Rectangle/RectangleF and Size/SizeF. Should they also replace MPoint and MRect?

I did not think about this before, but this is what I think right now. 

MPoint and MRect are more like geometries, so it compare more to the NTS Point and BoundingBox than to PointF, so, no it should not be replaced. 

Then again, I think we have also used MPoint and MRect in our UI components, which would make less sense. So, in some cases it perhaps would make sense to replace them. If we would make such changes it should not be part of the PR. .... Although in some cases it might be closely related to the Color changes and it would make sense (nothing comes to mind yet), if so, please let me know.

**Comment by pauldendulk** [comment]
If you already started from master you could to a `git pull origin feature/cleanup` from the command line to update to the branch.

**Comment by charlenni** [comment]
No, I didn't start. First think, then work ;-)

What is the right way? Replace all MColor (Mapsui.Styles.Color) with the Color (System.Drawing.Color)? Or derive MColor from Color and let all occurrences the same?

**Comment by pauldendulk** [comment]
System.Drawing.Color is a struct, not a class, it is not possible to inherit from a struct. So, you need to replace it. Because if this difference there may be some complications in the port. If you assign a struct you make of copy of the original. Changing the original would not change the copy. Perhaps in our code base there are situations where we assume an assigned color changes with the original. We have to be aware of this.

**Comment by pauldendulk** [comment]
Keep in mind that System.Drawing.Common (so Common, not Color) is deprecated.  https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by pauldendulk** [comment]
I ported everything to System.Drawing.Color and then decided it was not the option. Some remarks about this are in the MR: https://github.com/Mapsui/Mapsui/pull/2578.

We learned from the port and improved Mapsui.Styles.Color https://github.com/Mapsui/Mapsui/pull/2593
