### ISSUE TITLE
Tile layer does not show in the samples sometimes

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2261]
**Mapsui Version**
In the branch of this PR https://github.com/Mapsui/Mapsui/pull/2252 and probably today's master, did not test, which is before 5.0.0-preview.1.

**Mapsui Platform**
Maui Android

**Device**
RealMe C2

**Describe the bug**
Sometimes I don't see the openstreetmap map in the samples, after loading another sometimes I do see it again, sometimes. If I put a break point in the debugger. I get this exception:
`An error occurred while fetching data. Exception: Cannot access a disposed object. Object name: 'AndroidMessageHandler'.`

**To Reproduce**
Run Mapsui.Samples.Maui and go through a few samples. 

**Additional context**
Looks like this bug:
https://github.com/dotnet/runtime/issues/93252

**Comment by charlenni** [comment]
Shouldn't this be solved with the 8.0.100 version we got on Nov. 14th?

**Comment by pauldendulk** [comment]
Yes it should. This PR upgrades the packages https://github.com/Mapsui/Mapsui/pull/2291. Did not test it yet.

btw, our global.json in the root still points to 7. This should be upgraded to 8. We probably also need to explicitly install 7 from the Scripts/InstallDependencies.cmd script. It currently only installs MAUI 6. And I think we need to remove MAUI 6 because it is not supported anymore.

**Comment by pauldendulk** [comment]
I assume this is fixed with the release of .NET 8.
