### ISSUE TITLE
Porting to Blazor or/and WebAssembly

### ISSUE THREAD

**Issue by YordanYanakiev** [Mapsui/Mapsui#2273]
Hello.
I am just excited with Blazor and WebAssembly, and just as an idea - it could be cool to have it the MapsUI as Web port written in C# for Blazor and/or eventually as WebAssembly.
( Skyasharp is having port now to Blazor )
Seems like Microsoft have some great plans for Blazor as complete crossplatform framework in C# (Web/Desktop/Mobiles) so.. maybe it would be cool to have the awesome maps in there as well. :)

**Comment by ryanspain** [comment]
@pauldendulk, is there any support planned for Blazor Server, or the new Blazor Web App project template?

I created a new Blazor Web App (Use the newest template) with options:
- **Interactivity type**: Auto (Server and WebAssembly)
- **Interactivity location**: Per page/component

After following the [Mapsui Blazor getting started](https://mapsui.com/documentation/getting-started-blazor.html) guide against the `.Client` project created by the template, I'm left with with type not found error during build.

```csharp
// Home.razor
@page "/"
@rendermode InteractiveWebAssembly
@using Mapsui.UI.Blazor
```

```
The type name 'UI' does not exist in the type 'Mapsui'
```
