### ISSUE TITLE
.NET 8 (Blazor) support

### ISSUE THREAD

**Issue by jirisykora83** [Mapsui/Mapsui#2304]
**The problem**
Current version does not work with last .NET 8

**The proposed solution**
Update dependencies?

**Additional context**

```
warning NU1608: Detected package version outside of dependency constraint: Mapsui.Blazor 4.1.1 requires Microsoft.AspNetCore.Components.WebAssembly (>= 7.0.5 && < 8.0.0) but version Microsoft.AspNetCore.Components.WebAssembly 8.0.0 was resolved.
NU1107
Mapsui.Blazor 4.1.1 -> Microsoft.AspNetCore.Components.Web (>= 7.0.5 && < 8.0.0).
1>Done building project "XXX.csproj" -- FAILED.
```

**Comment by p2pbsh** [comment]
As a workaround, add nuget package Microsoft.AspNetCore.Components.WebAssembly 8.0.0 to your project.

**Comment by jirisykora83** [comment]
> Microsoft.AspNetCore.Components.WebAssembly

I do not understand blazor project (which reference Mapsui,Blazor already have `Microsoft.AspNetCore.Components.WebAssembly` reference (as i think it is included by default in blazor client project)

**Comment by pauldendulk** [comment]
I can not give a lot of attention to these platform specific issues. The issue you face is caused by the upper limit we set in our nuget. It is easy to remove that limit but it still may not function. I am not sure how Blazor compatibility works. We are building with Blazor 7 and I would think you really need to build with Blazor 8 to deal with breaking changes. If so, you need to wait for Mapsui v5. 

@p2pbsh did you get Mapsui 4 to work in Blazor 8?

**Comment by p2pbsh** [comment]
@pauldendulk  Can confirm, Mapsui 4 does work in a Blazor 8 project, based on the new webapp auto rendering template.

@jirisykora83  Sorry, was a long day, gave you duff advice, install 'Microsoft.AspNetCore.Components.Web 8.0.0' nuget into your wasm client project, not 'Microsoft.AspNetCore.Components.WebAssembly'

One thing though...Mapsui works great in Blazor, thanks again @inforithmics, but have discovered if I publish the wasm client with AOT enabled, the map fails to load. I don't get any exceptions, no trim warnings during publish, nothing, AOT just seems to break something. Curious if that's a know issue or something to do with the dotnet 7 dependencies?

**Comment by jirisykora83** [comment]
> @pauldendulk Can confirm, Mapsui 4 does work in a Blazor 8 project, based on the new webapp auto rendering template.
> 
> @jirisykora83 Sorry, was a long day, gave you duff advice, install 'Microsoft.AspNetCore.Components.Web 8.0.0' nuget into your wasm client project, not 'Microsoft.AspNetCore.Components.WebAssembly'
> 
> One thing though...Mapsui works great in Blazor, thanks again @inforithmics, but have discovered if I publish the wasm client with AOT enabled, the map fails to load. I don't get any exceptions, no trim warnings during publish, nothing, AOT just seems to break something. Curious if that's a known issue or something to do with the dotnet 7 dependencies?

Thank you adding `Microsoft.AspNetCore.Components.Web` fix build. There are still some warnings but at least build works.

I do not use AOT but there was [LinkerConfig](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-8.0) not sure if it is still supported.

**Comment by jirisykora83** [comment]
> I can not give a lot of attention to these platform specific issues. The issue you face is caused by the upper limit we set in our nuget. It is easy to remove that limit but it still may not function. I am not sure how Blazor compatibility works. We are building with Blazor 7 and I would think you really need to build with Blazor 8 to deal with breaking changes. If so, you need to wait for Mapsui v5.
> 
> @p2pbsh did you get Mapsui 4 to work in Blazor 8?

Yes, I am building with (migrating to) .net 8. As for all projects we have it was just updating nuget (or wait for nuget to update if their use upper limit as for us it was just npgsql and mapsui) & change version basically. I am not too familiar with MAUI & android/ios developing but I guess there is lot more works between version. If blazor isn't priority maybe you can remove the upper limit as if it isn't working then we still have to wait for new major release anyway and if it works then it is fine.

**Comment by pauldendulk** [comment]
AOT can not be used in all situations. Mapsui has a lot of dependencies so it is likely there is something in there which is not compatible with AOT. I think this is a problem Blazor 8 as well. It would be nice if we could support AOT though.

**Comment by p2pbsh** [comment]
Ok, cheers Paul. I'm guessing there's something in there that needs reflection, which seems to be the primary crusher of aot dreams.

Hardly a high priority, but currently mapsui will happily build in aot then silently fail, not sure how to do it, but would be handy to propogate an aot compatability behaviour warning to the user like you see in the dotnet libs.

**Comment by pauldendulk** [comment]
I have not investigated AOT at all so far. Guess it is time to start to think about it, but I don't think we will support it in v5. A quick search shows we use System.Reflection in a couple of places. 

About showing an error to the user. If it writes something to the logger this would be enough for me (perhaps that already happens). We are working on ways to make the logging more visible to developers.

**Comment by p2pbsh** [comment]
dotnet AOT is a bit wild west at the moment so I imagine the migration path will be a little smoother further down the road. That said, basic dotnet performance on wasm is not particularly great, being able to AOT buys huge performance gains, so Mapsui support would be pretty cool :)

I did check on Skia out of curiosity, apparently its used in AOT on UNO, but don't quote me on that, haven't ran it personally.

**Comment by pilotshamn** [comment]
I have a quite complicated blazor component with a SKGLView and a lot of skiasharp in the code and it works in wasm AOT but no map in a mapsui component. If this can be of any help

**Comment by pauldendulk** [comment]
@pilotshamn So SkiaSharp support AOT, good. That is one requirement checked.

**Comment by inforithmics** [comment]
Pull Request to Add .NET 8 To Blazor in 4.1 Branch
https://github.com/Mapsui/Mapsui/pull/2329

**Comment by pauldendulk** [comment]
.NET 8 is now supported in v4 van v5. Work has been done on AOT. This is the issue for that https://github.com/Mapsui/Mapsui/issues/2327
