### ISSUE TITLE
Zoom and pan shows empty blank space around world map?

### ISSUE THREAD

**Issue by calicoder77** [Mapsui/Mapsui#2309]
Good day. thanks for this great project. I'm just wondering if it's possible to limit the zooming and panning to stop either when the viewport reaches the edges of the world map? It is currently possible to either zoom or pan and show the empty blank space after the map moves too far.

Thanks for any tips and help.

All the best!

**Comment by pauldendulk** [comment]
Look for the sample 'Keep Within Extent' in the 'Navigator' category.

**Comment by calicoder77** [comment]
> Look for the sample 'Keep Within Extent' in the 'Navigator' category.

That works, much appreciated thank you
