### ISSUE TITLE
[Avalonia]: Hovered-event is not available yet

### ISSUE THREAD

**Issue by timunie** [Mapsui/Mapsui#2316]
**The problem**
At the moment it is not easily possible to show a label on pointer over a pin (tooltip-like). If we had the hover event available, this would be easier to implement

**The proposed solution**
Implement an event that consumed the already available HoveredEventArgs

**Alternative solutions**
Let the users click on the label to show the info

**Additional context**
This applies to Avalonia only I believe. For WPF this event seems to be consumable.

**Comment by pauldendulk** [comment]
The hover event is problematic because you need to do a query on the data on every mouse move you do. This performs only in the simplest cases. I do not want to invest in that unless there is solution that performs properly. 

Then again it is possible to build something yourself, if you listen to the MouseMove event of the platform (Avalonia in your case) and query the data yourself, in code like this:

```csharp
protected async void OnMouseMove(MouseEventArgs e)
{
    if (e.Buttons == 1) return; 

    var mapInfo = this.mapControl.GetMapInfo(new MPoint(e.OffsetX, e.OffsetY));
    var id = (mapInfo?.Feature as MyFeatureType)?.Id;
    mapControl.Refresh();
}
```
And in SetCallout(Id) something like this:
```csharp
public bool SetCallout(int id)
{
    foreach (var f in features)
        f.CalloutEnabled = false;
    GetMyFeature(id).CalloutEnabled = true;
}
```

**Comment by pauldendulk** [comment]
Thanks for the feedback @timunie. I will close the issue now, but you can close it also if your question is answered.

**Comment by pauldendulk** [comment]
I now read you answer properly and I have to add the possible performance problem is in the MapControl.GetMapInfo call itself. Depending on which layers are IsMapInfoLayer and how many features are in those layers. Some kind of timer is indeed a good idea, even if it is just waiting 200 ms before a call to MapControl.GetMapInfo.

**Comment by timunie** [comment]
Upd: Here is the DispatcherTimer if anyone needs it. Please adjust it to your needs: 

```cs
    // -----  Map ToolTip ----------
    
    // Dispatcher Timer to not update Tooltip on every mouse move
    private DispatcherTimer? _toolTipUpdateTimer;
    // Remember current pointer position
    private Point _toolTipPosition;
    
    private void MapControl_OnPointerEntered(object? sender, PointerEventArgs e)
    {
        // Setup the timer
        _toolTipUpdateTimer ??= new DispatcherTimer(
            TimeSpan.FromMilliseconds(500), 
            DispatcherPriority.Normal,
            ToolTipTimerTick);
        
        // Start the timer
        _toolTipPosition = e.GetPosition(MapControl);
        _toolTipUpdateTimer.Start();
    }
    
    private void MapControl_OnPointerMoved(object? sender, PointerEventArgs e)
    {
        // Re-Start the timer if needed
        
        _toolTipPosition = e.GetPosition(MapControl);
        _toolTipUpdateTimer?.Start();
    }
    
    private void MapControl_OnPointerExited(object? sender, PointerEventArgs e)
    {
        _toolTipUpdateTimer?.Stop();
    }

    private void ToolTipTimerTick(object? sender, EventArgs e)
    {
        try
        {
            var info = MapControl.GetMapInfo(new MPoint(_toolTipPosition.X, _toolTipPosition.Y));

            // That logic depends on your map design, so adjust it if needed
            if (info?.Feature?["name"] is { } name && info.Style is SymbolStyle)
            {
                ToolTip.SetTip(MapControl, name);
                ToolTip.SetIsOpen(MapControl, true);
            }
            else
            {
                ToolTip.SetIsOpen(MapControl, false);
            }
        }
        catch (Exception exception)
        {
            Log.Information(exception, "Not able to open the Tooltip for the given position");
        }
        
        // Stop DispatcherTimer once the function was called once.
        _toolTipUpdateTimer?.Stop();
    }
```
