### ISSUE TITLE
Mapsui.Wpf is incompatible with System.Drawing.Common 8.0.0

### ISSUE THREAD

**Issue by edgarssults** [Mapsui/Mapsui#2324]
**Mapsui Version**
4.1.1

**Mapsui Platform**
WPF

**Device**
Windows 11

**Describe the bug**
If System.Drawing.Common is updated to 8.0.0 there is a warning in the build log about an incompatibility.
`warning NU1608: Detected package version outside of dependency constraint: Mapsui.Wpf 4.1.1 requires System.Drawing.Common (>= 7.0.0 && < 8.0.0) but version System.Drawing.Common 8.0.0 was resolved.`

**To Reproduce**
1. Reference MapsUi.Wpf 4.1.1 in project
2. Reference System.Drawing.Common 8.0.0
3. Build and check log

**Expected behavior**
There is no warning, MapsUi.Wpf supports System.Drawing.Common 8.0.0.

**Additional context**
Observed while migrating a solution to .NET 8.

**Comment by pauldendulk** [comment]
Perhaps we should just remove the upper bound in our nuget package. There will be no breaking changes in WPF going to 8

**Comment by pauldendulk** [comment]
The upper bound of System.Drawing.Common will be removed in 4.1.1-preview.2 but there might be other limitations. 
https://github.com/Mapsui/Mapsui/pull/2325

**Comment by pauldendulk** [comment]
Done with #2324
