### ISSUE TITLE
Fail in GeoTiffSample unit test

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2337]
**Mapsui Version**
Todays master

**Mapsui Platform**
A unit test

**Describe the bug**
In the unit test this error occurs now and then. I have seen it three times now:

```The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.```

Preceded by this log line 

```LogLevel: Warning Message: VectorStyleRenderer can not render feature of type 'Mapsui.Layers.RasterFeature', Layer: GeoGif```

The GeoGif feature is in GeoGif layer which is part of the GeoTiffSample.

**To Reproduce**
The Mapsui.Rendering.Tests on the build server

**Screenshots**
![image](https://github.com/Mapsui/Mapsui/assets/963462/1c89dd6a-9bdd-47b6-8f3e-4caa7ce7bd50)

**Links**
Run: https://github.com/Mapsui/Mapsui/actions/runs/7171315946/job/19526020027

**Comment by inforithmics** [comment]
I can sometimes reproduce it locally, I'm trying to fix it here.

https://github.com/Mapsui/Mapsui/pull/2340

**Comment by inforithmics** [comment]
For me it looks like a Heisenbug that occours during Symbol Rendering in RasterizedTileLayer.

**Comment by pauldendulk** [comment]
> For me it looks like a Heisenbug that occurs during Symbol Rendering in RasterizedTileLayer.

A Heisenbug usually means something is wrong with threading. Either something should be thread save, or we should not call it on multiple threads. In general I would not want to fix all problem by making everything thread save because that will make it harder to add new functionality. Perhaps we should also add monitors in our code that check if a certain class is called on multiple threads while it should not. Such a monitor should store the id of the previous thread and throw an exception if the next thread id is different. I wander if anyone every built something like that, you would think so.

**Comment by pauldendulk** [comment]
This was fixed with https://github.com/Mapsui/Mapsui/pull/2459 in 4.1.3 and a the same fix was merged to main.
