### ISSUE TITLE
Callout not always on top

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#2387]
**The problem**
If you have different features nearby each other, then the callout could be hidden behind the other features.

![grafik](https://github.com/Mapsui/Mapsui/assets/4381223/343df37c-3899-4dc3-a980-13e34d460f63)

**The proposed solution**
Callout should be always on top

**Comment by pauldendulk** [comment]
We have a hierarchy of components. With at the bottom the core components and on top components closer to the user. 

The core components should be simple and should need no add-hoc solutions for specific user scenarios. So, in the core the callout should be a style like any other style. We should not need any custom code in for instance the renderer to treat the callout in a special way. 

Those core components can be composed to the kind of things the user would need. We could supply extension methods for this (like those we worked on in and another PR). There may be other solutions for that, we have to think about that.

To make sure one type of style is always on top of another style we could use a stack of styles on the layer. This is already possible by assigning a style collection on the ILayer.Style. In this case the style collection should have two entries, the symbol itself and the callout. The renderer will first draw all symbols and next all callouts. Elsewhere I suggested to change the ILayer.Style to ILayer.Styles like we have on the IFeature. This would make this possible solution more visible.

**Comment by charlenni** [comment]
There are two types of orders. The first is regarding the different layers. They are in an ordered list and so the user could decide, where a layer is relative to another layer. Here a ZOrder isn't useful/needed. The second is the order of features inside a layer. This could be handled by order of creation (ordered list or Id) or by a special property (ZOrder) or both.

Normally, your layer with pins should be the top layer. That is already possible for users. A special case is MapView, where the users could decide to add layers by their own, while MapView has to promise, that the pin layer is always on top. If they do it by hand, they have to check this by themselves.

Next is to assure, that the pin with the callout is shown on top of all pins in this layer. This couldn't be done by a style list for all features. So each feature gets its own list of styles. The draw order of these features should be like they are created or with the ZOrder. But if one of them has a callout, then these features should be staying on top of all other features (no features is drawn on top of the callout). With the marker implementation, this should be done with a ZOrder = int.Max when callout is visible. That should work.

If the users decide to not have the marker layer as topmost layer, then they are responsible by themselves when the callout isn't visible completely.

That is the way I would handle it.

There could also be different layer collections for e.g. background, normal layer and topmost. But I think an add, insert and remove implementation for layers as LayerCollection has, should be enough.

**Comment by pauldendulk** [comment]
> There are two types of orders.

There is also the order of Styles. I think this can be useful in many scenarios. There are Styles on the ILayer and on the IFeature. The layers Styles iterator is outside the feature iterator, so in the hierarchy it is in between layer and feature. The features Styles iterator is applied after the feature iterator. So, there are four types of orders, and this is their priority:
1. Layers
2. Layer Styles
3. Features
4. Feature Styles

> Next is to assure, that the pin with the callout is shown on top of all pins in this layer. This couldn't be done by a style list for all features. So each feature gets its own list of styles.

Ah, this is a use case I did not think about. It is good to be aware of this in the current design phase. Thanks for brining it up. 

However, I don't think always has to work like this. As a user I don't think I would expect this (I have to try it out to be sure). A symbol is partially covered. I click on it to see a callout. I expect the callout to show on top of all symbols, but not necessarily a change in the symbol layer underneath. In some cases I expect some kind of selection, like a change in outline color, or a 20% increase in size. If a selection style is used it makes sense to also put the symbol on top. But still, having no selection and nothing changing in the symbols, also seems an option to me.

My idea is that this feature (putting an item on top if clicked) should be perceived as a form of showing selection. And I think it should be solved in a similar way. The way I have been doing this in the past is to use a StyleCollection with the regular style and a ThemeStyle which only returns a symbol based on the selected state. Perhaps we need to change some things in the core to make this functionality easier. One step to make this easier is to introduces ILayer.Style**s**.

**Comment by pauldendulk** [comment]
Relevant part of the VisibleFeatureIterator:

```csharp
foreach (var layerStyle in layerStyles)
{
  foreach (var feature in features)
  {
	  if (layerStyle is IThemeStyle themeStyle)
	  {
		  var stylesFromThemeStyle = themeStyle.GetStyle(feature).GetStylesToApply(viewport.Resolution);
		  foreach (var styleFromThemeStyle in stylesFromThemeStyle)
		  {
			  callback(viewport, layer, styleFromThemeStyle, feature, (float)layer.Opacity, iteration);
		  }
	  }
	  else
	  {
		  callback(viewport, layer, layerStyle, feature, (float)layer.Opacity, iteration);
	  }
  }
}
```

**Comment by charlenni** [comment]
ThemeStyle would be one possible way. I made it for Markers different. I changed the sort order, so that features with callout at the end/topmost place. With this, the feature and with it, the callout is always on top of this layer. And the layer has no style and features on this layer have two of them. One is the SVG image, one is the callout.

Do you think we need a Selected property for Markers? I don't want to make things to complicated. I even removed the possibility to add your own SVG or image to Markers. Make the code longer and more complicated. So I stopped now.

With the given implementation you could add a marker with two lines of code: in the first line you add a layer to the map, with the second line you add a marker to this layer. You could choose from one of many predefined pins, select position, color and scale. For the callout you could set title and subtitle. It is automatically shown, if you tap on the pin. But you could set also your own touched function. That's it. All this works with only Mapsui, nothing else.

**Comment by charlenni** [comment]
Regarding this problem: I would say, that it is solved by adding the function to set the sort order. That solved the problem for me.
