### ISSUE TITLE
Drawing order different to map info order

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#2389]
**Mapsui Version**
Main

**Mapsui Platform**
WPF

**Device**
Windows 10

**Describe the bug**
If you add `PointFeatures` to a `MemoryLayer` one after one, they are drawn in wrong order. The last added will be drawn last, the first added will be drawn first. The problem is, that the map info works the other way. The function is checking the last added first and the first added last. That is no problem until the features overlap. If this is the case, the feature later added is drawn below the earlier added, but gets the map info event earlier.

**To Reproduce**
See video below

**Expected behavior**
Drawing and touching should be consistent. I'm not sure, what is the idea behind drawing in this case. Should the first added feature be drawn first (as expected by touching) or should it be drawn last (then we have to change touching order).

**Screenshots**
I added a video showing the problem: 
https://github.com/Mapsui/Mapsui/assets/4381223/3b7e3360-3f49-4351-9d7d-25f9bf5435be

**Comment by charlenni** [comment]
One info I missed in the description of the video is the order of adding the markers to the map. I added first the @ marker, then the A marker and so on. Z marker was the last added one.

**Comment by charlenni** [comment]
Looked into this problem. Seems in conjunction with ConcurrentBag, which isn't an [ordered list](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1?view=net-8.0). This shouldn't be used here, because when features overlap, it isn't possible to say, which is the upper and which is the lower.

That said, we have to find something else as list for MemoryLayer.

**Comment by pauldendulk** [comment]
Is this issue now fixed with the [id sorting fix](https://github.com/Mapsui/Mapsui/pull/2404), or is there something else to fix? We could have a more general discussion about how to determine the order but lets have that here: https://github.com/Mapsui/Mapsui/issues/2421
