### ISSUE TITLE
WMS On Mobile Devices

### ISSUE THREAD

**Issue by lewis785** [Mapsui/Mapsui#239]
My current project requires using WMS to retrieve data from Geoserver; I practised doing this using a WPF. Once I was happy with how to retrieve data using the WMS provider I started working on my xamarin application and realise that the WMS provider does not exist. Is there another way of retrieving WMS using Mapsui?

**Comment by pauldendulk** [comment]
A quick note. More on this next week. BruTile has a WMS-C client, w.

**Comment by lewis785** [comment]
Will have a look at that. Thank you

**Comment by pauldendulk** [comment]
A quick note. More on this next week. BruTile has a WMS-C client, which accesses a WMS in a tiled way. There is a sample for it in Mapsui.Samples.Wpf. If you need to configure a limited number of WMSes this is a good option. If you need automatic parsing of capabilities it may need more work.

**Comment by lewis785** [comment]
Thanks for the fast response. Will have a look at the sample and use the WMS-C client.
