### ISSUE TITLE
OSM MapControl does not work in Avalonia Browser when using .NET 8

### ISSUE THREAD

**Issue by james-s-may** [Mapsui/Mapsui#2398]
**Mapsui Version**
4.1.2

**Mapsui Platform**
Avalonia
Avalonia version: 11.0.6

**Device**
Windows, Chrome

**Describe the bug**
When using .NET 8, does not work in Avalonia Browser, but works correctly in Avalonia Desktop.
Shows a blank white screen instead of the map. Resizing browser window forces a refresh and then the map appears, but no input is possible.
Works correctly when using .NET 7 for both platforms.

**To Reproduce**
1. Create a new solution using the "Avalonia Cross Platform Application (AvaloniaUI)" template
2. Add Mapsui.Avalonia package from NuGet
3. Ensure the target framework for all projects is .NET 8.0
4. Add sample code from step 3 of: https://mapsui.com/documentation/getting-started-avalonia.html
5. Rebuild solution
6. Run Browser configuration

**Comment by pauldendulk** [comment]
This is not something I will personally investigate. Perhaps @inforithmics has a thought about this. We released Mapsui 4 before .NET 8 was released, so I don't have know if this qualifies as a bug, yet it would be nice if it worked properly because most Avalonia users will user .NET 8 coming year.

**Comment by inforithmics** [comment]
I‘ll investigate it. I think adding an . Net 8 target will solve it because all Browser platforms Blazor, Uno, Avalonia need . Net 8 because the Wasm Format changes by .Net Main Version and some SkiaSharp .targets workarounds.

**Comment by charlenni** [comment]
Perfect @inforithmics. Thank you for your work.

**Comment by james-s-may** [comment]
Great, thanks @inforithmics! Being able to use WASM with .NET 8 will greatly enhance our application, so it is much appreciated.

**Comment by inforithmics** [comment]
During investigating I found out that the newest Avalonia Version needs to be referenced to work, because Avalonia had some fixes in this area done.
https://github.com/AvaloniaUI/Avalonia/pull/13312

**Comment by inforithmics** [comment]
The Sample starts up but the Map seems not to properly refresh, I have to resize the Browser window to display the initial Osm Map and changing to another sample seems to not work.

https://github.com/Mapsui/Mapsui/pull/2455

**Comment by inforithmics** [comment]
The solution was here
https://github.com/AvaloniaUI/Avalonia/issues/14065

repalce in main.js 
await dotnetRuntime.runMainAndExit with await dotnetRuntime.runMain

**Comment by james-s-may** [comment]
Amazing, thanks @inforithmics. Works great now.
