### ISSUE TITLE
Regression tests crash on GeoTiff

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2402]
**Mapsui Version**
Current main

**Mapsui Platform**
Regression tests

**Device**
github build server

**Describe the bug**
In more than 50% of the cases the build fails with an error related to geotiff.

This is part of the logging. The full log is in the link below:
```console
ReadDirectory: 
Warning, 
C:\Users\runneradmin\AppData\Local\Mapsui.Samples\example.tif: unknown field with tag 33550 (0x830e) encountered
ReadDirectory: 
Warning, 
C:\Users\runneradmin\AppData\Local\Mapsui.Samples\example.tif: unknown field with tag 33922 (0x8482) encountered
ReadDirectory: 
Warning, 
in-memory: unknown field with tag 33550 (0x830e) encountered
ReadDirectory: 
Warning, 
in-memory: unknown field with tag 33922 (0x8482) encountered
The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
```

https://github.com/Mapsui/Mapsui/actions/runs/7444661574/job/20251467790

To it seems this error started occurring after this PR (but I did not check the dates):
https://github.com/Mapsui/Mapsui/pull/2240/files

@inforithmics Is this something that you could take a look at?

**Comment by inforithmics** [comment]
When I debugged it last time error like
in-memory: unknown field with tag 33922 (0x8482) encountered happen in geotiff but don't crash it. So my guess it is another process, I'll have a look at it.

**Comment by charlenni** [comment]
I had the same feeling. If you look into the report, it has problems to draw a path for a SymbolStyle. And there is no SymbolStyle in the GeoTiff sample. 

That was the reason for PR #2403. And I couldn't reproduce it local.

**Comment by pauldendulk** [comment]
It is not impossible that the geotiff error logging has nothing to do with the failed build and something else is flaky, but I have seen this message many times and not always in combination with other errors (Although it is easy to miss something in those big build logs). So, I still suspect geotiff, also because I think to have seen an increase in failed builds after that PR I pointed to.

I have noticed when working with gitlab (and github may work similar) that certain errors during tests can fail the build while they are not real crashes. It seems the gitlab build runner gets confused by them. In a sense this is a bug in gitlab, but it is also a problem such errors appear in the build log. If there is nothing wrong there should be no error in the logs. So we resolve those problems by avoiding such errors. Those are generally improvements.

Then again, this could also be a real crash that occurs only with specific timing, and that specific timing happens to occur more often on the build server (because it is inherently different from our own machines).

**Comment by pauldendulk** [comment]
Also, I think we should not log an error it if is working correctly. It confuses me, and it will confuse everyone else that will investigate the build log in the future. Further, even if we catch the error and log it this is not correct behavior.

**Comment by charlenni** [comment]
Warnings removed by #2407.
