### ISSUE TITLE
Remove the number prefix from all our samples

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2434]
**The problem**
At some point we added a number as prefix to our sample titles. For example in "1 Single Callout". This was so that we could control the order of the samples. The samples are discovered and ordered alphabetically. If a new sample is added we have to change the prefix of the other items to place the new one in the desired place. This is a hassle and we have come to neglect it.  

**The proposed solution**
Remove the prefix number in all samples and just accept the alphabetic ordering as it is.

**Comment by charlenni** [comment]
See PR #2437
