### ISSUE TITLE
System.NullReferenceException when replacing TileLayer.

### ISSUE THREAD

**Issue by Thoronion** [Mapsui/Mapsui#2443]
**Mapsui Version**
4.1.2

**Mapsui Platform**
WinUI

**Device**
Windows 11 build 22621.3007

**Describe the bug**
In our application we need to draw approximately 100 000 polygons. We do it with a RasterizingTileLayer and an IndexedMemoryProvider which works great for performance. However, sometimes, not often, we need to replace the tile layer with a new layer. After the layer is replaced, we occasionally get a System.NullReferenceException in IndexedMemoryProvider. 

**To Reproduce**

I created a minimal example that triggers the exception every time (at least for us).

1. Clone https://github.com/Thoronion/MapsuiSandBox
2. Launch.
3. Click on the Test button to add the rasterizing layer.  
4. Click once again to replace the layer.
5. We get a System.NullReferenceException in IndexedMemoryProvider.

**Expected behavior**
Layer replaced without exception.

**Comment by pauldendulk** [comment]
Fantastic you provided a sample. I ran the sample and get an Mapsui rendering error in the console.

![image](https://github.com/Mapsui/Mapsui/assets/963462/5a6fc592-3686-472b-9672-2b2777664416)

**Comment by inforithmics** [comment]
Fixed here: Was already fixed in Main.
https://github.com/Mapsui/Mapsui/pull/2457

**Comment by pauldendulk** [comment]
This was fixed in 4.1.3.
