### ISSUE TITLE
MyLocationLayer with animation results in tiles not loading 

### ISSUE THREAD

**Issue by Thoronion** [Mapsui/Mapsui#2462]
**Mapsui Version**
4.1.2

**Mapsui Platform**
WinUI

**Device**
Windows 11 build 22621.3007

**Describe the bug**
When combining MyLocationLayer and TileLayers and using animation when calling 

```csharp
_locationLayer.UpdateMyLocation(_points[_coordinateIndex],  animated: true);
```

causes some tiles to not load as shown in the GIF below. Even after the animation is complete, I am not able to restore the correct behavior by panning and zooming. Waiting a long time does not help either.
I cannot reproduce this by disabling animations.

![demo](https://github.com/Mapsui/Mapsui/assets/18140541/5839d48b-2b05-44ff-95e3-ce7b869fe36e)

**To Reproduce**
1. Clone https://github.com/Thoronion/MapsuiSandBox
2. Check out tile_loading_bug
3. Launch
4. Wait for animation to complete (20 seconds).
5. Try panning and zooming.

**Expected behavior**
Tiles should load properly.

**Comment by pauldendulk** [comment]
>  I am not able to restore the correct behavior by panning and zooming. 

But panning and zooming does load the tiles that were previously not loaded right?

**Comment by Thoronion** [comment]
> > I am not able to restore the correct behavior by panning and zooming.
> 
> But panning and zooming does load the tiles that were previously not loaded right?

That is correct.

**Comment by Thoronion** [comment]
@pauldendulk I added som features as well in a RasterizingTileLayer. They also seem to be stuck in "blurry mode".

![polygon](https://github.com/Mapsui/Mapsui/assets/18140541/d357a764-5344-438a-9355-05abc16bfc5d)

**Comment by pauldendulk** [comment]
Thanks, the problem probably that RefreshData is not called. In Mapsui we have RefreshData and RefreshGraphics. And Refresh, which calls both. 

Do you call `myLocationLayer.UpdateMyLocation(myLocation);` in your code? If so, could you call it with animation? `myLocationLayer.UpdateMyLocation(myLocation);`.

**Comment by Thoronion** [comment]
In my app I call `myLocationLayer.UpdateMyLocation(myLocation, animated: true);` and the behavior described above happens. It looks like it is enough to call it once with animation enabled to set the RasterizingTileLayer aside. If I call  `myLocationLayer.UpdateMyLocation(myLocation, animated: false);`, all the tiles load as expected.

**Comment by pauldendulk** [comment]
Thanks for you excellent minimal reproducible example. It was easy to reproduce the bug. If I call _map.RefreshData() that fixes the problem:

```csharp
_locationLayer.UpdateMyLocation(_points[_coordinateIndex], true);
_map.RefreshData();
```

When animations are used _map.RefreshData() is supposed to be called in the final of the animation. Somehow it is not, I have to figure out why.

**Comment by pauldendulk** [comment]
Just debugged with the Mapsui code. The RefreshData in final is called but with the extent of the start of the animation instead of the end of the animation. So, not hard to fix but I have to think of the best way.

**Comment by Thoronion** [comment]
That is great news. Thank you for spending time on this.
