### ISSUE TITLE
EditingWidget redesign

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#2470]
**The problem**
The EditingWidget is not functioning properly. I think only in WPF and Blazor work correctly.

**Analysis**
I don't want to spend too much time on writing this issue, because I need more hands on coding, but here is a dump of things mentioned in [this](https://github.com/Mapsui/Mapsui/pull/2394) PR:

- On some platforms, like Eto, editing does not work at all.
- On Avalonia KeyDown/Up does not seem to be triggered in this branch (perhaps the original works correctly)
- Blazor has a more generic way to determine the key state (including shift/alt/ctrl). Perhaps this should be applied to all platforms. On the other hand, if we want to support mobile as well, we should perhaps move away from key modifiers entirely.
- All platforms have different ways to determine the key state. 
- Only WPF (not Mapsui.Wpf but WPF itself) has a global state (which seems such an obvious simple solution, but perhaps there is a good reason other platforms do not have this). 
- On the other platforms you need to determine the key modifiers by listening to events but not all events have the key modifier information, and this is why we need to store the shiftPressed state. So, we do more than our platforms do. I think we should do less.
- Avalonia 'add line' and 'add polygon'  removes the last point (this is because of a difference in the number of touch events triggered).
- The samples Edit Line, Edit Polygon do not seem to work at all.
- And a bigger thing: We have to straighten out how to work with events. The different platforms listen to different types of events and this can result in a different number of widget touch events. For instance: MouseUp/TouchUp/PointerUp (pointer or touch up), raw touch events like received from the skia control, Tapped, DoubleTapped.
- The editing can only be used properly with shift and this is not supported on many platforms.
- Why use shift specifically, many other options are imaginable. Should we send all key states if we know them?
- MAUI does not support shift although you would expect it on Windows.
- Avalonia and WPF have a different number of touch events with the same actions.
- We now have three event types up/down/moving. Down is only used in editing. Moving in editing and mouse control. Up is somewhere in between an Up and a Tap event.
- We should not have to depend specifically on the shift key. There should be some general state, and using shift is one way to set that state. Perhaps the events args should have an action which calls back to the MapControl. So, there can be a platform specific implementation of the 'special state'.
- The shift state is used for two different cases. 1. Deleting a vertex in a polygon. Perhaps it should be seen as the delete state.  2. Closing a polygon. 
- Perhaps a button can also be used to set the special state.

### Possible ways to proceed
- We use the shift key for two different things, should we split that in two methods? I now think it is easier to keep it in one and call it AlternateMode. It could have other uses as well.
- I now consider a GetAlternateMode() function which has implementations in each of the MapControls. It could use Shift if available. On mobile the EditingWidgets might need an 'Alternate Mode' button. This should be a method on the EventArgs. I should be possible to override the use of GetAlternateMode in the EditingWidget.
- An alternative to the above: Always add an 'Alternate Mode' button to the editing widget, so that it works identical on all platforms.
- I think we should not use DoubleTap because that is an other type of event which would be different to align with SingleTap+Shift in other platforms.

### No priority
My biggest concern at the moment is that getting this right takes a lot of time and I would like to focus on more fundamental priorities. We cannot ship something that has bugs. By submitting this issue people start thinking about a solution. Instead we should think about how we can 'park' this without causing user frustration. Perhaps the EditingWidget should show a 'Not fully functioning' warning on all platforms without the AlternateMode.

**Comment by inforithmics** [comment]
I agree with most points. 

I think the GetAlternateMode() would solve the Editing Problems on Mobile/Touch Platforms. 

There could be a Property that tells if the GetAlternateMode is supported in the platform and if not an Alternate Mode Button is displayed in the Editing Widget. 

Or there could be a Property For displaying the AlternateModeButton on Mobile Platforms this is initially true. If it is set to false the GetAlternateMode Function needs to be implemented when it isn't implemented it throws an exception.

**Comment by pauldendulk** [comment]
@inforithmics I have been in submarine-mode in the previous weeks, focusing on manipulation (touch and mouse) and tackling anything that got in my way. The situation has completely change to when I wrote this post initially. 

Some remarks:
- The EditingWidget should not have priority but for the work on manipulation it served as a very useful testcase. It was problematic because the old manipulation implementation was problematic. I to make the EditingWidget usable on all platforms, also with touch. 
- GetShiftState is now a method that needs to be implemented on all platforms (because it is called from the shared code, and it would not compile without). The implementation was not fixed  yet. I think we should fix it because for mouse users this is really helpful. This means we need to start tracking key state on those platforms. 
- I mention not supporting double click. Because it was entangle with platform specifics and did not function the same way on all platforms. In main there is now a TapGestureTracker which is used on all platforms. It also detects double click. And it may also implement long press. Its logic is quite isolated.
- In general I am very happy with how the manipulations turned out. We have three trackers: TapGestureTracker, FlingTracker (not really looked at that, could perhaps be improved, but it works) and the ManipulationTracker. That last one isolates a lot of previously very complicated things. Now you just call it with an array of all the contact positions, and it then calls Navigator.Manipulate with a Manipulation state parameter: `_manipulationTracker.Manipulate(positions, Map.Navigator.Manipulate);`, we do not need to distinguish between a drag and pinch mode.
- Now that double click is possible it becomes possible to use editing on mobile which makes an alternative less necessary.
- I think we should not add GetAlternateMode to the MapControl or eventArgs. If anything it should be a state in the EditingWidget itself. Actually we already have buttons used in the EditingWidget that change state, they are used in the top Editing sample that you updated for skia.
- If we implement GetShiftState it might also become logical to go all the way with the modifier keys.

**Comment by pauldendulk** [comment]
I created to new issues and will close this one.
https://github.com/Mapsui/Mapsui/issues/2575
https://github.com/Mapsui/Mapsui/issues/2576
