### ISSUE TITLE
Transparent Fill on ellipse SymbolStyle becomes white when interacting with map

### ISSUE THREAD

**Issue by trampster** [Mapsui/Mapsui#2497]
**Mapsui Version**
4.1.2

**Mapsui Platform**
Avalonia
Not tested on any other platforms

**Device**
Linux (ubuntu 20.04)

**Describe the bug**
When creating a Ellipse symbol style with transparent Fill then it work initially but as soon as you click the map the Fill Changes to white

**To Reproduce**
1. Create a SymbolStyle as follows:
```
      _transmittingStyle = new SymbolStyle() 
      { 
         Fill = new Mapsui.Styles.Brush(Mapsui.Styles.Color.Transparent), 
         SymbolScale = 1,
         SymbolType = SymbolType.Ellipse,
         Outline = new Mapsui.Styles.Pen(Mapsui.Styles.Color.Blue), 2),
      };
```
2. Create a layer with it and add a point feature
3. Notice that it displays correctly initially
4. Click on map
5. Notice that the fill becomes white

**Expected behavior**
The Fill stays transparent when I interact with the map.

**Screenshots**
Before clicking (displaying correctly):
![image](https://github.com/Mapsui/Mapsui/assets/2063633/6f687845-66a2-40ae-98d9-8370e820f0d4)

After Clicking:
![image](https://github.com/Mapsui/Mapsui/assets/2063633/bf93291a-7739-45c6-a4eb-be1fb2ffe4be)

**Comment by pauldendulk** [comment]
The white dot looks like the default SymbolStyle. Perhaps this is the default ILayer.Style, see the FAQ: https://mapsui.com/documentation/faq.html#how-can-i-get-rid-of-the-white-dots-or-black-lines.
