### ISSUE TITLE
IWidgetExtended: HandleWidgetTouched's and HandleWidgetTouching's args always the same on MAUI (eg.: ClickCount always 1)

### ISSUE THREAD

**Issue by starnutoditopo** [Mapsui/Mapsui#2520]
**Mapsui Version**
Mapsui.Maui 4.1.1
![image](https://github.com/Mapsui/Mapsui/assets/1422525/0f95f826-8a4f-4139-a91c-945444afcdf2)

**Mapsui Platform**
MAUI

**Device**
Windows

**Describe the bug**
- Create a new project as described at: https://mapsui.com/documentation/getting-started-maui.html
- Create a new widget to handle touch-related events:
  here's the MainPage's code behind:

```C#
 public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();

            var mapControl = new Mapsui.UI.Maui.MapControl();
            mapControl.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());

            mapControl.Renderer.WidgetRenders.Add(typeof(MyWidget), new EditingWidgetRenderer());
            MyWidget myWidget = new MyWidget();
            mapControl.Map.Widgets.Enqueue(myWidget);

            Content = mapControl;
        }
    }

    public class MyWidget : Widget, IWidgetExtended
    {
        public bool HandleWidgetMoving(Navigator navigator, MPoint position, WidgetArgs args)
        {            
            return false;
        }

        public override bool HandleWidgetTouched(Navigator navigator, MPoint position)
        {
            return false;
        }

        public bool HandleWidgetTouched(Navigator navigator, MPoint position, WidgetArgs args)
        {
            if (args.ClickCount > 1)
            {
                Debugger.Break();
            }
            return false;
        }

        public bool HandleWidgetTouching(Navigator navigator, MPoint position, WidgetArgs args)
        {
            if (args.ClickCount > 1)
            {
                Debugger.Break();
            }
            return false;
        }
    }
```

**To Reproduce**
- Run the code on a Windows device
- Double click on the map
- Double click is never recognized: the value of args.ClickCount in HandleWidgetTouched and HandleWidgetTouching is always 0; also args.LeftButton is always True and args.Shift is always False

**Expected behavior**
- args.ClickCount expected to mirror the number of clicks
- args.LeftButton expected to be true or false, according to the pressed button
- args.Shift  expected to be true when Shift pressed

**Comment by pauldendulk** [comment]
I am currently rewriting the touch/mouse logic for all platforms because it was hard to maintain, especially MAUI. Debugging this kind of problem is something I want to avoid. So, I will mark this as 'wont-fix'.

A possible workaround is to use a [MAUI gesture recognizer](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/tap?view=net-maui-8.0) and call `MapControl.GetMapInfo`.

**Comment by pauldendulk** [comment]
This was rewritten in 5.0.0-beta.1. There is no click count but instead a TapType which could be: Single, Double or Long. This should function correctly on all platforms, please report an issue if it does not.
