### ISSUE TITLE
MbTiles not load  An error occurred while fetching data. Exception: no such table: tiles

### ISSUE THREAD

**Issue by martyresleonardo** [Mapsui/Mapsui#2558]
**4.1.5**
[The version of the NuGet package. Or the branch in case you work with the Mapsui code base.](https://www.nuget.org/packages/Mapsui.Maui/4.1.5)

**5.0.6**
[The version of the NuGet package. Or the branch in case you work with the Brutile code base.]
https://www.nuget.org/packages/BruTile.MbTiles/5.0.6

**Mapsui Platform**
MAUI
When try to get mbtilesSource getting An error occurred while fetching data. Exception: no such table: tiles

**Device**
Android Emulator SDk33 and 34. Tablet samsung e7 and redmi note 12. 

**Describe the bug**
When try to get mbtilesSource getting An error occurred while fetching data. Exception: no such table: tiles

**To Reproduce**
```csharp
 public static ILayer CreateMbTilesLayer(string path, string name)
 {
     try
     {
         if (!File.Exists(path))
         {
             throw new FileNotFoundException("MBTiles file not found.", path);
         }
                      
         var filePath = Path.GetFullPath(Path.Combine(FileSystem.AppDataDirectory, "globalpoint.mbtiles"));
         var sqlConnection = new SQLite.SQLiteConnectionString(path, SQLiteOpenFlags.ReadOnly, true);
         var tileSource = new BruTile.MbTiles.MbTilesTileSource(sqlConnection, new GlobalSphericalMercator("png", YAxis.TMS, 15, 19, "point"), MbTilesType.BaseLayer, false);
         var tileLayer = new TileLayer(tileSource);

         return tileLayer;
     }
     catch (Exception e)
     {
         Console.WriteLine(e.ToString());
     }
     return null;
 }
```

**Expected behavior**
Access de tiles table and return images to layer.

**Screenshots**
![image](https://github.com/Mapsui/Mapsui/assets/57037282/42664363-2c32-4276-a35e-5988195b663e)

![image](https://github.com/Mapsui/Mapsui/assets/57037282/6f161393-6449-47e6-952c-6d0d843ef1d4)

How could I fix or usage?

**Comment by pauldendulk** [comment]
I ran the 'Data Formats | MBTiles' sample with a wrong file name and got: SQLite.SQLiteException: 'no such table: metadata'.

Apparently sqlite just complains about the missing table when the file does not exist.

I created a PR to fix this in BruTile: 
https://github.com/BruTile/BruTile/pull/229

You could add such a check in your own code before creating the MbTilesTileSource to be sure it exists. Next you should check what the path should be. In the samples we explicitly deploy the files to the target location. This makes it easier to run it in all platforms. Also in some cases the file may exist but your apps does not have the rights to access it.

**Comment by martyresleonardo** [comment]
Hi paul, thanks to answer.

I made a file check before create the MbTilesTileSource.

.net maui probabily cant access the file even I gave the permission on manifest. 

I´ll check this.

**Comment by pauldendulk** [comment]
The fix in BruTile was merged. Other than I think this is a app specific issue.

**Comment by martyresleonardo** [comment]
Hi Paul,

I have rewriter de download file logic and now i get this error for default world.mbtiles in the example.
![image](https://github.com/Mapsui/Mapsui/assets/57037282/d1543694-91cb-413f-ab63-6908e48c84c5)

I dont know if the problem is on .net maui or other thing.

Any ideia or issue to try?
