### ISSUE TITLE
WPF: Set background color of MapControl if no map (TileLayer) is active

### ISSUE THREAD

**Issue by EmaDozer** [Mapsui/Mapsui#2567]
Hello,

first of all, thanks for this great project!

Is it possible to change the background color (by default its white, if no map/tile layer is active) of the MapControl?

Setting the 'Background' dependency property in XAML (WPF) has no effect. 

Thank you!
Emanuel

**Comment by pauldendulk** [comment]
You can do that what Map.Background:

```csharp
var map = new Map
{
    BackColor = Color.Pink
};
```
