### ISSUE TITLE
Replacement of map.home function in 5.0 Beta

### ISSUE THREAD

**Issue by TFreudi1** [Mapsui/Mapsui#2596]
Mapsui Version 5.0 Beta 1

In the beta the function  mapView.Map.Home is not defined. What is the replacement ?

**Comment by charlenni** [comment]
You don't have to set a Map.Home function, but can use the normal Map.Navigator functions. Mapsui now saves all this calls until the control has a size and then execute them. No Map.Home function needed anymore.

**Comment by TFreudi1** [comment]
Well OK, meanwhile I also find the diskussion in the issues :-) Ok thats solved but now the beta 5 crashing on InitializeComponent(); in the mainpage long before the "ex-Home" function are called. I put the mapView in th examl like this:
 <mapsui:MapView x:Name="mapView"
                 Grid.Row ="0"
                 Grid.Column="0"
                 Grid.ColumnSpan="2"
                 IsVisible="true"
                 VerticalOptions="FillAndExpand"
                 HorizontalOptions="FillAndExpand"
                 BackgroundColor="Gray" 
                 MyLocationEnabled="True"
                 IsMyLocationButtonVisible="True"
                  />

Maybe you have also a hint for that. If not I will close this and open a new issue with code sample.

**Comment by pauldendulk** [comment]
MapView is currently not functioning and it will be made obsolete in the v5 or v6. The MapControl needs to be further improved to function as a proper alternative.
