### ISSUE TITLE
Wrong attribution link after switching map layer

### ISSUE THREAD

**Issue by giobiondani** [Mapsui/Mapsui#2599]
I am building an app where the user can change the map type, for example switching from the Bing Aerial to the OSM.
The map control has 2 layers: the map and a GPS track.

When the user wants to switch map type, I remove the old map layer and replace it with the new one.
The new layer may have a different attribution text and URL.

So this is what happens:
- open the control with Bing Aerial; the attribution is Microsoft; clicking on it opens the Microsoft website
- switch to the OSM map; the attribution is OSM; clicking on it still opens the Microsoft website

I debugged the code and I see that when the layer is replaced, both the text and the URL of the attribution are correct, so I have no idea where the issue is coming from.
Is there maybe some sort of caching that I should take into account?

**Comment by pauldendulk** [comment]
Thanks for the report. This is something we need to try to reproduce in a sample.

**Comment by giobiondani** [comment]
Thank you for the response. I can try to reproduce in a sample but I never installed them so I may not get to it very quickly.
I also decided to handle the attributions in a different way because I realized the Stadia and Thunderforest require multiple separate URL links in the same attribution and as far as I can tell I can't do that with the standard Attribution object.

**Comment by janusw** [comment]
I see the exact same problem (with Mapsui.Maui v4.1.7), but actually I only observe it on iOS, not on Android.
@giobiondani On which OS do you see this?

I will try to set up a reproducer ...

**Comment by janusw** [comment]
I strongly suspect that this problem is related to the caching of widgets (in `MapControl`), as mentioned in #2694. Layer attributions are HyperlinkWidgets after all! Looks like the caching is only updated if the number of widgets changes. In the case here, one attribution widget is replaced by a different one, so the number stays the same.

Possibly ways to fix this:
* Have a way to trigger the re-caching of widgets (which could be done manually if it is known that the widgets have changed).
* Re-cache the widgets every time the layers change (to account for new attribution widgets).

**Comment by janusw** [comment]
> I see the exact same problem (with Mapsui.Maui v4.1.7)

I also checked 4.1.8-beta.1 by now, but it seems to behave the same way :/

**Comment by janusw** [comment]
> I see the exact same problem (with Mapsui.Maui v4.1.7), but actually I only observe it on iOS, not on Android.

Actually the problem with the wrong attribution I also see on Android.

But on iOS I see additional problems with odd placement of the outdated attribution widget (it can be overlaid with other widgets etc, and does not match the placement of the visible attribution any more).

**Comment by giobiondani** [comment]
> I see the exact same problem (with Mapsui.Maui v4.1.7), but actually I only observe it on iOS, not on Android. @giobiondani On which OS do you see this?
> 
> I will try to set up a reproducer ...

In my case I found the issue on Windows

**Comment by pauldendulk** [comment]
Assuming this is fixed after [this PR](https://github.com/Mapsui/Mapsui/pull/2740) which is included in the 4.1.8 release.
