### ISSUE TITLE
In Map.DataChanged event, DataChangedEventArgs Layer name is empty. It should contains the Layer Name.

### ISSUE THREAD

**Issue by damusthe** [Mapsui/Mapsui#2636]
Hi all,

I'm using `Map.DataChanged` event to generate the `IsBusy `property in order to display the activity indicator loading over the map like :
![image](https://github.com/Mapsui/Mapsui/assets/22999826/d1d974b8-b77f-49e2-83bd-6dd2b36424c2)

The XAML view sample:
```
<Grid>
	<mapsui:MapView x:Name="mapView" Map="{Binding Map}" />
	
	<!-- MUST be on top of the Map Control -->
	<ActivityIndicator IsRunning="{Binding IsBusy}" WidthRequest="100" HeightRequest="100"/>
</Grid>	
```

The code sample is as below:
```
Mapsui.Map Map = new Mapsui.Map();
Map.DataChanged += Map_DataChanged;
...
/// <summary>
/// Map DataChanged event to generate IsBusy ViewModel for showing activity indicator
/// </summary>
/// <param name="sender"></param>
/// <param name="e"></param>
private void Map_DataChanged(object sender, Mapsui.Fetcher.DataChangedEventArgs e)
{
	if ((sender != null) && (e.LayerName == "OpenStreetMap") && (sender is ILayer))
	{
		IsBusy = ((ILayer)sender).Busy;
	}
}
```

The problem is that `IsBusy` is never updated because `e.LayerName` is not updated with the name of the layer.

These are the screnshots of the debugger:
![image](https://github.com/Mapsui/Mapsui/assets/22999826/bf95e8fe-c68a-479b-81b1-c062491e5bf4)
![image](https://github.com/Mapsui/Mapsui/assets/22999826/2da4b03a-ed84-49b4-852b-535020344e62)

`e.LayerName` should be updated?

I'm using NugGet package Mapsui.Maui v4.1.5 on Windows platform.

**Comment by pauldendulk** [comment]
Thanks for reporting this. It looks like a bug.

**Comment by pauldendulk** [comment]
Had a look at this. We could make the layer Name a mandatory parameter of the OnDataChangedEventArgs constructor. This solves a lot of problems but a complication is that it is also used in some providers. So, perhaps in those cases the providers should return another type of event args (OnProviderDataChangedEventArgs?) and the layers should create their own OnDataChangedEventArgs when they handle those events.

**Comment by damusthe** [comment]
The workaround I used is the following :
```
/// <summary>
/// Map DataChanged event to generate IsBusy ViewModel for showing activity indicator
/// </summary>
/// <param name="sender"></param>
/// <param name="e"></param>
private void Map_DataChanged(object sender, Mapsui.Fetcher.DataChangedEventArgs e)
{
	if ((sender != null) && (sender is ILayer) && ((ILayer)sender).Name == "OpenStreetMap")
	{
		IsBusy = ((ILayer)sender).Busy;
	}
}
```
I'm using the sender ILayer.Name instead of the event args.

I don't know enough Mapsui architecture, but changing DataChangedEventArgs type on context would be a problem at use.

**Comment by pauldendulk** [comment]
I fixed this in main by making the layerName constructor argument mandatory for the DataChangeEventArgs and remove use of it in non-layers. These now use an event with minimal data.
https://github.com/Mapsui/Mapsui/pull/2685

I improved this in develop/4.1 without introducing breaking changes 
https://github.com/Mapsui/Mapsui/pull/2684

**Comment by damusthe** [comment]
I tested it in **Mapsui-5.0.0-beta.4** release.
It's well working.
Thank you.
