### ISSUE TITLE
Density Coordination

### ISSUE THREAD

**Issue by wangkai942901902** [Mapsui/Mapsui#2643]
Hello, this is a really cool library. I'm using it in my WPF project, and now I have a question. One of my layers is filled with labels, and I want it to display only one label if there is any overlap.

**Comment by pauldendulk** [comment]
This is not supported through configuration. It is possible to build something like this yourself if you use a custom IProvider and filter on the labels on zoomed-out resolutions. This may not be easy.

**Comment by wangkai942901902** [comment]
Thank you for your reply. Could you provide a simple demo to solve this problem?
