### ISSUE TITLE
Map.Info eventargs return null for args.MapInfo.Feature when clicking on feature.

### ISSUE THREAD

**Issue by trampster** [Mapsui/Mapsui#2658]
**Mapsui Version**
4.1.2

**Mapsui Platform**
Avalonia Linux

**Device**
Linux Desktop ubuntu 20.04

**Describe the bug**
When clicking on a feature the _mapControl.Map.Info event has null for args.MapInfo.Feature.

**To Reproduce**
1. Create a GenericCollectionLayer with point features
2. Subscribe to _mapControl!.Map!.Info event
3. Run app and click on feature
4. Notice MapInfoEventArgs.MapInfo.Feature is null

**Expected behavior**
MapInfoEventArgs.MapInfo.Feature is the feature that was clicked on

**Additional context**
I've noticed that this works in the Altlas BitmapPath sample but not sure what the difference is. the Sample uses a MemoryLayer and not a GenericCollectionLayer, but not sure why that would matter.

**Comment by damusthe** [comment]
See related similar #2636

**Comment by trampster** [comment]
I didn't, this fixes it for me.
