### ISSUE TITLE
Shapefiles and mbtiles in .NET MAUI (Android)

### ISSUE THREAD

**Issue by franconoronha** [Mapsui/Mapsui#2668]
Is it possible to load Shapefiles and mbtiles in a .NET MAUI project for android? Didn't find any examples, so I tried a few things but nothing worked.

This is my latest attempt:
```
        public MainPage()
        {
            InitializeComponent();
            var mapControl = new MapControl();
            mapControl.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());

            var dir = FileSystem.Current.AppDataDirectory;
            //mapControl.Map?.Layers.Add(createMbTilesLayer(Path.Combine(FileSystem.AppDataDirectory, "xx.mbtiles"), "teste"));

            var path = Path.Combine(dir, "shapes.shp");
            var shapefile = new ShapeFile(path);
            var layer = new Layer("ShapeFile")
            {
                DataSource = shapefile,
                Enabled = true,
            };
            mapControl.Map?.Layers.Add(layer);
            Content = mapControl;
        }
        public static TileLayer CreateMbTilesLayer(string path, string name)
        {
            var tileSource = new MbTilesTileSource(new SQLiteConnectionString(path, true));
            return new TileLayer(tileSource) { Name = name };
        }
```
Result:
**System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'

Mbtiles is probably not setup correctly, but a Shapefile should be simple, so what am I doing wrong. The shapes.shp file in is the Resources/Raw folder and has all other necessary files (.shx, .dbj, .prj), I also tried putting it in a folder outside Resources, tried different Path functions. (as for the mbtiles, I installed the nuget packages necessary for sqlite use in maui, but it throws the same exception). edit: the mbtiles file was generated in QGIS, and I just opened in DB browser with suffix .sqlite, went through the tables and it looks right...

**Comment by charlenni** [comment]
Did you checked, if you could access the files without Mapsui with normal file functions?

**Comment by franconoronha** [comment]
I managed to access the files after copying the bundled files into the app data directory, it duplicates data but it works. I guess the other way would be downloading the files inside the app so they aren't bundled.

**Comment by charlenni** [comment]
As I thought: it is an access problem not a Mapsui problem.

Glad you found a solution.
