### ISSUE TITLE
Mapsui Maui not working in ios 17.5

### ISSUE THREAD

**Issue by iliasrogaris** [Mapsui/Mapsui#2669]
**Mapsui Version**
4.1.6

**Mapsui Platform**
MAUI

**Device**
 iPhone simulator. ios 17.5

**Describe the bug**
in all iphone simulators on the ios 17.5  the application crashes when opening the map. Until 17.2 all the simulators work fine

**Comment by inforithmics** [comment]
As far as I know iOS 17.5 support was only added recently https://github.com/dotnet/maui/issues/21057
And there was a bug with the iOS Simulator and localization. This means you have to use the latest .net Sdk and Maui workloads. `dotnet workload update`

**Comment by iliasrogaris** [comment]
> Could it be a SkiSharp problem? Could you try to make a sample project with SkiaSharp but without Mapsui if this crashes too?

The app crashes when opening the map. I dont know of it SkiaSharp problem but I have to use map because the problem occurs when opening the map, not when the app starts

**Comment by pauldendulk** [comment]
> The app crashes when opening the map. I dont know of it SkiaSharp problem but I have to use map because the problem occurs when opening the map, not when the app starts

Mapsui depends on SkiaSharp. This could still be a SkiaSharp problem, or SkiaSharp in combination with MAUI. Maybe we need an update of SkiaSharp. 

In the meantime you could try what Thomas is suggesting: 

> This means you have to use the latest .net Sdk 8.0.6 and Maui workloads. dotnet workload update

**Comment by inforithmics** [comment]
Had a look at it, a Hello World Maui App works with 17.5 But not the Mapsui Samples project, I crashes because of a Satellite Assembly that is not found for MAUI, I think there are still Bugs in the 17.5 iOS Support in Maui.

**Comment by inforithmics** [comment]
I debugged it further, on ios 17.5 the 3d accelerated rendering stopped working, so this needs an SkiaSharp update or fix or as a workround set UseGPU to false before the first control is rendered.
`MapControl.UseGPU = false;`

**Comment by iliasrogaris** [comment]
I tested with MapControl.UseGPU = false and it work fine in ios 17.5
Thank you!
