### ISSUE TITLE
Upgrade 3-> 4 / Help / Question / Viewport

### ISSUE THREAD

**Issue by johnjore** [Mapsui/Mapsui#2674]
Hi! Looking for some assistance / help with the last remaining item when upgrading from 3.x to 4.x, and it has todo with Viewport / RenderToBitmapStream.

This works fine in 3.x, (probably not the cleanest or best implementation, but it appears to work)

>   var bounds = newGPX.GetBounds();
>   var min = SphericalMercator.FromLonLat((double)bounds.maxlon, (double)bounds.minlat);
>   var max = SphericalMercator.FromLonLat((double)bounds.minlon, (double)bounds.maxlat);
> 
>   //Set location to match route/track
>   Fragment_map.mapControl.Navigator.RotateTo(0.0);
>   Fragment_map.mapControl.Navigator.NavigateTo(new BoundingBox(min, max), ScaleMethod.Fit);
> 
>   //Create viewport to match GPX list
>   var viewport = new Viewport(Fragment_map.mapControl.Viewport)
>   {
>       Width = Resources.DisplayMetrics.WidthPixels
>   };
> 
>   //Set loction to match route/ track (again)
>   var navigator = new Navigator.Navigator(Fragment_map.map, viewport);
>   navigator.RotateTo(0, 0);
>   navigator.NavigateTo(new BoundingBox(min, max), ScaleMethod.Fit);
> 
>   //Wait for each layer to complete
>   foreach (ILayer layer in Fragment_map.map.Layers)
>   {
>       while (layer.Busy)
>       {
>           System.Threading.Thread.Sleep(10);
>       }
>   }
> 
>   //Create the thumbprint
>   MemoryStream bitmap = new MapRenderer().RenderToBitmapStream(viewport, Fragment_map.map.Layers, Fragment_map.map.BackColor);
>   bitmap.Position = 0;
>   string ImageBase64String = Convert.ToBase64String(bitmap.ToArray());
> 
>   return ImageBase64String;
> 

Thumprint uses full width of screen:
<img width="527" alt="3x" src="https://github.com/Mapsui/Mapsui/assets/12951842/79c09a86-a43f-4c05-b478-f4e7e890fe10">

This is my 4.x part, that needs a little guidance:
```
var bounds = newGPX.GetBounds();
var min = SphericalMercator.FromLonLat((double)bounds.maxlon, (double)bounds.minlat);
var max = SphericalMercator.FromLonLat((double)bounds.minlon, (double)bounds.maxlat);

//Set location to match route/track
Fragment_map.mapControl?.Map.Navigator.RotateTo(0.0);
Fragment_map.mapControl?.Map.Navigator.ZoomToBox(new MRect(min.x, min.y, max.x, max.y), MBoxFit.Fit);

//Create viewport to match GPX list
var viewport = new Viewport()
{
    Width = MainActivity.wTrackRouteMap
};

//This is just a sample that does not work.
//Set loction to match route/ track and change viewport to fill available size
//Fragment_map.mapControl?.Map.Navigator.SetViewport(viewport);
//Fragment_map.mapControl?.Map.Navigator.RotateTo(0, 0);
//Fragment_map.mapControl?.Map.Navigator.ZoomToBox(new MRect(min.x, min.y, max.x, max.y), MBoxFit.Fit);

//Wait for each layer to complete
foreach (ILayer layer in Fragment_map.map.Layers)
{
    while (layer.Busy)
    {
        System.Threading.Thread.Sleep(10);
    }
}

//Create the thumbprint
MemoryStream bitmap = new MapRenderer().RenderToBitmapStream(viewport, Fragment_map.map.Layers, Fragment_map.map.BackColor);
//MemoryStream bitmap = new MapRenderer().RenderToBitmapStream(Fragment_map.map.Navigator.Viewport, Fragment_map.map.Layers, Fragment_map.map.BackColor);
bitmap.Position = 0;
string ImageBase64String = Convert.ToBase64String(bitmap.ToArray());

return ImageBase64String;
```

First part works, where it has appropriate zoom level to fit the whole course/track:
<img width="531" alt="4x" src="https://github.com/Mapsui/Mapsui/assets/12951842/e612de9a-23ea-4efc-a0b8-8bf0b80f17aa">

But the viewport part is missing to fill it out on the left/right side. All my attempts at this have so far failed, and not found the magic formula. I either get nothing, ie. blank, or just this middle part.

Any help would be appreciated!

**Comment by pauldendulk** [comment]
There may be something broken with the Busy state. What if you just wait for two seconds?

**Comment by johnjore** [comment]
Tried adding 10 second delay but no change.

However I had a brain wave and added a random Height = 1000:

```
//Create viewport to match GPX list
var viewport = new Viewport()
{
    Width = MainActivity.mContext.Resources.DisplayMetrics.WidthPixels,
    Height = 1000
};
```

A full width image is now created. This was not needed on 3.x? Or I was just lucky on 3.x?

**Comment by pauldendulk** [comment]
Yes, the Width and Height need to be set. Something probably changed in the defaults. The Viewport was entirely rewritten in v4.

I tried to not set the Height in a unit test and I get an exception, so that may also have happened within your code. Make sure to attach to the Mapsui logger https://mapsui.com/documentation/logging.html.

Perhaps the Navigator.SetViewport method should be made private because it also sets the Width and Height which should not be controlled by the user but only by the MapControl.

**Comment by johnjore** [comment]
Thanks for the info! This one can probably be closed as its "just" changed behaviour between 3.x and 4.x and it somehow is working. Will probably break in 5.x when you make the method private, but that's a future bridge to cross.

I'll add logging to my project, thanks for the link I had missed that one.

**Comment by pauldendulk** [comment]
You could use `Navigator.ZoomToBox(viewport.ToExtent())` instead

**Comment by johnjore** [comment]
Hm... Its not a drop-inn replacement. As long as I use this, it works:
`Fragment_map.mapControl?.Map.Navigator.SetViewport(viewport);`

I either get a square that does not have any of my gpx route, or just the narrow strip, missing left and right of the route when using viewport.ToExtend(). Will need more investigating to see what is going on here.
