### ISSUE TITLE
Confusion with WMTS (blank map) #question #helpneeded

### ISSUE THREAD

**Issue by canhazcodez** [Mapsui/Mapsui#2675]
Hi Guys,
I'm sorry if this has been asked before, I haven't found a previous issue after a brief search.

I am trying to load a specific layer from the https://www.ogd.stadt-zuerich.ch/mapproxy/wmts/1.0.0/WMTSCapabilities.xml wmts map.
Specifically, the "Basiskarte_Zuerich_Raster_Grau" layer.

I used the sample code, copied a wmts sample and edited the url and played around with ther EPSG (3857 seems to work although the xml doesn't mention it). I was able to show the "Stadtplan" layer, which is the TileMatrixSet ktzh, however, the other one ech0056 seems to deliver me some empty tiles.

Can someone please help me with this?

Thanks a lot for your help and sorry again, if this is the wrong place. I am just a bit at my wits end.

Cheers,
Canhazcodez
#question #helpneeded

**Comment by pauldendulk** [comment]
Some suggestions:
- Try to get it to work in QGIS so you can see if it actually works and with which settings.
- Use a tool like Fiddler so see what kind of requests are done and what the result is.
- Attach the Mapsui logger: https://mapsui.com/documentation/logging.html

**Comment by inforithmics** [comment]
Had a look with QGis at the Stadtplan Layer, what I discovered is that it works but that it is very slow and had a lot of TimeOuts in Qgis, Maybe you have to increase the Timeout and have pacience and eventually use caching for the fetched tiles.

**Comment by inforithmics** [comment]
```
 public async Task<Map> CreateMapAsync()
  {
      var map = new Map
      {
          CRS = "EPSG:2056"
      };
      map.Layers.Add(await CreateLayerAsync());
      map.Navigator.CenterOnAndZoomTo(new MPoint(2672155, 1251624), 500);
      return map;
  }

  public static async Task<ILayer> CreateLayerAsync()
  {
      var url = " https://www.ogd.stadt-zuerich.ch/mapproxy/wmts/1.0.0/WMTSCapabilities.xml";

      using var response = await (DefaultCache as IUrlPersistentCache).UrlCachedStreamAsync(url);
      var tileSources = WmtsParser.Parse(response);
      var stadtplanSource = tileSources.FirstOrDefault(t => t.Name == "Stadtplan") ?? tileSources.First();
      if (DefaultCache != null)
      {
          stadtplanSource.PersistentCache = DefaultCache;
      }

      return new TileLayer(stadtplanSource) { Name = stadtplanSource.Name };
  }
```

This works made a pull request with this as a sample
https://github.com/Mapsui/Mapsui/pull/2691

**Comment by canhazcodez** [comment]
> ```
> public async Task<Map> CreateMapAsync()
>  {
>      var map = new Map
>      {
>          CRS = "EPSG:2056"
>      };
>      map.Layers.Add(await CreateLayerAsync());
>      map.Navigator.CenterOnAndZoomTo(new MPoint(2672155, 1251624), 500);
>      return map;
>  }
> 
>  public static async Task<ILayer> CreateLayerAsync()
>  {
>      var url = " https://www.ogd.stadt-zuerich.ch/mapproxy/wmts/1.0.0/WMTSCapabilities.xml";
> 
>      using var response = await (DefaultCache as IUrlPersistentCache).UrlCachedStreamAsync(url);
>      var tileSources = WmtsParser.Parse(response);
>      var stadtplanSource = tileSources.FirstOrDefault(t => t.Name == "Stadtplan") ?? tileSources.First();
>      if (DefaultCache != null)
>      {
>          stadtplanSource.PersistentCache = DefaultCache;
>      }
> 
>      return new TileLayer(stadtplanSource) { Name = stadtplanSource.Name };
>  }
> ```
> 
> This works made a pull request with this as a sample #2691

Thank you very much for the code sample and the explanation.
My problem is that the Stadtplan layer works, while the Basiskarte_Zuerich_Raster_Grau layer doesn't.

I tried the Basiskarte_Zuerich_Raster_Grau with your code and it didn't work.

**Comment by canhazcodez** [comment]
> Some suggestions:
> 
> * Try to get it to work in QGIS so you can see if it actually works and with which settings.
> * Use a tool like Fiddler so see what kind of requests are done and what the result is.
> * Attach the Mapsui logger: https://mapsui.com/documentation/logging.html

That's a good hint. I'll have a look at what it throws back at me. Thanks.
