### ISSUE TITLE
System.Text.Json has a vulnerability in version 8.0.3

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#2706]
System.Text.Json has a vulnerability in version 8.0.3, which is used by Mapsui. Compilation isn't possible anymore. There is a new version 8.0.4 since 2024-07-09.

@inforithmics Do you think it is possible to make a new version, that removes this problem.

**Comment by inforithmics** [comment]
Pull request
https://github.com/Mapsui/Mapsui/pull/2707

**Comment by charlenni** [comment]
Thank you

**Comment by inforithmics** [comment]
Is Fixed now
