### ISSUE TITLE
[iOS][4.X.X] Recording of map touches in widgets works selectively

### ISSUE THREAD

**Issue by MateuszLas421** [Mapsui/Mapsui#2731]
**Mapsui Version**
4.1.8-beta-1/4.1.7/4.1.6 

**Mapsui Platform**
.net for iOS

**Device**
Simulators and iphone 15 

**Describe the bug**

There's an issue with registering map touches in widgets. The problem occurs on the iOS platform, for example, in EditingWidget, but also in other custom widgets. The issue does not occur on Android. It also didn't occur in version 3.X.X  (Xamarin.iOS). Only some touches are being captured. Touch capturing by MapInfo works correctly.

**To Reproduce**
1. Sample Mapsui 4.1.7
2.  Update ViewDidLoad in ViewController (Mapsui.Sample.iOS)
```
 public override void ViewDidLoad()
    {
        base.ViewDidLoad();
        var mapControl = CreateMap(View!.Bounds);
        View = mapControl;

        var test = new EditingAddLineSample();
        test.Setup(mapControl);
    }
```

3. Run  Mapsui.Sample.iOS and try touch.

**Video**

https://github.com/user-attachments/assets/f36897b0-ca96-4b39-8c5f-e1e82537d0d2

**Comment by MateuszLas421** [comment]
Update : 5.0.0-beta2 it seems to be working properly

**Comment by pauldendulk** [comment]
Thanks for you excellent bug report. This will probably not be fixed in v4. This type of touch logic had some fundamental problems that were fixed in v5. I don't think we can not fix this in v4 without doing a major rewrite.
