### ISSUE TITLE
Location pin image not appearing in 5.0.0

### ISSUE THREAD

**Issue by smathersgit** [Mapsui/Mapsui#2764]
**Mapsui Version**
5.0.0-beta 3

**Mapsui Platform**
MAUI

**Device**
Android, MAC

**Describe the bug**
I have been successfully adding a red location pin image to my mapView using Xamarin, and Maui app builds with 4.x.x versions, including the last stable 4.1.7 release. However, the pin image doesn't appear when moving to 5.0.0-beta 3. I tried experimenting with the pin Callout feature as an alternative way of achieving the same, but although CalloutType.Detail works fine, I cannot find an example of how to use the CalloutType.Image with my own location image.

            mapView.Map = map;
            mapView.Pins.Add(new Pin()
            {
                Label = "Pin Label",
                Position = groundPosition,  // In my case this is a point within the map's view 
                Type = PinType.Pin,
                Scale = 0.5f,
                Color = Xamarin.Forms.Color.Red,   // or Colors.Red with MAUI
                Transparency = 0.0f,
                RotateWithMap = true,
                IsVisible = true,
            });

`

**To Reproduce**
In my case I am using Mapsui in a with dotnet 9 Preview Maui app build, and testing on Android, and IOS emulators. I haven't tried it on a real device yet.

1. Add a pin to a mapView (as in the bug description)
2. Build with Mapsui 4.1.7 and confirm pin is visible on device
3. Repeat 1. and 2. using Mapsui 5.0.0-beta 3 and confirm pin doesn't appear

**Expected behavior**
My expectation was that the location pin would appear on Mapsui 5.x.x builds as it did previously with 4.x.x.

**Comment by inforithmics** [comment]
I could reproduce it. Will try to implement a fix

**Comment by smathersgit** [comment]
Can confirm that your suggested workaround was successful (on Android an IOS emulators), thanks!

My slightly amended version of the relevant Category Demo and Add Pin extract:
`
        Mapsui.Styles.Color colour = new Mapsui.Styles.Color(255, 0, 0);
        var layer = new GenericCollectionLayer<List<IFeature>>
        {
            Style = SymbolStyles.CreatePinStyle(fillColor: colour, symbolScale:0.5f)
        };
        mapView.Map.Layers.Add(layer);
        layer?.Features.Add(new GeometryFeature
        {
            Geometry = groundLocation.ToPoint(),           
        });
        // To notify the map that a redraw is needed.
        layer?.DataHasChanged();
`

**Comment by janusw** [comment]
@smathersgit Don't you see any error/exception when creating a pin with scale (see #2765)?

**Comment by smathersgit** [comment]
I did encounter #2765 when I was experimenting with a workaround, but only got it when using the Pin (MapView) constructor. I also found RotateWithMap to give the "sequence contains no element" error too. The suggested workaround I am now using, successfully uses scaling.

**Comment by smathersgit** [comment]
Issue confirmed as fixed by https://github.com/Mapsui/Mapsui/pull/2768 in 5.0.0-beta 5 release.
