### ISSUE TITLE
Panning/zooming questions

### ISSUE THREAD

**Issue by pcloof** [Mapsui/Mapsui#278]
Hi, I'm working on an app using Xamarin Forms, I'm testing it on a real Android device and I show a OpenStreetMap using Mapsui. I encounter problems sometimes and then I look at the source code, but I can't find the answers to all my questions, so here are a few questions, related to panning and zooming:

Question 1:
I tried to use PanMode.None and ZoomMode.None, expecting that panning and zooming is then totally disabled, but this is not the case. It seems that no restrictions are applied in this case. Does 'None' mean 'no limitations'? If so, how about the idea of renaming 'None' to 'Unlimited' and adding enum value 'None' or 'Disabled' plus its implementation. For now I have a workaround for disabling panning/zooming: I put a transparent label without text on top of the map, so that the map does not receive the touch events.

Question 2:
I tried to keep the map within given pan and zoom limits. I see the same problem as addressed in https://github.com/pauldendulk/Mapsui/issues/265: horizontal pan limits work, but the vertical limits don't. This problem still exists for me after updating Mapsui to version 1.3.0, which is from January 2, the end date of the discussion in the issue that I referenced, so I was hoping that it would work properly now, but this isn't the case for me. However, I used a different approach of setting the pan and zoom limits than in the referenced issue, namely by directly setting properties Mapsui.Map.PanLimits and Mapsui.Map.ZoomLimits on my instance of a map. The zoom scale has limitations applied, but the zoom limits are different than the values I thought I was setting. What is the correct approach for setting the pan and zoom limits, and what is the unit of measure of the MinMax values for the zoom limits?

Question 3:
In my app, I have a CarouselPage. I currently show the map on the leftmost of multiple pages in the carousel. When I swipe with my finger from left to right, then panning is applied as expected. But when I swipe from right to left, the carousel moves instead of applying panning. Do you know how to give panning priority over switching carousel pages?

**Comment by pauldendulk** [comment]
### Question 1:
Yes, None was intended a setting of the ViewportLimiter and would indicate no limit. Good to hear how you interpreted it as a new user. In the WPF MapControl there is a ZoomLocked property that behaves as interpreted None. I think it makes sens to bring that under the same enum. So I will probably follow your suggestion.

### Question 2
The resolutions are always in UnitsPerPixel. Where 'Unit' is the unit used in the map. This can be different depending on the map you use. For Spherical The unit type is based on the 'resolution' used in a tileschema. https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification. The KeepWithinExentsSampe works as expected on Android. Maybe you can take that as a starting point and turn it into the setup you want. Tell me at which step it fails. The zoom/pan limitation feature is kind of 'in progress' so this could be a bug.

### Question 3
I don't know how this should work. In WPF you could set an event to 'Handled' to indicate that it should not be handled by its parent (the CarouselPage in your case). Perhaps this could also be a general setting on the control. I don't know if Xamarin forms support this. I don't know it you could set that on the specific MapControls. I don't  know if a code modification of the Mapsui MapControls is necessary to get this working. That's a lot of don't knows. I would like to find out though.

**Comment by pauldendulk** [comment]
btw, there is also the ZoomMode.KeepWithinResolutionsAndAlwaysFillViewport option. This is to prevent the 'impossible' configuration where the top resolution will not fill the entire map (yeah, it's complicated).

**Comment by pauldendulk** [comment]
@Sebastian1989101 Could you help with question 3? It seems a more general question about handling of events in Xamarin Forms and not specifically related to Mapsui. How to prevent an event to by sent to the parent?

**Comment by Sebastian1989101** [comment]
The same issue applies to MasterDetail pages and the NavigationPanel (normally on the left side of it). The major problem there is, that there is no way to prevent the event bubbling from happening (or at least as far as I know). So you have two options. 

1. Overwrite the specific event and use some kind of internal storage to check if it should be handled right now or not. 
2. Disable the gesture on the control (this is what I use for MD pages). But there is always a down side to it too. At least for MD pages, if you disable the gesture on Android there is no way to open the NavigationPanel even with a click on the specific button. But at least the Android implementation seems to prevent the Event Bubbling so it is a non-issue there (or should be?). 

Heres is the Code I use for iOS and MD pages to disable it from happening: 
```
public override void ViewAppeared()
{
    base.ViewAppeared();

    if (Device.RuntimePlatform == Device.iOS)
    {
        switch (Application.Current.MainPage)
        {
            case MasterDetailPage masterDetailPage:
                masterDetailPage.IsGestureEnabled = false;
                break;

            case NavigationPage navigationPage when navigationPage.CurrentPage is MasterDetailPage nestedMasterDetail:
                nestedMasterDetail.IsGestureEnabled = false;
                break;
        }
    }
}
```

The overwritten method comes from MvvmCross.Forms on the MasterViewModel. So if you use it in plain Xamarin.Forms it should be placed somewhere in the MasterPage itself. In case of your CarouselPage I guess it belongs to the Page-Host(?). I'm not 100% sure how it works with CarouselPage because I did not use them yet. Maybe the very similar TabbedPage is also an option to try.

**Comment by pcloof** [comment]
Thanks for the reactions so far. Regarding question 1: after looking at the enum names I already decided that options PanMode.KeepViewportWithinExtents and ZoomMode.KeepWithinResolutionsAndAlwaysFillViewport seem a good choice. Regarding question 2: I had already assumed the unit was in meter per pixel for my case. I have to look into this a bit further, because there is a distinction between physical pixels and density independent pixels. So far I mainly use density independent pixels, which are easy to use in Xamarin Forms. Regarding question 3: I think I will look into Sebastian's first suggested option.

**Comment by pcloof** [comment]
Regarding question 2: the zoom restrictions are exactly correct now that I used density independent pixels instead of actual pixels. So I think I answered my previous question myself: resolutions are in meter per density independent pixel.

**Comment by pcloof** [comment]
Regarding question 3: after searching the internet for info about overriding gestures I concluded that it seems to be hard to override gestures, so I followed another idea that I came across. When I want to disable the carousel swipe, I remove the other pages from the carousel. I have an arrow button that re-adds the pages and then changes the page programmatically. In this way I have control over when the user can swipe. Maybe it is a hacky workaround, but its simple and works decently.

I think the only remaining point of this issue is the idea for updating the zoom and pan enums. For now I'll keep the workaround of using a transparent overlay to disable zooming and panning, but I'd like to be informed if you changed the enums in a new available NuGet package, then I will try it.

**Comment by pauldendulk** [comment]
Thanks @Sebastian1989101! 

@pcloof, okay, i'll keep this open until changed.

**Comment by pcloof** [comment]
Regarding another part of my question 2: the vertical pan limitation is still not working properly for me. I set the PanMode to KeepViewportWithinExtents and the ZoomMode to KeepWithinResolutionsAndAlwaysFillViewport. When I am zoomed in significantly, the vertical limitation works as expected. But when I'm close to my zoom-out limit (when almost or completely no horizontal panning is allowed due to the horizontal limits), the vertical limitation fails and I can pan vertically indefinitely. When I pan beyond the vertical limitation and I start zooming in again, then suddenly the view snaps back within the limits.

I tested this on my Xamarin Forms Droid project on my Android 4.1.2 phone, showing OpenStreetMap using Mapsui 1.3.1 and BruTile 1.0.2. No rotation is applied to the map, north is straight upwards.

**Comment by pauldendulk** [comment]
Perhaps this is a rounding error where the resolution can get above the max resolution and the max resolution will be ignored. I will take a look.

**Comment by pauldendulk** [comment]
The remaining point is now part of #349

**Comment by pauldendulk** [comment]
Finally renamed None to Unlimited and closing this. 💪

**Comment by jinkhera** [comment]
I am using mbtiles and I would like to the viewport to fit around the limits of the tiles. Currently you can pan beyond the map and see blank areas, how to resolve this?

**Comment by pauldendulk** [comment]
@jinkhera In 2.0 you can work with LimitingViewport. There is sample called 'keep within extents'.

**Comment by jinkhera** [comment]
@pauldendulk Is there an example where I can set the Extents of the map (in 2.0)?

**Comment by pauldendulk** [comment]
@jinkhera In the wpf sample select 'Special' in the dropdown and then 'Keep Within Extents'. It seems to be not function properly at the moment. I will investigate.

**Comment by jinkhera** [comment]
I set the propert PanExtents and it works great. (Sorry I did not see this property)
