### ISSUE TITLE
Problem with japanese characters

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#279]
When running my app with japanese language all `LabelStyle.Text` display texts changed to squares. Here is a text string: "Mapsuiは最高です". Chinese (Simplified and Traditional) and Korean are also affected. Bulgarian, Russisn and Ukrainian on the other hand work. So only asia languages seems to be affected. Does Mapsui not use UTF-8? Or is just the Font not able to display these characters? Is there a way to change the Font within Mapsui to test this?

**Comment by pauldendulk** [comment]
Found this in a quick search:
https://github.com/mono/SkiaSharp/issues/232
Did not read it thoroughly. Since Mapsui users don't have direct access to the skia canvas this might be an issue.

**Comment by Sebastian1989101** [comment]
Looks exactly as the same issue. I tried different fonts as well but without luck. The asia translation are currently in a closed alpha of my app and a user noticed this problem. At least it was never announced as a feature to add this so I can skip it on the next version if this took to much time.

**Comment by pauldendulk** [comment]
Not sure if this applies but here is a stackoverflow answer related to Japanese characters from @Sebastian1989101 https://stackoverflow.com/questions/76389602/how-to-get-sktypeface-fromfamilyname-to-return-a-font-for-japanese-korean-chin

**Comment by Sebastian1989101** [comment]
> Not sure if this applies but here is a stackoverflow answer related to Japanese characters from @Sebastian1989101 https://stackoverflow.com/questions/76389602/how-to-get-sktypeface-fromfamilyname-to-return-a-font-for-japanese-korean-chin

Yep, that’s my own reply after a bunch of thinkering with it that solved it.

**Comment by pauldendulk** [comment]
@Sebastian1989101 ah, thanks for you quick reply. So, could this issue be closed or does Mapsui need to improve something as well?

**Comment by Sebastian1989101** [comment]
I think it won’t be an issue with 4.0 anymore anyway as the code for the font loading is different when I compare it to the implementation in 3.x. However it might be useful for some folks when trying to include these languages. 

But yes, the issue can be closed. :)
