### ISSUE TITLE
It would be helpful to add a method which converts a Microsoft.Maui.Graphics.Color to a Color Mapsui.Styles.Color

### ISSUE THREAD

**Issue by damusthe** [Mapsui/Mapsui#2794]
**The problem**
It would be very convenient to convert easily a `Microsoft.Maui.Graphics.Color` to a `Color Mapsui.Styles.Color`.

**The proposed solution**
A `Color Mapsui.Styles.Color` constructor that takes in input a `Microsoft.Maui.Graphics.Color` and returnes a `Color Mapsui.Styles.Color`.

**Comment by pauldendulk** [comment]
Mapsui.Styles.Color is in the core Mapsui project and we do not want dependencies on the platforms in that project. We have a lot of platforms to maintain and want most code to be cross platform.

We already have a ToMapsui extension method that can convert MAUI color to Mapsui, that could make it easier to convert. I just made a merge request to move the extension file, but the functionality will stay the same except for a rename to it's counterpart (from ToNative to ToMaui).

**Comment by damusthe** [comment]
Thank you Paul
