### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#301]
At some point I would like to to change to license of this project to MIT. For this some things need to be done. 

- Rewrite parts of the code. I think it is not that much.
- Remove parts of the code that is inherited from other projects. I think I can find alternatives.
- Get current contributors to agree to re-license the code. 

For this last one I would like to ask the contributors to sign the CLA. The CLA can found [here](https://cla-assistant.io/Mapsui/Mapsui)

So if you would like to help us please sign. If you don't, no problem at all, we are still thankful for your contributions :)

- @charlenni
- @JoeCooper 
- @drwatson1 
- @Skymirrh
- @grudolf 
- @kwesolowski 
- @TFleury 
- @tebben 
- @smremde 
- @radderz 
- @gklamm 
- @scottdewald 
- @bertt

**Comment by scottdewald** [comment]
I'd be happy to sign it but it will have to be next week. I am out of town
in vacation right now.

Scott Dewald

**Comment by radderz** [comment]
Do you know how much of the code doesn't come from other MIT licenced code?

**Comment by pauldendulk** [comment]
@scottdewald No problem. It could take months before it is changed.

**Comment by pauldendulk** [comment]
@radderz It originates from SharpMap which is LGPL but a lot has been rewritten. 

SharpMap
- The geometries are SharpMap and need to be replaced. Perhaps with NTS.
- The symbols are SharpMap and need to be rewritten. I was thinking about something simple initially
- The basics of the Layers and Providers originates from SharpMap but the current form is Mostly Mapsui and many specific providers and layers are Mapsui. I will rewrite it. Perhaps some providers could stay as LGPL in their own repository.

Mapsui
- The fetcher and all async fetching is Mapsui
- Everything related to tiling is Mapsui
- The ArcGISDynamicLayer is Mapsui
- The Viewport is Mapsui
- All MapControls are Mapsui (SharpMap had a WinForms MapControl).

My plan is to move it step by step to a new repository:
https://github.com/Mapogee/Mapogee

**Comment by kwesolowski** [comment]
Signed.

**Comment by charlenni** [comment]
Signed.

**Comment by JoeCooper** [comment]
Signed

**Comment by Skymirrh** [comment]
Done!

**Comment by gklamm** [comment]
Signed.

**Comment by grudolf** [comment]
Me too.

**Comment by pauldendulk** [comment]
Wow, so many responses so soon. Thanks everybody!

**Comment by smremde** [comment]
Signed

**Comment by TFleury** [comment]
Done 😉

**Comment by drwatson1** [comment]
Signed

**Comment by scottdewald** [comment]
Signed

**Comment by groege** [comment]
Hi Everyone, and thank you for trying to change this library to the MIT license :)
Is there any way to guess when we'll be able to use the library for commercial purposes?
The small company I'm working at this is very critical. Until recently all apps were Windows phone apps, now you can imagine the issues that arise now that M$ killed Windows Mobile...
Thanks for any reply,
Cheers George

**Comment by charlenni** [comment]
@groege Where is your problem with using LGPL?

**Comment by groege** [comment]
Well maybe I misunderstand, but when building an App Package (iOS, Android,
UWP), the dll becomes part of that package, thus we'd have to publish our
code right? Or can we still use the lib for commercial use, without
publishing the code?

**Comment by pauldendulk** [comment]
Yes, that is the theory. In practice I don't think anyone will ask you to publish your code but if you want to play it save you have to wait for MIT. Unfortunately I can not promise anything with respect to the progress. The plan is to do some further refactoring on 2.0 and after it's release we can start to think about replacing Mapsui.Geometries with NTS and then MIT is in sight.

**Comment by groege** [comment]
Ok, thank you!
The thing is we kind of have to play it safe since our company has been
sued before because of moronic reasons...
That's why I thought we might be able to start developing with mapsui and
hopefully the lib would be MIT before we release it.
So I guess we'll start with the non map features first and hopefully we'll
be able to switch to mapsui by then (or at least there will be progress
towards it so that it's reasonable to start implementing the map features
by then) :)
Cheers!

**Comment by charlenni** [comment]
NTS uses [GeoAPI](https://github.com/NetTopologySuite/GeoAPI) and GeoAPI is under LGPL. So I see not, how using NTS makes things better.

**Comment by charlenni** [comment]
[Here](http://answers.google.com/answers/threadview/id/439136.html) is a good answer to this theme.

**Comment by pauldendulk** [comment]
NTS was ported from JTS. JTS has changed it's license. NTS and GeoAPI will follow. At least that was my assumption but I read here GeoAPI.Coordinates will stay LGPL https://github.com/NetTopologySuite/NetTopologySuite/issues/196#issuecomment-384953899
That is a problem.

**Comment by dotMorten** [comment]
Just in good order, I signed the CLA wrt to my parts of SharpMap, and allow all non-derived works in SharpMap that I built to be re-licensed under MIT (Just note that there might be pieces of SharpMap that's derived from other works, but those parts should be called out in the individual files)

**Comment by pauldendulk** [comment]
With the original SharpMap author Morten also signing the CLA it becomes feasible to make the move to MIT. So I am looking for what else needs to be done. 

We forked SharpMap on 2012-01-24.
![image](https://user-images.githubusercontent.com/963462/87511889-628bef80-c676-11ea-8421-5c9745c1afa8.png)

The SharpMap repository contains history from 2006-09-12. That is quite a while back. It may miss some history before that, but I assume that is Morten's. The SharpMap copyright notices are from 2005 and 2006.
![image](https://user-images.githubusercontent.com/963462/87515267-e3011f00-c67b-11ea-9616-ab908899b8f6.png)

This makes it possible to track down possible other contributors.

**Comment by pauldendulk** [comment]
I search the Mapsui repository to see what needs to be done.
- Currently there are 54 files with the 'This file is part of SharpMap' header. 
- 10 of those are originally mine, with a Paul den Dulk copyright notice, also I can remember creating them. 44 left.
- 1 is by Scott Dewald who signed the CLA. 43 left
- 22 are in the Mapsui.Geometries project. They will be replaced by NTS. There will probably be e few things that will not come from NTS, we have to create our own. For example, Point. I think we should have our own, I want to keep the dependency on NTS somewhat Isolated. It should be possible to use TileLayer without a NTS dependency. 21 left.

For those 21 files I will get the committers from the period before our fork and try to reach them or remove their code.

**Comment by pauldendulk** [comment]
A follow up on this message posted more than four years ago:

> SharpMap
> 
> * The geometries are SharpMap and need to be replaced. Perhaps with NTS.
These have now been replace with NTS in master. 

> * The symbols are SharpMap and need to be rewritten. I was thinking about something simple initially
This is not necessary anymore since Morten Nielsen signed the CLA

> * The basics of the Layers and Providers originates from SharpMap but the current form is Mostly Mapsui and many specific providers and layers are Mapsui. I will rewrite it. Perhaps some providers could stay as LGPL in their own repository.
This is not necessary anymore since Morten Nielsen signed the CLA.

**Comment by dotMorten** [comment]
Yes by all means move the SharpMap stuff to MIT. I have no clue what I was thinking choosing LGPL back then 😬

**Comment by pauldendulk** [comment]
@dotMorten ah! Four years since my last update, but you respond within two minutes 😄. Thanks for the encouragement. I am actually deleting the old LGPL SharpMap license headers from the .cs files right now.

**Comment by pauldendulk** [comment]
> For those 21 files I will get the committers from the period before our fork and try to reach them or remove their code.

Went through all the file history before 2012-01-25 (date of the fork) in the SharpMap repository. As far as I can see back all contributor have signed the CLA except for 'cairn' who I could not contact. He changes just a few lines in SharpFile.cs. Also codekaizen reorganized the structure. A bit unclear how to deal with that. Currently our project structure is completely different.

In those days almost no projects had a CLA. We could also assume that all contributors implicitly handed their copyright to the project owner.

**Comment by pauldendulk** [comment]
As a final checkup I went through all code. Above I already dealt with the code in core that came from SharpMap. Most of the code was added as part of Mapsui, the renderer, tiling, asynchronous data fetching, all the UI platforms. Some of the samples have older code but that is also Mortens. 

I don't see anything that needs further changes.

**Comment by pauldendulk** [comment]
I will add a LICENSE file (without extension, which is the default if you add the MIT license through github) and set the copyright to the The Mapsui authors, apparently you can do that [see](https://opensource.stackexchange.com/a/4970/10247). With the Mapsui authors I consider everyone who contributed to Mapsui, either as member of Mapsui, SharpMap or as contributor.

**Comment by pauldendulk** [comment]
Created a PR https://github.com/Mapsui/Mapsui/pull/1476. Have to go over it once more, but this is what I can do today.

**Comment by geoimpact** [comment]
Signed

**Comment by pauldendulk** [comment]
@geoimpact Thank you very much. Note to all, geoImpact signs for Peter Robineu who developed the WFS functionality (long ago). I discovered his name was still missing from the CLA this week. I will merge this now.

**Comment by dotMorten** [comment]
PR looks good to me, since each forked file continues crediting all the different people this builds upon.

**Comment by pauldendulk** [comment]
@dotMorten Thanks for the feedback. And you signing the CLA made a huge difference in the amount of work we had to do, thanks again!

**Comment by dotMorten** [comment]
My pleasure. Crazy to think some of this code that I started almost 20 years ago still lives on today.

**Comment by FObermaier** [comment]
Good solution.

**Comment by pauldendulk** [comment]
This was implemented in 4.0.0.
