### ISSUE TITLE
Zoom/Pan animation and Fling/Flick guestures

### ISSUE THREAD

**Issue by radderz** [Mapsui/Mapsui#306]
Hi Guys,

This is an enhancement that I'd like to know if anyone would like to have as a setting/option.

I have built zoom/pan animation with acceleration UWP/Droid/iOS, I have also added "fling/flick" type deceleration. I did this in xamarin.forms using their Animation system but it shouldn't be a big deal to port that back to native since they have open source code which could be used as a guide.

I guess the question would be, is this a desired feature or would others prefer to do this on their own? Most Map tools include things like double click zoom/animation and fling type guestures. Assuming we leave it as an option feature of the map controls then I can't see a negative in including this in the Mapsui project. The way I wrote the fling/double click zoom it is similar to how I did the MapControl interations where it converts to non-native values and then uses shared code. Double click zooms about the point that you double click.

This could then be animated on 16ms ticks with a variety of different types of acceleration, i.e sin in sin out which is good for center point changes where it will accelerate till the half way point then decelerate to stop at the new center. Zoom is just be linear (but could be a setting), similar to the WPF scroll zoom. I have found this makes the map interaction feel much more natural, especially with the fling/deceleration. It just gets complicated to make them all settings rather than just included as it'd be a fair bit of if/else ifs etc to get the right combination based on the settings. I have found a weakness to the animation when MANY (i.e 1000+) bitmap symbols are on the map, but having this enabled/disabled will give the user the option.

There are some rules with the interactions that I have followed
- New touches cancel all animations
- All new animations cancel all other animations (i.e selecting a new center while a zoom or new center animation is going will cancel the other animations and start anew as the new animation.)

Cheers

**Comment by charlenni** [comment]
I would like it. All things, that Mapsui bring in direction of a complete map api would be very good.

**Comment by pauldendulk** [comment]
Sorry for my late reply.

Yes this is a great feature to have. I have some experience with this myself and it is something that can have a lot of nasty edge cases. The two rules you mention at the end are exactly the kind of rules to can help to keep it simple and prevent these edge cases.

My experience was that it better to do the animation at the level of the Mapsui renderer, and not at the level of the UI framework (which might seem attractive because it often has some animation functionality built in).

I used a cubiceaseout for feature animations:
https://github.com/pauldendulk/Mapsui/blob/41a20c5e80ea038efec47a0f19154a282cde1821/Mapsui/Layers/AnimatedFeatures.cs#L13
If could add a number of easing functions that could be used for various purposes. Also zooming from one polygon to another could benifit from a nice animation.


First we should have the shared project set up, no?

**Comment by charlenni** [comment]
I started in my fork with the shared project. It works. You need only to add an <import> to the project files.

Btw. I started today to add SVG for markers. Works good. Could even change the color on the fly. Would be nice to have this as SymboleStyle :)

**Comment by pauldendulk** [comment]
oh SVG markers is a great feature! Do you use the skia support for SVG?

**Comment by radderz** [comment]
I have already done SVGs using Skia, I just render them to bitmaps first and then use the bitmapids with the symbol style. SVG in skia a little unreliable as it doesn't support much of the SVG standards and I have had to do a fair number of preprocessing of SVGs to make them work well. I did this so I could change colors, and sizes from a single file.

The only thing I had to do after that was manage the bitmapids so that I reused the bitmaps rather than regenerating them based on the color replacements, sizes, scale etc.

**Comment by charlenni** [comment]
Yes. 10 lines of code :)

And sorry, no WPF implementation. Perhaps we could do this later. Up to now, it is only in the Forms part.

**Comment by radderz** [comment]
How did you do the SVG Marker specifically? Do you have a link? As it would be good to natively draw the SVG rather than store a bitmap but I'd be worried about the performance side of it if it isn't caching the resulting bitmap. I am sure I'll still need to clean the SVGs alot to make them work but thats a one off thing.

**Comment by radderz** [comment]
Skia could be used for WPF by just using SVG to bitmap even for the XAML renderer as the code to make the SVG into a bitmap from an SVG wouldn't change anything. It'd just require Skia as part of the build even though its not the main renderer.

**Comment by charlenni** [comment]
You should have the [link](https://github.com/charlenni/Mapsui/tree/Forms). It is in my Mapsui repository in the branch Forms. You could find the code in [Pin.cs](https://github.com/charlenni/Mapsui/blob/Forms/Mapsui.UI.Forms/Objects/Pin.cs). There are although samples for the Forms part. There you could test it. Each time you tap on the map, you set a new marker.

**Comment by charlenni** [comment]
And yes, up to now, I convert the SVG to a bitmap. This is stored in the BitmapRegistry.

**Comment by charlenni** [comment]
For cleaning, you could find online optimizer. Work perfect. But be careful, the Skia implementation is only a subset.

**Comment by radderz** [comment]
Yes the I have used SVGO for optimisation, but even then it doesn't work if you don't take out the x and y in favour of the viewport etc. I have written some cleaning code which is outside the scope of mapsui for this purpose.

**Comment by charlenni** [comment]
I used [SVGOMG](https://jakearchibald.github.io/svgomg/), but asume, that it is the same.

I don't understand, what you mean with x and y.

**Comment by charlenni** [comment]
Funny thing to have the tiger as marker image :)

![screenshot_20180214-131921 1](https://user-images.githubusercontent.com/4381223/36204071-124e02ae-118a-11e8-99b8-6b9222605a4a.png)

**Comment by charlenni** [comment]
Would it be helpful to have an extra SymbolSyle for SVG?

**Comment by pauldendulk** [comment]
Next to bitmap and the built in ones?

**Comment by charlenni** [comment]
First I thought, that this would be a good idea. Now I‘m not longer sure. Perhaps the bitmap is enough. It depends, if we draw the SVG each time or if we create a bitmap from it and use this for drawing.

**Comment by pauldendulk** [comment]
For performance we probably want to rasterize but if you have symbols that differ in scale vectors are nicer. Maybe it should be optional.

Initially my idea was to have two options, vector and bitmap symbols. SVG would then parse towards the vector type. It seems however that skia has specific functionality to draw SVG, so perhaps there would be a place for a separate SVG type.

**Comment by radderz** [comment]
Possible an SVG layer? which could then follow the zoom level, i.e image overlays that map to the world coordinates.

**Comment by charlenni** [comment]
I checked this today. Added SVG to PointRender for Skia. Works, but I have some problems with the hover events ;).

I check this tomorrow and, if it works, will make a PR.

**Comment by charlenni** [comment]
This is still open, but I assume it is solved. We now have fling.
