### ISSUE TITLE
InfoEvent NumTaps different behaviour between iOS and Android (1.3.2-beta4)

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#312]
I guess it would be better to have the same behavoir accross multiple platforms. Otherwise each developer needs a custom implementation per platform which made it hard to reuse as much code as possible. 

Behaviour on iOS: 
InfoEvent is called for each tap on a feature. The NumTaps parameter is always 1 there. 

Behaviour on Android: 
InfoEvent is called once with NumTaps set to the number of taps to a specific icon. If the number of taps > 2 the event is called multiple times.

Behaviour on UWP / WPF:
- not tested -

**Comment by radderz** [comment]
They are supposed to have the same behaviour on all the platforms (WPF is lacking though as there is no click or guestures so I'll get to that manually when I have time).

So what you are saying is the infoevent calls the the NumTaps with 1 every tap, so a double tap would send through NumTaps 1 twice?

**Comment by Sebastian1989101** [comment]
@radderz yes. On iOS the InfoEvent comes in twice (each time with NumTaps 1) and on Android it comes as expected as double or single tap.

**Comment by radderz** [comment]
@Sebastian1989101 - this works in the version that I did a pull request for, it does a single tap if there is a single tap and a single double tap if its a double tap. However a triple tap invokes the single tap after the double.

**Comment by radderz** [comment]
That might be due to it missing a change in beta 4 where I added must fail for gesture of the double click which has already been pulled into the code but may not have made it in time for beta 4, I am not sure what commit beta4 was up to.

https://github.com/pauldendulk/Mapsui/blob/b48ed0753839f84d2aebb38e6ee533c6decbc095/Mapsui.UI.iOS/MapControl.cs#L70

**Comment by radderz** [comment]
The above change stops the single tap gesture recognizer for succeding if the double tap succeeds.

**Comment by Sebastian1989101** [comment]
@radderz In this case I will wait for the next beta / version.

**Comment by radderz** [comment]
@Sebastian1989101 - In that case can you just ignore the single taps? As the double taps are still coming through for you?

**Comment by Sebastian1989101** [comment]
@radderz Currently I'm still using my custom solution to handle the double tap (catch the identifier from the first and check on 2nd event). But this means I have either tap very slowly on Android or I need to change the baviour there until both platforms act the same.

**Comment by Sebastian1989101** [comment]
@radderz Still different in 1.3.2 release version. Is there any plan to change this soon? Because I guess no one would expect this different behaviour between Android and iOS.

**Comment by radderz** [comment]
Hi Sebastian, I have tested this against the 1.3.2 release, and iOS is sending through *2* as the num taps for me when double tapping on an item. Therefore it works as expected. This was tested using an iPhone 6S. I cannot reproduce the issue you are talking about in either iOS or Android.

**Comment by pauldendulk** [comment]
Please create a new issue when you run into something like this.
