### ISSUE TITLE
License/copyright acknowledgement

### ISSUE THREAD

**Issue by Skymirrh** [Mapsui/Mapsui#333]
Hi Paul!

We would like to credit you, along with other library authors, in our commercial software. We already have made a folder including the whole LGPL text alongside our executable, as per the license requirement.

However, we would like to do a bit more than that and also have a listing of all third party libraries along with their authors, copyright mentions, and URL (if applicable).

I did not find any explicit copyright mention in the current `LICENSE.md`: perhaps you could give me one? E.g. "Copyright (C) 2018 Paul den Dulk" or something else of your choice?

Thanks in advance :)

**Comment by pauldendulk** [comment]
Mapsui is shipped as a nuget package so the third party libraries are specified in the dependencies that you can see on [nuget.org](https://www.nuget.org/packages/Mapsui/). 

In maintaining we use many more though. Maybe we should put a thank you some where. (note to self: thanks resharper in the readme.md).

About copyright. Mapsui is a port from SharpMap which is Morten Nielson's copyright. This is a minority of the code still in use. Perhaps you should say something generic as 'Mapsui Developes'.

**Comment by Skymirrh** [comment]
I'm sorry, I wasn't clear enough: we already made a list of all the libraries we use, including Mapsui and its dependencies.

For each one, we mention the author, the library website/GitHub (if there is any), and we add a "copyright mention" (if there is any). Mapsui did not seem to have a copyright mention specified anywhere, hence the question ;)

Would `Copyright (C) 2018 Mapsui contributors` be okay with you? Some other libraries in our list have copyright mentions that look like that.

**Comment by pauldendulk** [comment]
Maybe just leave it without copyright mention. I need to think about this.

And thanks for the thanks :)

Also, I intent to post a list of showcases somewhere here. If you would like to be added then let me know. You should have an app that is publicly available or a website I could point to.

**Comment by Skymirrh** [comment]
Alright, HMU if you change your mind and would like to add a copyright mention. As for adding our app to a list of showcases, I'll have to confirm with our marketing department first ;)

**Comment by Skymirrh** [comment]
Marketing gave me the go-ahead. If you'd like to add our app to a list of showcases:

* Name: FiberScript
* Website: http://www.fiberscript.com/ (French only)
* Description: Fiber network deployment all-in-one software, specifically tailored for France
* Editor: Script&Go (English website: http://www.scriptandgo.com/en/)

I can also provide a couple of screenshots if you'd like :)
