### ISSUE TITLE
Mapsui 2.0 small breaking changes

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#349]
I am thinking about a 2.0 release in the near future with some smaller breaking changes and without big refactorings (that should be 3.0). So basically things that need some cleaning up. My question to everybody is, what changes do you think should be included. I have written some down here:

https://github.com/Mapsui/Mapsui/blob/master/docfx/mapsui/documentation/Mapsui-2.0.md

**Comment by charlenni** [comment]
I don't see the need of a 2.0 with small breaks. Call it 1.5.

I like to see a more strikt separation between the main parts MapControl, Viewport and Map. When I started with Mapsui, I had problems, where to do what. There should be clear, that Map holds only map data and catch data. Viewport handle all regarding the part of the map that is visible and MapControl handle events.

**Comment by pauldendulk** [comment]
@charlenni So that means, Info should be moved to MapControl, but what else?

Also the PanMode, ZoomMode? Or perhaps they belong to Viewport. Where would you expect it?

It would think current Viewport does not have methods/properties that don't belong there.

**Comment by charlenni** [comment]
That's difficult. I assume, that Info belongs to Map. You want to have all features, that the Map contain at a selected place. That's an information, only Map could deliver.

PanMode and ZoomMode belong for me to MapControl. They affect the handling of the map.

Viewport needs things like zoom and navigation to a special place. All NavigateTo() function should belong to Viewport. All resolution functions should belong to Viewport.

**Comment by pauldendulk** [comment]
Your remark about Info at Map level makes sense and made me think for a while but I still prefer it at the MapControl level. The main reason is that users know controls have events and start to search for them using in intellisense. 

About PanMode/ZoomMode. Makes sense. Although it also influences the viewport. Although it does not block the viewport directly, since you can still use NavigateTo. 

About NavigateTo on Viewport, hmm, ya, I had originally intended to keep viewport really simple. Maybe I should split is further.

I added some more items to the list. Perhaps you can take a look.
https://github.com/pauldendulk/Mapsui/wiki/Mapsui-2.0

I think we should just go for 2.0. It doesn't mean much more than that we follow [semver](semver.org)
