### ISSUE TITLE
Newtonsoft.json dependency limitation

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#358]
MvvmCross just started to hit the .NET Standard 2.0 release with a huge amount of bugfixes. But to be able to use the latest version from them, I have to upgrade Newtonsoft.json to 11.0.0.2. On the other hand, Mapsui requires Newtonsoft.json to stay below v11. There should be no major problem allowing Newtonsoft.json to upgrade so I hope you can lift up this dependency limitation a bit.

**Comment by michalhoblik** [comment]
Hi, 

I had the same problem this week. Thats's right, there should be no problem to allow Newtonsoft.Json in Nuget without limitation. In my project I just made an update on Newtonsoft with "Ignore Dependencies" Option and till now everything is fine, Mapsui is working without problems.

**Comment by pauldendulk** [comment]
It is a silly problem I should fix soon. The json parser is only used by the esri layer which is not used that often. My plan was to ill merge it into the assembly so you don't have a conflict.

**Comment by michalhoblik** [comment]
Thanks Paul, nice to hear that 👍

**Comment by pauldendulk** [comment]
@Sebastian1989101 So, for the short term this could be fixed with Michal's suggestion to update with Ignore Dependencies and there are probably other workarounds.

**Comment by Sebastian1989101** [comment]
@pauldendulk I use it already this way. I just opened this issue in case you can change this maybe within one of the next updates because it could be very confusing for newer developers. Especially because MvvmCross fixes so much with Version 6 which requires a newer Newtonsoft.Json version.

**Comment by Sebastian1989101** [comment]
@pauldendulk Is there any ETA for a nuget beta/release with a more open dependency? I have to create a new project shortly which could be benefit from a Map and I would like to use Mapsui for that.

**Comment by pauldendulk** [comment]
I did some googling yesterday. The next release will be netstandard so we need to take this into account with merging. I did some googling but did not find any easy solutions. Not easy to understand for me anyway. Most people want everything to merge into a single assembly. This is not what I want. I see mentions of ILMerge, [.NET IL Linker](https://github.com/dotnet/core/issues/915), [ILRepack](https://stackoverflow.com/questions/43165788/merging-net-standard-assemblies).

If anyone can explain my how to do this with netstandard I give it priority. The use case is: There is a project that has a dependency on json.net. I guess there should be some post build step that calls one of these tools. The result is json.net merged into the project's assembly, and not other dependencies like the geometries.

**Comment by Sebastian1989101** [comment]
@pauldendulk I would recommand to not use a binary merge. While it looks like it has only positive impact there are actual a few problems. 

1. The size of the app grows unnecessarly 
2. If reflaction is used it can result in something like the merged Json.net is used instead of the self referenced one 
3. If a developer decides to use binary mergin he will get problems if he uses Json.net himself. 

I have used ILMerge a few times but only for final executable so that the customer has a single file instead of all the library files. I would never recommand or use something like this for a library. Even if it is more work, it is much cleaner just to update the referenced library when possible and use unit tests to make sure everything is still working properly.

**Comment by pauldendulk** [comment]
Well, the next alpha release of Mapsui 2.0 will have the latest json.net. So this solves your problem. 

In general this is not the ultimate solution since an application can have many dependencies with each different version of json.net included. You can not force everyone to use the latest version.

**Comment by pauldendulk** [comment]
Another road is to move the esri layer out of the Mapsui package. Perhaps this should be the way.

**Comment by Sebastian1989101** [comment]
@pauldendulk There will always be a problem that conflicts when using external libraries instead of own libraries. But in most cases it should always be the way to  use up2date libraries as much as possible. Espacially for security reasons and bug fixes. 

Is the next alpha version of mapsui already using .NET Standard or is it still a PCL thing?

**Comment by pauldendulk** [comment]
About the problems you mention. I did not think about, 2, thanks for that. About 3. Is it not possible to merge two versions of the same library?

**Comment by charlenni** [comment]
2.0 is now .Net standard 1.1 for Mapsui and 1.3 for Skia renderer. There aren‘t any PCL anymore.

**Comment by Sebastian1989101** [comment]
@pauldendulk In some cases it causes problems (depending on how both merges are executed). By default the assembly gets merged 1:1 into the "root" of the new assembly. In this case there is already a Json.net in the "root" while another should be merged into the exact same spot. This would result in an exception. So you would need to change the target for the merged Json.net in your project but this can lead into broken functions because it is not in the expected spot. Also the assembly should be internalized so that it is not possible to call the functions without reflections. There are a lot of things to be mentioned before doing something like this.

**Comment by pauldendulk** [comment]
Thanks a lot. This is valuable information that saves us a lot of trouble.

**Comment by pauldendulk** [comment]
And yes the next alpha 2.0 will be netstandard. Is this a problem for you?

**Comment by Sebastian1989101** [comment]
@pauldendulk No my projects are, except for one, .NET Standard anyway. I was just wondering because in another thread you mentioned v3.0 for .NET Standard. 

About the informations: Keep in mind that my expirence are based on ILMerge with .NET Framework. So it might be difference on other solutions but I would guess there are always the same issues when merging libraries.

**Comment by pauldendulk** [comment]
My impression is that with netstandard and net core these things have become more unpredictable. It will need some time.

**Comment by pauldendulk** [comment]
I had 3.0 in mind, but then @charlenni came along and ruthlessly ported it in just one day :)

**Comment by pauldendulk** [comment]
Mapsui 2.0.0-beta.2 has been released. It has no upper limit in the json.net version. So this should fix your problem. 

The core assemblies are now netstandard1.3

**Comment by Sebastian1989101** [comment]
I will test it next week. If everything works I will put it into a beta version as soon as this is fixed: https://developercommunity.visualstudio.com/content/problem/251326/error-mt5212-native-linking-failed-duplicate-symbo.html
