### ISSUE TITLE
AnimatedPointLayer problem

### ISSUE THREAD

**Issue by antonad** [Mapsui/Mapsui#360]
Hello. I am using AnimatedPointLayer to display several icons. Icons can be moved to another position or hidden by internal logic.
The problem happens when I try to hide features.
```
    public override IEnumerable<IFeature> GetFeaturesInView(BoundingBox box, double resolution)
    {
        var features = new List<IFeature>();
        for (int i = 0; i < f.Count; i++)
            if (f[i].m_Tracker.Enabled)
                features.Add(f[i]);
        return features;
    }

```

This code is running every 1 sec (Layer.UpdateData is called from timer). Buy Icons are hiding not every time. Usually I can hide icons 1-2 times only.

Can you help me with my problem. May be I should hide icons another way?

**Comment by pauldendulk** [comment]
Try to use a ThemeStyle for this. You need to return a Style with Enabled set to false if tracker.Enabled is false.

If  tracker.Enabled changes you need to call a refreh of the map.

**Comment by antonad** [comment]
How Can I make the map to refresh? 
I have not found something like Refresh function.

**Comment by pauldendulk** [comment]
MapControl.Refresh. From within a layer you can call OnDataChanged.
