### ISSUE TITLE
Resolutions of map

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#372]
Resolutions for map are always taken from the first layer (baselayer) in the Layers list. Is there the possibility to add all resolutions of all layers?

**Comment by pauldendulk** [comment]
It should be more flexible yes. It should also possible to add a list of resolutions. 

What is the scenario you had in mind? The resolutions are involved in mouse wheel and +/- zooming. And default min and max zoom.

**Comment by charlenni** [comment]
If you use Mapbox GL theme style, there could be more than one map layer. I the case of the OSM-Liberty theme, you have one raster map with zoom from 0 to 6 and above a vector map which could be more zoomed. But now, the map is limited to 0 to 6.

The next problem is, that ILayer MinVisible and MaxVisible aren't zoom levels as described, but in units per pixel/resolution. I don't expect this. The same for IStyle. That seems totally different from any other map library, where allways zomm levels are used.

**Comment by charlenni** [comment]
If you want to have an example:

![grafik](https://user-images.githubusercontent.com/4381223/38598766-07f14d98-3d5e-11e8-871e-b77046984b57.png)

It is a raster map in the background and streest and names are from a vector MBTiles file above this raster map. But in this case, the raster map determins the zoom levels (0 to 6), but the MBTiles file have up to 14 zoom levels.

**Comment by pauldendulk** [comment]
Not sure yet how to solve this. 

Currently it takes the lowest layer (drawn under the other layers) that is enabled and that has any resolutions. It updates this list if there is a change in the layer list which is nice. 

There is a Resolutions field. I could make this settable, but if you set it explicitly it should not update after adding and removing layers. 

Alternatively the user could specify which layer to use to determine the resolutions. So in your scenario you could tell the Map to take the top layers not the bottom one. 

Perhaps it could also be possible to override the DetermineResolutions method. So you don't set the list of resolutions but the set the Method that determines the resolutions. That method could contain a specific list, or it could try to search for a specific layer it could use. Perhaps the custom could fall back on the regular DetermineResolutions method if it does not find its preferred background layer.

This last idea does not seem too bad for to me now. It is very flexible. Not very intuitive but we could document it. 

A similar mechanism is the FetchStrategy that can be overriden.

**Comment by pauldendulk** [comment]
So I like the method solution, but it is not very easy for the user. It the fancy functionality is often not used. 

How could we make it easier for the most common scenario? Perhaps we could put all resolutions of all layers together. And do a distinct (with some tolerance for the double compare). But if a layer would be included that has its resolutions right in between the other layer then this would double the number of resolutions. .... This would not happen very often en would not be a disaster.

**Comment by pauldendulk** [comment]
Or it should use the base layers resolution in the range that it has resolution and include resolution outside this range from other layers.

**Comment by pauldendulk** [comment]
Perhaps it could work like this. Add all the resolutions of the first enabled layer. Then take all the resolutions of the second layer but only add a specific resolution if it is not too close to any of the other resolutions.

**Comment by pauldendulk** [comment]
Came up with this:
```C#
        private static IReadOnlyList<double> DetermineResolutions(LayerCollection layers)
        {
            var items = new Dictionary<double, double>();

            foreach (var layer in layers)
            {
                if (layer.Enabled && layer.Resolutions != null)
                {
                    foreach (var resolution in layer.Resolutions)
                    {
                        var normalized = Math.Pow(resolution, 2);
                        var distance = items.Keys.Min(k => Math.Abs(k - normalized));
                        if (distance > 0.75) items[normalized] = resolution;
                    }
                }
            }

            return items.Select(i => i.Value).ToList();
        }
```

**Comment by pauldendulk** [comment]
The resolution is the scale. You draw a map on a certain scale, no scale, no map. So it is pretty basic. :)

The level integer value that is used in the interface of many map applications indicates a kind of resolution. It is just a shorthand. But all other map application do have to determine the resolution (or scale) at some point when they draw something on the map. 

The Resolutions on the Map class are used when zooming in and out. They determine the steps when using the mousewheel (and since my fix a few days ago also by the +/- button). For tile layers this helps to choose a resolution that corresponds to the optimal resolution of the bitmaps so that it looks better, with more detail. To the end user the can be shown as integer values.

**Comment by charlenni** [comment]
Ok, if I get it right, Mapsui doesn't need it at all, correct? Than there should be a function or property to provide them by user, because he is the only, who knows the right resolutions. The resolution is a value, that depends on the map. It is only usefull for raster maps, because there are steps with good quality. If you have more than one map, the user should determin, which steps are usefull.

**Comment by pauldendulk** [comment]
Custom resolutions might also be necessary at some point but right now I try to fix this for the most common scenario. In this scenario there will be no further actions necessary by the user. There are also many dynamic cases where layers are added and removed. The above method will work properly in that case. 

I just committed this change. This should resolve the issue you describe in the first comment. The base layer resolutions will be used but if subsequent layers have additional resolutions they will be added.

**Comment by pauldendulk** [comment]
If there are no raster maps the mousewheel still needs a step size to zoom in. This is now determined by the ZoomHelper. It checks if there are resolutions, if not if will use a step of 2 (or 0.5 in the other direction).

**Comment by pauldendulk** [comment]
Right now you can do that like this:
```
map.NavigateTo(map.Resolutions[0]);
```

In CenterAndZoomOnLocation it is used to zoom in closer:
```
map.NavigateTo(map.Resolutions[9]);
```
I could add a NavigateTo that takes an integer and get the resolution for you, just to make it one step easier.
```
map.NavigateTo(9);
```
Implementation:
```
public void NavigateTo(int level)
{
  // todo: add some checks
   Viewport.Resolution = Resolutions[level];
   OnRefreshGraphics();
   ViewChanged(true);
}
```

**Comment by pauldendulk** [comment]
Is that what you were thinking about?

**Comment by charlenni** [comment]
This will only work, if you have a resolution for level 9. If you don't have such a resolution, it wouldn't work. So my intention is, that it should be possible to navigate to levels, that are not in Resolutions[].

**Comment by charlenni** [comment]
Ok, changed all zoom things in vector tiles to resolution.

I think, that the comment in IStyle isn't correct. It says

        /// <summary>
        /// Gets or sets the minimum zoom value where the style is applied
        /// </summary>
        double MinVisible { get; set; }

But MinVisible is the maximum zoom level. Greater zoom is smaller resolution. That's what making things complicated ;) And btw. even you use resolution and zoom level as synonyms.

**Comment by charlenni** [comment]
If I set my baselayer to max zoom of 6, than it isn't possible to zoom with the normal MapControl (in this case Wpf) beyond zoom level 6. What I expect is, that after zoom level 6 the raster bitmap get pixelated, but I could zoom further. If I than move the map around, than should allways the highest zoom level be loaded.

**Comment by pauldendulk** [comment]
You ask about 'max zoom', is this MaxVisible?

MinVisible should indicate the minimal resolution. When I use min and max I usually indicate the actual numerical value. 

The resolution concepts comes from the tile layers, for the user the inverse this would probably make more sense. I think it works like this in SharpMap, the comment probably originates from SharpMap. The Styles and Geometries or still close to the SharpMap version. 

I don't intent to make changes here in the short term. Just fix bugs and document correctly. If the comment was changed to 'Gets or sets the minimum resolution where the style is applied', would this be understandable from your perspective?

**Comment by charlenni** [comment]
Yes, that should work.

**Comment by charlenni** [comment]
Oh, I forgot: yes, MinVisible is max zoom level and MaxVisible is min zoom level.

**Comment by pauldendulk** [comment]
Yes, but the comment is indeed incorrect.

**Comment by pauldendulk** [comment]
In 4.0.0 it is possible to add custom resolution through the `Map.Navigator.OverrideResolutions` property.
