### ISSUE TITLE
Styling of raster layer?

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#374]
Is there a style for raster layers for e.g. applying opacity with a IThemeStyle?

**Comment by pauldendulk** [comment]
No currently style does not affect raster at all. You would like to determine the raster opacity with a themestyle? Is this something needed for vector styles?

**Comment by charlenni** [comment]
Not vector styles, but Mapbox GL theme files. There you have something like 

    {
      "id": "natural_earth",
      "type": "raster",
      "source": "natural_earth_shaded_relief",
      "maxzoom": 6,
      "layout": {
        "visibility": "visible"
      },
      "paint": {
        "raster-opacity": {
          "base": 1.5,
          "stops": [
            [
              0,
              0.6
            ],
            [
              6,
              0.1
            ]
          ]
        }
      }
    },

which says, that the raster tiles have opacity at zoom level 0 of 0.6 and than it goes with increasing zoom level exponential (base property) to 0.1. 

Could be nice. But isn't a must have. Could wait.

**Comment by pauldendulk** [comment]
Interesting information. Thanks for figuring these things out. 

Makes me wonder if returning Style instances is the solution here. Maybe individual Styles should now the resolution. Another approach would be to implement this at the layer opacity level. This does affect a tile layer in the current implementation.

**Comment by charlenni** [comment]
There are more styles for this, like contras. But I think in the moment opacity is enough.

On layer level is ok, but when to set? It should be changeable each time the resoultion changes.

**Comment by pauldendulk** [comment]
Yes, not sure where that should happen. Here layer.Opacity is use in the VisibleFeatureIterator.

```
        private static void IterateLayer(IViewport viewport, ILayer layer,
            Action<IViewport, IStyle, IFeature, float> callback)
        {
            var features = layer.GetFeaturesInView(viewport.Extent, viewport.Resolution).ToList();

            var layerStyles = ToArray(layer);
            foreach (var layerStyle in layerStyles)
            {
                var style = layerStyle; // This is the default that could be overridden by an IThemeStyle

                foreach (var feature in features)
                {
                    if (layerStyle is IThemeStyle) style = (layerStyle as IThemeStyle).GetStyle(feature);
                    if (style == null || style.Enabled == false || style.MinVisible > viewport.Resolution || style.MaxVisible < viewport.Resolution) continue;

                    callback(viewport, style, feature, (float)layer.Opacity);
                }
            }

            foreach (var feature in features)
            {
                var featureStyles = feature.Styles ?? Enumerable.Empty<IStyle>();
                foreach (var featureStyle in featureStyles)
                {
                    if (feature.Styles != null && featureStyle.Enabled)
                    {
                        callback(viewport, featureStyle, feature, (float)layer.Opacity);
                    }
                }
            }
        }
```

**Comment by pauldendulk** [comment]
What other style aspects are determined with such level stops?

**Comment by charlenni** [comment]
You could find them [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-raster). If there is a small triangle, than there could be stopps.

**Comment by pauldendulk** [comment]
This is an interesting issue but we will not act on this in the short term, so I will close it.
