### ISSUE TITLE
WMS layer on Xamarin.Forms

### ISSUE THREAD

**Issue by andrearivera8** [Mapsui/Mapsui#386]
I am working on an mobile app that requires using WMS to retrieve data from Geoserver and other servers. How can I obtain the feature info (field attributes) when the user clicks a polygon? I am using BruTile

Thank you.

**Comment by charlenni** [comment]
Did you tried `feature[field_name]`and looked into `feature.Fields`?

**Comment by pauldendulk** [comment]
Take a look here:
https://github.com/pauldendulk/Mapsui/blob/master/Mapsui.Desktop/Wms/GetFeatureInfo.cs
