### ISSUE TITLE
Fetching strategy & Info

### ISSUE THREAD

**Issue by Kortdag** [Mapsui/Mapsui#389]
# Hi Mapsui

I have two issues. 

1) One regarding Info
2) One related to the fetching strategy of ImageLayer - or actually in general

Both can be found in the attached samples.

**Info**

1. On iOS and a Retina screen the MapInfo ScreenPosition is in you internal canvas position. Since Retina i x2 the coordinates are outside the bounds since in MapControl you do
var screenPosition = GetScreenPosition(gesture.LocationInView(this)); 
private Point GetScreenPosition(CGPoint point)
        {
            return new Point(point.X * _scale, point.Y * _scale);
        }
On my device the map requests are of size 1240x962 and a random lower right coner yields
2018-04-20 18:10:32.861 Mapsui.Samples.iOS[812:642931] POINT (2176 1615)
So for one to do GetFeatureInfo you would have to scale back the position to the map/image resolution or get and position out of bounds from the WMS server.

This would imply making an UI service to tell you common library what the actual resolution is. Furthermore the screenposition is relative to the map itself which is fine for GetFeatureInfo - except the issue above. But for placing a callout one would often need the window position since the map is not alway full screen.

Furthermore like mentioned in the source the InfoRequest should be for all hit layers and not just the first one. If you have info on more than one layer the user could get to choose what to do if more than one feature is hit.

Suggestion
1) Make ScreenPosition in the MapInfo in resolutionsless pixels for GetFeatureInfo  purposes
2) Extend MapInfo to contain Window resolutionless pixel to position a callout regardles of map placement
3) Return a collection og MapInfo if more features found not just the first one.

**Fetching**

Suggestion
1) There is an issue in the ImageLayer and the FetchDelay makes it better but does not fix it. Consider making an Async version. Like shown in the sample I got it to work in an alternative but far better way - atleast thats my oppinon untill all starts crashing :-). 
2) Enabling a tilelayer to change the number of workers. TileFetcher is hidding in the constructor. 4 is less than most default browsers.
3) This is the controversial one :-) I know this is not something you would do but in the long term maybe consider an asynchronous approach. Atleast in my oppinion it would be the way to proceed for various ways. If you care feel free to continue or go enjoing the sun and mayby somebody in the forum will run into smilar issues and can use it for inspiration
[Demo.zip](https://github.com/pauldendulk/Mapsui/files/1933002/Demo.zip)
:-)

The GetFeaturesInView view API are all synchronous i.e. return IEnumerable and not Task<IEnumerable>.
This leads to you having to implement all backend fetching using Task.Run to get it off the UI thread. This does not work well for ImageLayer - but could of course.... 
If its slow it does not work at all like shown in the sample. The map locks up. I assume thats why there is implemented a FetchDelay to try to work against this? Anyway I have made a Task based implementation that does not do that even in the case of a very slow backend. This has the benefit of not locking the UI on quick map movements if the backend is slow and not punishing the user with a delay if one doing a single map operation.

A few thoughts on synchronous vs async.

Fetching tiles  and / or WMS maps are going to end up in a HttpClient ind the end - the one the users implement if not requested from a memory cache in which case they can just be returned. Its an almost 100% IO bound operation with very little CPU stuff going on. Basicly just making a feature from bytes. 
Task/Await does not block the UI so I think its perfect for a task like this.

A HttpClient has a limit on the concurrent connections allowed to the same host - default is two I believe. In a synchrounous API there is no way you can tell the HttpClient to cancel an ongoing task. Of course the backend server would still finish the work, but who cares :-). In the case of your tile layer there are 4 workes internally but if using the same HttpClient it wil not allow more than two at a time unless you increase that limit. Incresing it to more than 4 wont help since a tile layer cannot be setup to more than the internal 4. And most of the classes below are private so just copying the tilelayer wont fly. In the API its possible to cancel af fetch but only the background workers, the HttpClient will have to complete if on the limit. 

I attached an async WmsLayer that you can compare the the sync counterpart if you like. The only VERY tricky issue was related to the use of at feature bounding box apparently beeing parsed around the api and some threadding stuff not updating it, so I had to clone it or the feature would not update on pan before new fetch. Of course a async tilelayer is a bit more complex since there have to be some bookkeeping of pending work that is not needed (and can be cancelled) if moving the map quicly.

I think the benefit for you woould be much less stuff to maintain. Just let the user worry about how much is goind on at the same time and starting an cancelling tasks from the API.

In (Core 2.0 atleast) one can set the http concurrent limit like so
ServicePointManager.DefaultConnectionLimit = 20;

There is a lot of stuff to get for free in the async world like retry on error. If your interested se my favorite article and related stuff.
https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern

**Comment by pauldendulk** [comment]
Hi Kortdag, Thanks for your contribution. One thing I have to say is that is is a lot easier to deal with issues if they focus just on one topic. As small as possible. We need to close issues and the bigger they are the more likely it is there will be dangling things to keep discussing about. Also it is harder for my to formulate an answer. I would say this post contains at least 6 different issues :)

**Comment by pauldendulk** [comment]
Right now I will respond to one. The iOS coordinates. They should be in iOS screen positions not in skia canvas positions. If this is not the case this is a bug. I just tested this on Android and it seems to work correct there. If you run the Android sample of the current trunk you can test this. The Android logic is the same as the iOS logic so I expect it to be correct on iOS. Some questions.

- Which version of the code are you working with?
- Did you work with Android as well? Is it correct there?
- Could there be a confusion between logical pixels and actual pixels?
- The MapInfo event also returns the feature position. Does this have the same problem?

**Comment by Kortdag** [comment]
I should mention that in the infoholper
You do 
            var worldPosition = viewport.ScreenToWorld(
                new Point(screenPosition.X / scale, screenPosition.Y / scale));
So I assume world position is ok, but havent tested

**Comment by pauldendulk** [comment]
I removed the _scale multiplier in GetScreenPosition. On Android there is no such correction either. At some point I have rewritten the MapInfoHelper to take care of scale internally. I guess I have not corrected the iOS MapControl for this. Does this fix your problem?

**Comment by Kortdag** [comment]
It works - case closed :-)
