### ISSUE TITLE
Label: multiline

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#390]
Hi,

I try add LabelStyle to Feature and I would like to have a multiline text.
So, I do something like this:

feature.Styles.Add(new LabelStyle { Text = String.Concat("bleble\r\n123\r\nABC", Environment.NewLine, someX, " ", someY) });

and I have empty boxes there where the line breaks are.
```
bleble□
123□
ABC□
x y
```

Is it something with Font (FontFamily=Verdana, Size=12)?

Regards,
Łukasz

**Comment by lukaszpitulski** [comment]
![obraz](https://user-images.githubusercontent.com/15933140/39079216-63db6b10-4516-11e8-9f2c-37be5ec1b7e1.png)

**Comment by pauldendulk** [comment]
Try to remove the '\r'.

**Comment by lukaszpitulski** [comment]
works, thanks!

**Comment by pauldendulk** [comment]
Tra xurt Yves

**Comment by pauldendulk** [comment]
Yoghurt fr university her

**Comment by pauldendulk** [comment]
Tv c 6v

**Comment by pauldendulk** [comment]
Well if you can't appreciate it I will remove it. I'll will just enjoy my French university yogurt on my own! 😜

**Comment by pauldendulk** [comment]
While watch channel 6v on the tv together with Yves.
