### ISSUE TITLE
Layer Style vs Feature Styles

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#391]
Hi,

Layer has some Style (f.e. SymbolStyle or StyleCollection).
Each Feature has also some Styles (different from the Layer).

How to show/hide style(s) of the Feature and how of the Layer only?
(and keep them all)
F.e. I would like to see only the Layer's style and don't change/clear the Features' styles.

Currently all styles are visible (is mix :( ). Feature(s)' styles on the Layer style.
Layer.Style = null;  or Feature.Styles.Clear(); is not possible in my solution.

Regards,
Łukasz

Layer's style
![obraz](https://user-images.githubusercontent.com/15933140/39100903-f86737ce-4691-11e8-9ea3-6914a6fe832f.png)

Feature's style
![obraz](https://user-images.githubusercontent.com/15933140/39100918-3d691914-4692-11e8-9561-55049cabbece.png)

The mix
![obraz](https://user-images.githubusercontent.com/15933140/39100936-69cd92a0-4692-11e8-9bc8-1e285cab8b86.png)

**Comment by lukaszpitulski** [comment]
the proposition (to see the features styles only)

maybe some method in BaseLayer like HideStyle
where current style will be saved(copy) in temp IStyle 
and the layer.Style = null

next, some method ShowStyle
where the layer.Style = temStyle

**Comment by pauldendulk** [comment]
There is specific functionality to switch between those two and I don't think there should be. It is however possible to disable and enable a specific style.

What you are trying to do sounds complicated perhaps there are better solutions. Could you explain your use case?

In many advanced cases a ThemeStyle is a good solution.

**Comment by pauldendulk** [comment]
There is NO specific ... sorry

**Comment by lukaszpitulski** [comment]
What I'm trying to do is:

I have a layer with SymbolStyle
The layer has a feature(s) with styles: VectorStyle, LabelStyle

For example, I would like to hide the LabelStyle but don't delete it from any feature also I need to hide the layer's style(s).
So, in the end I should see the feature(s) only with the VectorStyle (nothing more).

Now, do some operations, and after all, I want to show the feature(s) and the layer styles (again).

Is it clear enough? ;)

**Comment by charlenni** [comment]
Yes, it is clear, but you could do this, like @pauldendulk said, by your own. IStyle has a flag Enabled, that is respected. So, if you set your for your LayerStyle Enabled to false, than it isn’t used. That’s easy. But for the feature style you have to go through the complete list. Perhaps a layer flag like UseLayerSytle and UseFeatureStyle could be helpful.

**Comment by pauldendulk** [comment]
As charlenni says, and also, why do you need the feature styles to be on the feature? You could put them on the Layer as well. You could put two styles on a layer in a layer collection. Or you could create a ThemeStyle that returns a layer collection.

**Comment by lukaszpitulski** [comment]
The feature style is required because each feature can have different style (fro. example bitmap/icon). Any feature without style will be with the layer style.
And now, all features' styles have LabelStyle, and I would like to hide only Label (keep icons) but for specific features only.
Do a few operations and show the hidden styles again.

**Comment by charlenni** [comment]
Why don't you use the Enabled flag for this?

**Comment by pauldendulk** [comment]
I think you could do anything with the ThemeStyle. You will need something to map feature id to style though.
