### ISSUE TITLE
Get center of the view

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#399]
Hi,

I try get center of this what I see on the screen (Point).
I try `Map.Viewport.Center` but I'm not sure if this is correct.

I want to have the center of the view-map always, even when zooming, moving etc.

(if the issue was reported already, please url)

Thanks,
Łukasz

**Comment by pauldendulk** [comment]
`Map.Viewport.Center` should be the center of what you see. What makes you think it is not?

**Comment by charlenni** [comment]
A short view into source code (that's the big advantage of open source projects) would have you shown the Viewport.Transform function (called by Mapsui.UI.Shared.MapControl.OnTouchMove when map is moved/dragged), which calculates the new center of the viewport.

**Comment by lukaszpitulski** [comment]
Thanks,

> Map.Viewport.Center should be the center of what you see. What makes you think it is not?
Just asking ;) , and in fact my confusion has come from another thing... when I use Map.Viewport.Center (in Map.PropertyChanged or Map.Viewport.ViewportChanged events) then something weird is going on with the map, is blank(backcolor) after init (but with all widgets inactive), just empty.  (init = transformation, crs, backcolor, layers, widgets, events, etc.)
I think the reason is that it's before any RefreshData(); and/or RefreshGraphics(); but when I don't use Map.Viewport.Center at all then is ok (after init the map shows whole glob (before navigate to any place) and the widgets are active).

**Comment by lukaszpitulski** [comment]
this helps (before Viewport.Center):
if (MapControl?.Map?.Viewport == null || !MapControl.Map.Viewport.Initialized) return;

but performance is a little worse

**Comment by lukaszpitulski** [comment]
Referring to https://github.com/Mapsui/Mapsui/issues/398  and using Map.Viewport.ViewportChanged / Map.PropertyChanged 

What I'm trying to do is get center point of the View always what ever is going on with and on the map, next put on one of the layer some icon(small cross) in that point. 
And in that way always see the center of the map view.

**Comment by charlenni** [comment]
I doesn‘t understand this. You want the center of the viewport, but say, that this point is always in the center?

The map doesn‘t have a center. Perhaps you could say, that 0/0 is a center. The viewport has a center, which is at Viewport.Width:2/Viewport.Height:2.

If you want to make a cross in the center of the viewport, than I would suggest to make a Widget. This draws on top in screen coordinates. That‘s the fastest method to do this.

**Comment by pauldendulk** [comment]
There is no plugin model voor Mapsui widgets yet (it will come), but you can just place something in your client's code on top of the map. An alternative is to add point to the map and then continuously move it to the new center of the map on every viewport change, but that would be weird, using some functionality and then fight against it. In this last case you have to do: 
```
var newCenter = Map.Viewport.ScreenToWord(Map.Viewport.Width * 0.5, Map.Viewport.Height * 0.5);
```

**Comment by lukaszpitulski** [comment]
I understand that you don't understand my issue, my description of it can be complicated ;)
All because of the lack of documentation and methods' descriptions/summaries in Mapsui.
Where are there, maybe I've missed them?

So, I don't blame anyone except myself, and my misunderstanding of Map.Viewport.Center result and how Features are located on the map(layer, view, etc.), I mean Geometry.

What I need and what the issue solution is :
```
var worldLocation = MapControl.Map.Viewport.Center
var mapLocation = Mapsui.Projection.SphericalMercator.ToLonLat(worldLocation.X, worldLocation.Y)

```
So, finall solution is Viewport.Center -> ToLonLat in Viewport.ViewportChanged
(side effect: a little performance degradation)

**Comment by gleblebedev** [comment]
> MapControl.Map.Viewport.Center

There is no Viewport property in the Map, not it is property of Navigator.

**Comment by pauldendulk** [comment]
> > MapControl.Map.Viewport.Center
> 
> There is no Viewport property in the Map anymore, it is property of Navigator class now.

Yes, thanks. In v4 it is `MapControl.Map.Navigator.Viewport.Center`. This kind of change can be found in the v4 upgrade guide: https://mapsui.com/documentation/v4.0-upgrade-guide.html#other-changes: "MapControl.Viewport moved to MapControl.Map.Navigator.Viewport".

For v5 such changes should be in here, but it is currently still missing a lot of changes: https://mapsui.com/v5/v5.0-upgrade-guide/
