### ISSUE TITLE
Strange namings

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#400]
While adding comments to Mapsui, I found some strange namings. Perhaps we could discuss, if there are better names for this. I try to add more, when I found them.

*Transform (move viewport around), Transforming (convert coordinates) and Transformer (same as Transforming?)*
All three sound equal and the later two seem to do the same.

*Envelope (Layer and Map), Extend (Viewport) and BoundingBox (Feature)*
All three are used for the same thing: the bounds around a geometrical figure. Envelope is used for the maximal coverage of a map or layer. Extend is used for the maximal coverage of a viewport. BoundigBox is used for the maximal coverage of a feature.

**Comment by pauldendulk** [comment]
### Envelope, Extent and BoundingBox
They all have roughly the same meaning and are indeed used in the way you describe. We could use the same term everywhere but I wonder if it would be clearer. The code might be harder to read when the same phrase is used to describe slightly different things. 

Geometry.BoundingBox is a term imposed by the geometry library. We could look at NTS and use what they use. 

The distinction in use of envelope versus extent is arbitrary. In esri software this is mostly used in the same way, envelope indicating the extent of all data combined, and extent indicating the current viewport. I don't see this as very confusing, and wonder if it might be more confusing if changed. 

As a general guideline I would say: **Do as the others do. **. So, what is the terminology in, OpenLayer, Leaflet, GoogleMaps, BingMaps, Esri.

**Comment by pauldendulk** [comment]
### Transform, Transformer, Transforming, Projection
There is certainly room for improvement here. One issue is the logic of projections itself. Some of these classes where added later and older ones should be removed. We could also use Projection for use of map projection libraries and transform just for screen to world and back. This should get some attention when rewriting the projection logic.

**Comment by pauldendulk** [comment]
IProvider.GetExtents is not in line with what is described above.

**Comment by pauldendulk** [comment]
There has been some renaming as part of the refactoring. There will be more renaming when introducing NTS and when rewriting projections. I am closing this now. Please bring up suggestions with respect to specific classes/fields when you run into them.
