### ISSUE TITLE
VisualStudio.Mac and Projections

### ISSUE THREAD

**Issue by TomQv** [Mapsui/Mapsui#402]
Its been a while, but today I came back to have a look of the current status of Mapsui and I must say, that I'm really impressed of the performance and progress of the engine. 
Trying some of the samples, zooming in and out, its absolutely awesome :)

Two questions:

1. We need VisualStudio.Mac. also. 
So I would need to write a Mapsui.UI.Mac-component. How would I start with this? 
Most probably with the Mapsui.UI.iOS component? 

2. We need to render rastermaps with any projection in any format
For example png, jpg, tif, ecw etc with different projections . 
So I need to write a new Layer-class, which reads these formats (which is not the problem). 
But how to handle the projections? 
There is Mapsui.Projection.ITransformation, but only MinimalTransformation at the moment. 
We have the proj.4-library in c#, so the actual projection-code is available. 
Could this be integrated as a new ITransformation?

Thank you
Tom

**Comment by pauldendulk** [comment]
hi Tom!

1. I don't know too much about Mac desktop. I guess that indeed Mapsui.UI.iOS would be a good start. It should be possible to have this as a component in your own project and use the mapsui nuget as reference. In the long term this would also be interesting for mapsui core. At this moment we have just started with a shared MapControl project. We will move more code into this step by step. This will take a while. Perhaps you should ignore this for now and just build your own by copying the necessary code.

**Comment by pauldendulk** [comment]
2. MinimalTransformation is a minimal implementation of ITransformation. You could build your own implementation. I did something similar with other projection libraries. Do you use an open source version of proj4? Where can I find it? Perhaps we could work an a sample for this in a shared repository.

Projection of rasters is not that easy. Do you already do some raster projection with proj4?

**Comment by TomQv** [comment]
Hi Paul,

I started with proj.4 from [this source, Proj4CSharp_1_1_beta.zip](https://sourceforge.net/projects/pro4jcsharp/files/). Its an old project, but the code is working.
We do projection of raster, its actually essential for our app, but we using an OpenGL renderer and the transformation is done with transforming the bitmap as textures on meshes with calculating the uv-coordinates according to the projection. I didn't find any solution up to now, to do this on raster-bitmap level with similar performance.
What I really like on Mapsui is the ui-performance. The way you guys implemented renderer and data fetcher is just awesome, but I'm scared the project will not work for us. We also need 3d with elevations.

**Comment by pauldendulk** [comment]
I don't think there is much available that could do these raster projections in a performant way. Seems like you'v built a nice solution. 

3D is not on the roadmap for Mapsui. Of course you can always use tricks like shaders or some kind of projection that could help with the illusion but if real 3D is important then Mapsui is not the best choice.

**Comment by pauldendulk** [comment]
I assume this is answered.
