### ISSUE TITLE
White border in skia rendering on wpf on some machines

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#403]
Most likely cause it that we do not take into account the skia scale on wpf. 

I don't know how to reproduce this, @bertt can.

![image](https://user-images.githubusercontent.com/963462/39614279-f5e1e5a4-4f6e-11e8-9be1-5045ea9f64c3.png)

**Comment by pauldendulk** [comment]
This in 1.4.0

**Comment by pauldendulk** [comment]
Changing the display settings seems to have no effect.

![image](https://user-images.githubusercontent.com/963462/39614392-c5263860-4f6f-11e8-80f3-0ee5229fcc4f.png)

**Comment by bertt** [comment]
![border](https://user-images.githubusercontent.com/538812/39614940-bb6da7a0-4f73-11e8-9b23-bd6c0501352e.gif)

**Comment by bertt** [comment]
indeed fixed in 1.4.1 👍
