### ISSUE TITLE
New logo for Mapsui

### ISSUE THREAD

**Issue by reallinfo** [Mapsui/Mapsui#405]
Hello, I wanted to contribute to Mapsui and I designed a logo for it. If you like it, I can send you a pr. If you have anything you want, you can tell me. 

![mapsui](https://user-images.githubusercontent.com/36298335/39719829-146503e0-5243-11e8-9d0f-c33309625812.jpg)

**Comment by pauldendulk** [comment]
Hi there, Thanks a lot. I would love to use this. I especially like the icon at the top.

**Comment by reallinfo** [comment]
Thanks! I sent pr. Please check it. https://github.com/Mapsui/Mapsui/pull/407

If you have any problems, do not hesitate to let me know.

**Comment by pauldendulk** [comment]
Great, I've merged it. How did you create the logo? Do you also have some kind of vector source?

**Comment by reallinfo** [comment]
Of course! all the files you need are here.

https://drive.google.com/open?id=1ikW6D2CD4d5cWMSOTHXJDWWNpgRkt6-Y

**Comment by pauldendulk** [comment]
Thanks, I will add them to the repo as well. Is that okay?

**Comment by reallinfo** [comment]
Ofcourse...
