### ISSUE TITLE
iOS - World Coordinates moves with the map

### ISSUE THREAD

**Issue by mintblau** [Mapsui/Mapsui#406]
Hello,
I am using MapsUi only for showing some Markers on a Open Street Map. If you click on a marker an overlay is shown with some info for this place. Very simple. On Android erything works fine.
On iOS the Info event finds the Feature on different Coordinates and if I pan or zoom the map the World Coordinates of the marker Place is changing, too.
To be a little bit more detailed:

- Map is shown and the markers are all in the right location
- clicking on a marker and logging the geo coordinates in the info event gets wrong geocoordinate (the overlay shows up, when I click more left and more in the direction of the bottom)
- MapInfoEvent logging code example:
```
private void MapOnInfo(object sender, MapInfoEventArgs args)
var loc = SphericalMercator.ToLonLat(args.MapInfo.WorldPosition.X, args.MapInfo.WorldPosition.Y);
Console.WriteLine($"Location - {loc.X} - {loc.Y}");
```
- after panning and clicking on the marker again the coordinates are changed (but the marker is still visible on the same position on the map tile)
- xamarin forms is used and the renderer on each plattform just wraps the mapcontrol

The MapControl is inside a grid. The code for moving to the position:
```
var sphericalMercatorCoordinate = SphericalMercator.FromLonLat((double)locations[0].Longitude, (double)locations[0].Latitude);
	                MapContent.Map.Viewport.Center = sphericalMercatorCoordinate;
	                MapContent.Map.Viewport.Resolution = MapContent.Map.Resolutions[14];
	                MapContent.MoveToCenter(locations[0].AsPosition);
	                MapContent.RefreshGraphics();
```

I am using MapsUI Version 1.4.0. Is something wrong in my code, or do you think it's a bug?

Thanks for help!
Markus

**Comment by pauldendulk** [comment]
What do you use for the Xamarin Forms implementation? Own code or charlennis package?

Did you use an older version before? Did you have the same problem?

There was a fix in ios position in 1.4. Perhaps this introduced a bug in forms.

Do you have the same problem if you run the info sample of mapsui.samples.ios?

**Comment by mintblau** [comment]
Hello Paul,
I've tried both. First my Own Renderer and after I've discovered the failure I have tried Charlennis Package. The same behaviour.

I have downgraded now to MapsUi Version 1.3.2 and it works on iOS. So it seems to be a new bug introduced by the positioning fix.

**Comment by pauldendulk** [comment]
Other things that could be relevant.

The MapInfo.WorldPosition is the position of the place where you clicked. Not the position of the marker that you clicked. If you want to center on the marker you have to use the MapInfo.Feature.Geometry.

Default an icon is centered on the point position. In many cases a pin is used. If you want the point of the pin to point to the position you need to use and offset.

**Comment by charlenni** [comment]
But @mintblau said, that the same code works perfect on Android.

**Comment by pauldendulk** [comment]
Yes. That means those last suggestions could not be the problem.

**Comment by pauldendulk** [comment]
It could also be a problem in the iOS skia view.

**Comment by pauldendulk** [comment]
@charlenni Your package has renderers around the Mapsui MapControls right? You also have a Xamarin.Forms only version in your branch? I intend to work on Xamarin.Forms the coming days.

**Comment by charlenni** [comment]
@pauldendulk Yes, the packages on NuGet is a wrapper around the native controls. And yes, the Forms branch contains a native Xamarin.Forms MapControl as PCL/.Net Standard which many extensions like adding features in Xamarin.Forms.Map style and a callout.

**Comment by pauldendulk** [comment]
@mintblau Is your MapControl right on top of the screen?

**Comment by pauldendulk** [comment]
The most likely cause of the problem is this change, introduced in 1.4
![image](https://user-images.githubusercontent.com/963462/40231216-804df8dc-5a9a-11e8-8dc5-9f5d2649fb38.png)
This is a fix for the native solution, but apparently introduces a bug in the forms solution. Somehow the skiaview behaves differently in the context of forms.

**Comment by pauldendulk** [comment]
@mintblau Could you test if the feature persists with 1.4.2?

**Comment by mintblau** [comment]
Hello Paul,
sorry I'm on holiday at the moment. I will test it next week, when I'm back.

**Comment by mintblau** [comment]
Hello Paul,

had time to test it now. Version 1.4.2 works!

Thx a lot, 
Markus

**Comment by pauldendulk** [comment]
Thanks for testing!
