### ISSUE TITLE
Odd artifacting with multiple RasterizingLayers

### ISSUE THREAD

**Issue by spaddlewit** [Mapsui/Mapsui#412]
I have two RasterizingLayers.. the grid, and the small purple polygons. Every time I pan, I get interesting artifacts for a split second before the map corrects itself. Any idea why this is occurring?

![rightafterpan](https://user-images.githubusercontent.com/29378443/40006299-05f2598c-5768-11e8-8de6-f0207c2776de.png)

![asecondlater](https://user-images.githubusercontent.com/29378443/40006349-21c752fc-5768-11e8-90ca-42861513e3d4.png)

**Comment by pauldendulk** [comment]
What exacly is the artifact? The tiny polygons? The labels? The yellow cells? Fo both images show the artifact?

**Comment by pauldendulk** [comment]
So the big purple squares are artifacts?

**Comment by spaddlewit** [comment]
Anything you see on the top screenshot that is different from the bottom screenshot is an undesired artifact. Every time I pan it does this for a split second, and different polygons are randomly affected each time.

**Comment by pauldendulk** [comment]
Perhaps the static skpaint is causing problems. I think that s it.

**Comment by pauldendulk** [comment]
If we fix this in master we release a latest build package. But that will netstandard1.3. Could you upgrade to that? Test with v2 beta 2.

**Comment by pauldendulk** [comment]
Explanation. There is a static skpaint defined in the the skia rendere for performance. If two threads render the two layers in parallel the will overwrite each others skpaint state.

**Comment by charlenni** [comment]
That could the problem. I reused the SKPaint, because it cost some time to recreate the SKPaint each time the renderer is called. It seems, that the Draw function is called from different threads, so that more than one thread use the SKPaint at the same time.

**Comment by pauldendulk** [comment]
Yes. We could cache the skpaint in the style at some point.

**Comment by charlenni** [comment]
But what to do, if the style changes? Should we update the SKPaint at each drawing?

**Comment by spaddlewit** [comment]
Awesome. Makes total sense. No, I can't use the .net standard v1.3 yet, but really, Mapsui was the only thing keeping me from upgrading my project. So I will be able to do so in the future.

**Comment by pauldendulk** [comment]
To fix the bug we will just recreate it every time. Or do you mean the style itself changes?

**Comment by charlenni** [comment]
If you recreate it each time, it isn't a problem except performance. But if you add it as data to the style, you have to reset all properties in the draw function from style values. If the style would be immutable, SKPaint could be created one time and than reused every time.

**Comment by pauldendulk** [comment]
Yes! Style should be immutable. But when we do that we should replace all styles with a better alternative.

**Comment by pauldendulk** [comment]
@spaddlewit This should be fixed with 1.4.2-beta.3.
