### ISSUE TITLE
MapControl.RotationLock logic is backwards

### ISSUE THREAD

**Issue by radderz** [Mapsui/Mapsui#413]
RotationLock = true means rotation is allow which is backwards to what the name suggests. The other "Locks" like ZoomLock and PanLock follow the logical naming.

**Comment by pauldendulk** [comment]
Oh. It was intended like this. What a silly mistake. Is this on all platforms?

**Comment by radderz** [comment]
Yes its in the shared code so they'd all follow the reverse logic currently
