### ISSUE TITLE
Bad performance  - spatialindex not used?

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#414]
When using a Mapsui 1.4.1 app with >1000 small polygons (non overlapping ), performance is considered as suboptimal.  Even when zoomed in to a few polygons the performance is not good, so it seems there is some issue with spatial indexing going on. 

I can create a reproducible case if needed.

**Comment by charlenni** [comment]
@bertt: That would be very nice. Save time to find this problem.

Btw. I draw whole vector tiles with much more than 1000 features, but normally this needs only around 300 ms.

**Comment by spaddlewit** [comment]
@charlenni I think he is adding a regular polygon layer, not using vector tiles.
Mapsui performance is terrible with a polygon layer. You can get better performance by using a RasterizingLayer.

**Comment by bertt** [comment]
yes indeed its a regular polygon layer. Can the performance of polygon layer be fixed?

**Comment by bertt** [comment]
maybe related: the work in 'performance' branch https://github.com/Mapsui/Mapsui/tree/performance

**Comment by pauldendulk** [comment]
For the short term you could try the rasterizing layer. Look at the shapefilesample.

**Comment by spaddlewit** [comment]
@bertt Just a heads up, something that tripped me up when I first started using RasterizingLayer, is that you need to use the underlying projection of the map. My polygon layer was in WGS84 originally and I didn't know why it wasn't showing up as a RasterizingLayer. I had to reproject the coordinates first.

**Comment by pauldendulk** [comment]
@spaddlewit oh wait. Shapefilesample is wgs84 but does not reproject.

 .

**Comment by pauldendulk** [comment]
Thanks for pointing out what @pauldendulk has said about this :)

**Comment by bertt** [comment]
@charlenni very simple polygons, only 5 vertices each

**Comment by charlenni** [comment]
@bertt Are this polygons placed in a small area or all over the map?

**Comment by bertt** [comment]
@charlenni they are tile boundaries at level 14, 1000+ polyons spread over the world

**Comment by pauldendulk** [comment]
@bertt The sample project will still be interesting for us to investigate.

**Comment by radderz** [comment]
I have written an RTREE index in C# that my company uses for spatial matching to millions of roads/addresses in milliseconds that may be able to improve the speed at which objects are found to be "on screen" for rendering. How does mapsui currently decide what to render on a polygon layer? Does it just iterate for all polygons whos bounding boxes overlap with the current viewport?

Does this also affect polylines?

**Comment by pauldendulk** [comment]
Yes, that's how it works. No spatial index at all. Bert assumes this is a spatial index problem because even with a few features in view it is slow but there might be other explanations like 'multiple enumerations' in an IEnumerable. I had this problem in my vector tile implementation. Fixing it had a huge impact.

**Comment by pauldendulk** [comment]
Here it is: https://github.com/Mapsui/Mapsui/commit/13c4485ebbfc53817b23dccae526f538959470c1

**Comment by bertt** [comment]
Why no spatial index is being used?

**Comment by pauldendulk** [comment]
Because there is none. 

It would be the responsibility of the datasource.

Do you use a MemoryLayer.

**Comment by bertt** [comment]
```
        map.Layers.Add(CreateLayer(polys, fillColor, outlineColor));
      
        public static ILayer CreateLayer(List<Polygon> polys, Color fillColor, Color outlineColor )
        {
            return new Layer("Polygons")
            {
                DataSource = new MemoryProvider(polys){ CRS = "EPSG:4326" },
                Style = new VectorStyle
                {
                    Fill = new Brush(fillColor),
                    Outline = new Pen
                    {
                        Color = outlineColor,
                        Width = 4,
                        PenStyle = PenStyle.Solid,
                        PenStrokeCap = PenStrokeCap.Round
                    }
                }
            };
        }
```

**Comment by charlenni** [comment]
I think, it is a IProvider problem. IProvider has GetFeaturesInView(BoundingBox, Resolution). All Features, that are returned, are drawn. But even when all polygons are returned, there shouldn‘t be a problem. Drawing 1000 polygons with solid stroke is very fast with Skia.

**Comment by pauldendulk** [comment]
This is the implementation of the MemoryProvider.GetFeaturesInView

```c#
 public virtual IEnumerable<IFeature> GetFeaturesInView(BoundingBox box, double resolution)
{
	if (box == null) throw new ArgumentNullException(nameof(box));

	lock (_syncRoot)
	{
		var features = Features.ToList();

		// Use a larger extent so that symbols partially outside of the extent are included
		var grownBox = box.Grow(resolution*SymbolSize*0.5);

		foreach (var feature in features)
		{
			if (feature.Geometry == null)
				continue;

			var boundingBox = feature.Geometry.GetBoundingBox();
			if (boundingBox!= null && grownBox.Intersects(boundingBox))
			{
				yield return feature;
			}
		}
	}
}
```
You could create your own MemoryProvider and play around with the implementation. Perhaps not use yield.

Copy this to your own code:
https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Providers/MemoryProvider.cs

**Comment by pauldendulk** [comment]
oh, and @bertt do you use the MinimalTransformion. Could it be the MemoryProvider does not apply it propertly for GetFeatureInView?

**Comment by bertt** [comment]
Here a sample Android app demonstrating the problem 

https://github.com/bertt/Mapsui/tree/polygons_perf/Samples/Bertt.Samples.AndroidPolygons

its drawing random tile boundaries over the world (level 14), zoom in and see the performance dropping... 

![small](https://user-images.githubusercontent.com/538812/40186431-5c7dd0c6-59f5-11e8-8b66-eac3739fa3cc.jpg)

Note: number of polygons turned out to be 10000.

**Comment by pauldendulk** [comment]
Here you can see the fix: https://github.com/Mapsui/Mapsui/commit/ac83a39764948216c2a2670f88422e1a9f0282b8

The problem was that first the transformation was done and after that the box was grown (for symbol size) but this growing was done with resolutions that did not make sense in the coordinate system of the provider.

**Comment by pauldendulk** [comment]
@radderz Could you roughly describe how you implemented spatial indexing? Did you implement it for a specific kind of layer?

**Comment by bertt** [comment]
Javascript spatial indexers by mourner: https://github.com/mourner/rbush (points/rectangles), https://github.com/mourner/kdbush (points)

**Comment by pauldendulk** [comment]
Let's port it :). But what mourner made was more than just spatial indexes wasn't it. He made something to allow fast hover info.

**Comment by radderz** [comment]
Hi Paul, I haven't implemented it in mapsui at all, I had implemented it for a map matching algorithm and address polygon matching services we use in our platform.

It's just an RTREE spatial index written in C# that can be used for any type of spatial object for distance and intersection of boundary queries. I can clean my implementation up and provide it when I get a chance if you'd like. It's much faster than do a distance check for every item. And the more objects the more the index matters.

**Comment by bertt** [comment]
Maybe try this? https://github.com/marchello2000/kdbush

**Comment by radderz** [comment]
It would be portable enough to use it as is, but it does a bit more than what you'd be wanting it for.

**Comment by pauldendulk** [comment]
ah, that kdbush project is already a port. It has no nuget package though. And it's not a lot of code it seems.

**Comment by pauldendulk** [comment]
@radderz @bertt Thanks for the info. I will open een new issue for adding a spatial index. I won't be able to work on this myself in the short term.

**Comment by bertt** [comment]
tested fix: works much better 👍 is it going to master branch too (so it gets in a package)?

**Comment by pauldendulk** [comment]
It should be in the latest build package if the build succeeds: http://mapsui.github.io/Mapsui/documentation/NuGet-of-latest-build.html
