### ISSUE TITLE
Layers doc

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#419]
Hello, 
(if the case was already please send me there, thanks)

Where I can find any info (documentation) about what are & how work :
MemoryLayer
ImageLayer
LabelLayer
TileLayer
BaseLayer
etc.

and when I should use them (what for)?

Many Thanks,
Łukasz

**Comment by lukaszpitulski** [comment]
and I'm not asking for Samples, I need descriptions, step by step, details, "Mapsui for dummies", a guide.
404 here https://mapsui.github.io/mapsui

**Comment by pauldendulk** [comment]
The casing is wrong. It is here: http://mapsui.github.io/Mapsui/
Press the documentation tab at the top. 

The documentation is work in progress. It will improve gradually. Two weeks ago we started the web site itself using docfx. The content will be improved step by step. For the layers we don't have specific documentation apart from the samples and the code itself.

**Comment by lukaszpitulski** [comment]
Thanks!
