### ISSUE TITLE
Android: No Map after upgrade to 2.0.0-beta.2

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#420]
Hi, I followed the Android Getting started with Mapsui 1.4.1 (http://mapsui.github.io/Mapsui/documentation/getting-started-android.html) app works.

Then after upgrading Mapsui Nuget package to 2.0.0-beta.2  no map show up :-(

Can this be fixed?

**Comment by bertt** [comment]
Project uses Android 8.1 (Oreo)

**Comment by pauldendulk** [comment]
Manifest from the sample:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto">
	<uses-sdk />
	<application android:largeHeap="true" android:hardwareAccelerated="false" android:theme="@android:style/Theme.Material"></application>
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>
```

**Comment by bertt** [comment]
just recompiled same code again and now it works hmmm... closing issue for now

**Comment by pauldendulk** [comment]
I have this problem if I switch between the 1.4 and 2.0 branch. Incremental build does not work for some reason. Perhaps because new versus old csproj, or netstandard versus pcl.
