### ISSUE TITLE
MapInfoEventArgs with null properties in Info event

### ISSUE THREAD

**Issue by antunesl** [Mapsui/Mapsui#421]
The **MapInfoEventArgs** object in **Info** event has null values for the Layer Name and Feature Fields (in MapInfo property), while the screen and world positions are ok.
This behavior only happens in iOS, on Android all the properties are filled as expected..

My scenario is a XamarinForms APP for iOS and Android, with custom renderers in both projects. I've also tried the project 'Mapsui.Samples.iOS' in the Samples folder and the behavior is the same, I'm suspicious that's not a thing with the Xamarin Forms but I'm not sure.

I'm using the 2.0.0-beta2 version, but I also tried the 1.4.1 and 1.4.2-beta2, all with the same behaviour.

**Code**
```c#
_mapView.NativeMap.Info += async (sender, args) =>
{
    var layername = args.MapInfo.Layer?.Name;
    var featureLabel = args.MapInfo.Feature?["Label"]?.ToString();
    var featureType = args.MapInfo.Feature?["Type"]?.ToString();

    Debug.WriteLine("Info Event was invoked.");
    Debug.WriteLine("Layername: " + layername);
    Debug.WriteLine("Feature Label: " + featureLabel);

    Debug.WriteLine("World Postion: {0:F4} , {1:F4}", args.MapInfo.WorldPosition?.X, args.MapInfo.WorldPosition?.Y);
    Debug.WriteLine("Screen Postion: {0:F4} , {1:F4}", args.MapInfo.ScreenPosition?.X, args.MapInfo.ScreenPosition?.Y);
};
```

**Output**

**iOS**
[0:] Info Event was invoked.
[0:] Layername: 
[0:] Feature Label: 
[0:] World Postion: 1814804.9028 , 10543159.4944
[0:] Screen Postion: 131.5000 , 166.0000

**Android**
[0:] Info Event was invoked.
[0:] Layername: Polygon Layer
[0:] Feature Label: Polygon Label
[0:] World Postion: 335616.3066 , -779236.4356
[0:] Screen Postion: 364.0000 , 465.0000

**This is iOS My Custom Renderer for the Map**
```c#
[Preserve(AllMembers = true)]
public class MapViewRenderer : ViewRenderer<MapsUIView, Mapsui.UI.iOS.MapControl>
{
    Mapsui.UI.iOS.MapControl mapNativeControl;
    MapsUIView mapViewControl;

    protected override void OnElementChanged(ElementChangedEventArgs<MapsUIView> e)
    {
        base.OnElementChanged(e);

        if (mapViewControl == null && e.NewElement != null)
            mapViewControl = e.NewElement;

        if (mapNativeControl == null && mapViewControl != null)
        {
            var rectangle = mapViewControl.Bounds;
            var rect = new CGRect(rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height);

            mapNativeControl = new Mapsui.UI.iOS.MapControl(rect)
            {
                Map = mapViewControl.NativeMap,
                Frame = rect
            };

            SetNativeControl(mapNativeControl);
        }
    }
}
```

**Comment by antunesl** [comment]
Yes it seems the same thing, sorry for the duplicate. I'll subscribe the #417 for news, thanks.

**Comment by pauldendulk** [comment]
I see you are using forms. I'll keep this open because I want to know if this is fixed in forms as well.

**Comment by pauldendulk** [comment]
@antunesl I just release 1.4.2-beta.3. I tested with Mapsui.Samples.iOS. Did not test with a forms implementation, so I am curious if this works for you.

**Comment by antunesl** [comment]
@pauldendulk this new version works correctly in forms. I created a [small application](https://github.com/antunesl/mapsui-forms-sample) in Xamarin Forms just to test mapsui related cases, and version **1.4.2-beta.3** works perfectly on iOS and Android.

Thanks for the quick fix!

**Comment by pauldendulk** [comment]
Thanks for testing. I will release 1.4.2 it.
