### ISSUE TITLE
White translucent fill covering map view v1.4.2

### ISSUE THREAD

**Issue by spaddlewit** [Mapsui/Mapsui#422]
Sorry @pauldendulk , not quite out of the woods yet! :)

On both iOS and UWP (Skia), I am getting what seems to be a 50% white translucency (sometimes) rendered overtop my mbtiles and polygon layers -- the top point layer doesnt appear to be affected.

My layers are:

MBTiles
Polygon
Point

I rolled back to 1.4.1, and I don't get this rendering issue. So it's got to be something that changed between 1.4.1 and 1.4.2.

**Comment by pauldendulk** [comment]
Do you have a screenshot?

I don't see this in the Mapsui samples. What could be the difference?

**Comment by pauldendulk** [comment]
oh i can reproduce it

![image](https://user-images.githubusercontent.com/963462/40573336-78656eb2-60c0-11e8-86db-25f602161a20.png)

**Comment by pauldendulk** [comment]
Fixed it. Commit will be later.
