### ISSUE TITLE
MaxZoomIn for ZoomInOutWidget

### ISSUE THREAD

**Issue by andrearivera8** [Mapsui/Mapsui#424]
Hi, is there a way to limit the MaxZoomIn of the ZoomInOutWidget? I have a OpenStreetMap as a TileLayer but it does not respect the MaxZoomIn of the TileLayer. 

Thank you.

**Comment by pauldendulk** [comment]
Is this in the latest version? I thougt i fixed this at some point.

**Comment by andrearivera8** [comment]
No, it wasn´t. I have just updated Mapsui package and my Mapsui.UI.InfoEventArgs is given me an error. I changed it to Mapsui.UI.MapInfoEventArgs and it responded with an Unhandled Exception: System.TypeLoadException: Could not resolve type with token 0100002f (from typeref, class/assembly Mapsui.UI.MapInfoEventArgs, Mapsui, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null).

I cleaned and rebuilded the solution but the problem still remains. Because of this problem, I cannot check if the ZoomInOutWidget works.

**Comment by pauldendulk** [comment]
This is the sample: https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/OsmSample.c

```
CRS = "EPSG:3857",
Transformation = new MinimalTransformation()
```

**Comment by andrearivera8** [comment]
Thank you, now it worked. The problem was that I had the CRS defined on both pages: the MapUIView page and the principal Map page. So, the solution was to only include it on the MapUIView page.

**Comment by pauldendulk** [comment]
Great
