### ISSUE TITLE
Problems compiling Mapsui.Sample.Android with newest master

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#425]
I getting the following error when trying to compile master:

````Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Itinero, Version=1.3.2.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Itinero.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Mapsui.Samples.Android			
````
I assume, there is a NuGet package missing.

**Comment by charlenni** [comment]
Adding Itinero by hand solved the problem.

**Comment by pauldendulk** [comment]
I don't understand why this is a problem now. The package should be derived fron it s dependencies.

**Comment by charlenni** [comment]
It didn't worked for me. Updated to 15.7.2, updated all Mapsui related things, removed all bin and obj folders and than made a "Build all" for the solution. Itinero wasn't in the installed NuGet packages.

**Comment by pauldendulk** [comment]
Yes. Don t think you made a mistake. I just don t understand why it works this way. Do we need to add every nuget package in the dependencies in the head as well?

**Comment by charlenni** [comment]
For me it seems so. Looked into the config files, but there is "automatic" set to true. And another place where to set such things, I didn't find.

**Comment by charlenni** [comment]
Yes, that could be the reason. But in this case we have to add it. Correct?

And the next problem is with System.Runtime.Extension and tests, had to install this too. After this, I want to run all tests, but all Xaml tests fail. Error is 

````
Message: System.TypeInitializationException : Der Typeninitialisierer für "SkiaSharp.SKAbstractManagedStream" hat eine Ausnahme verursacht.
  ----> System.BadImageFormatException : Es wurde versucht, eine Datei mit einem falschen Format zu laden. (Ausnahme von HRESULT: 0x8007000B)
````

Seems, that I had to stop for today :)

**Comment by pauldendulk** [comment]
I upgraded all skia packages to the latest. But latest svg is 1.60.0 and the others are 1.60.1. Perhaps this could cause problems. I noticed this discrepancy in an earlier release where I had trouble and then reverted to the latest common release.

**Comment by pauldendulk** [comment]
And I am not sure if we have to add all these packages that did not need references in v1.4. Perhaps there is something else thats wrong.

**Comment by charlenni** [comment]
I'm only work in the master. You said, master is 2.0. So there aren't any changes to 1.4.
