### ISSUE TITLE
Cleaning up MapControls

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#428]
We have taken an initial step in using a shared MapControl. Now we have to clean this up further and move more code to the shared project.

Some things I want to achieve:
- No code in the shared MapControl that is not used at all. Actually this a general rule for all software. There is 'no nice for later'. If you need it later, then add it later.
- All code in the shared MapControl should actually be used by all four platforms.
- There should be no #if's in the shared MapControl except for the usings. All shared code should be equal to all platforms. If it is specific for a platform then add it to that platforms MapControl.

First I am going to remove the methods that are not used at all.

**Comment by charlenni** [comment]
Are you now ready with deleting functions? With this way, there wouldn't much progress in the shared MapControl. To create a new function in shared MapControl, you have to implement it on all platforms. But how many people know all platforms (WPF, UWP, Android, iOS and so on)? If you know WPF and implement there a new function, you wouldn't look, if such a function is already implemented in all other MapControl except WPF. And if someone creates a new MapControl, should we than remove all shared functions until s/he as implemented them all in the new MapControl? Isn't it better to have a default function in the shared code, and when someone comes and thinks, that it is usefull for this or that MapControl alter the code of that MapControl?

And the #if's in the code: sometimes a native control has the function already, but all others not. What to do with the override or new?

I used this functions for the Xamarin.Forms implementation. So I have to reimplement the functions, you are deleted, in my MapControl. Is this right?

**Comment by pauldendulk** [comment]
Perhaps a larger part of the rotation logic could be move to the shared project, and there will be other parts too, but this is not something I actively work on now. We do it for the code we work on for some other feature.
