### ISSUE TITLE
WPF - brightness

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#434]
Hi,

is it way to change programmatically brightness of the map (with all layers, features, etc... WPF MapControl, RenderMode.Skia)? 
Or maybe exists any widget for it?

Thanks,
Łukasz

**Comment by pauldendulk** [comment]
No there is not. 

Some possible workarounds:
- If you set the background color to white and use a reduced Opacity on the background layer you get less intense colors. Using this on overlays will also show the background, so perhaps this is not what you want.
- Use some semi transparent overlay on top of the map control. Perhaps in WinForms, if this is not possible it should be possible in WPF. You will have to use a parent element to hold MapControl and the overlay together. 

A widget would indeed be a good idea. I am not that far removed from adding a plugin system for Mapsui. If this is realized it will not be too hard to make a widgets that overlays a semi transparent white surface on top of the map.

**Comment by lukaszpitulski** [comment]
ok, thanks.
