### ISSUE TITLE
Mapsui.UI.MacOS ?

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#435]
Is there a plan to support MacOS (project Mapsui.UI.MacOS)? Or better wait for a Xamarin.Forms mapcontrol.

**Comment by charlenni** [comment]
The native Xamarin.Forms Mapsui MapControl should work with the following platforms: [SkiaSharp.Views.Forms](https://github.com/mono/SkiaSharp/tree/master/source/SkiaSharp.Views.Forms)

**Comment by bertt** [comment]
where can we find developments on native Xamarin.Forms Mapsui MapControl (if any)?

**Comment by pauldendulk** [comment]
None in Mapsui. Charlenni has a branch somewhere.

**Comment by pauldendulk** [comment]
Lets call it 'pure' Xamarin.Forms, to avoid overused 'native'.

**Comment by pauldendulk** [comment]
There is MapControl shared code. I am working on that. The pure Xamarin.Forms control should fit in.

**Comment by charlenni** [comment]
You could find it [here](https://github.com/charlenni/Mapsui/tree/Forms). It is not complete, but in the moment I could not work on it, because VS 2017 couldn't compile it anymore on my PC. MS and Xamarin are working on this problem.

It mimics the Xamarin.Forms.Maps MapView and things like Position and MapSpan. Additionally it implements a CallOut.

**Comment by charlenni** [comment]
Ok, let's say, it doesn't need native renderers for Xamarin.Forms. In this implementation it is a PCL, but should be a .Net Standard library for Mapsui 2.0.

The shared code was implemented for this Xamarin.Forms part and than converted to all other MapControls, so it should fit in :)

**Comment by charlenni** [comment]
@bertt Are you interested to work on the Xamarin.Forms implementation?

**Comment by bertt** [comment]
No I'm using the wrapper technique for now, works ok so far

**Comment by pauldendulk** [comment]
So, is there any follow up? Do you intent to build a native mac os version? Actually I thing it is not worth it. It is hard enough to keep the iOS version stable. Support for mac os though pure Xamarin.Forms will be easy.

**Comment by bertt** [comment]
think we can close this issue. To summarize: there is no MacOS support until Xamarin.Forms mapcontrol is ready.

**Comment by charlenni** [comment]
I have a follow up. I now added a sample for Xamarin.Forms for Mac. It uses Xamarin.Forms 3.0. Looks like this:

![bildschirmfoto 2018-06-18 um 12 38 18](https://user-images.githubusercontent.com/4381223/41531794-db1b69c6-72f4-11e8-81b3-583ade12a75c.png)
