### ISSUE TITLE
System.Exception after Map.Info Event

### ISSUE THREAD

**Issue by pingurus** [Mapsui/Mapsui#437]
After I handle the Map.Info event, a System.Exception is raised by Mapsui.

> System.Exception
>   HResult=0x80131500
>   Nachricht = Point is empty
>   Quelle = Mapsui.Geometries
>   Stapelüberwachung:
>    bei Mapsui.Geometries.Point.get_X()
>    bei Mapsui.UI.Wpf.MapControl.MapControlMouseMove(Object sender, MouseEventArgs e)
>    bei System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    bei System.Windows.Input.InputManager.ProcessStagingArea()
>    bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    bei System.Windows.Input.MouseDevice.Synchronize()
>    bei System.Windows.Input.MouseDevice.PostProcessInput(Object sender, ProcessInputEventArgs e)
>    bei System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
>    bei System.Windows.Input.InputManager.ProcessStagingArea()
>    bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    bei System.Windows.Application.RunDispatcher(Object ignore)
>    bei System.Windows.Application.RunInternal(Window window)
>    bei System.Windows.Application.Run(Window window)
>    bei System.Windows.Application.Run()

I'm using Mapsui 2.0.0-beta-3 with wpf
Is this a bug or am I doing something wrong?

**Comment by pauldendulk** [comment]
Might be a bug. There is the info sample in Mapsui.Samples.Wpf. What are you doing different?

The Mapsui Point has an 'empty' state. Which is not a common concept in .NET. It is not null but while the state is empty it will throw when getting x/y.

**Comment by pingurus** [comment]
At the first glance, the only difference is that I use a writable layer, for the rest I don't think it should affect mapsui. 

Am 7. Juni 2018 09:13:43 MESZ schrieb Paul den Dulk <notifications@github.com>:

**Comment by pauldendulk** [comment]
I can reproduce a similar bug (not exactly the same unfortunately) if I add an default Point to a WritableLayer In InfoLayerSample.cs. This is still a bug, but perhaps you also added a default Point somewhere. You could try to avoid this.

```c#
        public static Map CreateMap()
        {
            var map = new Map();

            var writableLayer = new WritableLayer();
            writableLayer.Add(new Feature { Geometry = new Point()});
            map.Layers.Add(OpenStreetMap.CreateTileLayer());
            map.Layers.Add(CreateInfoLayer(map.Envelope));
            map.Layers.Add(CreateHoverLayer(map.Envelope));
            map.Layers.Add(CreatePolygonLayer());
            map.Layers.Add(writableLayer);
            map.Layers.Add(CreateLineLayer());

            map.InfoLayers.Add(map.Layers.First(l => l.Name == InfoLayerName));
            map.InfoLayers.Add(map.Layers.First(l => l.Name == PolygonLayerName));
            map.InfoLayers.Add(map.Layers.First(l => l.Name == LineLayerName));
            map.HoverLayers.Add(map.Layers.First(l => l.Name == HoverLayerName));

            return map;
        }
```

**Comment by pingurus** [comment]
I doubt that I add a default point anywhere, since I always use Geometry = SphericalMercator.FromLonLat(lon,lat) when constructiong the Feature.
I'd still have to checck wether, through some chance, there are default points in the layer at runtime.

**Comment by charlenni** [comment]
I get is error too. It is in line 537 of Mapsui.UI.WPF.MapControl
````
_map.Viewport.Transform(
  _currentMousePosition.X, _currentMousePosition.Y,
  _previousMousePosition.X, _previousMousePosition.Y);
````
because `_previosMousePosition` is `Point.Empty`.

I could reproduce it only when debuging. Set a breakpoint while dragging the map. Than continue. Map comes to front and than enter the map without pressed mouse button. `_mouseDown` is true, but _previosMousePosition is `Point.Empty`. Hope that helps.

**Comment by pauldendulk** [comment]
Thanks @charlenni that allowed me to reproduce it. The stack trace also indicated it should be at this location. I am not sure when this could ever happen in any regular situation. This is old code and I have never see this before. I now simply check if the previous point is empty.

**Comment by pauldendulk** [comment]
I assume this fixed. Please reopen if it is  not in the next release.

**Comment by pauldendulk** [comment]
I now understand how this problem arose. At some point when change the _previousMousePosition field from System.Windows.Point, which is a struct to Mapsui.Point which is a class. There was a check on the default value of the struct, this should have been replaced by a null check.

**Comment by pauldendulk** [comment]
@pingurus Did you also see this exception when you did not hit a breakpoint?

**Comment by pingurus** [comment]
Indeed, it only occurs when the application hits a breakpoint.

**Comment by pauldendulk** [comment]
I tried again and can't reproduce it. I did find another small bug though, it is caught so no real issue but show up in the logs so I will fix it. It would be great if you could provide a test project. Please make a new issue for it.

**Comment by IldarKhayrutdinov** [comment]
@pauldendulk done #1276 it seems that required to move the mouse when Ctrl pressing
