### ISSUE TITLE
Coordinate system, projection, CRS, Srs, Tile, Base Layer, Map... EPSG

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#440]
Hi,
(if the case was already, please, send me there, thanks)

I need advice, indication of the correct direction, clarification, etc.
I have and I do: (Mapsui 1.4.1)

```
MapControl.Map = new Map 
{
    Transformation = new MinimalTransformation(),
    CRS = "EPSG:3857"
    BackColor = Mapsui.Styles.Color.Gray,
};
```

next

`Map.Layers.Insert(0, base_Layer);`

where base_Layer is **TileLayer** from OpenStreetMap and from WMTS server
where **CRS** is always null
and where the layers have (from BruTile.TileSchema)
```
    OSM - **EPSG:3857** 
    WMTS - some **EPSG:900913** others **EPSG:4326** 
```
(EPSG:900913 = EPSG:3857)

also in all others layers ( `MapControl.Map.Layers.Add(Layer);` ) 
when are created CRS = null but after adding into Map.Layers CRS = Map.CRS (by Mapsui)

Am I doing these correctly? Have I missed something?
What is meaning of CRS, SRS, Transformation? (doc)

Could you add into MinimalTransformation constructor something like this?
```
            _toLatLon["EPSG:900913"] = SphericalMercator.ToLonLat;
            _fromLatLon["EPSG:900913"] = SphericalMercator.FromLonLat;
```

Then (maybe) I can do Map.CRS = "EPSG:900913";

Best Regards,
Łukasz

**Comment by pauldendulk** [comment]
SRS is the same as CRS.

> EPSG:900913 = EPSG:3857. 

Yes, correct. EPSG:900913 is an old notation. It was a fun idea arisen in the OSS community (900913 is google in numbers code). EPSG:3857 is the official code, backed by the OGC.

> Map.CRS = "EPSG:900913";

Well EPSG:3857 is the official code and I don't think you need to do this. I assume you add this for the WMTS layers, but there is no projection of tiles. You displayed map is in the google projection, so no projection needed.

I can help you better of you state specifically what you want to achieve.

**Comment by lukaszpitulski** [comment]
I would like to have Map compatible with
    OpenStreetMap  EPSG:3857 
    local WMTS layers  EPSG:900913 and EPSG:4326 
and (here is something outstanding, also WMTS) GeoPortal  EPSG:2180 (WGS 84 ... ?4326?) 

I wonder if I'm creating Map correctly.
Do I need these?:
```
Transformation = new MinimalTransformation(),
CRS = "EPSG:3857"
```
If I create Map without CRS (null), will all layers (as BaseLayer) be compatible with it and be displayed correctly?

Finally, I would like to change BaseLayer without creating Map from scratch.
I.e. create the Map once and next replace `Map.Layers[0]` as many times as I need (layer with any CRS).

```
Map.Layers.Remove(currentBaseLayer);
Map.Layers.Insert(0, newBaseLayer);
MapControl.Refresh()
```

**Comment by lukaszpitulski** [comment]
Also, I'm not sure what with CRS for layers. When Map CRS = null then Map.Layers.CRS = null, when MAP.CRS = ABC:123 then Map.Layers = ABC:123, unless during creation a layer will be set CRS.

With TileLayer (baseLayer, Layer[0]) is a little different story because they have (BruTile) Schema where is Srs (also Name, TileMatrixSet, etc.), but CRS is null.

So, I'm thinking what to do, what solution will be correct here.
Maybe something like this:
`baseLayer.CRS = baseLayer.CRS ?? ((TileLayer)baseLayer).TileSource.Schema.Srs;`
OR
`baseLayer.CRS = baseLayer.CRS ?? Map.CRS;`
OR
`baseLayer.CRS = baseLayer.CRS ?? /*Map.CRS*/ ((TileLayer)baseLayer).TileSource.Schema.Srs.Replace("urn:ogc:def:crs:", "").Replace("::",":");`
OR
`baseLayer.CRS = leave it as it is (null)`

For OSM layer the Srs is EPSG:3857
but for WMTS layers the Srss are  urn:ogc:def:crs:EPSG::4326 and  urn:ogc:def:crs:EPSG::900913  (TileMatrixSet is without urn:ogc:def:crs:).

So, what are Best Practices for Coordinate System in Mapsui ?

**Comment by lukaszpitulski** [comment]
**UPDATE**

any baseLayer EPSG:4326 doesn't work with Mapsui (for me)

**Comment by lukaszpitulski** [comment]
**UPDATE**
EPSG:4326 layers don't work in Mapsui
(blank map)

**Comment by lukaszpitulski** [comment]
I have replaced Insert by Add and Move, works better now.

```
Map.Layers.Remove(Layer_0);
Map.Layers.Add(newLayer);
Map.Layers.Move(0, newLayer);
MapControl.Refresh();

```
But I must to do this (ugly solution)
```
Map.NavigateTo(Map.Resolutions[0]);
Map.NavigateTo(Mapsui.Projection.SphericalMercator.FromLonLat(0, 0));
```
then I see the baseLayer (map).

But still I lose all Layers' Features on EPSG:4326, EPSG:2180 baseLayer. (the features created on baseLayer EPSG:900913/EPSG:3857)

**Comment by lukaszpitulski** [comment]
ooo think now I see something... and I think I've started understanding how it is in Mapsui...
`Map.NavigateTo(Mapsui.Projection.SphericalMercator.FromLonLat(0, 0));`
The center point (0,0) is always the same (canvas/Map).
For EPSG:900913 it is coordinate [0N,0E].
For EPSG:2180  it's somewhere on bottom-left (outside the baseLayer).
For EPSG:4326  it's more on North (NE) like in 900913.

Looks like I will need a real FeaturePointsTransformer to show features from one CRS on another CRS.

Still my questions (two posts above) are current :)

**Comment by lukaszpitulski** [comment]
The app stores the data (feature's geo-params/coordinates) in WGS84 (longitude, latitude) as WellKnownText.
E.g. POINT (19.0521564483643 52.2834587097168)

When the map (base Layer) is EPSG:3857 then the app uses SphericalMercator FromLonLat/ToLonLat and all is fine.
POINT (2120876.35 6851541.60)
[like here](https://epsg.io/transform#s_srs=4326&t_srs=3857&x=19.0521564&y=52.2834587)

But when the map is EPSG:4326 then using SphericalMercator makes mess. (-180.0 -90.0 180.0 90.0 so the example point is in a galaxy far, far away.... " 2120876.35°E  6851541.60°N " )
:(

Is it way to automatically (by Mapsui) recognize in SphericalMercator what CRS is for the map and then use correct transformation (LonLat, WKT, <-> ) ?
Or I must to do it myself in the app code.

What for is and what is doing Map.Transformation (exactly MinimalTransformation) ?

Thanks,
Łukasz

**Comment by lukaszpitulski** [comment]
I need all details about things in Mapsui.Projection

Thanks

**Comment by pauldendulk** [comment]
I got started on some documentations on projections:
https://github.com/Mapsui/Mapsui/blob/master/docfx/mapsui/documentation/projections.md

**Comment by pauldendulk** [comment]
Some random reactions.

You should not set the CRS on the Layers. It is automatically set by Mapsui. It is an ugly solution. It will change.

I was thinking about adding a Map.NavigateToFullEnvelope().

You need to choose what projection your Map should be. In your case I think this should be either EPSG:4326 or EPSG:3857.

**Comment by pauldendulk** [comment]
> If I create Map without CRS (null), will all layers be compatible with it and be displayed correctly?

If the Map CRS is null Mapsui does not know what the target projection is and will no be able to reproject from DataSource to Map. It still could be displayed correctly if your DataSource is in the same projection as the Map.

**Comment by pauldendulk** [comment]
> What for is and what is doing Map.Transformation (exactly MinimalTransformation) ?

The transform method takes a fromCRS and toCRS. There from and to are taken from the DataSource.CRS and Map.CRS. It will try to lookup if it has the projections available.
 
http://mapsui.github.io/Mapsui/api/Mapsui.Projection.ITransformation.html#Mapsui_Projection_ITransformation_Transform_System_String_System_String_Mapsui_Geometries_IGeometry_

**Comment by pauldendulk** [comment]
Important to know. Mapsui is not capable of transforming images. So no transformation of tiles are rasters. No attempt will be made to transform and the CRS fields will be ignored.

**Comment by charlenni** [comment]
Perhaps it is time to make this clear. It was the most difficult point when I start with Mapsui. People expect a coordinate system like Google provides. But Mapsui doesn’t have such thing. And without a documentation about this, it is very difficult.

**Comment by pauldendulk** [comment]
>  People expect a coordinate system like Google provides

What do you expect there?

Would the added documentation have helped you here?
http://mapsui.github.io/Mapsui/documentation/projections.html

**Comment by lukaszpitulski** [comment]
http://mapsui.github.io/Mapsui/documentation/projections.html
I read that. Thanks but it's not enough for my solution here. (is more like what not to do)
Maybe I don't understand how it works in Mapsui.
I worry that I'm missing DataSource in my solution (I don't use it at all).

Still I'm not sure how to change base layer and keep all transformation, layers and features coordinates working.
Maybe my descriptions are not clear, please let me explain it again.
(I don't want to transform images)

What I need is change the base layer (Layers[0]) without recreating the Map.
And have the Map and all layers compatible with the base layer is, without reloading anything.

**Comment by lukaszpitulski** [comment]
So, what I do is:
```
MapControl.RenderMode = RenderMode.Skia;
MapControl.Map = new Map
{
	Transformation = new MinimalTransformation(),
	CRS = "EPSG:3857",
	BackColor = Mapsui.Styles.Color.Gray
};
```
next, for example as first base layer is OSM
```
var VisibleLayer = Mapsui.Utilities.OpenStreetMap.CreateTileLayer();
Map.Layers.Add(VisibleLayer);
```
and next I add all others layers I need
```
ObjectsLayer = new WritableLayer
{
	Name = "ObjectPointLayer",
	Style = null
};
MapControl.Map.Layers.Add(ObjectsLayer);

FenceLayer = new WritableLayer
{
	Name = "FencePolygonLayer",
	Style = CreatePolygonStyle()
};
MapControl.Map.Layers.Add(FenceLayer);

MarkersLayer = new WritableLayer
{
	Name = "MarkerPointLayer",
	Style = null
};
MapControl.Map.Layers.Add(MarkersLayer);
```
and a few more (all WritableLayer so **I don't know what with DataSource, the Transformer.FromCRS is always null**, for each layer).

And last one is the edit layer
```
EditLayer = new WritableLayer
{
	Name = "EditLayer",
	Style = CreateEditLayerStyle()
};
MapControl.Map.Layers.Add(EditLayer);
MapControl.Map.Layers.Add(new VertexOnlyLayer(EditLayer) { Name = "VertexLayer" });
MapControl.Map.InfoLayers.Add(MapControl.Map.Layers.First(l => l.Name == "EditLayer"));
```

So, when I want to change the base layer, I do:
```
Map.Layers.Remove(Map.Layers[0]);

var VisibleLayer = ((Wmts)mapset).CreateTileLayer(); //the layer is from WMTS as EPSG:4326 (the mapset - is obj with all params to create wmts TileLayer)
Map.CRS = ((TileLayer)VisibleLayer).TileSource.Schema.Srs.Replace("urn:ogc:def:crs:", "").Replace("::", ":");
Map.Layers.Add(VisibleLayer);
Map.Layers.Move(0, VisibleLayer);
```
and to keep all layers.CRS the same like Map.CRS I do:
```
foreach (var layer in Map.Layers)
{
	layer.CRS = Map.CRS;
	layer.Transformation = Map.Transformation;
	//but what with e.g. layer.Envelope, Transformer.FromCRS and all the features in _cache ?
}
```
and
```
Map.NavigateTo(Map.Resolutions[0]); //I don't want to do this, but I have to.
Map.NavigateTo(Mapsui.Projection.SphericalMercator.FromLonLat(0, 0));
```

**Comment by lukaszpitulski** [comment]
And now, when I try add a feature ( POINT(19.0521564483643 52.2834587097168) ) into MarkersLayer, I do:
```
var feature = new Feature { Geometry = SphericalMercator.FromLonLat(19.0521564483643, 52.2834587097168) }; //->POINT (2120876.35 6851541.60) EPSG:3857
```
creating some style of the features etc., and
```
MarkersLayer.Add(feature);
```
And all is fine, if we stay with OSM and EPSG:3857.

But, when I've changed the base layer to a layer which is EPSG:4326, the feature (after SphericalMercator.FromLonLat) is in wrong position on the map (2120876.35°E  6851541.60°N).
So, I do something like this:
```
if (MapControl.Map.CRS.Contains("4326") || MapControl.Map.Layers[0].CRS.Contains("4326") || ((Mapsui.Layers.TileLayer)MapControl.Map.Layers[0]).TileSource.Schema.Srs.Contains("4326"))
	feature = new Feature { Geometry = new Point(19.0521564483643, 52.2834587097168) };
else
	feature = new Feature { Geometry = SphericalMercator.FromLonLat(19.0521564483643, 52.2834587097168) };
```
and it's fine, the point/feature is on the map in correct position (but only if I reload data = clear and add all features into the layer again). 
But with more complicated shapes (e.g. polygon) this solution will be really ugly. Is it?
**Should I do this everywhere where I use SphericalMercator?**


That's my current quasi-solution.
Does it make sense?


The summary queries are:
- Can I change the base layer (Layers[0]) and keep code (Map, Layers, Features, etc.) working? Or I must to recreate Map with new CRS and new all layers with features each time when I want to change the base layer?
- In the solution, should I use SphericalMercator or something else?
- Should all layers have the same projection (CRS, Transformer) as the Map (base layer)?
- Or maybe everywhere CRS should be null and I need to use my "ugly" solution (with ifs)?

Best Regards,
Łukasz

**Comment by lukaszpitulski** [comment]
I'm thinking about replacing SphericalMercator by MinimalTransformation().Transform

Example from mouse move:
```
var orgProjection = MapControl.Map.Viewport.ScreenToWorld(screenPosition);

if (new MinimalTransformation().Transform(MapControl.Map.Layers[0].CRS, "EPSG:4326", orgProjection.Copy()) is Point wgs84)//SphericalMercator.ToLonLat(orgProjection.X, orgProjection.Y); //orgProjection is Point
{ 
	CurrentCursorGeoPosition?.Invoke(wgs84.X, wgs84.Y, orgProjection.X, orgProjection.Y);
}
```

and later something like this
```
var geometry = new MinimalTransformation().Transform("EPSG:4326", MapControl.Map.Layers[0].CRS, new Point(19.0521564483643, 52.2834587097168)) as Point;
var feature = new Feature { Geometry = geometry };
```

What do you think, good way?

**Comment by lukaszpitulski** [comment]
But still I don't know what about CRS in Layers, Map, Transformer etc. And how to avoid re-loading data (clearing the Layers and re-adding all Features). Unfortunately, this is the solution for now:
```
foreach (var layer in Map.Layers)
{
	layer.Transformation = Map.Transformation;
	layer.CRS = Map.CRS;
	if (layer is BaseLayer baseLayer)
	{
		baseLayer.Transformer.FromCRS = oldCRS;
		baseLayer.Transformer.ToCrs = Map.CRS;
	}

	if (layer is GeoAvlLibMapsui.Layers.WritableLayer wlayer)
		foreach (var feature in wlayer.GetFeatures())
			feature.Geometry = new MinimalTransformation().Transform(oldCRS, layer.CRS, feature.Geometry);
}
```

**Comment by pauldendulk** [comment]
ah, I understand your problem better now. The DataSource property is only on the regular Layer, not on the WritableLayer. The documentation should be clearer on that. 

The workaround would be to do you own conversion to a DataSource (implementation of an IProvider interface). So after editing features in a Writable Layer so need to first transform them to WGS84 and them copy them to a DataSource (perhaps MemoryProvider or your own custom IProvider) that is attached to a Layer and has the projection fields set. 

I understand this is cumbersome but unfortunately this is the current state of things. After the 2.0 release  there needs to be rewrite of the projection logic.

**Comment by pauldendulk** [comment]
In v4 there is still no automatic projection of coordinates. The `ProjectingProvider` can be used to convert a LatLon DataProvider to the map coordinate system, but for this will probably not work for the WritableLayer because you would need to convert back to LatLon as well. So, if you want to use the WritableLayer you should convert to an from LatLon in your own code.
