### ISSUE TITLE
No new tiles on panning?

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#441]
Stack: Xamarin.Forms + UWP app + Mapsui 2.0.0-beta.2 with OSM layer from Microsoft store. On pan map there are no new tiles retrieved.

![mapsui](https://user-images.githubusercontent.com/538812/41230721-25acb19e-6d81-11e8-94bd-72cafab40c93.gif)

**Comment by charlenni** [comment]
I don't understand this. If you look at the last image, than you could see the road with "Im Siel", which is correct loaded. Perhaps it needs mor time to load?

**Comment by bertt** [comment]
had to cut the video a bit in the end due to max size :-( it's more about the tile above Im Siel

**Comment by bertt** [comment]
will try to use the OSM https version instead of the default http version with 307 internal redirect

**Comment by pauldendulk** [comment]
There have been some changes in uwp because it use the gpu when idle. In current master there are no new tile requests at all on pan. But RefreshGraphics is called. There are new tile requests on mouse wheel zoom.

**Comment by pauldendulk** [comment]
I pushed 2.0.0-beta.4 this morning with the fix in panning in uwp. I will close this. When discussing this yesterday there seemed to be some other issues with slow data fetching as well. Let's open een new issue for this if we have to clearer.
