### ISSUE TITLE
No map displayed in iOS after initialization

### ISSUE THREAD

**Issue by Sonnenspeer** [Mapsui/Mapsui#442]
Hi there! 

In my Xamarin Forms project I use Mapsui for offline tile loading which works great. On Android it's perfect and nothing to complain. But on iOS there is a strange phenomenon. After opening the app the map is loading in the background and other stuff is displaying (i.e. the zoom widget). Even the map is loaded it's only showing pitch black and no map tile is visible. After using the zoom (widget or gesture) the map is instantly showing up like it should.

Anyone have an advice how this problem could be fixed? I have a feeling that the zoom level is out of tiling range but how could i affect the zoom Level after the map is loaded? Tried to add "map.NavigateTo(XY)" after adding the offline tile layer but this has no effect. Maybe too early? 

On Android this problem does not occur and the map is loaded as expected (without any change in code).

**Comment by charlenni** [comment]
Seems, that there is a RefreshGraphics() is missing.

**Comment by pauldendulk** [comment]
Which version of Mapsui? Do you use Mapsui.Forms or your own Forms renderers?

**Comment by Sonnenspeer** [comment]
I already use RefreshGraphics() after adding it to the layer but this has no effect.

The version of Mapsui is 2.0.0 Beta 3. I don't use Mapsui.Forms but instead I wrote an own wrapper for it.

**Comment by Sonnenspeer** [comment]
I used to set the zoom level via NavigateTo() method. Is that correct?

Example Code:
`
public void LoadMap() {
  /* .. Load map */
  var resolution = map.Resolutions.Min(); // get nearest zoom level
  NavigateTo(resolution);

  RefreshGraphics();
}
`

**Comment by pauldendulk** [comment]
ah, thanks for the feedback. Your NavigateTo call also indirectly called RefreshGraphics which does not work on a background thread. I now use RunOnUIThread within all four platforms to avoid this.
