### ISSUE TITLE
Is it possible to get clicks with the right mousbutton through Map.Info event?

### ISSUE THREAD

**Issue by pingurus** [Mapsui/Mapsui#444]
Currently it does not fire for me when i click with the right mousebutton. Is there a way to make it happen? 
If not, it would be nice if it would be implemented.

**Comment by pauldendulk** [comment]
On the WPF MapControl there is GetMapInfo. If bind WPFs regular MouseRightButtonDown event you could call GetMapInfo in there.

**Comment by pingurus** [comment]
Thank you! 

Am 13. Juni 2018 23:06:38 MESZ schrieb Paul den Dulk <notifications@github.com>:

**Comment by pauldendulk** [comment]
Perhaps you need to correct for DetermineDeviceIndependentUnits.

**Comment by pauldendulk** [comment]
btw, this code will change again with the next beta. There will be big changes during these betas.
