### ISSUE TITLE
Line length on the scale

### ISSUE THREAD

**Issue by marcinsliwa1** [Mapsui/Mapsui#445]
Hi, pauldendulk!
Xamarin Android
I create 200 LineString.

Point endPooint = new Point();
            endPooint.X = s.X + 200;
            endPooint.Y = s.Y;

Where I made a mistake, because the length (line.Length) on the map is not equal to the scale
![obraz](https://user-images.githubusercontent.com/40258724/41394773-8a88ff1a-6fab-11e8-9fd8-d2387f67e246.png)

**Comment by charlenni** [comment]
The mistake is, that 200 on the map is online 200 m if you at equator. If you are above or below, 200 on the map aren't 200 m anymore. See for this the function `CalculateScaleBarLengthAndValue()` at [ScaleBarWidget.cs](https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Widgets/ScaleBar/ScaleBarWidget.cs). The part you need is
````
// Calc ground resolution in meters per pixel of viewport for this latitude
double groundResolution = viewport.Resolution * Math.Cos(position.Y / 180.0 * Math.PI);
````

**Comment by pauldendulk** [comment]
Here is a gis stackexchange question on this topic: https://gis.stackexchange.com/a/242547/801

**Comment by pauldendulk** [comment]
In the discussion about circles there is a similar issue. We could create some helper methods for this and documentation. 

https://github.com/Mapsui/Mapsui/issues/203

A helper method could be:

CreateLineInMeters(Point startingPoint, float direction, float lenghtInMeters)

**Comment by charlenni** [comment]
A good image for this problem you could also find at [Wikipedia](https://en.wikipedia.org/wiki/Mercator_projection#Scale_factor). There is a image with circles on the right side. Each of this circles has the same radii on earth.

**Comment by pauldendulk** [comment]
Closing this. Summary: SphericalMerator coordinates are not in meters.
