### ISSUE TITLE
lon lat x y

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#447]
Hi,

```
Mapsui.Projection.Transformer
Mapsui.Projection.Mercator
Mapsui.Projection.SphericalMercator
```
are ok
but
`Mapsui.Projection.MinimalTransformation`
in constructor is bug I think
_to**LatLon**["EPSG:4326"] = (x, y) => new Point(x, y);
_from**LatLon**["EPSG:4326"] = (x, y) => new Point(x, y);
_to**LatLon**["EPSG:3857"] = SphericalMercator.ToLonLat;
_from**LatLon**["EPSG:3857"] = SphericalMercator.FromLonLat;

LatLon = Y,X
LatLon != LonLat

Regards,
Łukasz

**Comment by pauldendulk** [comment]
I don't think this is a bug. It does not produce unwanted behavior, or does it? 

But you do point out bad naming.  _toLatLon and _fromLatLon are internal fields with a confusing name. Renaming them will fix the problem but won't change te behavior.

Did you find this code through the API documentation?

**Comment by lukaszpitulski** [comment]
in short, for me:
```
Point->FromLonLat : lon = x, lat = y
Point->ToLonLat : x = lon, y = lat
```

so, when I saw this
```
_toLatLon : Point(x,y)
_fromLatLon : Point(x, y)
_toLatLon : SphericalMercator.ToLonLat
_fromLatLon : SphericalMercator.FromLonLat
```
I was confused.
That's all (for now ;) )

**Comment by pauldendulk** [comment]
It is good to point it out. I will fix it.

**Comment by pauldendulk** [comment]
Done.

**Comment by lukaszpitulski** [comment]
2.0 is ok,
What with 1.4 ?
