### ISSUE TITLE
Replace Mapsui.UI.Timer

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#448]
Now we are using .Net Standard > 1.1 for Mapsui, so we could replace the own timer by the standard timer, because to reduce of code.

**Comment by pauldendulk** [comment]
Good idea. There might be more things that can be replaces by a more decent implementation.

Btw, that is the proper timer for .NET Standard 1.3?

**Comment by charlenni** [comment]
See PR #454
