### ISSUE TITLE
New coordinate system in MinimalTransformation - proposition

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#449]
Hi,

is there any chance to add into MinimalTransformation constructor these lines?:
this._toLonLat["EPSG:2180"] = (Func<double, double, Point>)((x, y) => new Point((x + 877200) / 73320, (y + 5504150) / 114900));
this._fromLonLat["EPSG:2180"] = (Func<double, double, Point>)((x, y) => new Point((x * 73320) - 877200, (y * 114900) - 5504150));

Many Thanks,
Łukasz

**Comment by lukaszpitulski** [comment]
Please cancel the request.
The units are not certain (precision).

**Comment by lukaszpitulski** [comment]
maybe these could be better, but still not 100% sure

this._toLonLat["EPSG:2180"] = (Func<double, double, Point>)((x, y) => new Point((x+863000)/71800, (y+5518000)/114780));
this._fromLonLat["EPSG:2180"] = (Func<double, double, Point>)((x, y) => new Point((x*71800)-863000, (y*114780)-5518000));

**Comment by lukaszpitulski** [comment]
https://epsg.io/2180

**Comment by lukaszpitulski** [comment]
https://epsg.io/transform#s_srs=4326&t_srs=2180

**Comment by lukaszpitulski** [comment]
maybe?
this._toLonLat["EPSG:2180"] = (Func<double, double, Point>)((x, y) => new Point(((x+500000)/0.9993/26145)-19, (y+5300000)/0.9993/110860));
this._fromLonLat["EPSG:2180"] = (Func<double, double, Point>)((x, y) => new Point((((x+19)*26145)*0.9993)-500000, ((y*110860)*0.9993)-5300000));

any idea how to do that transformation? (2180<->4326)

**Comment by pauldendulk** [comment]
The MinimalTransformation is just meant to support the most common use case, which is projecting between WGS84 and SphericalMercator. At some point Mapsui will use NTS and then it will become easy to add projection support using [ProjNet4GeoAPI](https://github.com/NetTopologySuite/ProjNet4GeoAPI). Until that time you have to solve this by using your own Transformation. You can add this yourself by deriving from ITransformation just as MinimalTransformation. You could add this custom code above in your custom transformation. If you know the correct algorithm and parameters that is probably a good solution. 

You could also add you own ITransformation using ProjNet4GeoAPI. In that case you have to do some transformation for Mapsui Geometries to GeoAPI geometries.

**Comment by lukaszpitulski** [comment]
And so I did.
