### ISSUE TITLE
ZoomLock and PanLock not working on Android

### ISSUE THREAD

**Issue by jothedev** [Mapsui/Mapsui#451]
Rather than an Issue, I would like to know whether ZoomLock and PanLock are working in Android or not? 

Since in the Shared project, it has been initialized but under `MapControl.cs` for Android project, both variable aren't being used.

**Comment by pauldendulk** [comment]
It is not used yet. This work currently in progress. We are moving more code to shared. It is a bit of a puzzle how to make this fit into the native controls. It would be nice if the checks themselves would also be done in the shared code.

**Comment by pauldendulk** [comment]
Work is going on right now. I could take somewhat longer because of the holidays. I expect this to be in v2.
