### ISSUE TITLE
EPSG:2180

### ISSUE THREAD

**Issue by marcinsliwa1** [Mapsui/Mapsui#452]
Hey.

I have point coordinates in the EPSG layout: 2180.
According to the sample, ProjectionSample.cs defines
var provider = new MemoryProvider (features) {CRS = "EPSG: 2180"};

During loading, however, I get the error:
System.Collections.Generic.KeyNotFoundException: The given key was in the dictionary. occurred

Is it possible to convert from EPSG: 2180 to EPSG: 3857

**Comment by charlenni** [comment]
Write a ITransformation object that could convert EPSG:2180 to EPSG:3857 and assign this to the Map.

**Comment by lukaszpitulski** [comment]
https://github.com/Mapsui/Mapsui/issues/449

**Comment by pauldendulk** [comment]
Yes, you need to implement you own ITransformation. You could try to use [ProjNet4GeoAPI](https://github.com/NetTopologySuite/ProjNet4GeoAPI).
