### ISSUE TITLE
Drag image on map control

### ISSUE THREAD

**Issue by gaurav230394** [Mapsui/Mapsui#456]
Can you add an event or something to drag a symbol while keeping the map static? Like if I have to place a symbol from one position to another on map using drag.

**Comment by pauldendulk** [comment]
In the sample Mapsui.Samples.Wpf.Editing there is dragging of vertices of polygons in edit mode. This is done by setting ZoomLock. ZoomLock only works in WPF so far, so if you work on another platform this won't work.

**Comment by gaurav230394** [comment]
Got it. Thank you.

**Comment by pauldendulk** [comment]
Yes, ZoomLock and PanLock will be available in 2.0. It is expected in the next beta.

**Comment by rthanga1** [comment]
Will this be available for Mobile?

**Comment by pauldendulk** [comment]
ZoomLock and PanLock can be used on all platforms. In 4.0.0-beta.9 this can be set like this `MapControl.Map.Navigator.Limiter.PanLock`. In 4.0.0-beta.10 (released the coming days) it will be `MapControl.Map.Navigator.PanLock`.

**Comment by rthanga1** [comment]
Thanks. I see that. But does the 'drag' works in Mobile? Like - can I drag pin/circle/polygon in a map?
