### ISSUE TITLE
iOS Skiarenderer fails on a specific geometry

### ISSUE THREAD

**Issue by Kortdag** [Mapsui/Mapsui#457]
I have a strange issue in production. I´ve isolated it to rendering a specific polygon which is a bit complex. 
My app freezes so it looks like something is blocking the UI thread. 

I´ve attached a sample to reproduce the issue. I´ve tested the same geometry on WPF using both WPF and SKia renderer and it works on WPF, but not on iOS. My observations on the sample running the iOS.

- On iPad simulator (5 generation iOs 11.4) it seems to freeze like what I see in my real world app
- On physical device it crashes and does not freeze / lock up. So probable due to us having more layers or combined types of layers..

my physical device is an iPad Pro running iOS 11.4.

Its reproduced in MapSui v. 1.4.2. downloaded as .zip from https://github.com/Mapsui/Mapsui/releases 
In our production code we´re using the Nuget package.

In the sample substituting one geometry with the other it works/crashes. 

I hope the physical device we sponsored have arrived so it possible to test on a real device - there should be a mail in your gmail account :-).

[PolygonSampleWKT.zip](https://github.com/Mapsui/Mapsui/files/2123261/PolygonSampleWKT.zip)

**Comment by charlenni** [comment]
I take a look on this problem, but couldn't reproduce it.

I used the actual master (2.0.0-beta.5) and added your polygon. Besides, that the map isn't drawn, I could see the polygon and the iPad simulator doesn't freeze. I could click on the attributaion and the website is shown.

Your polygon looks like this:
![bildschirmfoto 2018-06-21 um 20 34 03](https://user-images.githubusercontent.com/4381223/41738563-ae5c9694-7592-11e8-803c-2ad21c73139e.png)

**Comment by Kortdag** [comment]
There should be OSM map in the background right? If you try in 1.4.2 how does it look?

If you can reproduce 1.4.2 and iOS 11.4 for US a fix in 1.4.2 would highly appreciated. We're in production and 2.0 is a beta and lookes like a really big release. So we have to do a lot of making sure everything else is the same, by introducing a beta.

Let me know if you cannot reproduce and I will look into creating a sample with similar project settings. I fear that it might be worse on physical device. The emulator I tried had problems but not the same as on real device.

**Comment by pauldendulk** [comment]
Beta 2 is indeed a big change.

**Comment by charlenni** [comment]
I tested it with the current 1.4 branch, but could not reproduce the problem. There is another problem (view is only on the upper left part of the screen), but the polygon could be displayed correct and could be moved on screen.

![bildschirmfoto 2018-06-22 um 18 29 57](https://user-images.githubusercontent.com/4381223/41788043-95154560-764a-11e8-925d-5027a738bb03.png)

**Comment by Kortdag** [comment]
Interesting. I will try on monday ok a simulator again. Running my sample on a physical device crashes the app. On simulator it didnt work - or maybe I was in patient. Or deferent settings. 
I will look into it.

**Comment by Kortdag** [comment]
There is definitely a problem. I have reproduced another issue there seems to be related to the UI lockup.

Her is the two iOS sample projects but due to size restrictions with binaries + embedded stuf + mbTiles removed.

[Mapsui.Samples.iOS.zip](https://github.com/Mapsui/Mapsui/files/2141298/Mapsui.Samples.iOS.zip)

I have created two samples
**1) PolygonSampleWKT**
Screenshots of behavior on simulator on the two geometries
[SImulatorWorks.zip](https://github.com/Mapsui/Mapsui/files/2141317/SImulatorWorks.zip)

Screenshots of behavior on device on the two geometries. (The crash is the dreadded iOS "EXC_BAD_ACCESS SIGABRT)
[DeviceWorking.zip](https://github.com/Mapsui/Mapsui/files/2141320/DeviceWorking.zip)


**2) Another sample where there is a UI lockup by using rapid pinch zoom.**
Only screen recordings on device since I dont know how to test pinch zoom on simulator.
[UI Lockup.zip](https://github.com/Mapsui/Mapsui/files/2141333/UI.Lockup.zip)
when map movement stops in the video the UI is frozen and Im trying to zoom and pan :-D.

I´m convinced the two problems are two flavours of the same substance. 

I just upgradet to Win 10, but behavior looks the same as on Win7. When upgrading all VisualStudio stuff is latest version

**Current VisualStudio info:**
Microsoft Visual Studio Professional 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Professional

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40608.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40608.0
Azure Functions and Web Jobs Tools

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JetBrains ReSharper Ultimate 2018.1.2    Build 112.0.20180530.113618
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.
Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by pauldendulk** [comment]
Thanks for your in depth report. I will look at it as soon as I have time. However, I am a lot on the road this week so it is hard to find time. Yesterday I did get my Mac tools setup properly again (after a long hiatus) and got Mapsui.Samples.iOS sample running on the hardware iPad.

**Comment by Kortdag** [comment]
Sounds good with the physical device. It will make everything easier for sure :-).
Looking forward to your findings.

**Comment by charlenni** [comment]
PinZoom on simulator works for me with Alt key. But I have a Windows keyboard on my Mac.

**Comment by pauldendulk** [comment]
@charlenni Your issue "view is only on the upper left" was introduced in 1.4.2 :(

**Comment by pauldendulk** [comment]
Thanks for your PolygonSampleWKT. It is very helpful. I am doing some testing with it. Unfortunately it looks like a hard thing to fix. I am trying to narrow it down.

- It works fine on WPF, UWP and Android. On my iPad Air2 it crashes on first render in most cases. 
- If I don't render the outline (SKPaintStyle.Fill) it works fine.
- If I ignore the inner rings it still crashes. 

I try to further isolate the issue, but it looks like a limitation of SkiaSharp. Perhaps specific for the SKGLView used on iOS. I don't see a workaround right now. Not clear what exactly it violating.

**Comment by charlenni** [comment]
Did you have tested the polygon with a solid outline?

**Comment by pauldendulk** [comment]
Yes, that also fails. It was indeed a suspect. 

I now do just one draw with a very simple SKPaint. I created a branch. https://github.com/Mapsui/Mapsui/commits/isolation-crash-ios

Also removed the clipping. It was not related. I could be a buffer overrun in skia or skiasharp, but it will take some effort to create the minimal app to reproduce it.

**Comment by charlenni** [comment]
Very strange. I tested it and hadn't any problems on iOS. I try next time your branch. Perhaps I could reproduce the problem with that.

**Comment by pauldendulk** [comment]
I was working on the hardware ipad all the time. Did not test the simulator yet. 

There branch is not for merging back, just for research. The polygon renderer is now very simple:

**Comment by pauldendulk** [comment]
I also have problems with the simulator if I use the branch version. I had forgotten to ad the sample file, did that just now.

**Comment by pauldendulk** [comment]
When directly zooming in to the geometry there is no problem. Only when zoomed out. I updated the sample.

**Comment by pauldendulk** [comment]
I submitted an issue at SkiaSharp. https://github.com/mono/SkiaSharp/issues/571

I created a sample without Mapsui to reproduce it. It was quite some work to investigate this. https://github.com/pauldendulk/PolygonCrash

**Comment by pauldendulk** [comment]
Possible workarounds on the users side
- Don't show polygons when zoomed out.
- Don't show the outline when zoomed out.
- Don't show the outline at all.
- Perhaps simplify the polygon when zoomed out.

Possible workaround on the Mapsui side
- Use Matrix scale (not tested seriously yet, but seemed not to crash).
- Don't draw outline if the number of points is above a certain size. The test polygon is 454 points. Perhaps we should limit on 100.
- Replace the SKCanvasView with the we had before.

**Comment by pauldendulk** [comment]
@Kortdag is this a particularly large polygon in your dataset? In other words, could this be a problem because it is large? or is there something about the shape that could cause this? btw, I removed the inner rings because they were not needed and this simplifies the case.

**Comment by charlenni** [comment]
Very good work @pauldendulk !

**Comment by Kortdag** [comment]
Hi Paul

Thanks for a lot of usefull info. I´ve done som reasearch on the shape similar to yours. 

1)  I tested for validity in Oracle in order to let an advanced spoatial engine analyze the geometry - it´s valid according to our tolerance.
2) In the group of fields there was other that to a human eye looked as complex as the on I extracted and put into the sample.
3) We have millions of geometries but the majority are not as complex as the one in the sample. 
4) The other sample (..WKT2) causes another type of problem - UI lockup. Sure its due to rendering. 
5) On VERY strange issue I´ve noticed. Sometimes it seems that rendering the geometry the first time causes a UI freeze. Second app crash. Not sure how. Think its deleting app and the reinstall. Atleast I has seen this several times. Not sure if there is some singleton stuff inside Skia or something kept in memory? Could be a sign of a software- and not haardware problem.7) 
6) As you suspected I had a low/high zoomlevel thing going on. Zoomlevels on rendering as a possible workaround. But then I recreated the lockup sample2 on low zoom. Haven´t tried yet.
7) 100 vertex limit will for sure not be sufficient for us. Many  polygons will have more. I think the worst one is 3-4000. Or we had to intruduce this as a system limit due to Javascript / OpenLayers limit on ole IE.

The history of my findings
1) Sample "...WKT". I then had the client split the polygon as a workaround - It worked. But probably we have other "sleeping" issues.
2) Sample "..WKT2". Locks up the UI on rapid zoom. Look like a "soft" version of 1).

**Comment by charlenni** [comment]
Why not going back to SKCanvasView instead of SKGLView?

**Comment by pauldendulk** [comment]
That was my thought also. You work with the code. The change is small. Not sur how it impacts performance.

**Comment by pauldendulk** [comment]
@Kortdag Thanks for your extensive testing. Perhaps you can also test your geometries in the PolygonCrash sample. It reduces the number of possible factor influencing it.

https://github.com/pauldendulk/PolygonCrash

From the behavior I would think some memory is accessed or disposed which does not belong to the polygon. The failure will depend on which kind of memory this is.

**Comment by pauldendulk** [comment]
Also Mapsui itself should revert to SKCanvasView but I would like to wait for a response on the submitted issue. Perhaps I do something inappropriate and we could fix that.

**Comment by Kortdag** [comment]
The GL canvas is hardware accelerated drawing isn´t it? So I would assume rendering is much better. Can one stille draw many geometries fast on the old thing?

I did test and can reproduce the crash.
I did try to re-write the rendering using affine matrix transformation on the polygon and rendering the result. I dont seem to be able to recreate the crash there!!!

The impl. is very simplified and probably far from production ready, but it seems to work ok - conceptually.

Of course my attempt to teste content on the WKT2 sample went horribly wrong since all poygons are transladed to center. But still should be to much of an issue if testing rendering.

Maybe this can lead to a possible workaround . It seems the only major difference is weather to manipulate the cancas itself vs applying the full affine transformation to the individual geoms....


[MyView.zip](https://github.com/Mapsui/Mapsui/files/2167068/MyView.zip)

**Comment by pauldendulk** [comment]
Good to hear that there is no crash with matrix transform.

The matrix transform is not something we can do in the 1.4 branch. This change is too big. By replacing SKGLView with SKCanvasView in 1.4 the performance impact might not be big because of other bottle necks (like the point by point transform and re-creating the SKPath at every iteration).

Improving skia performance has been on my list for a long time, and I would like to work on it, but there have been higher priorities so far. There is a performance branch in which I already experimented with matrix transform. It breaks a lot of existing functionality which needs an alternative implementation. It is quite some work. It needs to be done after the release of v2.

Also we need to use benchmarkdotnet.

**Comment by pauldendulk** [comment]
I reverted to SKCanvasView. I created a new issue to go back up to SKGLView
https://github.com/Mapsui/Mapsui/issues/484

I see this issue as closed since there is no more crash in Mapsui.
