### ISSUE TITLE
WARNING: 2.0 breaking changes!

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#459]
Just a heads up. There will be breaking changes during the 2.0 betas. Please let me know if you encounter problems because of this.

Update: There is an v2.0 upgrade guide [here](https://mapsui.github.io/Mapsui/documentation/v2.0-upgrade-guide.html).

**Comment by jinkhera** [comment]
Hi Paul

I'm not sure it's too early for me to switch to the 2.0 betas but as I have I noticed changes to the way the viewport is used. It's now part MapControl which wasn't really a big issue in factoring the implementation. One event that was lost is the ViewportChanged, has this also been replaced or being replaced?

**Comment by pauldendulk** [comment]
The ViewportChanged is now a member of viewport, but I see that it is the Viewport field of the MapControl is a IReadOnlyViewport which does not have the ViewportChanged field. I guess I should add it there.

These are the kind of issues I expect in 2.0 and I want to get feedback on. So thanks :)

**Comment by jinkhera** [comment]
When will the version of the 2.0 beta be available? Will it have the pan-lock function? I would like to implement the dragging of a marker on the map :)

**Comment by jinkhera** [comment]
@pauldendulk After changing to 2.0 Beta 11 I could not set PanMode, has this been removed or replaced?

`mapControl.Map.Limiter.PanMode = PanMode.KeepViewportWithinExtents;`

**Comment by pauldendulk** [comment]
This is now the only option if you use the `ViewportLimiter`. The recent changes move towards an interface (`IViewportLimiter`), with different implementations to suite everyone's need. A single configurable ViewportLimter that would allow all possible use cases would become too complicated. 

In general I don't want to block what is possible. Users should be able to extend and inject their own implementations. For some simpler user cases this will make Mapsui a little harder to use. Now it is possible to do whatever you like if you implement your own IViewportLimiter, that was my main motivation.

**Comment by wjax** [comment]
Hi
Should I report here or create a new issue for 2.0?
Latest beta 17 and previous ones suffer from problems with WPF renderer once you try to resize Window.

Just open Mapsui.Samples.Wpf, run it, change renderer to WPF and try to resize windows. From that, application is super laggy and insusable.

**Comment by pauldendulk** [comment]
Thanks. Best to create a new issue for this.

**Comment by pauldendulk** [comment]
There is an upgrade guide http://mapsui.com/documentation/v2.0-upgrade-guide.html. It is far from complete but I don't want to invest in updating it. If however users run into upgrade issues this guide page should be updated. We do not need this issue for this.
