### ISSUE TITLE
Pan lock is not working with touch

### ISSUE THREAD

**Issue by gaurav230394** [Mapsui/Mapsui#460]
I tried locking the pan behaviour of map for touch move action but its not working. The map is panning anyway. Could be a possible bug. 
Working on WPF  application

**Comment by pauldendulk** [comment]
This is not yet implemented. Current work is on moving more code to the shared MapControl. PanLock and other 'limiters' will be a part of this.

**Comment by pauldendulk** [comment]
I expect this will be fixed in the final release of v2.
