### ISSUE TITLE
MasterDetailPage Xamarin Forms iOS Swipe Issue

### ISSUE THREAD

**Issue by XamHans** [Mapsui/Mapsui#461]
Hi there,

just implemented MapsUi, works like a charm on Android. But on iOS swiping stucks.
Found out that the issue is MasterDetailPage. If I set the Property " IsGestureEnabled" from MasterDetailPage to false, swiping works as expected.
Have anybody made the same experience with that?

Project is .net Standard ( Xamarin Forms) with the newest nugets.

Thank you in Advance.

**Comment by pauldendulk** [comment]
Thanks for your report. I am currently trying to avoid Forms but hope to get to it in the coming weeks. I will investigate this then. I assume the gesture captures the event we use for regular panning. I think we should take some time to consider how we should work with events. My idea is to keep it 'open', in a way to users can use the existing events and call Mapsui features from that instead of adding a Mapsui layer of events and gestures to hide the existing events. Not sure if this is possible.

If I understand you correctly you do have a workaround, so this is not an urgent matter for you?

**Comment by radderz** [comment]
Hi XamHans, you need to set the IsGestureEnabled to false as you mentioned, otherwsie the MasterDetail view will override the swipe guesture, this is a common design issue with Xamarin.Forms MD with a detail view that uses touch and nothing to do with Mapsui.

**Comment by charlenni** [comment]
Hi Mark,

nice to hear from you.

I want to ask, if you have some spare time to look into the Gorms implementation of Mapsui. You could find it (here)[https://github.com/charlenni/Mapsui/tree/Forms?files=1]. It uses only native Xamarin.Forms.

**Comment by radderz** [comment]
@charlenni - Anythign you'd like me to have a look at specifically?

**Comment by charlenni** [comment]
@radderz: Any comment is appreciated 😉

I tried to make a native Xamarin.Forms component for Mapsui not a wrapper. There is no one, I could ask, if it is correct and works. Paul want to look into it later.

Btw. You said, that you have code to move the map with a gesture (flinger?). I added a velocity tracker to the shared code of Mapsui as first part. Perhaps you can help, how to do the next steps. And you told, that you have animations for moving the map. No problem with Xamarin.Forms part, but would be wonderful to have it for all platforms.

**Comment by radderz** [comment]
@charlenni - @pauldendulk - Is this something we would bring into the main repo? If so I can have do some validation and start doing some changes where applicable.

**Comment by charlenni** [comment]
Do you mean the Xamarin.Forms MapControl or the other things? I think both are useful parts for Mapsui.

**Comment by charlenni** [comment]
I looked into the MapControl of the Xamarin.Forms implementation: it isn‘t only a Xamarin.Forms, but could be used as a native Skia control. So it could be used on all platforms that SkiaSharp supports. Around this control is a MapView, that derives from Xamarin.Forms View.
