### ISSUE TITLE
ScreenWidth and ScreenHeight

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#462]
The new IMapControl properties ScreenWidth and ScreenHeight are defined as
````
    /// <summary>
    /// The map's screen width in device independent units
    /// </summary>
    float ScreenWidth { get; }

    /// <summary>
    /// The map's screen height in device independent units
    /// </summary>
    float ScreenHeight { get; }
````
Should they set as map's width or as screen width. Both is possible regarding the comment? And what happens, if the device is rotated?

Btw. I saw, that it is used only in the native MapControls, so it isn't a commn part. It should be removed from IMapControl and placed in the native MapControls directly. I don't see any reason, why we need this information.

**Comment by pauldendulk** [comment]
This is step in moving more code to the shared mapcontrols. Now some logic needed to stay in the native mapcontrols because they depend on the the native width/height fields. I want to make the native part as small as possible.

When the screen is rotated events are triggered which assign new values for Width and Height. This is no different than it was before because ScreenWidth/ScreenHeight are just wrappers on the native width/height fields.

**Comment by pauldendulk** [comment]
Good point. I can not name it Width because it will collide with existing fields. I named it ScreenWidth because it is in screen coordinates, but that does suggest it is the width of the full screen which is not the case. We should think of a better namen.

**Comment by charlenni** [comment]
But what is than the differen between ScreenWidth/ScreenHeight and Width/Height? Why couldn't we use the last?

**Comment by pauldendulk** [comment]
Because the MapControls have different fields for that. 
iOS: Frame.Width
UWP/WPF: ActualWidth
Android: Width in pixels so you need to transform it. 

The ScreenWidth is to convert this into one field so that shared MapControl code can use this.

**Comment by charlenni** [comment]
Ok. But than it would be better to call it ControlWidth/ControlHeight instead of SCreenWidth/ScreenHeight.

**Comment by pauldendulk** [comment]
That's already a better name.

**Comment by pauldendulk** [comment]
I also like ViewportWidth. It's purpose is mainly to set the Viewport.Width.

And then it could also be removed from the IMapControl interface and be made private. I guess that is the most proper thing to do. Viewport.Width should be used by users.

**Comment by pauldendulk** [comment]
Removed them from MapControl altogether. Users should use MapControl.Viewport.Width. Now that Viewport is on MapControl this is almost identical to MapControl.ViewportWidth.
