### ISSUE TITLE
View is only on the upper left on iOS in 1.4.2

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#463]
As reported as part of #457. 

This will be fixed by using the skia canvas scale instead of it's parent's scale.

**Comment by pauldendulk** [comment]
Could you check if all your projects have updated to 1.4.4? And del bin and obj and rebuild.

What device are you using?

**Comment by pauldendulk** [comment]
I will look at it tomorrow.

**Comment by joshminor** [comment]
I did a full clean/rebuild and no change. I think you committed the fix only to the isolation-crash-ios branch.

**Comment by charlenni** [comment]
Often a full clean/rebuild isn‘t enough if you change the library version. You should delete all bin and obj folders in your project by hand.

**Comment by pauldendulk** [comment]
The code is actually missing the fix. Bad mistake. This bug has been in the most recent version for a long time. https://github.com/Mapsui/Mapsui/blob/1.4/Mapsui.UI.iOS/MapControl.cs#L82

**Comment by pauldendulk** [comment]
Did not test it though.

**Comment by joshminor** [comment]
I ended up having to revert to 1.3.2 for the time being, I'm experiencing some Android performance problems as well, and have a deadline to meet. I appreciate you're quick response.

**Comment by pauldendulk** [comment]
I can reproduce the problem but have no time to publish now. This will be tomorrow.

**Comment by pauldendulk** [comment]
Fix now in the right branch. This should be released as 1.4.5
