### ISSUE TITLE
Random feature order in WritableLayer

### ISSUE THREAD

**Issue by Sonnenspeer** [Mapsui/Mapsui#466]
Hi. I'm using a WritableLayer to display my current device position via GPS in Xamarin Forms.

Everytime the GPS data is changing I redraw the device position by clearing the cache from the WritableLayer and add the new features with the corresponding new position. But on every "draw call" the added features are displayed in a random order.

This is my Code: 
(Features are a 
blue outer circle (Order 1)
with a smaller inner white circle (Order 2)
and again a smaller inner blue circle (Order 3)
- Blue, White, Blue)

```
 Mapsui.Geometries.Point ps = new Mapsui.Geometries.Point(spherical.X, spherical.Y);

// Paint user position ui
            if (repaintUserIcon)
            {
                Feature featureUserOuterBlue = new Feature()
                {
                    Geometry = ps,
                    ["Name"] = "User position",
                    Styles = new List<IStyle> { new SymbolStyle { Fill = new Brush(Mapsui.Styles.Color.Blue), SymbolScale = 0.5f } }
                };
                Feature featureUserInnerWhite = new Feature()
                {
                    Geometry = ps,
                    ["Name"] = "User position",
                    Styles = new List<IStyle> { new SymbolStyle { Fill = new Brush(Mapsui.Styles.Color.White), SymbolScale = 0.4f } }
                };
                Feature featureUserInnerBlue = new Feature()
                {
                    Geometry = ps,
                    ["Name"] = "User position",
                    Styles = new List<IStyle> { new SymbolStyle { Fill = new Brush(Mapsui.Styles.Color.Blue), SymbolScale = 0.3f } }
                };    

                var features = new Features();
                features.Add(featureUserOuterBlue);
                features.Add(featureUserInnerWhite);
                features.Add(featureUserInnerBlue);

                if(layerUser != null)
                {
                    layerUser.Clear();
                    layerUser.AddRange(features);
                } 
            }
```

So the layer stays the same every time but the features are changing. Now the order of this Features are random. For example:

Draw call 1: Blue, White, Blue (1, 2, 3 - Correct order)
Draw call 2: White, Blue, Blue (2, 3, 1 - Biggest blue circle is overlapping everything)
Draw call 3: Blue, Blue, White (3, 1, 2 - Biggest blue circle and white circle only visible)

Has anybody experienced something like that? How could that be? Can anybody reproduce this?

**Comment by charlenni** [comment]
Why don't you add 3 styles to one feature? That would be better for this case.

````
Feature featureUser = new Feature()
{
  Geometry = ps,
  ["Name"] = "User position",
  Styles = new List<IStyle> { 
    new SymbolStyle { Fill = new Brush(Mapsui.Styles.Color.Blue), SymbolScale = 0.5f },
    new SymbolStyle { Fill = new Brush(Mapsui.Styles.Color.White), SymbolScale = 0.4f },
    new SymbolStyle { Fill = new Brush(Mapsui.Styles.Color.Blue), SymbolScale = 0.3f }
  };
};    

var features = new Features();
features.Add(featureUser);
````

And even better would be to only change the Geometry of the Feature. So create featureUser once and than set
````
featureUser.Geometry = ps;
````

**Comment by Sonnenspeer** [comment]
Yap that did it for me in my case. Thanks for the improvement. Not so familiar with the api.

This still might be a bug.

**Comment by lukaszpitulski** [comment]
Mapsui.Providers.Features is nothing else like **System.Collections.Generic.List**<Mapsui.Providers.IFeature>

**Comment by pauldendulk** [comment]
WritableLayer uses an ConcurrentHashSet internally. I can imagine that because of it's support for concurrency the order of the features is not always the same. For things like label placement order can become important. This is not something we are working on right now.

**Comment by pauldendulk** [comment]
I don't consider this a bug but thank you for pointing this out. It is not something that I had expected.
