### ISSUE TITLE
System.MissingMethodException: int Mapsui.Styles.BitmapRegistry.Register(object)

### ISSUE THREAD

**Issue by michalhoblik** [Mapsui/Mapsui#468]
Hi,

I just updated Mapsui to version 1.4.4 and now I am unable to create one of my layers with "SymbolStyle" Style inside because of this error on Android:

> _JNI DETECTED ERROR IN APPLICATION: JNI CallStaticObjectMethodA called with pending exception android.runtime.JavaProxyThrowable: System.MissingMethodException: int Mapsui.Styles.BitmapRegistry.Register(object)_

My SymbolStyle-Helper looks like this:
```
public static class BitmapHelper
    {
        public static Style CreateBitmapStyle(string imgNameWithExtension)
        {
            var stream = LoadEmbeddedResource($"MyTestApp.Resources.Images.{imgNameWithExtension}", typeof(BitmapHelper));
            return new SymbolStyle { BitmapId = BitmapRegistry.Instance.Register(stream) };
        }

        private static Stream LoadEmbeddedResource(string embeddedResourcePath, Type type)
        {
            var assembly = type.GetTypeInfo().Assembly;
            return assembly.GetManifestResourceStream(embeddedResourcePath);
        }
    }
```

Do you have any idea what am I doing wrong? The method seems to be there. Thanks in advance.

**Comment by pauldendulk** [comment]
I do not expect this. Please try delete bin and obj and rebuild.

From which version did you upgrade?

**Comment by michalhoblik** [comment]
Sorry my mistake, I deleted bin and obj and next thing I found out that the mapsui has been not updated for all projects. I started nuget update again and now is everything working again. Thanks for help. You can close this Issue.

**Comment by pauldendulk** [comment]
Thanks for quickly handling this.
