### ISSUE TITLE
Android 1.4.4 touch doesn't refresh view

### ISSUE THREAD

**Issue by radderz** [Mapsui/Mapsui#469]
when panning and zooming etc, I am getting no changes in the map position (occasionally get a change) until I release the touches. I had to revert back to 1.4.2 to get the map movements to follow touch again.

Was there any breaking changes for touch handling changes between 1.4.2 and 1.4.4?

**Comment by radderz** [comment]
Seems like a false alarm, I reinstalled the earlier version and upgraded again and the issue is gone :\

**Comment by pauldendulk** [comment]
I probably introduced this bug. I will have a look tomorrow. I don't I have this problem on my device.

**Comment by pauldendulk** [comment]
Oh right. Good news. Still weird.

**Comment by pauldendulk** [comment]
There was actually a bug that might be related to this. It was fixed in 1.4.6.
https://github.com/Mapsui/Mapsui/issues/479
