### ISSUE TITLE
Best way to create a legend

### ISSUE THREAD

**Issue by charmosz** [Mapsui/Mapsui#471]
Hi. I'm on Xamarin forms. I would like to show the legend of the map in a frame. For each layer I need to draw the style (symbol, line or polygon) and display the name of the layer. What would be the best to do that ? Should I reuse the existing renderers ? In this case I need a viewport, right ? Sounds difficult.
Thanks

**Comment by charlenni** [comment]
If you want to do this in Mapsui, you should look into the Widgets. That would be helpful.

**Comment by charmosz** [comment]
I looked into the Widgets but i don't quite understand how it can help me. What I need is just to be able to draw the symbols of my layers (a square, a circle, a line...) in a frame. The frame doesn't have to be on the map, it can be on another page or in a popup, but that's not the problem. How can I draw the same symbols ? Do I have to use skia and create a canvas ?

**Comment by charlenni** [comment]
One way would be to use SkiaSharp and draw the images by your own. That‘s right. Another way would be to create images and display them.

**Comment by pauldendulk** [comment]
The IRenderer interface has a RenderToBitmapStream. It takes a list of layers as argument. The resulting MemoryStream is a png. You could use that as a source of an image control. So perhaps this could be used. 

A complication could by that the data is asynchronously loading. The unit tests use the RenderToBitmapStream a lot but they only use data that is directly available in memory.

**Comment by pauldendulk** [comment]
It would be nice to have this as a widget so we could use it on all platform.

**Comment by charmosz** [comment]
Ok, thanks guys. I will give a try and let you know.
