### ISSUE TITLE
How I can Add a custom widget ?

### ISSUE THREAD

**Issue by Wil69** [Mapsui/Mapsui#475]
Hi,

I would like to add a new widget, for example a custom image with a click event (to position me on the map or others).
Please how I can to do that outside the library, have you got an example ?

Regards.

**Comment by pauldendulk** [comment]
I only made start with this and I am not even sure if this code is in beta 7. 

The idea was. The MapControl has a Renderer. The renderer has a list of WidgetRenders. If you create you own widget you should register is with your corresponding WidgetRenders.

That was the idea when I wrote this code. I made sure the current Widgets work with this interface but I never wrote an actual custom widget. It might be worth a try. This interface will probably change in the future.

**Comment by Wil69** [comment]
Thanks for your anwser.
I try to do a Widgetclass  and a WidgetRenderer but after I don't know how it's possible to link them.
I see that :
public class MapRenderer : IRenderer
    {
 ....
public IDictionary<Type, IWidgetRenderer> WidgetRenders { get; } = new Dictionary<Type, IWidgetRenderer>();
and example :
 WidgetRenders[typeof(Hyperlink)] = new HyperlinkWidgetRenderer();

So How I can do that ?

**Comment by pauldendulk** [comment]
You need to implement the ISkiaWidgetRenderer and the IWidget and then add it to the dictionary. That should be enough. When your widget is encountered by the renderer it will use the dictionary to find out which widget renderer to call. This is that code for skia:

Customhttps://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Skia/SkiaWidgets/WidgetRenderer.cs

For examples you can look at the registration of the default widgets:
https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Skia/MapRenderer.cs#L40

**Comment by pauldendulk** [comment]
Inside your custom widget renderer you will need to cast to you custom type to access it's specific properties.

**Comment by Wil69** [comment]
Hi
Thakns for your feed back. I understood that I need to implement two files in my .Core (it's correct ?) but after I don't know how I can add to the same dictionnary than implemented.
I try to acces in my MapsViewRenderers (.Android) but IRender do not give acces to
"IDictionary<Type, IWidgetRenderer> WidgetRenders "

I implement mapSui as your example : 
2 renderers in different platform : 
 MapsViewRenderer : ViewRenderer<MapsUiView, Mapsui.UI.Android.MapControl>
{
protected override void OnElementChanged(ElementChangedEventArgs<MapsUiView> e)
        {
            base.OnElementChanged(e);

            if (mapViewControl == null && e.NewElement != null)
                mapViewControl = e.NewElement;

            if (mapNativeControl == null && mapViewControl != null)
            {
                mapNativeControl = new Mapsui.UI.Android.MapControl(Context, null);
                mapNativeControl.Map = mapViewControl.NativeMap;
                SetNativeControl(mapNativeControl);
            }
}
and in the .Core a control class : 
protected internal MapsUiView()
        {
           NativeMap = new Mapsui.Map()
            {
                CRS = "EPSG:3857",
                Transformation = new MinimalTransformation(),
                BackColor = Mapsui.Styles.Color.White,
            };
        }
And in the xaml class : 
Mymap = new MapsUiView();

Please Can't you give me a example code or complete my code for adding my widget in the same dictionnary.
Thanks in advance. :-)

**Comment by Wil69** [comment]
I had forgotten : 
I can't implement ISkiaWidgetRenderer because I can't use "Mapsui.Rendering.Skia.SkiaWidgets" but just "Mapsui.Rendering.Skia", so I just can implement a WidgetRenderer ....

**Comment by pauldendulk** [comment]
Okay, I will need to add a custom widget sample to 'eat my own dog food'.

**Comment by charlenni** [comment]
I don't think that it is the correct usage for Widgets. Widgets are things, that should be drawn on top of a map and are not normal controls. Good examples are a scale bar or a cross in the center. What you want is a button, which should be made of normal UI controls. That would be much easier. So, if you want a button to center the map to your position, add a normal button and use this.

**Comment by Wil69** [comment]
Hi @charlenni yes it's the second solution, I do that ...
Tks

**Comment by pauldendulk** [comment]
Side note: I added a CustomWidgetSample. This is just a start and it will have further changes.

For this use case it is better to work with Xamarin widgets.
