### ISSUE TITLE
Xamarin.Forms project

### ISSUE THREAD

**Issue by pxp44** [Mapsui/Mapsui#476]
Hi,

how can i use Mapsui for Xamarin.Forms? I saw an (older) version by user charlenni but was wondering if there is a newer version and maybe this is in Mapsui 2.0 i read about...

My goal:

- add WFS / WFST layers
- click an object and get the info in an edit form

Maybe there is already an example?
My main goals is Android so if Xamarin.Forms is too far away then i'd like a hint for an example project in Android. 

Would love to hear regarding this.

Thanks!

Erwin

**Comment by pauldendulk** [comment]
Xamarin.Forms is not here yet. I intend to add it, and could have something reasonable in a day but that keeps moving into the future :)

WFS only has desktop implementation. It needs to be ported to .NET Standard 2.0. I have not looked into WFS-T at all. 

Is this something something you could work on yourself?

**Comment by pxp44** [comment]
thanks for the update. Hope Forms will work soon.

Could the WMS do the same? Meaning: click on map and get result to textbox?

Sorry, i have not a lot ofWFS WMS experience myself

**Comment by pauldendulk** [comment]
There is a WMS layer for desktop. For mobile you could use BruTile to configure a WMS called tiled. There is a sample for this. The feature info is not supported out of the box but has been implemented by others. Perhaps searching the older issues will help.

**Comment by pxp44** [comment]
thanks Paul
