### ISSUE TITLE
consider adding 'openstreetmap' topic in the Github description

### ISSUE THREAD

**Issue by matkoniecz** [Mapsui/Mapsui#478]
I was looking at https://github.com/topics/openstreetmap and https://github.com/topics/osm (to check whatever my projects are correctly tagged) and it appears that `osm` version is used rarely and almost in all cases also `openstreetmap` tag is used. This project is one of two popular ones that have only `osm`.

**Comment by pauldendulk** [comment]
Thank you! That was very easy to fix and a blind spot for me. Great suggestion.
