### ISSUE TITLE
How to determine if a point/location is on the visible map

### ISSUE THREAD

**Issue by josesimas** [Mapsui/Mapsui#481]
Hello,

I am trying determine if a certain point is already visible on the map. I found the BoundingBox Touches(Point) method in the samples and tried:

var visible = MapView.Map.Viewport.Extent.Touches(myPoint);

It always returns false. Would anyone be able to point me in the right direction?

Thanks,
Jose

**Comment by pauldendulk** [comment]
Touches only return true if the point is exactly on the edge, which is weird but probably follows the ogc spec. Try `Contains` instead.

**Comment by josesimas** [comment]
Doh, I could I miss it? Many thanks Paul.
