### ISSUE TITLE
Started using SKGLView once it is fixed

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#484]
The Mapsui iOS MapControl was reverted to use SKCanvasView because SKGLView can crash when rendering certain polygon outlines.

**Comment by pauldendulk** [comment]
This is the Mapsui issues discussing it:
https://github.com/Mapsui/Mapsui/issues/457

This is the SkiaSharp issue:
https://github.com/mono/SkiaSharp/issues/571

**Comment by pauldendulk** [comment]
The original issue was fixed in the version of skiasharp we are currently using so we could go back to SKGLView. Let's do that after release v2.

**Comment by charlenni** [comment]
The Forms implementation already uses the SKGLView.

**Comment by pauldendulk** [comment]
> The Forms implementation already uses the SKGLView.

Yes, I saw that. An indication it is stable. Still I prefer to not change the iOS implementation in this stage.

**Comment by pauldendulk** [comment]
Release in 2.0.0-beta.35

**Comment by setallunder** [comment]
In a Xamarin.iOS (Xamarin.Native) project SKGLView leads to the OOM crash (check the [SkiaSharp memory issue](https://github.com/mono/SkiaSharp/issues/1683)). It takes like a dozen navigations to a view controller with a fullscreen map to crash (iPhone 6). Changing canvas back to the SKCanvasView fixes the issue

**Comment by inforithmics** [comment]
I think the UseGPU Property should be available in base MapControl so that the other platforms can specify if GPU is used or not.

**Comment by pauldendulk** [comment]
With `MapControl.UseGPU = true` this is now a choice the user can make. It can not be used on all platforms yet, but that is not something to track in this issue.
