### ISSUE TITLE
Why change MemoryProvider to MemoryProvider2

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#485]
Are there any API changes here? For me it isn't clear, why to add a new one.

**Comment by pauldendulk** [comment]
It is only meant for 1.4 through. In 2.0 it replaces it.

There is a slight api change. 
- IEnumerable<IFeature> is now IReadOnlyList<IFeature>. 
- The IFeatures constructor is removed. 

It is a small change though. I though there was more. I had written MemoryProvider2 a long time ago. When fixing those two things fixed it could replace the existing MemoryProvider. If you want to do that please go ahead. btw, I saw another issue already. Layer uses the old MemoryProvider internally. So users won't be able to replace that. Reason for another release.

**Comment by pauldendulk** [comment]
hmm, thinking about it was already more work than doing it, so I did it. Released 1.4.7.
