### ISSUE TITLE
OGC.GPKG support

### ISSUE THREAD

**Issue by techmavengeospatial** [Mapsui/Mapsui#487]
Can Mapsui support Geopackage vector features or raster tiles?

**Comment by charlenni** [comment]
Raster tiles are supported via Mapbox tile files (mbtiles). See for this BruTile.

**Comment by pauldendulk** [comment]
Mapsui does not support GPKG, it would be in interesting format to support. There don't seem to be any .net libraries for this. An option would be to use GDAL. This would bring in a lot of functionality but it's always a hassle to get the binary deployment working smoothly. This should be a separate library.

**Comment by techmavengeospatial** [comment]
Mapsui has a converter for WKB and that's basically how the geopackage features are stored in the sqlite database blob. TILES are easy just like mbtiles except for XYZ instead of TMS.  but the tiles can be in any projection where mbtiles is only spherical web Mercator

**Comment by techmavengeospatial** [comment]
Mapsui has a converter for WKB and that's basically how the geopackage features are stored in the sqlite database blob. TILES are easy just like mbtiles except for XYZ instead of TMS.  but the tiles can be in any projection where mbtiles is only spherical web Mercator
