### ISSUE TITLE
Behavior of the polygon, changing the size of the point image

### ISSUE THREAD

**Issue by marcinsliwa1** [Mapsui/Mapsui#488]
Hello
Maybe a strange question. He builds polygons.
Is it possible to force on the polygon the lack of enlargement, reduction when changing the scale.
I want the polygon to behave when changing the scale as a point or how to resize the height and width of the image (png, svn) of the symbol for a point separately

**Comment by pauldendulk** [comment]
I need some more clarification. Do you want to change the behavior of a polygon or do you want to change the behavior of point symbol? Or do you use pointsymbols in your polygons somehow, like in the editing sample? And perhaps you can paste a picture of what you have now.

**Comment by marcinsliwa1** [comment]
1. I want to change the size of the width and length of the point symbol (SymbolScale changes the width and length), or
2. having a testing ground I want him to behave like a point symbol (he did not change the width and length when he was enlarged)

**Comment by charlenni** [comment]
I assume, that he wants to have different styles for the same feature dependent on the zoom level. If the zoom level is low, the feature is displayed as point. If you zoom in, than a polygon with fewer points should be should. Only if you want to zoom in complete, the full polygon should be shown.

Perhaps this is possible with styles dependent on the MinVisible and MaxVisible and a new behaviour, that if a polygon has a point style, that than the center point is used.

**Comment by marcinsliwa1** [comment]
Excuse me, I may have unnecessarily combined two questions.
I have a polygon. Normally, when you zoom in on the map, the polygon increases.
Is it possible that the polygon during the zooming in the map does not increase (it behaved like a point - it is about displaying)

**Comment by pauldendulk** [comment]
Seems like you want a vector image as a point symbol. You could look at SVG. There is a sample for this. You will need to convert from polygon to SVG though (or whatever your source data is).

**Comment by marcinsliwa1** [comment]
In mapsui, you can directly convert a Polygon type object to an SVG stream?

**Comment by charlenni** [comment]
No, but it shouldn't be a problem, to create a SVG from a list of points.

**Comment by marcinsliwa1** [comment]
I can get a lead, for example, because I'm just starting out in this topic

**Comment by pauldendulk** [comment]
This is an SVG library that came out of my google query: 
https://github.com/vvvv/SVG

You can iterate over vertices in a polygon with 
`Polygon.ExteriorRing.Vertices`

**Comment by pauldendulk** [comment]
You will need to correct the points for it's center position. So subtract the center for the vertex. The point you will use for the symbol will need to be positioned at the center.

To get the Center:
`Polygon.GetBoundingBox().GetCentroid()`

**Comment by marcinsliwa1** [comment]
thanks

**Comment by charlenni** [comment]
It is not complete correct. SVG coordinate systems starts on the left upper corner and goes right and down. So get the left top point of the BoundingBox, which should be substracted from each point in the polygons vertices.

Now create a string with the SVG header and add all points from the polygon as
````
<svg>
  <polygon points="p1.x,p1.y p2.x,p2.y p3.x,p3.y" />
</svg>
````
This string than could be used for creating a symbol image for Mapsui.
