### ISSUE TITLE
Perspective View Mapsui

### ISSUE THREAD

**Issue by XamHans** [Mapsui/Mapsui#490]
Hi,

is it possible to transform the View to achieve a perspectival View ?
Can i access the Canvas somehow, i did not find anything except the ITransformation.

Thanks in Advance.

XamHans

**Comment by pauldendulk** [comment]
No. You can rotate the view. So for navigation you could rotate into the direction you are driving. I assume what you want is to also tilt it backwards. That is not possible right now. 

To add this feature there will need to be transformation of the canvas. This may not be too hard. It will also affect the area in view, which will be trapezoid shaped, and thus other data needs to be fetched and drawn. This will be hard. You also need to take into account a lower level of detail for areas further from you viewpoint.

**Comment by Sonnenspeer** [comment]
Have the same problem. How can I access the canvas to transform it? 

As I have seen the MapControl.cs instantiates the canvas on each platform. But this field is private. Is there another way to access it?

**Comment by charlenni** [comment]
Take the source code and change MapControl and its Renderers.

But be carefull, Skia has problems with big numbers, because it only uses float for calculations. So, if you use matrix operations, there could be "jumping" features.

**Comment by Sonnenspeer** [comment]
Thanks. Can anyone give me a hint how I can transform the canvas after it has already drawn the map?

I.e: I want to rotate the map 90 Degree via SKCanvas. Usually you have to specify the rotation before something is drawn on the canvas but is there a possible solution to the the whole canvas content and then execute the rotation (change matrix) and then paste the content again so that it is rotated after?

Or is there a way to intercept the map drawing and add some operations before it?

**Comment by charlenni** [comment]
Map is rotated by Viewport.Rotation. That isn‘t a perspactival transformation. Paul’s answer above should you direct in the right direction.

**Comment by Sonnenspeer** [comment]
This was only an example. He said that the canvas needs to be transformated which is what I want now to achieve. The transformation only affects drawings after the transformation matrix was set.

**Comment by charlenni** [comment]
Try, ifyou could der the matrix before anything else happens. I don‘t have the code by hand, but if I remember correct, Mapsui derives from SKCanvasView.

**Comment by pauldendulk** [comment]
Perhaps the best way to go here is to create a copy of the MapControl and modify it to your needs.
