### ISSUE TITLE
How to add a floating view on the map that can show the current location?

### ISSUE THREAD

**Issue by jin-khera-eastpoint** [Mapsui/Mapsui#491]
I tried adding a custom widget but could not get it to work. What would be a good solution?>

**Comment by charlenni** [comment]
Do you want to show the current position or want you that the map shows always the current position in the center of the map?

**Comment by jin-khera-eastpoint** [comment]
<img width="318" alt="screen shot 2018-07-27 at 14 54 48" src="https://user-images.githubusercontent.com/40358958/43324936-3ac684ce-91ad-11e8-806e-8fb0a82ebe4f.png">

**Comment by charlenni** [comment]
Ah, ok. That depends on your OS. Put the map in a layout and add the overlay view to this layout too. It's like the arrow in the right lower corner or the zoom buttons.

**Comment by jin-khera-eastpoint** [comment]
It's a Xamarin Android app. The above image is just a design at the moment. Could you show some sample code of the axml file should be coded please?

**Comment by charlenni** [comment]
Sorry, but that are Android basics. In this case, Mapsui is a normal View.

Perhaps https://developer.android.com/guide/topics/ui/declaring-layout is a good starting point.

**Comment by jin-khera-eastpoint** [comment]
Thank you! I will let you know I get on.

**Comment by pauldendulk** [comment]
Side note: I added a CustomWidgetSample. This is just a start and it will have further changes.

For this use case it is better to work with Xamarin components.

**Comment by jin-khera-eastpoint** [comment]
Thanks for the update. I managed to achieve the layout needed by adding a linear layout above the map.

**Comment by pauldendulk** [comment]
Thanks for the feedback.
