### ISSUE TITLE
How can we achieve the offline map using mbtiles for xamarin forms

### ISSUE THREAD

**Issue by nrb1238** [Mapsui/Mapsui#492]
Hi 
How can we achieve the offline map using mbtiles for xamarin forms.. Can you please help out

for this mbtiles
https://openmaptiles.com/downloads/dataset/satellite-lowres/#0.23/0/-26

**Comment by charlenni** [comment]
Perhaps you should look into the samples. There is a MBTiles sample. Look [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/MbTilesSample.cs).

There isn't anything special for Xamarin.Forms. You could use the normal Mapsui handling.
