### ISSUE TITLE
Custom label

### ISSUE THREAD

**Issue by vlasovsv** [Mapsui/Mapsui#493]
Hi, guys!

Is there any method in Mapsui that can allow me to draw a custom label like this:

Some long long text
Pin=3.5 Mpa    | T=10°C | Qin=30.456 mln.m3
Pout=5.5 Mpa | T=20°C  | Qout=30.455 mln.m3

It has to be looked like a table (grid) with values in its cells.

Could you give me a direction what I can use to implement this.

P.S. Platform Windows, WPF.

Sincerely yours,
Sergey.

**Comment by pauldendulk** [comment]
There are not that many options for labels. There is no custom renderer. The only option I see is to use  the multiline labels of skia. It adds a new line after a line ending. It is in one of the samples. And then use a monospaced font and use spaces for outlining.

**Comment by vlasovsv** [comment]
Thank you for the answer. However, is it possible to extend current rendering engine (skia or wpf) without rewriting the library and add a custom renderer for labels.

I forgot to mention that every value in cells can have its own color and maybe fontweight.

Thank you!

**Comment by pauldendulk** [comment]
Another option is to use wpf controls and position them using map.viewport.viewportchanged at your desired position. Use viewport.worldtscreen for positioning.

**Comment by vlasovsv** [comment]
Thanks.
