### ISSUE TITLE
How adding a symbol style from a file ?

### ISSUE THREAD

**Issue by jmlaunay** [Mapsui/Mapsui#495]
Hello.
Really great job with this package.
I'm testing it, and i can't find how to load a symbol (.svg) from a file…
Your example is only from internal resources.
Can you help please ?
Regards,
JM Launay

**Comment by pauldendulk** [comment]
Below is the code to load an embedded resource. The method 'GetManifestResourceStream' returns a Stream. What you need to do there is get the stream from file. 

```c#
        private static int GetBitmapIdForEmbeddedResource(string imagePath)
        {
            var assembly = typeof(PointsSample).GetTypeInfo().Assembly;
            var image = assembly.GetManifestResourceStream(imagePath);
            return BitmapRegistry.Instance.Register(image);
        }
```
