### ISSUE TITLE
PanLock not working on Android

### ISSUE THREAD

**Issue by louisdevs** [Mapsui/Mapsui#496]
Please add PanLock support on Anrdroid. Currently it works only on WPF

**Comment by pauldendulk** [comment]
This will be part of the 2.0 release. Some refactoring has been done to allow to share this code over all platforms.

**Comment by jinkhera** [comment]
Is this now in the latest 2.0 beta?

**Comment by pauldendulk** [comment]
No. But almost

**Comment by pauldendulk** [comment]
This should be fixed in 2.0.0-beta.12.
