### ISSUE TITLE
XAML rendering on UWP and Xamarin Forms 

### ISSUE THREAD

**Issue by blwhttngtn** [Mapsui/Mapsui#498]
Hello, we're using Mapsui, with MbTiles on UWP and Xamarin Forms. We're very pleased thus far. Great job. We're looking to convert our static map pin (.png file) into a piece of XAML which is specific to a number/name of the Object being represented on the map. Example: if we were representing people, rather than representing a static, common .png avatar for each person on the map, we'd like to generate a new XAML TextBlock/Border indicating the name of each person, "Bob", "Jim", etc..
What's the best way to go about this? Thank you in advance folks!

**Comment by charlenni** [comment]
Perhaps you could use a combination of LabelStyle and SymbolStyle with a SVG or polygon.

**Comment by blwhttngtn** [comment]
@charlenni Thanks for your work on the Xamarin Forms nuget package. Do you know of any examples I could dig through for inspiration?

**Comment by blwhttngtn** [comment]
Thanks to you guys. I'll work on publishing an example once this is up and running. Great work. @pauldendulk and the rest of the contributors. Thanks again.
