### ISSUE TITLE
Marker image not comming

### ISSUE THREAD

**Issue by abhay081994** [Mapsui/Mapsui#500]
I am using mapsui map on that I am using a marker. right now marker in coming by symbol style but I want the image on the marker.

        public ILayer Cameramarker()
           {
           

            var s = new SymbolStyle();
            s.SymbolType = SymbolType.Rectangle;
            s.UnitType = UnitType.Pixel;
            s.SymbolScale = 0.5;
            s.SymbolRotation = 0.2;
    

            var Long = Convert.ToDouble(LongitudeLbl.Text);
            var Lat = Convert.ToDouble(LatitudeLbl.Text);
            Feature masterMarker = new Feature();
            masterMarker.Geometry = SphericalMercator.FromLonLat(Long, Lat);
            masterMarker.Styles.Add(s);

            Features ms = new Features();
            ms.Add(masterMarker);

            Layer r = new Layer();
            r.DataSource = new MemoryProvider(ms);          
            r.Name = "Camera";
            return r;
        }

**Comment by charlenni** [comment]
Look at the samples. There are examples, how to add images to a symbol style.

What format do your images have?

**Comment by abhay081994** [comment]
png  or base64

**Comment by abhay081994** [comment]
please provide links of examples.. @charlenni

**Comment by pauldendulk** [comment]
This is the 'Simple Points' sample. The third in the WPF sample: https://github.com/Mapsui/Mapsui/blob/1.4/Samples/Mapsui.Samples.Common/Maps/PointsSample.cs
