### ISSUE TITLE
Dynamic SVG Layers

### ISSUE THREAD

**Issue by blwhttngtn** [Mapsui/Mapsui#501]
Hey guys. Thanks for the help before. Today, wondering if you've got a work around for controlling the overlap in high-feature-density areas that occurs her between Label/SVG layers. Should I try adding these label-features into the same layer as the SVGs? Maybe build dynamic SVG layers with the label-text built-in to the SVG? 

best, Blake

![whatsapp image 2018-08-26 at 11 31 11 am](https://user-images.githubusercontent.com/12670350/44634203-49c3a500-a94b-11e8-9087-e03e9b87cb6d.jpeg)

**Comment by pauldendulk** [comment]
ah, Ii see the problem. This is actually a desired behavior in most other situation. In this case you want it to be handled as on symbol.

So, this is layer with SVG symbols with a layer with labels on top of it?

I was thinking about a StyleCollection containing both the SVG and Label, but looking at the code I think this will have the same effect. 

What probably will work is adding both styles on the individual features. This might not be an easy change for you.

**Comment by pauldendulk** [comment]
@blwhttngtn Any success?

**Comment by blwhttngtn** [comment]
@pauldendulk Yes! Absolutely. 

It's possible to create dynamic SVG layers, effectively passing strings as parameters into the file before registering the BitmapId for use in the image layer.

One way: create your base SVG file and include it in your project as an EmbeddedResource. Open the file from manifest stream. Make insertions into the SVG's XML. You might insert names like "Jim, Bob, or Barbara" to be generated as a component of this first SVG. After making the insertions into the SVG's XML, register the BitmapId for usage, and move onto the next object, inserting the next name for example into the SVG.

End result: your text/graphic layers will be consolidated into 1 style layer which will --in this case-- achieve the overlapping-as-a-whole-unit-result.

Any opinions on long-term issues with this -- performance or otherwise? Best, Blake

**Comment by pauldendulk** [comment]
So you are creating the SVG symbols on the fly. Does this mean you need to call BitmapRegistry.Register for each bitmap you create? If so, they will not be released unless you call BitmapRegistry.Unregister.

**Comment by blwhttngtn** [comment]
@pauldendulk Yes, thank you for that. Mind if I ask when it's reasonable to Unregister the layers? I'm assuming it's appropriate to Unregister: when 1) refreshing the symbol layers (removing and inserting symbol layers) and 2) closing the app. This means that I'll be leaving the SVG symbols in their "registered" state while the user navigates the application, waiting for them to return to interact with the maps/symbols.
