### ISSUE TITLE
How to keep map from zooming beyond limits and keep tiles in view

### ISSUE THREAD

**Issue by jin-khera-eastpoint** [Mapsui/Mapsui#502]
I am developing an Android app that has bundled mbtiles. I want the prevent the map from zooming too far out and limit the zoom and pan. I have set the MinMax, ZoomMode and PanMode, but these do not achieve what is needed. What ends up happening is that the map will zoom too far out and/or pan too far leaving grey background showing.

**Comment by pauldendulk** [comment]
Unfortunately this does not work in 1.4 for Android (only for WPF). This will be part of the v2 release. Probably in the next beta. This could take quite some weeks though.

**Comment by jin-khera-eastpoint** [comment]
Thanks for the update Paul. I will keep track of 2.0.

**Comment by pauldendulk** [comment]
With 2.0.0-beta.9 this should now work on all platforms.
