### ISSUE TITLE
ScaleBar Widget

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#504]
Hi,

when for zooming is used mouse scroll button the Mapsui.Widgets.ScaleBar.ScaleBarWidget works incorrectly, shows wrong scale bar and value. (when the Mapsui.Widgets.Zoom.ZoomInOutWidget is using for that all is fine).
Also when the map is in large distance and we move the map by mouse dragging or move the map outside the window/view(envelope?) the ScaleBarWidget is completely wrong.

I can prepare the video presentation to show the issue if you need.

Best Regards,
Łukasz

**Comment by pauldendulk** [comment]
Which version of Mapsui are you using?

**Comment by lukaszpitulski** [comment]
1.4.4

**Comment by lukaszpitulski** [comment]
MapControl.Map.Widgets.Add(new Mapsui.Widgets.ScaleBar.ScaleBarWidget(MapControl.Map) { TextAlignment = Mapsui.Widgets.Alignment.Center, HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Left, VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Bottom, MarginX = 40, MarginY = 40, TextColor = Color.Black, Halo = Color.White, Font = new Font{ FontFamily = "Arial", Size = 14 }, ScaleBarMode = ScaleBarMode.Both, Height = 19, MaxWidth = 200, TickLength = 5, ShowEnvelop = false });

MapControl.Map.ZoomLimits = new MinMax(0.009, 40000);
MapControl.Map.ZoomMode = ZoomMode.KeepWithinResolutionsAndAlwaysFillViewport;

**Comment by lukaszpitulski** [comment]
the map on the full window and min zoom
![obraz](https://user-images.githubusercontent.com/15933140/44961609-49f80d80-af14-11e8-942e-8c2372295827.png)


the same zoom and map is moved, a part of it is outside the view (window)
![obraz](https://user-images.githubusercontent.com/15933140/44961616-5b411a00-af14-11e8-88db-260ab2e720ba.png)

the same zoom and map is moved, more of it is outside the view (window)
![obraz](https://user-images.githubusercontent.com/15933140/44961620-7875e880-af14-11e8-8561-c3429c396a47.png)

please have a look at the ScaleBarWidget on the left-bottom corner

**Comment by charlenni** [comment]
Be careful, the ScaleBar uses always the center point of the map to calc the size and values. So, if this center point moves from north to south or vice versa, the values are changing. This isn‘t the case, if the center point moves west-east. This is correct behavior for Google and OSM type maps.

**Comment by lukaszpitulski** [comment]
ooo because the map is not flat, like paper one... is a globe.

I've checked the OSM and Google maps.

Now(OSM) if I look on Japan the scaleBar length is the same like when I look on Alaska where the values are different...  for both places the zoom is the same.

Japan's 300km ≈ Alaska's 200km

so, when I move the map east/west the scaleBar is the same all the time, when move on north/south it's being changed... the globe, GOT IT!

Japan
![obraz](https://user-images.githubusercontent.com/15933140/45021119-09da7d00-b031-11e8-96f3-df66286accf4.png)

Alaska
![obraz](https://user-images.githubusercontent.com/15933140/45021160-22e32e00-b031-11e8-8015-d0845c4ecbe4.png)

**Comment by lukaszpitulski** [comment]
I've checked zooming by scroll, and it's mouse cursor (position on map) case, so the issue is exactly related to above... the scaleBarWidget working is still confusing for end user but only in small zoom, and when the center is moving N/S... so ok, please change type/Labels of the issue, it's not Bug.

BTW where I can find any other widgets? Any info/doc about it.

**Comment by pauldendulk** [comment]
Thanks for reporting your full conclusion.

**Comment by charlenni** [comment]
The only other widget I made is the zoom in and out widget. But this is a terrible example for a widget. This should be made by normal controls.

A widget should be a thing, that’s doesn‘t move with the map. Another good example for a widget would be a center cross, which always shows the center of the map. If I have time, I try to make this.

**Comment by lukaszpitulski** [comment]
Yes, the center cross that would be great! 

I've resolved it by creating a bitmap (feature) on on of the layer, which position is calculated and re-added each time when navigation is going on. (#399 , #398 )

(many BitmapRegistry.Instance.Register (MemoryStream)...  so, it could be on of the reason of memory issue #504 )

**Comment by charlenni** [comment]
To be clear: you should add each bitmap (PNG or SVG) only once to the map. The Register function returns a BitmapID, which represents the saved bitmap. The memory for this bitmap isn‘t released until you release the map. So, if you have 100 symbols with the same bitmap and you register this bitmap 100 times, than the bitmap is 100 times in your memory. There is no part in Mapsui, that checks, if the bitmap is already registered. I don‘t know, if this is useful. Could be getting complicated, if you have many different bitmaps and want to check each new one against all old ones.

**Comment by charlenni** [comment]
Sorry, small smartphone screen.

There is a Unregister function for bitmaps. So you can unregister the bitmap of the last position and than add a new one. But this is silly. The best would be a widget, which is drawn above the map.

**Comment by lukaszpitulski** [comment]
#511
