### ISSUE TITLE
LabelStyle in polygon

### ISSUE THREAD

**Issue by marcinsliwa1** [Mapsui/Mapsui#505]
Hello.
I have a croissant polygon (like half a moon). The description of the polygon is outside the polygon.
Is there a method to set the description in the polygon.

**Comment by lukaszpitulski** [comment]
play with Offset

**Comment by lukaszpitulski** [comment]
for me this works ok:
new LabelStyle
{
HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Left,
VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Top,
Offset = new Offset(-0.4, 0, true)
}

**Comment by pauldendulk** [comment]
Offset can help if you know what polygon you are dealing with.

**Comment by pauldendulk** [comment]
Unfortunately there is no better way position labels. This is something that needs improvement.

A workaround might be that you create your own custom layer which takes the polygon layer as input. In the GetFeatures method you should return a point based on the polygon. Calculating such a label position might not be easy.

**Comment by pauldendulk** [comment]
Closing this. Still interested if you got a workaround to fix this.
