### ISSUE TITLE
Mapsui incorrectly supports SkiaSharp (>= 1.59.3 && < 2.0.0) 

### ISSUE THREAD

**Issue by radderz** [Mapsui/Mapsui#507]
Mapsui is looking for SkiaSharp.Svg but there was a breaking change in 1.60.0 and greater where SkiaSharp.Extended.Svg is the name of the binary instead.

**Comment by radderz** [comment]
This occurs on iOS and Android, there seems to be no extra dependancy on this new dll for UWP

**Comment by pauldendulk** [comment]
Is this in 2.0 and 1.4?

**Comment by pauldendulk** [comment]
@radderz Did you run into this using 1.4? or 2.0? 

I would assume 2.0 has no problem because it's lower version is 1.60.0.

If it is only 1.4 I think I should just put it's dependency lower bound to 1.60.0 to fix this.

**Comment by pauldendulk** [comment]
This is fixed in 1.4.8.
