### ISSUE TITLE
Mapsui Xamarin - Set Resolution

### ISSUE THREAD

**Issue by TechGuyGeek** [Mapsui/Mapsui#508]
Hi Am just trying to find my feet with your Mapsui its great thanks and finding https://development-blog.eu/an-own-map-with-mapsui-in-xamarin-forms-entwurf/ on the net has really helped 

Im struggling to find the ability to set home or Resolutions for this is this because this is not setup yet for Xamarin or could you piont me in the right direction?

          var mapControl = new MapsUIView();
            mapControl.NativeMap.Layers.Add(OpenStreetMap.CreateTileLayer());
           
            // var map = new Map();

            var layer = GenerateIconLayer();
            mapControl.NativeMap.Layers.Add(layer);
            mapControl.NativeMap.InfoLayers.Add(layer);

            // Get the lon lat coordinates from somewhere (Mapsui can not help you there)
            var centerOfLondonOntario = new Point(-81.2497, 42.9837);
            // OSM uses spherical mercator coordinates. So transform the lon lat coordinates to spherical mercator
            var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfLondonOntario.X, centerOfLondonOntario.Y);
            // Set the center of the viewport to the coordinate. The UI will refresh automatically
            // Additionally you might want to set the resolution, this could depend on your specific purpose
            //map.Home = n => n.NavigateTo(sphericalMercatorCoordinate, map.Resolutions[9]);
           // mapControl.NavigateTo(map.Resolutions[17]);

**Comment by pauldendulk** [comment]
The map.Home should do this. You have it commented out. Perhaps it did not work properly but it should. It is new functionality so could contain bugs.

**Comment by TechGuyGeek** [comment]
Wow thanks for your quick response really appreciate it, i commented it out as it says  "Map does not contain a definition called Home "

using System.Diagnostics;
using Mapsui.Geometries;
using Mapsui.Layers;
using Mapsui.Providers;
using Mapsui.Styles;
using Mapsui.Utilities;
using Mapsui.Projection;
using Mapsui;

namespace Pages.Maps
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class JasonMaps
	{
		public JasonMaps ()
        {
            InitializeComponent();

            var mapControl = new MapsUIView();
            mapControl.NativeMap.Layers.Add(OpenStreetMap.CreateTileLayer());
           
            var map = new Map();

            var layer = GenerateIconLayer();
            mapControl.NativeMap.Layers.Add(layer);
            mapControl.NativeMap.InfoLayers.Add(layer);

          
            var centerOfLondonOntario = new Point(-81.2497, 42.9837);
             var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfLondonOntario.X, centerOfLondonOntario.Y);         
            map.Home = n => n.NavigateTo(sphericalMercatorCoordinate, map.Resolutions[9]);
           // mapControl.NavigateTo(map.Resolutions[17]);

**Comment by pauldendulk** [comment]
ah, you are using 1.4 (v2 is indeed not stable). Perhaps you can checkout the 1.4 branch and look at the samples there.  https://github.com/Mapsui/Mapsui/tree/1.4.7

**Comment by TechGuyGeek** [comment]
Ar great, yeah when i load the version 2 instead it does like the home but crashes me app with the Error "Could not resolve type with token 01000085 (from typeref, class/assembly Mapsui.INavigator" will have a look at what you said to see if i can find an alternative thanks

**Comment by pauldendulk** [comment]
I suspect that exception is because of compile issues. When switching between .NET Standard and PCL I always have to delete bin and objs. 

Yet if 1.4 suffices then keep using that.

**Comment by TechGuyGeek** [comment]
Perfect thanks 

 mapControl.NativeMap.NavigateTo(sphericalMercatorCoordinate);
 mapControl.NativeMap.NavigateTo(mapControl.NativeMap.Resolutions[18]);

**Comment by TechGuyGeek** [comment]
Hi Paul 
Hope you dont mind me bothering you again :)
I have checked the sample files for reference to Markers on your site and i can see people looking at the idea in other posts but i just can not see where i should be looking, i assume this is possible with your Mapsui, is it symbols that i should be looking at? In the past i did manage to create what i was looking for using OSMdroid but i must say your Mapsui loads the maps a lot faster :)   Im hoping to be able to place some marks on the map and have a click event for each marker?

**Comment by pauldendulk** [comment]
Please create a new issue for a new question.

There is a Points sample that uses bitmaps as symbols. Perhaps only in master branch. But the logic is the same.

**Comment by pauldendulk** [comment]
I am closing this as the 'set resolution' question has been answered. If you have more questions please open a new issue. It is no problem if you ask questions that you can not answer with documentation or samples. It tells us what is hard to understand and where our samples and documentation should be clearer. Please post specific questions, one at a time. Such questions (and answers) can help other users as well.
