### ISSUE TITLE
Skia throwing nullreference exceptions after WPF control has been over map

### ISSUE THREAD

**Issue by pingurus** [Mapsui/Mapsui#509]
I have a contextmenu that opens up over the map when the user clicks. After I've closed it again, skia throws a nullreference exception when trying to get Mapinfo and when dragging the map.
Callstack for the case of dragging the map:

> System.NullReferenceException
  HResult=0x80004003
  Nachricht = Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Quelle = Mapsui.Rendering.Skia
  Stapelüberwachung:
   bei Mapsui.Rendering.Skia.SymbolCache.GetSize(Int32 bitmapId)
   bei Mapsui.UI.MapInfoHelper.IsTouchingTakingIntoAccountSymbolStyles(Point point, IFeature feature, IStyle layerStyle, Double resolution, ISymbolCache symbolCache, Int32 margin)
   bei Mapsui.UI.MapInfoHelper.<>c__DisplayClass1_1.<GetMapInfo>b__0(IFeature f)
   bei System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Mapsui.UI.MapInfoHelper.GetMapInfo(IEnumerable`1 layers, Point worldPosition, Point screenPosition, Double resolution, ISymbolCache symbolCache, Int32 margin)
   bei Mapsui.UI.Wpf.MapControl.InvokeInfo(IEnumerable`1 layers, IEnumerable`1 widgets, IReadOnlyViewport viewport, Point screenPosition, Point startScreenPosition, ISymbolCache symbolCache, Action`2 widgetCallback, Int32 numTaps)
   bei Mapsui.UI.Wpf.MapControl.MapControlMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei System.Windows.Application.Run()
   bei GeocachingTourPlanner.App.Main()

Is this a bug or am I doing something wrong?
Thank you

**Comment by pauldendulk** [comment]
This is not expected. Is there any call to `BitmapRegistry.Instance.Unregister` in your code? Do you use WPF or Skia rendering? Do switch between the WPF and Skia renderer? What do you do when you click in the context menu? (or is it just to call the MapInfo?). Can you successfully call MapInfo before you show the menu?

**Comment by pingurus** [comment]
- Is there any call to BitmapRegistry.Instance.Unregister in your code?
No
- Do you use WPF or Skia rendering? 
I don't know, honestly. The default if there is one
- Do switch between the WPF and Skia renderer? 
No
- What do you do when you click in the context menu? (or is it just to call the MapInfo?). 
Tested it again, it just happens if I add a new WritableLayer to the map
- Can you successfully call MapInfo before you show the menu?
Yes, since I need to determine what was clicked to show the menu

Thanks for your quick response

**Comment by pingurus** [comment]
I fixed it by adding a memorystream for the picture used in the feature I added.

**Comment by pauldendulk** [comment]
What type did you use before.

**Comment by pingurus** [comment]
Before I used an Svg like this:
`IStyle MarkerStyle = new SymbolStyle { BitmapId = BitmapRegistry.Instance.Register(Properties.Images.Pin_black), SymbolType = SymbolType.Svg, SymbolScale = App.DB.MarkerSize, SymbolOffset = new Offset(0.0, 0.5, true) };`
Now I manipulate that Svg first and then save it to a memorystream and then register that

**Comment by pauldendulk** [comment]
Ok. Perhaps the argument to the register funtion should not be an object to avoid this.
