### ISSUE TITLE
Is Mapsui MVVM friendly?

### ISSUE THREAD

**Issue by mattmiley** [Mapsui/Mapsui#510]
Hey Paul, I want to use mapsui in my xamarin forms application. I followed this [https://development-blog.eu/an-own-map-with-mapsui-in-xamarin-forms-entwurf/](url) and was able to get a map to show up by adding a layer in the xaml code behind. Is there anyway I can just modify this to just databind the map and set all the layers and everything with strictly with data binding? That's how my project is structured and I'd like to keep it that way.

**Comment by mattmiley** [comment]
Never mind, this worked... [https://stackoverflow.com/questions/28098020/bind-to-xamarin-forms-maps-map-from-viewmodel](url)

**Comment by pauldendulk** [comment]
Thanks for the info, this might be useful for others.

**Comment by giaza** [comment]
> Never mind, this worked... https://stackoverflow.com/questions/28098020/bind-to-xamarin-forms-maps-map-from-viewmodel

Hi Matt, 
can you share your code? I couldn't get it to work in my forms app.
Thanks in advance.

**Comment by mattmiley** [comment]
pull this nuget
Install-Package Mapsui.Forms -Version 2.0.0-beta.17	

Ref Mapsui on page xaml
xmlns:sui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms"


Add your map to your xaml            
<sui:MapControl  x:Name="myMap" />

In your code behind.
Binding you VM then bind the map on appear

`public partial class HomeView : ContentPage
    {
        HomeViewModel viewModel;

        public HomeView()
        {
            InitializeComponent();            

            BindingContext = viewModel = new HomeViewModel();
        }

        protected override void OnAppearing()
        {
            viewModel.MapControl = myMap;
        }       
    }`

**Comment by giaza** [comment]
Thank you.
I'll take a look.
Though I am not using Mapsui.Forms but Mapsui 1.4 with custom renderer as Mapsui.Forms is still in beta.

**Comment by mattmiley** [comment]
That's what I was using before I upgraded, you'll be fine. Obviously reference the right lib in xaml then OnAppearing just do  
`viewModel.Map = myMap.Map;`
