### ISSUE TITLE
AllVertices vs MainVertices

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#512]
Hi,

What is the difference between them exactly?
When should I use which one and why?

Thanks,
Łukasz

**Comment by pauldendulk** [comment]
MainVertices was added for editing. It returns the MainVertices as a list. For a multipolygon this is only the outer ring. It is only implemented for Point, LineString and Polygon. It is just a helper for editing.

AllVertices was added for re-projection. It iterates over all vertices in any geometry.

**Comment by lukaszpitulski** [comment]
I have a code:
```

editManager.TryInsertVertex(mapControl.GetMapInfo(screenPosition, editManager.VertexRadius));

public bool TryInsertVertex(MapInfo mapInfo)
{
	if (mapInfo.Feature == null) return false;

	var vertices = mapInfo.Feature.Geometry.MainVertices();

	if (TryInsertVertex2(mapInfo, vertices, VertexRadius))
	{
		mapInfo.Feature.RenderedGeometry.Clear();
		Layer.SignalDataChanged();
	}
	return false;
}

public static bool TryInsertVertex2(MapInfo mapInfo, IList<Point> vertices, double screenDistance)
{
	var (distance, segment) = GetDistanceAndSegment(mapInfo.WorldPosition, vertices);
	if (distance <= mapInfo.Resolution * screenDistance)
	{
		vertices.Insert(segment + 1, mapInfo.WorldPosition.Clone());
		return true;
	}
	return false;
}

```
The code
doesn't work: `var vertices = mapInfo.Feature.Geometry.AllVertices().ToList();`
is fine: `var vertices = mapInfo.Feature.Geometry.MainVertices();`

but the methods return the same values (in that case).

**Comment by lukaszpitulski** [comment]
generally in the solution I have to use MainVertices instead of AllVertices

**Comment by pauldendulk** [comment]
In the context of editing you should use mainvertices.

**Comment by lukaszpitulski** [comment]
OK
