### ISSUE TITLE
Multitouch screen - WPF

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#513]
Hi,
(if the case was already, please, send me there, thanks)

When I use the mouse, I have:
MapControl.MouseLeftButtonDown
MapControl.MouseLeftButtonUp
(MouseButtonEventArgs, ....GetPosition(MapControl).ToMapsui() )

What should I use for a finger (touchscreen)?
I's trying with TouchStarted and TouchEnded but don't work for me (maybe I do something wrong).
Also I's trying with TouchDown and TouchUp, TouchEnter and TouchLeave, GotTouchCapture and LostTouchCapture; but work a little chaotic (sometimes have nothing sometimes a few points/touches in one place - as if the screen is too sensitive?).
![obraz](https://user-images.githubusercontent.com/15933140/45579070-9254eb00-b885-11e8-8aad-47b0cdfa51ce.png)
![obraz](https://user-images.githubusercontent.com/15933140/45579244-99302d80-b886-11e8-9d4d-5b1770a3d8c9.png)
![obraz](https://user-images.githubusercontent.com/15933140/45579403-984bcb80-b887-11e8-8fd9-8a750f74c292.png)

The issue is when I try edit/add any feature of WritableLayer. (with mouse is ok)
TouchStarted/Ended - When I touch the screen nothing happening, still I can move the map and zoom it (by a finger).
TouchDown/Up, TouchEnter/Leave, etc. - Could be fine but how to handle a double-click?
Maybe I can use DoubleTap?

Maybe I can use MapControl.Map.Info mapInfoEventArgs.MapInfo.WorldPosition or SingleTap or mix of any?

I don't have any experience with touch screens.

Please help!

Thanks,
Łukasz

**Comment by pauldendulk** [comment]
I know nothing about touch manipulation in WinForms. This is not really a Mapsui issue. Perhaps you can ask one of your colleagues.

**Comment by pauldendulk** [comment]
The touch manipulation in wpf might be very different in wpf and winforms. Wpf has it's own touch support. I expect winforms to do to some kind of mouse emulation. So you should investigate this in a winforms sample.

**Comment by lukaszpitulski** [comment]
The WPF is in WinForms app via UserControl but it's still Mapsui.UI.Wpf.MapControl

And I would like to use MapControl and EventHandlers of it.
(like for MapControl.MouseLeftButtonDown and MapControl.MouseLeftButtonUp)

How I mentioned, in clear WPF app (no winforms) the situation is exactly the same, and first I need to have it in WPF next I can think about WinForms.

Any idea how can I solve this? Any one?!

**Comment by pauldendulk** [comment]
Are you sure it is the same? In wpf there are touch events. Do these work when embedded in winforms?

**Comment by lukaszpitulski** [comment]
I'm working with WPF app now only.

Maybe it's problem of the device what I have here (IRTOUCH).

The work is still going on, and so far:
- I have mouse events conflict with touch events (move, up, down)
- I need to use ((UIElement)MapControl).TouchMove because MapControl.TouchMove doesn't work for me
- I can't catch DoubleTouch(doubleclick/tap), MapControl.DoubleTap doesn't work at all
- I need to look at touching differently than at mouse clicking and moving, e.g. mouse movement can be with or without LeftButton down, any motion on touchscreen are always by touching, etc.
But I want to replicate the mouse states and actions using the touchscreen.
- I don't know how to recognize if I use touchscreen or standard one (or if touch or mouse)? (TouchDevice?)
- I don't want to create own things with System.Windows.Input.Touch etc. I would like to use what I already have in the solution and in the Mapsui 1.4.*

If anyone has any idea or advice please comment.

I will let you know about the progress and if I finally solve the issue, I will close it.

**Comment by charlenni** [comment]
How about an overlay on top of Mapsui MapControl?

**Comment by lukaszpitulski** [comment]
Could you explain exactly what do you mean?

**Comment by charlenni** [comment]
Put an object, that works correctly with touch events on top of the MapControl and catch all events. Than forward the events to MapControl, that you don't need.

You could add changes to Mapsui by your own. It is a open source project and all others, that want a new feature, have to do this too.

**Comment by lukaszpitulski** [comment]
I have some solution already. (for our requirements)
Maybe it's not beautiful but works... except the situation when I would like to draw more like one object(feature) at once.

Let me explain (touchscreen).
When I draw a polygon, I touch the screen and have a point, next touch again and next point and next one so I have the polygon (3 points = triangle), now: I save the layer and then (simulate double-click) end editing (method outside the map, button in GUI).
When I want to draw two or more polygons, I draw one and now I can't draw next one because each touching it's a next point of first one, and I can't save layer because it will end editing and 'll save one polygon only.
Double touch creates two points (each touch = one point, always).

With mouse, I don't have to worry because I can finish drawing first polygon by double click and start drawing next one and next and etc.
So, before end of the edit I have many polygons on the map (in one "session" of edit).

So still is the issue with double-touch/click/tap on the MapControl.

I think, I will create some method (button in GUI) where I will end editing of each polygon without saving layer. And then will use the method witch I have already to finish and save the layer.

Not nice, but if I don't have a mouse, only touchscreen and don't have a double-click... I don't see another solution for now.

**Comment by lukaszpitulski** [comment]
in Mapsui is Mapsui.Geometries.MultiPolygon, I'm not sure how I can use it, draw it?
