### ISSUE TITLE
MapsUI 1.3.0.0, NullReferenceException in Skia\MapRenderer 

### ISSUE THREAD

**Issue by PChristoph** [Mapsui/Mapsui#516]
Greetings!

I found a bug, appearing from time to time. Not sure what might cause this, because most of the time everything is fine. Unfortunately the given information won't tell much.

System.NullReferenceException ist aufgetreten.
  HResult=-2147467261
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=Mapsui.Rendering.Skia
  StackTrace:
       bei Mapsui.Rendering.Skia.MapRenderer.RenderToBitmapStream(IViewport viewport, IEnumerable`1 layers, Color background) in C:\Users\Poeppelbaum\Downloads\Mapsui-master(6)\Mapsui-master\Mapsui.Rendering.Skia-PCL\MapRenderer.cs:Zeile 57.
  InnerException: 

the local variable "surface" is null, which renders the map totally blank.

I'm attaching a screenshot with the stacktrace and location in the code. I'm not sure how I can provide more details, but don't hesitate to ask!

![image](https://user-images.githubusercontent.com/18269443/45870110-6e643e80-bd8a-11e8-999b-f3de1b5a1ba6.png)

Best regards
Christoph

**Comment by charlenni** [comment]
What values do you have for viewport.Width and viewport.Height in this case?

**Comment by pauldendulk** [comment]
Is this a raster layer?

How is the memory consumption at that point?

Maybe we should look into SkiaSharp when SKSurface.Create could return null. 

Is is indeed a good idea to check the values for Height and Width.

**Comment by pauldendulk** [comment]
The image of the stack trace shows that there is a rasterizing layer calling RenderToBitmapStream.

**Comment by pauldendulk** [comment]
Which version of Mapsui? Which platform? (Android/iOS/WPF).

**Comment by Manu-F** [comment]
Hi, i am a colleague of PChristoph. Currently he is on holiday for three weeks. He asked me to look at this thread.
We are using WPF with .NET Framework 4.6.1. All Mapsui dlls are on version 1.3.0.0 except Mapsui.Desktop.dll is on 1.1.1.0.

**Comment by pauldendulk** [comment]
Thanks. I will add some checks and release Mapsui 1.4.7.

I assume you have built the desktop version yourself.

**Comment by pauldendulk** [comment]
I released 1.4.8.

**Comment by pauldendulk** [comment]
I consider this fixed. Please reopen if it's not.
