### ISSUE TITLE
Mapsui 2.0 to .NET Standard 2.0?

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#517]
I am considering to move Mapsui 2.0 to .NET Standard 2.0 to avoid a NETStandandard.Library consolidate issue. I get the impression there are other hidden complications as well. And there is this [tweet](https://twitter.com/davidfowl/status/1008453902058917888?lang=en). Xamarin.Forms will be .NET Standard 2.0 by default. So I assume most users will just be on 2.0.

Who sees a problem with this?

**Comment by pauldendulk** [comment]
2.0.0-beta.9 is release with .NET Standard 2.0.

**Comment by hwd71** [comment]
Sooner the beta :) I can't see beta 9.

**Comment by pauldendulk** [comment]
You need to check show prereleases in the nuget manager.

https://www.nuget.org/packages/Mapsui/2.0.0-beta.9

**Comment by hwd71** [comment]
Thanks for that, will give it a go 😊



Sent from Mail for Windows 10

**Comment by alainju** [comment]
I think it's a very good idea to pass mapsui 2.0 in .netStandard 2.0, actually it becomes the norm for Xamarin. 
I also believe that having a Xamarin.Forms version of Mapsui 2.0 is very important. 
Even if the future control derived from Xamarin.Forms.View is succinct, it would be easy to add BindingProperties. 
The trend is towards Xamarin.forms rather than Xamarin.Android and Xamarin.IOS
Do you have any idea of the release date of a first version of a Xamarin.Forms.View control?

**Comment by hwd71** [comment]
I found the skia renderer worked well on Forms, except the VP init was a bit nasty coming from the XF custom renderer code. I could overlay a canvas and implement drawing on the map OK. I hope you'll keep the renderer nicely decoupled as it is, as I'm using mapsui with a custom renderer, and I'd like to avoid breaking changes!

**Comment by pauldendulk** [comment]
What is VP init?

**Comment by hwd71** [comment]
Sorry, InitializeViewPort.

**Comment by hwd71** [comment]
And when you say "map lock feature", you're not talking about locking the zoom level until the touch event is complete, are you? That's something I definitely need.. it's nice to zoom in, so see something, without the thing reloading new higher-res tiles, whilst you're trying to read it :)

**Comment by charlenni** [comment]
I have a Xamarin.Forms implementation with a native Skia MapControl and a XF MapView. It replaces the native MapView of XF. You could find it in the Forms branch of my Mapsui repository. So, if Paul starts to work on this, it should go fast.

**Comment by pauldendulk** [comment]
@hwd71  you say:

> And when you say "map lock feature", you're not talking about locking the zoom level until the touch event is complete, are you? That's something I definitely need.. it's nice to zoom in, so see something, without the thing reloading new higher-res tiles, whilst you're trying to read it :)

How would this work exactly? There will be no change in zoom level of the map until you let go? Or you do not mind to see the change, but don't want Mapsui to show tiles from another resolution?

What is the reason you want this? Is the font to small when it shows another level? Is the sudden jump between layers confusing?

Are there any other map components that work like this?

**Comment by hwd71** [comment]
Yes; on "touch", it's useful to be able to pinch zoom without the reload, to look at a feature in more detail, without having the tiles reload. Although, on zoom-out, you do need the new edge tiles loading.. so, a bit tricky. Having a "zoom-lock" on the chart would help control this.

The "sudden jump" is also a pain, with two finger drag/zoom, which can introduce a flicker as you inadvertently flick between one zoom and another; I want a "hysteresis" effect.

Google maps is of course the best, I think, that I know of currently, on touch.

**Comment by pauldendulk** [comment]
@hwd71 okay, I see. Hysteresis might be possible is the renderer has some adjustment for it's fetch resolution depending on the direction of zooming. 

Other things that might help:
- Vector tiles. The switch between levels will be less abrupt.
- Labels that are not part of the bitmaps but drawn on top.
- Perhaps it is also an option to inflate te tiles more. The tiles are designed for an optimal resolution. When in between there optimal levels there is an arbitrary point in which we switch from one level to another. The point could perhaps be chosen differently.

These points all need code changes.

**Comment by charlenni** [comment]
Perhaps this is a new issue? 😁

**Comment by hwd71** [comment]
Interesting points, thanks. I'm liking the idea of fading from one to another. Perhaps this stuff really belongs in the renderer, in that the map is good at iterating visible features over a region; perhaps it's the renderer's job to decide what to paint or not dependant on hysteresis etc. 

Definitely off topic, sorry about that! But, no issue from me really, as I'm using a custom renderer.

**Comment by pauldendulk** [comment]
@charlenni Yes, I should have started a new issue when inquiring further about hwd71 interpretation of lock. Many issues have become messy. Maybe we should be a bit more strict in this.

**Comment by pauldendulk** [comment]
@hwd71 but, to actually answer your question. The zoom lock part of 2.0 is something different. I ZoomLock = true the user can not change the resolution with either pinch zoom, mouse wheel or zoom buttons.

**Comment by hwd71** [comment]
FYI Just moved to the preview, NetStandard 2, and made the effort to move to the new separate Viewport, and discovered the Navigator.. shiny! Only using Mapsui and Geometries, but all is well; keep up the good work!

**Comment by charlenni** [comment]
@hwd71 You say, that you only use Mapsui and Geometries. Could I ask, what you are doing with them? Do you not use any renderer?

**Comment by hwd71** [comment]
Thanks @ZoomLock.. 
I'm trying to get an Urho renderer running, but it's quite prototype.

**Comment by pauldendulk** [comment]
We have chosen .NET Standard 2.0.
