### ISSUE TITLE
the nearest point to the polygon from the point (the tangent point of the lines)

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#520]
Hi,

Is it chance to have by Mapsui methods a solution for the query below?

How to find the closest point of polygon ring to external point?
More precisely:
- there is a polygon, where the ring of it is some line with start and end points
- there is a point (X,Y) "green"
- from the point to the line is some distance, the shortest one, the distance's line is perpendicular to the polygon ring's line
- the place where the distance's line comes into contact with the r-line is the closest point "red"
how to find coordinates (X,Y) of the point?

I try some trigonometry and analytic geometry calculations but without any success for now.

Any ideas?

Best Regards,
Łukasz

![obraz](https://user-images.githubusercontent.com/15933140/46108036-5acb3480-c1dd-11e8-869b-0d9a0a83e19a.png)

![obraz](https://user-images.githubusercontent.com/15933140/46108064-6880ba00-c1dd-11e8-869e-4c43e1aba1d4.png)

**Comment by lukaszpitulski** [comment]
Another similar query is, how to find the intersection point of the two lines where the starting and ending points of the two are known, using Mapsui?

In this case:
- one line is from the point to the center of the polygon (polygon.GetBoundingBox().GetCentroid())
- second one is part of the polygon's ring (one of polygon.InteriorRings?)

Maybe something like this:
```
Point thePoint = null;
var line = new LineString(new []{ point, polygon.GetBoundingBox().GetCentroid() });
foreach (var lv in line.Vertices)//here should be some iteration by each point of the line but every few pixels / degrees, not only start and end
{
	if (polygon.Contains(lv))
	{
	        thePoint = lv;
		break;
	}
}
```

![obraz](https://user-images.githubusercontent.com/15933140/46109073-e04fe400-c1df-11e8-912c-7d0dd8c18233.png)

**Comment by charlenni** [comment]
There are many websites for this. Mapsui isn‘t the correct place to find it.

https://en.m.wikipedia.org/wiki/Distance_from_a_point_to_a_line
https://stackoverflow.com/questions/10983872/distance-from-a-point-to-a-polygon

**Comment by lukaszpitulski** [comment]
I was hoping the Mapsui would help me, using some methods/algorithms.

But I have the solution already (for the lines). From pattern of point of intersection of two straight lines.
I still have to find the line of the polygon which intersects with the line from the ext-point.
(polygon.InteriorRings ?)

![obraz](https://user-images.githubusercontent.com/15933140/46112010-54db5080-c1e9-11e8-8417-c4c30ec99dff.png)

**Comment by lukaszpitulski** [comment]
Sorry, but it doesn't give me peace.
It's impossible that Mapsui doesn't have the right methods.

What with  Mapsui.Geometries.Utilities.Algorithms  and Mapsui.Geometries.Utilities.CGAlgorithms  methods?

I already have some kind of solution of the issue.
I can find the closest Vertex of the polygon to the point. :)
```
double minDist = Double.MaxValue;
Point pointX = null;
Point lastVertex = null;

foreach (var vertex in polygon.ExteriorRing.Vertices)
{
	if (lastVertex != null)
	{
		var dist2L = Mapsui.Geometries.Utilities.CGAlgorithms.DistancePointLine(thePoint, lastVertex, vertex);
		//var dist2L = Mapsui.Geometries.Utilities.Algorithms.DistanceToLine(thePoint, new List<Point>(new[] { lastVertex, vertex }));
		if (dist2L < minDist)
		{
			minDist = dist2L;
			pointX = Mapsui.Geometries.Utilities.CGAlgorithms.ClosestPoint(thePoint, lastVertex, vertex);
		}
	}

	lastVertex = vertex;
}

if (pointX != null)
{
	//!!!!!!!
}
```

![obraz](https://user-images.githubusercontent.com/15933140/46113682-ab4b8d80-c1ef-11e8-9247-b7e1849502cb.png)

**Comment by lukaszpitulski** [comment]
now I've found (using http://mapsui.github.io/Mapsui/api/Mapsui.Geometries.Utilities.Algorithms.html) this method (.NET 4.7.1):
`Mapsui.Geometries.Utilities.Algorithms.GetDistanceAndSegmentIndex`
and I have:
```
var distSeg = Mapsui.Geometries.Utilities.Algorithms.GetDistanceAndSegmentIndex(thePoint, polygon.ExteriorRing.Vertices);
var segment = polygon.ExteriorRing.GetSegments()[distSeg.Segment];
var pointX = Mapsui.Geometries.Utilities.CGAlgorithms.ClosestPoint(thePoint, segment.StartPoint, segment.EndPoint);
```

It is a pity that I wasted so much time.

**Comment by lukaszpitulski** [comment]
UPDATE
"I can find the closest **Vertex** of the polygon to the point."
The closest **Point** !

GetDistanceAndSegmentIndex + ClosestPoint - works perfectly for me 👍 :)

![obraz](https://user-images.githubusercontent.com/15933140/46114816-96bdc400-c1f4-11e8-8e76-13850fded9f5.png)
