### ISSUE TITLE
Add sample to show pulsing animation on a feature.

### ISSUE THREAD

**Issue by jinkhera** [Mapsui/Mapsui#521]
Hi, would it be possible to add an animation to a layer/feature that could replicate how Google maps does it's pulsating location icon?

**Comment by pauldendulk** [comment]
This is not possible in Mapsui. Perhaps a custom symbol renderer should be introduced to make this possible. A possible workaround would be to draw something like this your self on top of the map. You need to listen to the ViewportChanged event to relocate. It is not easy if you don't know how to do this.

**Comment by jinkhera** [comment]
Thanks for the quick response. I was thinking the same and thought it would have to be a view that sits outside of the mapcontrol. I don't believe it will be difficult to implement but thought I would discuss before implementing.

**Comment by pauldendulk** [comment]
How would that work? Add an array of circles on the symbol that increase in size? If you use a ThemeStyle you could return one of these circles depending on the moment in time. You also need to refresh the map with regular intervals. This is also done in the animation provider.

**Comment by jinkhera** [comment]
I will try to implement this as suggested above.

**Comment by pauldendulk** [comment]
I will close this but am interested to hear if you had any success.
