### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by pingurus** [Mapsui/Mapsui#522]
I accidentally tried to navigate to some very odd coordinates (lat =ca. -8000, lon=ca. -1000)(conversion error) through
` mapControl.Navigator.NavigateTo(SphericalMercator.FromLonLat(lon,lat))`
This caused the program to hang and eventually cause a System.OutOfMemoryException. Maybe the Mapsui code should be reviewed there. (Although I don't think this exception occurs often ;) )

**Comment by pingurus** [comment]
I'm not using navigation limits. The version is 2.0.0-beta8

**Comment by pauldendulk** [comment]
Thanks I will have a look. 

Thinking out loud. Perhaps some kind of navigation limits will be necessary. If you keep zooming infinitely you will get some divide by zero at some point. Perhaps the limits should be hard code at extreme values. Options:
1. Ignore if. If users want to prevent it they should use a limiter.
2. Add a default limiter. If users wants to remove it it is up to them.
3. Make a limiter obligatory. Throw exception when it is set to null
4. Limit hard coded at extreme values.

**Comment by pauldendulk** [comment]
Not really (I did not test it). Without a ViewportLimiter it should still not crash. So we should reproduce the problem and then think about a solution. It could be solved with a forced default ViewportLimiter (don't allow null to be set). Not sure what this default ViewportLimiter should be like. How does this work in GoogleMaps, Mapbox and esri software?

**Comment by pauldendulk** [comment]
I can not reproduce the crash in beta 11 with this sample below:

```
using Mapsui.Geometries;
using Mapsui.Projection;
using Mapsui.UI;
using Mapsui.Utilities;

namespace Mapsui.Samples.Common.Maps
{
    public class ReproduceCrashSampleSample : ISample
    {
        public string Name => "ReproduceCrash";

        public string Category => "Special";

        public void Setup(IMapControl mapControl)
        {
            mapControl.Map = CreateMap();
        }

        public static Map CreateMap()
        {
            var map = new Map();
            map.Layers.Add(OpenStreetMap.CreateTileLayer());
            map.Limiter = new ViewportLimiterWithoutLimits();
            map.Home = n => n.CenterOn(SphericalMercator.FromLonLat(-1000d, -8000d));
            return map;
        }
    }
}
```
