### ISSUE TITLE
Performance on tablets is laggy and slower than on phone.

### ISSUE THREAD

**Issue by jinkhera** [Mapsui/Mapsui#523]
I have tested this on several devices and the performance is not optimal on tablets. Is something that will be addressed with version 2.0? I currently running 1.48. The test I am running is using just the base world map with a few resolutions. It runs smoothly on phones(mostly) and on tablets it seems to lag when panning.

**Comment by pauldendulk** [comment]
Performance improvements are not plannen as part of the 2.0 release. There could be improvements afterwards. Possible improvements:
- User skia hardware acceleration
- Use matrix calculations for positioning.
- Caching of features in their rendered form.

**Comment by pauldendulk** [comment]
Do you see a difference between 2.0 and 1.4 performance?

**Comment by jinkhera** [comment]
The performance is better. I noticed that if there are no zoom limits on the layers then performance degrades when zooming out.

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
