### ISSUE TITLE
Draw marker on every position change

### ISSUE THREAD

**Issue by FrankPohl** [Mapsui/Mapsui#524]
Hello,
I would like to paint a position marker on the map whenever the GPS position changes.
In additon I would like to draw a cricle around the position marker with the current accuracy of the GPS position.
I have found an example to draw a circle but I don't know how to handle layer.
Is it OK to remove the layer and add a new one with the new marker, everytime the position changes ?
Or is there a more efficient way to do that?
Can someone point me to the right direction?
Frank

**Comment by pauldendulk** [comment]
@FrankPohl Can you use charlenni's MyLocationLayer? Removing and adding layers is not a good idea.

**Comment by FrankPohl** [comment]
@pauldendulk Not directly, because he is using Mapsui.UI.Forms. I cannot use that, because my program must run on Windows Mobile, so I'm stuck with version 1.4.8. But I'm almost there, I understand what he is doing and am putting it in my project. But there is one thing I cannot reproduce frm his example. How can I do the refresh/repaint of the Map. The position of the features in the layer is changed but I only see it, wehn I resize the screen or something. Charlenni calls a Refresh method and ends up in an InvalidateSurface . Is there an alternative way to refresh the screen?

**Comment by pauldendulk** [comment]
MapControl.Refresh should work

**Comment by charlenni** [comment]
@FrankPohl Are there any more questions regarding this issue? If no, please close the issue.

**Comment by FrankPohl** [comment]
Thanks for your help. I found everything in the samples. Sorry for not closing earlier.
