### ISSUE TITLE
Map.get_Envelope() throws a NullReferenceException when an empty Linestring is added to a WritableLayer

### ISSUE THREAD

**Issue by pingurus** [Mapsui/Mapsui#525]
When I add an empty Linsestring to a WritableLayer and then click on the map a NullReferenceException is thrown at Mapsui.Map.get_Envelope(), because the envelope of the Linestring is null. I think this needs a fix.

**Comment by pauldendulk** [comment]
Thanks, I will add a unit test for it and fix it.

**Comment by pauldendulk** [comment]
Fixed.
