### ISSUE TITLE
Best way to update dynamic memory layer features?

### ISSUE THREAD

**Issue by mattmiley** [Mapsui/Mapsui#527]
Hello,

I'm updating a dynamic memory provider layer after each zoom/pan. I've just been creating a new layer each time and removing then replacing the layer. Is there a more efficient, elegant way to do this? Can you show me some examples? Am I using the right type of layer?

Thanks,

**Comment by charlenni** [comment]
Perhaps the discussion at the end of #291 helps you.

**Comment by pauldendulk** [comment]
Perhaps look at WritableLayer. Depending on your use case you might want to update the geometries of the features. In that case you need to clear the cache on the feature itself.

**Comment by jinkhera** [comment]
I have implemented a linestring layer that updates as the location changes. It basically draws your track as you move. I can share this code if it helps?

**Comment by mattmiley** [comment]
Yes @jinkhera , please do.  That sounds like a perfect example.

**Comment by mattmiley** [comment]
I can't figure out why my point isnt showing up. Does anything look wrong with this code? 

`
        public static MemoryLayer CreatePointLayer(Wkx.LineString geometry)
        {
            return new MemoryLayer
            {
                Name = "Points",
                Enabled = true,
                Opacity = 1,
                DataSource = new MemoryProvider(GetPointFromEmbeddedResource(geometry)),
                Style = CreateBitmapStyle("PROJECT.Mobile.loc.png"),   
            };
        }

        private static Features GetPointFromEmbeddedResource(Wkx.LineString geometry)
        {
            var feats = new Features();
            var feature = new Feature();
            var point = SphericalMercator.FromLonLat((double)geometry.Points[0].X, (double)geometry.Points[0].Y);
            feature.Geometry = point;            
            feature["name"] = "name";

            feats.Add(feature);

            return feats;
        }

        public static SymbolStyle CreateBitmapStyle(string embeddedResourcePath)
        {
            // For this sample we get the bitmap from an embedded resouce
            // but you could get the data stream from the web or anywhere
            // else.
            //var path = "Mapsui.Samples.Common.Images.home.png"; // Designed by Freepik http://www.freepik.com
            var bitmapId = GetBitmapIdForEmbeddedResource(embeddedResourcePath);
            var bitmapHeight = 70;// To set the offset correct we need to know the bitmap height
            return new SymbolStyle { BitmapId = bitmapId, SymbolScale = 5, SymbolOffset = new Offset(0, bitmapHeight * 0.5) };
        }

        public static int GetBitmapIdForEmbeddedResource(string imagePath)
        {
            var embeddedImage = new Xamarin.Forms.Image { Source = Xamarin.Forms.ImageSource.FromResource(imagePath, typeof(Helpers).GetTypeInfo().Assembly) };

            var bitmapId = BitmapRegistry.Instance.Register(embeddedImage);

            // NOTE: use for debugging, not in released app code!
            var assembly = typeof(Helpers).GetTypeInfo().Assembly;
            foreach (var res in assembly.GetManifestResourceNames())
            {
                System.Diagnostics.Debug.WriteLine("found resource: " + res);
            }


            return bitmapId;
        }`

**Comment by pauldendulk** [comment]
You create a Xamarin Forms image. 

```var embeddedImage = new Xamarin.Forms.Image { Source = Xamarin.Forms.ImageSource.FromResource(imagePath, typeof(Helpers).GetTypeInfo().Assembly) };```

The register method takes the raw image bytes. Perhaps you can request the raw bytes from the Xamarin Forms image.

**Comment by pauldendulk** [comment]
An other option is not to load it as XF image in the first place, but load the raw resource in some other way.

**Comment by charlenni** [comment]
@mattmiley @pauldendulk second suggestion is the right. ````BitmapRegistry.Register()```` accepts a stream, containing the bytes of a SVG, PNG or JPG file, not a Xamarin ImageSource.

So the correct version of this would be
````
var stream = typeof(Helpers).GetTypeInfo().Assembly.GetManifestResourceStream(imagePath);
var bitmapId = BitmapRegistry.Instance.Register(stream);
````

**Comment by gpsaliola** [comment]
I'm try to read an image into MemeoryStream to be consumed into BitmapRegistry.Instance.Register.
The images are stored into Resources/drawable in Android and into Resources in iOS.
I'm trying to use (as suggested by charlenni):
`var stream = typeof(Helpers).GetTypeInfo().Assembly.GetManifestResourceStream(imagePath);`
but Helpers isn't defined.
Can anyone help me? Thank you.
