### ISSUE TITLE
How to get event Viewport.ViewportChanged?

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#531]
It seems I'm new to Mapsui ;)

You moved the Viewport to MapControl. But there is only a read only version of Viewport. With this, you couldn't attach to ViewportChanged. Or I'm wrong? How could I get events, when the Viewport changes?

**Comment by pauldendulk** [comment]
Thanks for mentioning this. Something when wrong with the refactoring around IViewport and IReadOnlyViewport. The IReadOnlyViewport should get a ViewportChanged event to fix this.

**Comment by pauldendulk** [comment]
Also noticed here: https://github.com/Mapsui/Mapsui/issues/459#issuecomment-429369833

**Comment by pauldendulk** [comment]
Pushed a fix. This will be in 2.0.0-beta.10.

**Comment by charlenni** [comment]
Thank you!
