### ISSUE TITLE
NullReferenceException executing Mapsui.UI.iOS.MapControl constructor

### ISSUE THREAD

**Issue by aquisio** [Mapsui/Mapsui#535]
I am attempting to use Mapsui v2.0.0-build.636 in a .NET Standard Xamarin.Forms app, using iOS and Android custom renderers.

This implementation works well on Android, but throws NullReferenceException on iOS, while attempting to create a new instance of Mapsui.UI.iOS.MapControl (using the constructor overload that accepts a CGRect).

I have debugged this issue and found that it occurs in LimitedViewport.SetSize, specifically because the first time it is called its Limiter property is null.

The following chain of calls result in this NRE:

```
MapControl constructor
  UIView base class constructor
    MapControl.Frame property setter override
      MapControl.SetViewportSize
        LimitedViewport.SetSize
```
				
After this initial constructor call sequence, the LimitedViewport.Limiter property becomes populated (when the MapControl.Map property is set) and the NRE does not recur.

I have been able to work around the issue by subclassing Mapsui.UI.iOS.MapControl and overriding the Frame property setter, but it might be helpful if the Mapsui codebase includes this protection.

**Comment by pauldendulk** [comment]
Thanks for you clear analysis.

**Comment by pauldendulk** [comment]
Fixed in latest commit.
