### ISSUE TITLE
Collision detection of the features (during and especially after drawing them)

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#536]
Hi guys!

Referring to the issue  #383  I would like to ask about the following issue.

I'm working on some solution where I think about using Collision Detection, but I'm not sure if think correctly about it, or even about exactly what's in Mapsui (#383).

What I'm trying to do is: 
on the same layer 
there are the features like Points with SymbolStyle(SymbolType.Bitmap)
and there are the features like Polygons with VectorStyle.
(both may also have LabelStyle but not necessary)

And now, when the polygon is drawn and on the map in the area of the polygon is any point, how to find out about it, by any event or in some Polygon feature properties?
Also I would like to know if any point is in any polygon (just after drawing, moving, removing of any polygon).

I know that there are Mapsui.Geometries.Utilities.Algorithms.PointInPolygon method and Mapsui.Geometries.Polygon.Contains method 
But is there any other way?

I would not like any iteration of all objects on the map and checking if something contains something or is contained in something, etc. Each time when I do anything with any polygon or point.

Thanks!
Łukasz

**Comment by charlenni** [comment]
I would be interested in such a thing too.

Background is the vector map. It isn't a problem to draw streets and other areas on the map. But it is difficult to draw the names for towns and places. For this, you should create a list ordered by the importance of the place and than draw one by one and check, if there is place for this. Ideally it would be a special layer type, which gets a list of symbols, which are than drawn. This list could be updated when zoomed in or out or the position changes.

**Comment by charlenni** [comment]
Thinking further on this, there should be a special layer for this. This layer has a list of features, which could be drawn, but must not. Drawing is abortable any time. The renderer should get a function to calculate the size on screen for this feature. With this, it could be determined (by a RTree), if there is enough space to draw the next feature. If drawing isn't aborted (because a new list is generated), than the complete list is processed.

Has someone out there such a thing? Or has someone an idea, how to make this?

**Comment by lukaszpitulski** [comment]
😮 
Lower zoom = less objects and labels on the map(layer).
This is how OSM and GMap work (names and symbols of cities, roads, things)...

Sorry, but I'm not sure what you're talking about.
How is this related to my question?

Not enough space in the envelope/view to show all object with their labels, etc. 
and managing them in fly, it's another issue.

**Comment by charlenni** [comment]
For the vector map, all parts are Features. Roads, areas and symbols are all Features. Nothing else. Some Features should be drawn like roads and areas. Some Features should be drawn only, if there is enough space for them.

So it is the same as your problem. In both cases, there are to much Features to show. So you have to decide, which Features should be displayed and in which order. There could be a mechanism, which could reduce the space a Feature uses (remove text from a symbol), but this is an extra.

So if this is different from your problem, than I didn't understand your problem correct.

**Comment by lukaszpitulski** [comment]
This is not case of the issue:
> there are to much Features to show. So you have to decide, which Features should be displayed and in which order. There could be a mechanism, which could reduce the space a Feature uses (remove text from a symbol), but this is an extra.

#539

I don't want to reduce any features, features styles, symbols, labels etc. on any layer.
All must to stay as are and where they are.


Maybe example will give you better image of the issue:

- Exists only one WritableLayer.
- In the layer are 2 features, both are points (icons with label).
Now I would like to draw on the same layer a polygon (Vector) an after finishing drawing I would like to have the polygon under the points automatically. #539
And if I add a new point the point will be above the polygon, and if will be next polygon the polygon will be under the all points, etc. etc.

And now, when I finish drawing, moving, editing polygons I would like to know (directly) if the polygons contains any other features (especially points) if they have collision with any others.

I can use Mapsui.Geometries.Utilities.Algorithms.PointInPolygon method.

only Points:
![obraz](https://user-images.githubusercontent.com/15933140/48629764-d31ecc80-e9ba-11e8-8e8b-8213fde6f8b1.png)

current situation, the Points and the Polygon:
![obraz](https://user-images.githubusercontent.com/15933140/48629933-31e44600-e9bb-11e8-8bc7-95a8f2d4d02d.png)

expectation:
![obraz](https://user-images.githubusercontent.com/15933140/48629955-432d5280-e9bb-11e8-9a82-4819b0c5e4ef.png)

**Comment by charlenni** [comment]
What's the reason, that their could only one layer for all Features? How should Mapsui know, which things you want on top and which on bottom? If allways all points should be on top, than use different layers and put the point layer above the polygon layer. If you want a z-index for this, than see #539.

For the collision detection: iterate over all polygons and than check, if any of the points is inside of the current polygon. Nothing else Mapsui would made. To do this automatically each time you add an point or polygon would be to time consuming. That's a thing, that you should only make, if you want to know it.

**Comment by lukaszpitulski** [comment]
>  How should Mapsui know, which things you want on top and which on bottom

Exactly!  This is why I deeply regret that there is no z-index in the features #539 

> iterate over all polygons and than check, if any of the points is inside of the current polygon

Please have a look at my first post in the issue, I mentioned about it and expected troubles with performance.

> Nothing else Mapsui would made

Thanks.
