### ISSUE TITLE
Feature on top

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#539]
Hi,

How can I move any feature(s) to top above others (on the same layer)?

I have polygon and point. Sometimes the point is under the polygon sometimes is above.
I would like to have the point feature always on top.

Regards,
Łukasz

**Comment by charlenni** [comment]
Normally features a drawn in order, if you create them. If you want to change this, you should change the order of the Features.

**Comment by lukaszpitulski** [comment]
This will be difficult because the features are added dynamically into the layer in real time. 
It's only possible to move (remove) all to some temp layer (in mem, not visual), order them and add them back into the layer, in a loop/timer or after each time when any new feature is added to the layer.
I'm worried about performance.

**Comment by lukaszpitulski** [comment]
Another solution is to create one more layer for the polygons only and add it to the map before the points layer (under it). Then dividing the features between the two layers.
This creates more to do with methods that work with the features (adding, changing styles, editing features, etc.)
Also polygons and points are in the relations and depend on each other, so two layers can be more problems. Or not, what do you think?

**Comment by charlenni** [comment]
Perhaps you could create your own ````IProvider````. You don't have to do so much and you could create a list of features in any order you want in the
````
public virtual IEnumerable<IFeature> GetFeaturesInView(BoundingBox box, double resolution)
````
Than you add this ````IProvider```` as the ````DataSource```` of your ````Layer````.

**Comment by lukaszpitulski** [comment]
I don't use DataSource at all.
I have here WritableLayer(: BaseLayer) only and own mechanism to add, remove, edit features in them.

I deeply regret that there is no z-index (or something that could tell a layer which features are above or below others).

**Comment by lukaszpitulski** [comment]
Of course, I know that 
> add the Features in the right order to your WritableLayer and you get them drawn in this order.
 the same is with order of adding layers etc.

Problem is, the features are added in many threads, sometimes in the same time, and almost always in different order.
I don't have any control over that (mostly).

I can only reorder (redraw/readd) all features in the layer each time when a new feature is added or edited.
With about hundred features it could be a little hard for performance.

And this has to applies to all features in the layer not only in the current view regardless of resolution/zoom.

**Comment by charlenni** [comment]
Than create your own WriteableLayer. Copy the whole code and use a concurrent sorted list instead of the ConcurrentHashSet<IFeature> and change
````
public void Add(IFeature feature)
````
so that you add the new Feature in the correct way. That should do the trick.

This has only to apply to the visible Features, because only they are visible/drawn. You could also change the 
````
public override IEnumerable<IFeature> GetFeaturesInView(BoundingBox box, double resolution)
````
Get the list of visible Features, sort it and return it, so that it could be drawn. Place the sorting between the following lines
````
var result = cache.Where(f => biggerBox.Intersects(f.Geometry?.BoundingBox));
return result;
````

**Comment by lukaszpitulski** [comment]
The adding order of the feature in the layer doens't work correctly (Mapsui 1.4.8), I think.

The scenario:
1. 2 points (features) added
2. 1 polygon added (drawn on the points) = points are above the polygon feature ?! (order?)
3. + point, is above polygon
4. + point, is above polygon
5. + second polygon and all points are above it ?! (order?)
6. + point and is above all polygons
7. + point and is above all polygons
6. + third polygon and the points are under it (order ok, but why now?!)
... etc.
Looks like order is not keep and position "z-index" of the features on the same layer is randomly?
Is it something with that the points are Symbols and the polygons are Vectors?

The same scenario, repeated, each time gives different result on the map(layer).

![obraz](https://user-images.githubusercontent.com/15933140/48631232-660d3600-e9be-11e8-993a-393b5a9713c8.png)

**Comment by charlenni** [comment]
Than I would say, that ConcurrentHashSet returns the Features not in the right order. You could test this by your own. Create your own ConcurrentHashSet, add some data and try, if the result is ordered. If not, change WritableLayer and make a PR or create a new own Layer. First is preferred 😉.

**Comment by charlenni** [comment]
Btw. a z-index isn‘t very performant. If Mapsui sorts all features each time, it draws the features, than this is much more time consuming than you sort the order while adding a new feature. And if you do this, than you don‘t need a z-index.

**Comment by lukaszpitulski** [comment]
Good point!
Especially when I need that only for two types of features in a specific solution.
If Mapsui (WritableLayer) would start doing this every time for all&any features... yes, that would affect performance.

Now I get what you mean in the post https://github.com/Mapsui/Mapsui/issues/539#issuecomment-439418227

I'm now experimenting with ConcurrentDictionary<IFeature, int> instead of ConcurrentHashSet<IFeature>
<feature, zIndex>

Thanks!

**Comment by lukaszpitulski** [comment]
I'm done, failed and 'm terrified about what's happening with ConcurrentDictionary and order of item in it.
I'd no idea it's so terrible.
(new C# experience :/ and disappointment)

I think that if I don't want to create a little monster in the code with ordering(z-index) features in layers I'll have to use the next layer for it.
Pity, because I wanted to avoid creating a separate layer for each kind of feature's type etc.

**Comment by grudolf** [comment]
Dictionary and HashSet don't preserve the insertion order by definition, you should be using a different structure instead. OrderedDictionary?
