### ISSUE TITLE
Adding a point to an openstreetmap map

### ISSUE THREAD

**Issue by jessedegans** [Mapsui/Mapsui#540]
So i just made a UWP project. Now, I am trying to create a map which works fine(great work pauldenbulk!). 
But when I try to add a point the screen goes white. That is because almost all the values of the Viewport inside MyMapControl.Map are Nan. Does anyone know how to initialize the viewport or fix this issue?

`  this.InitializeComponent();
            
            MyMapControl.Map.Layers.Add(OpenStreetMap.CreateTileLayer());
            
            MyMapControl.Refresh();

            var t = CreatePointLayer();
            var point = Mapsui.Projection.SphericalMercator.FromLonLat(52.8867981, 5.9925056);
            var screenpoint = MyMapControl.Map.Viewport.WorldToScreen(point);
            t.Add(new Feature { Geometry = screenpoint });

            MyMapControl.Map.Layers.Add(t);
            MyMapControl.Refresh();`

and the xaml is 

` <Grid>
        <uwp:MapControl Name="MyMapControl"></uwp:MapControl>
    </Grid>`

**Comment by jessedegans** [comment]
I tried  `t.Add(new Feature { Geometry = point });`
but that gives me a location near africa. While the long/lat should be somewhere in Friesland, Netherlands

**Comment by charlenni** [comment]
Be careful: the function is ˋˋˋˋFromLonLat()ˋˋˋˋ and not ˋˋˋˋFromLatLon()ˋˋˋˋ. You should change your values.

**Comment by jessedegans** [comment]
Omg i am so stupid.. Thanks 👍

**Comment by charlenni** [comment]
You are welcome.

Could you close the issue?
