### ISSUE TITLE
Xamarin.Forms rework

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#542]
We just accepted a big pull request adding Xamarin.Forms support. Here we discuss possible rework.

- The OpenStreetMap sample shows no background map on Android
- MbTiles fails with a method not found exception.
- Mouse wheel zoom does not work on UWP. How should this work in forms, where there is no mouse on the other platforms?
- @charlenni mentioned there was more work to be done. @charlenni what kind of things are those?

**Comment by charlenni** [comment]
> The OpenStreetMap sample shows no background map on Android

It seems, that Android get no raster images from OpenStreetMap. On UWP it works perfect.

> MbTiles fails with a method not found exception.

The inner exception is "Method not found: void SQLite.SQLiteConnectionString..ctor(string,bool)". It seems, that there changes something between my SQLite-net version and yours. I try to investigate this. Perhaps something like [this](https://github.com/oysteinkrog/SQLite.Net-PCL/issues/14).

> Mouse wheel zoom does not work on UWP. How should this work in forms, where there is no mouse on the other platforms?

This is a function missing in Skia up to now. If Skia provides the wheel events in Skia.View, than it is possible to use them. See for this see [#449](https://github.com/mono/SkiaSharp/issues/449).

**Comment by pauldendulk** [comment]
About the missing mouse wheel event. Could there a workaround where you embed the skia view in some parent that catches the mouse wheel events?

**Comment by pauldendulk** [comment]
About the sqlite exception. Not sure how that works. The same sqlite libraries are used in the forms sample as in the native sample. I don't expect a difference there. Could it be forms ships with it's own sqlite library? Not something I would expect. Perhaps the exception message is just wrong or misleading.

**Comment by pauldendulk** [comment]
By the way. There is a new pre-release of skiasharp that we could start using in our beta. Don't expect to fix the mousewheel issue, but if it gets fixed it is possible in the pre-release.

**Comment by charlenni** [comment]
I debuged now the code for getting tiles (I assume same for MbTiles and OpenStreetMap). I do it in iOS (because of the Android problem). If I use the native iOS sample app, I get to TileFetchDispatcher.UpdateMissingTiles(), line 147 and map is displayed correct. If I do the same with XF, then I don't get there. One time, when debuging from the begining, I got there and than same the map. It seems to be a problem with the fetching of the tiles. Any runtime condition. But I don't see, where this could be happen.

**Comment by pauldendulk** [comment]
On Android you need to set the permission to access the internet.

**Comment by charlenni** [comment]
Found the problem, but could not solve it up to now.

The problem is an exception, when converting the BoundingBox to a Extent. Because the BoundingBox is only a point, the conversion throws an exception (see [here](https://github.com/BruTile/BruTile/blob/master/BruTile/Extent.cs#L50). I didn't see this exception.

So now the question is, where RefreshData() gets this BoundingBox from.

**Comment by charlenni** [comment]
> MbTiles fails with a method not found exception.

If I downgrade sqlite-net-pcl from 1.5.231 to 1.4.118, than MbTiles work again on Android.

**Comment by charlenni** [comment]
Removed some bugs, but there still some ;)

Found, that you get on iOS only a black screen instead of the map. Don't know, why :(

**Comment by pauldendulk** [comment]
> If I downgrade sqlite-net-pcl from 1.5.231 to 1.4.118, than MbTiles work again on Android.

ah okay, we will just work with that. No idea why this would matter if the 1.5 version works fine on Android native.

**Comment by charlenni** [comment]
> Found, that you get on iOS only a black screen instead of the map. Don't know, why :(

Problem was an update of screen not using main UI thread.

**Comment by mattleibow** [comment]
@charlenni If you get some code that works with mouse events, you could also submit a PR to SkiaSharp. I am the only guy on the SkiaSharp team, and I can't always get to everything. I am busy looking into making the build process a bit easier for most people. I hope to not require a full rebuild of the entire system just to tweak some code in the forms views.

**Comment by plamen-i** [comment]
[[BREAKING CHANGE] SQLiteConnectionString ctor](https://github.com/praeclarum/sqlite-net/issues/784)

**Comment by charlenni** [comment]
@plamen-i Thank you for the help. That is the reason for the problems.

**Comment by pauldendulk** [comment]
Closing because we handled a number of obvious issues. There may be others but they will need to be added as separate issues (like the mouse wheel issue on uwp).

**Comment by charlenni** [comment]
Ah, closing day ;)

Skia now has wheel support. I should test it and add it to the demo. Try to do this.

**Comment by pauldendulk** [comment]
oh, I assume this wheel support is in the new version? We are still using 1.60. Latest is 1.68.

**Comment by charlenni** [comment]
I assume, that it is in the next version. The same as [SKDrawable](https://github.com/mono/SkiaSharp/pull/739).

**Comment by mattleibow** [comment]
@charlenni, I am busy with a few merges and SKDrawable will soon be in. I have merged your PR into the development branch, and all looks good so far. I added a few basic tests, but do you have any specific cases that you would like to check for? If you do, just open a new PR with them against the development branch so I can make sure we test everything.

**Comment by charlenni** [comment]
@mattleibow Thank you for creating the tests. They look good and I think it is enough. If I think, that there should one more, than I made a PR.
