### ISSUE TITLE
Check if feature is clicked

### ISSUE THREAD

**Issue by jessedegans** [Mapsui/Mapsui#543]
I cannot get an feature click event to work. I tried adding a button on top. Later i saw a post about MapInfo. Which is nice it gives me the position of where the user clicked but can I request the feature on that? I tried checking the label of the feature but this returns empty. Only the world position is being sent:

```
  private void MapOnInfo(object sender, MapInfoEventArgs args)
        {
           
            var layername = args.MapInfo.Layer?.Style.ToString();
            var featureLabel = args.MapInfo.Feature?["Label"]?.ToString();
            var featureType = args.MapInfo.Feature?["Type"]?.ToString();

            Debug.WriteLine("Info Event was invoked.");
            Debug.WriteLine("Layername: " + layername);
            Debug.WriteLine("Feature Label: " + featureLabel);
            Debug.WriteLine("World Postion: {0:F4} , {1:F4}", args.MapInfo.WorldPosition?.X, args.MapInfo.WorldPosition?.Y);
            Debug.WriteLine("Screen Postion: {0:F4} , {1:F4}", args.MapInfo.ScreenPosition?.X, args.MapInfo.ScreenPosition?.Y);

        }
```

How can one get the specific feature being clicked? Or like the label of the feature?

**Comment by jessedegans** [comment]
Sorry my question was not right. What i actually try to do is give some ID to the feature. So i have a point layer and each point need to have an id. Onclick I want to get a record from my database with this ID. So i was like okay i will save this ID into the label and then read the label on click but the label seems to be empty... How can i archieve this?

**Comment by charlenni** [comment]
For the Layer name use Layer.Nam instead of Layer.Style.

Than could you show, how you created the Feature? Perhaps a typo ("label" instead of "Label")?

**Comment by charlenni** [comment]
Did you marked the Layer as IsInfoLayer?

**Comment by jessedegans** [comment]
How can i mark a layer as an infolayer?

**Comment by charlenni** [comment]
See [ILayer](https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Layers/ILayer.cs#L130)

**Comment by charlenni** [comment]
To be a little be more verbose: If you don't set this flag, than the Features of this Layer aren't checked while GetMapInfo. I assume, that your ````args.MapInfo.Feature```` is null. Perhaps you should check, if you get a Feature. Should possible while debuging.

**Comment by jessedegans** [comment]
Well the problem is that i use a WriteableLayer which inherits from BaseLayer (which should following the docs implement ILayer and IsMapInfoLayer) But there is no such thing. Should i try creating my own layer? Copying the BaseLayer and WriteableLayer and do implement the bool?

**Comment by jessedegans** [comment]
I tried creating my own Layer and Implementing ILayer and the IsInfoMapLayer. but that didnt work either Feature is still null. Does anyone have a click example?

**Comment by ChristiaanG** [comment]
Hi I am working together with @jessedegans. We are making an UWP app and with Mapsui 1.4.8. In this version ILayer does not have the field IsInfoMapLayer. And MapControl does not have the method GetMapInfo. Is there a different way to make a layer clickable?

**Comment by charlenni** [comment]
Ah, thats are very useful informations ;)

If you use 1.4.8, you should use Map.InfoLayers and add your layer, which contains the Feature to this list. You could find an example [here](https://github.com/Mapsui/Mapsui/blob/1.4/Samples/Mapsui.Samples.Common/Maps/InfoLayersSample.cs). For getting and handling the created MapInfo event see [here](https://github.com/Mapsui/Mapsui/blob/1.4/Samples/Mapsui.Samples.Uwp/MainPage.xaml.cs#L109) and [here](https://github.com/Mapsui/Mapsui/blob/1.4/Samples/Mapsui.Samples.Uwp/MainPage.xaml.cs#L37).

**Comment by ChristiaanG** [comment]
@charlenni thanks for the quick response. I will try it out.

**Comment by pauldendulk** [comment]
How is this going? I find the discussion very confusing. There is a MapInfo sample. You can click the map and get a MapControlOnInfo. In the UI the property is shown.

Can you create this yourself? If yes, then what else is your problem? If no, where do you get stuck?

![image](https://user-images.githubusercontent.com/963462/49214853-cab98f00-f3c7-11e8-89a4-8cb549d226c7.png)

**Comment by pauldendulk** [comment]
btw, the screenshot is from master, but in the 1.4 branch there is a similar sample.

**Comment by ChristiaanG** [comment]
Hi @pauldendulk. The problem has been solved with the last resoinse from @charlenni. Thanks for the help.
