### ISSUE TITLE
When Widget is clicked, result is null

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#545]
When you click on a Widget, the click is handled, but than there is returned null instead of a MapInfoEventArgs with Handled = true (see [here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.UI.Shared/MapControl.cs#L362)). 

For this, the widget callback should return a value, if the Widget handled this event or not. This said, the Widget callback should be ````Func<IWidget, Point, bool>```` instead of ````Action<IWidget, Point>````

**Comment by pauldendulk** [comment]
Okay, let's do it like that.

**Comment by charlenni** [comment]
Should I make this and the create a PR?

**Comment by charlenni** [comment]
See PR #547
