### ISSUE TITLE
Map not rendered in Xamarin.Forms iOS when HttpClient Implementation is set to NSUrlSession

### ISSUE THREAD

**Issue by gnout** [Mapsui/Mapsui#552]
In Xamarin.Forms 3.4.0
In Samples/Mapsui.Sample.Forms.iOS the map is not rendered when the HttpClient Implementation is set to NSUrlSession (iOS 7+) (in Properties > iOS Build)
The same app works fine when the HttpClient Implementation is set to "Managed"

**Comment by charlenni** [comment]
Did you have the same problems when using the Samples/Mapsui.Sample.iOS sample? I assume, that this isn't a Forms problem, but a problem using BruTile.

**Comment by gnout** [comment]
I didn't try the Samples/Mapsui.Sample.iOS sample but my guess is, as you said, this is not a Forms problem but a BruTile problem!
But how can I fix it?

**Comment by charlenni** [comment]
I try to find a solution. Takes some time.

**Comment by gnout** [comment]
Yes, certainly, I'm doing now. (version 1.4.8)

**Comment by charlenni** [comment]
Äh, you use the Sample/Mapsui.Sample.Forms.iOS with 1.4.8?

**Comment by gnout** [comment]
Download the entire repository (master) and run the Sample/Mapsui.Sample.Forms.iOS

**Comment by charlenni** [comment]
Ok, than you use 2.0 beta. That's ok.

**Comment by gnout** [comment]
The map is not rendered with NSUrlSession. It works perfectly fine with Managed. Both with 1.4.8 in an iOS simulator.

**Comment by gnout** [comment]
Same behavior with a device (1.4.8) I'm trying the repository of Mapsui-2.0

**Comment by gnout** [comment]
In the repository of Mapsui-2.0 the xamarin forms sample does not exists!

**Comment by gnout** [comment]
BTW I tried [this](https://github.com/bertt/Mapsui.Forms) example with version 2.0 of mapsui and crashed.
It's working with 1.4.8 and Managed HttpClient implementation.
It's not working with 1.4.8 and NSUrlSession HttpClient implementation but it's just don't render the map. It doesn't crash.

**Comment by gnout** [comment]
I just tried the `Mapsui.Samples.iOS` of version 2.0 and still the map is not rendered when the HttpClient implementation is set to NSUrlSession

**Comment by charlenni** [comment]
Ok, the naming of the branches is a little bit confusing. The branch master contains the version 2.0 of Mapsui, which is the active branch. The branch 1.4 contains the version 1.4.8. The Xamarin.Forms native MapControl works only with the version 2.0 and is included in the master branch.

I tried the same as above with Mapsui.Sample.iOS. Now I can see the problem and get it on Mapsui.Samples.Forms.iOS too. Try to find the problem.

**Comment by gnout** [comment]
I just tried it and it is working. Thanks a lot for your help.

**Comment by pauldendulk** [comment]
@gnout Thanks for the clear report.
@charlenni Thanks for diagnosing and fixing this. You are awesome!
