### ISSUE TITLE
Rotation (WPF touch) is causing flickering on the map

### ISSUE THREAD

**Issue by leo-costa** [Mapsui/Mapsui#554]
Hello !

I'm currently using 2.0.0-beta-10 and when trying out Mapsui.Samples.Wpf, I saw that when using touch to rotate on any of the sample demo maps, the viewport will start to flicker. 

After the map is slightly rotated, any panning would  cause flickering too. If Map.RotationLock is set to true, then it wouldn't go here and no flickering wouldn't happen. 

```
if (!Map.RotationLock)
{
    _innerRotation += angle - prevAngle;
    _innerRotation %= 360;

    if (_innerRotation > 180)
        _innerRotation -= 360;
    else if (_innerRotation < -180)
        _innerRotation += 360;

    if (Viewport.Rotation == 0 && Math.Abs(_innerRotation) >= Math.Abs(UnSnapRotationDegrees))
        rotationDelta = _innerRotation;
    else if (Viewport.Rotation != 0)
    {
        if (Math.Abs(_innerRotation) <= Math.Abs(ReSnapRotationDegrees))
            rotationDelta = -Viewport.Rotation;
        else
            rotationDelta = _innerRotation - Viewport.Rotation;
    }
}

```

**Comment by charlenni** [comment]
Which renderer do you use? Skia or Xaml?

**Comment by leo-costa** [comment]
> Which renderer do you use? Skia or Xaml?

I'm currently using Skia. I'm almost positive the same problems happens under WPF renderer. I will test it again soon as I don't have a touch device on me now. 

The device in question is a Surface Go. I might try it on other Surface Pro devices.

**Comment by pauldendulk** [comment]
And you don't have this problem if you use mouse drag on a rotated map?

I must say that wpf touch has barely been tested, since I don't use a device with touch input.

**Comment by leo-costa** [comment]
> And you don't have this problem if you use mouse drag on a rotated map?
> 
> I must say that wpf touch has barely been tested, since I don't use a device with touch input.

No I don't see this problem on a rotated map and using the mouse to drag.

**Comment by pauldendulk** [comment]
@leo-costa I don't see an obvious way to emulator touch. Now I am trying to understand the problem without emulator. 

Could you describe the flicker? Is it going from map to white to map, or from rotated to upright to rotated?

**Comment by pauldendulk** [comment]
I investigated rotation in the uwp mapcontrol. It uses the same method for mouse drag and finger drag. What I found missing is that the _innerRotation is not initialized. WPF has the same problem. So, I committed a bug fix for this. There is s 7% change that this affects your problem too. 

I have no other ideas what could cause your problem. I don't see how I can test touch on wpf soon.

**Comment by pauldendulk** [comment]
I published 2.0.0-beta.11, you could test it.

**Comment by leo-costa** [comment]
@pauldendulk  I recorded the flickering with version 2.0.0-beta.11. This happens on both Wpf and Skia renderer. It was recorded with the built in windows 10 capturing, then converted to gif at 10FPS, so the flickering is much faster than this.

![mapsui-problem](https://user-images.githubusercontent.com/32940986/50027685-17ea5300-ffbb-11e8-9e3f-7c9d4f977a9d.gif)

**Comment by pauldendulk** [comment]
It is general problem. It is also on Android.

**Comment by pauldendulk** [comment]
This should be fixed with this commit https://github.com/Mapsui/Mapsui/commit/cfbcafa596266b3abb60c04263d969af2b449658

**Comment by leo-costa** [comment]
@pauldendulk I don't have a touch device with me over the weekend. Monday morning I will just confirm with you. Thank you so much for the fix 👍

**Comment by leo-costa** [comment]
@pauldendulk It seems the fix is working 👍 
One minor "problem" is the performance when rotating. It seems somewhat sluggish, but it is better to rotate then to flicker :)

Thank you once again for the quick fix.
