### ISSUE TITLE
Can Mapsui you show measure while drawing lines or shapes?

### ISSUE THREAD

**Issue by echambi** [Mapsui/Mapsui#557]
I need to see the measure or distance in meters from one point to another while drawing lines or shapes in the viewfinder. Please an example of how to do it.
thank you

**Comment by pauldendulk** [comment]
There is no out of the box way to show it. Calculating distance is also done in the scalebar widget. Based on that it should be possible to create something like this yourself. There were some previous issues here asking the same thing. Perhaps you could search the issues to get some hints.
