### ISSUE TITLE
Mapsui can show the map or image of the plane, disconnected from the network

### ISSUE THREAD

**Issue by echambi** [Mapsui/Mapsui#558]
when my phone is disconnected to the wifi or internet the background map, it is no longer displayed and everything is with a white background.

there is a way to save the background image on the mobile and mapsui can visualize it in offline mode?

I appreciate your kind support.

Thanks

**Comment by pauldendulk** [comment]
You could look at mbtiles for this. It is also possible to store files on the fly into a sqlite database. There should be some samples for that in [brutile](https://github.com/BruTile/BruTile).
