### ISSUE TITLE
Xamarin.Forms on Windows Mobile

### ISSUE THREAD

**Issue by FrankPohl** [Mapsui/Mapsui#562]
I'm trying to run the Xamarin.Forms components (MapView or MapControl from Mapsui.UI.Forms) on a device with Windows Mobile or Windows IOT Enterprise. The current Windows version on the devices is 1709, so you can only use the target .NET Standard 1.4 for the components.

The current Xamarin.Forms implementation from the master branch is running fine on these devices, but with one major problem. The control does not receive any touch events. On Android and on the desktop all touch events are triggered.

I have no idea why it doesn't work. Even a GestureRecognizer for the components is not triggered.

**Comment by charlenni** [comment]
Mapsui.UI.Forms uses the SkiaSharp Forms view as basis. As you can see [here](https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs#L20), SkiaSharp uses the events of FrameworkElement to catch gestures. Perhaps you could see something strange there?

**Comment by FrankPohl** [comment]
Hi Charlenni, thanks for the quick answer, but I am not able to compile the SkiaSharp samples on my machine, so I cannot double check this. The source code itself seems to be fine, so it might be something using this source code. Maybe there is no Framework Element set?
That came into my mind when I saw in the control in Mapsui.UI.Uwp, where a comment mentioned, that setting a background is necessary to get touch events.
Will be off for holiday after Christmas, so do not expect a quick answer on this.

**Comment by pauldendulk** [comment]
Perhaps the MapControl should not be directly derived from the SKGLView but from a regular forms control (like the ContentView perhaps). Touch events should be handled by that forms control. Skia could then be used for rendering only.

**Comment by pauldendulk** [comment]
oh, now I understand the question better. It seems in general touch works correct but just not on this device where only .NET Standard 1.4 is allowed. All kinds of errors could occur when working with our .NET Standard 2.0 assemblies. So I guess the answer is, this is not supported. Skia itself is on .NET Standard 1.6, so there could be an issue as well.
