### ISSUE TITLE
Loading mbtiles

### ISSUE THREAD

**Issue by OracleJavaX2** [Mapsui/Mapsui#563]
What happened to Mapsui in Windows Forms? I can't find WinForms sample anymore and can't use it in Windows Forms... Is WinForms unsupported?

**Comment by charlenni** [comment]
See https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/MbTilesSample.cs

**Comment by OracleJavaX2** [comment]
Thanks for the link charlenni, but I can't add that to WinForms. How do I use map in a WinForms?

**Comment by charlenni** [comment]
There isn‘t a WinForms Mapsui implementation. And I assume, that you could use the WPF implementation.

**Comment by OracleJavaX2** [comment]
Ok. I tried to add WPF implementation, added an ElementHost and tried to add Mapsui to it, but that didn't work either. Any sample/reference on how to do use WPF component of mapsui in WinForms?

**Comment by charlenni** [comment]
@OracleJavaX2 You open and close many issues in the moment. It is not clear, if you solved the closed issues. If you solved it, than it would be helpful for others, if you could post the solution. Thanks.
