### ISSUE TITLE
How to get coordinates of clicked point/location?

### ISSUE THREAD

**Issue by OracleJavaX2** [Mapsui/Mapsui#564]
In Mapsui control (WPF) MouseUp event (or similar mouse click handling event), I want to be able to get exact (as accurate as possible) long/lat of the clicked point. 

            

`Mapsui.Geometries.Point lonLat = Mapsui.Projection.SphericalMercator.ToLonLat(this.MyMapControl.Viewport.Center.X, this.MyMapControl.Viewport.Center.Y);`

I have this and it works for center of current view, but how about clicked point?

**Comment by pauldendulk** [comment]
Look at the map info sample.

**Comment by OracleJavaX2** [comment]
Thank you Paul!
