### ISSUE TITLE
Detect click on Marker in WPF Component

### ISSUE THREAD

**Issue by OracleJavaX2** [Mapsui/Mapsui#566]
I have added numerous markers using MemoryLayer/MemoryProvider and Features.

Now, how can I detect a click on one of my markers? I need to get the name of the clicked marker. 

I see some PinClickedEventArgs in some samples, but I can't find them in WPF component.

I have 
` var screenPosition = e.GetPosition(this.map);`
`MapInfo mapdata = MyMapControl.GetMapInfo(screenPosition);`

But I always get Null in mapdata's Feature and Layers fields.

Please advise. Thank you

**Comment by kreativgeist** [comment]
Same problem here when I use version 1.4 with WPF
Is there a workaround?
The problem also occurs in the sample InfoLayersSample when this function is called on MouseDown of your mapcontrol.

`private void MyMapControl_MouseDown(object sender, MouseButtonEventArgs e)
        {
            Point p = e.GetPosition(this);
            
            Mapsui.UI.MapInfo mi =MyMapControl.GetMapInfo(new Mapsui.Geometries.Point(p.X, p.Y),100);                        
            IFeature feature = mi.Feature;

            if (feature != null)
            {
                MessageBox.Show(feature.ToString());
            }
        }`

Thanks a lot

**Comment by pauldendulk** [comment]
@kreativgeist  There is a 'Map Info' sample. The implementation is in 'InfoLayersSample.cs'.
