### ISSUE TITLE
MapInfo and ScreenToWorld are returning wrong locations

### ISSUE THREAD

**Issue by OracleJavaX2** [Mapsui/Mapsui#568]
I have code in MouseUp event of MapControl (WPF).

```
private void MyMapControl_MouseUp(object sender, MouseButtonEventArgs e)
{
var screenPosition = e.GetPosition(this.MyMapControl);
var worldPosition = MyMapControl.Viewport.ScreenToWorld(screenPosition.X, screenPosition.Y);
}
```

But both Long and Lat are off. Any ideas why?

**Comment by charlenni** [comment]
I assume, that you use lat for long and vice versa.

And again: it would be nice, if you could give the answer to the question, if you have solved it.
