### ISSUE TITLE
Missing SkiaSharp.Views.Forms reference in NuGet package (Forms)

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#571]
When using the Xamarin.Forms NuGet package you will get this error message as soon as you try to use it: `Error: Failed to resolve assembly: 'SkiaSharp.Views.Forms, Version=1.60.0.0, Culture=neutral, PublicKeyToken=null'`

**Comment by pauldendulk** [comment]
ah, that's a bug. The Xamarin.Forms package automatically gets the SkiaSharp package via Mapsui, but not SkiaSharp.Views.Forms. It is a separate package that should be added as an explicit dependency. 
https://www.nuget.org/packages/SkiaSharp.Views.Forms/

**Comment by charlenni** [comment]
@pauldendulk If this is solved, you could close the issue.
