### ISSUE TITLE
Question About Linestring Distance/threshold of clicked item.

### ISSUE THREAD

**Issue by mbaker92** [Mapsui/Mapsui#572]
I have a question about Linestring and having some type of threshold ( like distance away from a point on the line) to register a click for that line. I have a GeoJSON file, given to me, with a bunch of information including the Latitude and Longitude that break down a road into multiple sections. I convert the lat and long to the coordinate system used by Mapsui.

I created both screenshots below with this data (one using Polygon and one using Linestring). I am able to click on most of the polygon features and have the information for that section show up, but the polygons look like they use the first point to close up the shape causing the feature I want to appear distorted.

Example with Polygon 
![screenshot_20181216-215428](https://user-images.githubusercontent.com/11892008/50676525-ab56e880-0fa9-11e9-9d1c-a1ae92ddef34.png)

The linestring version of the code has shapes more of what I am looking for and works with the points in the GeoJSON file I have. The only problem I have is that the linestring is almost impossible to hit, unless you click on what seems like 1 pixel on the line. 

Example with Linestring
![screenshot_20190103-223719](https://user-images.githubusercontent.com/11892008/50676527-adb94280-0fa9-11e9-9747-7adfedab0eb2.png)

I am developing on the Android platform. Is there some easy way to have the Infolayer choose the closest feature to the clicked point so that I can use Linestring or will I have to modify the GeoJSON file/Points I am given in some way to create the appearance I need?

Thanks

**Comment by pauldendulk** [comment]
In Mapsui.Samples.Wpf.Editing I used something like that to determine whether a point was clicked within a polygon. I does not some custom code though. This might be easier to do in v.2.0. It has a GetMapInfo method on the MapControl that takes a (touch) margin parameter. On the other hand this parameter should perhaps be on the layer itself to make it really easy for users. Not a big change in Mapsui I suspect.

A workaround might be to increasing the width of the line. Could you test if this works as expected? On the other hand you might not want to use a wider line.

**Comment by mbaker92** [comment]
Increasing the width did not have an effect on detection (even set at a large number). I will take a look at the code for Mapsui.Samples.Wpf.Editing and see how I can modify it before attempting to upgrade my nuget version and dealing with dependency issues. 

Thanks

**Comment by pauldendulk** [comment]
Thanks for the feedback. This might also be an issue in v2. If someone runs in this in v2 please post a new issue. It needs to get solved there.
