### ISSUE TITLE
Changes to the map limiter are not reflected on the map's viewport

### ISSUE THREAD

**Issue by johnpudd** [Mapsui/Mapsui#582]
The viewport limiter is defined when a map instance is assigned to the MapControl.Map property.

Map is assigned to in the  Mapsui.UI.Android.MapControl.Initialize() method, as such the Viewport Limter will always have the initial value.

I propose updating the Mapsui.Map.Limiter property as follows:
```
        private IViewportLimiter _limiter = new ViewportLimiter();
        public IViewportLimiter Limiter
        {
            get => _limiter;
            set
            {
                if (!_limiter.Equals(value))
                {
                    _limiter = value;
                    OnPropertyChanged(nameof(Limiter));
                }
            } 
        } 
```

And adding the following to the Mapsui.UI.Android.MapControl.Map setter to pass the new limiter through to the Viewport:
```
                    Map.PropertyChanged += delegate(object sender, PropertyChangedEventArgs args)
                    {
                        if (args.PropertyName.Equals(nameof(Map.Limiter)))
                        {
                            _viewport.Limiter = Map.Limiter;
                        }
                    };
```

**Comment by pauldendulk** [comment]
Good find! The solution makes sense. 

The fact that these classes and fields have to be stitched together with property changed event like this is an indication of complicated design, perhaps I need to think of something better. On the the other hand I could just get 2.0 to release and think about it in 3.0.

**Comment by pauldendulk** [comment]
@johnpudd I see you pushed a commit to your branch but you did not create a pull request. Perhaps you forgot about that.

**Comment by johnpudd** [comment]
Hi @pauldendulk, thanks - it looks like I got my branches in a muddle, so I have redone it and created a PR https://github.com/Mapsui/Mapsui/pull/592

**Comment by charlenni** [comment]
There is already a MapPropertyChanged in [MapControl.cs](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.UI.Shared/MapControl.cs#L271). So it seems, a new MapOnPropertyChanged isn’t needed.

**Comment by johnpudd** [comment]
Thanks @charlenni - I'll check and update the PR as appropriate..
