### ISSUE TITLE
InvalidCastException when starting Mapsui.Samples.Forms.WPF

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#585]
I get an exception when I try to run Mapsui.Samples.Forms.WPF.

> System.InvalidCastException: 'Unable to cast object of type 'SkiaSharp.Views.Forms.SKGLViewRenderer' to type 'Xamarin.Forms.IRegisterable'.'

Did not investigate this. Do others have the same problem?

**Comment by pauldendulk** [comment]
@charlenni Do you have this problem as well? Did this ever work correctly?

**Comment by charlenni** [comment]
Yes, I get this error too. Perhaps the SkiaSharp.Views.Forms implementation for WPF has some problems. If I have time, than I try to look into this.

**Comment by charlenni** [comment]
You could use the UWP to test the Forms MapControl on your desktop.

**Comment by pauldendulk** [comment]
After upgrading to SkiaSharp 1.68.1 this seems to be fixed.

**Comment by charlenni** [comment]
But using 1.68.1 was a problem with the rotation being very slow, wasn’t it?

**Comment by pauldendulk** [comment]
Yes, the first pre-release still had this problem. But when I mentioned this on the issue and Matthew investigated it further, found the problem and fixed it quickly. The problem was that skia is optimized for the Clang compiler but WPF was compiled with MSVC. 

See the release notes here: https://github.com/mono/SkiaSharp/releases/tag/v1.68.1 (in which you are mentioned twice 😀).

There have been quite a few changes so there could be new bugs in how we use skia.
