### ISSUE TITLE
ScaleBarWidgetRenderer first render uses the wrong font info

### ISSUE THREAD

**Issue by johnpudd** [Mapsui/Mapsui#593]
Typeface and TypeSize properties are only set on subsequent renders due to the necessary precondition _paintScaleBar == null.

I propose to update  Mapsui.Rendering.Skia.SkiaWidgets.ScaleBarWidgetRenderer.Draw to set these properties in all cases:

       
        // If this is the first time, we call this renderer, ...
        public void Draw(SKCanvas canvas, IReadOnlyViewport viewport,  IWidget widget,
                    float layerOpacity)
        {
            ...

            // If this is the first time, we call this renderer, ...
            if (_paintScaleBar == null)
            {
                // ... than create the paints
                ...
            }
            else
            {
                // Update paints with new values
                _paintScaleBar.Color = scaleBar.TextColor.ToSkia(layerOpacity);
                _paintScaleBar.StrokeWidth = StrokeInternal * scaleBar.Scale;
                _paintScaleBarStroke.Color = scaleBar.Halo.ToSkia(layerOpacity);
                _paintScaleBarStroke.StrokeWidth = StrokeExternal * scaleBar.Scale;
                _paintScaleText.Color = scaleBar.TextColor.ToSkia(layerOpacity);
                _paintScaleText.StrokeWidth = StrokeInternal * scaleBar.Scale;
                _paintScaleTextStroke.Color = scaleBar.Halo.ToSkia(layerOpacity);
                _paintScaleTextStroke.StrokeWidth = StrokeInternal * scaleBar.Scale;
            }
            
            _paintScaleText.Typeface = SKTypeface.FromFamilyName(scaleBar.Font.FontFamily, SKTypefaceStyle.Bold);
            _paintScaleText.TextSize = (float)scaleBar.Font.Size * scaleBar.Scale;
            _paintScaleTextStroke.Typeface = SKTypeface.FromFamilyName(scaleBar.Font.FontFamily, SKTypefaceStyle.Bold);
            _paintScaleTextStroke.TextSize = (float)scaleBar.Font.Size * scaleBar.Scale;

            ...

        }

It would also be very nice to be able to pass in `StrokeExternal` and `StrokeInternal` properties by adding these to ScaleBarWidget and updating the above to use if set.

**Comment by charlenni** [comment]
That's correct. This is a bug. Thank you for mentioning this.

See #594.

**Comment by johnpudd** [comment]
Great, thanks

**Comment by pauldendulk** [comment]
wow, thanks, a bug fixed before I read the report. Merged it.
