### ISSUE TITLE
Limiter causes flashing/jumping screen at extents

### ISSUE THREAD

**Issue by johnpudd** [Mapsui/Mapsui#595]
Creating a limiter (ViewportLimiterKeepWithin) where layers may extend beyond that area causes flickering when the user pans / zooms beyond the limit (and continues to touch the screen). 

This can be resolved in the map.Envelope calculation by limiting the bounding box by applying an intersection method.

In my case, this works nicely (but may not work for other limiters):

        public BoundingBox Envelope
        {
            get
            {
                if (_layers.Count == 0) return null;

                BoundingBox bbox = null;
                ...

                if (Limiter?.PanLimits != null)
                {
                    if (bbox == null)
                    {
                        return Limiter.PanLimits;
                    }
                    else
                    {
                        var limitedBBox = bbox?.Intersect(Limiter.PanLimits);
                        return limitedBBox;
                    }
                }
                else
                {
                    return bbox;
                }
            }
        }

In order to create greater flexibility, ILimiter could provide a method to handle the equivalent of the intersection calc here. This would allow for the Limiter's author to implement their preferred calculation - or simply return the original BoundingBox. 

        public BoundingBox Envelope
        {
            get
            {
                if (_layers.Count == 0) return null;

                BoundingBox bbox = null;
                ...

                if (Limiter != null)
                {                    
                    return Limiter.Clip(bbox);
                }
                else
                {
                    return bbox;
                }
            }
        }

The example above uses the following method to calculate the intersection:

        /// <summary>
        ///     Computes the intersection boundingbox of this instance and another boundingbox
        /// </summary>
        /// <param name="box">Boundingbox to create inersection with</param>
        /// <returns>Boundingbox of intersection of both boundingboxes</returns>
        public BoundingBox Intersect(BoundingBox box)
        {
            if (box == null)
                return Clone();
            return new BoundingBox(Math.Max(Min.X, box.Min.X), Math.Max(Min.Y, box.Min.Y),
                Math.Min(Max.X, box.Max.X), Math.Min(Max.Y, box.Max.Y));
        }

**Comment by pauldendulk** [comment]
Trying to reproduce your issue I ran into an issue that may not be exactly the same. I fixed this first. Maybe you can test this fix to see how it affects your issue.

**Comment by pauldendulk** [comment]
2.0.0-beta.17 was released which should improve your issue. Take a look and let me know if there are still issues left.
