### ISSUE TITLE
Mapui extreme lag after resize. WPF renderer only

### ISSUE THREAD

**Issue by wjax** [Mapsui/Mapsui#599]
Download latest beta 17 or master. Run Mapsui Sample WPF and set WPF renderer.
Everything works great until you resize the mainwindow. If you do so, application become unresponsive and super laggy.

**Comment by pauldendulk** [comment]
Thanks you very much. I will fix it.

**Comment by pauldendulk** [comment]
An update. It is easy to reproduce this. I can avoid it by adding an _invalidated boolean and checkin that in the render loop. However, I don't understand why this should be necessary. What makes invalidate triggered by the resize different from any other invalidate. I will investigate further.

**Comment by pauldendulk** [comment]
What seems to be happening is that the system goes into a infinite refresh loop. Why on resize?

**Comment by pauldendulk** [comment]
@wjax Do you need WPF specifically? It is the older renderer and will probably not be supported at some point.

**Comment by wjax** [comment]
Well.

The long story is that I am evaluating the possibility of migration from GMAP.net to Mapsui.
I use GMAP in many apps to paint vehicles, their tracks, heading and polygons etc.
While GMAP is bad in performance, it is very full of features.

One of the great things of GMAP is to be able to create a XAML of the marker you want to render and link it with Datacontext to it's data model using binding for updating a label, a rotation etc.

When I started to look at Mapsui I did not find anything similar. You seem to use "styles" that can be stacked one on top of the previous. The xaml thing was really great but I think I could live with the Mapsui styles.

Anyway. The wpf thing was because I only was able to rotate the marker in Mapsui while using the wpf renderer. Imagine the marked as an Aircraft icon that has to be pointing to the current heading.

**Comment by pauldendulk** [comment]
It is possible to rotate symbols in Skia as well with SymbolRotation. Is this what you need or is something else missing to display your aircraft correct?

**Comment by wjax** [comment]
I am already using SymbolRotation.
With wpf renderer it works as expected, with Skia don't.

I set rotation and then call Refresh.

**Comment by wjax** [comment]
Hello Paul. I will open an issue about the SymbolRotation in Skia if you don't mind

**Comment by pauldendulk** [comment]
Yes. It sound like an actual issue. The workaround is perhaps to clear some cache somewhere.
