### ISSUE TITLE
Xamarin Forms PinClick Problem

### ISSUE THREAD

**Issue by ptufail** [Mapsui/Mapsui#601]
Hi, 

I have a problem with PinClicked event, when i try to navigate to another page in this event nothing happens.

I have the same code to navigate in PinClicked event and button. When i the press button the navigation works but when i call navigate from PinClicked nothing happens

I create a repo to show this problem https://github.com/ptufail/TestingMapsuiIssue

**Comment by pauldendulk** [comment]
Thanks for the reproduction project!

**Comment by charlenni** [comment]
@ptufail I downloaded your example and try to test it, but get always an error. Both, on emulator and on device.

    Unhandled Exception:
    System.NullReferenceException: The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class. occurred

Anything I have to change?

**Comment by ptufail** [comment]
Hi, 

I found the problem... 

The PinClicked event need Device.BeginInvokeOnMainThread to navigate

Is supposed ?

**Comment by pauldendulk** [comment]
Yes, everything related to the UI has to be done on the UI thread. This is not related to Mapsui.

**Comment by pauldendulk** [comment]
So, your problem is solved and this can be closed?

**Comment by ptufail** [comment]
> So, your problem is solved and this can be closed?

Yes thanks
