### ISSUE TITLE
SymbolRotation not rotating with SkiaSharp renderer

### ISSUE THREAD

**Issue by wjax** [Mapsui/Mapsui#607]
As simple as it sounds.

If you create a symbol, add a style with a rectangle or square and try to rotate it wit SymbolRotation, it only works with WPF renderer but not with default Skia Renderer

**Comment by charlenni** [comment]
You used a VectorStyle or a SymbolStyle? And if SymbolStyle, which type of symbol do you use? 

Made a PR (#612) for the later one.

**Comment by wjax** [comment]
Use SymbolStyle created with this method:


private IFeature CreatePointWithStackedStyles()
        {
            point = new Feature { Geometry = SphericalMercator.FromLonLat(-6, 37) };

            point.Styles.Add(new SymbolStyle
            {
                SymbolScale = 2.0f,
                SymbolType = SymbolType.Triangle,
                Fill = null,
                Outline = new Pen { Color = Color.Yellow }
            });

            point.Styles.Add(new SymbolStyle
            {
                SymbolScale = 0.8f,
                Fill = new Brush { Color = Color.Red }
            });

            point.Styles.Add(new SymbolStyle
            {
                SymbolScale = 0.5f,
                Fill = new Brush { Color = Color.Black }
            });

            point.Styles.Add(new SymbolStyle
            {
                SymbolType = SymbolType.Rectangle,
                SymbolScale = 0.2,
                SymbolRotation = 0,
                Fill = new Brush { Color = Color.Blue }
            });

            point.Styles.Add(new LabelStyle
            {
                Text = "Stacked Styles",
                HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Left,
            });

            return point;
        }

**Comment by pauldendulk** [comment]
@wjax There are some issues but it seems to me that in beta 20 you can use orientation of vehicles if you use bitmap symbols instead of SymbolType.Triangle, providing you don' t use map rotation. The issues will be fixed before the 2.0 release.

**Comment by pauldendulk** [comment]
With the above commit vehicle orientation should now work properly for bitmap symbols and default symbols. When map rotation is used SymbolStyle.RotateWithMap should be set to true.
