### ISSUE TITLE
Pin visibility not honored on initial creation in Mapsui.Forms

### ISSUE THREAD

**Issue by lumberjack4** [Mapsui/Mapsui#608]
In my app I have a fixed set of pins that I can show on the map.  During map initialization, I want to go ahead and load the pins onto a map with the visibility set to false, so the user can place, show, and hide them at will.

When a pin is created the visibility is treated as true regardless of what the user specifies.  Once a pin is created, the visibility is correctly handled when changing the `IsVisible` property.  This is due to not setting the enabled flag of the underlying style on pin creation (it is handled on the property changed event).

The change is located here (7d14fafbb141883f6fba38ad3ecc00eb36b700c3).

**Comment by pauldendulk** [comment]
Thanks, merged it.
