### ISSUE TITLE
Always visible layers

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#610]
While looking into problem #606, I found another problem. The demo project creates no new Map object and than replace the MapControl.Map property, but uses the predefined MapControl.Map and than adds another layer for the raster map. Why is this a problem? The Pin layer (and the other two layers) that the Forms MapView uses, are added to the Map, when the MapControl.Map property change. But in this case, this never happens.

I think, we have three possible ways to handle this:
1. Document, that the user has to create a new Map, add layers s/he wants and than set this Map to MapView.Map, so I could add the Forms layers on top.
2. MapView attaches to Map.Layer.OnLayerAdded and OnLayerRemoved. Each time one of this events is fired, the 3 layers of MapView will be removed and added again. If not, they are not the top most layers and so aren't visible.
3. LayerCollection has the possibility to define special layers, which are always on top (in this case the last layers in array) of all other layers.

Any suggestions, which is the right/best way?

**Comment by charlenni** [comment]
Seems to be the same as #598.

**Comment by pauldendulk** [comment]
I see the problem. We will need some  better way to order layers. Let's discuss this further in #598. I will close this one.
