### ISSUE TITLE
Error to add new Mbtiles file in Samples

### ISSUE THREAD

**Issue by Davidgh96** [Mapsui/Mapsui#611]
I try to add new mabtiles file in Samples project and i can't do working correctly. Show you the error 

Excepción producida: 'System.ArgumentNullException' en SkiaSharp.dll
Excepción producida: 'System.ArgumentNullException' en SkiaSharp.dll
Excepción producida: 'System.ArgumentNullException' en SkiaSharp.dll
Excepción producida: 'System.ArgumentNullException' en SkiaSharp.dll
Excepción producida: 'System.ArgumentNullException' en SkiaSharp.dll
Excepción producida: 'System.ArgumentNullException' en SkiaSharp.dll
El subproceso 0x2f6c terminó con código 0 (0x0).
El subproceso 0x1e2c terminó con código 0 (0x0).
El subproceso 0x13b0 terminó con código 0 (0x0).
Excepción producida: 'System.NullReferenceException' en Mapsui.Rendering.Skia.dll
Excepción producida: 'System.NullReferenceException' en Mapsui.Rendering.Skia.dll
Excepción producida: 'System.NullReferenceException' en Mapsui.Rendering.Skia.dll
Excepción producida: 'System.NullReferenceException' en Mapsui.Rendering.Skia.dll
Excepción producida: 'System.NullReferenceException' en Mapsui.Rendering.Skia.dll

![image](https://user-images.githubusercontent.com/25246266/53230247-908a2180-3686-11e9-8b28-ac869cda9abb.png)

**Comment by charlenni** [comment]
What type of MBTile file do you have? Raster/bitmap or vector?

**Comment by Davidgh96** [comment]
i don't know exactly, show you  the file 
![image](https://user-images.githubusercontent.com/25246266/53234842-bfa59080-3690-11e9-9ee0-34f2c02bddd1.png)

**Comment by Davidgh96** [comment]
I think is a vector file

**Comment by charlenni** [comment]
Ok, that's the problem. Mapsui couldn't display vector MBTiles, but only raster MBTiles.

**Comment by pauldendulk** [comment]
@Davidgh96 What component did you use to generate the screenshot?

**Comment by Davidgh96** [comment]
yes , It's true. I replaced the vector mbtiles to raster mbtiles and now its working. Other question, i tried to used the embebed example Itinero.Code.Samples but it's not working because said me that is old version. Do you have another update sample? or how can i create a sample with only mbtiles map( without the rest of the Mapsui.Samples.Wpf )?

**Comment by pauldendulk** [comment]
I am not sure what you are asking. What I can say is that there is MTilesSample.cs with the sample code. You need to copy it to your own project. If this is not the answer to your question then please open another issue to discuss it.
