### ISSUE TITLE
Feature Selection issue on Info Clicked Action when upgraded to New Version

### ISSUE THREAD

**Issue by RajeethKalluru** [Mapsui/Mapsui#614]
**2.0.0-beta.17.**
![issueversion17 0](https://user-images.githubusercontent.com/48022555/53422066-c0c61d00-3a04-11e9-9328-4f7d00ecd608.gif)

 **2.0.0-beta.16.**
![workingversion_16 0](https://user-images.githubusercontent.com/48022555/53422144-ee12cb00-3a04-11e9-9ae5-e1c7fa89ebb3.gif)

Hi Team,
I am trying to implement a "Feature" with "SymbolStyle".
Here is my requirement. 

**Requirement:**
I want to fill the color to one of the feature's SymbolStyle  on Info Click event.

**Here is the block of code I am using to fill the color:**
public void InfoClicked(object sender, MapInfoEventArgs args)
        {
            Feature selectedFeature = (Feature)args.MapInfo.Feature;
            SymbolStyle currentSymbolStyle = (SymbolStyle)selectedFeature.Styles.FirstOrDefault();
            currentSymbolStyle.Fill = new Brush { Color = Mapsui.Styles.Color.Red };
            currentSymbolStyle.Outline = new Pen { Color = Mapsui.Styles.Color.Red };
        }

**Issue:**
Unable to fill color occasionally (it is getting filled once we change the viewport of the map) with version 2.0.0-beta.17 onwards. It was working fine till 2.0.0-beta.16.
Also app is getting crash when we change the viewport multiple times.

**Here is the source code.**
[MapsUIFeatureDemo.zip](https://github.com/Mapsui/Mapsui/files/2906331/MapsUIFeatureDemo.zip)

Please do needful.

Thanks & Regards
Rajeethulla Kalluru.

**Comment by pauldendulk** [comment]
Thanks for your clear report!

It looks like this is a refresh issue. The map does not refresh after a feature is selected. Since we don't have notifications going from the features to the map I think you should trigger the refresh yourself. This could be done with Map.Refresh() or ILayer.DataHasChanged available from 2.0.0-beta.18.

**Comment by pauldendulk** [comment]
The crash sounds more serious. Perhaps you can open a separate issue for that. Please try to explain how we can reproduce it.

**Comment by RajeethKalluru** [comment]
> Thanks for your clear report!
> It looks like this is a refresh issue. The map does not refresh after a feature is selected. Since we don't have notifications going from the features to the map I think you should trigger the refresh yourself. This could be done with Map.Refresh() or ILayer.DataHasChanged available from 2.0.0-beta.18.

Hi Team,
We appriciate your quick reply and it worked great for me.
I implemented  "ILayer.DataHasChanged()" method.
Thanks for your support.

Thanks & Regards
Rajeethulla Kalluru.

**Comment by RajeethKalluru** [comment]
> The crash sounds more serious. Perhaps you can open a separate issue for that. Please try to explain how we can reproduce it.

Sure pauldendulk, 
I will try to reproduce the crash and I will create a new issue for that.


Thanks & Regards
Rajeethulla Kalluru.
