### ISSUE TITLE
Pinch rotation

### ISSUE THREAD

**Issue by Nj0376** [Mapsui/Mapsui#616]
I have begun looking at mapsui in xamarin forms.  Really like whats been done here.  One thing I cannot seem to find is the ability to turn on MapControl.AllowPinchRotation = true.  Apologies if I am missing something obvious but I've looked in in both Android and iOS as well as shared implementations and cannot find it anywhere.

**Comment by pauldendulk** [comment]
I think this is just not implemented. @charlenni knows more. For me this won't block a 2.0 release.

**Comment by charlenni** [comment]
Where did you find this? In the Xamarin.Forms.Maps implementation? We have a RotationLock property, which you could find in MapView and also in Map.

If you search something for the Forms implementation, than you should look into Mapsui.UI.Shared and Mapsui.UI.Forms. The Mapsui.UI.iOS and Mapsui.UI.Android don't used for the Forms part.

**Comment by pauldendulk** [comment]
@charlenni So it should work in XF if you set:

```MapControl.Map.RotationLock = false```

**Comment by charlenni** [comment]
Yes. Or you could use
````
MapView.RotationLock = false;
````
This is also a bindable property in MapView.

**Comment by Nj0376** [comment]
Thanks for the feedback I notice RotationLock is in Beta for version 2.  I've been using 1.48 and can see considerable differences between them now.  I'll look more into the new version.

btw I found references to AllowPinchRotation in older issues such as #8

**Comment by charlenni** [comment]
@Nj0376 Ah, than you use the renderer approach for Xamarin.Forms. Mapsui 2.x uses a native approach, which is complete different to the old one.

**Comment by pauldendulk** [comment]
It is probably best to go for 2.0 right. It is in the final phase for release.
