### ISSUE TITLE
Current Location Pin Icon

### ISSUE THREAD

**Issue by Afonsoxvp** [Mapsui/Mapsui#618]
I am currently developing an application that uses MapsUi and would like to know if it is possible to **change the icon that represents the current location of the user**. If so, how is this done.
![img_20190228_132440](https://user-images.githubusercontent.com/33024207/53570213-dc910680-3b5d-11e9-8fa4-6b80d29de68c.jpg)

**Comment by charlenni** [comment]
No, in the moment there are only two given icons (one for still, one for moving).

Do you need such a functionality?

**Comment by Afonsoxvp** [comment]
Currently I am working on a project that uses OpenStreetMap. The project uses a service that provides me with coordinates that use to dynamically define some pins on the map. I know that it is possible to be constantly acquiring the current coordinates of the user and my idea is to set a pin with a custom image in the current location and to update whenever there is movement.
Is this the better approach, or you have another thought about it ?

**Comment by pauldendulk** [comment]
The MapView Current-Location is additional functionality offered by the MapView (on top of the MapControl). It is always possible to add such functionality yourself on top of the MapControl. 

Then again it also interesting for us to hear what kind of functionality users want.

**Comment by charlenni** [comment]
I could add the functionality, that you could add your own icon for the MyLocationLayer, which is a normal Mapsui Layer with additionaly functionality. Should I?

**Comment by pauldendulk** [comment]
@charlenni Do you mean you would need a modified version of the Mapsui Layer?

**Comment by Afonsoxvp** [comment]
At this time it is not very urgent to add this functionality. I'll test it the way I explained and see if it works, but I think it's an interesting little map customization. I'll be aware if you add this functionality

**Comment by charlenni** [comment]
@pauldendulk As you can [see](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.UI.Forms/Objects/MyLocationLayer.cs#L20), MyLocationLayer is a normal MemoryLayer with added functionality. The only thing it uses from Forms is the animation. If you set a new location, it moves smooth to this new location (as asked for in #615). It is, that the map doesn't "jump" araound.

**Comment by pauldendulk** [comment]
ah, I see. Whether you should change this is up to you. It is certainly no necessity. There are probably other things you could better spent your time on. Also, perhaps @Afonsoxvp could send a PR to fix this. The code seems easy enough. 

Perhaps a better way to improve this is to use a ThemeStyle. The ThemeStyle gets a method with the feature as argument. The feature should contain all possibly relevant information (like isMoving). The method can then decide whichever SymbolStyle to return based on the position information.

If you create a setter for the ThemeStyle (or IStyle) users can attach their own symbology and there will be little else to make configurable.
