### ISSUE TITLE
MyLocation Icon and Pins are not visible

### ISSUE THREAD

**Issue by Mohakalilam** [Mapsui/Mapsui#619]
Application zooms correctly to my current location but I dont see the location icon.

![image](https://user-images.githubusercontent.com/7780397/53583014-af1c7b00-3ba6-11e9-97e7-7a2a528d1583.png)
I also drew some pins but they are not visible. Should I have to add svg images??

![image](https://user-images.githubusercontent.com/7780397/53583089-d3785780-3ba6-11e9-8c80-f555d7730f05.png)

**Comment by Mohakalilam** [comment]
![image](https://user-images.githubusercontent.com/7780397/53583254-37028500-3ba7-11e9-84c3-5d5ccf1d3661.png)

**Comment by charlenni** [comment]
Do you use the newest version of Mapsui NuGet? And how do you create the layer for your map?

**Comment by Mohakalilam** [comment]
Yes I am using the latest beta version. I have declared MapView in Xaml and setting the MyLocation in backend.

 var request = new GeolocationRequest(GeolocationAccuracy.Best);
            var location = await Geolocation.GetLocationAsync(request);
            if (location != null)
            {
                double Speed = location.Speed.HasValue ? (double)location.Speed : 0;
                int Course = location.Course.HasValue ? (int)location.Course : 0;
                var coords = new Mapsui.UI.Forms.Position(location.Latitude, location.Longitude);
                info.Text = $"{coords.ToString()} -A:{location.Accuracy} D:{Course} S:{Math.Round((double)Speed, 2)}";
                mapView.MyLocationLayer.UpdateMyLocation(coords);
                //mapView.MyLocationLayer.UpdateMyDirection(location., mapView.Viewport.Rotation);
                mapView.MyLocationLayer.UpdateMySpeed(Speed);
            }

It zooms to right location but it is not showing the Location Icon. Am I missing anything?

**Comment by charlenni** [comment]
I would like to see the place, where you create the layer with the map.

**Comment by Mohakalilam** [comment]
Here is the complete code.

![image](https://user-images.githubusercontent.com/7780397/53587486-8305f780-3bb0-11e9-8181-2c29c8a5a6a3.png)

**Comment by charlenni** [comment]
Ok, now I see the problem. You create a new layer and add it to Map.Layers. This layer is than on top of all other layers (even the layers of MapView). So the location icon and all pins are hidden from this new layer.

I created a new PR (#620) for this problem. Thought, I did this before :(

**Comment by charlenni** [comment]
As workaround you could create a Map by your own and than replace MapView.Map with this new Map.

**Comment by pauldendulk** [comment]
#620 was merged.

**Comment by Mohakalilam** [comment]
I have applied the workaround and its working fine, other thing I had to do was to add the osm at zero index.

![image](https://user-images.githubusercontent.com/7780397/53591309-b0a36e80-3bb9-11e9-851b-b9ab747f7d86.png)
