### ISSUE TITLE
Pin coordinates are not transformed

### ISSUE THREAD

**Issue by hajmajeboss** [Mapsui/Mapsui#623]
I have the following issue:
- I have to use CRS EPSG:102067 for my Xamarin.Forms project
- I want to use pins 
- I have written my own transformation class 
- Pin coordinates are not transformed, so the pin still appears at spherical mercator coordinates

**Comment by pauldendulk** [comment]
The out of the box Mapsui support for projections is limited. There is some documentation here: https://mapsui.com/documentation/projections.html.

However there should be some workaround for this scenario.

**Comment by hajmajeboss** [comment]
Yes, there is a workaround - directly changing underlying feature's geometry after the pin is created.

However, I think it's better to have these things already sorted out in the API - there is a projection support and there is a projection defined in the map's property - no reason not to use it when transforming Position objects into Point objects. That's why I filled this issue in the first place. 

Thank you for the reply anyway.

**Comment by charlenni** [comment]
I assume here, that you use MapView of the Mapsui 2.0 beta.

This MapView is designed to mimic the original Xamarin.Forms.Maps object. There isn’t any projection handling. If you want to use a special projection, than create your own MapView from the normal MapControl from Forms. With this, you could create your own pin layer which than respects your projection. Or add an own pin layer to the existing MapView.Map.

**Comment by hajmajeboss** [comment]
Ok, thank you.
