### ISSUE TITLE
How to load feature of a layer by bbox

### ISSUE THREAD

**Issue by sebs78** [Mapsui/Mapsui#624]
Hi,
Is it a way to load feature in a layer by bbox?
I have 60000 features in my layer and I would like mapsui load only feature that are in the view bbox. Is it possible? With 60000 features, the map moving is very slow(xamarin project on android phone). Any other idea?
Regards
Seb

**Comment by pauldendulk** [comment]
For this you should use the async Layer and the 6000 features should be in it's provider. 

This will decrease the responsiveness. It will take a moment for the features to load. A problem you had earlier.

**Comment by pauldendulk** [comment]
If you zoom out a lot of features will be visible. You might need to use MaxVisible. Or perhaps do some clustering in your provider.

**Comment by sebs78** [comment]
> For this you should use the async Layer and the 6000 features should be in it's provider.
> 
> This will decrease the responsiveness. It will take a moment for the features to load.

Hi, what do you mean by async Layer. my code is:

List<Feature> features = new List<Feature>();
//point is a 60 000 object list
foreach (var  in points)
{
        var feature = new Feature();
        Point point = new Point(p.x, p.y);
        feature.Geometry = point;
         features.Add(feature);
}  
MemoryLayer layer = new MemoryLayer
 {
        Name = "Points",
        DataSource = new MemoryProvider(features),
        Style = CreateBitmapStyle(),
        MaxVisible = 18,
        MinVisible = 0
};
mapControl.NativeMap.Layers.Add(layer);

With this code, the map load all objects when I was between Max and MinVisible even if the object isn't in the visible bbox.

**Comment by pauldendulk** [comment]
You use a ```MemoryLayer```. You should use a ```Layer``` instead. It fetches it's data from a Provider after change in the maps Viewport. Your features should be added to a MemoryProvider. The MemoryProvider needs to be assigned to the Layer.DataSource.

**Comment by sebs78** [comment]
thanks, it works!!

Regards
