### ISSUE TITLE
Issue with .PNG Marker File path

### ISSUE THREAD

**Issue by HoolieR** [Mapsui/Mapsui#628]
Hey there,

I'm currently running the latest Beta of Mapsui on my project and I'm trying to apply a custom Marker .PNG but my program has trouble loading it. As a test, my image is located on my base E: drive like so:

> "E:\home.png"

And my code is written as such:

> var path = @"E:\\\home.png";

When I load the map and have the program load the marker on the push of a button I get the error:

> System.ArgumentException: 'The bitmap data that is registered is null. Was the image loaded correctly?'

I've checked the Sample code for PointsSample.cs - and it has the file path written as;

> var path = "Mapsui.Samples.Common.Images.home.png"; 

So the file is located in:

> "C:\Users\Work\Downloads\Mapsui-master\Samples\Mapsui.Samples.Common\Images\home.png"

I've tested this error in the Sample code by altering var path to:

> @"E:\\\home.png"

And it reports back the error, which is the same error I get in my own project.

I've tried different methods of getting "var path" to direct to an image in a different drive and folder, such as writing a method which looks into the base directory of my project and loading that, to naming var path to:

 
> var path = "MapTest.Images.home.png"; //[Project Folder/Images/home.png]
However, I still get the same error.

I'm just having trouble understanding the formatting of "var path". Is there a method where I can load "home.png" from my base E: drive, or my base project folder - and what is the recommended formatting for var path?

Many thanks.

**Comment by charlenni** [comment]
This is not a file path to a folder on a drive, but a path to a resource. This resource is in your project.

**Comment by HoolieR** [comment]
> This is not a file path to a folder on a drive, but a path to a resource. This resource is in your project.

Ah, I see. I've imported home.png as a Resource and I've edited my code to:

> SymbolStyle CreateBitmapStyle()
                    {
                        var path = "MapTest.Images.home.png"; 
                        var bitmapId = GetBitmapIdForEmbeddedResource(path);
                        var bitmapHeight = 176;
                        return new SymbolStyle { BitmapId = bitmapId, SymbolScale = 0.20, SymbolOffset = new Offset(0, bitmapHeight * 0.5) };
                    }
                    int GetBitmapIdForEmbeddedResource(string imagePath)
                    {
                        var assembly = typeof(MainWindow).GetTypeInfo().Assembly;
                        var image = assembly.GetManifestResourceStream(imagePath);
                        return BitmapRegistry.Instance.Register(image);
                    }

But I still get the same error. Is there something I'm doing wrong? I'm using almost the exact same code as the sample.

**Comment by charlenni** [comment]
@HoolieR That's ok. Thank you for coming back and mention your solution. But please make next time a new entry instead of editing the old one.
