### ISSUE TITLE
Add Pin Sample crashes when nugets are updated to latest

### ISSUE THREAD

**Issue by klzig** [Mapsui/Mapsui#630]
While investigating #629, I discovered that the Add Pin Sample crashes if I update all of the nuget packages in the Mapsui project to latest stable (not prerelease), 40+ packages total.  In a quick check, some of the samples work normally while others crash.  All of the samples work for me if I leave
the packages alone.  I'm working with a current fetch from the Mapsui repo.

Tested on Nokia 6.1 running Android 9.

In ScaleBarWidgetRenderer.cs:
![image](https://user-images.githubusercontent.com/2966135/54089251-b1ac6c80-432c-11e9-81b4-86eea44a5e64.png)

**Comment by pauldendulk** [comment]
I ran into this error myself while updating to latest SkiaSharp. It looks like an unintended breaking change in SkiaSharp or even a bug in SkiaSharp. The input is an empty string. This should not cause a null reference exception. The method should just set textSize 0.

**Comment by pauldendulk** [comment]
In my local code I added a workaround for this.

**Comment by klzig** [comment]
I'm not sure what to make of this, but when I attempted to reproduce this again I used VS2019 Preview 2 and it didn't reproduce.  With latest nugets, deployed on my Android device, I tried many of the samples including Add Pin and they all worked.   When it failed I built with VS2017 15.9.7.  Windows.  Guessing I didn't get all the components installed correctly.  It did complain about a problem with a nuget package that required restarting VS, but so did 2019.

**Comment by charlenni** [comment]
I couldn't reproduce this. What do you do to get this problem.

**Comment by klzig** [comment]
I've lost my ability to reproduce it, see my previous comment.  Maybe @pauldendulk can still repro it.

**Comment by pauldendulk** [comment]
This is fixed in master. Here:
https://github.com/Mapsui/Mapsui/commit/8301e3a99ca402e1f6afd5e0cf2b64535cba819a#diff-89053c60defb3cd8f222c8e2efb09795R125
I will close the issue.
