### ISSUE TITLE
Question: Is there a way to allow users to drag&drop Pins/Markers/Features?

### ISSUE THREAD

**Issue by SebastianKruseWago** [Mapsui/Mapsui#633]
Does Mapsui already support something like this?

**Comment by pauldendulk** [comment]
You could take a look at the Mapsui.Samples.Wpf.Editing. The editing code is in large parts in custom code which is not part of the nuget packages yet. The idea is that at some point this code will move into an EditLayer.

**Comment by pauldendulk** [comment]
![out7](https://user-images.githubusercontent.com/963462/54144425-f539d000-442b-11e9-9905-afd99171bf05.gif)

**Comment by pauldendulk** [comment]
![out8](https://user-images.githubusercontent.com/963462/54144673-7c874380-442c-11e9-9aa4-7f38c39ab283.gif)
