### ISSUE TITLE
When map is rotated, than click on feature doesn't work correct

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#634]
If you rotate the map and than try to click on a Feature, you don't get the correct Feature. If you click at the area where the Feature should be in unrotated position, than you get the correct Feature.

**Comment by pauldendulk** [comment]
If I run Samples.Mapsui.Wpf and select the MapInfo sample map rotation and feature selection seems to work correct.

**Comment by charlenni** [comment]
Go to the Symbols-Symbols demo, rotate the map and click around the black markers. You tested it with marker, that are nearly rotation symetric. Try with asymetric ones.

**Comment by pauldendulk** [comment]
ah, we need to take the rotation of the symbol into account and also take into account RotateWithMap.

**Comment by pauldendulk** [comment]
This is fixed in skia and won't be fixed in wpf.
