### ISSUE TITLE
How to zoom to a bounding box?

### ISSUE THREAD

**Issue by klzig** [Mapsui/Mapsui#636]
The best I've been able to come up with (#14) is the following.  It centers correctly but is zoomed in way too far, the resolution is obviously wrong.   Using the latest Mapsui.Forms beta for Android and iOS.

What's the correct way to do this?

```
var w = Application.Current.MainPage.Width;
var h = Application.Current.MainPage.Height;
ZoomHelper.ZoomToBoudingbox(-116.210927, 43.617908, -116.195544, 43.623198, w, h, out double x, out double y, out double resolution);
var p = new Position(y, x);
mapView.Navigator.NavigateTo(p.ToMapsui(), resolution);
```

**Comment by charlenni** [comment]
The resolution is calculated by
````
resolution = Math.Max((x2 - x1) / screenWidth, (y2 - y1) / screenHeight);
````
This is, because the scale method is `ScaleMethod.Fit`. Perhaps you should use another one?

**Comment by pauldendulk** [comment]
There is a specific overload for that:

```c#
public void NavigateTo(BoundingBox extent, ScaleMethod scaleMethod = ScaleMethod.Fit)     
```

**Comment by klzig** [comment]
Do you mean
```
 var bbox = new Mapsui.Geometries.BoundingBox(-116.210927, 43.617908, -116.195544, 43.623198);
 mapView.Navigator.NavigateTo(bbox, ScaleMethod.Fit);
```
?

With this I get the same results as my ZoomHelper example if I remove
`var p = new Position(y, x).ToMapsui();`
It takes me somewhere off the west coast of Africa, zoomed waaaaay in.

It seems Position.ToMapsui() is doing a necessary translation for the x,y coordinates?  But the translation is independent of resolution so even with it (my original example) the zoom is wrong.  It's wrong (zoomed in too far) no matter how I set ScaleMethod.

If this isn't making sense I can add it to my sample app.

**Comment by pauldendulk** [comment]
You are using coordinates in WGS84 (latlon). They need to be transformed to SphericalMercator.

https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Projection/SphericalMercator.cs#L12

**Comment by pauldendulk** [comment]
I just made a start with a FAQ

https://mapsui.com/documentation/faq.html#why-is-all-my-data-in-a-small-area-near-the-west-coast-of-africa

**Comment by charlenni** [comment]
As I mentioned earlier, MapView uses WGS84 instead of spherical mercator coordinates, which are used by Mapsui. So you have to transform them. This is made by
````
var p = new Position(y, x).ToMapsui();
````

Regarding your problem: you try to use WGS84 coords for Mapsui, which doesn't work. You should translate them before you use them with MapView. So your code should look like this:
````
var w = Application.Current.MainPage.Width;
var h = Application.Current.MainPage.Height;
// Transfer your coordinates from WGS84 (MapView format) to spherical mercator (Mapsui format)
var southWest = new Position(43.617908, -116.210927).ToMapsui();
var northEast = new Position(43.623198, -116.195544).ToMapsui();
// Use the Mapsui functions
ZoomHelper.ZoomToBoudingbox(southWest.X, southWest.Y, northEast.X, northEast.Y, w, h, out double x, out double y, out double resolution);
mapView.Navigator.NavigateTo(x, y, resolution);
````

The problem here is, that I missed the `MapView.MoveToRegion()` function. This function uses a MapSpan to move the map.

**Comment by klzig** [comment]
Thanks for all your help.  That worked (with one minor change to the last line).
```
var w = Application.Current.MainPage.Width;
var h = Application.Current.MainPage.Height;
// Transfer your coordinates from WGS84 (MapView format) to spherical mercator (Mapsui format)
var southWest = new Position(43.617908, -116.210927).ToMapsui();
var northEast = new Position(43.623198, -116.195544).ToMapsui();
// Use the Mapsui functions
ZoomHelper.ZoomToBoudingbox(southWest.X, southWest.Y, northEast.X, northEast.Y, w, h, out double x, out double y, out double resolution);
mapView.Navigator.NavigateTo(new Mapsui.Geometries.Point(x, y), resolution);
```

**Comment by pauldendulk** [comment]
The NavigateTo(BoundingBox box, ScaleMethod scaleMethod) was meant for zooming to boundingbox. Is there a reason you could use it? It will look something like this:

```c#
// Transfer your coordinates from WGS84 (MapView format) to spherical mercator (Mapsui format)
var min = new Position(43.617908, -116.195544).ToMapsui();
var max = new Position(43.623198, -116.210927).ToMapsui();

mapView.Navigator.NavigateTo(new BoundingBox(min, max), ScaleMethod.Fit);
```

**Comment by pauldendulk** [comment]
btw, spherical mercator is not the coordinate system of Mapsui but of the OpenStreetMap background layer. You could choose other background layers and work with other coordinate systems. This is design choice with advantages and disadvantages. The advantage is that you can support local coordinate systems. This is often used for government related organizations that use the coordinate system of the country. Sometimes this is enforced by regulations. The disadvantage is that you can not add better support for the conversion between WGS84 and SphericalMercator. Users often need to convert it in their own code.

**Comment by klzig** [comment]
This works as well and is definitely cleaner, thanks.
```c#
// Transfer your coordinates from WGS84 (MapView format) to spherical mercator (Mapsui format)
var min = new Position(43.617908, -116.195544).ToMapsui();
var max = new Position(43.623198, -116.210927).ToMapsui();

mapView.Navigator.NavigateTo(new BoundingBox(min, max), ScaleMethod.Fit);
```
I may have just missed it but I don't recall this zoom to bounding box example in the sample app, I could add it if there is any interest.

Also, is there value in a sample app based on .net standard and the standard Forms master-detail pattern like I posted here: [MapsuiFormsSample](https://github.com/klzig/MapsuiFormsSample)?

**Comment by klzig** [comment]
FWIW part of my confusion came from the fact that this works without any apparent translation but zooming to bounding box didn't.

```c#
var bbox = new BoundingBox(-116.210927, 43.617908, -116.195544, 43.623198);
Mapsui.UI.Objects.Drawable f;
lock (mapView.Drawables)
{
  if (mapView.Drawables.Count == 0)
  {
     f = new Polyline { StrokeWidth = 4, StrokeColor = Color.Red };
     mapView.Drawables.Add(f);
  }
  else
     f = mapView.Drawables.First();

  if (f is Polyline)
  {
      ((Polyline)f).Positions.Add(new Position(bbox.TopLeft.Y, bbox.TopLeft.X));
      ((Polyline)f).Positions.Add(new Position(bbox.TopRight.Y, bbox.TopRight.X));
      ((Polyline)f).Positions.Add(new Position(bbox.BottomRight.Y, bbox.BottomRight.X));
      ((Polyline)f).Positions.Add(new Position(bbox.BottomLeft.Y, bbox.BottomLeft.X));
      ((Polyline)f).Positions.Add(new Position(bbox.TopLeft.Y, bbox.TopLeft.X));
  }
}
```

**Comment by charlenni** [comment]
That‘s because MapView.Drawables is a MapView layer, which does the conversion for you. The same happens with the Pin layer.

**Comment by pauldendulk** [comment]
> I may have just missed it but I don't recall this zoom to bounding box example in the sample app, I could add it if there is any interest.

It would be nice to have this implemented in an ISample. A problem is that the current setup of the sample only create a static map. There is no way to add some kind of action. This has been a problem before. A possible solution that I have been thinking of is to add an ISampleAction interface with just one method that could be implemented only in samples where it makes sense. In the sample app there should be a button to call this action. The sample app should check if the selected sample implements ISampleAction and should enable the button if it does.

The could be a sample category for navigation. Other areas that could make use of this are 
- Adding removing layers
- Adding removing features
- Change style for a selection of features
- Call feature info on a WMS
- Calculate a route
