### ISSUE TITLE
symbol style from base64 bitmap string or svg string file?

### ISSUE THREAD

**Issue by sebs78** [Mapsui/Mapsui#637]
Hi,
I would like to set the feature symbol with a bitmap base64 string or with a string svg. Is it a way to do that? I found sample with assembly ressource but not with memory string describing the symbol (svg or bitmap base64).

Regards
Seb

**Comment by charlenni** [comment]
You could not register a string, but you could register a stream containing a string. If the string starts with “<svg”, than it is interpreted as SVG image. If not, than it is interpreted as bitmap (JPEG, PNG and so on).

**Comment by sebs78** [comment]
ok, thanks, it works
