### ISSUE TITLE
How to use layer MinVisible / MaxVisible?

### ISSUE THREAD

**Issue by sebs78** [Mapsui/Mapsui#638]
I would like to use layer MinVisible and MaxVisble to display features following the zoom(like OSM zoom).

How to use this value to set my feature visible between OSM zoom (14/20)?

Regards

**Comment by pauldendulk** [comment]
They values of MaxVisible and MinVisible would correspond with the 'resolution' values that correspond to zoom level 12 and 20.

**Comment by pauldendulk** [comment]
Seem 'm / pixel' column here for the values used in osm.
https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by sebs78** [comment]
thanks it works
