### ISSUE TITLE
Forms: LongTap (iOS) not working

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#639]
The LongTap event is not getting fired on iOS (Forms). It works on Droid and also SIngleTap and DoubleTap is working fine. Just LongTap is not fired. 

Edit: Only tested iOS and Android with Mapsui 2.0 beta 22 while using Xamarin.Forms.

**Comment by charlenni** [comment]
I assume, that this is the same problem like the double tap: you move with your finger between press and release. So I added an around check for this (see #640).

**Comment by Sebastian1989101** [comment]
@charlenni The double tap was working just fine on my app so I'm not sure if this is really the issue. Also long tap was working in a older beta version (I guess it was last tested before the changes for the Samsung touch detection on Droid?). Also it seems like the issue also happens when I use a script to klick and hold a specific pixel down. Does iOS maybe have a problem with double event registration? Because in some cases I register more than one listener to a event (because the user can configure what happens on which event and if the user wants for example long tap for open existing markers and long tap to create new ones the app is registered two times to this event).

**Comment by pauldendulk** [comment]
I assume this is fixed by now.

**Comment by pauldendulk** [comment]
Update: In v5 long press is implemented crossplatform in the TapGestureTracker.
