### ISSUE TITLE
Is it possible to change map theme

### ISSUE THREAD

**Issue by Yuan-JLL** [Mapsui/Mapsui#647]
Google Maps allows to change to different map themes.
https://mapstyle.withgoogle.com/

Is it possible to achieve similar effect in Mapsui?

**Comment by charlenni** [comment]
No, that isn’t possible. Google could make this, because it uses a vector map. Mapsui only uses raster maps up to now. If you find a raster tile provider, which could handle this, than you could use this.

**Comment by ashishmundrajll** [comment]
@charlenni Are there any other existing color palette that OSM Maps has, from which we can choose one? The default one does not go well with our UI design.

**Comment by charlenni** [comment]
You don’t have to use an OSM map at all. You could use all raster tile providers. There are many out there, some for free, some are paid.

**Comment by charlenni** [comment]
Some examples could be found [here](https://wiki.openstreetmap.org/wiki/Tile_servers).

**Comment by taublast** [comment]
> No, that isn’t possible. Google could make this, because it uses a vector map. Mapsui only uses raster maps up to now. If you find a raster tile provider, which could handle this, than you could use this.

mapsui is rendering bitmaps with skia, you could let people apply any color filter and make other adjustments to bitmaps before rendering them on canvas. so the anwer "not possible" is not correct, it's just not implemented.

**Comment by taublast** [comment]
Quickly have done nothing fancy but just added a quick tint color filter, eplaced standart birmap renderer with custom one `this.Renderer.StyleRenderers[typeof(RasterStyle)] = new CustomRasterStyleRenderer();` but this custom one was mainly copy-pasted from repo, while it would nicer to let people subclass the renderer and override virtual SkPaint provider methods, so they can do anything, also letting them adjust paint quality etc.

![image](https://user-images.githubusercontent.com/25801194/206761945-1725e662-0e0d-45b5-9f66-f09aae27b0fd.png)

**Comment by charlenni** [comment]
@taublast That is correct, but, I assume, that this isn't what the owner of this thread is asking for. I assume, that it is more about the style of a map should be changed like you could do with e.g. [Maputnik](https://maputnik.github.io/editor). And that is only possible with vector styles.

But the example is good. Perhaps it would be helpful for others, if you could upload your code here.
