### ISSUE TITLE
ArrowLineString - how to...

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#648]
Hi,

I see this issue #472 but I'm not sure which version of Mapsui is this?

On my side is Mapsui 1.4.8 and I need to do something like this:
![obraz](https://user-images.githubusercontent.com/15933140/55629209-ee944380-57b2-11e9-8030-c86aa4f6e1e3.png)

I mean the arrow-lines only (the points are not important in this case, I have them already).
**How can I draw on Map the ArrowLineString?**

```
var rtfeature = new Feature { 
    Geometry = new LineString(listOfPoints),
    Styles= new IStyle[] {
    new ArrowVectorStyle
        {
            Fill = null,
            Outline = null,
            Line = {Color = Color.Red, Width = 2, PenStyle = PenStyle.UserDefined, DashArray = new float[] { 6, 4, 12, 4 } }
            BranchesOffset = 0.5,
            BranchesLength = 20,
            TiltAngle = 40
        }
    }
};
```

**Comment by lukaszpitulski** [comment]
anyone? any ideas?

**Comment by lukaszpitulski** [comment]
I'm trying to clone these
ArrowVectorStyle.cs 
LineStringRenderer.cs (+ IReadOnlyViewport, ReadOnlyPoint)
LineStringSample.cs 
from https://github.com/ScriptAndGo/Mapsui/

But still no arrows on the lines
![obraz](https://user-images.githubusercontent.com/15933140/56067141-5a117e80-5d7a-11e9-9402-8eec78130e23.png)

**Comment by lukaszpitulski** [comment]
what with this: https://github.com/ScriptAndGo/Mapsui/tree/evol/mapsui_arrowLine  ? (1.4.9?)

**Comment by charlenni** [comment]
Sorry @lukaszpitulski , but I assume, that there will no version 1.4.9. If changes happen, than in version 2.x.

**Comment by lukaszpitulski** [comment]
It's a pity but I understand it.
Is there an easy way to draw an arrow on the line in Mapsui 1.4.8?
Do I have to find a way how to do it myself?
Maybe an extra feature like a triangle without a base or two additional short lines attached to the line, hmmm ...

**Comment by pauldendulk** [comment]
Perhaps an Symbol in the shape of an arrow rotated in the right direction. You could change the offset of the symbol so that the arrow points to it's associated Point.

**Comment by softlion** [comment]
> what with this: https://github.com/ScriptAndGo/Mapsui/tree/evol/mapsui_arrowLine ? (1.4.9?)

how to refactor that so it's usable without modifying the source code ? 
Are there any extension point that can be used ?

**Comment by pauldendulk** [comment]
@softlion Perhaps the best option is to create your own ArrowStyle and SkiaArrowStyleRenderer using the  Custom Style Renderer. options https://mapsui.com/documentation/custom-style-renders.html. The code in the page might be outdated. The code of the samples in todays master is [here]( https://raw.githubusercontent.com/Mapsui/Mapsui/master/Samples/Mapsui.Samples.Common/Maps/Styles/CustomStyleSample.cs)
