### ISSUE TITLE
Midpoint (points)

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#649]
Hi,

Mapsui 1.4.8 - is in Mapsui any method to calculate(get) the middle point between two points?
Or do I have to create my own for example based on this https://www.mathsisfun.com/algebra/line-midpoint.html (ease ;) )?

Thanks!

**Comment by pauldendulk** [comment]
No there is no support for that. 

Note that for geographic coordinates the curvature of the earth could complicate this.
