### ISSUE TITLE
InfoLayer not working on Mapsui.Forms 2.0.0 beta 17

### ISSUE THREAD

**Issue by mattmiley** [Mapsui/Mapsui#650]
I can't get infolayer working in my forms project. Only testing with android right now. 

`
   private void RefreshLayer(ILayer features, IStyle style, string layerName, bool ClearCache)
        {
            var selectedLayers = MapControl.Map.Layers.FirstOrDefault(l => l.Name == layerName);
            if (selectedLayers != null)
            {
                features.IsMapInfoLayer = true;
                MapControl.Map.Layers.Remove(selectedLayers);
                MapControl.Map.Layers.Add(features);
                MapControl.Info += MapOnInfo;

//THEN THIS NEVER GETS CALLED WHILE TAPPING ON LINES
  private void MapOnInfo(object sender, MapInfoEventArgs e)
        {
            if (e.MapInfo?.Feature != null)
            {
                var item = e.MapInfo?.Feature;
                item = item;
            }
        }
`

**Comment by mattmiley** [comment]
Sorry, wrong repo to be asking this question in.

**Comment by charlenni** [comment]
I‘m not sure, if this is the case. Since 2.0 the Forms implementation is integrated into Mapsui. The the question is, what you use: a wrapper around the native MapControls or the Forms MapControl?

**Comment by radderz** [comment]
@mattmiley - This is fixed in the current master for MapControl. The Info event wasn't being called correctly. It is still not correct as of beta 25. But if another build comes out it should be fixed.

**Comment by mattmiley** [comment]
Thank you, I'll watch for the next prerelease.
