### ISSUE TITLE
Mapsui Pin Anchor Bug

### ISSUE THREAD

**Issue by taz4270** [Mapsui/Mapsui#651]
Hi, Im using your library to do some experiments, and in one of my experiments, i got a bug where anchor was not doing what was supposted, I experimented more and then i concluded it was not my fault.

### Steps i've done (with squares):
  - Added a pin (anchor: **x** & **y** at center of the square )
  - Added another pin and set the anchor for Point(0,0) (anchor: **x** at center but **y** was on top of the square - 4)

### Solution for my problem:
 - Had to set the anchor for Point(0,4)

Squares where the same with width = height = 48

I hope, i could help, with this bug report :)

### Platform:
 - Xamarin.Forms

### Testing with:
 - Android 7.0

**Comment by charlenni** [comment]
Thank you for your help.

Is it possible to see some code, how you created the pins? And perhaps a screenshot?

**Comment by taz4270** [comment]
Unfortunnatly i no longer have the code, nor have remembered to take a screenshot, But is the following,
Example:
You had 2 points, a dot which isnt modded, and a square (that is fits well, Dot at the center of the square, but once u modify the anchor, even if its at point 0,0 it will change to 4 points up, dot will be 4 points down the center)
