### ISSUE TITLE
Samples not working

### ISSUE THREAD

**Issue by mmmakka** [Mapsui/Mapsui#652]
All,

I have a problem I cannot get solved. I try to open and run the samples provided here.
Both with VS2017 and VS2019. But I cannot get it to work. VS keeps complaining that 

"This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\SQLitePCLRaw.lib.e_sqlite3.linux.1.1.11\build\net35\SQLitePCLRaw.lib.e_sqlite3.linux.targets.	Mapsui.Samples.Wpf

Anyone a solution?

Kind regards
M

**Comment by charlenni** [comment]
Did you install [sqlite-net-pcl](https://www.nuget.org/packages/sqlite-net-pcl/1.6.258-beta)?
