### ISSUE TITLE
Default point width and height prevents points of different sizes

### ISSUE THREAD

**Issue by keithpower** [Mapsui/Mapsui#655]
It appears the point sizes are set to 32x32 pixels based on the static properties SymbolStyle.DefaultWidth and SymbolStyle.DefaultHeight.  I have a requirement to have points of different sizes.

One possible solution is to have a Width and Height property on the VectorStyle class that can be used in the Xaml and Skia PointRenderer instead of SymbolStyle.DefaultWidth and SymbolStyle.DefaultHeight.

**Comment by charlenni** [comment]
Why don't you use [SymbolScale](https://github.com/Mapsui/Mapsui/blob/bbc3532196327b3a3211e0fdea8b4ff2e898bba2/Mapsui/Styles/SymbolStyle.cs#L40)? With this, you could change the size of the symbol.

**Comment by keithpower** [comment]
I had missed that property.  That will work perfect.  Thanks!
