### ISSUE TITLE
[Xamarin forms] Samples - Map empty after lock and unlock phone.

### ISSUE THREAD

**Issue by pkozak2** [Mapsui/Mapsui#656]
When I run Xamarin.Forms.Sample.Android on my phone and select one of options, then lock and unlock my phone, map is empty. There are default zoom in-out buttons etc. after unlock but map is "white box".

**Comment by charlenni** [comment]
If you move the map, is it than visible again?

**Comment by pkozak2** [comment]
@charlenni nothing changes when I swiping on map, clicking "+/-", "Current Location" buttons. "CurrentLocation" pointer is hidden.

**Comment by pkozak2** [comment]
@charlenni Have you reproduced the issue? I checked that Mapsui.Forms in version 0.2.1 is working fine and smothly than 2.0.0 beta, but beta version have nice features out-of-box.

**Comment by josesimas** [comment]
@pkozak2 I had that issue some time ago and, as far as I remember, I solved it by calling MapView.RefreshGraphics(); at the OnAppearing override of the map page.

**Comment by pkozak2** [comment]
Not helped, but... I checked on some other phones in my team, and map dissapears only on my Huawei P9 Lite. On Samsung, another Huawei map working fine.

**Comment by soomsy** [comment]
This issue occurs for me as well. Also tried the RefreshGraphics but it didn't help. Happens on both Samung J2 and J5 Prime.

**Comment by pauldendulk** [comment]
Last activity was old and it is in testing for a while. Will close this.

**Comment by charlenni** [comment]
This would happen again. This is a problem on Andrid devices with lower version numbers. The MapControl doesn't get a Refresh after appearing again on the screen. New version seems to do this automatically. So users have to call a Refresh of the MapControl/MapView after the page appear again on the screen.
