### ISSUE TITLE
Event when we drag (pan the map from one region to another) map.

### ISSUE THREAD

**Issue by RajeethKalluru** [Mapsui/Mapsui#658]
Hi Team,
Do we have any event that fires on dragging the map (panning the map when one region to another).
"Viewport.ViewportChanged" is getting fired even when we drag or pan the map.
Is there any event when we drag the map or any possibility of restrict the "ViewportChanged" event only in the case of map dragging. 
Please do needful.

Thanks,
Rajeethulla.

**Comment by charlenni** [comment]
Sorry, it is not clear, what you want.

You want an event, that is fired when dragging the map, but not fired when dragging or panning the map? That's nonsens.

So what do you want to track: dragging/panning (moving center) or anything else?

**Comment by charlenni** [comment]
@RajeethKalluru If this issue doesn't need any further attention, than it would be nice, if you could close it. Thank you.
