### ISSUE TITLE
Pinch Gesture not working

### ISSUE THREAD

**Issue by RajeethKalluru** [Mapsui/Mapsui#659]
Hi Team,
        I added below code for pinch gesture. But event did not fired when we pinch the map in android device (zoomin /zoomout). 

            var pinchGestureRecognizer = new PinchGestureRecognizer();
            pinchGestureRecognizer.PinchUpdated += OnPinchUpdated;
            _mapView.GestureRecognizers.Add(pinchGestureRecognizer);

void OnPinchUpdated(object sender, PinchGestureUpdatedEventArgs e)
        { 
        }

Please do needful.

Thanks, 
Rajeethulla.

**Comment by charlenni** [comment]
First of all, it would be helpful, if you could say, which UI of Mapsui do you use: native Android or Forms.

I assume, that you use the Forms control. If this is correct, than this control consumes all tap event that occure.

It seems, that only MapControl for Forms has a Zoomed event, but not MapView. So you have to use MapControl or use MapView.Map.Viewport.ViewportChanged event.

**Comment by charlenni** [comment]
@RajeethKalluru If this issue doesn't need any further attention, than it would be nice, if you could close it. Thank you.
