### ISSUE TITLE
[Forms / iOS (iPad only)] Map does mess up the events when the Master View in MasterDetail was shown with a slide event

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#661]
In some cases, when the app needs to long to load the data, it might be possible to fire the MasterDetail gesture for swiping in the master menu. As for now, I disable this gesture with this code on my MasterViewModel: 

```
public override void ViewAppeared()
{
    base.ViewAppeared();
    if (Device.RuntimePlatform == Device.iOS)
    {
        switch (Application.Current.MainPage)
        {
            case MasterDetailPage masterDetailPage:
                masterDetailPage.IsGestureEnabled = false;
                break;

            case NavigationPage navigationPage when navigationPage.CurrentPage is MasterDetailPage nestedMasterDetail:
                nestedMasterDetail.IsGestureEnabled = false;
                break;
        }
    }
}
```

But if the event is fired because this code was not called yet, the gestures on the Mapsui Map are messed up. In this case, the map act like it has a two finger event the whole time even when only used one. Therefore it is no longer possble to pan the map and get the info tap event. I'm not sure if this is even possible to fix within the Mapsui control but this might be a problem if the gesture for the MasterDetail is wanted even with the map on one page. 

On Android it works fine to use the swipe gesture for the master menu and still the Mapsui map is working as I would expect. Also on iPhones I was not able to reproduce this issue so it seems like this only happens on iPad's. 

**Edit:** Maybe it would already help to have a way to clear the currently registered fingers. In this case the developer has the option to reset the gesture after initialization.

**Comment by pauldendulk** [comment]
I close this one and keep Granite's issue open.

**Comment by pauldendulk** [comment]
Applied granite26's PR which will be released in beta.36.
