### ISSUE TITLE
No scroll wheel for 2.0 (UWP)?

### ISSUE THREAD

**Issue by joshminor** [Mapsui/Mapsui#666]
I'm doing a test run of upgrading from 1.3 to 2.0 on Xamarin.Forms and noticed that using scroll wheel to zoom is no longer working on UWP. Am I missing something, or is this not a feature anymore?

**Comment by Sebastian1989101** [comment]
I can also confirm this does not work with 2.0 (tested with Forms) on UWP. As a workaround it is possible to use something like this: https://forums.xamarin.com/discussion/comment/356037/#Comment_356037 and set the zoom manual through the Navigate method (you should check for min and max values).

**Comment by charlenni** [comment]
It is a problem of SkiaSharp, which hasn‘t such a event. You could find the discussion [here](https://github.com/mono/SkiaSharp/issues/449).

**Comment by pauldendulk** [comment]
The only thing we can do is wait.

**Comment by charlenni** [comment]
See #762

**Comment by joshminor** [comment]
Lol, I didn't mean to close and reopen, but thanks

**Comment by pauldendulk** [comment]
Just tested. This is fixed.
