### ISSUE TITLE
Mapsui.Providers.Feature  indexer is case sensitive

### ISSUE THREAD

**Issue by garykindel** [Mapsui/Mapsui#667]
The indexer for Mapsui.Providers.Feature uses a case sensitive dictionary with a string key.
 private readonly Dictionary<string, object> _dictionary = new Dictionary<string, object>();

Running into problems attempts to match field names in shapefile dbf files.
If this dictionary was case insensitive, problem goes away:

Recommended fix: 
private readonly Dictionary<string, object> _dictionary = new Dictionary<string, object>(StringComparer.InvariantCultureIgnoreCase);

https://github.com/garykindel/Mapsui/commit/d3bf392446faec2803d165560091c2ede3e8f968

**Comment by pauldendulk** [comment]
Could you describe the situation in which this problem occurs? Is there use input involved?

**Comment by garykindel** [comment]
In processing 1000+ shapefiles, I encountered several where field names returned by mapsui code (see below) did not match the field name string case in the dbf file itself.  Unfortunately, I lost track of the specific shapefiles with this issue.  If I can locate one of these files I'll share it.  Changing aforementioned dictionary to allow case insensitive string key fixed the issue.

Sample code to acquire feature field names.
`        [TestMethod]
        public void GetFieldNamesFromShapefile()
        {
            string shapefilePath = @"C:\DRC_Data\Arcview\CANADA\BC\BC_bedrocks_ll83.shp";
            Assert.IsTrue(File.Exists(shapefilePath));
            var wShapeFile = new Mapsui.Desktop.Shapefile.ShapeFile(shapefilePath);
            var Boundingbox = wShapeFile.GetExtents();
            var features = wShapeFile.GetFeaturesInView(Boundingbox, 1);
            var wFeature= features.FirstOrDefault();
            var wFieldNames = wFeature.Fields;
            Assert.IsNotNull(wFieldNames);
        }`

**Comment by pauldendulk** [comment]
Thanks for the sample code!

But how come Mapsui returns a different casing. Should the problem not be fixed at the source?

**Comment by garykindel** [comment]
I thought about what would be the correct solution.  I like the idea of find fields without having to know case of the field name.  Some of the other database provider solutions for foxpro and dbf often force upper case on the field names because I think back in the day dbf had to have upper case field names.  My vote is change the dictionary.

**Comment by pauldendulk** [comment]
I decided this to leave it as it was because I can see scenarios where this would be a problem and I don't want to introduce a breaking change here. I there still is a problem because of upper-casing then perhaps this could be solved in a different way.
