### ISSUE TITLE
Onclick event on mapcontrol 

### ISSUE THREAD

**Issue by FreddyBlu** [Mapsui/Mapsui#670]
Hi - Am loving using Mapsui. Thanks for all your hard work with it ! 

1.4.8 Android

Quick question - I'd like to add a feature when the user clicks on (i,e touches) the mapControl. I've tried adding an OnClick Handler but the event doesn't seem to get fired. 

And if I catch the Touch event - it does fire but there seems no easy way to tell between a Click/Move/Zoom. I guess I could check e.Event.Action for a Down and then an Up with nothing inbetween but seems cumbersome. 

Any tips please would be great thanks

**Comment by pauldendulk** [comment]
Download the source and run Samples\Mapsui.Samples.Wpf.Editing to see examples of adding/editing/deleting features.
