### ISSUE TITLE
Map without Labels

### ISSUE THREAD

**Issue by bruceo-beflex** [Mapsui/Mapsui#672]
I don't know if this is right place to ask this question. 

But, can't find the way to solve it. 

I would like to create a map without any labels which means the map has only street, not like building and store labels. 

Is it possible? or can I create a layer like this(http://tiles.wmflabs.org/osm/slippymap2.html)?

**Comment by pauldendulk** [comment]
When I click your link it loads the default osm layer. You probably referred to the 'osm no-labels' layes.  You could set up Mapsui to use this layer but it is data served by wmflabs. I don't know under what conditions this data can be used. 

The default OSM layer which is used in most of our sample has streets combined with layers baked it. It is one image. This can not be changed. So you need a custom datasource like the one of wmflabs.

The options are serve such a data source yourself (which is a lot of work if you are not familiar with this) or look for some data source that is available online, like the one from wmflabs. In that case you might need to pay for use.
