### ISSUE TITLE
MbTiles Sample for UWP Forms throws an exception 

### ISSUE THREAD

**Issue by ssombat** [Mapsui/Mapsui#674]
Getting the following Error "SQLite.SQLiteException: 'Could not open database file: .\MbTiles\world.mbtiles (CannotOpen)'" in the MBTilesSample.cs file when trying to test Mapsui.Samples.Forms.UWP

**Comment by ssombat** [comment]
I've added the following lines of code for the uwp forms MainPage.cs

"MbTilesSample.MbTilesLocation = MbTilesLocationOnUwp;
            MbTilesHelper.DeployMbTilesFile(s => File.Create(Path.Combine(MbTilesLocationOnUwp, s)));"

after InitializeComponent()

**Comment by jean-gblr** [comment]
Hello i also have the issue, problem seems to be when instantiating the new MbTilesTileSource from line 31.

path to db is good, manages to create SQLITEconnection but then the exception appears at the mbtilestilesource

**Comment by charlenni** [comment]
The problem is UWP. It isn't possible to access SQLite files, which aren't at the right place. See [here](https://stackoverflow.com/questions/35084058/uwp-app-sqlite-access-database-in-documents-library).

If you make your own app, you could copy the files at a place, where SQLite could access them. But this is beyond this sample, which is running on Android, iOS, WPF, Mac and Forms.

**Comment by jean-gblr** [comment]
> The problem is UWP. It isn't possible to access SQLite files, which aren't at the right place. See [here](https://stackoverflow.com/questions/35084058/uwp-app-sqlite-access-database-in-documents-library).
> 
> If you make your own app, you could copy the files at a place, where SQLite could access them. But this is beyond this sample, which is running on Android, iOS, WPF, Mac and Forms.

Will explore this, thank you for your answer. Will tell when i get to implement it.

**Comment by charlenni** [comment]
I corrected this. See #923. 

If you don't want to wait, replace it by yourself in the samples file.

**Comment by jean-gblr** [comment]
Thanks for your help, it has now been resolved in my project
