### ISSUE TITLE
[Forms / Droid] Map getting blank after App sleep mode

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#677]
**Test Environment(s):** 
1. Google/Intel HAXM Emulator (Nexus 5X Template) with Android 6.0 API 23
2. Google/Intel HAXM Emulator (Nexus 4 Template) with Android 4.4 API 19
3. Google/Intel HAXM Emulator (Nexus 6 Template) with Android 5.1 API 22
4. Google/Intel HAXM Emulator (Pixel Template) with Android 9.0 API 28

Upon all test enviroments, this bugs happend with 1-3 but not with 4. From the Mapsui Sample I used the "MbTiles" Sample to test it. 

As soon as the app enters the sleep mode with the Mapsui map open and then resuming the app, the map is getting blank/empty. The event for panning and zooming is still triggered but not visual visible. Also a `Refresh()` won't reactivate the Map control (and neither does the recreate of all layers). 

Here is a small video about the issue: 
https://cloud.kruse-familie.eu/index.php/s/EKpnLc9j9WuFj0h

**Comment by pauldendulk** [comment]
Thanks a lot for the video. On my Samsung I only get a blank screen that redraws after panning. We should try to reproduce it on the emulator. This is probably related to the Android lifecycle. https://developer.android.com/guide/components/activities/activity-lifecycle. I do not have much experience in the area.

**Comment by pauldendulk** [comment]
This problem was not reported anymore with a later version. Perhaps it was related to the skiasharp version we used at the time.
