### ISSUE TITLE
[Xamarin Forms] Question : How can I detect if a point is inside or outside a circle?

### ISSUE THREAD

**Issue by Jesrigt** [Mapsui/Mapsui#678]
Hello, I would like to know if there is a method that can detect if a point (in this case the GPS) is inside or outside a circle (geofencing or geofencing).

Something similar to this code that is for Android (Java)
```
float[] disResult = new float[2];

Location.distanceBetween( pos.latitude, pos.longitude,
                          circle.getCenter().latitude, 
                          circle.getCenter().longitude, 
                          disResult);

if(disResult[0] > circle.getRadius()){
    Log outside
 } else {
    Log inside
 }
```
Computes the approximate distance in meters between two locations, and optionally the initial and final bearings of the shortest path between them. Distance and bearing are defined using the WGS84 ellipsoid.

The computed distance is stored in results[0]. If results has length 2 or greater, the initial bearing is stored in results[1]. If results has length 3 or greater, the final bearing is stored in results[2].

Parameters
--
**startLatitude | double:** the starting latitude
**startLongitude | double:** the starting longitude
**endLatitude | double:** the ending latitude
**endLongitude | double:** the ending longitude
**results | float:** an array of floats to hold the results

I've been looking at the documentation but I have not found something similar to help me implement it.

If you have any ideas, I would appreciate it.  :)

**Comment by pauldendulk** [comment]
To know if a point is within a circle it is enough to check if the distance to the center is less than the radius (no fancy geometry). So what you need is a method to calculate the distance between two points in latlon (wgs84, https://epsg.io/4326). There is no such method in Mapsui right now but you should be able to google one. This is the first thing I hit upon: https://stackoverflow.com/a/11172685/85325

**Comment by Jesrigt** [comment]
Thanks @pauldendulk  for the information, I will investigate a little more what you comment.

**Comment by Jesrigt** [comment]
This is the code I use and it has served me very well :)


         public static double Distance(double Lat_gps, double Long_gps)
        {

            var lat1 = Lat_gps;
            var lon1 = Long_gps;
            var lat2 = Lat_geo;
            var lon2 = Long_geo;

            var R = 6378.137; // Radius of earth in KM
            var dLat = lat2 * Math.PI / 180 - lat1 * Math.PI / 180;
            var dLon = lon2 * Math.PI / 180 - lon1 * Math.PI / 180;
            var a = Math.Sin(dLat / 2) * Math.Sin(dLat / 2) + Math.Cos(lat1 * Math.PI / 180) * Math.Cos(lat2 * Math.PI / 180) * Math.Sin(dLon / 2) * Math.Sin(dLon / 2);
            var c = 2 * Math.Atan2(Math.Sqrt(a), Math.Sqrt(1 - a));
            var d = (R * c) * 1000;
            return d;

        }

**Comment by pauldendulk** [comment]
@Jesrigt Thanks for giving this back!

**Comment by kean-haughty** [comment]
@JesrigPineda https://stackdev.space/questions/discovering-the-distance-between-two-points-in-android-using-java-code

**Comment by pauldendulk** [comment]
The method to calculate the distance in meters based on lanLon coordinates is now in Mapsui:

https://github.com/Mapsui/Mapsui/blob/main/Mapsui/Utilities/Haversine.cs
