### ISSUE TITLE
WPF - Non scalable Labels

### ISSUE THREAD

**Issue by vincenzoxx** [Mapsui/Mapsui#679]
Hello. I couldn't find a way to draw non scalable Labels or Symbols. Is it possible? Is there any guide to do so?

**Comment by pauldendulk** [comment]
There are some samples on symbols and labels under the 'symbols' sample set. What are you looking for?

![image](https://user-images.githubusercontent.com/963462/61952764-0cc9bd80-afb5-11e9-87f8-267a70811416.png)

**Comment by vincenzoxx** [comment]
Is possible to create a custom border for labels? I would like to have possibility to do something like that: black border with gray background and white text with black halo.
Is possible to create a line that goes from the point to the label? 
![image](https://user-images.githubusercontent.com/50289647/61990494-09c8de80-b042-11e9-9ae3-3d3177592bed.png)
I couldn't find a way, so I'm here asking if is possible to have the closest effect. 
And also I was wondering what collision allows you to do? Is possible to move a label that is under another one in a place that allows user to read both of them?
Thank you.

**Comment by pauldendulk** [comment]
Sorry, there is no option for custom border, and there is no logic for collision. It is probably possible to create your own LabelLayer which collection detection, but it will not be easy.
