### ISSUE TITLE
MapsUI.Forms - Remove whitespace around the map

### ISSUE THREAD

**Issue by thandunaresh** [Mapsui/Mapsui#680]
Hello, 

I am using MapsUI.Forms.

I can see whitespace around the map when I try to move around.

Is there any way I can remove the whitespace around the map and just set the map extents as the boundaries/limit.

I have tried to use 'ViewportLimiterKeepWithin' but not working as expected, probably I maybe doing something wrong.

Thanks,
Naresh

**Comment by pauldendulk** [comment]
ViewportLimiterKeepWithin should be the right solution. Does the sample work for you? (Special -> Keep Within Extents). You need to explicitly set the extents that you want to limit to.
