### ISSUE TITLE
can't build Mapsui.Forms

### ISSUE THREAD

**Issue by ShariatPanah** [Mapsui/Mapsui#681]
I can't build the Mapsui.Forms project (the sample project you provided) its full of errors, i can't seem to figure out how to make it work, please help

**Comment by charlenni** [comment]
You want to compile Mapsui.Forms or a project build with Mapsui.Forms?

What errors do you get?

**Comment by ShariatPanah** [comment]
sorry it was my bad, i fixed it thanks
