### ISSUE TITLE
Update SkiaSharp library to 1.68.0

### ISSUE THREAD

**Issue by galadril** [Mapsui/Mapsui#689]
Can you maybe look into updating the SkiaSharp dependency in this library to 1.68.0?
Mapsui 2.0.0-beta.25 -> SkiaSharp (>= 1.60.0 && < 1.68.0).

**Comment by charlenni** [comment]
Paul did this, but encountered, that it is much slower than the older one. So he goes back.

I don‘t find the issue.

**Comment by galadril** [comment]
ok thanks for the response

**Comment by charlenni** [comment]
Found it: #643 at https://github.com/Mapsui/Mapsui/issues/643
