### ISSUE TITLE
It is possible to save the map display on screen with mapsui ? 

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#690]
I need for a project to save a part of map. 
I search a lot and I didn't found if it is possible to save the part of the map which is display on screen ?

**Comment by pauldendulk** [comment]
If it is just the image of the map you could like at the test file 'MapRendererTests.cs'. It shows how you can save a map extent as an image. 

```c#
var bitmap = new MapRenderer().RenderToBitmapStream(viewport, map.Layers, map.BackColor);
```

There is no support for saving the geometries themselves.

**Comment by pauldendulk** [comment]
btw, The features are loaded asynchronously, so when saving features it could happen that you save before the features are loaded and your image will be blank. In some cases you need to wait and perhaps you also need to trigger the loading of features. If you save while you see the image on your screen things will be fine.

**Comment by xFoRdeX** [comment]
@pauldendulk Thank's for you fast answer. 
And with a bitmap, it is possible to load a map in offline from this bitmap ?

**Comment by pauldendulk** [comment]
You can not load a map from the bitmap. Although it is possible to load any image as a feature in the map, but this is probably not what you want.

bitmap is not null in the unit tests. Work from there.

**Comment by SebastianKruseWago** [comment]
@xFoRdeX If you want to make the map offline available, you have to use local mbtiles file(s). On iOS (and macOS/tvOS?) you can use nested On-Demand Resources for this and on any other platform you have to host the mbtiles on your own server. I would not include them to the app directly, otherwise the user had to load them with each update. 

There is also a sample how to consume the mbtiles file(s).

**Comment by xFoRdeX** [comment]
@SebastianKruseWago  Thank's for your answer. 
I found an other issue about this but Idon't really understand how to use these mbtiles files. 
Can I save the "state" of my map with this ? How can I use this files to use the map offline ?

**Comment by SebastianKruseWago** [comment]
@xFoRdeX If you have the mbtiles file localy it is also offline available. You simply don't use an online TileSource you use a MbtilesTileSource (which is available through the BruTiles.MbTiles NuGet package). Anything you need to know is in this sample as already mentioned: https://github.com/Mapsui/Mapsui/blob/989b713b591468bbf5f3edc398cb552851799a9f/Samples/Mapsui.Samples.Common/Maps/MbTilesSample.cs

If you mean the last position, zoom, etc. with "state" - you can easily code this on your own.
