### ISSUE TITLE
Strange behaviour when using an AnimatedNavigator on MouseWheel Event

### ISSUE THREAD

**Issue by isra60** [Mapsui/Mapsui#691]
I am testing my app with the new AnimatedNavigator but I set an Animated Navigator to the MapControl. The Zoom with MouseWheel is not working as I expected. The does not centered around the mouse position as if works with standard Navigator.
The MouseWheel Event has this.

            
```
 // Some cheating to trigger a zoom animation if resolution does not change.
             // This workaround could be ommitted if the zoom animations was on CenterX, CenterY and 
             Resolution, not Resolution alone.
           // todo: Remove this workaround once animations are centralized.              
                

Navigator.CenterOn(new Geometries.Point(Viewport.Center.X + 0.000000001, 
             Viewport.Center.Y + 0.000000001));

             //Navigator.ZoomTo(_toResolution);
             StartZoomAnimation(Viewport.Resolution, _toResolution);

```
Removing the StartZoomAnimation line and adding Navigator.ZoomTo does not solve the problem.

**Comment by pauldendulk** [comment]
At the moment the AnimatedNavigator can not be used in this way. What are you trying to achieve?

**Comment by isra60** [comment]
I want the standard behaviour of Mouse Wheel Zoom. To center the zoom animation on the mouse position. I think this function is not animated.

         `public void ZoomTo(double resolution, Point centerOfZoom)
        {
            // 1) Temporarily center on the center of zoom
            _viewport.SetCenter(_viewport.ScreenToWorld(centerOfZoom));

            // 2) Then zoom 
            _viewport.SetResolution(resolution);

            // 3) Then move the temporary center of the map back to the mouse position
            _viewport.SetCenter(_viewport.ScreenToWorld(
                _viewport.Width - centerOfZoom.X,
                _viewport.Height - centerOfZoom.Y));

            Navigated?.Invoke(this, EventArgs.Empty);
        }`

**Comment by pauldendulk** [comment]
You can get the standard mouse behavior with the standard setup. What are you trying to achieve by using the AnimatedNavigator. You can always make use of the AnimatedNavigator from code.

**Comment by isra60** [comment]
But how? If I leave the standard Navigator in MapControl ?? I have to set the AnimatedNavigator each time ??

**Comment by pauldendulk** [comment]
Where did you get the AnimatedNatigator code from?

**Comment by isra60** [comment]
From master branch... is that what do you mean?

**Comment by pauldendulk** [comment]
You could Instantiate a separate AnimatedNavigator with the Map and Viewport of the MapControl and call it's methods from a zoomin/zoomout button, for example.

```csharp
_navigator = new AnimatedNavigator(mapControl.Map, mapControl.Viewport);
```

```csharp
void OnZoomToButtonClick()
{
   _navigator.NavigateTo(newCenter, newResolution);
}
```

**Comment by isra60** [comment]
I tried with that way but it's also necessary to attach the Navigated Event from Navigator to MapControl in order to refresh the Map canvas... So a lot of dirty code.  It would be a better way to fix the problem with the zoom with mouse wheel, Maybe using a Standar Navigator for this method and using a Animated Navigator for the rest of the methods..

Tomorrow I will look for the difference of the
`public void ZoomTo(double resolution, Point centerOfZoom)`

between the two Navigators..

**Comment by isra60** [comment]
The problem was this line on MouseWheelHandler.

`Navigator.CenterOn(new Geometries.Point(Viewport.Center.X + 0.000000001, 
             Viewport.Center.Y + 0.000000001));
`

**Comment by pauldendulk** [comment]
That hack was added to trigger an animation when the resolution changed but not the center. With no change in center there would be no refresh. By slightly altering the center the refresh would be triggered. Maybe it's time to think about a proper solution. 

If you remove this line your problems are solved? 

I have to check how that will affect the initial problem.

**Comment by isra60** [comment]
Yeah. Everything seems to work
