### ISSUE TITLE
Crash while navigating to a bounding box on startup

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#692]
(Mapsui1.48)

Hi @pauldendulk and team, I came across this today on a production build. I'm attaching an StackTrace screenshot.

On a testing machine, we determined that this issue is reproducible when, at the System Settings level, you swap the **Decimal Symbol** period ('.') and **Digit Grouping Symbol** comma ('.')

For us, we were crashing while navigating to a bounding box on startup.

![image](https://user-images.githubusercontent.com/12670350/64300244-f9edc580-cf30-11e9-9e97-57021dac1d02.png)

![image](https://user-images.githubusercontent.com/12670350/64299849-87c8b100-cf2f-11e9-9cae-570708e7f965.png)

![image](https://user-images.githubusercontent.com/12670350/64299686-f5c0a880-cf2e-11e9-913f-604560b5b1c4.png)

_Originally posted by @blwhttngtn in https://github.com/Mapsui/Mapsui/issues/97#issuecomment-528131678_

**Comment by pauldendulk** [comment]
I am not aware of Mapsui doing any string parsing so I assume the change is settings affects your code and my guess is that as a consequence some extreme value is set in Mapsui. How does the change in setting affect the value of DistanceBetweenCorners?

**Comment by blwhttngtn** [comment]
_Note that we're using BruTile and BruTile.MbTiles 2.0.2, which is outside of the dependency of Mapsui 1.48, but I've been able to reproduce this 1:1 with BruTile and BruTile.MbTiles 1.0.3._

Somehow, setting the BoundingBoxBottomLeft Point in the image below results in a NaN Latitude value despite the X Y values passed-in to the SphericalMercator.FromLonLat being valid.

![image](https://user-images.githubusercontent.com/12670350/64369183-a59a2280-cfd0-11e9-8562-75f11678ac3c.png)

Navigating to a bounding box (in the original post) with this invalid point as its MinPoint results in this:

![image](https://user-images.githubusercontent.com/12670350/64368367-04f73300-cfcf-11e9-865b-0d918219897a.png)

Then, attempting to zoom-out from the resultant position using the mouse wheel produces this:

![image](https://user-images.githubusercontent.com/12670350/64368855-0117e080-cfd0-11e9-8716-80c39d16eff2.png)

**Comment by charlenni** [comment]
Is it possible to provide the _xLeft and _yBottom values? Could it be, that you interchanged lat and lon?

**Comment by charlenni** [comment]
Did you solved the problem? If yes, please close the issue.

**Comment by pauldendulk** [comment]
>  ... and BruTile.MbTiles

ah, the problem might be the parsing of fields in the MbTiles file.

**Comment by pauldendulk** [comment]
When I adjust my system settings as you describe and run the BruTile MbTiles unit tests they still read the extend correctly. 

Now I think a more likely explanation is that you use incorrect values as input to FromLonLat which causes an overflow. Could they be SphericalMercator coordinates instead of LonLat? What are the values of _xLeft and _yBottom? 

Valid input values:
- Latitudes range from -90 to 90.
- Longitudes range from -180 to 180.

I will close this for now. Please reopen if you have a sample with which we can reproduce this problem.

**Comment by blwhttngtn** [comment]
@pauldendulk @charlenni thank you for your interest and your help. I'm going to disappoint you by including this image... the test machine which had the decimal/digit-grouping symbol switched was interpreting our sample data lat/lon values as very large or very small values because of the switch. I'm sorry! 

Obviously at the object, I've gone ahead and added range validation tests so that no lat/lon values could be saved outside of the valid ranges: -90 < lat < 90 and -180 < lon < 180.'

Thanks guys! Sorry

![image](https://user-images.githubusercontent.com/12670350/65396766-c5ff0680-dd5e-11e9-90fa-cdd286593fd1.png)

**Comment by pauldendulk** [comment]
Okay, let's investigate further. We will need some way to reproduce this though. Could you somehow create a sample for this? Perhaps fork the Mapsui repo and adjust some of the samples to reproduce this.

**Comment by charlenni** [comment]
@pauldendulk I assume, that you misunderstand it. For me, the data was wrong, Mapsui is ok and the issue could be closed. Isn’t that right?

**Comment by pauldendulk** [comment]
Ohhhhh! You are right. Did not have my glasses on.

**Comment by blwhttngtn** [comment]
@pauldendulk @charlenni exactly. Thanks again! @pauldendulk your comment actually led to me to the conclusion. Much appreciated.
