### ISSUE TITLE
Error with MapClick event : Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#693]
I'm actually using the MapClick event and I associate to it the creation of a pin. It works perfectly on Android but on UWP, i've got the following error : 
`Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD`
It is a known issue about UWP ? 
Thank's you

**Comment by xFoRdeX** [comment]
Still no one know something about this issue ? I search a lot and I didn't found something that resolve my problem...

**Comment by pauldendulk** [comment]
@xFoRdeX It would help us a lot if you could create a sample to reproduce this. Perhaps you can fork the Mapsui repository and modify the sample project to reproduce your problem.

**Comment by xFoRdeX** [comment]
For people who had the same issue : I resolve that by set the "IsCalloutVisible" property of pin at true

**Comment by pauldendulk** [comment]
I assume this is related to the callout issue that should now be fixed.
