### ISSUE TITLE
[Xamarin.Forms] Call UpdateMyLocation methods frequently cause a 100% cpu load

### ISSUE THREAD

**Issue by antoineloos** [Mapsui/Mapsui#698]
First of all thank you for your great job on this framework, it's fantastic. 

I have an issue when I try to refresh MyLocation property by calling mapView.MyLocationLayer.UpdateMyLocation methods.
My app is connected to an external device that provide an api to retrieve GPS position and I try to call this API each 300ms and then refresh MyLocation. 
I also use the MyLocationFollow mode and MbTilesProvider . So with this, I obtain a 100% CPU load on my device (Galaxy tab active2 with Android 7.1) and the result is a bit laggy but it does not crash. 
 
I can't produce repro sample now but I guessed where the error is located : 
In MyLocationUpdate method code there is this line
`animation.Commit(mapView, animationMyLocationName, 100, 3000, finished: (s, v) => mapView.Map.RefreshData(mapView._mapControl.Viewport.Extent, mapView._mapControl.Viewport.Resolution, true));` 

In xamarin documentation of animation.commit [https://docs.microsoft.com/fr-fr/dotnet/api/xamarin.forms.animation.commit?view=xamarin-forms](url) there is the rate parameter which is 100 frame per second here, and the duration which is 3000ms in this case. 

Is it possible to make those parameters accessible in the MyLocationLayer object in any way ? 
I think that if i set the rate of the animation under 30 fps it could be fix the problem. 

I will try to make a repro project but I'm not sure to be able to achieve that soon.

Thanks a lot.

**Comment by pauldendulk** [comment]
The UpdateMyLocation method start a new animation on any change. This could cause a performance problem when many updates are called. A better solution might work with just a single animation class, later calls to UpdateMyLocation could then alter the animation that is in progress without creating a new one. 

Something like that is used for the mouse wheel animation in the WPF MapControl (Mapsui.UI.Wpf.MapControl.cs). A mouse wheel event will cause a call to MapControlMouseWheel. At the bottom of that method is a call to
```csharp
StartZoomAnimation(Viewport.Resolution, _toResolution);
```
In that method an existing animation is stopped and a new animation is started from the current resolution to the new target resolution.

```csharp
private void StartZoomAnimation(double begin, double end)
{
    _zoomStoryBoard.Pause(); //using Stop() here causes unexpected results while zooming very fast.
    _zoomAnimation.From = begin;
    _zoomAnimation.To = end;
    _zoomStoryBoard.Begin();
}
```

**Comment by antoineloos** [comment]
Thank you for your anwser, I think it's a better option than I tryed to do with the frame rate of the animation. So I will test it as soon as possible. Sadly I'm stuck with another issue on mapsui projection right now, i will open another issue. I'll let you know.  Thanks a lot

**Comment by antoineloos** [comment]
Hi @pauldendulk,
I finally found a solution, I've replace UpdateMyLocation call by calling CenterOn from AnimatedNavigator. It's not very smooth but that ok for now and I will optimize that as soon as possible. 
Thanks for all
