### ISSUE TITLE
Collision for LabelStyle don't working

### ISSUE THREAD

**Issue by TarasParashchuk** [Mapsui/Mapsui#702]
Hello guys!
I read issue #383 and #536. if I understand right, I must create own render Label with collision.
But i wanna to know maybe there is new information about issue or example (Mapsui for Xamarin.Forms).
Thanks all for feedback.

**Comment by pauldendulk** [comment]
That is correct. This still needs to be implemented and perhaps some fundamental changes need to be made to make this possible.
