### ISSUE TITLE
TileLayer - all tiles in MemoryCache

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#704]
Hi,

referring to https://github.com/BruTile/BruTile/issues/106 

How can I get all tiles cached in TileLayer (Viewport)?

From this MemoryCache.TileCount I know how many there are, but I don't know what the max and min indexes of columns and rows are (to use in MemoryCache.Find).

Maybe there is a way to get the col/row indexes in the Map.Viewport (.Extent) ?

Thanks,
Lukasz

**Comment by lukaszpitulski** [comment]
I'm doing:

`var tileCount = tileLayer.MemoryCache.TileCount;
var minCol = 0;//?
var maxCol = tileCount;//?
var minRow = 0;//?
var maxRow = tileCount;//?
var zoomLevel = "4";

for (int colIdx = minCol; colIdx < maxCol; colIdx++)
for (int rowIdx = minRow; rowIdx < maxRow; rowIdx++)
  {
    var feature = tileLayer.MemoryCache.Find(new BruTile.TileIndex(colIdx, rowIdx, zoomLevel));//above 8 (zoomLevel>8) it's very long process

    if (feature != null)
    {
        //using the tile from MemoryCache
    }
  }`

It would be nice to have something like this:
`var allTiles = baseLayer.MemoryCache._bitmaps;`

**Comment by lukaszpitulski** [comment]
I need this
`new System.Collections.Generic.Mscorlib_DictionaryDebugView<BruTile.TileIndex, Mapsui.Providers.Feature>(tileLayer.MemoryCache._bitmaps).Items` :(

**Comment by lukaszpitulski** [comment]
//using the tile from MemoryCache
```
var imgData = ((Mapsui.Geometries.Raster)feature.Geometry.Clone()).Data;
imgData.Position = 0;

using (System.IO.FileStream file = new System.IO.FileStream("tile_" + zoomLevel + "_" + colIdx + "_" + rowIdx + ".png", System.IO.FileMode.Create, System.IO.FileAccess.Write))
    imgData.CopyTo(file);

imgData.Dispose();
imgData = null;
```

**Comment by charlenni** [comment]
You want to create a cache on the file system? Be careful, the most tile providers will not allow this.

I would say, the suggested approach with the own MemoryCache would be the best.

**Comment by lukaszpitulski** [comment]
I know that they may not allow this (a ban, block IP etc.). This will be a temporary, occasional, experimental solution. Not for permanent use. I'm careful. ;)

"own MemoryCache"... as System.Collections.Generic.Dictionary<BruTile.TileIndex, Mapsui.Providers.Feature>... I'm not sure how to do this... inherit TileLayer in own TileLayer?

Thanks.

**Comment by charlenni** [comment]
The only thing, you have to do, is, when creating the TileProvider/TileSource for your layer, to add your own cache. That’s it.

**Comment by lukaszpitulski** [comment]
Sorry, I don't know (yet) how to do this. Any sample?

**Comment by lukaszpitulski** [comment]
```
		public TileLayer CreateTileLayer()
		{
		  TileLayer tileLayer = new TileLayer((ITileSource) CreateTileSource(), 200, 300, 2, (IFetchStrategy) null, (IRenderGetStrategy) null, -1, -1);
		  return tileLayer;
		}

		private HttpTileSource CreateTileSource()
		{
		  return new HttpTileSource((ITileSchema) new GlobalSphericalMercator(), "https://some_provider.png", (IEnumerable<string>) new string[3]
		  {
			"a",
			"b",
			"c"
		  }, (string) null, "name", (IPersistentCache<byte[]>)new MemoryCache2<byte[]>(), (Func<Uri, byte[]>) null, OSMAttribution);
		}
```

**Comment by lukaszpitulski** [comment]
It seems that GetTileInfos is the solution I needed. :)

var area = MapControl.Map.Viewport.Extent;
var theTails = tileLayer.TileSource.Schema.GetTileInfos(new BruTile.Extent(area.MinX, area.MinY, area.MaxX, area.MaxY), zoomLevel).Select(a => a.Index);

Without own MemoryCache<byte[]>. but PersistentCache in TileSource of TileLayer can't be null.

**Comment by charlenni** [comment]
But that only provides the tiles currently visible, not all tiles, that are in the MemoryCache.

**Comment by lukaszpitulski** [comment]
And this is exactly what I need, visible tiles in current view (Viewport.Extent).

Not all tiles from MemoryCache, only from specific area&zoom on demand.

Sorry, it seems my question was not clear enough.

**Comment by lukaszpitulski** [comment]
BTW

> Be careful, the most tile providers will not allow this.

We use own GeoServer and don't cache tiles from web providers (OSM etc.).
Sometimes a local map is required (on the same machine where is app, without lan, without internet access) and the map doesn't have to be of the whole world. So we need create an offline map of a part of the glob, some specific area and provide it to the app (e.g. mbtiles).
