### ISSUE TITLE
Position of LabelStyle 

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#705]
I create a feature which is a line between 2 pins and I want to place a label (using a LabelStyle) at the right of my second pin. 
Can i choose the position of my Label with x-y position ?

**Comment by pauldendulk** [comment]
Mapsui only has labels on points. What you could do is to add the location of the second pin as an point with no style (invisible) and add a label to it using 'LabelStyle.HorizontalAlignmentEnum.Left'. There are some samples in LabelsSample.cs.

**Comment by xFoRdeX** [comment]
Thank's Paul, that's works great !
