### ISSUE TITLE
Get size text (width and height) from LabelStyle

### ISSUE THREAD

**Issue by TarasParashchuk** [Mapsui/Mapsui#707]
Hi, guys.
I must get the width and height dimensions for the label, because I want to use these properties when looking for label collisions.

**Comment by pauldendulk** [comment]
Could you explain a bit more what the current code is that you are working from? 

In Mapsui.Rendering.Skia.LabelRenderer.cs there is a Rect used for drawing at line 104. This information should get to you, but right now a don't have a plan for how this should work. Something similar happens on feature info. We use the size of the symbol there. Maybe we should do the same here, the size of the label is the size of the feature. If you use just one style on your feature that would work.
