### ISSUE TITLE
[help?] Polylines that go from USA -> Australia look weird

### ISSUE THREAD

**Issue by galadril** [Mapsui/Mapsui#720]
Polylines that go from USA/Mexico/etc -> Australia look weird Or am i doing something wrong??

![afbeelding](https://user-images.githubusercontent.com/14561640/66818414-94342680-ef3d-11e9-9ebc-22e6fc897b67.png)

**Comment by pauldendulk** [comment]
Is it possible to use the LineString geometry instead? Does it have a similar appearance? 

@charlenni What kind of functionality does the polyline have that a linestring does not? In other words, what would we need to add to linestrings to make it equivalent?

**Comment by charlenni** [comment]
@pauldendulk Polyline is only a wrapper around a LineString. Xamarin.Forms.Maps calls it Polyline, you calkl it LineString. 

@galadril Could you provide the code for this problem?

**Comment by galadril** [comment]
I've tried to make a test example with a polyline that goes from south america to australia. It doesn't look as weird as my example above, but the route never ends in australia
https://github.com/galadril/MapsuiTestApp

![Screenshot_2019-10-20-12-16-39-725_com companyname mapsuiapptest](https://user-images.githubusercontent.com/14561640/67158065-c970b800-f333-11e9-90e6-e2ca3495acac.png)
![Screenshot_2019-10-20-12-16-44-900_com companyname mapsuiapptest](https://user-images.githubusercontent.com/14561640/67158066-c970b800-f333-11e9-8d31-67e9dce8e505.png)

**Comment by charlenni** [comment]
Looking at your code, I would say the following Positions aren't correct
````
new Position(-9.761041, -181.567089), 
new Position(-29.366861, -212.937655), 
new Position(-25.133358, -231.776641)
````
The longitudes are below -180°, which isn't defined and all set to -180°. Australia is around -140°.

**Comment by charlenni** [comment]
The problem hier is, how to draw a LineString from say W179° to E179°? In the moment it is always drawn from W179° over E0° to E179°, but I assume, you would draw it direct from W179° over E180° to E179°. Correct?

**Comment by charlenni** [comment]
Are here any news?
