### ISSUE TITLE
Should IXamlWidgetRenderer interface be public?

### ISSUE THREAD

**Issue by mhardingham** [Mapsui/Mapsui#722]
IXamlWidgetRenderer doesn't appear to be public like ISkiaWidgetRenderer, is there a reason for this?

**Comment by pauldendulk** [comment]
Well, I am not even sure if it was a conscious decision, but at some point the WPF renderer will probably be deprecated, so it is not something we would like to stimulate. Is there a reason for you to use WPF instead of skia?

**Comment by pauldendulk** [comment]
I added a comment in the code. It was intended this way in retrospect 🙄
