### ISSUE TITLE
Resizing wpf MapControl takes 100% of one core, lots of GC and freezing

### ISSUE THREAD

**Issue by capsicumDreams** [Mapsui/Mapsui#726]
Latest version 68ade75d doesn't like resizing wpf MapControl at all..
I had a look, but am not familiar enough with the code to tack down why..

**Comment by pauldendulk** [comment]
Thanks for reporting. 

Did this work for you in previous versions or are you a new user?

**Comment by capsicumDreams** [comment]
..new to V2.x

**Comment by pauldendulk** [comment]
I can not reproduce this with a couple of samples I tried. Are you testing this in your own data? Could it depend on some specific kind of data that you use? Or some use of the refresh mechanism that doesn't work will with v2?

**Comment by capsicumDreams** [comment]
I'm not doing anything clever :)
Just running the sample app, using either the Skia or Wpf renderers.
As soon as I full-screen the app, it stutters/freezes.

**Comment by pauldendulk** [comment]
I need to reproduce the error and so far I can not. I need to understand the difference of our situations. Below a gif of a simple resize with the cpu activity on the right. Do you get high cpu in this situation?

![cpu](https://user-images.githubusercontent.com/963462/68284023-f4ba0d80-007c-11ea-92a0-29a1c96315e0.gif)

**Comment by capsicumDreams** [comment]
I definitely can't do that!

![animation](https://user-images.githubusercontent.com/2741536/68383592-3d91c500-0156-11ea-82b2-90a52fc579a7.gif)

**Comment by capsicumDreams** [comment]
Apologies! I screwed up pulling your latest changes in Git.
It's fantastic - thanks for all your development.
I hope you didn't spend much time on this spurious issue.

**Comment by pauldendulk** [comment]
No problem. You took the effort to report an issue, this is a good thing, and you did follow up testing to wrap it up.
