### ISSUE TITLE
Xamarin Forms Shell : Issue with Sliding out menu over map not releasing touch point

### ISSUE THREAD

**Issue by Granite26** [Mapsui/Mapsui#727]
When using the map in an app using Xamarin.Forms.Shell,  sliding out the map from the side causes the menu to load, but the map retains the touch point.  Because the map is no longer the active control, it's not catching the finger up event.

This causes the touch point to 'stick', and returning to the map (via closing the slide out menu) to rotate around the old touch when a new drag is started (rather than move the map, as expected.)

Possibly related to #661

**Comment by Granite26** [comment]
The ability to manually reset the touch points would resolve this.

Looking at the code, I notice that 'touch cancelled' has a remove touch result, but 'touch exited' does not. (MapControl.cs ln ~225).  I'm not familiar enough with the paradigm to know if changing that would have unintended side effects.

**Comment by pauldendulk** [comment]
Thanks for the bug report. Manual cleaning would seem a fairly easy fix. 

You suggest to add _touches.Remove(e.Id); on line 227 of the forms MapControl. You don't know if it has sided effect, but do you know if it is actually called in your situation?

Also, it would be even better if this could be implemented stateless.

**Comment by Granite26** [comment]
No, I don't know.  I tried setting up a build to test the ln 227 addition but couldn't get the edited DLLs working in my solution (Ignorance on my part, I'm sure).  After the touch starts, the menu is sliding out under the finger.  I'm _assuming_ that this triggers an exit event, but I don't know.  These events are on the MapControl, which is internal to the MapView, and I can't put hooks into it.  It doesn't look like the MapControl.OnTouch event (ln ~108) is exposed through the MapView either, and there aren't MapView HandlerTouchEntered / HandlerTouchExited events.

I advocate a manual clear option only because it'll enable any similar issues to be fixed by end-users until the correct fix is put it.

**Comment by Granite26** [comment]
I put in #728 to surface the events and add the clear.  I'll be able to answer your question with that.  It seems like a pretty safe change.

I did put in the 227 addition, but I wouldn't be upset if you wanted (me) to pull that out until further testing could be done.

**Comment by pauldendulk** [comment]
Perhaps this needs to be fixed.

**Comment by pauldendulk** [comment]
Applied @Granite26's  PR which will be released in beta.36.
