### ISSUE TITLE
Check if tiles in view have finished loading?

### ISSUE THREAD

**Issue by Murded** [Mapsui/Mapsui#730]
I have a WPF project that setups and displays a map using open street maps. 

Here's the code I have to setup the OpenStreetMap layer
```
 mapControl.Map.Layers.Add(OpenStreetMap.CreateTileLayer());
```

and further down the code I'm using WPF's rendertargetbitmap class to save the map control as a bitmap

```
RenderTargetBitmap rtb = new RenderTargetBitmap((int)mapControl.RenderSize.Width, (int)mapControl.RenderSize.Height, 96d, 96d, System.Windows.Media.PixelFormats.Default);
```

which works fine however the application must operate in circumstances where a stable internet connection may not be guaranteed which can lead to some weird results if the map is saved while tiles are still being loaded.

I'm wondering if there is a way to check if the tiles that are currently in view (At the current zoom level) have been loaded ?

I saw that in the documentation that [TileFetcher](http://mapsui.com/api/Mapsui.Fetcher.TileFetcher.html) has a NumberTilesNeeded property.  I'm just wondering how I would access this TileFetcher object using my current setup.

Thanks in advance

**Comment by pauldendulk** [comment]
The TileLayer has a Busy boolean that should be set to false when all tiles are loaded.

**Comment by Murded** [comment]
> The TileLayer has a Busy boolean that should be set to false when all tiles are loaded.

Do you know if this is just tiles in view or everything that it's currently trying to load?

For example if I move around alot (which pressumably causes alot of tiles to be loaded) would the Busy variable be true until every tile has been loaded (Even those now outside of my view)?

**Comment by pauldendulk** [comment]
If you stop panning the tiles in view will be fetched (and some tiles in that view at a higher level) and the tiles for which the request has already started will be finished. But this should not take a long time at all. It it does it there might be something wrong with the Busy boolean or the fetch strategy.

btw, for your scenario you might also want to apply a different fetch strategy, one where only the tiles in view are fetched at the view's level. The constructor of the TileLayer as a 5th argument called fetchStrategy, you could pass it the MinimalFetchStrategy implementation.
