### ISSUE TITLE
Width-Property ignored on VectorStyle with a LineString-Object

### ISSUE THREAD

**Issue by kreativgeist** [Mapsui/Mapsui#732]
When I use the following definition of a style, the drawn line remains small.
It does neither depend on Width of Line or of Outline.

```
Mapsui.Styles.VectorStyle style = new Mapsui.Styles.VectorStyle()
            {
                Fill = new Mapsui.Styles.Brush { Color = Mapsui.Styles.Color.Red },
                Line = { Color = Mapsui.Styles.Color.Red, Width = 4 },
                Outline = new Mapsui.Styles.Pen { Color = Mapsui.Styles.Color.Black, Width = 4 }
            };
```
Can you confirm this to be a bug?

**Comment by pauldendulk** [comment]
If I set the width to 40 in the LineString sample (under 'Geometries') I get this:

![image](https://user-images.githubusercontent.com/963462/69523537-68f11e00-0f64-11ea-9430-b031aef10ffa.png)

This is the style:

```csharp
public static IStyle CreateLineStringStyle()
        {
            return new VectorStyle
            {
                Fill = null,
                Outline = null,
                Line = { Color = Color.FromString("YellowGreen"), Width = 40}
            };
        }
```
What could be the difference?

**Comment by kreativgeist** [comment]
Hello Paul, 
it is not reproducable any more. Yesterday I was looking the whole afternoon for a solution, but today it works great.
Thanks for your positive energy 
Joe
