### ISSUE TITLE
No PinClicked event for selected pin (Xamarin Forms)

### ISSUE THREAD

**Issue by klzig** [Mapsui/Mapsui#733]
Repro:
1) Add handler for PinClicked event
2) Populate map with some pins
3) Select a pin by tapping it on the map, observe that the PinClicked handler is called
4) Tap the same pin again
Actual result: The PinClicked handler is not called for the second tap
Expected result:  The PinClicked handler is called again

My UI design requires different actions when a pin is tapped more than once (slowly, not a double-tap).  On the first tap I add a callout.   On the second tap I invoke a navigation operation.  How can I achieve this?

I see the same behavior on Android and iOS.

**Comment by pauldendulk** [comment]
@charlenni How about this one? Could be related to some callout hang but not sure. What do you think?

**Comment by pauldendulk** [comment]
@klzig could you check if you still have this problem with 2.0.0-beta.34?

**Comment by klzig** [comment]
Yes, I'll try to get to this over the weekend.

**Comment by klzig** [comment]
This appears to be fixed in 2.0.0-beta.34 along with multiple events for a single pin click that I'd been seeing.  Nice!  Tested on Android.

**Comment by pauldendulk** [comment]
Ah, great! Thanks for testing this quickly.
