### ISSUE TITLE
Map Rotation with Animated Navigator is not working correctly

### ISSUE THREAD

**Issue by isra60** [Mapsui/Mapsui#736]
When yo have a Map Rotation of 0/360 and then you send the map to rotation -5 or 355. The map animates with the long path instead of going to the short path.

**Comment by pauldendulk** [comment]
Thanks for reporting this. There should be some code to check for the shortest 'rotation distance'.

**Comment by charlenni** [comment]
See PR #743

**Comment by isra60** [comment]
Ok. Seems to work perfect right now.

Thanks.

**Comment by charlenni** [comment]
@isra60: @pauldendulk approved the above mentioned PR. Is it possible for you to close this issue?
