### ISSUE TITLE
The docfx version had to be downgraded because of issue with v2.47

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#739]
See issue here: 
https://github.com/dotnet/docfx/issues/4535

We should check if a new version has this fixed.

It will remain a good practice to install a specific version of docfx so external changes can not break the build.

**Comment by tmijieux** [comment]
Is this the reason the api reference is gone from https://mapsui.com/api/index.html ?

**Comment by pauldendulk** [comment]
> Is this the reason the api reference is gone from https://mapsui.com/api/index.html ?

No, it was an actual error in the build. I had not noticed the missing api reference. Thanks for mentioning this. I looked into it tonight and have things working now with VS2019 build tools and the latest version of docfx, 2.48.0.
