### ISSUE TITLE
MutatingTriangleSample does not continue refreshing

### ISSUE THREAD

**Issue by capsicumDreams** [Mapsui/Mapsui#740]
I am having trouble changing LineString vertices in a MemoryLayer and subsequently refreshing the layer, and turned to the MutatingTriangleSample for reference.

Once the tiles have finished downloading/refreshing, the triangle no longer 'mutates'.
I believe it is because a MemoryLayer has no implementation for RefreshData().

    public override void RefreshData(BoundingBox extent, double resolution, bool majorChange)
    {
        // RefreshData needs no implementation for the MemoryLayer
    }

Is this intended behavior? Should I implement my own Layer to refresh, somehow?

**Comment by pauldendulk** [comment]
This is a bug. At least in the sample. Also the MemoryLayer should be redesigned. It is possible to set the DataSource but not possible to trigger an update. 

This was the old implementation:
```csharp
        public override void RefreshData(BoundingBox extent, double resolution, bool majorChange)
        {
            //The MemoryLayer always has it's data ready so can fire a DataChanged event immediately so that listeners can act on it.
            OnDataChanged(new DataChangedEventArgs());
        }
```

I removed this OnDataChanged call because I found it confusing. The RefreshData method is intended to fetch data but in this case is used to let the Map know it needs to redraw. Instead it would be better to call a method specifically for this purpose. The WritableLayer has a SignalDataChanged method for this purpose. By removing the implementation I broke things, confirming it is confusing.

I am not going to fix this bug before januari. I think your best option is to copy the MemoryLayer into your own code and implement RefreshData as above. Another option is to use the WritableLayer.

**Comment by capsicumDreams** [comment]
Thanks for your feedback.
In the meantime, I have mearely cleared the RenderedGeometry, and it seems to refresh the data that way. I'm not familiar enough with the codebase to make a more elegant fix..

            // setup
            _greenLineGeometry = new LineString(new[] { _blueLocation, _redLocation });
            _greenLine = new Feature
            {
                ["Name"] = "GreenLine",
                Geometry = _greenLineGeometry,
            };
            _greenLine.Styles.Clear();
            _greenLine.Styles.Add(new VectorStyle
            {
                Line = new Pen(Color.Green, 3),
                Enabled = true,
            });
            _lineLayer = new WritableLayer
            {
                Name = @"GreenLine",
            };
            _lineLayer.Add(_greenLine);
            _lineLayer.Style = null;


            // updating
               PeriodicTask.Run(() =>
                {
                    _redLocationLonLat = RotatePoint(_redLocationLonLat);
                    _redLocation = SphericalMercator.FromLonLat(_redLocationLonLat.X, _redLocationLonLat.Y);
                    _blueLocationLonLat = RotatePoint(_blueLocationLonLat);
                    _blueLocation = SphericalMercator.FromLonLat(_blueLocationLonLat.X, _blueLocationLonLat.Y);

                    _redPoint.Geometry = _redLocation;
                    _bluePoint.Geometry = _blueLocation;

                    _greenLineGeometry.Vertices[0] = _blueLocation;
                    _greenLineGeometry.Vertices[1] = _redLocation;

                    _greenLine.Geometry = new LineString(new[] { _blueLocation, _redLocation });
                    _greenLine.RenderedGeometry.Clear();

                    _lineLayer.RefreshData(null, 1.0, true);
                },
                TimeSpan.FromSeconds(0.1));

**Comment by pauldendulk** [comment]
Oh. I forgot about the RenderedGeometry. This basically a cache and should be explicitly cleared when the Geometry itself changes. Thanks for mentioning it.

**Comment by pauldendulk** [comment]
My earlier comment mentioned SignalDataChanged in WritableLayer but this had allready been replace by DataHasChanged the BaseLayer. So, this could be fixed by just calling DataHasChanged instead of RefreshData.
