### ISSUE TITLE
Can I contribute to Samples?

### ISSUE THREAD

**Issue by RidaNoor** [Mapsui/Mapsui#747]
I want to contribute to Samples with an MVVMCross Xamarin.Forms Application using Mapsui for both Android and iOS with complete cross-platform coding. Will it be accepted? Should I work on it?

**Comment by pauldendulk** [comment]
This needs some discussion first. Does this involve changes to Mapsui itself or just the samples? What is the Model in this case? Does it involve the Map, Layers or Features?

There was an issue submitted on MVVM recently. Is your request related? https://github.com/Mapsui/Mapsui/issues/742

**Comment by RidaNoor** [comment]
@pauldendulk  

Regarding issue # 742,  I don't know what he is talking about exactly. He might be talking about some additional functionality? Although I have managed to use the functionality of Maps, layers and other features like pointers, getting the real-time location and updating the map on real-time accordingly, etc, through the already implemented functionality of this plugin. 

And  I want to share how I made it work with an MVVMCross Xamarin.Forms application. All the supported versions of all the packages and how it should be structured to make it 100% cross-platform, plus, how can you achieve some dynamics, such as different pointer images for a different type of coordinates and different layers and a lot more options that I personally found harder to achieve. Then, how to achieve the real-time location update on the map etc.

**Comment by pauldendulk** [comment]
Perhaps it is better to put this in a separate repository on github. I am struggling with the maintenace of this repository and should try to reduce the scope. Updating mvvmcross, and keeping it in sync with other dependencies, can be a hassle. If you put it in your own repositoy you can be the maintaner. We could point to you repo from our documentation and anounce it in the news section of the readme. Also there have been several questions about mvvm. We should add a comment there with a reference to your project. This will make it easy to find for anyone interested in mvvm and mapsui. We could also help with the setup of such a repo.

**Comment by pauldendulk** [comment]
Some more questions.

Some users that used mvvm in the past were struggling with maintaining state. They have the map in a model and the mapcontrol in a view which could be destroyed at some point. How does your sample deal with that?

**Comment by pauldendulk** [comment]
You mention real time location. This is also present in @charlenni's MapView. How does your solution relate to that?

**Comment by RidaNoor** [comment]
@pauldendulk  I can definitely put it in my repo but I would love to be added as a contributor, will I?
Addressing your questions:
1. I have made the code completely in the MVVMCross way which keeps the Logic and Code separate.
2. I get the realtime location of the Mobile using Xamarin.Forms and have setup the code of both my app and Mapsui to get the real time location as soon as it changes even a little and update the layers of the map according. By updating layers I mean, as I am showing an icon of a person on the map , it gets updated as the location of the person changes

**Comment by pauldendulk** [comment]
Contributors are added automatically after a PR is merged. I suggest you make a PR for the changes in the documentation to point to your repository. In the table of contents you could add a main section called 'tutorials'. Under that an 'MVVM' entry pointing to a page about mvvm. In that page some general introduction and a reference to your github repository. The markdown files you should change are in the docfx folder.

What do you think?

**Comment by RidaNoor** [comment]
@pauldendulk Please check the pull request at : https://github.com/Mapsui/Mapsui/pull/814

**Comment by RidaNoor** [comment]
@pauldendulk  build is failing and definitely because of other reasons or code as I have only changed the markdown files:
https://github.com/Mapsui/Mapsui/commit/387b86cf67930946ec1afac173e95ed4ccca7250

**Comment by pauldendulk** [comment]
ah great, this looks good! The only thing you need to do is to sign the CLA.
 
https://github.com/Mapsui/Mapsui/pull/814#issuecomment-585193979

**Comment by RidaNoor** [comment]
But I have signed it already @pauldendulk 
<img width="938" alt="CLI" src="https://user-images.githubusercontent.com/34579371/74434542-755e8600-4e84-11ea-9547-86aae9a3eb79.png">

**Comment by pauldendulk** [comment]
In that case it can not match the account your signed with to the account of the PR. In this link https://github.com/Mapsui/Mapsui/pull/814#issuecomment-585193979 they mention "Rida Noor seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.". Perhaps this is what you need to do. Or perhaps sign with another account.

**Comment by pauldendulk** [comment]
The account with which you did the commit was rida.noor@tunnll.com.

![image](https://user-images.githubusercontent.com/963462/74512336-586b9680-4f08-11ea-837f-7856663ac9b2.png)

You may need to add the email address used for this commit to your github account

**Comment by RidaNoor** [comment]
@pauldendulk  Oh no, I am using this account in my Visual Studio actually. 
But I have github account with : ridanoor212@gmail.com

**Comment by RidaNoor** [comment]
Let me try to push everything again

**Comment by pauldendulk** [comment]
You do not need to push again.

> @pauldendulk Oh no, I am using this account in my Visual Studio actually.
> But I have github account with : [ridanoor212@gmail.com](mailto:ridanoor212@gmail.com)

Yes, and that explains why it fails. You committed with rida.noor@tunnll.com and this email address is now the author of that commit. This email address does not match your github account. The email address needs to match your accounts email address and this is why it fails. Now what you need to do is exactly what the message says. Read this message and add the other email address to your github account:

https://github.com/Mapsui/Mapsui/pull/814#issuecomment-585193979

**Comment by RidaNoor** [comment]
@pauldendulk  https://github.com/Mapsui/Mapsui/pull/815

**Comment by RidaNoor** [comment]
@pauldendulk  I am hoping that when you merge this PR, Mapsui will appear under the organizations in my Github account, will it?
I need it to show my Open Source COntributions

**Comment by pauldendulk** [comment]
Thanks for the PR. Your documentation page has been deployed:
https://mapsui.com/documentation/tutorials.html

Mapsui shows on your list of repositories https://github.com/RidaNoor?tab=repositories
And you show as a contributor on the mapsui contributors page: https://github.com/Mapsui/Mapsui/graphs/contributors

**Comment by RidaNoor** [comment]
@pauldendulk  thanks for merging it :)
Will not Mapsui appear as organizations here:
<img width="195" alt="CLI" src="https://user-images.githubusercontent.com/34579371/74524510-fb400700-4f40-11ea-9b63-cbd2226df08e.png">

**Comment by pauldendulk** [comment]
No, you are not part of the organization. You have to explicitly added to that and it could be independent of your contributions. There are only 3 people part of the organization, even though there are many contributors. Some who contributed a lot.

**Comment by RidaNoor** [comment]
Got it!
Thanks. I thought, after contributing, it will be added to my Organization. 
Thanks again :)

**Comment by pauldendulk** [comment]
This was implemented. Read more here:
https://mapsui.com/documentation/tutorials.html?q=mvvm

See also this discussion:
https://github.com/Mapsui/Mapsui/issues/742
