### ISSUE TITLE
Reveal pins to appium for Automation Testing

### ISSUE THREAD

**Issue by praveenkumargjll** [Mapsui/Mapsui#748]
Hi,

I am using Mapsui 1.4. I am currently engaging in Automation testing using Appium. The testing team could not able to select pins on the map. Can you let me know, how to set automation properties for Mapsui map and pins?

Thanks

**Comment by pauldendulk** [comment]
I have not looked into appium. I assume it hooks into native widgets. The pins on the map are rendered with skia so no native widgets. So i think this will not be possible in it s current form. 

Is there an easy way to enable Mapsui for appium?

For performance reasons I do not intend to replace all pins with XF widgets.
