### ISSUE TITLE
How to scale the map to the current control size at the specified level？

### ISSUE THREAD

**Issue by IOL0ol1** [Mapsui/Mapsui#750]
Version: 2.0.0-beta.30

i have a tilesource and min level is 3 (8 x 8 tiles), each tile is 256pixel x 256pixel. 
When level is equal to 3, I want to show it completely in the MapControl (500pixel x 500pixel).
How do that?

**Comment by IOL0ol1** [comment]
map.Layers.Add(new TileLayer(tileSource));
            map.Limiter = new ViewportLimiter() { ZoomMode = ZoomMode.Unlimited};


but it‘s not valid for the default mouse roll event，so we need to implement our own mouse wheel event with **MapControl.Navigator.ZoomTo**

**Comment by IOL0ol1** [comment]
en，but when implement my own mouse wheel event ，There is a conflict with the MapControl default implementation.  **ZoomMode.Unlimited** affects most scaling-related operations

**Comment by charlenni** [comment]
Can you describe your problems a little bit? Do you want the same as #757?

**Comment by IOL0ol1** [comment]
> Can you describe your problems a little bit? Do you want the same as #757?

It's different from that question. 
MapControl has listened to mouse wheel events internally, and it limits the zoom factor to the resolution list of all layers.
For example, a world map level 0 have 1 tile, height and width is 256pixel, resolution is 156543.033928 m/pixel
how do i get the map to show width and height less than 256pixel by mouse wheel event?

I found an imperfect solution:
Implement my own tile layer to add more resolution.
code like this:
```csharp
    public class MyTileLayer : TileLayer
    {

        public MyTileLayer(ITileSource source = null)
             : base(source, 200, 300, 2, null, null, -1, -1)
        {
            Name = "MyTileLayer";
        }


        public override IReadOnlyList<double> Resolutions
        {
            get
            {
                // add more resolution to base resolution list
                var output = new List<double>(base.Resolutions);
                for (int i = 0; i < 5; i++)
                {
                    output.Add(156543.033928 * i * 2);
                }
                return output;
            }

        }
    }
```

**Comment by charlenni** [comment]
Ah, than I assume that you working with Mapsui for WPF. Is this correct?

**Comment by IOL0ol1** [comment]
> Ah, than I assume that you working with Mapsui for WPF. Is this correct?

yeah. this code is work, but a little dirty :(
it's compatible with default MapControl's mouse wheel events. 
The zoom factor of the control is obtained by traversing all layers, see [here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Map.cs#L250)

maybe MapControl add **protected void OnMouseWheel(...)** is better?

**Comment by charlenni** [comment]
Again: Which MapControl do you use. We have MapControls in Mapsui.UI.Android, Mapsui.UI.iOS, Mapsui.UI.Uwp, Mapsui.UI.Wpf and Mapsui.UI.Forms.

**Comment by IOL0ol1** [comment]
> Again: Which MapControl do you use. We have MapControls in Mapsui.UI.Android, Mapsui.UI.iOS, Mapsui.UI.Uwp, Mapsui.UI.Wpf and Mapsui.UI.Forms.

Mapsui.UI.Wpf

**Comment by charlenni** [comment]
Thank you.

Than this is @pauldendulk part. The Wpf is really old. So it could happen, that it doesn't support the LimitViewport concept.

**Comment by IOL0ol1** [comment]
> Thank you.
> 
> Than this is @pauldendulk part. The Wpf is really old. So it could happen, that it doesn't support the LimitViewport concept.

thinks, I‘ll look at the implementation of other platforms.

**Comment by pauldendulk** [comment]
It is not clear yet what you are trying to achieve.

> When level is equal to 3, I want to show it completely in the MapControl

What do you see instead?

Mapsui selects the tile level based on the current resolution. You could tweak which level it selects by adjusting the tile schema, but if you have a client with another screen size/resolution the results could be different.

**Comment by IOL0ol1** [comment]
> It is not clear yet what you are trying to achieve.
> 
> > When level is equal to 3, I want to show it completely in the MapControl
> 
> What do you see instead?
> 
> Mapsui selects the tile level based on the current resolution. You could tweak which level it selects by adjusting the tile schema, but if you have a client with another screen size/resolution the results could be different.

sorry, my english is not very good.
Thanks for paying attention to this issue.
I wrote an example to show the problem.
at [https://github.com/IOL0ol1/Mapsui.WPF.Test](https://github.com/IOL0ol1/Mapsui.WPF.Test)

**Comment by pauldendulk** [comment]
Thank you very much for the sample project. I looked at it and understand the problem. The resolutions of the layer are determined by the levels in the mbtiles. In your case leve 0, 1 and 2 are missing (this should not be a problem). The consequence is that the navigation also sees level 3 as the top level en limits zoom out to this level.

It should be possible to override the Resolutions somehow. I think the clearest way to do this is by adding a CustomResolutions field and when this is set the layer resolutions are ignored.

You say the third MapControls behaves as you want. Does this mean your problem is fixed with this workaround?

**Comment by IOL0ol1** [comment]
> Thank you very much for the sample project. I looked at it and understand the problem. The resolutions of the layer are determined by the levels in the mbtiles. In your case leve 0, 1 and 2 are missing (this should not be a problem). The consequence is that the navigation also sees level 3 as the top level en limits zoom out to this level.
> 
> It should be possible to override the Resolutions somehow. I think the clearest way to do this is by adding a CustomResolutions field and when this is set the layer resolutions are ignored.
> 
> You say the third MapControls behaves as you want. Does this mean your problem is fixed with this workaround?

yes，my problem solved.

Maybe change ILayer's
```csharp
IReadOnlyList<double> Resolutions {get;}
```
to
```csharp
List<double> Resolutions {get;}
```
 allow user add/remove custom resolution.
I see only **TileLayer** set this property from **ITileSource**.
ILayer's other implementations are 0 length lists.
Final all layer's resolutions** are summarized to **Map.Resolutions**.
**Map.Resolutions** used in mouse wheel event to zoom.

**Comment by pauldendulk** [comment]
Thanks for creating a sample after your own problem was solved, that's neat. 

Making the Resolutions is quite straightforward for the user. But is the Resolutions are net explicitly set the Map should default to the Layers' Resolutions. The problem is that if you set the Map.Resolutions directly it is not clear that the default is overridden. The could be resolved by adding Map.CustomResolutions. 

Another option is to make it the responsibility of the MapControl to choose between layer Resolutions and Map.Resolutions. In this case the layer Resolutions should not be assigned to the Map.Resolutions.
