### ISSUE TITLE
how to active satellite view

### ISSUE THREAD

**Issue by reza40741** [Mapsui/Mapsui#751]
how ca I active satellite view?

**Comment by charlenni** [comment]
Please see the samples, especially [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/BingSample.cs).

To show satellite images, you need a map tile provider for this. If you have one, than you could use it as any other provider for map tiles.

If this answers your question, please close this issue.

**Comment by damusthe** [comment]
@charlenni , the sample link is not more valid : "404 - page not found".

**Comment by charlenni** [comment]
Yes, that could be. The answer is now 5 years old and it seems that a lot of the project changed.

There should be still a sample for this. You only have to find it by yourself.
