### ISSUE TITLE
MapsUi.Forms - Drawables.Clear throw exception

### ISSUE THREAD

**Issue by pkozak2** [Mapsui/Mapsui#752]
Version: 2.0.0-beta.30
Platform: Xamarin.Forms

I want to remove all drawables from my map, so I want to call:
`mapView.Drawables.Clear()`

After clear Drawables control will throw an Exception: "Object reference not set to an instance of an object." 

[Line 789](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.UI.Forms/MapView.cs#L789) throws an exception, and [Line 762](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.UI.Forms/MapView.cs#L762) is already fixed.

Please add check for `e.NewItems != null`

**Comment by charlenni** [comment]
Thank you for reporting this bug. 

See #758.

**Comment by pauldendulk** [comment]
This should be fixed in 2.0.0-beta.31 that was just released.
