### ISSUE TITLE
Is there support for highlighting buildings in Open Street Maps using MapsUI for Xamarin Forms

### ISSUE THREAD

**Issue by BrianVance** [Mapsui/Mapsui#754]
Well this isn't a issue but more of a query. I need to highlight buildings close to my position in Open Street Maps. I am using the Mapsui for Xamarin Forms and was wondering if this feature was possible? I took the below screenshot from Open Street Maps while editing the maps and I noticed it highlighted the buildings in my view. My would like to achieve the same effect using Mapsui (Notice the buildings highlighted in red). Any thoughts?

![image](https://user-images.githubusercontent.com/10665687/71687298-8091a280-2d6b-11ea-86e4-c3ac17990d02.png)

**Comment by BrianVance** [comment]
I also discovered a feature that would help me with my situation. The below screenshot showcases Open Street Map with "Map Data" option checked which highlights buildings. Do we have an option to enable this in MapsUI?

![image](https://user-images.githubusercontent.com/10665687/71688347-b041aa00-2d6d-11ea-9c9f-0cb13c32f322.png)

**Comment by charlenni** [comment]
If you edit OpenStreetMaps, than you use vector data. If you use Mapsui, than you use bitmap data. The later one has no informations about streets or buildings. It is only a picture of the map after someone has rendered the vector data for you. 

For this you have to use vector data with a special style and a renderer, that convert both into bitmap map tiles. This could be done by some services in the internet, e.g. Mapbox.

**Comment by BrianVance** [comment]
@charlenni I have a shape file that contains the building shapes. Can MapsUI for Xamarin Forms 2.0 load a Shape File? I wanted to save the shape file on an android device and load it through a Xamarin Forms app. I noticed a project titled Mapsui.Desktop which had a ShapeFile class but I could not use it in the Mapsui.Forms 2.0 library.

**Comment by charlenni** [comment]
Mapsui could load some types of shape files. See the samples [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common.Desktop/ShapefileSample.cs). The Xamarin.Forms implementation hasn't a special wrapper for this, but you could use MapView.Map for this.
