### ISSUE TITLE
Pins scaling on map resize ? (Xamarin.Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#756]
First, thanks for all you hard work - really appreciate it.

I have now added some pins to my map, in the same way as I have added polylines.

The polylines "scale with the map", ofcourse - but when I scale my map pin are not changing size, is that the intended behavior ?

This means that when I zoom out and the map becomes "smaller", the pins gather closer and closer - but as they do not scale / get smaller, they end up covering the entire map.

**Comment by charlenni** [comment]
I don't know of any map library, where pins are scaled. You could do this, when you add your own symbols to Mapsui and scale them regarding the resoultion of the map each time that the resoultion change.

**Comment by tonyfonager** [comment]
Thanks for the answer, I actually think I was wrong too - so sorry for the misunderstanding!
