### ISSUE TITLE
Dragging / scaling map "out of bounds" ? (Xamarin.Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#757]
I have added the map to my app, and as I do not want to provide data for the entire planet, I have only added mbtiles based data for Denmark.

But I can both zoom / scale / drag the map, so the areas that contains no map data is visible, showing the white backgrounds.

Is there a way to avoid this ? - so no matter how small / big an area I have data for, I cannot make those annoying white areas become visible ?

Thanks to all the contributers - you are doing an awesome job ;-)

You can see an example of an "out of bounds" map in my app here :

![image](https://user-images.githubusercontent.com/837894/71851740-7d821380-30d7-11ea-9157-145d1111527f.png)

**Comment by charlenni** [comment]
You could find this in the examples [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/KeepWithinExtentsSample.cs).

If this answers your question, than please close this issue.

**Comment by tonyfonager** [comment]
*sigh* - how did I miss that.

Its already tested and works - thanks for your efforts and quick reply!
