### ISSUE TITLE
Update .Net Framework and friends?

### ISSUE THREAD

**Issue by ejkani** [Mapsui/Mapsui#759]
I would like to update the projects to target the latest framework versions as of 2020-01-07 beginning with:
- Upgrade .Net Framework projects to .Net Framework 4.8
- Upgrade all Nuget packages to latest version, this includes upgrade to Xamarin.Forms 4.4

The reason for this is that I'm chasing a UI Thread exception, and want to fix it. But first it would ve nice to update the projects to the latest framework and packages. (PS: Not going to upgrade netstandard2.0 to netstandard2.1 :-) )

Are there any concerns, other than making the Tests and Samples run, in order to do this?

BR, Terje Kvannli

**Comment by pauldendulk** [comment]
You want to submit a PR to upgrade the version?

Upgrading also forces users to upgrade so I don't usually do this unless there is some specific reason, or as part of a major version upgrade. What is the advantage for you to upgrade?

**Comment by ejkani** [comment]
Hi Paul!
Primarily it was to update to Xamarin.Forms 4.4, but I can leave it as is and focus on the threading error instead.
