### ISSUE TITLE
Creating custom symbol issue

### ISSUE THREAD

**Issue by TheProme** [Mapsui/Mapsui#760]
I'm trying to resolve issue with creating symbol from image and can't figure why am I seeing my symbol on top of point's circle. With some changes I'm reffering to:
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/PointsSample.cs

Using Xamarin.Forms with WPF.
![sample](https://user-images.githubusercontent.com/22505666/71975576-fb036c00-321c-11ea-81e2-38aaa353e63d.png)

Code below:

        private static int GetBitmapIdForEmbeddedResource(string imagePath)
        {
            using (FileStream fs = new FileStream(imagePath, FileMode.Open))
            {
                var memoryStream = new MemoryStream();
                fs.CopyTo(memoryStream);
                var bitmapId = BitmapRegistry.Instance.Register(memoryStream);
                return bitmapId;
            }
            
        }
        private static SymbolStyle CreateSymbolStyle(string embeddedResourcePath, double scale)
        {
            var bitmapId = GetBitmapIdForEmbeddedResource(embeddedResourcePath);
            return new SymbolStyle { BitmapId = bitmapId, SymbolType = SymbolType.Bitmap, SymbolScale = scale, SymbolOffset = new Offset(0.0, 0.0, true) };
        }
        private void MapView_SingleTap(object sender, Mapsui.UI.TappedEventArgs e)
        {
            var feature = new Feature();
            feature.Geometry = mapView.Viewport.ScreenToWorld(e.ScreenPosition);
            var symStyle = new SymbolStyle();
            symStyle = CreateSymbolStyle(@"C:\Users\r\Desktop\configuration.png", 1);
            feature.Styles.Add(symStyle);
            MapVM.WritableLayer.Add(feature);
            mapView.RefreshGraphics();
        }

**Comment by charlenni** [comment]
What style does your layer contain? If you want to set the style of each feature, than the style of your layer should be empty. 

If all features of a layer should have the same style, than you set Layer.Style to your style and Feature.Style.Clear(). If you want to have each Feature a different style, than you set Layer.Style.Clear() and Feature.Style to your style.

**Comment by TheProme** [comment]
I'm using WritableLayer and trying to achieve different styles of each symbol on the layer. Seems like WritableLayer does not contain such method as Style.Clear()

**Comment by TheProme** [comment]
Setting Layer.Style = null resolving this issue, but is this appropriate way to solve this?

**Comment by charlenni** [comment]
WriteableLayer inherits from BaseLayer. And as you could see, BaseLayer (see [here](https://github.com/Mapsui/Mapsui/blob/5a65c4775bc0ceba0a51446f3e5167aee7131b66/Mapsui/Layers/BaseLayer.cs#L49)) sets the default style to a new VectorStyle(), which produces your circles.

**Comment by TheProme** [comment]
Well, alteast it works for now :) thanks for a quick reply. I'm closing this issue
