### ISSUE TITLE
[Forms] MapView: stacklayout  holding buttons not transparent to input when all buttons are hidden.

### ISSUE THREAD

**Issue by tmijieux** [Mapsui/Mapsui#766]
I would like to use the Mapsui.UI.Forms.MapView class  because I use the "Pins" feature this class provides but with all buttons hidden.

The problem is the stacklayout that hold the buttons remains "visible". It is transparent(I cannot really "see" it) but I cannot drag the map through it.
https://github.com/Mapsui/Mapsui/blob/a01d10d482ed499a10e4e4a7e3e78c1ebd34e77d/Mapsui.UI.Forms/MapView.cs#L135

The problem appeared on an android physical device (the one I am currently testing my application on: Samsung J3 "SM-J330FN" Android 9). I did not test it on any other device.

Suggestion: maybe we could toggle the visibility of this stacklayout dynamically in a similar way it is done for the buttons separators but only when all button are hiddens:
https://github.com/Mapsui/Mapsui/blob/a01d10d482ed499a10e4e4a7e3e78c1ebd34e77d/Mapsui.UI.Forms/MapView.cs#L658

EDIT:
We can easily see where this StackLayout is on Android with the developer options that allow you to see layout bounds "show layout bounds".

**Comment by pauldendulk** [comment]
I won't have time to look into this soon.

Perhaps use the MapControl instead.

**Comment by charlenni** [comment]
Problem solved. Was a bug in MapView. See #787.

**Comment by pauldendulk** [comment]
Should be fixed in 2.0.0-beta.33.
