### ISSUE TITLE
Question: Anchor ScaleBar to a longitude and latitude

### ISSUE THREAD

**Issue by BrianVance** [Mapsui/Mapsui#771]
Hi,
   I was thinking of a solution of measuring a single side of a building and I noticed the ScaleBar sample might help me do this. Is there a way to anchor the scale bar to two points (Longitude/Latitude) and keep it fixed? Maybe the below example can give you an idea.

![image](https://user-images.githubusercontent.com/10665687/72358828-2e317980-36bb-11ea-8fcb-a5f4d7762644.png)

**Comment by pauldendulk** [comment]
I think the best option is to create a custom widget specifically for this. There is a CustomWidgetSample to show how to configure your own widget. It is a widget that does nothing useful. You could use code from the scalebar widget as a start for the measure widget.

**Comment by charlenni** [comment]
A custom widget isn‘t the right thing. Widgets are things, that stay always on top of the map relative to the views outline. They are independent of map coordinates.

I would suggest two symbols, one for each side, and a normal line between them. If you want text between them, than add a symbol with text in the middle.

Or, if you want a better solution, create a new feature type with its own rendering in Mapsui.

**Comment by pauldendulk** [comment]
Widgets are intended for these kind of user tools. Perhaps the interface needs adaption for this scenario though. For this feature a button to turn measuring on/off might still be positioned on top of the map. But even if that is not the case it would be nice to have this functionality in a reusable widget.

@BrianVance How did you image the user interaction for this purpose?

**Comment by BrianVance** [comment]
@pauldendulk  For now I have used two symbols and a line to keep things simple. We are working on a way to calculate the sides of a building using a polygon points which will eventually help us determine the distance between them. We will be integrating this distance with the solution for the line and symbol.

**Comment by pauldendulk** [comment]
Alright, a reusable widget for all will have to wait. My priority now is on fixing bugs.
