### ISSUE TITLE
map not showing (only showing backColor) 

### ISSUE THREAD

**Issue by eugenerobby** [Mapsui/Mapsui#773]
i am currently clone the source code and start to build it on my phone, i use samsung galaxy J7+ (android 8.1 API 27)
after deploy the app, it just show the backColor and the polygon but its not showing the map, is there any other step that i missed ? 

i am also add mapsui v1.3.0 and mapsui.form v0.2.1 on nuget

thank you 
![Screenshot_20200116-105646](https://user-images.githubusercontent.com/46314605/72492271-273b7000-384f-11ea-890b-56ae922f9a2e.jpg)

**Comment by pauldendulk** [comment]
Do you run the samples? Which ones?

**Comment by eugenerobby** [comment]
i run code from this link: https://github.com/Mapsui/Mapsui, is there any step that i missed when implement it ? thank you

**Comment by pauldendulk** [comment]
That url points to the entire project. What sample in the project are you running?
