### ISSUE TITLE
WidgetRenderer in Mapsui.Rendering.Xaml have some bug

### ISSUE THREAD

**Issue by IOL0ol1** [Mapsui/Mapsui#774]
This problem is very easy to reproduce.
- run Samples/Mapsui.Samples.Wpf
- select Demo - OpenStreetMap
- change render from Skia to Wpf.
You'll find the zoom button in the lower right corner is missing.
i debug at [here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Xaml/XamlWidgets/WidgetRenderer.cs#L14)
```csharp
            var widgetCanvas = new Canvas
            {
                Width = canvas.ActualWidth,
                Height = canvas.ActualHeight,
                Background = null
            };

            canvas.Children.Add(widgetCanvas);
```
after set **widgetCanvas.Height** and **widgetCanvas.Width**,
**widgetCanvas.ActualWidth** and **widgetCanvas.ActualHeight**  are still 0.
There will be failures in the subsequent rendering process([here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Xaml/XamlWidgets/ZoomInOutWidgetRenderer.cs#L30)).
```csharp
        var posX = zoomInOut.CalculatePositionX(0, (float) canvas.ActualWidth,
            zoomInOut.Orientation == Widgets.Zoom.Orientation.Vertical ? zoomInOut.Size : zoomInOut.Size * 2 - Stroke);
        var posY = zoomInOut.CalculatePositionY(0, (float) canvas.ActualHeight,
            zoomInOut.Orientation == Widgets.Zoom.Orientation.Vertical ? zoomInOut.Size * 2 - Stroke : zoomInOut.Size);
```

**Comment by IOL0ol1** [comment]
by the way, my solution is to manually call the layout calculation function, code like this
```csharp
            var widgetCanvas = new Canvas
            {
                Width = canvas.ActualWidth,
                Height = canvas.ActualHeight,
                Background = null
            };
            widgetCanvas.Arrange(new System.Windows.Rect(canvas.RenderSize));
            canvas.Children.Add(widgetCanvas);
```

**Comment by pauldendulk** [comment]
oh, this is a report and a fix, fantastic. You could also have submitted a PR for this. Add pushed your fix.

A question, why do you use the WPF renderer? It might disappear in the future and I would like to add functionality missing in skia to make up for that.

**Comment by IOL0ol1** [comment]
> oh, this is a report and a fix, fantastic. You could also have submitted a PR for this. Add pushed your fix.
> 
> A question, why do you use the WPF renderer? It might disappear in the future and I would like to add functionality missing in skia to make up for that.

I want to add some controls to MapControl,  looks like ZoomInOutWidget, but i need more complex styles, animations and effects.  
- controls position need bind with other layer's point, looks like add a polylone to Layer. 

Do you have a better way?
