### ISSUE TITLE
First map click is NOP but prevent removing pin from map

### ISSUE THREAD

**Issue by sailman342** [Mapsui/Mapsui#776]
First thanks to the Mapsui team for this marvelous project !

I am writing an app dealing with routing and storing routes in files. For this I need to edit a route on the map, save it and possibly reload it later. Therefore I am playing with inserting and removing pins from the mapView.Pins ! 

I realised Strange behaviours and minimized my app up to being able to demonstrate the problem. 

If you create a Pin on the map, and Don't click anywhere on the map but remove the pin with a dedicated button of your form, the app will hang.

The first click on the map after creating the pin doesn't fire the onMapClicked event !

This is the case for UWP and Android  2.0.0-beta 32 

A smal demo of the problem is here (visual studio 2019 solution) hope it helps

https://www.dropbox.com/sh/ndt6ixr5u3auiz0/AAARIRHvRAhsClgrkRTlYfv3a?dl=0

**Comment by sailman342** [comment]
I Don't know if it helps for finding the bug but here is what you get after navigation between pages and come back to the point you intend to remove the pin (remember pin Added, no click on hte map or whatever and navigation to other pages, then come back to the map page and try to remove the pin by code)

For the time being, the work around is to use Pins.clear() at page appearing and redraw the whole thing waiting for the user to click somewhere before trying to delete anything !

![image](https://user-images.githubusercontent.com/58634016/72661498-f8ea9b80-39da-11ea-9d6c-15da937a3f84.png)

**Comment by pauldendulk** [comment]
Thanks for the report and thanks a lot for providing a minimal sample, that is appreciated. However I can not download the sample. Dropbox presents it as a long list of separate files. Perhaps you can upload a zip.

**Comment by sailman342** [comment]
here is the zip file, I don't want to pollute github with that !

https://www.dropbox.com/s/jmsuhoopth82yy1/SmallTest.zip?dl=0

Kindest

**Comment by charlenni** [comment]
Again, this is a problem with the CallOut. It tries to create one, while trying to hide it.

@pauldendulk I should create callouts on a complete different way. But for this, I should ahve an idea, what things we could do with callouts.

**Comment by sailman342** [comment]
I Don't use the Mapsui CallOut, I build my own ….

I need buttons on the pin CallOut to indicate if it is a start point, a via point or end point … or if user whish to delete the pin ... or get info ...

For this I derived the Pin class and added new properties and methods. I define dynamically the buttons role. Still at prototype level but works fine for now :-)

**Comment by charlenni** [comment]
A Pin always creates a callout in the background.

**Comment by sailman342** [comment]
Here is my constructor code, I Don't touch the callOut, everything is by default ..

`        public RBPin(
            int indexArg,
            AddressPoint addressPointArg,
            RoleType roleToPlayArg,
            bool canBeDeletedArg,
            Color colorArg,
            float transparencyArg,
            LeftButtonHandler leftButtonHandlerArg,
            MiddleButtonHandler middleButtonHandlerArg,
            RightButtonHandler rightButtonHandlerArg,
            RBMapView mapViewArg,
            AbsoluteLayout layoutArg)

            : base(mapViewArg)

        {
            ThreadLog("RBPin Constructor", true);
            // base 
            Label = roleToPlayArg.ToString();
            Address = addressPointArg.Address;
            Position = new Position(addressPointArg.Latitude, addressPointArg.Longitude);
            Type = PinType.Pin;         
            Color = colorArg;
            Transparency = transparencyArg;
            Scale = 1.0f;

            // child class
            index = indexArg;
            mapView = mapViewArg;
            layout = layoutArg;
            addressPoint = addressPointArg;
            roleToPlay = roleToPlayArg;

            canBeDeleted = canBeDeletedArg;

            leftButtonHandler = leftButtonHandlerArg;
            middleButtonHandler = middleButtonHandlerArg;
            rightButtonHandler = rightButtonHandlerArg;

            // ?? this.ShowCalloutWindow();
        }`

**Comment by charlenni** [comment]
It is created in the background.

**Comment by sailman342** [comment]
I understand, this was an temptative answer to Paul :-)

**Comment by pauldendulk** [comment]
@charlenni Okay, let's do that. I will try to spend some time on this the coming period.

**Comment by pauldendulk** [comment]
I can reproduce the problem with the sample. Thanks for the instruction in the sample.

**Comment by pauldendulk** [comment]
@charlenni And this one? apparently I could reproduce it with the sample.

**Comment by charlenni** [comment]
I now see no problem with this app. Works like a charme.

**Comment by pauldendulk** [comment]
Good! let's consider it tested.
