### ISSUE TITLE
Question: Get North position when map is rotated

### ISSUE THREAD

**Issue by BrianVance** [Mapsui/Mapsui#777]
It might seem like a silly question since I am new to maps but is it possible to get the North direction when the map is rotated. I am creating a screen grab of the map using the GetSnapshot method and I want to display an arrow which shows where the north direction is. 
  Something similar to the below feature -

![image](https://user-images.githubusercontent.com/10665687/72745170-23745a00-3b7d-11ea-9a99-d2b18cacd3ef.png)

I can rotate the image using degrees but I fail to understand how to get the North direction from Mapsui through code.

**Comment by pauldendulk** [comment]
The navigator sets the Viewport.Rotation. You can request it with:
```csharp
MapControl.Viewport.Rotation
```

**Comment by BrianVance** [comment]
Perfect! Thank you very much
