### ISSUE TITLE
Mapsui for Xamarin.Mac

### ISSUE THREAD

**Issue by TarasParashchuk** [Mapsui/Mapsui#778]
Hi developers Mapsui!
I wanna know, when build Mapsui will be relised for Xamarin.Mac. 
Thanks in advance!

**Comment by pauldendulk** [comment]
No plans yet. 

Do you use Mapsui on other platforms already?

**Comment by TarasParashchuk** [comment]
![image](https://user-images.githubusercontent.com/28906316/72967935-1d73b880-3dcb-11ea-8fb8-8ef606a2bbeb.png)
I don't used Mapsui on other platforms (I used for Xamarin.Forms). First time I saw this information on github and I thought maybe someone else tried to use own build Mapsui for Xamarin.Mac.

**Comment by pauldendulk** [comment]
Ah, the builder server for mac is just for iOS.

**Comment by charlenni** [comment]
If you use Xamarin.Forms on Mac, it should be no problem to use Mapsui.Forms. It builds on SkiaSharp. If there is a version of SkiaSharp for Xamarin.Forms for your platform, and I saw one for the [Mac](https://github.com/mono/SkiaSharp/tree/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac), than it should work.
