### ISSUE TITLE
Circle is shown as triangle (Bug ?)

### ISSUE THREAD

**Issue by sailman342** [Mapsui/Mapsui#779]
Circle cirCle = new Circle();
            cirCle.Radius = Distance.FromMeters (100);
            cirCle.Center = center;
            cirCle.FillColor = Color.Green;
            MyMapView.Drawables.Add(cirCle);`

with Xamarin Forms will produce this 

![image](https://user-images.githubusercontent.com/58634016/72976138-4b103000-3dd2-11ea-8d67-d98678377ab2.png)

Possibly a bug or I need to read the doc :-)

same on beta 32 or build 966

**Comment by charlenni** [comment]
No bug. See [sample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/CircleSample.cs)  for creating circles. You didn’t set the Quality property.

**Comment by sailman342** [comment]
`            cirCle.Quality = 360;`

Corrected the problem, I saw it in the doc but didn'realize that quality factor is in fact number of sides :-)

maybe a default value a bit higher than 3 ?


Thanks a lot for helping and for the nice tool you give us !

**Comment by charlenni** [comment]
I assume, that 360 is much to high. It would be faster to use a lower value.

There are no real circles in Mapsui. So all circles are made of lines/polygons. If you set a Quality of 360, each circle consist of 360 lines.

**Comment by sailman342** [comment]
I intended to draw circles on each point of a gpx track but it is slow ! I discovered polyline is fastest and nicest, so the circles will be for start (green) and end (red) points only :-)

**Comment by charlenni** [comment]
If you use Features, you could use symbol style to draw circles. That should be very fast.

**Comment by sailman342** [comment]
Patience I am still on the Learning curve .... but if I can help :-)
