### ISSUE TITLE
Pin IconType Position (Possible Bug)

### ISSUE THREAD

**Issue by reza40741** [Mapsui/Mapsui#780]
I want to show a Pin (Icon Type) at the end of the line, although the line and the icon have the same position, the icon is not in the right position, I don't have this issue with pin (Pin Type)
![20200123_132024](https://user-images.githubusercontent.com/59375636/73013588-9f250f80-3de6-11ea-82ae-b8912945716a.jpg)

**Comment by pauldendulk** [comment]
Something with alignment maybe? Set vertical alignment to 'Center'. Just guessing.

Do you have some code to show?

**Comment by reza40741** [comment]
> Something with alignment maybe? Set vertical alignment to 'Center'. Just guessing.
> 
> Do you have some code to show?

var assembly = typeof(MainPage).GetTypeInfo().Assembly;

            Stream strImage = assembly.GetManifestResourceStream("WFMS_Locator_Trajectory.Portable.Assets.Arrow.png");

            byte[] imgIcon = strImage.ToBytes();

            map.Pins.Add(new Pin(new MapView())
            {
                Position = new Position(pst.Latitude, pst.Longitude),
                Type = PinType.Icon,
                Label = pinName,
                Icon = imgIcon
            });

**Comment by charlenni** [comment]
Did you look into the property Anchor? If you use a bitmap, you should specify the position, where the zero point of the bitmap is. Default is (0,28). 

So change this Anchor regarding to your imgIcon and try again.

**Comment by reza40741** [comment]
ok, Thanks, It Works
