### ISSUE TITLE
Custom widget issue

### ISSUE THREAD

**Issue by TheProme** [Mapsui/Mapsui#781]
I've been playing with widgets and stumbled on a bug (maybe?). Custom widget Alignment is always set at top left corner and is impossible to place it somewhere else.
![image](https://user-images.githubusercontent.com/22505666/73052995-452c5480-3e8f-11ea-8653-0b1001f7c43e.png)

`mapView.Renderer.WidgetRenders[typeof(MapPointer)] = new MapPointerRenderer();
            mapView.Map.Widgets.Add(new MapPointer
            {
                HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Right,
                VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Bottom,
                Width = 20,
                Height = 20,
                Color = Mapsui.Styles.Color.Red
            });;`

I've been following custom widget sample. The same happens in Mapsui.Samples so maybe it's a bug?

**Comment by pauldendulk** [comment]
Well, that was just not implemented. There is actually a comment in the sample's which says ["A better implementation would take into account widget alignment"](https://github.com/Mapsui/Mapsui/blob/39734798d5438d1a85b7fef71ad95a31fc0a6ad6/Samples/Mapsui.Samples.CustomWidget/CustomWidgetSkiaRenderer.cs#L25).

The idea of the sample was how to show how you could create your own widget and how to configure it. In the widget renderer itself there is a lot of stuff the implementer needs to do.

**Comment by TheProme** [comment]
Oh, I see. Would be wonderfull if you share any ideas on how to implement alignment to custom widget. Seems like I'm stuck on this point :(

**Comment by pauldendulk** [comment]
You could look at the implementation of other widgets to see how to determine the rectangle to draw. For example [here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Skia/SkiaWidgets/ZoomInOutWidgetRenderer.cs#L37) the starting  x is calculated.

To get started you could also copy the entire code from one of the existing widgets and throw away what you don't need.

**Comment by TheProme** [comment]
I'll give it a try. Thanks a lot :)
