### ISSUE TITLE
I need a label Without circle

### ISSUE THREAD

**Issue by reza40741** [Mapsui/Mapsui#782]
All of the labels in Mapsui have a circle, I don't know why? is there any label without the circle?

My Code:
 featureWithDefaultStyle.Styles.Add(new Mapsui.Styles.LabelStyle
            {
                Text = dis ,
                BackColor = new Mapsui.Styles.Brush(Mapsui.Styles.Color.Gray),
                ForeColor = Mapsui.Styles.Color.White,
                MaxWidth = 12,
                WordWrap = Mapsui.Styles.LabelStyle.LineBreakMode.WordWrap,
                HorizontalAlignment = Mapsui.Styles.LabelStyle.HorizontalAlignmentEnum.Right,
                VerticalAlignment = Mapsui.Styles.LabelStyle.VerticalAlignmentEnum.Bottom,
            });

![20200124_092811](https://user-images.githubusercontent.com/59375636/73076531-4c059800-3e8c-11ea-8411-a078a997fb0b.jpg)

**Comment by charlenni** [comment]
See #760

**Comment by reza40741** [comment]
Thanks
