### ISSUE TITLE
Samples don't work because of missing map

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#784]
With PR https://github.com/Mapsui/Mapsui/commit/e5e93ff0a094c9d727be35b406baa828cc3050b4 you added in the MBTilesSample a line, which add a chines-world.mbtiles layer to the map, but you don't add this map to the PR.

**Comment by pauldendulk** [comment]
That's a mistake, I will fix it.

**Comment by charlenni** [comment]
Removed the line. See #786.

**Comment by pauldendulk** [comment]
Should be fixed in 2.0.0-beta.33.
