### ISSUE TITLE
Desktop Wms Client Description

### ISSUE THREAD

**Issue by mhardingham** [Mapsui/Mapsui#792]
Mapsui.Desktop/Wms/Client.cs, Line 357
			
node = xnlServiceDescription.SelectSingleNode("sm:ContactInformation/sm:ContactElectronicMailAddress", _nsmgr);
			
Should this be...
						
node = xnlServiceDescription.SelectSingleNode("sm:ContactInformation/sm:StateOrProvince", _nsmgr);

Also, 
Line 365
                    "sm:ContactInformation/sm:ContactPersonPrimary/sm:ContactOrganisation", _nsmgr);
Should this be... 
                    "sm:ContactInformation/sm:ContactPersonPrimary/sm:ContactOrganization", _nsmgr);

Regards

**Comment by pauldendulk** [comment]
Thank you very much. Your information made it easy to fix.
