### ISSUE TITLE
StrokeColor is always black in Polygon

### ISSUE THREAD

**Issue by mgutierrezaill** [Mapsui/Mapsui#793]
In the sample: [https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/PolygonSample.cs](url), the StrokeColor is always black, and StrokeWidth is not affected in polygon.

Is this example the most recent or should I look at this [https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/PolygonSample.cs](url) ?

**Comment by charlenni** [comment]
Sorry, you found a bug in the Forms implementation. I try to look into this problem ASAP, because it is one of the easier problems 😉

**Comment by charlenni** [comment]
See PR #794.

**Comment by pauldendulk** [comment]
Should be fixed in 2.0.0-beta.33.

**Comment by mgutierrezaill** [comment]
Thanks!!
