### ISSUE TITLE
Own MemoryLayer with Pins or Polylines (Xamarin.Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#795]
I have one TIleLayer with a map, and then I add some pins (POI's) and a Polyline (a hiking route) to the MapView control (.Pins and .Drawables properties)

But I am seeing some serious performance issues, so I wondered if it would speed up rendering if I added my own MemoryLayers, one for Pins and one for Polylines.

But what I see when I do this, is that I loose the click functionality on fx the Pins - when looking into the sourcecode, the MapView in forms actually add its own MemoryLayers for Pins and Drawables, so maybe I cannot gain any performance from this ?

Maybe I am just duplicating the functionality thats already in the MapView control ?

Also, I would like my Pins only to be visible at a certain zoom level - I can specify this when using my own MemoryLayer (and confirm that it works), but how is that possible if I use the built in .Pins collection on the MapView control ?

**Comment by charlenni** [comment]
I assume, that the performance problems occure because of the callout creation problem. I'm working on this problem and hope, that I could solve it.

Yes, Pins and Drawables are created on special layers. If you want to make your own features on a MemoryLayer, than you have to use the normal Mapsui Features and LineStrings.

The visibility for a special zoom level isn't implemented in MapView up to now. I look, what I can do.

**Comment by tonyfonager** [comment]
Thanks for your fast reply, appreciate it.

Can you point to some kind of documentation for the "Features" things, not sure I fully understand what it is / how to use it ?

**Comment by charlenni** [comment]
You could look at the common samples of Mapsui like for [LineString](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/LineStringSample.cs) or for [Points](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/PointsSample.cs).

But be carefull, as in the LineString sample, you should convert your coordinates in the right coordinate system for Mapsui.
