### ISSUE TITLE
Adding thousands of positions to Polyline slow (Xamarin.Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#797]
Every time I add to the Polyline.Positions observable collection, an event is fired and then entire LineString is recreated.

When adding **thousands** of positions to a polyline, this adds up to taking seconds.

I would like to be able to "bulk insert" data into these observable collections, and when that is done it should ask for the drawable to be recreated.

**So only once - not every time a position is added!**

Right now I have tried adding a new method to the Polyline.cs file, which disables the CollectionChanged event, then it inserts the entire collections of positions, reassigns the CollectionChanged event and call "OnPropertyChanged", to have the LineString recreated.

```
public void AddPositionsBulk(List<Position> bulkPositions)
{
    // disable events on collection
    _positions.CollectionChanged -= OnCollectionChanged;

    foreach (Position pos in bulkPositions)
    {
         _positions.Add(pos);
    }

    // reassign events on collection
     _positions.CollectionChanged += OnCollectionChanged;

    // notify that collection has changed, to recreate LineString
     OnPropertyChanged(nameof(Positions));
}
```

Its so much faster, that my app starts up several seconds quicker now.

What do you think ?

**Comment by tonyfonager** [comment]
I could also just add a new constructor, that takes a list of positions as a parameter ?

Maybe that is more clean ?

**Comment by charlenni** [comment]
Perhaps it is a better solution to use this [ObservableRangeCollection](https://stackoverflow.com/questions/670577/observablecollection-doesnt-support-addrange-method-so-i-get-notified-for-each/45364074#45364074).

**Comment by tonyfonager** [comment]
Is that a custom class ? I dont think its a part of .NET api ?

If yes, we could add it ?

**Comment by radderz** [comment]
ObservableRangeCollection is just an extension of ObservableCollection, there is a myriad of examples of it.

**Comment by charlenni** [comment]
@radderz Any better NuGet for this?

**Comment by pauldendulk** [comment]
You could also use a LineString. It is not that hard to convert your coordinates from wgs84 (used for gps coordinates) to SphericalMercator (used by the openstreetmap default background layer). 

```csharp
var centerOfLondonOntario = new Point(-81.2497, 42.9837);
var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfLondonOntario.X, centerOfLondonOntario.Y);
```

**Comment by tonyfonager** [comment]
So LineString does not "recreate itself" everytime I add a new position to the object ?

**Comment by pauldendulk** [comment]
It is possible to add a point to a geometry without creating a new one. Editing a LineString will require more custom code though. You can look at the Mapsui.Samples.Wpf.Editing sample app to get an impression how this works. The sample uses a WriteableLayer. Take into account that the cache of the geometry needs to be cleared.

![addline](https://user-images.githubusercontent.com/963462/73528475-3f95b800-4415-11ea-96fc-cc28e5c0bf27.gif)

**Comment by pauldendulk** [comment]
Fixed by using the ObservableRangeCollection.
