### ISSUE TITLE
Creating MbTilesTileSource() is slow - worst on device (Xamarin.Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#798]
Hi there, sorry that I keep bugging you guys - you do an incredible job, thanks!

I am using mbtiles for my map data, which I generate by using Maperative on Windows.

I see that when I start creating more and more "complex" (meaning bigger) maps, it really starts hurting the performance.

Creating the MbTilesTileSource takes 35 seconds on a physical iPhone XS Max. If I do the same on the simulator on my iMac, the same only takes 5 seconds :

`var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(path, true));
`

The mapfile is 537 mb, but being a SQLite database I do not expect size to be the biggest issue.

It also seems like the map becomes more "laggy", when adding more tiles. But, I thought that by only loading the tiles "visible", it would not matter if it is a huge or small map - or have I misunderstood something ?

Has anyone tried the same size mbtiles map data files and experience the same ?

**Comment by charlenni** [comment]
Is it possible to download the file anywhere? I assume no one tested such big files up to now.

**Comment by tonyfonager** [comment]
I will test out some of the samples with my mbtiles file, just to rule out that its something in my app that it slow.

Also, you can download the file here : https://www.dropbox.com/s/3gr5xfgf8eu1rid/map.mbtiles?dl=0

**Comment by tonyfonager** [comment]
I just added and tested my 600 mb .mbtiles file on the "Samples" project - it sure loads slower that the 2 mb demo files, but its still almost instant (1-2 seconds).

That is wierd, compared to my project - gotta dig some more!

**Comment by charlenni** [comment]
I tried your file with a SQLite administration tool. If you want a special tile with zoom level 15 you need up to 200 ms to get the result. Normally you need 9 of this tiles to fill the screen, which is the same you found (around 1-2 seconds).

It would be nice, if you could inform as, what the problem was.

**Comment by tonyfonager** [comment]
Thanks. I am working on testing something new now, and will get back with the result.

But we agree - if there are 100.000 tile records in the database or 100 - it should be "almost" the same speed to fetch the tiles from the SQLite database, right ?

**Comment by tonyfonager** [comment]
Ok, finished testing more now - for some reason the initial test must have been wrong (from my end), as now it keeps taking around 40 seconds to load the map in your Forms sample (MbTilesSample) on my device.

Exactly the same as on my own app (on the device) ...

I would really love to know what going on inside that "new MbTilesTileSource()" call in the BruTile project - Paul, you have any idea why it takes so long ?

I do not have time to setup the BruTile project to debug it, but maybe someone has it loaded already and want to replace the world.mbtiles with the map.mbtiles I added a link to above - and let me know why the constructor is so slow ?

I have browsed the code from BruTile repo, but it seems so simple and the SQL inside of it I tried running manually - and they returned data very quickly.

Btw, when the data has loaded after 40 seconds - the map is very speedy / responsive, which is SUPER nice!

**Comment by pauldendulk** [comment]
The focus is the 2.0 release, so for me this is no priority. 

If I would investigate this I would first try to load it in BruTile and if it is slow there step through the code to see which part takes so long.

One thing that comes to mind is that if there is no extent explicitly specified (or specified in a way not known to BruTile) BruTile will calculate the extent based on the tiles in the file. With many tiles this could take long. I wrote this code many years ago so I don't know any details.

**Comment by tonyfonager** [comment]
Ok, I thought this was for the 2.0 release, sorry.

I will try debugging BruTile then.

Have a nice weekend.

**Comment by pauldendulk** [comment]
I assume this is BruTile issue which could be fixed independently. 

btw, If this problem does not show in 1.4.8 it will probably be a Mapsui issue.

**Comment by tonyfonager** [comment]
So I have looked a bit into the BruTile sourcecode, to see how to optimize my issues described above!

Its actually the code that scans the mbtiles database to create the extent, as you wrote. Thanks for the pointer!

I created a fix that "caches" the data inside the metadata table, so the next time the mbtiles file is being loaded - its being read from there instead of scanning the database.

But despite this, the best "fix" is to call the constructor with all the necessary information:

```
var schema = new GlobalSphericalMercator("png", YAxis.TMS, 5, 15);
var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(path, true), schema,  MbTilesType.BaseLayer, false);
```
With the above code, my loading of the map has almost no delay

**Comment by tonyfonager** [comment]
I guess we can close this ticket - its actually not really related to MapsUI after all ...

**Comment by pauldendulk** [comment]
BruTile could be improved though. Perhaps the automatic scanning is not a good idea and we should thrown an exception immediately.

**Comment by tonyfonager** [comment]
Well - its kind of handy to have the function, if you do now know how to create the schema.

So maybe we keep it, and consider adding the "caching" feature so it only happens once.

**Comment by pauldendulk** [comment]
I added an issue in BruTile

**Comment by pauldendulk** [comment]
The BruTile issue: https://github.com/BruTile/BruTile/issues/108

**Comment by pauldendulk** [comment]
In BruTile 3.0.0 the default is not to use the 'tiles' table. If minzoom and maxzoom are not present it will assume all levels of GlobalSphericalMercator are present. You can still use the 'tiles' table with the properties
- determineZoomLevelsFromTilesTable
- determineTileRangeFromTilesTable
