### ISSUE TITLE
[Forms][MapView] inconsistent initialization of MapView.MyLocationLayer.Enabled and MapView.MyLocationEnabled

### ISSUE THREAD

**Issue by tmijieux** [Mapsui/Mapsui#800]
Hello again,
I think a found another little issue with MapView (xamarin forms) :

According to the following snippet of code and common sense, the MyLocationEnabled property should reflect whether the "my location layer" is shown or not
https://github.com/Mapsui/Mapsui/blob/b13375c852fd64e49b7bbe8851918316738c2849/Mapsui.UI.Forms/MapView.cs#L600-L608

but in the MapView constructor, The MyLocationEnabled property is initialized to false at line 49 (which is the default value anyway so the PropertyChanged event is not even called) and then the _mapMyLocationLayer is instanciated with Enabled  = true on line 55
https://github.com/Mapsui/Mapsui/blob/b13375c852fd64e49b7bbe8851918316738c2849/Mapsui.UI.Forms/MapView.cs#L47-L55

As a result the MyLocation pin is initially visible even if MyLocationEnabled property is false, 
and I have to do this in order to hide it:

```c#
myMapView.MyLocationEnabled = true;
myMapView.MyLocationEnabled = false;
```

**Comment by pauldendulk** [comment]
Without further reports I assume this is fixed.

**Comment by davidce** [comment]
There is another issue with MyLocationEnabled in xaml:
example code:
             <mapsui:MapView x:Name="mapView"
             ...
             MyLocationEnabled="False"
             ... />
To enable MyLocationLayer you should set MyLocationEnabled to "False",
 In C# :
mapView.MyLocationEnabled = true; is work code to  enable MyLocationLayer
