### ISSUE TITLE
microsoft maps

### ISSUE THREAD

**Issue by dchillman123** [Mapsui/Mapsui#803]
the microsoft windows maps application can store and use offline maps.  I can access the offline maps with the UWP map control.  Is Mapsui compatible with the UWP map control for use with the windows offline maps?

**Comment by pauldendulk** [comment]
No, we have never looked at that. Do you know anything more about that format?

**Comment by dchillman123** [comment]
Not really – I am very new to mapping – I have a requirement to develop a
UWP application that uses the UWP map control for accessing offline windows
maps and am just starting to investigate my options.  Came across a
reference to the matsui and wondered if it could be of use.  From what I
have learned so far the format of the windows offline map is something
Microsoft developed.



*From:* Paul den Dulk <notifications@github.com>
*Sent:* Monday, February 3, 2020 10:36 AM
*To:* Mapsui/Mapsui <Mapsui@noreply.github.com>
*Cc:* dchillman123 <dan.hillman@state.co.us>; Author <
author@noreply.github.com>
*Subject:* Re: [Mapsui/Mapsui] microsoft maps (#803)



No, we have never looked at that. Do you know anything more about that
format?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mapsui/Mapsui/issues/803?email_source=notifications&email_token=AG6LTJGV344D653R5436SXDRBBIYDA5CNFSM4KPJBHZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKUW4CA#issuecomment-581529096>,
or unsubscribe
