### ISSUE TITLE
Possibility  to lock only Zoom in or Zoom out ? 

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#806]
I'm using a MapView in my application and I wan't to lock the zoom when the user reaches a certain level. I found the property ZoomLock in MapView but It lock both zoom (in & out). So, it is possible to only a given direction or, at least, cancel the zoom event ?

**Comment by charlenni** [comment]
See `MapView.Map.Limiter.ZoomLimits` for this.
