### ISSUE TITLE
VectorStyle

### ISSUE THREAD

**Issue by VladGluschenko** [Mapsui/Mapsui#810]
I use this code to style a shape with a dot line on the map.
`this.Styles.Add(new VectorStyle { Line = new Pen(Color.Red, 5) { PenStyle = PenStyle.Dot } });`
![question](https://user-images.githubusercontent.com/32134319/74129472-4b893300-4be8-11ea-90ac-342f9e430619.png)
I want the black thin line not to be visible. Just red dots. How can this be fixed? Thanks in advance.

**Comment by charlenni** [comment]
You don't mention, how you draw this shape. I assume, that you use a LineString. Try to use

    this.Styles.Clear();

before you set the style, so that a already set style is cleared. If this doesn't solve the problem, try to clear the style of the layer where your features is added.

**Comment by VladGluschenko** [comment]
Yes I use Linestring. I tryed to use `this.Styles.Clear()` but it does not help.

**Comment by charlenni** [comment]
It would be helpfull to know, it this is a Layer or a Feature/LineString

**Comment by charlenni** [comment]
To be clear: both of them have styles. First all features are drawn with the styles of the layers, than all features are drawn with the styles of each feature. If you set the style of the feature to red dots, but the style of the layer is a black line, than first the black line is drawn and than the red dots above it.

**Comment by VladGluschenko** [comment]
1) This is a Feature. 
2) Apparently this is the case.

**Comment by charlenni** [comment]
If your problem is solved, it would be nice, if you could close the issue.

**Comment by pauldendulk** [comment]
I added an entry for this question in the [FAQ](https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/faq.md#how-can-i-get-rid-of-the-white-dots-on-my-point-geometries-or-black-lines-on-my-linestrings-and-polygons). I have seen the question often and it was just asked again in [gitter](https://gitter.im/Mapsui/Lobby).
