### ISSUE TITLE
Offsetting map tile locations

### ISSUE THREAD

**Issue by fusionconsulting** [Mapsui/Mapsui#811]
I have a map based on the OSGB coordinate system for a single city which I would like to display as an overlay on a MapSui map. The map tiles do not sit on a MBtiles tile boundary so I'm wondering if there is a way to offset the coordinates to allow the tiles to align with the MBtiles map.

Is this possible in MapSui or would the tiles have to be realigned somehow before display?

**Comment by pauldendulk** [comment]
So, the overlay is not positioned correctly? Could you show a screenshot?

There are number of ways to fix this. 

The best way would be to fix your mbtiles dataset. The mbtiles file should contain metadata wrt it's positioning. In BruTile this is called the TileSchema. When this data is missing it is assumed it is the most common 'whole world' schema. 

An alternative is to specify the schema in code. In the code below I took part of the MBTilesOverlaySample and added a custom schema.

```csharp

        public static TileLayer CreateMbTilesLayer(string path)
        {
            var customSchema = new TileSchema();
            // todo: initialize schema
            var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(path, true), customSchema);
            var mbTilesLayer = new TileLayer(mbTilesTileSource);
            return mbTilesLayer;
        }
```
Now the question is, what is the correct schema? That is not possible for me to know. It should be known to the person who created the schema. Perhaps you could start off with a copy of BruTile's GlobalSphericalMercator schema (the whole world) and then modify some of it's parameters. Perhaps only the offset needs to be changed.

https://github.com/BruTile/BruTile/blob/master/BruTile/Predefined/GlobalSphericalMercator.cs

**Comment by fusionconsulting** [comment]
Thanks, I will get a screenshot tomorrow.

I think the issue is the schema having been looking at the source over the last few hours. It is using the whole world schema and so the tile bounds of my map do not sit on the tile bounds of the whole world "grid" (i.e. they don't match the rows/cols exactly) which is causing an offset.

So, what would be the solution to a map for example, based on bounds os OSGB (400000, 1200000) to (500000, 1300000). I would like to both display this map tileset correctly as well as restrict the view to just those tiles. I believe the latter is achieved with a ViewportLimiter which I'm looking into now but I'm not clear on how I would display the map correctly in the first place. 

I'm not an expert at mapping (as you can probably tell). Do I need to convert my coordinates to lat/lng and  then produce a custom schema to restrict to those coordinates?

**Comment by pauldendulk** [comment]
MBTiles positioning and ViewportLimiter are separate problems. Let's first get the positioning right.

Using whole schema would not be a problem if the data in your mbtiles file would be correct. The MBTiles file is an ordinary sqlite file. Please use a tool like [DB Browser for sqlite](https://sqlitebrowser.org/) to inspect your data. You can also read a bit about the [MBTiles specification](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md).

You can read a bit about projections here:
https://mapsui.com/documentation/projections.html

**Comment by fusionconsulting** [comment]
Thanks, I've actually read both of those and already using DB Browser. I guess I must be missing something in my knowledge to answer this question.

Using the Tile Map Service Specification my map tiles does not land on a tile boundary which I believe is the cause of the offset. So, at what point does this need to be adjusted? Do I need to somehow reposition the map tiles themselves before creating the SQLite DB? Or would this be something that can be adjusted via metadata (can't find anything that suggests it can be). Or could this be adjusted via a projection or schema at the Mapsui level?

Sorry if this is a simple question but I'm not from a mapping background and I'm not sure exactly where I need to be focussing to resolve this problem.

**Comment by pauldendulk** [comment]
> my map tiles does not land on a tile boundary which I believe is the cause of the offset

The tile schema of the overlay does not have to match the base layer tile schema in any way. It can have a different tiles size, different offset and even different resolutions. Mapsui has no limitations in this respect. But you do need to the set the correct schema somehow.

One hard constraint is that your tileset does need to be in the same coordinate system (projection). Mapsui can not reproject tiles and most of the time you do not want to reproject.

>  Do I need to somehow reposition the map tiles themselves before creating the SQLite DB

Well te schema needs to be correct. I understand this is not a very helpful answer but it is hard to answer this question without any knowledge of the data. How did you generate the mbtiles, where did you get it from?

**Comment by fusionconsulting** [comment]
I think I need to take a step back and go back to basics on this as I may be mistaken as to what's causing the offset. Thanks for the clarification.

Is there any documentation on creating a schema?

**Comment by pauldendulk** [comment]
Actually I expect you do not need to tweak the TileSchema in code. The tool you use to generate the tile schema should help you to generate the right schema. Perhaps there was something wrong with the parameters you choose.

A possible cause is the coordinate system, or projections. This is defined in an EPSG code. The coordinate system of the openstreetmap background map is called SphericalMercator and it in [EPSG:3857](http://epsg.io/3857). Your tileset should be generated in that same projection.

**Comment by fusionconsulting** [comment]
The tile set was created using a script I wrote to split the larger tiles into smaller JPGs and generate an MBTiles file. I've attempted to use the EPSG:3857 projection but that's where the offset issue comes from. I'm now trying to use the OSGB (EPSG:27700) projection directly and I've created a separate issue for that. I'm hoping one way or another there is a solution to this.
