### ISSUE TITLE
Function for replacing a bitmap in BitmapRegistry

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#818]
It would be nice to have a function to replace a registered bitmap with another one. With this it would be possible to replace bitmaps instead of adding always a new one.

**Comment by pauldendulk** [comment]
Does not complicate things. What is your use case?

**Comment by charlenni** [comment]
If you change an field of a callout, a new image is created, while the last is dropped. But the old one still exists. So no memory is given free. When replacing the old bitmap, the memory could given free.

**Comment by charlenni** [comment]
I could create a Replace function and make a PR.

**Comment by pauldendulk** [comment]
A PR would be great.

When would a field in a callout be changed?

**Comment by charlenni** [comment]
Up to now each time something inside the bubble changes. That could be the text or the design (size, color, font, attributes of font and so on) of the text. If this happens, than I have to create a new image for the content, which than replaces the old one.

**Comment by charlenni** [comment]
Should be solved with #821.
