### ISSUE TITLE
Ship v2

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#825]
Let's deal with the remaing issues. 

3 bugs remain that are not in testing
https://github.com/Mapsui/Mapsui/issues?q=is%3Aissue+is%3Aopen+label%3A%22bug+%F0%9F%90%9B%22

12 possible bugs
https://github.com/Mapsui/Mapsui/issues?q=is%3Aissue+is%3Aopen+label%3A%22possible+bug%22

Looks more than it is. Some are already fixed, some are not bugs and there a few we can ignore.

**Comment by charlenni** [comment]
Looks like there some more work to do 😉

**Comment by pauldendulk** [comment]
Good news. All the known bugs are in testing.

**Comment by pauldendulk** [comment]
Release 2.0.0-rc.1 https://www.nuget.org/packages/Mapsui/2.0.0-rc.1

**Comment by radderz** [comment]
@pauldendulk - given that V2 is shipped now, shall we close this?

**Comment by pauldendulk** [comment]
Yes, thanks. Closing it.
