### ISSUE TITLE
LongTap not raised on Samsung Galaxy Tab S4

### ISSUE THREAD

**Issue by ChaseMarsh** [Mapsui/Mapsui#826]
When attempting a LongTap on a Samsung Galaxy Tab S4, the map moves and does not register the LongTap. I looked at the MapControl source and saw the `touchSlop=8` added to address this issue (specifically with Samsung devices), so I created my own LongPress event and had to increase the slop to 20! Is there a better approach?

**Comment by charlenni** [comment]
No, not up to now. You could read about the problem in the source code of Android [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewConfiguration.java#162) and [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/config.xml#L2469). I assume, that your device has a higher resolution than other devices and has therefore a higher TouchSlop in the configuration file.

Up to now I don't have an idea, where to get this value from. Perhaps it should be configurable by the user.
