### ISSUE TITLE
Feature on top

### ISSUE THREAD

**Issue by reza40741** [Mapsui/Mapsui#828]
I have 2 features in a layer and I have a pin, I need to show the features on top of the pin, I create the features layer after adding pin but it doesn't work
![20200219_095033](https://user-images.githubusercontent.com/59375636/74956216-c7972e00-53d3-11ea-84d4-6deaf1f1464f.jpg)

**Comment by charlenni** [comment]
In this case: don't use pins, but use your own feature for the pin.

**Comment by reza40741** [comment]
> In this case: don't use pins, but use your own feature for the pin.

unfortunately, I cannot, because I am working with  pin location and pin_Clicked and other options

**Comment by charlenni** [comment]
Than try to add your style to Pint with

    Pin.Feature.Style.Add()
