### ISSUE TITLE
Custom Style Rendering

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#829]
@pauldendulk I uploaded a [new branch](https://github.com/charlenni/Mapsui/tree/OwnerDraw) with this functionality. Take a look and say, what you think. Could be made even less complicated with defining functio `Render` from CustomStyle as

    public virtual Render(RenderStyleArgs args);

Than there isn't any event handling.

PS: I couldn't make the WPF render part, because I don't know, how to ;-).

_Originally posted by @charlenni in https://github.com/Mapsui/Mapsui/issues/783#issuecomment-589154857_

**Comment by pauldendulk** [comment]
First, I will really not add anything that is not a bug fix.

I briefly looked. Seems to be generally what I had in mind. Perhaps it is also possible to call the customstyle callback in the RenderFeature method because any geometry could have a customstyle. My earlier idea was to have several custom styles, like you can have several kind of widgets. Perhaps this is possible by deriving from CustomStyle so that users can check the type in the callback.

**Comment by pauldendulk** [comment]
@charlenni We could also leave the implementation completely open to the user. The user can get a callback of any feature/style combination. The style could be created by the user itself. How to render this is up to the user.

For performance I would not like to call a callback just for any feature/style. Not sure how to filter there.

**Comment by charlenni** [comment]
> Perhaps it is also possible to call the customstyle callback in the RenderFeature method because any geometry could have a customstyle. 

That's a good idea.

> My earlier idea was to have several custom styles, like you can have several kind of widgets. Perhaps this is possible by deriving from CustomStyle so that users can check the type in the callback.

At the end you would have many CustomStyles. For each thing you want to draw your own style.

**Comment by charlenni** [comment]
> @charlenni We could also leave the implementation completely open to the user. The user can get a callback of any feature/style combination. The style could be created by the user itself. How to render this is up to the user.

This is even now possible. You create a style, which derives from CustomStyle. Than you implement Render, wher you draw your feature with the given style on Skia or any other renderer.

Up to now, I would like to have the predefined styles. It is easier to start for that users, that don't want to draw their own. The only, that could be done would be to replace the old styles with new ones in the new style.

> For performance I would not like to call a callback just for any feature/style. Not sure how to filter there.

Why not? If it is a CustomStyle, than you have to call Render.

**Comment by charlenni** [comment]
For me the big advantage is, that if you draw direct to the canvas, the graphics is much clearer/sharper than if you create a bitmap and draw this on the screen.

Direct draw
![grafik](https://user-images.githubusercontent.com/4381223/74972569-4450f900-5422-11ea-84d6-1ec9532cd357.png)

Draw to a bitmap and draw that
![grafik](https://user-images.githubusercontent.com/4381223/74972671-6d718980-5422-11ea-952c-d6a79ed1698a.png)

As you could see, the first is much better and sharper. I assume, that direct draw are using the full resolution, while the second draws to a unknown canvas and this have much less pixels than the screen. I prefer always the first.

**Comment by pauldendulk** [comment]
> Why not? If it is a CustomStyle, than you have to call Render.

Yes, but I was thinking about the option to call the callback for just any feature/style combination. If we do this all the time for all the feature/style combinations, even when the user is not interested in in custom rendering, this might have unnecessary influence on performance.

I like the idea of keeping things open though, no specific style, just any style the user would like to use. So, perhaps we should add another way to filter out the unwanted callback.

**Comment by charlenni** [comment]
No, the other way round. Each style is a CustomStyle. So you have to call Render for each style. A ready made SymbolStyle draws the symbol in the Render function and couldn't be changed. The same for the others. 

You now call a render function for each feature/style combination too. So why should there be a performance leg?

**Comment by pauldendulk** [comment]
> You now call a render function for each feature/style combination too. So why should there be a performance lag? 

True, it won't make a big difference. Still, I want things to go faster, not slower.

> No, the other way round. Each style is a CustomStyle. So you have to call Render for each style. A ready made SymbolStyle draws the symbol in the Render function and couldn't be changed. The same for the others.

I like the idea of having the same approach to every style but I don't see yet how you could make it so that the regular styles call only the Mapsui implementations and the custom styles call the callback.

What I was thinking of this morning might be similar. Add a CustomRender callback to IStyle. The developer instantiating the style could set it or not. When it is not set it is not called, so a low performance impact. The regular styles still draw the regular implementation as they do now, but after they are drawn the CustomRender callback is called. So a user could drawn something on top of existing styles as well.

**Comment by pauldendulk** [comment]
A more general remark about this approach. We are now discussing this with skia sharp rendering in mind. Could this callback also be used for drawing native XF elements in a XF overlay. How would that work? Perhaps you don't want to add and remove those elements every time. Perhaps the user has a list  of elements and checks if an element is already present in the list before creating it. With such an approach you might need to remove unused elements as well.

**Comment by charlenni** [comment]
> > You now call a render function for each feature/style combination too. So why should there be a performance lag?
> 
> True, it won't make a big difference. Still, I want things to go faster, not slower.
> 
> > No, the other way round. Each style is a CustomStyle. So you have to call Render for each style. A ready made SymbolStyle draws the symbol in the Render function and couldn't be changed. The same for the others.
> 
> I like the idea of having the same approach to every style but I don't see yet how you could make it so that the regular styles call only the Mapsui implementations and the custom styles call the callback.

Regular styles draw their content in the callback function as all custom styles too.

> What I was thinking of this morning might be similar. Add a CustomRender callback to IStyle. The developer instantiating the style could set it or not. When it is not set it is not called, so a low performance impact. The regular styles still draw the regular implementation as they do now, but after they are drawn the CustomRender callback is called. So a user could drawn something on top of existing styles as well.

Where is the performance gain to check, if a function is empty to call an empty function?

**Comment by charlenni** [comment]
> A more general remark about this approach. We are now discussing this with skia sharp rendering in mind. Could this callback also be used for drawing native XF elements in a XF overlay. How would that work? Perhaps you don't want to add and remove those elements every time. Perhaps the user has a list of elements and checks if an element is already present in the list before creating it. With such an approach you might need to remove unused elements as well.

If you want to do this, you could do this. The Render (or better Draw) function is called whenever the MapControl redraw the map. You could there also enable or disable other things or move a button around on the new values of your style.

I saw, that there isn’t a canvas for the Xaml renderer. There are two approaches for this:
1. Create a SKCanvas as overlay and use the normal Skia drawing function
2. Create a path and return this in the arguments. For this, I added the Result field.

**Comment by charlenni** [comment]
But with this approach you couldn’t separate data and rendering. And where to store this new styles? In Mapsui? Or in Mapsui.Rendering.Skia? Or in Mapsui.Styles as a new project?

**Comment by pauldendulk** [comment]
> But with this approach you couldn’t separate data and rendering. And where to store this new styles? In Mapsui? Or in Mapsui.Rendering.Skia? Or in Mapsui.Styles as a new project?

Are you now talking about the XF overlay or the custom renderer in general? I see separating data en rendering as a prerequisite. I think this is possible with the IStyle.CustomDraw. This is how I see it now:
- Add the IStyle.CustomDraw
- Create a BaseStyle that implements CustomDraw
- Derive all styles from BaseStyle.
- Call the CustomDraw method in some central place. 
- Call CustomDraw in some central place. Perhaps at the end of MapRenderer.RenderFeature `
  - ``if (style.CustomDraw != null) style.CustomDraw(canvas, viewport, layer, style, feature, opacity);```

The styles will hold a pointer to the method but not the implementation. The regular draw implementation does not depend on the callback.

**Comment by pauldendulk** [comment]
> Where is the performance gain to check, if a function is empty to call an empty function?

Yes, that is the only difference, pretty minimal compared to the total duration, I admit. Although copying a method to the stack and removing it is a lot work compared to a single null check.

**Comment by charlenni** [comment]
I assume, that modern compilers are so clever, that they get this.

**Comment by charlenni** [comment]
> Are you now talking about the XF overlay or the custom renderer in general? 

In general.

> I see separating data en rendering as a prerequisite. I think this is possible with the IStyle.CustomDraw. This is how I see it now:
> 
>     * Add the IStyle.CustomDraw

Add IStyle.Draw

>     * Create a BaseStyle that implements CustomDraw

Correct

>     * Derive all styles from BaseStyle.

Correct

>     * Call CustomDraw in some central place. Perhaps at the end of MapRenderer.RenderFeature `
>       
>       * ``if (style.CustomDraw != null) style.CustomDraw(canvas, viewport, layer, style, feature, opacity);```

Call IStyle.Draw always

> The styles will hold a pointer to the method but not the implementation. The regular draw implementation does not depend on the callback.

With this, you have special styles, that handled different from other styles. Why? A SymbolStyle is a style, that draws a symbol on the canvas. So its draw method draws a symbol to the canvas. Why should this style handeled different from the custom styles at a different place?

**Comment by pauldendulk** [comment]
> With this, you have special styles, that handled different from other styles. Why? A SymbolStyle is a style, that draws a symbol on the canvas. So its draw method draws a symbol to the canvas. Why should this style handeled different from the custom styles at a different place?

Could you be more specific about how you see things. Which classes? Which interfaces? Where are the implementations?

In the solution that I describe the CustomDraw method would be on the style definition and I do not want the implementation in there. How do you see that?

**Comment by charlenni** [comment]
I don’t want to have special style like now. We have, for example, a SymbolStyle, which is check in RenderFeature and is drawn by a special function. In the case of using CustomDraw, the drawing will go there. All styles are drawn by a call to CustomDraw. Only difference is, that some of the styles are predefined by Mapsui like SymbolStyle, which has an already defined CustomDraw.

But when to set this predefined functions? I don’t know, where the right place is.

**Comment by charlenni** [comment]
Perhaps IStyle.CustomDraw could be a static field?

**Comment by pauldendulk** [comment]
> I don’t want to have special style like now. We have, for example, a SymbolStyle, which is check in RenderFeature and is drawn by a special function. In the case of using CustomDraw, the drawing will go there. All styles are drawn by a call to CustomDraw. 

I understand this is what you want in a very general sense but I don't see how this is technically possible. 

> Only difference is, that some of the styles are predefined by Mapsui like SymbolStyle, which has an already defined CustomDraw.

A Mapsui style class, like SymbolStyle, can not have a render implementation because that would make it platform dependent.

**Comment by pauldendulk** [comment]
> Perhaps IStyle.CustomDraw could be a static field?

It is not possible to define a static in an interface.

**Comment by charlenni** [comment]
Why not doing it in a way the WidgetRenderer do it. You have to register a renderer for a given style. If the style has no renderer, than nothing is drawn. Default styles are registered when the renderer is created. No automatic special functions, but flexible enough for the users. If they want a new owner drawn style, they derive the style from IStyle and register an ISkiaStyleRenderer or IXamlRenderer at the renderer. When RenderFeature doesn’t find the style, than it looks in the dictionary if there is a registered renderer for this style. If yes, ok, if no, than this feature isn’t drawn. Goal is, that RenderFeature contains only this lookup for all styles. Predefined renderers like for SymbolStyle are registered in the constructor of the renderer and the SymbolStyleRenderer is an own class, which could also replaced by the user, if s/he likes another look. That’s clear and flexible.

The only problem I have: is it possible to use the renderer from an inherited class without re registering. E.g. you create NewSymbolStyle and derive from SymbolStyle. Should you then register SymbolStyleRenderer for NewSymbolStyle or could we find the next best renderer, in this case SymbolStyle, automatically?

For implementation: because it isn’t possible to have static functions in interfaces, we should move to a singleton concept as with BitmapRegistry.

Btw. last time you said to an user, that widgets could also move with the map. I didn’t understand this. When we started with widgets (I like the name Overlay more) its concept was to draw things, that stay on their place relative to the MapControl and don’t move around. If they should move with the map, than they should implemented as Features with a special Style. Isn’t this correct?

And another wish: you always work in the Master branch of Mapsui. The problem is, that I don’t get a message, if you something change. So I have to look again and again, if you worked at the code. Perhaps it would be better, if you create a new branch for your work and than merge this.

**Comment by pauldendulk** [comment]
> Why not doing it in a way the WidgetRenderer do it. You have to register a renderer for a given style. If the style has no renderer, than nothing is drawn. Default styles are registered when the renderer is created. No automatic special functions, but flexible enough for the users. If they want a new owner drawn style, they derive the style from IStyle and register an ISkiaStyleRenderer or IXamlRenderer at the renderer. When RenderFeature doesn’t find the style, than it looks in the dictionary if there is a registered renderer for this style. If yes, ok, if no, than this feature isn’t drawn. Goal is, that RenderFeature contains only this lookup for all styles. 


> Predefined renderers like for SymbolStyle are registered in the constructor of the renderer and the SymbolStyleRenderer is an own class, which could also replaced by the user, if s/he likes another look. That’s clear and flexible.

Initially I saw this as a disadvantage, things could become confusing if users mess with the default implementation while they do not understand what they are doing. My idea was to avoid this. But perhaps you are right, and it would be handy in some situations. Not sure.

In general I can see how this could be build. We already do this for the widgets, so it is possible. But it does also sound complicated. And I would say the current feature renderer is simpler than the widget renderer. 
 
> The only problem I have: is it possible to use the renderer from an inherited class without re registering. E.g. you create NewSymbolStyle and derive from SymbolStyle. Should you then register SymbolStyleRenderer for NewSymbolStyle or could we find the next best renderer, in this case SymbolStyle, automatically?

If we use type checking than it is important that the more more specific type (the custom type derived from the default type) is check before the more general type. If it is the other way around the more general type will always be selected. Actually I had this problem rewriting the PointRenderer. See here:

https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Skia/PointRenderer.cs#L37

SymbolStyle is derived from ImageStyle and should be checked first. Initially this was the other way around and the ImageStyle case was never selected.
 
> For implementation: because it isn’t possible to have static functions in interfaces, we should move to a singleton concept as with BitmapRegistry.

I see the BitmapRegistry as problematic because it has a static field. Why not use a registry like used for widgets. It is a registry on the renderer which also makes sense because that is where it applies:

```csharp
public IDictionary<Type, IWidgetRenderer> WidgetRenders { get; } = new Dictionary<Type, IWidgetRenderer>();
```

Not sure about your suggestion yet, but it made me think of a disadvantage of the IStyle.CustomDraw callback, and that is that if create many different styles for separate features (which users do most of the time) you need to register this callback for every instance you create. Typically you would like to do this only once. So, a central registry would be a better option in this respect.
 
> Btw. last time you said to an user, that widgets could also move with the map. I didn’t understand this. When we started with widgets (I like the name Overlay more) its concept was to draw things, that stay on their place relative to the MapControl and don’t move around. If they should move with the map, than they should implemented as Features with a special Style. Isn’t this correct?

I have to admit here do not have the full picture clear anymore, but I was my idea was that you are free to draw anything you want in the widgetrenderer. So I assume that this is possible. Although I am not sure if all necessary information is present in the widgetrenderer. Also, it was not completely clear how that specific case was supposed to work. Perhaps it widget does not need to be moved with the map all the time. My idea of a measure tool is that you click in the map, and drag, and you draw just at that location. If indeed this extra information needs to stay there at all times then a feature renderer would be better. That said, a measure tool is a very common thing in a GIS application and it seems to me it should typically be implemented by a widget. It this is not possible with the current implementation this should be changed.
 
> And another wish: you always work in the Master branch of Mapsui. The problem is, that I don’t get a message, if you something change. So I have to look again and again, if you worked at the code. Perhaps it would be better, if you create a new branch for your work and than merge this.

I can do that. This is actually what I am used to in other projects.

**Comment by charlenni** [comment]
I made a PR (see #839) for this, so we have a draft to discuss.

> Initially I saw this as a disadvantage, things could become confusing if users mess with the default implementation while they do not understand what they are doing. My idea was to make this impossible. But perhaps you are right, and it would be handy in some situations. Not sure.

It is now possible, because the SytleRenderers is first check, before Mapsui styles are drawn. If `Draw()` returns true, no other style renderer is checked. If it returns false, than the normal rendering process takes place.

> If we use type checking than it is important that the more more specific type (the custom type derived from the default type) is checked before the more general type. If it is the other way around the more general type will always be selected. Actually I had this problem rewriting the PointRenderer. See here:
> 
> https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Rendering.Skia/PointRenderer.cs#L37
> 
> SymbolStyle is derived from ImageStyle and should be checked first. Initially this was the other way around and the ImageStyle case was never selected.

I dropped this. If a derived style should be drawn, than you have to register a derived style renderer. It is clearer than a fallback system.

> I see the BitmapRegistry as problematic because it has a static field. Why not use a registry like used for widgets. It is a registry on the renderer which also makes sense because that is where it applies:
> 
> ```cs
> public IDictionary<Type, IWidgetRenderer> WidgetRenders { get; } = new Dictionary<Type, IWidgetRenderer>();
> ```

Did this now. Problem is the static function usage of WPF renderer.

> Not sure about your suggestion yet, but it made me think of a disadvantage of the IStyle.CustomDraw callback, and that is that if create many different styles for separate features (which users do most of the time) you need to register this callback for every instance you create. Typically you would like to do this only once. So, a central registry would be a better option in this respect.

Yes. Did it this way. Is much better.

**Comment by pauldendulk** [comment]
@charlenni May I compliment you on the Skia SpecialStyleSample. Although Mapsui has high quality standards this sample pulls Mapsui to an even higher level. It is sheer beauty. 😂

![special](https://user-images.githubusercontent.com/963462/76090360-b5b0b000-5fbb-11ea-9974-79c8e7945df2.gif)

**Comment by charlenni** [comment]
Do you touched/clicked one of this symbols?

**Comment by pauldendulk** [comment]
oh! I did just now, but will not again. I do not want to hurt the teddybears!

**Comment by charlenni** [comment]
😂

Btw. each time, they are redrawn, they get a new color. So you could see, how often the map is redrawn.

**Comment by charlenni** [comment]
I made my own NuGet package to get the new user style. But now, there is no Mapsui.Rendering.Skia.SkiaStyles. Do you have an idea, whats going wrong?

**Comment by pauldendulk** [comment]
It should be a namespace in the dll Mapsui.Rendering.Skia project. Where are you looking?

**Comment by charlenni** [comment]
At `using Mapsui.Rendering.Skia.SkiaStyles;`.

**Comment by charlenni** [comment]
I could find Mapsui.Styles.IStyleRenderer, but not the other things. Because of the first, I assume, that I have the newest sources.

**Comment by pauldendulk** [comment]
> At using Mapsui.Rendering.Skia.SkiaStyles;.

And you referenced the Mapsui.Rendering.Skia dll?

**Comment by charlenni** [comment]
I added the Mapsui and the Mapsui.Forms package. Both work correct.

I now saw, that I also missing SkiaWidgets.

**Comment by pauldendulk** [comment]
Do you have the same problem with Mapsui 2.0.0-beta.37 that was just published.

**Comment by charlenni** [comment]
I don't see it on NuGet in VS 2019 up to now.

**Comment by pauldendulk** [comment]
It was validated 9 minutes ago https://www.nuget.org/packages/Mapsui/2.0.0-beta.37

**Comment by charlenni** [comment]
I got a message, but could not see it in VS 2019. On NuGet you could see, that the latest is beta.36, but if you open the Mapsui page you could see beta.37. It seems, that it needs some time.

**Comment by pauldendulk** [comment]
Something else. There is the question how to call this functionality. We need to advertise this a bit. I would like to make a documentation page as well. It is an important improvement.  My idea was to call it Custom Styles with Custom Style Renderers. 

If we choose this. I would also like to rename the sample as well. 

What are your thoughts?

**Comment by pauldendulk** [comment]
oh, it needs to be indexed. Don't expect this to take very long.

![image](https://user-images.githubusercontent.com/963462/76097574-3ecde400-5fc8-11ea-8062-bdd17e544de6.png)

**Comment by charlenni** [comment]
> Something else. There is the question how to call this functionality. We need to advertise this a bit. I would like to make a documentation page as well. It is an important improvement. My idea was to call it Custom Styles with Custom Style Renderers.
> 
> If we choose this. I would also like to rename the sample as well.
> 
> What are your thoughts?

No problems with this. Custom Styles sounds good.

**Comment by charlenni** [comment]
Now it is ready.

**Comment by charlenni** [comment]
And no, I don't get the ISkiaStyleRenderer. It's missing.

**Comment by charlenni** [comment]
Ok, created a new Xamarin.Forms project. Added Mapsui and Mapsui.Forms to shared and platform project and created a new class, which should use as SkiaStyleRenderer. What I'm getting is

![grafik](https://user-images.githubusercontent.com/4381223/76102600-83f61400-5fd0-11ea-97b8-fdf718cef628.png)

Cursor is behind `Skia.`.

**Comment by charlenni** [comment]
Ok, found the problem. If you use the normal template in VS 2019 for Xamarin.Forms, it creates a class library and no shared project. Now dropped the library and added a shared project and now I find ISkiaStyleRenderer :-)

**Comment by pauldendulk** [comment]
@charlenni I added some documentation. 
https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/custom-style-renders.md
Feedback is welcome.

**Comment by pauldendulk** [comment]
This was implemented and is an important feature.
