### ISSUE TITLE
Idea or fix for CanvasSize null if isn't in view.

### ISSUE THREAD

**Issue by johnhs91** [Mapsui/Mapsui#842]
Don't know if it's still an issue.
But since I use Mapview in ALOT of pages on my app. I've decided to move around MapView, from 1 page to another. 
It was a fix back in my old Mapsui. Since the resources didn't get released correct. (It maybe better today)
And make my own job easier, since I don't have to move around the layers.

But when I move around view it crash on in MapControl in Mapsio.UI.Forms, because CanvasSizie is null, it make sense, since the view isn't anywhere.

It crash on first line in the method. (251 in file)

        void OnPaintSurface(object sender, SKPaintGLSurfaceEventArgs skPaintSurfaceEventArgs)
        {
            _skiaScale = (float)(CanvasSize.Width / Width);
            skPaintSurfaceEventArgs.Surface.Canvas.Scale(_skiaScale, _skiaScale);

            _renderer.Render(skPaintSurfaceEventArgs.Surface.Canvas,
                Viewport, _map.Layers, _map.Widgets, _map.BackColor);
        }

With a easy fix, change "CanvasSize.Width" to "skPaintSurfaceEventArgs.BackendRenderTarget.Width" it doesn't crash anymore. (Simply using the event objects instead of getting from class) 
Have no clue if this can make issues elsewhere. But the size have been the same untill now.

Just an idea.

Br. John Sørensen

**Comment by pauldendulk** [comment]
Oh, this crash is an issue in itself. Not sure if that was reported before.

I am not familiar with skPaintSurfaceEventArgs.BackendRenderTarget.Width. Strange that CanvasSize is null while the BackendRenderTarget.Width is not. We have to be sure this is the correct value though, on all densities.

Further we should start using PixelDensity everywhere instead of SkiaScale.

**Comment by johnhs91** [comment]
I've used on alot of difference devices android. Witch use difference densities. And haven't seen any issues yet.
But the problem is that CanvasSize isn't null. Can't make a null check, since SkiaSharp crash before that. Because it's null in their end.
That's why I had to use width from eventargs instead.

**Comment by pauldendulk** [comment]
Maybe this should be done. Perhaps next week.

**Comment by pauldendulk** [comment]
2.0.0-beta.37 was released with your suggestion to use BackendRenderTarget.Width

**Comment by pauldendulk** [comment]
The logic here was changed again for other purposes, there need to be a way to determine the PixelDensity outside of the paint loop. I noticed that CanvasSize is struct so can not be null but can be 0. I now check for this. This should be enough.

**Comment by charlenni** [comment]
@pauldendulk Could this be a problem after the PR "IsVisible" last week?
