### ISSUE TITLE
Xamarin.Forms, UWP. Exception after touch gesture has ended

### ISSUE THREAD

**Issue by Feroks** [Mapsui/Mapsui#846]
Exception happens after finger is lifted of the screen in `OnTouch` method of `MapControl`.

After debugging using Sample UWP app i have noticed that `SKTouchAction.Exited` event is called directly after `SKTouchAction.Released`. Since event Id is already removed from dictionary, it throws a "Key not found" exception.

It seems that this can be fixed by simple using `TryGetValue` method here:
https://github.com/Mapsui/Mapsui/blob/e521f21d60c077c8a5f5e917196d59f25ccc1ada/Mapsui.UI.Forms/MapControl.cs#L231-L233
Alternatively, `ConcurrentDictionary` can be used instead, because it already contains `TryRemove` method. Android and desktop UWP are working correctly.

I can make a PR, just tell me what option you prefer.

OS: Windows 1803
Platform: Xamarin.Forms UWP
MapsUi.Forms version: 2.0.0-beta36
Device: Tablet

**Comment by pauldendulk** [comment]
Thanks for your analysis! And a PR would great. I prefer the concurrent dictionary with TryRemove.

**Comment by Feroks** [comment]
Thanks for quick response, I will make PR tomorrow.
