### ISSUE TITLE
Transparent error in skia renderer

### ISSUE THREAD

**Issue by IOL0ol1** [Mapsui/Mapsui#850]
WPF.MapControl
2.0.0-beta.36

sample code add a red border, transparently filled rectangle to layer, set layer IsMapInfoLayer 
```csharp
private static ILayer CreateWritableLayer()
{
    var layer = new WritableLayer
    {
        Style = new VectorStyle { Fill = new Brush(Color.Transparent), Outline = new Pen(Color.Red) },
        IsMapInfoLayer = true
    };
    layer.Add(new Feature
    {
        Geometry = new Polygon(new LinearRing(new[]
        {
            new Point(1000000, 1000000),
            new Point(1000000, -1000000),
            new Point(-1000000, -1000000),
            new Point(-1000000, 1000000),
            new Point(1000000, 1000000)
        }))
    });
    return layer;
}
```

Listen Info events for Wpf.MapControl.
Click transparent place in rectangle, MapInfoEventArgs.MapInfo.Feature is null in Info event.
wpf renderer is work.

2.0.0-beta.33 is ok
Starting at 2.0.0-beta.34.

**Comment by pauldendulk** [comment]
When writing this feature I realized it would work like this and considered this a good thing. For instance when working bitmaps with a transparant background it would be a good thing to ignore the transparent background.

Also in this case I would think it makes sense. The users clicks on something which looks equal to the background. Why expect a response? As a developer you know there is a polygon in there, but from a user's perspective it could be a polygon with a large hole or a line forming a rectangle. 

Do you really have a use case for this? Which?

As a workaround you could add a opacity of 1 to get a response, like this:

```csharp
        private static ILayer CreateWritableLayer()
        {
            var layer = new WritableLayer
            {
                Style = new VectorStyle { Fill = new Brush(new Color(255, 255, 255, 1)), Outline = new Pen(Color.Red) },
                IsMapInfoLayer = true
            };
            layer.Add(new Feature
            {
                ["Name"] = "Transparent polygon",
                Geometry = new Polygon(new LinearRing(new[]
                {
                    new Point(1000000, 1000000),
                    new Point(1000000, -1000000),
                    new Point(-1000000, -1000000),
                    new Point(-1000000, 1000000),
                    new Point(1000000, 1000000)
                }))
            });
            return layer;
        }
```

**Comment by IOL0ol1** [comment]
> When writing this feature I realized it would work like this and considered this a good thing. For instance when working bitmaps with a transparant background it would be a good thing to ignore the transparent background.
> 
> Also in this case I would think it makes sense. The users clicks on something which looks equal to the background. Why expect a response? As a developer you know there is a polygon in there, but from a user's perspective it could be a polygon with a large hole or a line forming a rectangle.
> 
> Do you really have a use case for this? Which?
> 
> As a workaround you could add a opacity of 1 to get a response, like this:
> 
> ```cs
>         private static ILayer CreateWritableLayer()
>         {
>             var layer = new WritableLayer
>             {
>                 Style = new VectorStyle { Fill = new Brush(new Color(255, 255, 255, 1)), Outline = new Pen(Color.Red) },
>                 IsMapInfoLayer = true
>             };
>             layer.Add(new Feature
>             {
>                 ["Name"] = "Transparent polygon",
>                 Geometry = new Polygon(new LinearRing(new[]
>                 {
>                     new Point(1000000, 1000000),
>                     new Point(1000000, -1000000),
>                     new Point(-1000000, -1000000),
>                     new Point(-1000000, 1000000),
>                     new Point(1000000, 1000000)
>                 }))
>             });
>             return layer;
>         }
> ```

Using a small MapControl as a thumbnail,
There is a red box in the thumbnail representing the ViewPort of the main MapControl,
I want to be able to drag the red box to adjust the main MapControl‘s ViewPort

I think transparent element should respond to events.
Just as wpf allows you to click on controls with the background as transparent.
Only elements with an empty background (Brush is null)  are ignored.

Thank you for your advice, is an acceptable alternative.

**Comment by pauldendulk** [comment]
> Using a small MapControl as a thumbnail,
There is a red box in the thumbnail representing the ViewPort of the main MapControl,
I want to be able to drag the red box to adjust the main MapControl‘s ViewPort

Interesting. So many use cases I would never think of.

> I think transparent element should respond to events.
Just as wpf allows you to click on controls with the background as transparent.
Only elements with an empty background (Brush is null) are ignored.

ah yes, that is true. I was actually very surprised to learn a null background did not respond to events. There is even a comment in the Mapsui code about this:
https://github.com/Mapsui/Mapsui/blob/efa5ea97356b331761847cf42ff5f4f9ab0decc5/Mapsui.UI.Uwp/MapControl.cs#L44-L51

On the other hand by treating null and transparent different the user can choose. We could technically do the same. To fix this in our current logic we should somehow be able to override the user defined color when drawing for mapinfo. Perhaps this is possible with a color [transform](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/color-filters).

**Comment by charlenni** [comment]
We shouldn’t do this. I would stay with the workaround. If you fill the rectangle in the background, the next user wonders, why s/he gets with overlapping rectangles this recht and not that. And others would expect, that you only could touch the line around and not the transparent inside.

**Comment by pauldendulk** [comment]
Yes, this could be confusing. Nevertheless it could be an option to allow developers to use a non-touchable transparency. It should not be the default though. 

Personally I found the difference between null and a transparent color in WPF very confusing. A very implicit way to distinguish between touch and no touch. And why is color related to touch al all? So if we add this it should be more explicit. Perhaps we could add a Color.TransparentWithoutTouch.

Then again, the current workaround is just fine and we have other priorities. So, lets leave this for now.
