### ISSUE TITLE
Exception when moving the map - Android

### ISSUE THREAD

**Issue by hajmajeboss** [Mapsui/Mapsui#852]
My map in  Android keeps crashing quite frequently, this is one of the exceptions:
Unable to decode stream: java.io.FileNotFoundException: /data/system_ce/0/recent_images/...

It seems to be somehow related to bitmaps, I cannot post entire stack trace, as I can't replicate the bug now - seems like a minor one . Most of the crashes are related to segfault caused by SkiaSharp .so library.

**Comment by pauldendulk** [comment]
Issue at SkiaSharp:
mono/SkiaSharp#1168

**Comment by hajmajeboss** [comment]
No, it's different bug, that segfault.

**Comment by hajmajeboss** [comment]
The segfault is also not related to SkiaSharp. I used addr2line and it found the address only in libxamarin-debug-app-helper.so.

**Comment by pauldendulk** [comment]
So file access. How to relate that to Mapsui? Do you make map screenshots? Do you use mbtiles?

**Comment by hajmajeboss** [comment]
`xamarin::android::internal::BasicAndroidSystem::for_each_apk(_JNIEnv*, xamarin::android::jstring_array_wrapper&, void (xamarin::android::internal::BasicAndroidSystem::*)(char const*, unsigned int, unsigned int, void*), void*)
shared-constants.cc:?`

The failing method.

**Comment by pauldendulk** [comment]
Do you think this is relate to Mapsui? How would it? At what moment does this happen?

**Comment by hajmajeboss** [comment]
When working with the map - zoom, pan...

**Comment by hajmajeboss** [comment]
Maybe this is the cause for other crashes in GUI as well, I don't have the stacktrace and it probably was a segfault. Will look into it. The bitmap error is however most probably related to Mapsui.

**Comment by pauldendulk** [comment]
At this point I do not have a clue how failure to access a file could be related to our panning/rendering logic.

**Comment by pauldendulk** [comment]
>  The bitmap error is however most probably related to Mapsui.

But how? Mapsui does not store bitmaps.

**Comment by hajmajeboss** [comment]
I thought there might be some kind of tile cache stored in system memory. I don't know much about the implementation itself.

**Comment by hajmajeboss** [comment]
It's not crashing in release configuration, because the problematic library is not present.

**Comment by pauldendulk** [comment]
We keep bitmaps in working memory but do not store them anywhere.

**Comment by hajmajeboss** [comment]
Ok, it's unrelated then.
