### ISSUE TITLE
Delay in fetching data in Layer

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#854]
There is a small delay in fetching data to avoid a continuous battering of requests to the datasource.  This is managed by the Delayer class. The behavior of this class could perhaps be improved.

**Comment by pauldendulk** [comment]
@hajmajeboss You mentioned an issue with fetch of data van sqlite with the Layer class. I made some improvements to the Delayer it uses which I am about to commit. Could you check if it behave as you would expect?

**Comment by hajmajeboss** [comment]
I'm in a train right now, will have a look later.

**Comment by pauldendulk** [comment]
Some improvements have been made to the Delayer. Other improvements could be the use of majorChange versus minorChange. A first thing to do is to create an enum with 'DiscreteChange' (for +/- buttons, mouse up and specific navigator command) and 
'ContinuousChange' (for mousewheel and pan). That will have to be discussed in another issue. Closing for now.
