### ISSUE TITLE
Zoom out on RasterizingLayer - wierd jagged scaling of LineString (Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#867]
I am using the RasterizingLayer to display some routes on a map - due to the high amount of points, this layers type performs much better inside my app.

But something weird is going on, - when you zoom out on the map it of course becomes smaller - but it starts creating weird spikes and in the end it becomes like a little jagged star (in my case).

Take a look at this video - its a Forms project on IOS : https://youtu.be/f0E3CxoTUUA

I briefly had a discussion with @charlenni about this before, asking him if they did something with the linestring points, like skipping points - which would make the lines change in zoomed out situations.

**Comment by charlenni** [comment]
For me it looks more like a problem with line path rendering. If you have small angles between lines and use miter as line joints, than you could get problems. Try to use bevel or round as line join.

**Comment by tonyfonager** [comment]
?? I just use the LineString feature ....

**Comment by charlenni** [comment]
Yes, but to do this, your style uses a Pen, which holds informations about color and so on. And one part of Pen is the StrokeJoin type. This is by default set to StrokeJoin.Miter. Try to change this.

**Comment by tonyfonager** [comment]
> Yes, but to do this, your style uses a Pen, which holds informations about color and so on. And one part of Pen is the StrokeJoin type. This is by default set to StrokeJoin.Miter. Try to change this.

Thanks, I will try "playing" with that 👍

**Comment by tonyfonager** [comment]
Looks like it fixed it - thanks 👍

**Comment by pauldendulk** [comment]
@tonyfonager what did you use instead? Maybe we should change the default.

**Comment by tonyfonager** [comment]
I changed it to using "StrokeJoin.Round" - much better result 👍
