### ISSUE TITLE
Can not resolve reference: 'Topten.RichTextKit'

### ISSUE THREAD

**Issue by SebastianKruseWago** [Mapsui/Mapsui#868]
After updating Mapsui 2.0 from beta 30 to beta 37, the compilation fails with this error: 

> error XA2002: Can not resolve reference: `Topten.RichTextKit`, referenced by `Mapsui.Rendering.Skia`. Please add a NuGet package or assembly reference for `Topten.RichTextKit`, or remove the reference to `Mapsui.Rendering.Skia`.

**Comment by tonyfonager** [comment]
You need to add in manually to your project via NuGet - jus search for "Topten.RichTextKit" and add it.

**Comment by SebastianKruseWago** [comment]
@tonyfonager yes, I know how to solve the compiler problem. That however dosn't change the fact that a package should install all of it's dependencies on it's own.

**Comment by tonyfonager** [comment]
Ohhhh okay! Maybe because its a beta version ?

**Comment by charlenni** [comment]
Oh, more may be because @pauldendulk forgot to include it ;-)

**Comment by SebastianKruseWago** [comment]
@tonyfonager And that means I should not report errors? I just reported it so that @pauldendulk is aware of it. And as far as I know, the Issue section on github are the proper section for it.

**Comment by tonyfonager** [comment]
> @tonyfonager And that means I should not report errors? I just reported it so that @pauldendulk is aware of it. And as far as I know, the Issue section on github are the proper section for it.

Of course you should 👍

**Comment by pauldendulk** [comment]
oh no! not again. 😳

I will add it to the nuspec. Thanks for reporting.

**Comment by pauldendulk** [comment]
This should be fixed in 2.0.0-beta.38.
