### ISSUE TITLE
MapView in Xamarin.Forms and "Hot Reload" goes blank ?

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#869]
Hi there,

When working on Xamarin.Forms app one of the cool things is "Hot Reload", where you can reload UI and controls while debugging on a device.

But, at least in my app, when a "Hot Reload" is being performed the MapView control comes back with default settings and widgets, and no content added to it.

Any idea if/how this can be improved ?

Tested in iOS 13, newest VS 4 Mac and beta 28 on Mapsui (was also an issue on the newest betas)

**Comment by pauldendulk** [comment]
I never tested Hot Relead. In my life so far I have never seen fancy features like this actually work. It is just very exiting when you see the first demo, and later on it is just a cause for more bugs. 

This is an example. We develop a component that does not work with Hot Reload. How is this supposed to work? Should every individual component developer test for Hot Reload? Will they?

**Comment by tonyfonager** [comment]
Ok.
