### ISSUE TITLE
Mapsui.Forms requires Xamarin.Forms < 4.4.0?

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#870]
Is there any reason to restrict Xamarin.Forms to <4.4.0 in the nuspec? I'm currently testing the new changes to Xamarin.Forms in 4.4.0 and 4.5.0 which lead my project to upgrade to the latest version of Xamarin.Forms. Currently, through Mapsui, my app also contains a second Xamarin.Forms version which increases the app size.

**Comment by pauldendulk** [comment]
I am always a bit conservative. Did not test with higher versions. But if this is a problem for the users we have to be less limiting. I will limit it to < 5.0.

**Comment by pauldendulk** [comment]
This should be fixed in 2.0.0-beta.38.
