### ISSUE TITLE
MemoryLayer based on dynamic list of Features - not updating

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#871]
I have a MemoryLayer, which is initialised and based on a List<Feature> collection. Initially there is 1 feature in this collection, but with a timer I randomly add additional features to this collection.

But they are not appearing on my layers - I can with success change the initial feature and fx. move it around, but the new features added to the feature collection are not appearing.

Is there any trick / method I need to call, or am I misunderstanding how it works ?

**Comment by pauldendulk** [comment]
You can call Layer.DataHasChanged to indicate a change in the data. Did you try this?

**Comment by tonyfonager** [comment]
Yes, I did try that.

But it suddenly hits me, that it might be related to the fact that I am running beta 28.

**Comment by pauldendulk** [comment]
I would expect this to work on beta 28 as well. Could you show me some code??

**Comment by tonyfonager** [comment]
I have a MemoryLayer where the datasource is based on a list of features - when the layer is created, and I for example initially add 3 features, they are rendered fine :

> private List<Feature> featureCollection = new List<Feature>();
> 
> featureCollection.Add(feature1);
> featureCollection.Add(feature2);
> featureCollection.Add(feature3);
> 
> DataSource = new MemoryProvider(featureCollection);
> 

Later I add new features to this list and then calls "DataHasChanged()" on that MemoryLayer, but it did not update. I also started using "mapView.Refresh()" as seen in the "mylocation" layer code.

I ended up replacing the datasource, and then calling mapView refresh which resulted in my features updating :

> DataSource = new MemoryProvider(featureCollection);
> mapView.Refresh();
> 

... currently I only have few features on this layer, so not sure if this is a bad way performance wise - but it gets my layer updated 👍

**Comment by pauldendulk** [comment]
For editing you should use the WritableLayer. We should be more clean in this. 

Perhaps we can prevent your mistake by altering the MemoryLayer/MemoryProvider. How do you add the Features to the MemoryProvider?

**Comment by tonyfonager** [comment]
I just examined the WritableLayer - I did something "more or less" like that, but I prefer using the builtin objects, so have changed it to use the WritableLayer now.

Thanks for the pointer 👍
