### ISSUE TITLE
TouchMove

### ISSUE THREAD

**Issue by VladGluschenko** [Mapsui/Mapsui#872]
"Touchmove event" doesn't work for me, but "mousemove" and "touchdown" works fine. Can anyone come across a similar problem?

**Comment by pauldendulk** [comment]
Which plaform, which version?

**Comment by VladGluschenko** [comment]
It's wpf, 1.4.8

**Comment by VladGluschenko** [comment]
Maybe does someone have example with touchmoving of feature

**Comment by pauldendulk** [comment]
Mapsui.Sample.Wpf.Editing demonstrates moving, adding and deleting features.

**Comment by pauldendulk** [comment]
btw, for WPF I would advice to go with the latest beta. It is stable and would have been released if not for problems with the GL renderer on Android and iOS.
