### ISSUE TITLE
Rotated labels

### ISSUE THREAD

**Issue by hajmajeboss** [Mapsui/Mapsui#876]
Hello,
is it anyhow possible to rotate labels (LabelStyle)? 

I need the labels to get fixed rotation and stay like that no matter the viewport's rotation.

**Comment by hajmajeboss** [comment]
![Screenshot_20200323-175328~2](https://user-images.githubusercontent.com/29458619/77341767-8629d380-6d2f-11ea-86fb-ff18a75728d4.png)

**Comment by hajmajeboss** [comment]
Screenshot is Cordova version of our app using OpenLayers.

**Comment by charlenni** [comment]
After a short look into LabelRenderer, it seems, that this isn't possible.

**Comment by hajmajeboss** [comment]
Yes, I guess. 

I started the issue to possibly discuss any possibilites, including editing the renderer somehow.

**Comment by hajmajeboss** [comment]
Took another look at the label renderer and sadly, it doesn't look possible.

**Comment by charlenni** [comment]
Try to use the new user defined renderers. You get a canvas and can draw whatever you want. Should be possible and not so difficult.

**Comment by hajmajeboss** [comment]
I get a Skia canvas? There is no such method that allows me to draw rotated text (DrawText()).

**Comment by charlenni** [comment]
Yes, you get one. And you don’t rotate the text, you rotate the canvas in the other direction and than draw the text.

**Comment by hajmajeboss** [comment]
Well, there will be one canvas for one label? It won't work otherwise, I need every label to have different rotation.

**Comment by charlenni** [comment]
It is always the same canvas. But you could rotate it for each draw in another direction.

    canvas.Save();
    canvas.Rotate(30);
    canvas.Restore();
    canvas.Save();
    canvas.Rotate(12);
    canvas.Restore();

Or you could rotate by the difference.

**Comment by hajmajeboss** [comment]
Ok, will try. Thank you.

**Comment by charlenni** [comment]
See [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/transforms/rotate).

**Comment by pauldendulk** [comment]
Good. Custom renderers are really helpful here. First because everyone can solve their own problems. Second because this will result in more merge requests for new functionality.

**Comment by hajmajeboss** [comment]
![mapsui](https://user-images.githubusercontent.com/29458619/77446529-d025be80-6dee-11ea-81e4-9145b0eb918d.jpg)

Worked like a charm. Thank you for the advice.

**Comment by pauldendulk** [comment]
@hajmajeboss Perhaps it is possible to create a PR out of this. I guess LabelStyle should get a Rotation field. Anything else? Could there be complications?

**Comment by hajmajeboss** [comment]
Why not add Rotation property and RotareWithMap property to LabelStyle and render it accordingly?

**Comment by leo-costa** [comment]
Hello ! I ran into this problem today and I'm wondering if there could be a PR for this with what @hajmajeboss had mentioned above

**Comment by pauldendulk** [comment]
@leo-costa Yes, this is an addition that makes sense. Rotate and RotateWithMap could be seen as separate issues but for the feature described above you will need both. 

This is the current functionality.

![image](https://user-images.githubusercontent.com/963462/90801423-294e3b80-e316-11ea-98cd-7f22eb5e65a7.png)

The labels don't rotate. Which is what you want in most cases.

## RotateWithMap 
RotateWithMap should be a boolean. Should default be false. If true the label will rotate with the map, so in the screenshot above the labels would be rotated 45 degrees. Not a common use case in itself.

## Rotate
Individual rotation of the label. If RotateWithMap is false they will simply be rotated relative to the top of the form. If RotateWithMap is true they will be rotated relative to the north of the map.

**Comment by pauldendulk** [comment]
@leo-costa I created a new issue for this, lets discuss this there:
https://github.com/Mapsui/Mapsui/issues/983
