### ISSUE TITLE
AnimatedNavigator gets replaced with plain Navigator

### ISSUE THREAD

**Issue by hajmajeboss** [Mapsui/Mapsui#879]
Hello, it's me again.

I noticed there is (probably new) AnimatedNavigator feature and wanted to used it for moving to GPS location and rotating the map to north.

However, it seems the AnimatedNavigator gets replaced with plain Navigator somewhere in the process and then it crashes with invalid cast exception.

Do I need to always set the navigator before casting it to AnimatedNavigator, or where could be the problem?

**Comment by hajmajeboss** [comment]
I see now, it gets rewritten when MapControl.Map property is set. 

I set it pretty often to make it redraw in MvvmCross viewmodel, I will take a look, if it's possible to do it any other way.

**Comment by pauldendulk** [comment]
We never really got AnimatedNavigator properly working. Have to look into this.

**Comment by hajmajeboss** [comment]
I replaced it in the setter of Map property in MapControl.cs and it works just fine, I'm going to stick to that for the moment.

**Comment by pauldendulk** [comment]
Yes, the AnimatedNavigator might work correctly itself but other parts might not interact well with it. Have to figure out how to fix the issue with the Map setter. Some things are too tightly coupled.

**Comment by hajmajeboss** [comment]
Create NavigatorMode enum and set it according to that, the way you went with rendering modes? I will report if anything crashes with the animated navigator, so far all good.

**Comment by charlenni** [comment]
The problem with AnimatedNavigator was, that it couldn’t be set by default and that @pauldendulk said, that this shouldn’t happen before V2. So I added it as possibility, but you have to set it by hand when you create the Map. Normally users create Map only once, and so it shouldn’t be a problem. Why do you create more than one Map?

**Comment by hajmajeboss** [comment]
To refresh it. I should use RefreshData() method probably.

**Comment by charlenni** [comment]
But than you will add always the same Map? Or do you create always a new Map, add all layers and so on?

**Comment by hajmajeboss** [comment]
Always the same map. I use MVVMCross, created a binding for Map property in MapControl and once I change the property in my VM, it changes the property in MapControl, thus calling the setter method and replacing Navigator. 

It somehow refreshes data shown on screen. I'm looking into replacing it with RefreshData(), I didn't know which bounding box and resolution should I use back then - or better said, where to get such data.

**Comment by charlenni** [comment]
Do you want to refresh the data or to redraw the screen?

**Comment by hajmajeboss** [comment]
Refresh the data - I need to refresh points position in realtime when moving it around the map in Draw mode and immediately see the change on screen.

**Comment by charlenni** [comment]
Did you tried `MapControl.Refresh()` or `MapControl.RefreshGraphics()`? And if this doesn't work, do you use a [WritableLayer](https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Layers/WritableLayer.cs) for your Features?

**Comment by charlenni** [comment]
Could you test the AnimatedNavigator a little bit more? If yes, any problems so far? Perhaps it could now move to standrad Mapsui.

**Comment by hajmajeboss** [comment]
I'm using it since then and didn't notice any problems at all.

**Comment by charlenni** [comment]
Thank you for your fast answer.

**Comment by pauldendulk** [comment]
@charlenni @hajmajeboss So, what is the summary? It this properly solved or it this still a workaround?

**Comment by hajmajeboss** [comment]
When you set the map, you have to set the navigator after, or you go back to plain navigator. I solved it by changing Map setter in MapControl to always use AnimatedNavigator. No problems since then.

**Comment by charlenni** [comment]
It is still open. The problem is, that Mapsui already set a Navigator when you add the map to the MapControl. I‘m not sure, so I have to look into this again when I at home.

**Comment by pauldendulk** [comment]
thanks, looks like something we should fix, at least for 3.0.

**Comment by pauldendulk** [comment]
This is not relevant anymore. In v4 there is no Navigator interface but just a single Navigator that support animations.
