### ISSUE TITLE
Unable to create custom widgets in Mapsui.Forms

### ISSUE THREAD

**Issue by EngineerCoding** [Mapsui/Mapsui#881]
In dotnet standard projects, it is currently impossible to create custom widgets since the required `ISkiaWidgetRenderer` is not available in the `Mapsui.Forms` NuGet package. This can be solved by referencing the `Mapsui.Rendering.Skia` dll in the NuGet package.

For reference this was discussed with @pauldendulk in gitter. A quote about how to solve the problem:

> I think I understand the problem. In our nuspec we define which dlls belong to which project type.
> Currently only Mapsui en Mapsui.Geometries are added there. The Forms core project is of type netstandard, so only those dlls were added. Originally this made sense because nothing else was needed, but with the introduction of widgets with possible custom implementations in skia it makes sense to add Mapsui.Rendering.Skia to the netstandard list.

**Comment by pauldendulk** [comment]
Thanks for reporting this.

**Comment by pauldendulk** [comment]
No further reports. Assumed fixed.
