### ISSUE TITLE
Bug in LayerCollection.Clear()

### ISSUE THREAD

**Issue by ondrasvoboda** [Mapsui/Mapsui#882]
Hi, 
I believe there is a bug in LayerCollection.Clear() on this line:
https://github.com/Mapsui/Mapsui/blob/9ff08d79507c6c8833156435e111694ac475f243/Mapsui/Layers/LayerCollection.cs#L50

Calling this doesn't clear the layers collection, it is just copied.

**Comment by pauldendulk** [comment]
oh! looks you are right. I must have recently introduced this when making the LayerCollection thread save. Just the 'copy' argument needs to be removed.

I expect this will be fixed with the next release tomorrow or the day after.

**Comment by ondrasvoboda** [comment]
I can confirm this is fixed in 2.0.0-rc.2.
Thanks!

**Comment by pauldendulk** [comment]
Thanks for the feedback.
