### ISSUE TITLE
Attribution issues

### ISSUE THREAD

**Issue by ondrasvoboda** [Mapsui/Mapsui#883]
I have two ideas about layer attributions, might be bug or feature request.

- attribution is visible even if layer is disabled (I would expect to be hidden)

- if there are more layers with attributions they draw over each other

**Comment by pauldendulk** [comment]
Thanks for the report. I never implemented the 'hide when disabled'. Maybe it is easy.

I though I did implement stacking of attributions at some point, or some other solution. I will take a look.

**Comment by pauldendulk** [comment]
Don't render when layer is disabled was easy to add.

**Comment by pauldendulk** [comment]
I also looked at attributions drawn over each other. Apparently I never implemented this. I created a little method to stack them on top of each other but I don't think it should be added to Mapsui. You can use a method like this in your code so this could be a workaround for you. 

### Workaround
The attribution is a Hyperlink widget on the Layer. You can position this Hyperlink widget to your liking. This method stacks them on top of each other.

```csharp
        public static void PlaceAboveEachOther(IEnumerable<ILayer> layers)
        {
            var attributions = layers.Where(l => l.Enabled).Select(l => l.Attribution).Where(w => w != null).ToList();
            var counter = 0;
            var attributionHeight = 16;
            var startOffset = 3;

            foreach (var attribution in attributions)
            {
                attribution.MarginY = startOffset + counter * attributionHeight;
                counter++;
            }
        }
```

It takes into account the the Enabled status. If one of the layers is disabled the other is at the bottom. It looks like this is what you want.

### Why not in Mapsui?
The Hyperlink is a widget that could be positioned by the user. It has an alignment which is default to bottom right, but it could also top left. If a user chooses different alignment for different attributions the method above would make no sense. Also a user could use different margins and offsets. So the idea right now is that the attribution positioning has a default, which is bottom right, but as a user can position by choise.

### Future
A better solution would probably be to just put attribution info in the layer, not a widget, and add a single widget for all layers which gets the layer list as input.

**Comment by ondrasvoboda** [comment]
Thanks for fixing the first issue and providing workaround for the second issue. I'm OK with that and your future solution sounds great.

**Comment by ondrasvoboda** [comment]
One more thing: when OSM layer is hidden, it's attribution is correctly hidden as well, but when you click on place when it was - https://www.openstreetmap.org/copyright is still being opened in browser.  Probably little bug in hit test, not considering that layer is disabled.

**Comment by pauldendulk** [comment]
Hmm, silly, The touch logic is fully independent of the widget rendering and over there it no knowledge about layer. I think I should add an Enabled field to IWidget which determines if it is drawn and touchable.

**Comment by ondrasvoboda** [comment]
That would be good solution and useful also in other use-cases (I myself was recently looking for Enabled field in IWidget).

**Comment by pauldendulk** [comment]
>I myself was recently looking for Enabled field in IWidget

ah, good to know.

**Comment by pauldendulk** [comment]
Added IWidget.Enabled which should fix avoid the click event when disabled.
https://github.com/Mapsui/Mapsui/pull/901

**Comment by ondrasvoboda** [comment]
Hi, I can confirm this works, thanks!

**Comment by pauldendulk** [comment]
@ondrasvoboda Thank you very much for your quick feedback.
