### ISSUE TITLE
Callout can't show text

### ISSUE THREAD

**Issue by Masobaker** [Mapsui/Mapsui#888]
In the "ManyPinSample" How it can't show text in callout.the random kind of the callout can't show the callout text,only can show the bitmap.
All test in Android 8.0 (SkiaSharp 1.68.2-preview.43).

**Comment by charlenni** [comment]
Sorry, there was a bug in one of the last PRs. Should be solved by PR #889.

**Comment by pauldendulk** [comment]
Thanks @Masobaker and @charlenni. The fix will be released in rc.3.
