### ISSUE TITLE
Pin click firing twice on rc-2 with forms UWP, iOS, Android

### ISSUE THREAD

**Issue by sailman342** [Mapsui/Mapsui#893]
I am surprised nobody mentionned Pin Click event is fired twice on Forms UWP, iOS (simu and phone) and Android, !  Working nice on MacOs and WPF, 

Should I be the only one ?

**Comment by sailman342** [comment]
If it can help, here is the sequence of events

This is my handler

![image](https://user-images.githubusercontent.com/58634016/79236799-ba476e80-7e6d-11ea-8126-f9279eba5a32.png)

this is the Mapsui mapControl.cs code

![image](https://user-images.githubusercontent.com/58634016/79236991-f084ee00-7e6d-11ea-8f1c-9b95dba34063.png)
the sequence is the Following

MapControl line 661
My handler line 126
MapControl line 668
My handler line 126

then I click the modal alert OK window 
My Handler line 127

then I click a second time the modal alert OK window 
My Handler line 127

Seems like while I am setting e.handled = true, Mapsui don't wait on it and continues the code …

**Comment by charlenni** [comment]
I tested it and there are no double click events.

Your problem is, that you don't tell Mapsui, that you already handled the event. In the above example you should set the Handled flag before you show your dialog. In the async/await construct, your handler returns, before Handled is set to true.

**Comment by sailman342** [comment]
OOOOOPS I will finish the day a bit less stupid that it started :-)

Just to tell you for the fun, I was wondering why I had sometime map events when clicking on the pin …

if by accident you click in the transparent hole you get a map clicked instead :-)

Thanks ...

**Comment by charlenni** [comment]
Yes, that is because of the routine we check for the click event. Only when you click on a colored pixel you get an event.

If the issue is solved, could you please close the issue?

**Comment by sailman342** [comment]
Yes, thanks :-)
