### ISSUE TITLE
Zoom buttons inoperand on rc-2 Forms with WPF

### ISSUE THREAD

**Issue by sailman342** [Mapsui/Mapsui#894]
The problem of the map over all buttons seems resolved by having Mapsui using SKCanvasView instead of SKGLView see #892 

Remains the WPF zoom buttons are now shown but will not react,

**Comment by charlenni** [comment]
You are talking about the buttons in the right top corner of the map. And you say, you could see them, but you couldn’t hit them. Is this right? What’s happening, if you click on them? Nothing?

**Comment by sailman342** [comment]
Yes, when Mapsui was build with SKGLView, the map was over everything including the DisplayAlert messages and the buttons … now that I rebuild with SKCanvasView, the buttons (mine) and DisplayAlert are functionning correctly. 

The right top  corner buttons now appear (they were hidden before) but they are inoperand. If I click, Nothing.

To get my buttons working on Forms WPF I had to set the Absolute position and flags directly on the buttons, doing that on the enclosing Absolute Layout didn't work, very likely a problem in the forms.wpf implementation !

Have a look on #892  

```
				if (Device.RuntimePlatform == Device.WPF)
				{
					// for wpf bounds must be on canvas why ?
					AbsoluteLayout.SetLayoutBounds(canvasView, new Rectangle(0.5, 0.5, 100, 100));
					AbsoluteLayout.SetLayoutFlags(canvasView, AbsoluteLayoutFlags.PositionProportional);
					mapAbsoluteLayout.Children.Add(canvasView);
				}
				else
				{
					// here bounds on canvas will not work !
					absoluteLayout = new AbsoluteLayout();
					AbsoluteLayout.SetLayoutBounds(absoluteLayout, new Rectangle(0.5,0.5,100,100));
					AbsoluteLayout.SetLayoutFlags(absoluteLayout, AbsoluteLayoutFlags.PositionProportional);
					absoluteLayout.Children.Add(canvasView);
					mapAbsoluteLayout.Children.Add(absoluteLayout);
				}
```

**Comment by charlenni** [comment]
I assume, that this is a Xamarin.Forms or SkiaSharp WPF problem. You should create a small sample only with SkiaSharp SKGLView without Mapsui and test this, if it works. If not, try to use only an OpenGL view of Xamarin.Forms. Create an issue for the right system.

SKCanvasView is much slower than SKGLView. Perhaps you don't have enough workload to test this. Try one of the samples with much workload.

**Comment by sailman342** [comment]
I followed your wise advice and did a bit more testing. 

Changing in my test program a SKCanvasView (used as button) to SKGLView with exactly the same code resulted in an inoperand button (no Mapsui) !

My conclusion is that the SkiaSharp GL and Forms WPF are not that much compatible and Nothing to do with Mapsui (I would have preferred as you are very reactive)
