### ISSUE TITLE
Use EventToCommand on Drawable

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#899]
I'm using a MVVM pattern in my application and I want to use command on the event "Clicked" on drawable object in Mapsui.UI.Forms.
Did someone alerady did this or at least, it is possible ? 
Thank's !

**Comment by pauldendulk** [comment]
What exactly are you asking for? Clicked is not an ICommand but you ask how it could be used as a ICommand? Should it be wrapped in a command?

**Comment by xFoRdeX** [comment]
Yes that's it. I want to use it as a Command.

**Comment by charlenni** [comment]
You could do this via a Behavior. See [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior).
