### ISSUE TITLE
Event click not trigger for drawables with linear ring for feature

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#900]
I'm using the Drawables collection for all my feature. When I create a drawable which the feature is a polygon, I can use use the event click perfectly. 
But when the feature is a linear ring, the event is not trigger. 
Do you know if an option exist for this or if it's just a bug ? 

Thank's !

**Comment by charlenni** [comment]
For drawables you can only use polygons and polylines. I did looked, but if I know it correct, there are no LinearRings as drawables.

**Comment by xFoRdeX** [comment]
I tried with a polyline like this :  
`Drawable drawable = new Polyline { BindingContext = rou, IsClickable = true, StrokeColor = new Color(ColorView.R, ColorView.G, ColorView.B), StrokeWidth = 6 };
                            
                            if (drawable is Polyline polyline)
                            {
                                foreach (MP pointsMP in points)
                                {
                                    polyline.Positions.Add(new Position(pointsMP.X, pointsMP.Y));
                                }
                            }
                            
                            drawable.Clicked += RouteClicked;`

But the event isn't trigger too

**Comment by charlenni** [comment]
I added the following lines into the "Add Polyline Sample" ([PolylineSample.cs](https://github.com/Mapsui/Mapsui/blob/4661ed3dd16b49954423014b06ababd95e7f47ed/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/PolylineSample.cs#L25))

                if (mapView.Drawables.Count == 0)
                {
                    f = new Polyline { StrokeWidth = 4, StrokeColor = Color.Red, IsClickable = true };
                    f.Clicked += (send, arg) =>
                    {
                        var taps = arg.NumOfTaps;
                    };
                    mapView.Drawables.Add(f);
                }

There the click work perfect.

Do you have problems ti hit the line? Is it very small? Could you increase the line width and test it again?

**Comment by xFoRdeX** [comment]
I added your to code to my code but it doesn't change anything. I increased the width to 6 but the click still doesn't work...

**Comment by charlenni** [comment]
Could you test it with the original Mapsui sample for Forms? Cloud you provide a small sample to reproduce this?

**Comment by xFoRdeX** [comment]
I already try on the original Mapsui sample and, like you, that works.
There is my code if you want : 
```
 Drawable drawable = new Polyline { BindingContext = rou, IsClickable = true, StrokeColor = new Color(ColorView.R, ColorView.G, ColorView.B), StrokeWidth = 6 };
                            if (drawable is Polyline polyline)
                            {
                                foreach (MP pointsMP in pointEtapesMapsui)
                                {
                                    polyline.Positions.Add(new Position(pointsMP.X, pointsMP.Y));
                                }
                            }
                            Drawable drawablePoint = new Drawable { BindingContext = rou, IsClickable = true, Feature = point };

                            drawable.Clicked += (send, arg) =>
                            {
                                var taps = arg.NumOfTaps;
                            };

                            MapView.Drawables.Add(drawable);
```

**Comment by charlenni** [comment]
Then you do something different to the sample. The code looks ok.

So I suggest to create a small sample, so I could check, what's going wrong.

**Comment by charlenni** [comment]
Any news for this issue? If you meanwhile solved it, could you please close it?

**Comment by pauldendulk** [comment]
No response from submitter. Assuming this was fixed.
