### ISSUE TITLE
Question: UIWebView is used in iOS ?

### ISSUE THREAD

**Issue by felipechavez** [Mapsui/Mapsui#903]
Hi all, we got problems publishing our app in iOS, and we don't know if this nuget use WebView for open the attribution (the link to open OpenStreetmap on the right side corner).

We are getting this email:

> 
> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, XXXXX. Please correct the following issues, then upload again.
> 
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Thanks in advance.

**Comment by charlenni** [comment]
Do you use Mapsui.iOS or Mapsui.Forms?

**Comment by charlenni** [comment]
On iOS Mapsui uses this [code](https://github.com/Mapsui/Mapsui/blob/51054029b416fbff512de1a1ec297b17771ef07d/Mapsui.UI.iOS/MapControl.cs#L211).

**Comment by charlenni** [comment]
I assume, that you use Mapsui.Forms and get into trouble with [this](https://github.com/xamarin/Xamarin.Forms-api-docs/issues/159).

Had to check, if there is a solution.

**Comment by charlenni** [comment]
Find a description and solution [here](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/user-interface/webview?tabs=windows#uiwebview-deprecation-and-app-store-rejection-itms-90809).

**Comment by felipechavez** [comment]
Hi @charlenni , thanks for the quick response. The problem was the Xamarin Forms version that we use (4.4), but Xamarin Forms 4.6 have been recently released. With that version can work i guess.

**Comment by felipechavez** [comment]
I'll close this, because is off topic. Thanks!!
