### ISSUE TITLE
Avalonia version cannot run on Linux

### ISSUE THREAD

**Issue by jinyuttt** [Mapsui/Mapsui#904]
Avalonia version cannot run on Linux.
![image](https://user-images.githubusercontent.com/13539621/80916902-1d059900-8d8e-11ea-99e7-4a011c7ab011.png)

**Comment by charlenni** [comment]
I seems, that this is not a Mapsui problem, but a SkiaSharp or Avalonia problem.

**Comment by ahopper** [comment]
This appears to be a SkiaSharp version issue. If you copy SkiaSharp.dll from another Avalonia app to the output it then works.
This is good motivation to do some more work on this.
The nightly builds of Avalonia have just moved to skia 1.68.3, is this on the Mapsui roadmap.

**Comment by charlenni** [comment]
There isn't a 1.68.3 for Skia. Perhaps in the nightly build. Mapsui 2.0.0, which was published this morning, comes with SkiaSharp 1.68.2.1.

**Comment by ahopper** [comment]
@charlenni sorry you are right, my memory failed me there. I'll have a play with merging in the latest and see what happens.

**Comment by charlenni** [comment]
That's good, because there were problems with one of the last SkiaSharp versions some weeks ago.

**Comment by ahopper** [comment]
https://github.com/ahopper/Mapsui/tree/initial-avalonia-port now uses latest Mapsui and Avalonia and appears happy on windows and linux.

**Comment by charlenni** [comment]
Nice to hear, that now all work.

Could you please close this issue?

**Comment by pauldendulk** [comment]
@jinyuttt So, does this solve your issue?

**Comment by jinyuttt** [comment]
Unfortunately, the new version has not been compiled and has not run successfully

**Comment by ahopper** [comment]
@jinyuttt It is probably a good idea to close this issue here and open one on my branch.  It worked for me on linux, how did it fail for you?

**Comment by jinyuttt** [comment]
@ahopper I'm preparing a development project and testing it.

**Comment by jinyuttt** [comment]
OK

**Comment by jinyuttt** [comment]
OK

**Comment by jinyuttt** [comment]
@ahopper Avalonia canceled support?

**Comment by ahopper** [comment]
@jinyuttt sorry I don't understand. My branch currently works with the Avalonia nightly builds and I've tested on windows and linux.

**Comment by jinyuttt** [comment]
@ahopper I've opened a problem in your branch. We have jet lag or bad network. We always delay to see the latest things

**Comment by jinyuttt** [comment]
@ahopper  Can you send me a complete example of Linux running?
