### ISSUE TITLE
a project with an output type of class library cannot be started directly 

### ISSUE THREAD

**Issue by Kayumiy** [Mapsui/Mapsui#910]
![image](https://user-images.githubusercontent.com/22438366/81374196-a7a51a00-9139-11ea-9871-0337120d17c3.png)

I cannot run this project.
Can anybody explain how to solve it?

**Comment by charlenni** [comment]
As the error message says: you try to start a library. 

You should not download a part of Mapsui. If you want to try a sample, than download the whole project and select a sample project for a platform (like the Mapsui.Samples.Droid for Android or Mapsui.Samples.UWP for UWP) as startup project.

**Comment by Kayumiy** [comment]
![image](https://user-images.githubusercontent.com/22438366/81380871-957da880-9146-11ea-98ff-b51c39e5529f.png)


Even though, I opened  whole project and selected a sample project, same error message has been shown.

Any solution?

**Comment by charlenni** [comment]
Now you have selected Mapsui as startup project. Mapsui itself is a library, which couldn't started. 

So select the Mapsui.Samples.Uwp project, press the right mouse button and choose "Set as Startup project". Than start again.

**Comment by Kayumiy** [comment]
![image](https://user-images.githubusercontent.com/22438366/81384859-3f603380-914d-11ea-810d-3f690386c4ef.png)

Same error has not been solved yet.

**Comment by charlenni** [comment]
You didn't do, what I said. Now you try again to start the library Mapsui.Samples.Common.Desktop. That wouldn't work. You should select "Mapsui.Samples.Uwp" as startup project.

**Comment by Kayumiy** [comment]
![image](https://user-images.githubusercontent.com/22438366/81388994-14c5a900-9154-11ea-807b-5d54770aeb1d.png)

When I select "Mapsui.Samples.Uwp" as startup project, it suddenly shows a lof of errors.

**Comment by charlenni** [comment]
Go on the right side to "Solution", press right mouse button and select "Clean Solution". Than press right mouse button again and select "Restore NuGet Packages". Try again.

Btw. do you create a C# project before?

**Comment by Kayumiy** [comment]
I am Unity Developer so I have lack knowledge of the IDE.
I am sorry for simple questions.
Thank You a lot.

**Comment by Kayumiy** [comment]
I did "**Clean Solution**" and "**Restore NuGet Packages**". However, nothing has been changed.

**Comment by Kayumiy** [comment]
![image](https://user-images.githubusercontent.com/22438366/81520530-8fbed780-937f-11ea-8cd9-02cb8d02dec2.png)

I am going to run   ShapefileSample.cs script. When I Debug Ctrl+F5, it does not show any result.



![image](https://user-images.githubusercontent.com/22438366/81520543-98afa900-937f-11ea-82fa-5697f6afbe41.png)

**Comment by charlenni** [comment]
If this issue is solved, could you please close it?

**Comment by pauldendulk** [comment]
> If this issue is solved, could you please close it?

Yeah, @Kayumiy, be a good citizen and close the issue, you can do it!

@charlenni I added a few notes of how users can help in the readme: https://github.com/mapsui/mapsui#how-can-i-help-as-a-user
