### ISSUE TITLE
Mapsui.Forms: Manipulating toolbar?

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#912]
When using Mapsui.Forms is it possible to manipulate the toolbar? For example change location (default upperright) and remove/adding buttons?

**Comment by charlenni** [comment]
You could move the toolbar by the following code

    var toolbar = (StackLayout)((AbsoluteLayout)mapView.Content).Children[1];
    AbsoluteLayout.SetLayoutBounds(toolbar, new Rectangle(0.05, 0.03, 40, 176));

By this way (use of `toolbar.Children`), it should be possible, to add more buttons. 

To remove the existing buttons, you could use the following properties:

    IsZoomButtonVisible
    IsMyLocationButtonVisible
    IsNorthingButtonVisible

Would it be helpful to have the toolbar as property or is this enough?

**Comment by bertt** [comment]
Ok thanks, for the moment I've removed it completely to get my original design, using

```
((AbsoluteLayout)mapControl.Content).Children.RemoveAt(1);
```

**Comment by charlenni** [comment]
Ok. That would also possible with setting all 3 flags to false.

Do you think it should be more possible? Expose buttons, so that images could be changed?

**Comment by charmosz** [comment]
The solution is not working anymore. Do you have a new one ? I have difficulties to understand how to modify widgets position.

**Comment by pauldendulk** [comment]
Which solution to what problem?

If you are trying to disable the buttons you could use:

```csharp
 IsNorthingButtonVisible="false"
 IsZoomButtonVisible="false"
 IsMyLocationButtonVisible="false"
```

**Comment by charmosz** [comment]
I am trying to manipulate the toolbar. But the following advice is not working anymore since 3.0.0-rc.3
`var toolbar = (StackLayout)((AbsoluteLayout)mapView.Content).Children[1];
AbsoluteLayout.SetLayoutBounds(toolbar, new Rectangle(0.05, 0.03, 40, 176));`

Must have something to do with widgets so I looked around methods like `CreateButtons` and `UpdateButtonPositions`. But I'm a bit lost. Any advice is welcome.

**Comment by charlenni** [comment]
@charmosz The buttons are now implemented as `ButtonWidget`s. You couldn't change the position, as you could see in [UpdateButtonPositions](https://github.com/Mapsui/Mapsui/blob/6fa0bad4df4bfc31f8c46a52f10cde7204cfb2b1/Mapsui.UI.Forms/MapView.cs#L767). It is always placed in the right upper corner. You could change spacing between the buttons and Margin around the buttons (mostly to the border). If you want to use your own buttons, you could remove the standard buttons, as @pauldendulk described. MapView for Forms is a convenience object around MapControl. So there is only one position for the buttons.

**Comment by charlenni** [comment]
Perhaps it is enough to set x/y for the top left corner?

**Comment by janusw** [comment]
> Perhaps it is enough to set x/y for the top left corner?

Well, that's not really user-friendly, I guess ;)
The user might need to fiddle quite a bit to get the magic numbers for a proper placement (and it might depend on the number of buttons shown etc).

@bertt, @charmosz Could you maybe comment on this from your point of view?

I could offer to implement proper alignment options if it helps anyone.

In general I think our default top-right placement of the buttons is not optimal for mobile devices (in particular for one-hand usage). Apps like OSMAND have the buttons at bottom-right by default. Also in this context I think that an button-alignment option would make sense (I might even use it myself at some point).

**Comment by charmosz** [comment]
Totally agree with that. I think it is a good solution to add 2 properties `ButtonHorizontalAlignment` and `ButtonVerticalAlignment`.

**Comment by pauldendulk** [comment]
These buttons are ButtonWidgets with their own aligment properties like: HorizontalAlignment, VerticalAlignment, MarginX and Margin. Is it not better to expose those widgets on the mapview so that these properties can be set. Now a new layer of properties is created to set the underlying properties. And you have to do that for all widgets.

**Comment by pauldendulk** [comment]
You could also go further and treat these buttons more as regular Widgets that happen to be added by default. In that case they can not be fields but could be added to a 'Widgets' dictionary. Users could clean the dictionary to start from scratch. Not sure what the impact of this change would be. Properties like IsNorthingButtonVisible, IsMyLocationButtonVisible, IsZoomButtonVisible would have to go. An alternative for 'IsNorthingButtonVisible = false' would be: 

```csharp
Mapview.Widgets["northing-button"].Enabled = false;
```

And regular alignment can be set with: 

```csharp
Mapview.Widgets["northing-button"].HorizontalAligment  = HorizontalAlignment.Right
```

@charlenni Created this class, I would like to hear what he thinks.

**Comment by janusw** [comment]
Huh, but it doesn't really make sense to specify the alignments for the zoom-in and zoom-out buttons separately.
Maybe one should use a ('compound') `NavigationButtonsWidget` that (potentially) contains all four buttons (with the possibility to hide some of them). Then one could simply use this widget's alignment properties.

I do like the idea of having such a widget as a 'regular' widget in a widget dictionary :)

**Comment by pauldendulk** [comment]
Good point. Did not think about the zoom-in zoom-out pair. And it does make sense to add compound widget, but that will be a much bigger change. Nevermind, just a suggestion, do not want to meddle with this.

**Comment by charlenni** [comment]
I would say, that exposing the widgets would be enough, because, each type of alignment would find someone not good enough. If you could set the widgets by your own pixel alight, then it is the best. 

But I could also live with the alignment solution. If I remember it correct, then it works this way at scalebar too.

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
