### ISSUE TITLE
Get _dropPoint coordinates after Drop from other controls

### ISSUE THREAD

**Issue by ghost** [Mapsui/Mapsui#918]
Hi everyone

I'm using mapsui 2.0.0 and i'm trying to drop something from a WPF control inside the map.

```
MapControl.AllowDrop = true;
MapControl.DragOver += MapControl_DragOver;
MapControl.Drop += MapControl_Drop;
```
Inside MapControl_Drop i have no problems getting my dragged object from the event arguments, but i can't get the coordinates of the point where i dropped it.
The coordinates are actually there in the non public _dropPoint variable, but of course i can't get them.
I tried storing the screen position using e.GetPosition in the MapControl_MouseMove callback, but the callback isn't actually called when dragging over the map, so the coordinates aren't updated.

Any help would be appreciated.

Thanks

**Comment by charlenni** [comment]
You should get screen coordinates for your drop point. Is this correct? If yes, than you could translate this screen coordinates to control coordinates and then translate this with `ScreenToWorld()` to map coordinates.
