### ISSUE TITLE
Replace Navigator with AnimatedNavigator

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#919]
@radderz Do you think, that we need new functions for this? Wouldn't it be not enough, if we set in all function the duration value to zero? As you can see, AnimatedNavigator checks always for `duration == 0` and if true, it does the same as the old Navigator. So where is the advantage to have new functions?

**Comment by pauldendulk** [comment]
> @radderz Do you think, that we need new functions for this? Wouldn't it be not enough, if we set in all function the duration value to zero? As you can see, AnimatedNavigator checks always for `duration == 0` and if true, it does the same as the old Navigator. So where is the advantage to have new functions?

That's what I was about to say.

**Comment by pauldendulk** [comment]
Related. The mouse wheel animation in WPF should also be replaced with the animation of the AnimatedNavigator. A problem I have encountered in the past and recently in the latest version of OpenLayers is that various separate animation loops conflict with each other. There should be one central point for the state of the animation. Let this be the _animation field in the AnimatedNavigator.

**Comment by charlenni** [comment]
@pauldendulk Our problem is [line 289](https://github.com/Mapsui/Mapsui/blob/9aef3bbeb41adb9581a44dbf026c3429805fa2f7/Mapsui.UI.Shared/MapControl.cs#L289) from shared MapControl. There it replaces the Navigator with a new Navigator each time, you assign a Map to a MapControl. 

For me the Navigator belongs to the MapControl or, perhaps this is logical better, to the Viewport, because you control the part, which you see from the map, with the Viewport and any changes to this Viewport are changed with the Navigator. But for historic reasons I wouldn't do this.

I made a first PR (#920) for this. With this, you don't need any changes in the API. And you need no new functions.

**Comment by charlenni** [comment]
Regarding the mouse wheel: the mouse wheel uses the `ZoomTo(double resolution, Point centerOfZoom)` function. This moves the center to the position under the mouse cursor, then changes the resolution and changes the center back. This would be a special case of the normal animation. Have to look into this, if this is possible.

**Comment by charlenni** [comment]
I added this too.

Now we have the same API as before. The only difference is, that MapControl.Navigator is an AnimatedNavigator instead of a Navigator. If you want to use the new animated naviagtion functions, all you have to do is to insert the following line

    ((AnimatedNavigator)mapControl.Navigator).AnimationTime = 300;

With this, you set the default animation time to 300 ms instead of 0 ms. Than all navigation functions will use this duration. You have nothing to change in the rest of your code. But you can also use the new navigation functions with your own duration. So you could use a default time for all navigations (AnimatationTime = 300) and for e.g. a zoom in a speciall time of 1000 ms with `ZoomIn(1000)`.

Any comments?

**Comment by pauldendulk** [comment]
What about removing the Navigator and renaming the AnimatedNavigator to Navigator? 

I like the idea of using the same methode (or overload) for animated and non-animated. I would hope the user does not have to use the AnimationTime field too much, but I understand you would like to have some sensible default which could change.

What about all methods having an *optional* delay in milliseconds as second parameter, and the default for that parameter is the AnimationTime?

Since you can not set the default to a variable you may want to do it like this:

```csharp
public void ZoomTo(double resolution, int animationTime = int.MaxValue)
{
    if (animationTime == int.MaxValue)
        animationTime = AnimationTime; // The default could be changed.

    //.... implemenation

}
```

**Comment by charlenni** [comment]
We have this all allready. There is a `ZoomTo(resolution)`, which uses the AnimationTime, which is by default zero. If you set it once, then this new animation time value is used everywhere. And if you want to have a speciall value for a single time, you can use `ZoomTo(resolution, duration)`.

**Comment by pauldendulk** [comment]
Okay thanks, I have to step through the code and that will not be today or tomorrow. Should have more time next week.

**Comment by charlenni** [comment]
Regarding removing the Navigator and replacing it with AnimatedNavigator: could be done, but, because MapControl.Navigator is defined as INavigator, you have to always make a cast to the correct type.

**Comment by pauldendulk** [comment]
The INavigator will have to be extended with the features currently in the AnimatedNavigator..... and perhaps we should not use a interface at all in this case.

**Comment by charlenni** [comment]
I'm not sure, that this is a must have. You need the cast only once and than could use the normal INavigator functions. And with the interface, it is possible to create your own navigator. The only problem for this was the replacement of the navigator if you set the Map of the MapControl.

**Comment by radderz** [comment]
The reason I was thinking of separate methods is to be explicit, but yea it could default to duration = 0, I was also thinking it would be good to offer the ability for the user to specify the easing style for certain animation types (but not sure if this is really necessary if we pick a natural one). I don't particularly like linear for change from one point to another for instance, as it's too rigid. I like the sin in, followed by a sin out for the second half to give it a accelerating/decelerating like motion.

I was intending to extend INavigator, others could still implement this interface to do their own thing and just ignore the animation side of things if they don't want it animated. It's a pain casting things all the time as I don't want to hold an instance of the navigator outside of the map.

**Comment by radderz** [comment]
Will do a pull request now for my changes and we can discuss

**Comment by charlenni** [comment]
Perfect. Thank you. Didn‘t thought about the animation easing.

**Comment by radderz** [comment]
@charlenni check out the pull request

**Comment by radderz** [comment]
it's not fully tested as I had to join a meeting but will do testing later today and work on the feel by doing some different conbinations of easings.

**Comment by charlenni** [comment]
I thought about it. Perhaps @pauldendulk suggestion is the best: use -1 for the default in the functions. If this is the case, then replace the duration with a `long DefaultDuration = 0` as default. With this, you could use it in the light version by setting a DefaultDuration at the beginning and never again use a duration. Or you could use different durations for every call. Or you could mix both.

For changes see the [PR](https://github.com/radderz/Mapsui/pull/2) to your repository.

**Comment by charlenni** [comment]
Regarding the not so good animation: I think, the animation jumps at the end. It seems, that it is to slow, so that at the end is a gap and it jumps direct to the final. Could that be? Is this what you see?

**Comment by pauldendulk** [comment]
In the case of the Navigator I think the default should be what we think is the best solution. So, probably with animation and easing. Many users don't get around to trying alternative implementations, they use the defaults and think that is all there is.

**Comment by charlenni** [comment]
But setting a default value other then zero while bring problems, because existing apps would work any longer as expected.

**Comment by pauldendulk** [comment]
> But setting a default value other then zero while bring problems, because existing apps would work any longer as expected.

In v3 we can introduce breaking changes. Actually I was thinking about all these Navigator changes going into the v3 branch but perhaps it is possible to add some of them to a 2.1.

**Comment by pauldendulk** [comment]
> Regarding the not so good animation: I think, the animation jumps at the end. It seems, that it is to slow, so that at the end is a gap and it jumps direct to the final. Could that be? Is this what you see?

What should I do to see the 'not so good' animations?

**Comment by charlenni** [comment]
> What should I do to see the 'not so good' animations?

Try to use longer durations. At the end of the animation you will see a „jump“.

**Comment by charlenni** [comment]
> > But setting a default value other then zero while bring problems, because existing apps would work any longer as expected.
> In v3 we can introduce breaking changes. Actually I was thinking about all these Navigator changes going into the v3 branch but perhaps it is possible to add some of them to a 2.1.

It is clear a 2.1. With the changes, there is no difference to the behavior of the old Navigator.

**Comment by pauldendulk** [comment]
> It is clear a 2.1.

I had more in mind than this.

**Comment by charlenni** [comment]
More for 2.1 or more for animations?

**Comment by pauldendulk** [comment]
More for animations and some related things, but maybe it is better to first take this step. 

What I had in mind:
- Reduce the Viewport to just public state, no methods. The current methods would be extension methods (I had this in mind also for other reasons).
- Animations become transitions of one Viewport state to another Viewport state. So there is no list of animation, but just one Viewport.
- Default to what we think are the best options.
- Fully replace mousewheel animation with navigator animation.
- Do not start and stop animations but just set a new target. Also work from the current state, the starting point is not relevant anymore. This way I hope to get smoother animations when the animation changes in between. The mousewheel animation works like this. 

It is hard to explain this in a few sentences and I don't have the full picture in mind yet, but hopefully you have a rough idea what I mean.

**Comment by charlenni** [comment]
> Reduce the Viewport to just public state, no methods. The current methods would be extension methods (I had this in mind also for other reasons).

There are only a few functions in Viewport:
- Transform(): Is used to move the center of the Viewport in touch events. Should be moved to Navigator.
- All conversions between screen coordinates and world coordinates. I assume, that you want to do this by extensions.
- Anything else is state related. The Set... functions could be replaced by access of the properties.

> Animations become transitions of one Viewport state to another Viewport state. So there is no list of animation, but just one Viewport.

This is the way it works already, or not? Each animation step set the new state of the Viewport. Or would you say, that the animations should go into the Viewport? But then it isn't only a state.

Animations could be combined. You could make an animation for resolution and one for center. Then both will change together, but you have distinct functions for both. So you mustn't create new animations if you want create new combinations. I would say, that this is very flexible.

> Default to what we think are the best options.

Best option is zero for duration. It is, what users expect the most time. Animated transitions are the extra case.

> Fully replace mousewheel animation with navigator animation.

If I'm right, than you only have to change line 234 of Mapsui.UI.Wpf/MapControl.cs by changing it to

    Navigator.ZoomTo(_toResolution, _currentMousePosition, 1000);

With this, you zoom to the position of the mouse.

> Do not start and stop animations but just set a new target. Also work from the current state, the starting point is not relevant anymore. This way I hope to get smoother animations when the animation changes in between. The mousewheel animation works like this.

The new animations do this too. The animation changes each time the state of the Viewport. If you abort it and start a new one, then this starts from the current Viewport to the new values.

**Comment by charlenni** [comment]
Perhaps it would be good to have a setting function in Viewport to set more then one value at a time. If you zoom on a given point, we set the center, change the resolution and reset the center. Between we call each time a OnViewportChanged(). This shouldn't happen. It should called only once at the end when all values are set to their new once.

**Comment by pauldendulk** [comment]
@charlenni @radderz What I was thinking of is to work from @radderz PR and use that in a 2.1.0 release. Perhaps with the only 2.1 feature, so it can be released soon. Choices we make:
- The main Navigator will have all of the current animation (and some more), so users do not have to switch back to the AnimatedNavigator.
- We still have an interface which includes the animation logic. It it is overriden animation logic can be ignore. I don't see an actual use case for this but perhaps someone has already overriden it.
- The AnimatedNavigator can be deprecated. 

What more changes should go into that MR? What should further be tested?

**Comment by charlenni** [comment]
> The main Navigator will have all of the current animation (and some more), so users do not have to switch back to the AnimatedNavigator.

AnimatedNavigator was made to replace the existing Navigator. It has the same functions plus a FlyTo function. @radderz added a FlingTo for the fling function. All other functions are only usefull, if Viewport gets more properties, which could be manipulated by the Navigator.

The only thing I could imagine is to add arguments for the easing function of an animation.

> We still have an interface which includes the animation logic. It it is overriden animation logic can be ignore. I don't see an actual use case for this but perhaps someone has already overriden it.

Radderz changes to INavigator made it ready for animations.

> The AnimatedNavigator can be deprecated.

Yes

> What more changes should go into that MR? What should further be tested?

* We should update the MapControls for this behavior. 
* We should use the fling for all MapControls and check the zoom functions, if there are any (e.g. the mouse wheel zoom in Wpf).
* We should check, if System.Timer is the correct timer for this work or if we should replace it by a special timer for this work.
* We should think about the time steps of the timer. Perhaps 16 ms is to long.

**Comment by radderz** [comment]
I think the Xamarin approach to their timer is a good starting point as you can get a more accurate timer in some platforms specifically for animating.

Would you be ok with me leaving the animated navigator deleted since it's merged in? Given it would just mean people no longer need to add the animated navigator they can just remote their line of code. I could also just add an AnimatedNavigator as a subclass of Navigator and mark as obsolete.

**Comment by charlenni** [comment]
I would say, it is ok to remove the AnimatedNavigator. It wasn‘t official at any time since I introduced it.

@radderz For me it is ok to use the Xamarin timer approach, but how to implement this in Mapsui, which is a .Net Standard library? With this in mind, Navigator has to move to the platform dependent part.

Do you think it would be helpful, if the animation runs in an own thread?

**Comment by radderz** [comment]
@charlenni I didn't mean to use Xamarin's animation timer, but more just the way they actually do it (in their source code). The idea is you can set the timer system, else it'll revert back to a basic timer. So I guess the idea would be to make it overridable somehow so the tick's can either be through a C# standard timer or some platform specific thing to enable better animations if needed. i.e. on WPF I doubt the override for the platform specific side of things would be needed as the cpu's are more powerful.

Navigator would stay platform independent, just the animation class might have a static variable that allows an external platform specific instance of a timer. I guess we'd do this through an interface, and the default implementation of that interface is just using a timer under the hood. Then when the platform is android, we override that with an android specific one like xamarin do.

**Comment by charlenni** [comment]
Ok, that could work. But Xamarin does a little bit more than only call a platfom specific timer. At leaste on iOS.

**Comment by pauldendulk** [comment]
> Would you be ok with me leaving the animated navigator deleted since it's merged in? Given it would just mean people no longer need to add the animated navigator they can just remote their line of code. I could also just add an AnimatedNavigator as a subclass of Navigator and mark as obsolete.

I prefer to mark it as obsolete because it is a direct way to inform the users. With the obsolete message you can use the compiler to inform the user. In the message you can also tell them what is the alternative to what they use now. In a later release I then remove the obsoleted class. 

There are two ways to make a class obsolete. I With or without the error boolean. If set to true it is impossible to use it so you could remove the implementation. I choose one or the other depending on the situation. If I expect quite some users make quite some use of something and it does still function properly I use error = false. In this case perhaps we can set error = true and remove the implementation code of the AnimatedNavigator.

**Comment by pauldendulk** [comment]
@radderz @charlenni Could you point me to the Xamarin animation code?

**Comment by pauldendulk** [comment]
> > Reduce the Viewport to just public state, no methods. The current methods would be extension methods (I had this in mind also for other reasons).
> 
> There are only a few functions in Viewport:
> 
> * Transform(): Is used to move the center of the Viewport in touch events. Should be moved to Navigator.
> * All conversions between screen coordinates and world coordinates. I assume, that you want to do this by extensions.
> * Anything else is state related. The Set... functions could be replaced by access of the properties.

Yes, that is what I had in mind. With the WindowExtent still a readonly property.
