### ISSUE TITLE
Navigating to bounding box in Map.Home()

### ISSUE THREAD

**Issue by hajmajeboss** [Mapsui/Mapsui#922]
Hello,

I encountered a problem when navigating to bounding box in Map.Home() method / and the very same problem in OnResume() method. 

We have our MapControl in MvxFragment (MVVMCross library) and have geometries as parameter when navigating to the map fragment - we expect our fragment to "select" those geometries and show detailed info about them. I tried calling the navigation method in OnResume, but it didn't work as I would except, so I decided to try the navigation in Map.Home() method.

However, what happens is, that geometries get selected, infobox gets shown, but map doesn't navigate to the desired bounding box, but to its full envelope. If I set timeout around 500ms, then it gets navigated, but not to the exact bounding box. If I set 2000ms timeout, it gets navigated correctly.

I don't want to go with timeout, so I'm posting this issue.

**Comment by charlenni** [comment]
You are talking about a timeout. Which value do you mean? 

Then, you use Map.Home(). This navigates to the full envelop of the map. Do you expect something else?

**Comment by hajmajeboss** [comment]
Map.Home could be set to navigate to any point I want - right now, I navigate to the last position saved in OnPause() method on Android.

By timeout, I mean Thread.Sleep(500).

**Comment by charlenni** [comment]
Map.Home could be set, that is correct. But would it be possible to see, what you set for Home?

**Comment by charlenni** [comment]
If I'm correct, than you call MapControl.Navigator.NavigateTo() and don't get the desired result. Is this correct?

**Comment by hajmajeboss** [comment]
I just deleted the code :-D

It was something like this

`Map.Home = n => 
{
 if (SelectedGeometries != null && SelectedGeometries.Count > 0) 
 { 
  var bbs = SelectedGeometries.Select(x => x.BoundingBox).ToArray(); 
  var bb = BoundingBox.Join(bbs);
  n.NavigateTo(bb, ScaleMethod.Fit); 
 }
}`

**Comment by hajmajeboss** [comment]
![image](https://user-images.githubusercontent.com/29458619/82033722-6ebaf700-969d-11ea-9b88-7815c6538995.png)
![image](https://user-images.githubusercontent.com/29458619/82033882-ac1f8480-969d-11ea-8a46-ceaaa98632ae.png)


Expectation vs Reality

**Comment by charlenni** [comment]
For me it seams, that you haven't a tile ready loaded. But why aren't the features visible? Are you at the correct bounding box?

I checked here the normal NavigateTo function and it work correct. So it could only be a problem with the OnResume.

**Comment by hajmajeboss** [comment]
I'm, it works just well when I return from another activity, but doesn't work when the activity is created before OnResume() is called.

**Comment by hajmajeboss** [comment]
Tiles are loaded, you can see the ČUZK text under GPS indicator. This provider only provides data for the Czech Republic.

**Comment by charlenni** [comment]
The bounding box is calculated correct?

**Comment by charlenni** [comment]
If I look into code, I would say, that the Width and Height of the Viewport aren't set correct in this moment. You could check MapControl.Viewport.HasSize. 

I saw this before, because SkiaSharp is undefined in this moment. Perhaps it is possible to add an event handler to OnViewportChanged, which checks, if the viewport has a valid size and then navigates to the correct bounding box and removes itself (the handler) at the end.

**Comment by pauldendulk** [comment]
The idea is that you set the Home method just once and you use it to go back to your full extent. When you want to zoom into some feature use the MapView.Navigator methods.

**Comment by hajmajeboss** [comment]
I pretty much use it to navigate to last position before pausing/closing the application. I would try the OnViewportChanged event, but I believe it didn't work and we had to make workaround with OnPropertyChanged or something like that.

**Comment by charlenni** [comment]
Try to use the other NavigateTo function with center and resolution. Both could be saved before pausing/closing, but doesn't use a recalculation of the resolution by viewport dimensions. This would be much easier.

**Comment by hajmajeboss** [comment]
Yes, this one works. But I talk about zooming to feature which I select in feature list in different fragment.

I choose a feature in the list, click navigate, switch to MapFragment and navigate to its bounding box. This works as long as I set timeout (Thread.Sleep()) of at least 100ms.

**Comment by charlenni** [comment]
You use the following function to navigate:

    /// <summary>
    /// Navigate center of viewport to center of extent and change resolution
    /// </summary>
    /// <param name="extent">New extent for viewport to show</param>
    /// <param name="scaleMethod">Scale method to use to determine resolution</param>
    public void NavigateTo(BoundingBox extent, ScaleMethod scaleMethod = ScaleMethod.Fit)
    {
        if (extent == null) return;

        var resolution = ZoomHelper.DetermineResolution(
            extent.Width, extent.Height, _viewport.Width, _viewport.Height, scaleMethod);
        _viewport.SetResolution(resolution);

        _viewport.SetCenter(extent.Centroid);

        Navigated?.Invoke(this, EventArgs.Empty);
    }

As you can see, the viewport dimensions are essential for the calculation. So why not save this by your own and calculate the new resolution by yourself.

    var resolution = ZoomHelper.DetermineResolution(
                extent.Width, extent.Height, savedViewportWidth, savedViewportHeight, scaleMethod);

and than call

    NavigateTo(bbs.Centroid, resolution);

**Comment by charlenni** [comment]
Or you could check the size of the MapControl and use this for width and height, if it is ok.

**Comment by hajmajeboss** [comment]
Same story - works with timeout, doesn't work without timeout.

**Comment by charlenni** [comment]
So you say, that even if you use precalculated resolutions, NavigateTo doesn‘t work, correct?

**Comment by hajmajeboss** [comment]
Yes.

**Comment by charlenni** [comment]
Ok. Then it is a problem in navigation and not in calculation.

**Comment by charlenni** [comment]
I now used the Mapsui.Samples.Android sample and added the following function to it

        protected override void OnResume()
        {
            base.OnResume();

            _mapControl.Navigator.NavigateTo(new Mapsui.Geometries.BoundingBox(-1000000, -1000000, 1000000, 1000000));
        }

Then I started it with the emulator (Android 9.0), turned it of and on again. The bounding box is shown correct. Then I started it with a real device (Android 8.0), turned power off and on again. Same result, bounding box is shown correct.

**Comment by hajmajeboss** [comment]
Try, if it works with animated navigator please.

**Comment by charlenni** [comment]
Same behavior.

**Comment by hajmajeboss** [comment]
I started to suspect it has to do something with Mvvmcross inflating fragments.

**Comment by hajmajeboss** [comment]
No. 

If I select 4 features, it needs longer timeout than if I select 1 feature - maybe it waits until those features are drawn?

**Comment by charlenni** [comment]
For this I should have a valid sample to test.

I see, that you get the tiles of your provider, which are normally send, when the zoom level isn't available. I had this while testing too. Could you check you resolution in the moment of calling NavigateTo()?

**Comment by charlenni** [comment]
You call the Sleep() before or after the NavigateTo()?

**Comment by hajmajeboss** [comment]
Before.

**Comment by hajmajeboss** [comment]
Anyway, tried not selecting the features and still didn't work.

**Comment by charlenni** [comment]
Could you add the following line in your OnResume() function

    ((AnimatedNavigator)_mapControl.Navigator).NavigateTo(new Mapsui.Geometries.BoundingBox(-1000000, -1000000, 1000000, 1000000), Utilities.ScaleMethod.Fit, 5000);

and try it again? It should zoom to the west coast of Africa.

**Comment by hajmajeboss** [comment]
I have no map outside of Czechia.

**Comment by hajmajeboss** [comment]
But no, it didn't work, I'm still zoomed out to full extent.

**Comment by hajmajeboss** [comment]
Also, we use Krovak projection (EPSG:5514), not WGS84 or Mercator/Web mercator. Could this possibly cause something?

**Comment by charlenni** [comment]
You could use

    ((AnimatedNavigator)_mapControl.Navigator).NavigateTo(new Geometries.Point(1607208.5, 6459368), 10, 2000);

This should zoom to Prag. And it is in native Mapsui coordinates. And nothing is calculated. Only values are set.

But never mind what you use, there should something else than the full extent of the map. This said, something must prevent NavigateTo() to set the correct values.

Do you use the animated version of NavigateTo() (do you use a duration not equal to zero)?

**Comment by hajmajeboss** [comment]
I tried both with same result. 

I think this won't zoom to Prague in Krovak coords, because they are negative for whole extent of Czechia.

**Comment by charlenni** [comment]
Mapsui doesn't know anything about Krovak coordinates. It has its own coordinate system, which is 1 m in both direction at 0/0. So the coordinates are 16 million meters to the east and 6,5 million kilometers to the north. Not complete correct, but approximatly.

I don't assume, that it is the NavigateTo() function. I assume, that you (or better MvvmCross) calls another function at the end of initialisation, because how should values of Mapsui change? Perhaps a recreation of the object? And if the object is recreated, then you could navigate to another point. The time you wait is for the end of this.

What happens, if you don't call NavigateTo() in OnResume()? I will bet, that you get the same result.

**Comment by hajmajeboss** [comment]
If I don't call it, it ends up at the last position (probably calling Home, but I'm not calling it anymwhere I think).

**Comment by charlenni** [comment]
So it is the same before and after powering off the device?

**Comment by hajmajeboss** [comment]
It ends up on correct location after powering off and on (meaning turning display off/on) or moving to another activity. Only the first OnResume call is causing the problem.

**Comment by charlenni** [comment]
Now I see what you mean. OnResume is called also when you start the app the first time. And only this time it doesn't work. So you want to call NavigateTo() with a saved state the next time the app starts. Correct?

**Comment by hajmajeboss** [comment]
No, that works. 

I want to call NavigateTo when I go from one fragment of my app back to map fragment of my app, whenever I pass geometry or geometries as parameter.

It goes like this

`NavigationService.Navigate<MapViewModel, IEnumerable<IGeometry>(SelectedGeometries);`

and then it navigates to MapFragment, constructs it calling OnCreate, OnCreateView etc. and also OnResume. It doesn't work in OnCreate or OnCreateView either.

When I open the app, there is no parameter being passed, so it just navigates to Home, which is last position and this works well.

**Comment by charlenni** [comment]
While debuging, you see, that after OnResume is called, another event is fired. It is the OnSizeChanged. And this OnSizeChanged calls CallHomeIfNeeded, which calls Map.Home. This later call overwrites your NavigateTo from OnResume, because it is called later.

So try to set your Map.Home in your OnResume. This should work for the first time.

**Comment by hajmajeboss** [comment]
Ok, will try. Thank you.

**Comment by charlenni** [comment]
Try to check, if OnSizeChanged is called in your workflow and if yes, if it is called before or after OnResume. And check, if Map.Initialized is false in this moment.

I assume, that MvvmCross disposes the MapControl and recreates the object new, when it needs it.

**Comment by pauldendulk** [comment]
The Navigator code was rewritten. I assume this is not relevant anymore.
