### ISSUE TITLE
Render map on Tizen (watch)

### ISSUE THREAD

**Issue by keks-24** [Mapsui/Mapsui#926]
We try render .mbtiles offline map on TizenXaml Application.
We use Xamarin.Forms for front page. Like in this link (https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/Mapsui.Forms.md) , we try use Mapsui.UI.Forms, and get from there MapControl. From back we set NameMapControl.Map.Layers.Add(OurTileLayer).
In debug we shure that it creates, but on front page dont render MapControl. 
So how can we render this control? Any solutions or advise for it?

**Comment by pauldendulk** [comment]
I am not aware of any user on Tizen. Perhaps the best first step would be to use the OpenStreetMap layer, like in this sample: 
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/OsmSample.cs
