### ISSUE TITLE
Improvement request for event `Map.Viewport.ViewportChanged`

### ISSUE THREAD

**Issue by lehmannk** [Mapsui/Mapsui#927]
I am having trouble with Map.Viewport.ViewportChanged Upon setting a new viewport with MapControl.Navigator.NavigateTo alone this event gets fired 6 times. When moving the mouse the slightest bit left / right / up / down this event also fires about 6 times. When zooming in and out the event fores about 30 times. This is a problem for me as I have to do some heavy calcs on viewport change. Maybe this is because of the animation effects when panning / zooming. 

Is it possible to maybe, as @charlenni suggests, add a flag such as `Animation=true` to `PropertyChangedEventArgs`?

**Comment by pauldendulk** [comment]
We use some similar for Map.RefreshData where there is a majorChange boolean. This boolean is false while panning the map. This can be useful when calling a WMS, you do not want to fetch a new WMS image on every minor change. 

I proposed earlier to replace this with a ChangeType enum with members Continuous and Discrete. If we use something like that all Animation should end with a Discrete event.

**Comment by charlenni** [comment]
Perhaps this isn‘t enough. Perhaps we should add some internal functions to set two or more values of the viewport at a time. Normally a NavigateTo() command will change the center in x-direction, the center in y-direction and the resolution. Each will cause a ViewportChanged event. But how should the viewport know, which is the last setting. 

So I would suggest to add a view internal functions to set center, center and resolution, center and rotation and so on. All have an additionally ChangeType to signal, if they part of an animation or are discrete. This functions are used by the navigator.

**Comment by pauldendulk** [comment]
Good point. Perhaps one setter method with defaults for values that can be ignored.

An alternative is to make use of a struct to represent the whole Viewport state. It can only be set as a whole.

**Comment by pauldendulk** [comment]
In the v4 there is a `Navigator.RefreshDataRequest` event which could be used for this purpose. Also the Viewport is now a records which gets updated as one property, so a change in X, Y and Resolution will still be a single viewport change.
