### ISSUE TITLE
Expose some render quality settings

### ISSUE THREAD

**Issue by joshminor** [Mapsui/Mapsui#931]
I'm working on upgrading from 1.3 to 2.0 and I noticed a steep drop in performance across all the platforms. After digging around in the source code, I've to come to believe that this is related to IsAntialias = true being set for the various renderers. I made a custom renderer to try turning it off and, sure enough, everything ran smoothly again. 
I rather like the internal renderers, and don't want to write my own just to toggle a setting, perhaps there could be a way to change some of the default render settings? I see a couple other settings like Hinting, blend, dithering, and filter quality that might also be nice to be to set.
I'm in the unfortunate position of trying to display 10-20k points at a time (customer requirement), so these little things add up fast. 
Thanks!

**Comment by pauldendulk** [comment]
Thanks, that makes sense, we should look into this. 

Most of the quality improvements came up because the lower quality was noticeable, but this may be important for just some scenarios.

**Comment by tonyfonager** [comment]
@joshminor I kinda have some of the same issues when adding 70k objects to the map, can you maybe elaborate how to worked around and toggled those settings ?

**Comment by joshminor** [comment]
I followed the information here:
https://mapsui.com/documentation/custom-style-renders.html
Making a custom renderer allowed settings to be set on the SKCanvas that could adjust the various quality aspects.
Ultimately I ended up reverting to pre-2.0 mapsui for various reasons, so I haven't looked into it any more.

**Comment by tonyfonager** [comment]
Thanks alot @joshminor 👍

**Comment by joshminor** [comment]
Yeah SKPaint has multiple properties that can be used to affect the quality.
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint?view=skiasharp-1.68.1#properties
IsAntialias had one of the larger impacts.

**Comment by tonyfonager** [comment]
So if I disable it on a custom render, those objects will not use fx Antialias ?

What if I want to disable it everywhere, will I then need to make custom renderers for all my objects, and disable it on each of them ?

I fx. use LineString alot (I am developing a hiking app, with 1200 km routes consisting of 70k points) - so I should make a custom version of that, and disable antialising then ?

**Comment by joshminor** [comment]
If I'm not mistaken you define a renderer for a style, then anything you associate the style to will use the renderer.
I'm not sure you'll gain enough performance to display 70k points even with with antialiasing off. Using a raster layer might be a better alternative. My test project has a map with 100k points and it is pretty laggy when trying to use vector drawing.

**Comment by tonyfonager** [comment]
I am already using the rasterizing layer for my 70k string map, but I still thinks its hanging/slow sometimes ...

**Comment by pauldendulk** [comment]
I created a new issue to discuss how quality instructions should be designed https://github.com/Mapsui/Mapsui/issues/2213
