### ISSUE TITLE
Coordinates grid on Mapsui

### ISSUE THREAD

**Issue by TheProme** [Mapsui/Mapsui#934]
Is it possible to create a coordinates grid on mapsui map? If so how could I achieve this?

**Comment by charlenni** [comment]
I made a short sample. It is a Xamarin.Forms project, but uses only native Mapsui functions.

[GridApp.zip](https://github.com/Mapsui/Mapsui/files/4710884/GridApp.zip)

**Comment by TheProme** [comment]
I'll give it a try. Thanks a lot @charlenni ! :)
