### ISSUE TITLE
Crash when removing map control (UWP - Xamarin Forms)

### ISSUE THREAD

**Issue by joshminor** [Mapsui/Mapsui#935]
I've run into a crash when two or more map controls are displayed. Removing one of the controls will result in a crash with _"Failed to make EGLSurface current"_. I've also seen _"Failed to create EGL surface"_ but was unable to isolate that one in an example.
This seems to be only occurring in UWP, Android and iOS appear unaffected.
This may be a SkiaSharp bug, but I thought I'd raise it here first. Feel free to close/move/mark this if it should be reported to SkiaSharp.

**Platform**
UWP - Xamarin Forms
**Version**
Mapsui 2.0.1, Xamarin Forms 4.6.0.800
**STR**
[MapCrashSample.zip](https://github.com/Mapsui/Mapsui/files/4713877/MapCrashSample.zip)
1. Open sample project.
2. Click "Open Popover" button as many times as you like
3. Close one of the popovers.
4. Observe sadness.
5. If crash doesn't occur right away, attempt to interact with the remaining map and it should crash.

**Comment by pauldendulk** [comment]
Thanks you very much for you complete reproducible sample! I can reproduce it on my machine. There is no stack trace unfortunately.

![image](https://user-images.githubusercontent.com/963462/83487352-2f691480-a4ab-11ea-9bf0-7a4ec7aca63b.png)

I modified the sample to replace the MapControl with the SKGLView. In this way I could not reproduce the crash. The bug could still be in SkiaSharp though, but perhaps it is not, or perhaps it is avoidable. 

[NoCrashWithoutMapsui.zip](https://github.com/Mapsui/Mapsui/files/4715383/NoCrashWithoutMapsui.zip)

The way this could be investigated further:
- Clone this Mapsui source code.
- Add the sample to the Mapsui.sln.
- Figure out by stepping though the code where it crashes.
- Remove as much Mapsui code as possible to still reproduce the crash.
- Hopefully with the simplest possible code it becomes possible to understand where things go wrong.

It will not have time for this the coming week.

**Comment by joshminor** [comment]
Thanks for your response. I tried your modified sample and discovered (by accident, actually) that you can still repro the crash if you open a popover, close it, then resize the window.

I actually got a stack trace from it, 
`System.Exception: Failed to make EGLSurface current
   at SkiaSharp.Views.GlesInterop.GlesContext.MakeCurrent()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.RenderFrame()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.Invalidate()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.OnSizeChanged(Object sender, SizeChangedEventArgs e)`

I should have some time later today to dig into this a bit more.

**Comment by pauldendulk** [comment]
aha, well, then I think this is enough to submit as a bug to [skiasharp](https://github.com/mono/SkiaSharp). Even when it is not a bug it is good to hear their feedback.

**Comment by itoledo** [comment]
been hitting this bug. happens when i navigate from a page that contains a map to another that also contains a map. tried removing the map from the visual tree but it still crashes. however navigating back and forth to the first map view works fine. does anyone know a workaround?

**Comment by pauldendulk** [comment]
@itoledo Thank you very much for the workaround and the sample! There is now a skiasharp bug reported by @joshminor over [here](https://github.com/mono/SkiaSharp/issues/1315). Give it a thumbs up, subscribe and make yourself heard over there.

**Comment by pauldendulk** [comment]
Let me put some emphasis on your workaround:

# There is a Workaround!

Just create an empty page and use it as an "interstitial" page to your second map. Have to wait a few MS between navigations so add a ActivityIndicator or something like that.

**Comment by joshminor** [comment]
Unfortunately this workaround won't work in my particular use case. I'll have to hold off on completing my migration to 2.0 for the time being.

**Comment by pauldendulk** [comment]
This is now outdated. If something like this occurs please create a new bug report.
