### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by VladGluschenko** [Mapsui/Mapsui#936]
I use polygons to draw on the map. 
This is how i set the polygon style:
`this.Styles.Add(new VectorStyle { Line = new Pen(Color.FromArgb(255, 128, 224, 255), polygonThickness){ PenStyle = PenStyle.Solid, PenStrokeCap = PenStrokeCap.Square, StrokeJoin = StrokeJoin.Round } });`
I want to change polygonThickness depending on the current zoom. For example, the smaller the scale, the smaller the line thickness. How can i do this using mapsui?

**Comment by charlenni** [comment]
Attach to the event Viewport.ViewportChanged and recalc there your line thickness regarding Viewport.Resolution (which is the zoom in Mapsui).

**Comment by VladGluschenko** [comment]
Thank you very much. It works
