### ISSUE TITLE
BruTile HttpTileSource works in UWP, but not on iOS

### ISSUE THREAD

**Issue by spaddlewit** [Mapsui/Mapsui#946]
Possibly the first of many tickets I have related to this...

Why does this work in UWP, but not on iOS? Blank map screen, although it will supposedly show my position.

[BruTilePersistentStorageRepro.zip](https://github.com/Mapsui/Mapsui/files/4755723/BruTilePersistentStorageRepro.zip)

**Comment by pauldendulk** [comment]
I am on Windows right now. What is not working on iOS? The HttpTileSource is used in almost every sample, I expect it does work in the regular samples?

In your title you mention 'HttpTileSource 'and in your text you mention 'show my position', this seems unrelated.

**Comment by pauldendulk** [comment]
Okay, just give me 6 ours and my mac will be updated to run the your sample.

**Comment by spaddlewit** [comment]
So sorry that I keep finding all of these weird bugs, @pauldendulk ! Thanks for continuing to help me track these down.

**Comment by pauldendulk** [comment]
I started the sample on ipad but see no map at all and I do see a segfault exception in the error log related to sqlite. Perhaps a problem with versions.

What you are seeing is probably something else. Perhaps the difference between uwp and ios might be in the fact that the one has cache entries where the other has not. Or one has corrupt cache entries. What do you see when you clean the cache?

I also don't get aerial photos because the url is http instead of https.

If you add an Android version which has this problem I'll have another look.

**Comment by spaddlewit** [comment]
Here it is, with the Android project.
Problem is, it works GREAT on Android.. Ughh.. I'm using the same NuGets and everything.

Does appear to be a minor bug, though.. until your finger moves the map, the screen remains blank white and no location dot.

Yes, I know I have location disabled in the app permissions... but it won't even show the 0,0 until you touch the screen.

[BruTilePersistentStorageReproWithAndroid.zip](https://github.com/Mapsui/Mapsui/files/4786498/BruTilePersistentStorageReproWithAndroid.zip)

**Comment by spaddlewit** [comment]
Some more investigating -- on iOS, it appears to be a threading issue, because if I lock the SQLite connection usage, it's working.

My other point about the screen starting off blank, even on Android, stands however.

Can you shed some light on how the IPersistentCache is disposed of when it is also IDisposable? When I click < Back at the top, the MbTileCache doesn't have its Disposed() method called, even when the map no longer exists. Do I need to call this manually? Any kind of best practice? Is it possible there are other Mapsui resources that are not being freed properly when this occurs?

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is fixed now.
