### ISSUE TITLE
Xamarin WPF shows black rectangle

### ISSUE THREAD

**Issue by CometSL9** [Mapsui/Mapsui#951]
Hello,

I am developing a mobile app with Mapsui. So far, so good.

After the update to Mapsui.Forms 2.0, everything wrent down. It just displays a black rectangle right where the map should appear. No error messages are thrown. When using the mouse wheel, it just flickers from background color to black (and stays at black).

Under Xamarin.iOS, the map is correctly rendered.

In the past, I was using an old version of mapsui and wrote a custom renderer for XAmarin WPF to use it (just encapsulates Mapsui.UI.Wpf.MapControl). When using a custom renderer now, it clears the whole screen and throws away the whole content (including parents).

Any guesses?

**Comment by pauldendulk** [comment]
There have been many changes from version 1 to 2, it is hard to tell what is going on here. Perhaps it would be best to start with the samples in the [v2 branch](https://github.com/Mapsui/Mapsui/tree/2.0) and get something working from there.

I do not understand this part: "it clears the whole screen and throws away the whole content (including parents).".

**Comment by CometSL9** [comment]
Hi Paul, 

A pure C# WPF application (without Xamarin) works - with Skia and WPF renderer, I have checked that.

Regarding the last part: That means, that as soon as I include a Mapsui.UI.Forms.MapUIView with my custom renderer in a Xamarin.Forms ContentPage, the whole page content (including other Views) will not be shown (=white).

When I find some time, I'll take the full repo (instead of the NuGet package and debug it step by step.

**Comment by pauldendulk** [comment]
Okay, let me know if you have some more specific information. 

2.0 does have a lot of breaking changes so I do not expect it to work with every custom renderer. There still may be a bug in there and perhaps we could provide a better exception.

**Comment by CometSL9** [comment]
Hi Paul,

Today, I had the chance to test it again. With the newest Xamarin.WPF, everything works again. So, dont mind.
