### ISSUE TITLE
Final fling events

### ISSUE THREAD

**Issue by mhardingham** [Mapsui/Mapsui#953]
I've recently done some widget work that required rendering after a zoom in/out or a fling.  There are events invoked when zoom in/out has finished but nothing for a fling.  After digging in the code base, I found the FlingFinal method.  Rather than it doing nothing, as per comment in code, do you think you could look at invoking a navigated event like the zooms?

private void FlingFinal(AnimationEntry entry)
{
   Navigated?.Invoke( this, ChangeType.Discrete );
}

**Comment by pauldendulk** [comment]
We are rewriting the animations for 3.x and there are no plans for improved animations in 2.x. The way something like this should be implemented in 3.x is by using a specific Easing function.
