### ISSUE TITLE
WmsProvider swallows errors silently

### ISSUE THREAD

**Issue by stevenengland** [Mapsui/Mapsui#955]
Hi Mapsui team, thank you for your very useful work.
My setting: WPF desktop, .NET 4.7
Today I experienced the following behavior (steps to reproduce it):

- use the WmsSample from the samples repo
- slightly change the WmsProvider
- set ContinueOnError to false
- set url to server that needs authentication
- provide credentials

            const string wmsUrl = "urlToRestrictedContent";

            var provider = new WmsProvider(wmsUrl)
            {
                ContinueOnError = false,
                TimeOut = 20000,
                CRS = "EPSG:25832",
                Credentials = new NetworkCredential("user", "pass"),
            };
            provider.AddLayer("someExistingLayer");
            provider.SetImageFormat(provider.OutputFormats[0]);
            return provider;
That works fine if the user and pass are set correct. If authentication or anything else fails and the ContinueOnError option is set, the error is silently swallowed by the ImageLayer.StartNewFetch method, that runs a Task in a fire and forget way.
The call stack is:

- ImageLayer.StartNewFetch
- FeatureFetcher.FetchOnThread
- WmsProvider.GetFeaturesInView
- WmsProvider.TryGetMap

Here it says

            catch (Exception ex)
            {
                if (!ContinueOnError)
                    throw (new RenderException("There was a problem while attempting to request the WMS", ex)); // <-- never reaches the calling party to handle that error
                Trace.Write("There was a problem while attempting to request the WMS" + ex.Message);
            }

As far as I can see there is no way to handle that error (prompt the user for credentials or at least tell him that something went wrong.

If I play around with the OsmSample I am able to handle errors by subscribing to the map.DataChanged event. That event and no other is fired in the WmsProvider scenario. Do I miss something or is there really no way to handle errors in that case?

Thank you in advance!

**Comment by pauldendulk** [comment]
Thanks, that's a bug. Good exception handling is important. I will take a look.

**Comment by pauldendulk** [comment]
I fixed this one and added test for it. The exception is now passed out on as argument in OnDataChanged as is done with tiles. Your analysis was very helpful, Thanks.
