### ISSUE TITLE
Question：Add Point Feature with symbol style always add a circle automaticly

### ISSUE THREAD

**Issue by daxiangxi** [Mapsui/Mapsui#956]
I Create a WritableLayer and add Point Feature with specify symbol using below codes，the result always add a circle automatic，         
   var feature = new Feature { Geometry = pt};           
            var imageStream = EmbeddedResourceLoader.Load("Images.home.png", typeof(CommGX.MySymbolPool));
            SymbolStyle sym = new SymbolStyle
            {
                BitmapId = BitmapRegistry.Instance.Register(imageStream),
                SymbolOffset = new Offset { Y = 64 },
                SymbolScale = 0.25
            };
            feature.Styles.Add(sym);
            _curLayer.Add((IFeature)feature);

the result like this：
![image](https://user-images.githubusercontent.com/5284880/85952293-b7ebaf80-b99a-11ea-8804-6f5a854b5a42.png)

if I specify the symbol to the layer，the result is ok， like this：
![无标题](https://user-images.githubusercontent.com/5284880/85952474-2a10c400-b99c-11ea-862c-3d4d8cdfe17d.png)

but I want to specify each Point Feature symbol manually, because the symbols In this Layer maybe Various, how can i solve it? can anyone help?

**Comment by daxiangxi** [comment]
solved，set the layer's style with null will be ok, if not set, layer's default style is a circle symbol and will automatic add to each feature's symbol, as seen above.

**Comment by pauldendulk** [comment]
Thanks for giving feedback and closing your own issue. This is also added in the FAQ now https://mapsui.com/documentation/faq.html#how-can-i-get-rid-of-there-white-dots-or-black-lines
