### ISSUE TITLE
Shapefile layer optimizations

### ISSUE THREAD

**Issue by ondrasvoboda** [Mapsui/Mapsui#958]
Hi,
I've implemented shapefile layer based on ShapefileSample. I have set MaxVisible resolution for the layer and noticed that even if viewport resolution is higher and the layer is hidden function ShapeFile.GetFeaturesInView is still beeing called when panning/zooming - causing some delays when having big shapefile. I think there is no need to call this function when the layer is not being drawn anyway. Isn't that a bug?

Also when zooming with mouse wheel the same function as being called multiple times, it has something to do with zoom animation. Couldn't this be also reduced = called once in the end of the animation? Or disable the animation at all?

Thanks!

**Comment by pauldendulk** [comment]
Thanks. Looks like a bug.

I can reproduce this in the ShapeFileSample when I set the MaxVisible on the RasterizingLayer. The RasterizingLayer fetching ignores the MaxVisible.

I can not reproduce this when I set the MaxVisible on the Layer that is wrapped inside the RasterizingLayer. For you this may be a workaround. 

Looking at the code the sample problem exists if you use the Layer without the RasterizingLayer. The layer also ignores MaxVisible.

**Comment by ondrasvoboda** [comment]
This is correct - I have layer NOT wrapped in RasterizingLayer. The RasterizingLayer wrapper doesn't work for me - my shapefile is another CRS then the map and it is not projected correctly when wrapped in RasterizingLayer. Without wrapper projection works. Maybe another bug?

**Comment by ondrasvoboda** [comment]
What about the mouse wheel zooming? Do you have an idea how to optimize it?

**Comment by pauldendulk** [comment]
> What about the mouse wheel zooming? Do you have an idea how to optimize it?

I am not sure if I understand your question. The fix should be to check MaxVisible before fetching the data. This will fix it for all situations, including mousewheel.

**Comment by ondrasvoboda** [comment]
The mouse wheel issue is not connected to MaxVisible.
I've noticed that data are fetched multiple times during one mouse wheel operation.

**Comment by pauldendulk** [comment]
> The mouse wheel issue is not connected to MaxVisible.
> I've noticed that data are fetched multiple times during one mouse wheel operation. Which is causing delays with big shapefiles.

There is a delayer in there so not every mousewheel tick is fetched, but in the release/2.0 branch I see 3 fetches even on 1 tick. So this can be improved.

**Comment by pauldendulk** [comment]
I created a separate issue for the mousewheel fetch problem. https://github.com/Mapsui/Mapsui/issues/962

I expect this will not be improved in v2. Your best option is probably to copy the Layer and Delayer to adjust it to your needs. 
change to this on line 41:
```private int _fetchingPostponedInMilliseconds = 1000;```
In Delayer.cs delete the 'action()' call on line 44.

**Comment by pauldendulk** [comment]
Oh, I forgot. There is a Layer.FetchingPostponedInMilliseconds you could set to 1000 to reduce the requests on mousewheel.

**Comment by pauldendulk** [comment]
> Oh, I forgot. There is a Layer.FetchingPostponedInMilliseconds you could set to 1000 to reduce the requests on mousewheel.

With the next release this will be changed to 
Layer.Delayer.MillisecondsToWait.

**Comment by ondrasvoboda** [comment]
Works fine, thanks!
