### ISSUE TITLE
How to add Layers from WMS request into a map

### ISSUE THREAD

**Issue by NenkoPakov** [Mapsui/Mapsui#960]
I realy like Mapsui and i want to create Xamarin mobile app with map and to add on it two layers from this "http://anta.nat.bg:8080/cgi-bin/mapserv.exe?map=/ms4w/maps/map.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=bnd_lines,ot&STYLES=&SRS=EPSG:7801&BBOX=320471,4724240,323127,4730190&WIDTH=400&HEIGHT=300&FORMAT=image/png" 
request.
I am trying from 2 deys and can't do it. My target is to can select object from map and with getFeatureInfo to get object properties.
Many thanks!

**Comment by pauldendulk** [comment]
This is not fully worked in Mapsui at the moment. There are two routes you could go. 

Use BruTile's WMS support. It is cross platform but has no feature info, you have to write this yourself. See the sample 'WMS called tiled' under 'data'.

Use the desktop support. It is not cross platform. It does have feature support. There are two samples but I just notices both services are down. See samples under 'desktop'.
