### ISSUE TITLE
SkiaSharp update in the NuGet package

### ISSUE THREAD

**Issue by gattila** [Mapsui/Mapsui#964]
Hello,

The current NuGet version supports  SkiaSharp.Views.Forms (>= 1.68.2.1 && < 1.69.0), but the current Skia version is 2.80.0.
Is there any way to create upgraded version of the package which is supports the current version of Skia ?

**Comment by gattila** [comment]
Ps. If possible please update the BruTile.MbTiles dependency too.

**Comment by pauldendulk** [comment]
> Hello,
> 
> The current NuGet version supports SkiaSharp.Views.Forms (>= 1.68.2.1 && < 1.69.0), but the current Skia version is 2.80.0.
> Is there any way to create upgraded version of the package which is supports the current version of Skia ?

I think so. If to see if that's not too big a change.

**Comment by pauldendulk** [comment]
> Ps. If possible please update the BruTile.MbTiles dependency too.

Yes, that will be part of a new release.

**Comment by gattila** [comment]
Thank you very much, especially the fast response!

**Comment by pauldendulk** [comment]
This is now been released as 3.0.0-alpha.1, I don't expect a update in v2.
