### ISSUE TITLE
Grouping features

### ISSUE THREAD

**Issue by VladGluschenko** [Mapsui/Mapsui#965]
Good day. Is it possible to combine several features(points, lines) into a group on a map layer when scaling? If so, tell me where I can find an example (possibly a specific file in the mapsui project). I'll be very thankful

**Comment by pauldendulk** [comment]
The only form of grouping is the stackedLabels. It shows one label stack for all points in the group. The group is drawn in a box. The positions of the points are still the original positions. For another use case you might one to present them as one point. This is not possible yet in Mapsui.

A possible workaround is to create your own IProvider (DataSource), which has the original provider as input, and do clustering there. You have to write your own code for clustering.

This question has come up before so perhaps it helps to search in the issues.

**Comment by jean-gblr** [comment]
Hello, im also looking into doing this. If you guys find any articles or materials that would help us in this making please comment :D
