### ISSUE TITLE
StackedLabel

### ISSUE THREAD

**Issue by VladGluschenko** [Mapsui/Mapsui#968]
Good day everyone. I use StackedLabel from source examples Mapsui. 
![image](https://user-images.githubusercontent.com/32134319/88633231-60398480-d0bd-11ea-92e7-f9b1c84e3551.png)
I am interested in drawing this without circles. I wanna just rectangular outline. Сan anyone know how to implement this? below is some of the code to create style.
![image](https://user-images.githubusercontent.com/32134319/88633617-ebb31580-d0bd-11ea-8ae8-7af00bd829c5.png)

**Comment by pauldendulk** [comment]
I understand this is confusing. The VectorStyle applies to all features in the Layer, which consists of the points and the rectangles added as polygon. You could filter out the points within the GetStyle method of the ThemeStyle. So you need to replace the VectorStyle with a ThemeStyle.

**Comment by pauldendulk** [comment]
@VladGluschenko Did you manage to solve this?

**Comment by VladGluschenko** [comment]
I have postponed this question for now. But I'll get back to this soon
