### ISSUE TITLE
White screen Issue with MapsUI.forms for Android

### ISSUE THREAD

**Issue by MarianHristov92** [Mapsui/Mapsui#969]
In my company project we have setup mapsui in our xamarin forms app. We found the strange behaviour. If you are on the map and then you turn the phone in standby, then you turn it off the map is shown in white screen. 
Steps to reproduce: 
    
1. Create a simple stack layout with mapsui included:
    
2. Start the app

3. Wait for 30-60 seconds phone to go standby

4. Turn on the phone and get in the app

5. You will see a white screen.

Has anyone encountered this issue or there is a workaround that I can use ?

**Comment by pauldendulk** [comment]
Which version do you use?

What happens if you zoom to the full extent after it has gone white?

**Comment by pauldendulk** [comment]
Closing, outdated, not enough information.
