### ISSUE TITLE
Navigate and keep zoom level/how to get zoom level

### ISSUE THREAD

**Issue by trevelyanuk** [Mapsui/Mapsui#970]
I've tried looking for this a fair bit, but I can't find anything about it in the documentation or API..

I essentially want to navigate to a specific place but keep the current "zoom level" whilst doing so. I thought perhaps I could get the current resolution of the mapview, or find the current zoom control's associated resolution index, but that doesn't appear to be the case.. or at least, I haven't found it.

Is there a nice way to do this, or would I have to use the current bounds and translate it by the difference between the current and new coordinates? I'd rather just see if there was this functionality already before going down a random hole. 

Alternatively, is it a good candidate for V3?

**Comment by pauldendulk** [comment]
Navigator.CenterOn is not what you are looking for?

**Comment by trevelyanuk** [comment]
100% is what I am looking for - thanks for pointing it out, I was just looking for the entirely wrong thing and just didn't even see it (or think of using that word, I guess!)..

Apologies for that, hopefully if someone else searches closed issues for this, they won't make the same mistake.. 😂
