### ISSUE TITLE
Xamarin Forms Quick Start Guide steps don't work on Android

### ISSUE THREAD

**Issue by lachlanwgordon** [Mapsui/Mapsui#974]
The steps in the [quick start guide](https://mapsui.com/documentation/getting-started-xamarin-forms.html) work fine on iOS but when you try to run it on Android the map is blank.

This is caused by a strange issue with user agents as discussed in #668 

Rather than setting up the Tile Layer in the user code, it's much easier to use the one in [OpenStreetMaps.cs](https://github.com/Mapsui/Mapsui/blob/945ce990d130ca7ec3ca93db734b58a88798c7df/Mapsui/Utilities/OpenStreetMap.cs).

**Comment by pauldendulk** [comment]
Fantastic, you fixed the issue before I had read it myself 😄
