### ISSUE TITLE
[Bug] Double tap always zooms in

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#977]
I would expect the same behavior as on other maps apps like Apple Maps and Google Maps (first double tap zoom in, second zoom back out). But currently, Mapsui is always zooming in on a double tap and even ignores the zoom limits set. Tested with iOS in a TestFlight version using Mapsui 2.0.3.

**Comment by pauldendulk** [comment]
How could I test this? Can I use older iPads for this?

**Comment by pauldendulk** [comment]
I don't think we should change the behavior of the second double tab in v2, but perhaps in v3.

Not respecting the zoomlimits is a bug that should be fixed.

**Comment by Sebastian1989101** [comment]
Just as a idea: Maybe it should just let the developer decide what should happen with a double tap on the map. I know that there is already a single, double and long tap for the placed icons on the map - maybe something like this can be a great idea for the map itself so that the behavior can be overwritten if needed. In this case it also would not matter if the default is always zoom in or zoom in/out or maybe always zoom out or what so ever because it can be changed easily.

**Comment by radderz** [comment]
@Sebastian1989101 The user can already override how it works for the Xamarin.Forms MapControl by implementing the event handler for double tap. I can't remember if this was implemented everywhere exactly the same but the intention is for the user to be able override the feature.

`public event EventHandler<TappedEventArgs> DoubleTap; and setting the tap to handled.`


```
private bool OnDoubleTapped(Geometries.Point screenPosition, int numOfTaps)
        {
            var args = new TappedEventArgs(screenPosition, numOfTaps);

            DoubleTap?.Invoke(this, args);

            if (args.Handled)
                return true;

            var eventReturn = InvokeInfo(screenPosition, screenPosition, numOfTaps);

            if (eventReturn?.Handled == true)
                return true;

            // Double tap as zoom
            return OnZoomIn(screenPosition);
        }
```

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
