### ISSUE TITLE
Double tap on map in WPF application not zooming in 

### ISSUE THREAD

**Issue by anushabasavaraj92** [Mapsui/Mapsui#979]
The map doesn't zoom in when I double tap at a position on map in WPF Desktop application. Should it be implemented ?

**Comment by pauldendulk** [comment]
Not sure. Most important thing is that it should be possible to implement. So if you had your own handler to to OnMouseDown it should be possible. Is it? I think it is.

And then there is the question if the user really wants it like this. In the current UWP implementation the double tab is feature info request. Perhaps this should be configurable?

How would you implement it? I don't see a native event for it in WPF.

It this any different in .NET 3.0?

**Comment by pauldendulk** [comment]
This is one of the things looked into when moving more of the UI logic to one code base.
