### ISSUE TITLE
Is Mapsui compatible with .Net core 3.1?

### ISSUE THREAD

**Issue by anushabasavaraj92** [Mapsui/Mapsui#982]
Hi,

I am using .Net core for WPF desktop application and am not able to use the Mapsui mapcontrol. Is Mapsui compatible with .NET core?

**Comment by pauldendulk** [comment]
No, it isn't. There has been another question about this, please look here:
https://github.com/Mapsui/Mapsui/issues/917

It does suggest a possible solution.
