### ISSUE TITLE
Add Rotate and RotateWithMap to SymbolStyle

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#983]
@leo-costa Yes, this is an addition that makes sense. Rotate and RotateWithMap could be seen as separate issues but for the feature described above you will need both. 

This is the current functionality.

![image](https://user-images.githubusercontent.com/963462/90801423-294e3b80-e316-11ea-98cd-7f22eb5e65a7.png)

The labels don't rotate. Which is what you want in most cases.

## RotateWithMap 
RotateWithMap should be a boolean. Should default be false. If true the label will rotate with the map, so in the screenshot above the labels would be rotated 45 degrees. Not a common use case in itself.

## Rotate
Individual rotation of the label. If RotateWithMap is false they will simply be rotated relative to the top of the form. If RotateWithMap is true they will be rotated relative to the north of the map.

_Originally posted by @pauldendulk in https://github.com/Mapsui/Mapsui/issues/876#issuecomment-677781846_

**Comment by leo-costa** [comment]
Since there is no way to currently extend and override the `LabelRenderer` my solution was to copy that class and modify line 217 to be like this 

```
 target.Save( );
 target.RotateDegrees((float)style.Rotation, x, y);
 target.DrawText(text, drawRect.Left, drawRect.Top + baseline, paint);
 target.Restore( );
```

This is the most naive approach where line wrapping is not being taken into consideration. The `style` here is a custom style derived from `LabelStyle` that add `Rotation` property.

**Comment by pauldendulk** [comment]
This was for your own needs where you had to work with the existing version, right? For the PR the modifications can be in the LabelRenderer and the LabelStyle. The rotation itself can be something simple like RotateDegrees. Save and Restore make take some extra render time, perhaps you don't have to use it as part of the LabelRenderer.

**Comment by leo-costa** [comment]
Yes, this was for my own need. The PR would modify the `LabelRendered` and `LabelStyle`.  Is there also a possibility to allow to extend and override a "built in" renderer instead of creating one from scratch using `ISkiaStyleRendered` ? Sometimes most of the capabilities are already on the built in ones and small mod may be necessary.

**Comment by pauldendulk** [comment]
> Is there also a possibility to allow to extend and override a "built in" renderer instead of creating one from scratch using ISkiaStyleRendered ? Sometimes most of the capabilities are already on the built in ones and small mod may be necessary.

I am not a fan of inheritance hierarchies. To allow more code reuse I would rather rewrite the current renderer towards more smaller statics methods that could be called from anywhere.

Other reasons for refactoring the renderer are:
- Make everything more in line with the StyleRenderer setup that was introduced later.
- Optimize for performance. We should start measuring performance. I am sure that there is a lot that could be improved.

**Comment by pauldendulk** [comment]
This was implemented.

**Comment by Matt-17** [comment]
Hello @pauldendulk,
sorry for late reply. I'm a bit confused about this solution (I'm new to Mapsui and using 4.19). 

When I create a feature, I can rotate any symbol with SymbolStyle.SymbolRotation now. But the text I'm adding with a LabelStyle does not rotate and there is no Rotaten Property. Is there anything I missed?

**Comment by pauldendulk** [comment]
The LabelStyle does not implement RotateWithMap. It makes sense to add this, but if it is added it will be in V5. 

The CalloutStyle does implement a RotateWithMap perhaps you could use this as a workaround.

**Comment by Matt-17** [comment]
Thank you. I'm still trying to understand the system. But I like this package and looking forward to 5
