### ISSUE TITLE
How to add transport layer?

### ISSUE THREAD

**Issue by JawadJaber** [Mapsui/Mapsui#984]
I have noticed that Open Street Map uses different languages per countries, (for example Saudi Arabia and all its cities are in Arabic).
Now I found a possible work around to add the english words by using the transport layer
https://www.openstreetmap.org/#map=5/24.147/39.595&layers=T
but I could not find the correct method to include this in my WPF application.

**Comment by pauldendulk** [comment]
In the basic OpenStreetMap the labels are part of the rasters. To be able to switch between languages you need a vector representation (or separated tile sources for all languages but that is a solution that would consume a lot of space).
