### ISSUE TITLE
[Bug] [UWP] [Xamarin.Forms] Disable mouse wheel zoom/pan

### ISSUE THREAD

**Issue by BurkusCat** [Mapsui/Mapsui#985]
I have a Xamarin.Forms project using Mapsui running on UWP. I have enabled Panlock: `mapView.PanLock = true;` which generally seems to be working great. I want the map to be zoomable still so I have not changed anything to do with that. The issue is that whenever you use the mouse wheel on the map, it pans and zooms to the cursor which completely overrides the pan lock.

Is there anything I can do to disable mouse wheel events? Or should panlock be prevent this from happening?

I'm not sure if it is relevant, but the map view I have is within a ScrollView.

**Comment by radderz** [comment]
This sounds like a bug where the zoom is occuring at the mouse location and ignoring panlock to just zoom at center.

**Comment by BurkusCat** [comment]
Is there any way I can disable the mousewheel from interacting with the Map control in the meantime? The center of the map is used to mark locations in my app and there are certain times I do want the user to be able to move the map & change it to the wrong locatio.n

**Comment by pauldendulk** [comment]
This fixed in 4.0. If mouse wheel is used during PanLock the center of the map remains the same. See the sample Navigation | PanLock, where Sao Paulo remains the center of the map when mouse wheel zooming.
