### ISSUE TITLE
Question: Padding around bounding box

### ISSUE THREAD

**Issue by BrianVance** [Mapsui/Mapsui#986]
Hi,
    I am trying to zoom on a live line drawn on the map while the user walks. So basically I am drawing the lines with a set of coordinates. After the line is drawn I want to zoom/focus on the area where the line was drawn (Zoom to bounds).

For that I am using, 

`map.Navigator.NavigateTo(new BoundingBox(lstLineAngles), ScaleMethod.Fit);`

where lstLineAngles are the array of lon/lats that form the line. This feature works great but I need some padding around the bounding box since currently the start & end of the lines stick to the screen.

Any ideas on how I can achieve this?

Thanks,
Brian Noronha

**Comment by BrianVance** [comment]
I found another workaround this..

**Comment by NguyenThang1996** [comment]
> Tôi đã tìm ra một giải pháp khác cho vấn đề này..

can u share your solution?
