### ISSUE TITLE
Extend the already drawn linestring geometry

### ISSUE THREAD

**Issue by anushabasavaraj92** [Mapsui/Mapsui#987]
I am using an animated layer to draw a real-time trajectory on the map in WPF. But, to draw the trajectory, I have to keep all the points from the start of the trajectory to the current point of the trajectory in memory for the linestring geometry feature. Is there a way to just add to the already drawn line instead of creating a feature geometry every time a new point is obtained?

**Comment by pauldendulk** [comment]
I have not worked with a setup as yours so I do not have a specific solution. Perhaps it helps if you look at the project Mapsui.Samples.Wpf.Editing. It adds points to a geometry while drawing, perhaps you can use this mechanism.
