### ISSUE TITLE
Feature search

### ISSUE THREAD

**Issue by VladGluschenko** [Mapsui/Mapsui#988]
How can i find out if there are objects(Features) in a certain area and get the coordinates of that object. I click on the map. Find the closest object within the radius of that click. Very grateful for your reply in advance.

**Comment by radderz** [comment]
On option would be to loop through the features you have added to the map (I assume you maintain these in a list/dictionary). Get the map location based on the click and compare with the search box based on that click location. If you have many items, you'll need to use an index, which RTree indices are great for spatial data.
