### ISSUE TITLE
Getting point from lon lat not working as expected

### ISSUE THREAD

**Issue by frostblooded** [Mapsui/Mapsui#990]
On open street map I am looking at this node https://www.openstreetmap.org/node/6260778311. There it says that its coordinates are 42.6987510, 23.3155870. I tried to create a point with them and navigate to it, but the map centers on a completely different spot of the world (somewhere in Africa). I realized that maybe I need to do a conversion on the coordinates, so I tried

```c#
Mapsui.Geometries.Point point = SphericalMercator.FromLonLat(42.6987510, 23.3155870);
MyMapControl.Navigator.NavigateTo(point, 10000.0);
```

Unfortunately, this didn't produce any success either. Now it navigates to a different point, but it is in Saudi Arabia and still nowhere near the goal. Any ideas what is going on?

I assume I am missing something very simple here, but I can't find out what.

**Comment by frostblooded** [comment]
Apparently the lon and lat have swapped places, so the right code is

```
Mapsui.Geometries.Point point = SphericalMercator.FromLonLat(23.3155870, 42.6987510);
MyMapControl.Navigator.NavigateTo(point, 1.0);
```

**Comment by pauldendulk** [comment]
The LonLat order is has been causing for decades. Mapsui has choosen to use the X, Y order, like most other coordinate systems. The method was names LonLat to indicate this order, first the longitude (x) then the latitude (y).
