### ISSUE TITLE
IFeatureProvider interface

### ISSUE THREAD

**Issue by JKNAUG** [Mapsui/Mapsui#992]
Hi all,

is there any reason why the IFeatureProvider interface lives in the assembly Mapsui.UI.Forms? I have written an own FeatureProvider, originally for Xamarin.Forms, and now I want to reuse it for UWP. Said interface is my missing link at the moment, since I don't want to reference the Forms assembly in my shared library.

**Comment by JKNAUG** [comment]
Add: the same goes for ObservableCollectionProvider, it's in the same assembly.

**Comment by pauldendulk** [comment]
Most of this functionality also exists in the more basic classes. Those Forms classes were added to work with Forms' objects in the renderer. The preferred way is to use the IFeature, those work for all platforms, also possible future platforms.

**Comment by pauldendulk** [comment]
If you look at Mapsui.Samples.Wpf, there are many samples there. This functionality also exists in Forms but does not depend on Forms. My advice is to use this functionality.
