### ISSUE TITLE
Big raster performance issues

### ISSUE THREAD

**Issue by ondrasvoboda** [Mapsui/Mapsui#993]
I have big rasters (5000x5000 px) which I need to show in the map. Positioning works fine, but I see serious performance issues when more then one raster is added, or even when I have one raster and OSM layer and I try to move or zoom the  map.

It can be easily reproduced by modifying SymbolsInWorldUnitsSample. Just replace netherlands.jpg with picture with size around 5000x5000. And try to move or zoom the map.
In this sample there is the raster twice in two features, if you remove one and disable OSM layer, performance is OK. The problem is only with skia renderer, with WPF it works fine.

Thanks for any help.

**Comment by ondrasvoboda** [comment]
Tested with 2000x2000 picture and event there performance is not good. I would say that problem is in SkiaSharp, can anybody confirm?
Workaround I can think of is to cut the big raster to smaller "tiles". Not sure if it works, but probably will give it a try, since I need this to work soon.
Or does anybody have some other ideas?

**Comment by ondrasvoboda** [comment]
So I've cut 5000x5000 raster to 100 tiles of size 500x500 and when drawn all together in a loop the performance is acceptable. Strange that drawing one big raster is too slow and when drawing the same in smaller parts it is so better.

**Comment by pauldendulk** [comment]
The best solution would probably be a tile piramide like use in mbtiles.
