### ISSUE TITLE
2nd layer not visible in Android

### ISSUE THREAD

**Issue by NoClue11** [Mapsui/Mapsui#994]
Hi, 
I've created as simple example and added OpenStreetMap as base layer with tile source:
`return new HttpTileSource(new GlobalSphericalMercator(),
                "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                new[] { "a", "b", "c" }, name: "OpenStreetMap",
                attribution: OpenStreetMapAttribution, userAgent: "OpenStreetMap in Mapsui");`
                
and adding OpenSeaMap sea marks as second layer:
`return new HttpTileSource(new GlobalSphericalMercator(),
                    "http://t1.openseamap.org/seamark/{z}/{x}/{y}.png",
                    name: "OpenSeaMap",
                    attribution: OpenStreetMapAttribution, userAgent: "OpenStreetMap in Mapsui");`
                
That works in UWP:
![upw](https://user-images.githubusercontent.com/48393256/95675832-5a324a80-0bba-11eb-9509-336caf338e9f.PNG)

but not with Android:
![android](https://user-images.githubusercontent.com/48393256/95675842-6c13ed80-0bba-11eb-86ab-d43f88c16f53.PNG)

Any idea what could be wrong? Using Mapsui.Forms 2.0.3

Best Regards,
Manfred

**Comment by pauldendulk** [comment]
There is no general limitation on Android in that respect. Perhaps there is an error that occurs while rendering on Android. Perhaps a resource that can not be found. The renderer logs its exception to the static logger perhaps you can use that to diagnose the problem. See:

https://mapsui.com/documentation/how-to-work-with-mapsui.html#logging

**Comment by radderz** [comment]
> Hi,
> I've created as simple example and added OpenStreetMap as base layer with tile source:
> `return new HttpTileSource(new GlobalSphericalMercator(), "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", new[] { "a", "b", "c" }, name: "OpenStreetMap", attribution: OpenStreetMapAttribution, userAgent: "OpenStreetMap in Mapsui");`
> 
> and adding OpenSeaMap sea marks as second layer:
> `return new HttpTileSource(new GlobalSphericalMercator(), "http://t1.openseamap.org/seamark/{z}/{x}/{y}.png", name: "OpenSeaMap", attribution: OpenStreetMapAttribution, userAgent: "OpenStreetMap in Mapsui");`
> 
> That works in UWP:
> ![upw](https://user-images.githubusercontent.com/48393256/95675832-5a324a80-0bba-11eb-9509-336caf338e9f.PNG)
> 
> but not with Android:
> ![android](https://user-images.githubusercontent.com/48393256/95675842-6c13ed80-0bba-11eb-86ab-d43f88c16f53.PNG)
> 
> Any idea what could be wrong? Using Mapsui.Forms 2.0.3
> 
> Best Regards,
> Manfred

Is it intended to use http for the second layer?

**Comment by NoClue11** [comment]
Hi radderz - good catch. Using https solves the issue on Android. 
I just used the URL provided by the tile provider and http works with UWP. Seems that for whatever reason Android requires https.
Thanks,
Manfred
