### ISSUE TITLE
LabelRenderer TailTruncation index out of range

### ISSUE THREAD

**Issue by willy40** [Mapsui/Mapsui#999]
I have a label for example 'aaaaaaaaaaa' which has 11 characters.

style for this label:
```csharp
            new LabelStyle
            {
                Text = label,
                BackColor = new Brush(Color.Transparent),
                ForeColor = Color.White,
                Halo = new Pen(Color.Black, 2),
                HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Left,
                VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Center,
                MaxWidth = 10,
                WordWrap = LabelStyle.LineBreakMode.TailTruncation,
                Offset = new Offset(0, 15, false),
                MaxVisible = 400
            };
```
labelrenderer at line 151 

```csharp

if (style.WordWrap == LabelStyle.LineBreakMode.TailTruncation)
  {
      var result = text.Substring(0, (int)style.MaxWidth + 2);  // <-- here is exception
      //......rest of the code
```

I'm suggesting add check of the text length:

```csharp
               if (style.WordWrap == LabelStyle.LineBreakMode.TailTruncation)
                {
                    var truncateLength = (int)style.MaxWidth + 2;

                    if (text.Length > truncateLength)
                    {
                        var result = text.Substring(0, truncateLength);

                        while (result.Length > 1 && Paint.MeasureText(result + "...") > maxWidth)
                            result = result.Substring(0, result.Length - 1);
                        text = result + "...";
                    }

                    Paint.MeasureText(text, ref rect);
                    drawRect = new SKRect(0, 0, rect.Right - rect.Left, rect.Bottom - rect.Top);
                }
```

the same is happening at line 138:

```csharp
       if (style.WordWrap == LabelStyle.LineBreakMode.HeadTruncation)
	{
		var result = text.Substring(text.Length - (int) style.MaxWidth - 2);
		while (result.Length > 1 && Paint.MeasureText("..." + result) > maxWidth)
			result = result.Substring(1);
		text = "..." + result;
		Paint.MeasureText(text, ref rect);
        	drawRect = new SKRect(0, 0, rect.Right - rect.Left, rect.Bottom - rect.Top);
	}
```

version 2.0.3

**Comment by pauldendulk** [comment]
What platform?

I do not get the exception in WPF
![image](https://user-images.githubusercontent.com/963462/97724285-04700480-1acd-11eb-9273-6f0420e5e208.png)

**Comment by willy40** [comment]
winforms and my own mapcontrol

exception occurs when text is shorter then maxWidth

in my example MaxWidth = 10 and label has 9 characters

I think I didn't explain correctly this situation elier, sorry

**Comment by pauldendulk** [comment]
I created this branch to try to reproduce your exception but failed so far. Perhaps you can modify this branch to reproduce the exception. https://github.com/Mapsui/Mapsui/blob/research/try-to-reproduce-issues-999/Samples/Mapsui.Samples.Common/Maps/LabelsSample.cs

**Comment by willy40** [comment]
uhmmm I can't push my commit :(
but i reproduced exception:

`private static IFeature CreateFeatureWithTailTruncation()
        {
            var featureWithColors = new Feature { Geometry = new Point(8000000, 2000000) };
            featureWithColors.Styles.Add(new LabelStyle
            {
                Text = "16:TPP-DG14",
                BackColor = new Brush(Color.Transparent),
                ForeColor = Color.White,
                Halo = new Pen(Color.Black, 2),
                HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Left,
                VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Center,
                MaxWidth = 10,
                WordWrap = LabelStyle.LineBreakMode.TailTruncation,
                Offset = new Offset(0, 15, false),
                MaxVisible = 400
            });
            return featureWithColors;
        }`

zoom very close to this label, enable break at line 151 in labelrenderer.cs /skia renderer/

![image](https://user-images.githubusercontent.com/15885968/97797197-6d659280-1c1b-11eb-86f4-7f7a78a262f9.png)

**Comment by pauldendulk** [comment]
> uhmmm I can't push my commit :(
You would have to fork it first.

> but i reproduced exception
Now I can too! great.

**Comment by pauldendulk** [comment]
I will accept a PR to prevent this.

I was hoping to fix this quickly but it is complicated. The MaxWidth is actually a double that indicates font size, while the logic deals with character indexes. It looks like it needs a bigger rewrite than just a check. This is no something I can dig into righ now. I will accept a PR, also if it is just a simple check.

**Comment by pauldendulk** [comment]
This was reported before the first beta of v4. Assuming this is not relevant anymore.
